### ISSUE TITLE
Relay Streams Not Showing Port (404 Error)

### ISSUE THREAD

**Issue by JoshRiley** [AzuraCast/AzuraCast#2224] opened 2019-12-16 21:57 UTC
**Using Docker installation method**
Yes

**Host Operating System**
CentOS 7

**Describe the bug**
The relay streams no longer have listen.stationname.tld:8000/mountname (specifically the port at the end) causing 404 errors when trying to click on said mount point. The URL with the port 8000 at the end still works, but does not allow for people to listen on the public page provided through azuracast.

**Screenshots**
https://i.imgur.com/zK8mmZy.png
https://i.imgur.com/CenBqi2.png
(check URL in each case)

**Comment by JoshRiley** [comment] 2019-12-21 21:27
Any updates on this?

**Comment by SlvrEagle23** [comment] 2019-12-23 06:50
@JoshRiley Are you specifically using the AzuraRelay tool to set up and manage the relays?

If so, that should definitely be registering the port number.

Let me know whether you're setting up the remote relays manually or via AzuraRelay and I can diagnose the issue further.

**Comment by JoshRiley** [comment] 2019-12-24 17:02
It was working fine with no additional software when we first set it up. It appeared to have just changed somehow overnight, nobody touched the server. 

I am not familiar with the AzuraRelay tool.

**Comment by SlvrEagle23** [comment] 2019-12-27 17:29
@JoshRiley Where are you seeing the link that's missing the port number? On the station's profile? In API responses? etc.

We haven't made any changes to that portion of the code in quite a while, so it's rather unusual that your relay would suddenly lose its port number listing overnight.

**Comment by JoshRiley** [comment] 2019-12-30 18:56
I am seeing it underneath "Streams" on the station dashboard. I am also quite shocked that it changed, I wasn't expecting it either.

**Comment by SlvrEagle23** [comment] 2020-01-11 18:33
@JoshRiley Sorry I'm just now getting back to this, but I can't reproduce this locally on my installation...a test relay still shows the port just like normal on the profile pages:

![2020-01-11 12_29_48-(Development) Edit Remote Relay - AzuraCast](https://user-images.githubusercontent.com/6744885/72208900-32b52280-346e-11ea-9270-9b64c056f7be.png)

![2020-01-11 12_30_25-(Development) Profile - AzuraCast](https://user-images.githubusercontent.com/6744885/72208901-33e64f80-346e-11ea-90aa-3a8a4c66d5e0.png)

I'm not sure specifically what happened with your setup or how to reproduce it. Do you have any more information that could help with debugging? If you manually set the port number back on the relay listening URL does it show the port on the profile after saving changes?

**Comment by Vaalyn** [comment] 2021-04-23 09:50
Closing this since there has been no further responses for a very long time.

If this is still happening for someone please create a new issue and link to this one here.

**Closed by Vaalyn** 2021-04-23 09:50 UTC
Labels: bug, in progress
