### ISSUE TITLE
Install Failure

### ISSUE THREAD

**Issue by williambatson** [AzuraCast/AzuraCast#1308] opened 2019-03-15 12:26 UTC
New install - replaced traditional install with fresh Docker install
Ubuntu 16.04 
*Made sure curl, sudo and git were installed (added git)

ran:
curl -L https://raw.githubusercontent.com/AzuraCast/AzuraCast/master/docker.sh > docker.sh
chmod a+x docker.sh
./docker.sh install

have repeated 2X with same result-  Any help please?

root@80849:~# ./docker.sh install
Docker does not appear to be installed. Install Docker now? [Y/n] y
# Executing docker install script, commit: cfba462
+ sh -c apt-get update -qq >/dev/null
+ sh -c apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
+ sh -c curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | apt-key add -qq - >/dev/null
+ sh -c echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable" > /etc/apt/sources.list.d/docker.list
+ sh -c apt-get update -qq >/dev/null
+ sh -c apt-get install -y -qq --no-install-recommends docker-ce >/dev/null
E: Sub-process /usr/bin/dpkg returned an error code (1)

Docker Compose does not appear to be installed. Install Docker Compose now? [Y/n] y
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   617    0   617    0     0    809      0 --:--:-- --:--:-- --:--:--   808
100 11.2M  100 11.2M    0     0  1972k      0  0:00:05  0:00:05 --:--:-- 2426k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13238  100 13238    0     0  28851      0 --:--:-- --:--:-- --:--:-- 28840
Writing default .env file...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    80  100    80    0     0    174      0 --:--:-- --:--:-- --:--:--   175
Creating default AzuraCast settings file...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1340  100  1340    0     0   2415      0 --:--:-- --:--:-- --:--:--  2414
Retrieving default docker-compose.yml file...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2920  100  2920    0     0   7309      0 --:--:-- --:--:-- --:--:--  7318
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

**Comment by Vaalyn** [comment] 2019-03-15 13:00
This seems like a compatibility problem between your Ubuntu installation and docker / docker-ce. When you execute `apt-get install -y --no-install-recommends docker-ce` you should see why the command fails. Can you try this and post the output here?

**Comment by williambatson** [comment] 2019-03-15 13:05
root@80849:~# apt-get install -y --no-install-recommends docker-ce
Reading package lists... Done
Building dependency tree
Reading state information... Done
docker-ce is already the newest version (5:18.09.3~3-0~ubuntu-xenial).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up docker-ce (5:18.09.3~3-0~ubuntu-xenial) ...
update-alternatives: warning: forcing reinstallation of alternative /usr/bin/dockerd-ce because link group dockerd is broken
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2019-03-15 15:05:11 EET; 8ms ago
     Docs: https://docs.docker.com
  Process: 16523 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
 Main PID: 16523 (code=exited, status=1/FAILURE)

Mar 15 15:05:11 80849.s.time4vps.cloud systemd[1]: Failed to start Docker Application Container Engine.
Mar 15 15:05:11 80849.s.time4vps.cloud systemd[1]: docker.service: Unit entered failed state.
Mar 15 15:05:11 80849.s.time4vps.cloud systemd[1]: docker.service: Failed with result 'exit-code'.
dpkg: error processing package docker-ce (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 docker-ce
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by Vaalyn** [comment] 2019-03-15 13:10
This seems to be a known issue with the docker installer when it's upgrading an existing docker installation. See [this issue](https://github.com/docker/for-linux/issues/567) on the docker repository for more information.

Can you try to restart docker manually by using `systemctl restart docker` and then retrying the AzuraCast installation?

**Comment by williambatson** [comment] 2019-03-15 13:18
Can you try to restart docker manually by using systemctl restart docker and then retrying the AzuraCast installation?             install failed - same result

**Comment by Vaalyn** [comment] 2019-03-15 13:19
If there is nothing else using docker on that machine I'd try removing the docker installation with `apt-get remove docker` to see if that resolves the problem

**Comment by williambatson** [comment] 2019-03-15 13:27
looks like that failed too:

root@80849:~# apt-get remove docker
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package 'docker' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up docker-ce (5:18.09.3~3-0~ubuntu-xenial) ...
update-alternatives: warning: forcing reinstallation of alternative /usr/bin/dockerd-ce because link group dockerd is broken
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2019-03-15 15:25:56 EET; 7ms ago
     Docs: https://docs.docker.com
  Process: 16781 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
 Main PID: 16781 (code=exited, status=1/FAILURE)

Mar 15 15:25:56 80849.s.time4vps.cloud systemd[1]: docker.service: Unit entered failed state.
Mar 15 15:25:56 80849.s.time4vps.cloud systemd[1]: docker.service: Failed with result 'exit-code'.
dpkg: error processing package docker-ce (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 docker-ce
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@80849:~#

I have already re-installed the OS twice and started over -  not sure what to do next

**Comment by Vaalyn** [comment] 2019-03-15 13:33
Please check if something docker related is already installed on your system by checking `apt list -a --installed`. This is most likely a problem with an existing docker installation or with the Ubuntu installation itself. Is the Ubuntu Version installed a modified version from your hoster or the original one from the Ubuntu website?

**Comment by williambatson** [comment] 2019-03-15 13:35
docker-ce/now 5:18.09.3~3-0~ubuntu-xenial amd64 [installed,local]

docker-ce-cli/now 5:18.09.3~3-0~ubuntu-xenial amd64 [installed,local]

these 2 show up listed as 'docker'

**Comment by Vaalyn** [comment] 2019-03-15 13:41
Try removing `docker-ce` and `docker-ce-cli` with `apt-get remove` and retry the installation. If it then still fails you Ubuntu version is likely modified and has some incompatibility with docker that needs to be resolved. If that is a version modified by your hoster please contact them and ask them what they modified and if they know how to get docker working there.

**Comment by williambatson** [comment] 2019-03-15 13:47
root@80849:~# apt-get remove docker-ce
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package docker-ce
root@80849:~# apt-get remove docker-ce-cli
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package docker-ce-cli

Fresh install Ubuntu 16.04 -  nothing from Azuracast loaded yet -  ran the above as they still show when I run apt-list -   so tried to remove them.

**Comment by Vaalyn** [comment] 2019-03-15 13:54
So `docker-ce` and `docker-ce-cli` are shown as installed but you are unable to remove them, is that correct?

**Comment by williambatson** [comment] 2019-03-15 13:56
yes -  shows on the list when i run apt-list
then says 'unable to locate'   when I run apt-get remove
**Just checked with my hoster...... no changes made, still the same Ubuntu 16.04.6 LTS as they have always offered.

**Comment by Vaalyn** [comment] 2019-03-15 14:01
I've had a quick look at the documentation of your hoster where they say they support docker installations and how to install it on their VPSs. There they install docker with an old name `docker.io`. Can you try `apt-get remove docker.io`?

I'm pretty sure that your hoster has somehow modified the default Ubuntu installation image since docker is not installed by default on Ubuntu.

**Comment by williambatson** [comment] 2019-03-15 14:02
root@80849:~# apt-get remove docker.io
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package 'docker.io' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

**Comment by Vaalyn** [comment] 2019-03-15 14:10
To be completely sure that we've made sure that everything relating to an old docker version is gone try this `apt-get remove docker docker-engine docker.io containerd runc` it's okay if this reports nothing is installed.

Then do `apt-get update` after that and install all prerequisites of docker with:
```
apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common
```

Then add the GPG key of the docker repo `curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -`.

Then setup the stable repository of docker with this command:
```
add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
```

Then update the repo cache again with `apt-get update` and finally try `apt-get install docker-ce docker-ce-cli containerd.io`.

If the installation of docker still fails it's pretty clear that the problem is coming from the Ubuntu image your hoster supplies you with.

**Comment by williambatson** [comment] 2019-03-15 14:15
yep you're right - did all you said  (thank you a ton btw - much appreciated)
after all that - here's what we have:

 Process: 19600 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
 Main PID: 19600 (code=exited, status=1/FAILURE)

Mar 15 16:13:34 80849.s.time4vps.cloud systemd[1]: Failed to start Docker Application Container Engine.
Mar 15 16:13:34 80849.s.time4vps.cloud systemd[1]: docker.service: Unit entered failed state.
Mar 15 16:13:34 80849.s.time4vps.cloud systemd[1]: docker.service: Failed with result 'exit-code'.
dpkg: error processing package docker-ce (--configure):
 subprocess installed post-installation script returned error exit status 1

**Comment by Vaalyn** [comment] 2019-03-15 14:18
Maybe as an additional question to figure out where the problem is originating from. Which VPS line of your hoster are you using? I've read on their page that `We support Docker on our VPS server line.` and `Unfortunately we do not support Docker on our Container and Storage VPS’s.`. Which one are you using?

**Comment by williambatson** [comment] 2019-03-15 14:36
Just got off the line with them again -  THAT's the change.   I was running a traditional install there just fine.   The upgrade failed, so re-installing on Docker is a no go on that server.    Looks like one more thing to check prior to spinning up a VPS -    again, thank you for your help.   I switched to a new server - we'll see how that goes..... else it's VPS shopping time yet again.

**Comment by Vaalyn** [comment] 2019-03-15 14:42
Please give us a small note on if the installation worked on a VPS instance from them that should support docker so I can close this issue. Until then I'll let this issue stay open.

**Comment by SlvrEagle23** [comment] 2019-03-15 15:14
@Vaalyn Thank you for your help in figuring this one out. Seems like they're deliberately not supporting Docker for certain VPS tiers.

@williambatson If you don't mind sharing who your host provider is so we can anticipate this issue in the future if it happens, that would be appreciated. I can't seem to find it in the thread here.

**Comment by williambatson** [comment] 2019-03-15 15:17
that was it -  go ahead and close it -   once more thank you for your help, is much appreciated

**Comment by Vaalyn** [comment] 2019-03-15 15:35
@SlvrEagle23 The hoster is https://www.time4vps.com/

@williambatson Thanks, I'll close the issue now

**Closed by Vaalyn** 2019-03-15 15:35 UTC
Labels: error
