### ISSUE TITLE
Download CSV listeners

### ISSUE THREAD

**Issue by detone** [AzuraCast/AzuraCast#3911] opened 2021-03-11 17:39 UTC
**Using Docker installation method**
 YES

**AzuraCast version**
 Rolling Release #9af25b3 (2021-03-09 8:49) • Docker • PHP 7.4 

**Host Operating System**
 Debian

**Describe the bug**

It is possible to see listeners connected in real time by statistics. The problem is when we want to have access to the report of the total listeners for a period (1 month or more).

I notice that the CPU consumption increases, but the report of all accesses is not displayed during the selected period.

I also can't generate the CSV file for the last selected month, for example.

Thanks!

David Jill
BestRadio Brasil

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**

Desktop and mobile
Chrome, Firefox and Safari
Windows and MacOS
All versions

- Device: 
- OS: 
- Browser: 
- Version: 

**Additional context**

**Comment by SlvrEagle23** [comment] 2021-03-22 15:05
I believe this is a duplicate of other issues that were reported with the listeners report that have since been largely resolved or improved significantly.

**Closed by SlvrEagle23** 2021-03-22 15:05 UTC

**Comment by detone** [comment] 2021-03-22 15:37
Thank you for your answer. I will make the latest recent updates and give you feedback if it worked successfully.
