### ISSUE TITLE
AAC+ / FDK

### ISSUE THREAD

**Issue by efsysefsys** [AzuraCast/AzuraCast#69] opened 2016-11-20 00:06 UTC
Ogg not good :) Best = fdk-aac / MPEG-4 HE-AAC v2 ( plase add aac+ not aac but aac+ v2 ) aac+ dont eat much trafic good for mobile radio apk and websites. I think its not very hard to add just need liquidsoap plugin and some libs for ubuntu.

* aac+ on bitrate 32 or 48 = sound ok = trafic low :P try listen on this bitrate ogg or mp3 and check internet trafic  :D 

p.s. Default icecast2 server its ok but, icecast KH brench beter check icecast KH version features :)

**Comment by SlvrEagle23** [comment] 2016-11-20 06:47
@efsysefsys I'm having trouble getting fdk-aac to work on Ubuntu. Even with `apt-get install libfdkaac-ocaml`, LiquidSoap still doesn't detect that the plugin is available.

**Comment by efsysefsys** [comment] 2016-11-20 08:32
apt-get install libfdk-aac-dev , libaacplus-ocaml-dynlink , libfdkaac-ocaml. Mabby u have trouble because ubuntu dont have lib fdk aac? first need install lib on ubuntu then install plugins , ocaml. etc or try compile aac or fdk from source on ubuntu machine.

**Comment by SlvrEagle23** [comment] 2016-11-21 02:15
Right now I'm unable to get LiquidSoap to detect FDK-AAC at all, even after installing libfdk-aac-dev.

Also, for the KH build of IceCast, I would agree that it looks to be more stable, but the problem is that there are no prebuilt binaries available for it that I can find. I don't want to get into the business of having AzuraCast pull down and compile components if it's at all possible to avoid that.

**Comment by efsysefsys** [comment] 2016-11-21 08:54
maby precompiled liquidsoap-full have disabled aac.

**Comment by SlvrEagle23** [comment] 2016-11-26 00:19
Closing for now as I'm unable to find a build of LiquidSoap that runs out of the box with FDK-AAC support.

**Closed** 2017-05-17 21:52 UTC
Labels: enhancement
