### ISSUE TITLE
Folders can't be added as a Live Folder to a Playlist

### ISSUE THREAD

**Issue by NicoxDJ** [AzuraCast/AzuraCast#5943] opened 2022-12-14 18:41 UTC
### Installation Method

Ansible Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.17.3 Stable

### What happened?

I'm setting a Live Folder as a Playlist.
Some of the folders were ok. But some, won't add. 
Right now, when I'm adding a Folder as a Playlist, it doesn't add it, but adds all the files that it contains to the playlist.
The problem is that I make automation and these files are deleted and replaced with new ones.
In this case, the playlist is becoming empty.
The only way I can add the folders now as a Live folder is directly in mysql.
I don't know what I've did during this time of managing the system with files, could be probably different permissions, but I don't think this can relay to this problem?

### Relevant log output

```shell
I really don't know what kind of log to give, but in the frontend it doesn't give any error message
```

**Comment by silvaalex2021** [comment] 2022-12-28 15:42
@NicoxDJ Could you kindly give me instructions on how to do that directly via Mysql? I urgently need to get this to work, as we are working on a new project that needs this functionality.

**Comment by NicoxDJ** [comment] 2022-12-28 17:45
@silvaalex2021 You go ti mysql and insert it in table `station_playlist_folders` like this:
![](https://i.imgur.com/trRszqD.png)

Note: you have to know the mysql password from the installation of azuracast.

**Comment by silvaalex2021** [comment] 2022-12-28 20:16
@NicoxDJ MYSQL is complaining, and won't let me insert the rows.

ERROR 1452 (23000) at line 1: Cannot add or update a child row: a foreign key constraint fails (`azuracast`.`station_playlist_folders`, CONSTRAINT `FK_15190AE96BBD148` FOREIGN KEY (`playlist_id`) REFERENCES `station_playlists` (`id`) ON DELETE CASCADE)

I'm pretty sure I'm doing this wrong 😉

**Comment by NicoxDJ** [comment] 2022-12-28 20:33
@silvaalex2021 Did you insert the right playlist_id? It have to match, with your playlist, that you want to add the folder to

**Comment by BusterNeece** [comment] 2022-12-29 15:44
Is your playlist a Sequential playlist type? Right now, we don't support setting folders to be assigned to Sequential playlists, because we couldn't keep track of what order the tracks should be when we do the sync process.

For shuffled/random playlists, I'm testing on the latest Rolling Release version (0.17.3 is a few versions back, by the way) and it's working exactly as intended, and can add folders into playlists without any issues.

**Comment by silvaalex2021** [comment] 2022-12-29 16:36
@BusterNeece But there is no warning or information about this limitation anywhere (not that I've seen) and the media manager throws a "success" message when trying to perform this operation.

**Comment by NicoxDJ** [comment] 2022-12-30 11:34
@BusterNeece yes, thats the case. I didn't knew that neither. Also my folders that i try to add is with just one file inside.
Anyway, i will remove the Sequential mode. Thanks!

**Closed** 2023-01-14 02:34 UTC
Labels: needs investigation
