### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by ckeurk** [AzuraCast/AzuraCast#820] opened 2018-09-28 14:41 UTC
**Installation method**
Traditional

Hello,
I created a new radio with icecast but it probably doesn't work that the media file is too big.
I deleted the folder in question but now I have this page. The main radio still works
how to solve the problem ?
Thank you
![capture d ecran 2018-09-28 a 16 40 54](https://user-images.githubusercontent.com/379099/46215281-4aca6680-c33d-11e8-92b1-9b107ae77506.png)

**Comment by SlvrEagle23** [comment] 2018-09-28 19:49
@ckeurk This was caused by a station not having a default mount point registered, which led to the stream URL function returning `null`. It should be fixed now.

**Closed by SlvrEagle23** 2018-09-28 19:49 UTC
Labels: bug
