### ISSUE TITLE
error in azuracast-setup : Run AzuraCast Setup (Install Mode

### ISSUE THREAD

**Issue by anmiefan** [AzuraCast/AzuraCast#3538] opened 2020-12-10 06:40 UTC
Using Docker installation method
No

AzuraCast version
latest

Host Operating System
Ubuntu 18.04 LTS x64

Describe the bug
During installation, azuracast-setup : Run AzuraCast Setup (Install Mode

Screenshots

Device(s):

Device: PC
OS: Windows server 2012 in vmware 
Browser: Chrome
Version: latest
Additional context
I know you but i think docker takes to much ram so i need to use Ansible

here is the error 

TASK [azuracast-setup : Run AzuraCast Setup (Install Mode)] ********************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/AzuraCast/bin/console azuracast:setup", "delta": "0:00:00.500598", "end": "2020-12-10 06:22:02.092980", "msg": "non-zero return code", "rc": 1, "start": "2020-12-10 06:22:01.592382", "stderr": "\nIn AbstractMySQLDriver.php line 61:\n                                                                               \n  An exception occurred while executing 'SELECT t0.setting_key AS setting_key  \n  _1, t0.setting_value AS setting_value_2 FROM settings t0':                   \n                                                                               \n  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settin  \n  gs' doesn't exist                                                            \n                                                                               \n\nIn Exception.php line 18:\n                                                                               \n  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settin  \n  gs' doesn't exist                                                            \n                                                                               \n\nIn PDOConnection.php line 125:\n                                                                               \n  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settin  \n  gs' doesn't exist                                                            \n                                                                               \n\nazuracast:setup [--update] [--load-fixtures] [--release]", "stderr_lines": ["", "In AbstractMySQLDriver.php line 61:", "                                                                               ", "  An exception occurred while executing 'SELECT t0.setting_key AS setting_key  ", "  _1, t0.setting_value AS setting_value_2 FROM settings t0':                   ", "                                                                               ", "  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settin  ", "  gs' doesn't exist                                                            ", "                                                                               ", "", "In Exception.php line 18:", "                                                                               ", "  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settin  ", "  gs' doesn't exist                                                            ", "                                                                               ", "", "In PDOConnection.php line 125:", "                                                                               ", "  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settin  ", "  gs' doesn't exist                                                            ", "                                                                               ", "", "azuracast:setup [--update] [--load-fixtures] [--release]"], "stdout": "", "stdout_lines": []}

**Comment by SlvrEagle23** [comment] 2020-12-10 11:23
Closing as duplicate of #3517 .

**Closed by SlvrEagle23** 2020-12-10 11:23 UTC
