### ISSUE TITLE
Listeners page returns incorrect data - Internal/Reserve IP location

### ISSUE THREAD

**Issue by simpsss** [AzuraCast/AzuraCast#5002] opened 2022-01-18 20:19 UTC
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#dcea1b9

### What happened?

After the last update (#dcea1b9), is not showing the real IPs and locations of the people who are listening.

Maybe it's because you changed the nginx proxy?

![image](https://user-images.githubusercontent.com/51731449/150011494-c81a0de7-7d7a-4d5a-89a3-6561666f91f1.png)

**Comment by SC2Mitch** [comment] 2022-01-18 20:57
Shall check in a moment, standby.

**Comment by dvdred** [comment] 2022-01-21 09:03
> I have the same issue on my installation on docker, version #fcdc50c
I don't know why, but i solved the issue in this way:
- docker-compose down of azuracast
- update and reboot of the docker host (CenOS 7)
- docker-compose up of azuracast (with the same version: #fcdc50c)
Now i can see the public ip of the listeners.

**Comment by SlvrEagle23** [comment] 2022-01-21 12:24
I suspect this may be indeed caused by our retirement of the multi-container nginx proxy solution, but it should be fixed after updating.

Some possible causes of problems may be:
 - Do you have a `docker-compose.override.yml` file? Make sure that's updated to not have any references to `nginx_proxy` or `nginx_proxy_letsencrypt_companion` (unless you're actually using a multi-site configuration)
 - Make sure when updating that you run `./docker.sh update-self` first, to ensure the updater is running all the necessary steps

**Comment by SC2Mitch** [comment] 2022-01-21 14:00
Updated to latest rolling, and still retains the Internal IP
![image](https://user-images.githubusercontent.com/29955942/150539654-8c284c77-10e7-4f5e-99e6-a4a29dd18a93.png)

Not using a override file.

**Comment by SlvrEagle23** [comment] 2022-01-21 14:20
@SC2Mitch And just to confirm, there's no `nginx_proxy` service listed in the main `docker-compose.yml` file?

**Comment by SC2Mitch** [comment] 2022-01-21 14:24
Nope, this is my main file for clarity
```
services:
    web:
        container_name: azuracast_web
        image: 'ghcr.io/azuracast/web:${AZURACAST_VERSION:-latest}'
        ports:
            - '${AZURACAST_HTTP_PORT:-80}:80'
            - '${AZURACAST_HTTPS_PORT:-443}:443'
            - '${AZURACAST_SFTP_PORT:-2022}:2022'
        depends_on:
            - mariadb
            - stations
            - redis
        env_file: azuracast.env
        environment:
            LANG: '${LANG:-en_US.UTF-8}'
            AZURACAST_DC_REVISION: 13
            AZURACAST_VERSION: '${AZURACAST_VERSION:-latest}'
            AZURACAST_SFTP_PORT: '${AZURACAST_SFTP_PORT:-2022}'
            NGINX_TIMEOUT: '${NGINX_TIMEOUT:-1800}'
            LETSENCRYPT_HOST: '${LETSENCRYPT_HOST:-}'
            LETSENCRYPT_EMAIL: '${LETSENCRYPT_EMAIL:-}'
            PUID: '${AZURACAST_PUID:-1000}'
            PGID: '${AZURACAST_PGID:-1000}'
        volumes:
            - 'letsencrypt:/etc/nginx/certs'
            - 'letsencrypt_internal:/etc/acme.sh'
            - 'www_vendor:/var/azuracast/www/vendor'
            - 'www_uploads:/var/azuracast/uploads'
            - 'tmp_data:/var/azuracast/www_tmp'
            - 'station_data:/var/azuracast/stations'
            - 'shoutcast2_install:/var/azuracast/servers/shoutcast2'
            - 'geolite_install:/var/azuracast/geoip'
            - 'sftpgo_data:/var/azuracast/sftpgo/persist'
            - 'backups:/var/azuracast/backups'
        networks:
            - frontend
            - backend
        restart: unless-stopped
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
        logging:
            options:
                max-size: 1m
                max-file: '5'
    mariadb:
        container_name: azuracast_mariadb
        image: 'ghcr.io/azuracast/db:${AZURACAST_VERSION:-latest}'
        volumes:
            - 'db_data:/var/lib/mysql'
        env_file: azuracast.env
        networks:
            - backend
        restart: unless-stopped
        logging:
            options:
                max-size: 1m
                max-file: '5'
    redis:
        container_name: azuracast_redis
        image: 'ghcr.io/azuracast/redis:${AZURACAST_VERSION:-latest}'
        sysctls:
            net.core.somaxconn: 1024
        volumes:
            - 'redis_data:/data'
        networks:
            - backend
        restart: unless-stopped
        logging:
            options:
                max-size: 1m
                max-file: '5'
    stations:
        container_name: azuracast_stations
        image: 'ghcr.io/azuracast/radio:${AZURACAST_VERSION:-latest}'
        environment:
            PUID: '${AZURACAST_PUID:-1000}'
            PGID: '${AZURACAST_PGID:-1000}'
        ports:
            - '8000:8000' - I snipped the ports to save your eyes
        volumes:
            - 'station_data:/var/azuracast/stations'
            - 'shoutcast2_install:/var/azuracast/servers/shoutcast2'
            - 'letsencrypt:/etc/nginx/certs'
            - 'tmp_data:/var/azuracast/www_tmp'
        networks:
            - frontend
            - backend
        init: true
        restart: unless-stopped
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
        logging:
            options:
                max-size: 1m
                max-file: '5'
networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
volumes:
    db_data: {  }
    letsencrypt: {  }
    letsencrypt_internal: {  }
    shoutcast2_install: {  }
    geolite_install: {  }
    sftpgo_data: {  }
    station_data: {  }
    www_vendor: {  }
    www_uploads: {  }
    tmp_data: {  }
    redis_data: {  }
    backups: {  }
```

**Comment by SlvrEagle23** [comment] 2022-01-22 02:50
Hmm. I really thought we had this one figured out. Are the internal IPs showing up from users connecting via `/radio/8000/radio.mp3` or via `:8000/radio.mp3`? If we can isolate the issue to one or the other, that can help.

**Comment by SC2Mitch** [comment] 2022-01-22 04:58
via domain/port/radio.mp3, i don't use the :8000 stuff.

**Comment by YosefAdPro** [comment] 2022-01-22 17:16
> Hmm. I really thought we had this one figured out. Are the internal IPs showing up from users connecting via `/radio/8000/radio.mp3` or via `:8000/radio.mp3`? If we can isolate the issue to one or the other, that can help.

The problem seems to be that you only listen through `/radio/8000/radio.mp3`.
When using `:8000/radio.mp3` See the public IP.

**Comment by jjs999jjs** [comment] 2022-01-22 19:14
If I listen through :8000/radio.mp3 it shows IP
If I listen through /radio/8000/radio.mp3 it does not
![image](https://user-images.githubusercontent.com/65810290/150652396-d9e80f9c-18f0-48dd-aeb6-5afb8f7b2721.png)

**Comment by dvdred** [comment] 2022-01-23 11:58
After reading your latest comments, I checked and in fact found the same behavior you described.
So I changed the nginx proxy configuration of the "web" container:
**/etc/nginx/conf.d/azuracast.conf**
```
...
    location ~ ^/radio/(8[0-9][0-9]0)(/?)(.*)$ {

        proxy_buffering           off;
        proxy_ignore_client_abort off;
        proxy_intercept_errors    on;
        proxy_next_upstream       error timeout invalid_header;
        proxy_redirect            off;
        proxy_connect_timeout     60;
        proxy_send_timeout        21600;
        proxy_read_timeout        21600;
**--->    proxy_set_header    X-Real-IP        $remote_addr;
--->    proxy_set_header    X-Forwarded-For  $proxy_add_x_forwarded_for;**
        proxy_set_header Host localhost:$1;
        proxy_pass http://stations:$1/$3?$args;
    }
....
    location ~ ^/radio/(8[0-9][0-9]5)(/?)(.*)$ {


        resolver 127.0.0.11;

        proxy_buffering           off;
        proxy_ignore_client_abort off;
        proxy_send_timeout        21600;
        proxy_read_timeout        21600;
**--->    proxy_set_header    X-Real-IP        $remote_addr;
--->    proxy_set_header    X-Forwarded-For  $proxy_add_x_forwarded_for;**

        proxy_pass http://stations:$1/$3;
    }

```
Then I reloaded nginx (**/etc/init.d/nginx reload**) and now i see the correct public Ip of the client on all endpoints.

**Comment by SlvrEagle23** [comment] 2022-01-23 12:56
Yeah, we made some changes to how we handle those headers for when we were behind a multi-site configuration, and now we have to undo those changes. It's really minor in the grand scheme of things, but in this case it makes all the difference in the world.

I'm pushing up an updated version that should resolve this issue. Once the commit above goes green, if you all don't mind updating and confirming that the update fixes it, it would be much appreciated.

**Comment by simpsss** [comment] 2022-01-23 14:15
I updated and it didn't work

![image](https://user-images.githubusercontent.com/51731449/150682711-ec261620-c714-448c-89f2-d26ffc94d420.png)

**Comment by SC2Mitch** [comment] 2022-01-23 22:21
Should be fixed now

**Closed by SC2Mitch** 2022-01-23 22:22 UTC
Labels: bug, unexpected behaviour, rolling-release

**Comment by jjs999jjs** [comment] 2022-01-23 22:28
Many thanks Mitch
