### ISSUE TITLE
Hiding Information For Jingle?

### ISSUE THREAD

**Issue by Ilario42** [AzuraCast/AzuraCast#1086] opened 2019-01-03 18:31 UTC
Hi, I need to send jingles for my radio, having implemented top5 votes and much more. Now I wonder, would it be possible to hide the jingles? In other words, when they are played, the jingle being played is not shown in the bees and public page, but is it the last song before the jingle?
It would be very useful for many people in my opinion.

I wait for your answer!
Best regards, Ilario

**Comment by SlvrEagle23** [comment] 2019-01-03 18:33
Duplicate of #753. Follow that issue for updates.

**Closed by SlvrEagle23** 2019-01-03 18:33 UTC
