### ISSUE TITLE
Music files are not displayed

### ISSUE THREAD

**Issue by VTCAKAVSMoACE** [AzuraCast/AzuraCast#1074] opened 2018-12-27 20:27 UTC
**Installation method**
Docker

**Host OS (for Docker installations)**
```
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={76E245CF-C0D0-444D-BA50-36739C18EB00}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={76E245CF-C0D0-444D-BA50-36739C18EB00}
CHROMEOS_RELEASE_BOARD=lakitu-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=60
CHROMEOS_RELEASE_BUILDER_PATH=lakitu-release/R71-11151.60.0
CHROMEOS_RELEASE_BUILD_NUMBER=11151
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=71
CHROMEOS_RELEASE_DESCRIPTION=11151.60.0 (Official Build) stable-channel lakitu 
CHROMEOS_RELEASE_KEYSET=mp-v2
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=11151.60.0
DEVICETYPE=OTHER
GOOGLE_RELEASE=11151.60.0
HWID_OVERRIDE=LAKITU DEFAULT
```
OS with SELinux, optimized for running containers.

**Describe the bug**
Media files within the the media folder is not shown within the music files page.

**To Reproduce**
1. Upload files over SFTP to the media folder of the target station (>100 files).
2. Run the medium sync.
3. `docker-compose run --rm cli azuracast_cli azuracast:media:reprocess`

**Expected behavior**
All files are shown.

**Relevant Logs**
N/A

**Device(s):**
N/A

**Additional context**
#1052 appears to have allowed me to upload my files, but now they are not shown within the files explorer.
![music files explorer](https://user-images.githubusercontent.com/10711159/50493419-f8075600-09e2-11e9-996d-47aa64cd6ffb.png)

**Comment by vasilisss** [comment] 2018-12-27 23:04
hi and me. , I have exactly the same problem.....

**Comment by SlvrEagle23** [comment] 2018-12-27 23:16
@VTCAKAVSMoACE @vasilisss Duplicate of #1073, which was just fixed as of the latest code update. You'll want to reupload any media that didn't appear in the music files page.

**Closed by SlvrEagle23** 2018-12-27 23:16 UTC
