### ISSUE TITLE
Recording Lost after DJ Disconnected 

### ISSUE THREAD

**Issue by Christosgm** [AzuraCast/AzuraCast#6739] opened 2023-11-17 17:23 UTC
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

 0.19.2

### What happened?

After disconnecting from the stream the recording of a DJ wasn't available to listen or to download. 

Having 2 other different DJs connect and succesfully record their sessions via the Record Live Broadcasts option, I wanted to try the Audio Post-processing options ticking the Basic Normalization and Compression option and also ticking the Apply Post-processing to Live Streams option as well. When the DJ disconnected, the Default Live Broadcast Message appeared in the AutoDJ player and couldn't continue with the General Rotation Playlist. 

After waiting for 2 hours nothing happened and decided to reload the AutoDJ Service. The DJ Broadcasts tab shows the entry like this (this is from the time the DJ disconnected till now):
![Screenshot from 2023-11-17 19-13-53](https://github.com/AzuraCast/AzuraCast/assets/43483665/ae309659-6b0e-437d-99fb-d2bd8e7ebbef)

### Relevant log output

```shell
2023/11/17 10:18:02 [lang:3] API djon - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/djon' with body: { "user": "flakes" }
2023/11/17 10:18:02 [lang:3] API djon - Response (200): true
2023/11/17 10:18:02 [input_streamer:3] Decoding...
2023/11/17 10:18:07 [live_fallback:3] Switch to metadata_map.2 with transition.
2023/11/17 10:18:07 [replay_metadata.464:3] Content type is {audio=pcm(stereo)}.
2023/11/17 10:18:07 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/feedback' with body: { "artist": "", "title": "Live Broadcast" }
2023/11/17 10:18:07 [lang:3] API feedback - Response (200): true
2023/11/17 12:41:36 [input_streamer:2] Feeding stopped: Ffmpeg_decoder.End_of_file.
2023/11/17 12:41:36 [lang:3] API djoff - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/djoff' with body: { "user": "flakes" }
2023/11/17 12:41:36 [lang:3] API djoff - Response (200): true
2023/11/17 12:43:39 [output_file:2] Warning: there may be an infinite sequence of empty tracks!
2023/11/17 12:43:39 [output_file:2] Warning: there may be an infinite sequence of empty tracks!
2023/11/17 12:43:40 [output_file:2] Warning: there may be an infinite sequence of empty tracks!
2023/11/17 12:43:40 [output_file:2] Warning: there may be an infinite sequence of empty tracks!
2023/11/17 12:43:40 [output_file:2] Warning: there may be an infinite sequence of empty tracks!
2023/11/17 12:43:40 [output_file:2] Warning: there may be an infinite sequence of empty tracks!
2023/11/17 12:43:41 [output_file:2] Warning: there may be an infinite sequence of empty tracks!
2023/11/17 12:43:41 [output_file:2] Warning: there may be an infinite sequence of empty tracks!
2023/11/17 12:43:41 [output_file:2] Warning: there may be an infinite sequence of empty tracks!
2023/11/17 12:43:41 [output_file:2] Warning: there may be an infinite sequence of empty tracks!
.
.
.
```

**Comment by netbladenl** [comment] 2023-11-19 10:14
Seems like the same problem I have, https://github.com/AzuraCast/AzuraCast/issues/6727

I already made an issue at the github of Liquidsoap

**Comment by burjuyz** [comment] 2023-11-25 19:31
Confirm, the same log and the same error.

**Comment by streulma** [comment] 2023-11-26 23:13
We can confirm on 0.19.3 stable. I commented on #6727 too.
We fixed this ourself with an own recording system: VLC player on the same server constantly listening to the Icecast stream and recording it and split in MP3 files of a couple of hours. Files served via HTTP and htpasswd protected with a download link.

**Comment by BusterNeece** [comment] 2023-11-26 23:45
Duplicate of #6727. I still strongly suspect this is an upstream Liquidsoap issue, so if they publish any fixes or updates, please let us know.

**Closed by BusterNeece** 2023-11-26 23:45 UTC
Labels: needs investigation
