### ISSUE TITLE
AutoDJ/Liquidsoap crashes frequently after update to v0.12.1 stable

### ISSUE THREAD

**Issue by houndbee** [AzuraCast/AzuraCast#3839] opened 2021-02-23 12:13 UTC
**Using Docker installation method**
No

**AzuraCast version**
v0.12.1

**Host Operating System**
Ubuntu 18.04.5 LTS

**Describe the bug**
After an update to 0.12.1, AutoDJ does not start automatically. But it crashes soon after you start it manually. This continues to happen everytime you restart it manually.

**To Reproduce**
Update to 0.12.1. Start AutoDJ

**Expected behavior**
AutoDJ should keep running :)

**Relevant Logs**
`````
2021/02/23 12:48:24 >>> LOG START
2021/02/23 12:48:24 [main:3] Liquidsoap 1.4.2
2021/02/23 12:48:24 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.4.6 sedlex=2.3 menhirLib=20201216 dtools=0.4.2 duppy=0.8.0 cry=0.6.1 mm=0.5.1 ogg=0.5.2 vorbis=0.7.1 opus=0.1.3 mad=0.4.5 flac=0.1.5 flac.ogg=0.1.5 dynlink=[distributed with Ocaml] lame=0.3.3 fdkaac=0.3.1 samplerate=0.1.4 taglib=0.3.3 ssl=0.5.9 camomile=1.0.2 faad=0.4.0 ladspa=0.1.5
2021/02/23 12:48:24 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
2021/02/23 12:48:24 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2021/02/23 12:48:24 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2021/02/23 12:48:24 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2021/02/23 12:48:24 [decoder:3] Method "MAD" accepted "/var/azuracast/www/resources/error.mp3".
2021/02/23 12:48:24 [sandbox:3] Sandboxing disabled
2021/02/23 12:48:24 [video.converter:3] Couldn't find preferred video converter: gavl.
2021/02/23 12:48:24 [audio.converter:3] Using samplerate converter: libsamplerate.
2021/02/23 12:48:24 [harbor:3] Adding mountpoint '/' on port 8005
2021/02/23 12:48:24 [playlist_default:3] Loading playlist...
2021/02/23 12:48:24 [playlist_default:3] No mime type specified, trying autodetection.
2021/02/23 12:48:24 [playlist_default:3] Playlist treated as format application/x-mpegURL
2021/02/23 12:48:24 [playlist_default:3] Successfully loaded a playlist of 1 tracks.
2021/02/23 12:48:24 [error_jingle:3] "/var/azuracast/www/resources/error.mp3" is static, resolving once for all...
2021/02/23 12:48:24 [local_3:3] Connecting mount /256.ogg for source@127.0.0.1...
2021/02/23 12:48:24 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/openradio/media/silence_30s.mp3".
2021/02/23 12:48:25 [local_3:3] Connection setup was successful.
2021/02/23 12:48:25 [local_1:3] Connecting mount /radio.mp3 for source@127.0.0.1...
2021/02/23 12:48:25 [local_1:3] Connection setup was successful.
2021/02/23 12:48:25 [local_2:3] Connecting mount /256.mp3 for source@127.0.0.1...
2021/02/23 12:48:25 [local_2:3] Connection setup was successful.
2021/02/23 12:48:25 [local_4:3] Connecting mount /128.ogg for source@127.0.0.1...
2021/02/23 12:48:25 [local_4:3] Connection setup was successful.
2021/02/23 12:48:25 [clock.wallclock_main:3] Streaming loop starts, synchronized with wallclock.
2021/02/23 12:48:25 [safe_fallback:3] Switch to compress_10680.
2021/02/23 12:48:25 [live_fallback:3] Switch to cross_10640.
2021/02/23 12:48:25 [requests_fallback:3] Switch to autodj_fallback.
2021/02/23 12:48:25 [autodj_fallback:3] Switch to dynamic_startup.
2021/02/23 12:48:25 [dynamic_startup:3] Switch to switch_10622.
2021/02/23 12:48:25 [switch_10622:3] Switch to autodj_startup_blank.
2021/02/23 12:48:27 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:48:31 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:48:33 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:48:39 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:48:41 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:48:46 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:48:48 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:48:53 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:48:55 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:48:59 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:49:01 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:49:05 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:49:09 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:49:12 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:49:16 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:49:18 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:49:22 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:49:24 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:49:28 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:49:31 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:49:35 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:49:38 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:49:42 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:49:44 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:49:49 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:49:51 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:49:55 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:49:56 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:50:01 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:50:04 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:50:05 [lang:3] AutoDJ could not be initialized within the specified timeout.
2021/02/23 12:50:05 [main:3] Shutdown started!
2021/02/23 12:50:05 [main:3] Waiting for main threads to terminate...
2021/02/23 12:50:05 [local_4:3] Closing connection...
2021/02/23 12:50:05 [local_2:3] Closing connection...
2021/02/23 12:50:05 [local_1:3] Closing connection...
2021/02/23 12:50:05 [local_3:3] Closing connection...
2021/02/23 12:50:05 [lang:3] DJ Source disconnected! Current live DJ: 
2021/02/23 12:50:05 [server:3] New client: 127.0.0.1.
2021/02/23 12:50:05 [server:3] Client 127.0.0.1 disconnected.
2021/02/23 12:50:05 [lang:3] AzuraCast Live Disconnected Response: true
2021/02/23 12:50:05 [harbor:3] Removing mountpoint '/' on port 8005
2021/02/23 12:50:05 [harbor:3] Nothing more on port 8005: closing sockets.
2021/02/23 12:50:10 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:50:10 [clock.wallclock_main:3] Streaming loop stopped.
2021/02/23 12:50:10 [main:3] Threads terminated.
2021/02/23 12:50:10 [threads:3] Shutting down scheduler...
2021/02/23 12:50:10 [threads:3] Scheduler shut down.
2021/02/23 12:50:10 [threads:3] Waiting for queue threads to terminate...
2021/02/23 12:50:10 [threads:3] Queues shut down
2021/02/23 12:50:10 [server:3] Closing socket.
2021/02/23 12:50:10 [main:3] Cleaning downloaded files...
2021/02/23 12:50:10 [main:3] Freeing memory...
2021/02/23 12:50:10 >>> LOG END
2021/02/23 12:52:59 >>> LOG START
2021/02/23 12:52:59 [main:3] Liquidsoap 1.4.2
2021/02/23 12:52:59 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.4.6 sedlex=2.3 menhirLib=20201216 dtools=0.4.2 duppy=0.8.0 cry=0.6.1 mm=0.5.1 ogg=0.5.2 vorbis=0.7.1 opus=0.1.3 mad=0.4.5 flac=0.1.5 flac.ogg=0.1.5 dynlink=[distributed with Ocaml] lame=0.3.3 fdkaac=0.3.1 samplerate=0.1.4 taglib=0.3.3 ssl=0.5.9 camomile=1.0.2 faad=0.4.0 ladspa=0.1.5
2021/02/23 12:52:59 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
2021/02/23 12:52:59 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2021/02/23 12:52:59 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2021/02/23 12:52:59 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2021/02/23 12:52:59 [decoder:3] Method "MAD" accepted "/var/azuracast/www/resources/error.mp3".
2021/02/23 12:52:59 [sandbox:3] Sandboxing disabled
2021/02/23 12:52:59 [video.converter:3] Couldn't find preferred video converter: gavl.
2021/02/23 12:52:59 [audio.converter:3] Using samplerate converter: libsamplerate.
2021/02/23 12:52:59 [harbor:3] Adding mountpoint '/' on port 8005
2021/02/23 12:52:59 [playlist_default:3] Loading playlist...
2021/02/23 12:52:59 [playlist_default:3] No mime type specified, trying autodetection.
2021/02/23 12:52:59 [playlist_default:3] Playlist treated as format application/x-mpegURL
2021/02/23 12:52:59 [playlist_default:3] Successfully loaded a playlist of 1 tracks.
2021/02/23 12:52:59 [error_jingle:3] "/var/azuracast/www/resources/error.mp3" is static, resolving once for all...
2021/02/23 12:52:59 [local_3:3] Connecting mount /256.ogg for source@127.0.0.1...
2021/02/23 12:52:59 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/openradio/media/silence_30s.mp3".
2021/02/23 12:52:59 [local_3:3] Connection setup was successful.
2021/02/23 12:52:59 [local_1:3] Connecting mount /radio.mp3 for source@127.0.0.1...
2021/02/23 12:52:59 [local_1:3] Connection setup was successful.
2021/02/23 12:52:59 [local_2:3] Connecting mount /256.mp3 for source@127.0.0.1...
2021/02/23 12:53:00 [local_2:3] Connection setup was successful.
2021/02/23 12:53:00 [local_4:3] Connecting mount /128.ogg for source@127.0.0.1...
2021/02/23 12:53:00 [local_4:3] Connection setup was successful.
2021/02/23 12:53:00 [clock.wallclock_main:3] Streaming loop starts, synchronized with wallclock.
2021/02/23 12:53:00 [safe_fallback:3] Switch to compress_10680.
2021/02/23 12:53:00 [live_fallback:3] Switch to cross_10640.
2021/02/23 12:53:00 [requests_fallback:3] Switch to autodj_fallback.
2021/02/23 12:53:00 [autodj_fallback:3] Switch to dynamic_startup.
2021/02/23 12:53:00 [dynamic_startup:3] Switch to switch_10622.
2021/02/23 12:53:00 [switch_10622:3] Switch to autodj_startup_blank.
2021/02/23 12:53:00 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:53:02 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:53:04 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:53:08 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:53:10 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:53:15 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:53:17 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:53:22 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:53:24 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:53:25 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:53:30 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:53:32 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:53:36 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:53:40 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:53:43 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:53:47 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:53:49 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:53:54 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:53:57 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:54:00 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:54:03 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:54:06 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:54:10 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:54:12 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:54:16 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:54:18 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:54:24 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:54:27 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:54:31 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:54:33 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:54:39 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:54:39 [lang:3] AutoDJ could not be initialized within the specified timeout.
2021/02/23 12:54:39 [main:3] Shutdown started!
2021/02/23 12:54:39 [main:3] Waiting for main threads to terminate...
2021/02/23 12:54:39 [local_3:3] Closing connection...
2021/02/23 12:54:39 [local_1:3] Closing connection...
2021/02/23 12:54:39 [local_2:3] Closing connection...
2021/02/23 12:54:39 [local_4:3] Closing connection...
2021/02/23 12:54:39 [lang:3] DJ Source disconnected! Current live DJ: 
2021/02/23 12:54:39 [server:3] New client: 127.0.0.1.
2021/02/23 12:54:39 [server:3] Client 127.0.0.1 disconnected.
2021/02/23 12:54:39 [lang:3] AzuraCast Live Disconnected Response: true
2021/02/23 12:54:39 [harbor:3] Removing mountpoint '/' on port 8005
2021/02/23 12:54:39 [harbor:3] Nothing more on port 8005: closing sockets.
2021/02/23 12:54:41 [lang:3] AzuraCast Raw Response: 
2021/02/23 12:54:41 [clock.wallclock_main:3] Streaming loop stopped.
2021/02/23 12:54:41 [main:3] Threads terminated.
2021/02/23 12:54:41 [threads:3] Shutting down scheduler...
2021/02/23 12:54:41 [threads:3] Scheduler shut down.
2021/02/23 12:54:41 [threads:3] Waiting for queue threads to terminate...
2021/02/23 12:54:41 [threads:3] Queues shut down
2021/02/23 12:54:41 [server:3] Closing socket.
2021/02/23 12:54:41 [main:3] Cleaning downloaded files...
2021/02/23 12:54:41 [main:3] Freeing memory...
2021/02/23 12:54:41 >>> LOG END
`````

**Comment by houndbee** [comment] 2021-02-23 12:26
Just to add - this is also happening to me on a latest rolling release test instance I run using Docker.

**Comment by Vaalyn** [comment] 2021-02-23 12:59
The following line indicates that for some reason the dynamic source in Liquidsoap is not returning true on the `source.is_ready` check even after trying for over a minute.

```
AutoDJ could not be initialized within the specified timeout.
```

This can indicate a resource issue on the server or some other things.

Are you using remote playlists?
How does the resource usage (CPU & RAM) look like when this happens?
Can you also look into the `AzuraCast Application Log` / post that here?

**Comment by mikeopensauce** [comment] 2021-02-23 13:22
A also have the same problem using the Docker install on Ubuntu 18.04.
When I start the AutoDJ it runs for a short while (less than a minute) then stops. Server isn't showing any different strain when it is trying to run. I only have a few demo songs on the playlist to try it out.
It seemed to be working fine before latest update.
Liquidsoap Log finishes with
`2021/02/23 13:21:23 [lang:3] AzuraCast Raw Response: 
2021/02/23 13:21:24 [lang:3] AutoDJ could not be initialized within the specified timeout.
2021/02/23 13:21:24 [main:3] Shutdown started!
2021/02/23 13:21:24 [main:3] Waiting for main threads to terminate...
2021/02/23 13:21:24 [local_1:3] Closing connection...
2021/02/23 13:21:24 [local_2:3] Closing connection...
2021/02/23 13:21:24 [local_3:3] Closing connection...
2021/02/23 13:21:24 [lang:3] DJ Source disconnected! Current live DJ: 
2021/02/23 13:21:24 [lang:3] AzuraCast Live Disconnected Response: true
2021/02/23 13:21:24 [harbor:3] Removing mountpoint '/' on port 8005
2021/02/23 13:21:24 [harbor:3] Nothing more on port 8005: closing sockets.
2021/02/23 13:21:24 [clock.wallclock_main:3] Streaming loop stopped.
2021/02/23 13:21:24 [main:3] Threads terminated.
2021/02/23 13:21:24 [threads:3] Shutting down scheduler...
2021/02/23 13:21:24 [threads:3] Scheduler shut down.
2021/02/23 13:21:24 [threads:3] Waiting for queue threads to terminate...
2021/02/23 13:21:24 [threads:3] Queues shut down
2021/02/23 13:21:24 [server:3] Closing socket.
2021/02/23 13:21:24 [main:3] Cleaning downloaded files...
2021/02/23 13:21:24 [main:3] Freeing memory...`

**Comment by houndbee** [comment] 2021-02-23 13:40
> Are you using remote playlists?

Yes, I do every now and then - but this problem persists even after disabling all remote playlists.

> How does the resource usage (CPU & RAM) look like when this happens?

The CPU and RAM usage looks pretty normal - the box is a
 8 core decicated server(Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz) with 16GB RAM with nothing except Azuracast running on it.

> Can you also look into the `AzuraCast Application Log` / post that here?

Here you go, the app log (partial, but corresponding to the same time frame as the above liquidsoap log)

https://pastebin.com/HW3fzPg2

**Comment by lawesw** [comment] 2021-03-03 10:54
Anyone got a solution to fix this yet? I'm having the same issue..

**Comment by SlvrEagle23** [comment] 2021-03-03 13:00
I'm not sure at all what's happening with this update affecting Liquidsoap, as the only change we made to that image was well before the 0.12.1 release went stable (Jan 27), so anyone would've noticed that from that point on, not from now on.

In any case, they've released an update to version 1.4.4 stable of Liquidsoap, and we're in the process of updating the radio image to reflect that. You should update again (a few minutes after this message) and see if it improves the situation.

**Comment by kaweesi** [comment] 2021-03-03 20:12
i have just launched a new digital ocean droplet and had this exact same issue once again

**Comment by SlvrEagle23** [comment] 2021-03-03 22:54
@kaweesi DigitalOcean is using our stable builds, which we haven't updated to incorporate this change yet; we need to confirm via Rolling Release whether it works properly for most installations before we can move it to the Stable branch.

You can change your installation's release channel by [following these instructions](https://docs.azuracast.com/en/getting-started/updates/release-channels).

**Comment by zarankumar** [comment] 2021-03-04 08:16
I m using Rolling Release #d3938fa latest. The issue is still there. Did u update the code?

**Comment by SlvrEagle23** [comment] 2021-03-04 10:53
@zarankumar Yes, the Liquidsoap installation should have updated since then; the code update wasn't with this repository but with one of our related ones (the Docker build image).

**Comment by RobertC85** [comment] 2021-03-05 13:05
the rolling release version released this morning has this issue on ubuntu 20.04. i an wondering if 18.04 might do better

**Comment by SlvrEagle23** [comment] 2021-03-05 13:12
We need more information if we're going to be able to diagnose the problem; in particular, we need logs from two places:
 - Liquidsoap (visible via the Utilities > Log Viewer on any given station) Log
 - the web application log (visible either via the System Administration > Log Viewer page, or via `docker-compose logs -f web` on the host computer from `/var/azuracast`)

If the AutoDJ is reporting that it has no track it can play, this will cause the AutoDJ to fail and to shutdown operations after a short period of time.

**Comment by SlvrEagle23** [comment] 2021-03-05 13:26
@RobertC85, @zarankumar and others:

I have a suspicion this was caused by a safety feature we added in, where if the AzuraCast AutoDJ wasn't able to produce a playable song within the first few seconds/minutes of broadcast, the system would shut down the stream to avoid basically playing nothing over the air and to facilitate a process restart.

In cases where you have only a live broadcast or otherwise don't have playable content for the AutoDJ in that first threshold period, it appears that's causing this safety check to trigger inappropriately, shutting down the broadcast when it's actually broadcasting a signal. Also, instead of restarting the radio service, it's shutting it down and not starting it back up, which is also clearly not the desired behavior.

I've pushed an update to the Rolling Release channel just now that should help resolve this issue.

**Comment by RobertC85** [comment] 2021-03-05 13:28
ok, thanks, i will update again in a few minutes, i am usually relaying another stream from another source until there is a program scheduled

**Comment by RobertC85** [comment] 2021-03-05 13:41
yes, it plays your voiceover, do you mind telling me the path to that file so i can record my own notice please?

**Comment by zarankumar** [comment] 2021-03-05 14:46
@SlvrEagle23  You are right.  iam checking with Rolling Release #b05e036. Currently, liquidsoap is running without any issue when we create a new station through the admin panel and also through API. Only issue I am seeing is now playing is showing "stream offline" for few minutes and after that, it is showing AzuraCast is Live! and streaming correctly. Also when we create a new station it is not automatically starting. We should click to start it.

**Comment by sessionsradio** [comment] 2021-03-05 15:36
I have also encountered the same issue, using Docker install, and the log files show the same as original reported above

2021/03/05 15:07:32 [lang:3] AzuraCast Raw Response: 
2021/03/05 15:07:35 [lang:3] AzuraCast Raw Response: 
2021/03/05 15:07:37 [lang:3] AzuraCast Raw Response: 
2021/03/05 15:07:38 [lang:3] AutoDJ could not be initialized within the specified timeout.
2021/03/05 15:07:38 [main:3] Shutdown started!


I changed to the rolling release channel and updated. Liquidsoap now stays running and shows the following 

2021/03/05 15:14:42 [lang:3] AzuraCast Raw Response: 
2021/03/05 15:14:45 [lang:3] AzuraCast Raw Response: 
2021/03/05 15:14:47 [lang:3] AzuraCast Raw Response: 
2021/03/05 15:14:50 [lang:3] AzuraCast Raw Response: 
2021/03/05 15:14:50 [lang:3] AutoDJ could not be initialized within the specified timeout.

And no further entry in the logs after this, however the stream has stayed online and Liquidsoap continues running.

I did check the server to begin with before updating and there was no issues and RAM & CPU usage were normal 

It might be worth noting, our Azuracast install runs 5 stations simultaneously, and no other station was having this issue, just one. And we are not using any remote URL playlists

**Comment by SlvrEagle23** [comment] 2021-03-07 01:48
It appears removing the `shutdown` call from our AutoDJ fixes the issue with the Liquidsoap instance turning off entirely for certain stream types.

**Closed by SlvrEagle23** 2021-03-07 01:48 UTC
Labels: error

**Comment by kaweesi** [comment] 2021-03-09 11:13
the last i time i tried this out, it wasn't fixed, was it finally fixed?

**Comment by SlvrEagle23** [comment] 2021-03-09 11:14
@kaweesi The fix for this was verified repeatedly in Rolling Release testing, and so has now been published on the stable release version, so regardless of which channel you're using, you should be able to update and it will fix the issue.
