### ISSUE TITLE
The local stream player selector on profile page is not working properly

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#3779] opened 2021-02-05 20:27 UTC
**Using Docker installation method**
Yes
**AzuraCast version**
Rolling Release #6774392 (2021-02-05 16:58)

**Host Operating System**
Ubuntu 20.04

**Describe the bug**
In case of  running 3 or more mounts, when "PLAY" is pressed on the third mount,  all other mounts icons change to pause.
![image](https://user-images.githubusercontent.com/2701228/107085425-23cfa980-6801-11eb-9717-dac86b20b242.png)

**Comment by betowebti** [comment] 2021-02-05 22:33
I got the same problem here

**Comment by SlvrEagle23** [comment] 2021-02-06 00:14
@eranwo What are the last parts of the URLs (besides the random timestamp tagged on the end)? i.e. what are the mount point names (`/radio.mp3`, etc). because I can't reproduce this locally with standard mount point names.

**Comment by Vaalyn** [comment] 2021-02-06 02:42
This is most likely the same problem as in issue #3566.

I'd recommend following that issue for more information.

**Comment by eranwo** [comment] 2021-02-06 08:19
@SlvrEagle23 @Vaalyn I found the cause to the issue. If you setup a mount point without a type (`.mp3`, etc) the issue occurs.
For example `/radio.mp3` or `/rado.aac` - works good, but just /radio not.
Anyway it's playing but if there's one mount name in the list, without `.xyz` after the name, it causes the player icon issue.

**Comment by Vaalyn** [comment] 2021-02-06 17:26
As you can see in the issue that I linked to the root cause is that the beginning of one mount name is also the name of another mount. It’s bot strictly due to the extension / type but since it is rather commpn to have multiple mount point with a similar name just different types this is the easiest way to encounter this bug.

**Comment by Vaalyn** [comment] 2021-02-06 17:29
Since this here is indeed a duplicate issue I‘ll close it now.

Please follow #3566 for further updates regarding this bug.

**Closed by Vaalyn** 2021-02-06 17:29 UTC
Labels: bug, duplicate
