### ISSUE TITLE
Playlist not displayed in calendar

### ISSUE THREAD

**Issue by nexion63** [AzuraCast/AzuraCast#7098] opened 2024-05-09 18:18 UTC
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.19.7

### What happened?

Hi, there,
I made the last update of Azuracast and any new programming does not appear in the calendar, nor in the planned part of the homepage of the station except when it is in broadcast now, before it worked perfectly.

Example: on the "Scheduled" screenshot, DJ JOS is broadcasting at the scheduled time, but it doesn't appear in the calendar. I did a test by creating a new "TEST" for 10/05 04:00 pm-05:00 pm playlist, but it doesn't appear in the calendar either, nor in the scheduled.

This isn't really a problem, as recorded programs scheduled via the playlist are broadcast, but it's annoying when you want to be sure that the program has been programmed correctly.

What would be the solution? Will there be a new update to correct this?

In any case, despite this, I'd like to thank you for this radio management software, which is incredible in every way! 

![Capture d'écran 2024-05-09 200705](https://github.com/AzuraCast/AzuraCast/assets/18293266/863468ac-59a2-41be-90d9-408de19d399a)
![Capture d'écran 2024-05-09 200822](https://github.com/AzuraCast/AzuraCast/assets/18293266/8fca8afa-4878-42f9-9cd1-516c320f33dc)
![Capture d'écran 2024-05-09 200727](https://github.com/AzuraCast/AzuraCast/assets/18293266/b1af1b7b-7736-4d80-adad-816ec5899833)

**Comment by chrisulloa** [comment] 2024-05-13 17:14
I'm seeing this issue too, calendar is completely broken for live streamers and most playlists.

**Comment by BusterNeece** [comment] 2024-05-17 17:38
@nexion63 I'm investigating this but I'm having trouble reproducing it in my local installation. If anyone else is experiencing this and can tell me the exact settings they're using for the user(s) who aren't showing up, it may help with isolating things.

**Comment by BusterNeece** [comment] 2024-05-17 17:52
Seems like the problem is that it's not rendering schedules that are set to start and end on the same day (i.e. are one-day schedules). Will investigate.

**Comment by chrisulloa** [comment] 2024-05-17 17:54
Ahh you're right, I made this change to the playlist (set start and end date to different dates) and it appeared on the calendar (though incorrectly)
![image](https://github.com/AzuraCast/AzuraCast/assets/11605892/0fb83c59-0ee9-4239-95b8-796b009a7e1a)
![image](https://github.com/AzuraCast/AzuraCast/assets/11605892/5f96cd87-8b73-47fa-b841-8d903f9ff114)

**Comment by BusterNeece** [comment] 2024-05-17 18:30
@chrisulloa The issue with single-day events not showing up on the schedule should be fixed as of the latest Rolling Release. If you could update and verify that it's fixed, let me know.

**Comment by chrisulloa** [comment] 2024-05-17 18:32
@BusterNeece issue is fixed, the schedule is working again for me! thank you

**Closed** 2024-05-17 18:38 UTC
Labels: bug, in progress, needs investigation, rolling-release

**Comment by nexion63** [comment] 2024-05-17 18:43
Well, I did a test again actually it works after restarting the container the calendar updates but if we make a modification in the playlist without restarting It doesn't update

**Comment by BusterNeece** [comment] 2024-05-17 18:44
@nexion63 Without refreshing the page you mean?

**Comment by nexion63** [comment] 2024-05-18 14:22
@BusterNeece Thanks for your v0.20.0 update, everything's back to normal! You did it!
