### ISSUE TITLE
ERROR 500 after update

### ISSUE THREAD

**Issue by DAMaia1989** [AzuraCast/AzuraCast#7429] opened 2024-09-04 17:50 UTC
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release Channel 

### What happened?

Hi there,
After updating to the latest version, I can't access the Azura panel, I get error 500. However, if I change to the stable version I can access it without any problem.

**Comment by Sella-GH** [comment] 2024-09-04 18:57
Confirming here, no 500 tho but it doesn't load at all.

Logs:
```
NOTICE: PHP message: PHP Fatal error:  Uncaught RuntimeException: File not found: "/var/azuracast/www/web/static/vite_dist/.vite/manifest.json" in /var/azuracast/www/backend/src/Utilities/Json.php:36
Stack trace:
#0 /var/azuracast/www/backend/src/View.php(83): App\Utilities\Json::loadFromFile('/var/azuracast/...')
#1 /var/azuracast/www_tmp/CompiledContainer.php(743): App\View->__construct(Object(App\Customization), Object(App\Environment), Object(App\CallableEventDispatcher), Object(App\Version), Object(App\Http\Router))
#2 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(55): CompiledContainer->get45()
#3 /var/azuracast/www_tmp/CompiledContainer.php(659): DI\CompiledContainer->get('App\\View')
#4 /var/azuracast/www_tmp/CompiledContainer.php(689): CompiledContainer->get35()
#5 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(55): CompiledContainer->get34()
#6 /var/azuracast/www_tmp/CompiledContainer.php(90): DI\CompiledContainer->get('App\\Http\\ErrorH...')
#7 /var/azurac...
[2024-09-04T18:56:08.561296+00:00] AzuraCast.ALERT: Fatal Error (E_ERROR): Uncaught RuntimeException: File not found: "/var/azuracast/www/web/static/vite_dist/.vite/manifest.json" in /var/azuracast/www/backend/src/Utilities/Json.php:36 Stack trace: #0 /var/azuracast/www/backend/src/View.php(83): App\Utilities\Json::loadFromFile('/var/azuracast/...') #1 /var/azuracast/www_tmp/CompiledContainer.php(743): App\View->__construct(Object(App\Customization), Object(App\Environment), Object(App\CallableEventDispatcher), Object(App\Version), Object(App\Http\Router)) #2 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(55): CompiledContainer->get45() #3 /var/azuracast/www_tmp/CompiledContainer.php(659): DI\CompiledContainer->get('App\\View') #4 /var/azuracast/www_tmp/CompiledContainer.php(689): CompiledContainer->get35() #5 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(55): CompiledContainer->get34() #6 /var/azuracast/www_tmp/CompiledContainer.php(90): DI\CompiledContainer->get('App\
\Http\\ErrorH...') #7 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(55): CompiledContainer->get4() #8 /var/azuracast/www/vendor/slim/slim/Slim/CallableResolver.php(135): DI\CompiledContainer->get('Slim\\Interfaces...') #9 /var/azuracast/www/vendor/slim/slim/Slim/CallableResolver.php(58): Slim\CallableResolver->resolveSlimNotation('Slim\\Interfaces...') #10 /var/azuracast/www/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(136): Slim\CallableResolver->resolve('Slim\\Interfaces...') #11 /var/azuracast/www/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(118): Slim\Middleware\ErrorMiddleware->getDefaultErrorHandler() #12 /var/azuracast/www/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(90): Slim\Middleware\ErrorMiddleware->getErrorHandler('App\\Exception\\W...') #13 /var/azuracast/www/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(79): Slim\Middleware\ErrorMiddleware->handleException(Object(App\Http\ServerRequest), Object(App\Exception\WrappedException)) #14 /var/azuraca
st/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(129): Slim\Middleware\ErrorMiddleware->process(Object(App\Http\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous)) #15 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(73): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(App\Http\ServerRequest)) #16 /var/azuracast/www/vendor/slim/slim/Slim/App.php(209): Slim\MiddlewareDispatcher->handle(Object(App\Http\ServerRequest)) #17 /var/azuracast/www/vendor/slim/slim/Slim/App.php(193): Slim\App->handle(Object(App\Http\ServerRequest)) #18 /var/azuracast/www/web/index.php(13): Slim\App->run() #19 {main}   thrown {"code":1,"message":"Uncaught RuntimeException: File not found: \"/var/azuracast/www/web/static/vite_dist/.vite/manifest.json\" in /var/azuracast/www/backend/src/Utilities/Json.php:36\nStack trace:\n#0 /var/azuracast/www/backend/src/View.php(83): App\\Utilities\\Json::loadFromFile('/var/azuracast/...')\n#1 /var/azuracast/www_tmp/CompiledContainer.php(74
3): App\\View->__construct(Object(App\\Customization), Object(App\\Environment), Object(App\\CallableEventDispatcher), Object(App\\Version), Object(App\\Http\\Router))\n#2 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(55): CompiledContainer->get45()\n#3 /var/azuracast/www_tmp/CompiledContainer.php(659): DI\\CompiledContainer->get('App\\\\View')\n#4 /var/azuracast/www_tmp/CompiledContainer.php(689): CompiledContainer->get35()\n#5 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(55): CompiledContainer->get34()\n#6 /var/azuracast/www_tmp/CompiledContainer.php(90): DI\\CompiledContainer->get('App\\\\Http\\\\ErrorH...')\n#7 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(55): CompiledContainer->get4()\n#8 /var/azuracast/www/vendor/slim/slim/Slim/CallableResolver.php(135): DI\\CompiledContainer->get('Slim\\\\Interfaces...')\n#9 /var/azuracast/www/vendor/slim/slim/Slim/CallableResolver.php(58): Slim\\CallableResolver->resolveSlimNotation('Slim\\\\Interfaces...'
)\n#10 /var/azuracast/www/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(136): Slim\\CallableResolver->resolve('Slim\\\\Interfaces...')\n#11 /var/azuracast/www/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(118): Slim\\Middleware\\ErrorMiddleware->getDefaultErrorHandler()\n#12 /var/azuracast/www/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(90): Slim\\Middleware\\ErrorMiddleware->getErrorHandler('App\\\\Exception\\\\W...')\n#13 /var/azuracast/www/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(79): Slim\\Middleware\\ErrorMiddleware->handleException(Object(App\\Http\\ServerRequest), Object(App\\Exception\\WrappedException))\n#14 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(129): Slim\\Middleware\\ErrorMiddleware->process(Object(App\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#15 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(73): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(App\\Htt
p\\ServerRequest))\n#16 /var/azuracast/www/vendor/slim/slim/Slim/App.php(209): Slim\\MiddlewareDispatcher->handle(Object(App\\Http\\ServerRequest))\n#17 /var/azuracast/www/vendor/slim/slim/Slim/App.php(193): Slim\\App->handle(Object(App\\Http\\ServerRequest))\n#18 /var/azuracast/www/web/index.php(13): Slim\\App->run()\n#19 {main}\n  thrown","file":"/var/azuracast/www/backend/src/Utilities/Json.php","line":36,"trace":null} []
```

**Comment by hwalker928** [comment] 2024-09-04 19:14
Can confirm this issue as well.

**Comment by BusterNeece** [comment] 2024-09-04 21:43
Sorry folks; this was caused by a breaking change in the `upload-artifact` GitHub Action (https://github.com/actions/upload-artifact/releases/tag/v4.4.0) where they started excluding "hidden" files (files starting with a dot, including our `.vite` manifest) as a security precaution to avoid leaking credentials. People are pretty furious over there, and for good reason; it should've likely been a 5.x release, not something people auto-updated to, because ours is far from the only repo that it totally broke.

Anyway, it's fixed as of the latest Rolling Release you can pull down currently.

**Closed by BusterNeece** 2024-09-04 21:43 UTC
Labels: needs investigation

**Comment by Sella-GH** [comment] 2024-09-04 22:31
Thanks for the fast response and fix! 🙂

**Comment by DAMaia1989** [comment] 2024-09-05 09:42
Thanks @BusterNeece for fix it! regards
