### ISSUE TITLE
I can't move music files to other folders

### ISSUE THREAD

**Issue by habib1228** [AzuraCast/AzuraCast#3270] opened 2020-10-13 01:48 UTC
AzuraCast version
Rolling Release #2e6cfee (2020-10-12 22:20)

reproducing: https://cloud.disroot.org/s/8TYxbFeQBSwRtRn

**Comment by SlvrEagle23** [comment] 2020-10-13 04:57
@habib1228 Thank you for the report and the video. This should be fixed as of the latest update; please update your installation when convenient and let me know if the issue is resolved.

**Comment by habib1228** [comment] 2020-10-13 06:23
@SlvrEagle23 Perfect! I got it!

**Closed** 2020-11-29 16:39 UTC
Labels: bug, in progress
