### ISSUE TITLE
Listener's IP not displaying

### ISSUE THREAD

**Issue by onurk7** [AzuraCast/AzuraCast#3078] opened 2020-08-10 11:02 UTC
Ubuntu x Docker

Not in every station, but some stations not displaying listener's IP's anymore at reports -> listeners. Even while GeoLite IP Database installed. Almost for a week, this situation is seen at some of our instances' some stations. 

Listener's IP seen as "192.168.32.6"
Listener's location seen as "Internal/Reserved IP"

Please let me know if I can do anything to fix it or send logs from a source.

**Comment by pixel-paul** [comment] 2020-08-10 13:43
Duplicate of #2898

**Closed** 2020-11-01 07:17 UTC
Labels: wontfix

**Comment by christiansacks** [comment] 2021-01-29 01:13
I just upgraded to the latest version and now I'm seeing the same thing
![image](https://user-images.githubusercontent.com/40481087/106218435-2b72cb00-61cf-11eb-8e18-b127d8f4463e.png)
