### ISSUE TITLE
Stream Offline

### ISSUE THREAD

**Issue by Jaymoon85** [AzuraCast/AzuraCast#1397] opened 2019-04-04 17:08 UTC
**Installation method**

Docker

**Host OS (for Docker installations)**

Ubuntu 18.10

**Describe the bug**

I am pushing audio to a mount on this server from a Barix Instreamer device as an Icecast stream. The audio works fine, excellent in fact, no issues there.

But when I view the Public Page of the station this mount is using, it says "Stream Offline", even though clicking the Play button starts playing the audio immediately.

So what is this field that "Stream Offline" is trying to pull from? (Status?, Title?, Artist?)

**To Reproduce**

1. Restart Barix Instreamer to send audio to AzuraCast server
2. View station Public Page
3. Click Play button
4. Audio is playing, but "Stream Offline" shows beside generic album art image
5. In the Station Overview of the Dashboard, station reports "Stream Offline" underneath the Now Playing column.

**Expected behavior**

4. Audio is playing, with any other text (even no text would be fine) instead of "Stream Offline"
5. Custom text, or even blank text

**Relevant Logs**

**Screenshots**

![Public Page](https://user-images.githubusercontent.com/3331159/55574570-8e71a480-56c1-11e9-8b29-18ba925cb64f.png)
![Dashboard](https://user-images.githubusercontent.com/3331159/55574580-96314900-56c1-11e9-908e-baded0757a98.png)

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment] 2019-04-04 17:47
@Jaymoon85 Does this only happen while the first song is playing, before any metadata updates are sent? This is a known issue with the software that's upstream from ours.

**Comment by Jaymoon85** [comment] 2019-04-04 20:28
Well, for this particular stream, there shouldn't be any changes to the metadata.  Maybe that's why this remains as "Stream Offline"?

On my previous setup of sending the audio to a pure Icecast server, the metadata was just static (through b.u.t.t.) and never changed.

I don't need it to change, but being able to manually set it, or just have it update (through the administration meta update task) is what I was looking for.

**Comment by SlvrEagle23** [comment] 2019-04-05 04:28
@Jaymoon85 This is likely a duplicate of known issue #867.

**Closed by SlvrEagle23** 2019-04-05 04:28 UTC
Labels: error
