### ISSUE TITLE
All stations offline, Liquidsoap not running

### ISSUE THREAD

**Issue by Deiiji** [AzuraCast/AzuraCast#5270] opened 2022-04-10 05:42 UTC
### Installation Method

Ansible Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #5d52ff4 (2022-04-09 2:37) • Ansible • PHP 8.1

### What happened?

Hello
I have all station offline, impossible to start liquidsoap but also it refuse live streaming as well or relay mode

### Relevant log output

```shell
Liquidsoap error:
Error 5: this value has type
  float
but it should be a subtype of
  int
At /var/azuracast/stations/goons_radio/config/liquidsoap.liq, line 44, char 20-41:
            timeout=float_of_int(timeout)

PHP error with stack:
[10-Apr-2022 01:36:53 UTC] PHP Fatal error:  Uncaught Error: Class "Ramsey\Uuid\Uuid" not found in /var/azuracast/www/src/Doctrine/Generator/UuidV6Generator.php:19
Stack trace:
#0 /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php(637): App\Doctrine\Generator\UuidV6Generator->__construct()
#1 /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php(144): Doctrine\ORM\Mapping\ClassMetadataFactory->completeIdGeneratorMapping()
#2 /var/azuracast/www/vendor/doctrine/persistence/src/Persistence/Mapping/AbstractClassMetadataFactory.php(391): Doctrine\ORM\Mapping\ClassMetadataFactory->doLoadMetadata()
#3 /var/azuracast/www/vendor/doctrine/persistence/src/Persistence/Mapping/AbstractClassMetadataFactory.php(260): Doctrine\Persistence\Mapping\AbstractClassMetadataFactory->loadMetadata()
#4 /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(307): Doctrine\Persistence\Mapping\AbstractClassMetadataFactory->getMetadataFor()
#5 /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/Repository/DefaultRepositoryFactory.php(29): Doctrine\ORM\EntityManager->getClassMetadata()
#6 /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(785): Doctrine\ORM\Repository\DefaultRepositoryFactory->getRepository()
#7 /var/azuracast/www/vendor/doctrine/persistence/src/Persistence/ObjectManagerDecorator.php(84): Doctrine\ORM\EntityManager->getRepository()
#8 /var/azuracast/www/src/Doctrine/Repository.php(39): Doctrine\Persistence\ObjectManagerDecorator->getRepository()
#9 /var/azuracast/www/src/Entity/Repository/SettingsRepository.php(32): App\Doctrine\Repository->__construct()
#10 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(143): App\Entity\Repository\SettingsRepository->__construct()
#11 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(71): DI\Definition\Resolver\ObjectCreator->createInstance()
#12 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(71): DI\Definition\Resolver\ObjectCreator->resolve()
#13 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(390): DI\Definition\Resolver\ResolverDispatcher->resolve()
#14 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(139): DI\Container->resolveDefinition()
#15 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Reference.php(53): DI\Container->get()
#16 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(66): DI\Definition\Reference->resolve()
#17 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ParameterResolver.php(78): DI\Definition\Resolver\ResolverDispatcher->resolve()
#18 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(138): DI\Definition\Resolver\ParameterResolver->resolveParameters()
#19 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(71): DI\Definition\Resolver\ObjectCreator->createInstance()
#20 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(71): DI\Definition\Resolver\ObjectCreator->resolve()
#21 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(390): DI\Definition\Resolver\ResolverDispatcher->resolve()
#22 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(139): DI\Container->resolveDefinition()
#23 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Reference.php(53): DI\Container->get()
#24 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(66): DI\Definition\Reference->resolve()
#25 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ParameterResolver.php(78): DI\Definition\Resolver\ResolverDispatcher->resolve()
#26 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(138): DI\Definition\Resolver\ParameterResolver->resolveParameters()
#27 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(71): DI\Definition\Resolver\ObjectCreator->createInstance()
#28 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(71): DI\Definition\Resolver\ObjectCreator->resolve()
#29 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(390): DI\Definition\Resolver\ResolverDispatcher->resolve()
#30 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(139): DI\Container->resolveDefinition()
#31 /var/azuracast/www/vendor/symfony/console/CommandLoader/ContainerCommandLoader.php(46): DI\Container->get()
#32 /var/azuracast/www/vendor/symfony/console/Application.php(561): Symfony\Component\Console\CommandLoader\ContainerCommandLoader->get()
#33 /var/azuracast/www/vendor/symfony/console/Application.php(648): Symfony\Component\Console\Application->has()
#34 /var/azuracast/www/vendor/symfony/console/Application.php(259): Symfony\Component\Console\Application->find()
#35 /var/azuracast/www/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#36 /var/azuracast/www/bin/console(17): Symfony\Component\Console\Application->run()
#37 {main}
  thrown in /var/azuracast/www/src/Doctrine/Generator/UuidV6Generator.php on line 19
[10-Apr-2022 01:36:53 UTC] PHP Fatal error:  Uncaught Error: Class "Symfony\Component\Console\Event\ConsoleTerminateEvent" not found in /var/azuracast/www/vendor/symfony/console/Application.php:1021
Stack trace:
#0 /var/azuracast/www/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#1 /var/azuracast/www/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#2 /var/azuracast/www/bin/console(17): Symfony\Component\Console\Application->run()
#3 {main}
  thrown in /var/azuracast/www/vendor/symfony/console/Application.php on line 1021
[10-Apr-2022 02:08:29 UTC] PHP Fatal error:  Uncaught RedisException: Redis server localhost:6379 went away in /var/azuracast/www/vendor/symfony/lock/Store/RedisStore.php:256
Stack trace:
#0 /var/azuracast/www/vendor/symfony/lock/Store/RedisStore.php(256): Redis->eval()
#1 /var/azuracast/www/vendor/symfony/lock/Store/RedisStore.php(244): Symfony\Component\Lock\Store\RedisStore->evaluate()
#2 /var/azuracast/www/src/Lock/RetryTillSaveStore.php(102): Symfony\Component\Lock\Store\RedisStore->exists()
#3 /var/azuracast/www/vendor/symfony/lock/Lock.php(233): App\Lock\RetryTillSaveStore->exists()
#4 /var/azuracast/www/vendor/symfony/lock/Lock.php(67): Symfony\Component\Lock\Lock->isAcquired()
#5 [internal function]: Symfony\Component\Lock\Lock->__destruct()
#6 {main}
  thrown in /var/azuracast/www/vendor/symfony/lock/Store/RedisStore.php on line 256
[10-Apr-2022 02:39:22 UTC] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/azuracast/www/vendor/pda/pheanstalk/src/Response/ArrayResponse.php on line 23
[10-Apr-2022 02:44:33 UTC] PHP Fatal error:  Uncaught RedisException: Redis server localhost:6379 went away in /var/azuracast/www/vendor/symfony/lock/Store/RedisStore.php:256
Stack trace:
#0 /var/azuracast/www/vendor/symfony/lock/Store/RedisStore.php(256): Redis->eval()
#1 /var/azuracast/www/vendor/symfony/lock/Store/RedisStore.php(244): Symfony\Component\Lock\Store\RedisStore->evaluate()
#2 /var/azuracast/www/src/Lock/RetryTillSaveStore.php(102): Symfony\Component\Lock\Store\RedisStore->exists()
#3 /var/azuracast/www/vendor/symfony/lock/Lock.php(233): App\Lock\RetryTillSaveStore->exists()
#4 /var/azuracast/www/vendor/symfony/lock/Lock.php(67): Symfony\Component\Lock\Lock->isAcquired()
#5 [internal function]: Symfony\Component\Lock\Lock->__destruct()

#6 {main}
  thrown in /var/azuracast/www/vendor/symfony/lock/Store/RedisStore.php on line 256
[10-Apr-2022 05:33:49 UTC] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 2621440 bytes) in /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2731
[10-Apr-2022 05:34:17 UTC] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 2621440 bytes) in /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2731

Azuracast error: 
[2022-04-10T05:41:52.142403+00:00] AzuraCast.ERROR: Response does not contain a "source" listing; the stream may be hidden or misspelled. {"response":"{\"icestats\":{\"admin\":\"icemaster@localhost\",\"banned_IPs\":0,\"build\":20220220182312,\"host\":\"akemi.webradio.ovh\",\"location\":\"AzuraCast\",\"outgoing_kbitrate\":0,\"server_id\":\"Icecast 2.4.0-kh13\",\"server_start\":\"10/Apr/2022:02:44:57 +0000\",\"stream_kbytes_read\":0,\"stream_kbytes_sent\":0}}"} {"station":{"id":5,"name":"Goons and CopyKat radio/stream by Deiji-Dame"}}
[2022-04-10T05:41:52.874711+00:00] AzuraCast.ERROR: Remote server has no mount points listed. {"response":"<?xml version=\"1.0\"?>\n<icestats>\n  <admin>icemaster@localhost</admin>\n  <banned_IPs>0</banned_IPs>\n  <build>20220220182312</build>\n  <client_connections>189</client_connections>\n  <clients>0</clients>\n  <connections>95</connections>\n  <file_connections>0</file_connections>\n  <host>akemi.webradio.ovh</host>\n  <listener_connections>0</listener_connections>\n  <listeners>0</listeners>\n  <location>AzuraCast</location>\n  <outgoing_kbitrate>0</outgoing_kbitrate>\n  <server_id>Icecast 2.4.0-kh13</server_id>\n  <server_start>09/Apr/2022:22:33:10 -0700</server_start>\n  <source_client_connections>0</source_client_connections>\n  <source_relay_connections>0</source_relay_connections>\n  <source_total_connections>0</source_total_connections>\n  <sources>0</sources>\n  <stats>0</stats>\n  <stats_connections>0</stats_connections>\n  <stream_kbytes_read>0</stream_kbytes_read>\n  <stream_kbytes_sent>0</stream_kbytes_sent>\n</icestats>\n"} {"station":{"id":6,"name":"Aether Music"}}
[2022-04-10T05:41:52.875635+00:00] AzuraCast.WARNING: Could not fetch XML data; falling back to public JSON. [] {"station":{"id":6,"name":"Aether Music"}}
[2022-04-10T05:41:52.877218+00:00] AzuraCast.ERROR: Response does not contain a "source" listing; the stream may be hidden or misspelled. {"response":"{\"icestats\":{\"admin\":\"icemaster@localhost\",\"banned_IPs\":0,\"build\":20220220182312,\"host\":\"akemi.webradio.ovh\",\"location\":\"AzuraCast\",\"outgoing_kbitrate\":0,\"server_id\":\"Icecast 2.4.0-kh13\",\"server_start\":\"09/Apr/2022:22:33:10 -0700\",\"stream_kbytes_read\":0,\"stream_kbytes_sent\":0}}"} {"station":{"id":6,"name":"Aether Music"}}
[2022-04-10T05:41:52.908527+00:00] AzuraCast.ERROR: Remote server has no mount points listed. {"response":"<?xml version=\"1.0\"?>\n<icestats>\n  <admin>icemaster@localhost</admin>\n  <banned_IPs>0</banned_IPs>\n  <build>20220220182312</build>\n  <client_connections>191</client_connections>\n  <clients>0</clients>\n  <connections>96</connections>\n  <file_connections>0</file_connections>\n  <host>akemi.webradio.ovh</host>\n  <listener_connections>0</listener_connections>\n  <listeners>0</listeners>\n  <location>AzuraCast</location>\n  <outgoing_kbitrate>0</outgoing_kbitrate>\n  <server_id>Icecast 2.4.0-kh13</server_id>\n  <server_start>09/Apr/2022:22:33:10 -0700</server_start>\n  <source_client_connections>0</source_client_connections>\n  <source_relay_connections>0</source_relay_connections>\n  <source_total_connections>0</source_total_connections>\n  <sources>0</sources>\n  <stats>0</stats>\n  <stats_connections>0</stats_connections>\n  <stream_kbytes_read>0</stream_kbytes_read>\n  <stream_kbytes_sent>0</stream_kbytes_sent>\n</icestats>\n"} {"station":{"id":6,"name":"Aether Music"}}
[2022-04-10T05:41:52.908684+00:00] AzuraCast.WARNING: Could not fetch XML data; falling back to public JSON. [] {"station":{"id":6,"name":"Aether Music"}}
[2022-04-10T05:41:52.910044+00:00] AzuraCast.ERROR: Response does not contain a "source" listing; the stream may be hidden or misspelled. {"response":"{\"icestats\":{\"admin\":\"icemaster@localhost\",\"banned_IPs\":0,\"build\":20220220182312,\"host\":\"akemi.webradio.ovh\",\"location\":\"AzuraCast\",\"outgoing_kbitrate\":0,\"server_id\":\"Icecast 2.4.0-kh13\",\"server_start\":\"09/Apr/2022:22:33:10 -0700\",\"stream_kbytes_read\":0,\"stream_kbytes_sent\":0}}"} {"station":{"id":6,"name":"Aether Music"}}
```

**Comment by SlvrEagle23** [comment] 2022-04-10 05:59
@Deiiji Unfortunately, this is caused by a change that liquidsoap made in their latest testing branch, which we're using on our Docker installations as a result of some bug fixes they've applied. They haven't shipped a stable version of the software yet, which is why we haven't updated the Ansible and ARM64 versions of our software to incorporate the fixes yet. This means that, for a brief period of a few days, our software will be incompatible with the version of Liquidsoap that some installations are running. They're expected to ship a new stable version at the beginning of this coming week, so the issue should be fully resolved after that version releases.

**Comment by Deiiji** [comment] 2022-04-10 22:43
Ok; thank you for fast answer

**Closed** 2022-04-11 01:29 UTC
Labels: bug, in progress, upstream, liquidsoap 2.0

**Comment by SlvrEagle23** [comment] 2022-04-11 02:19
@Deiiji you should now be able to use Ansible/ARM64 devices again.
