### ISSUE TITLE
Error Processing multiple files and different albums 

### ISSUE THREAD

**Issue by officialgamerfm** [AzuraCast/AzuraCast#3475] opened 2020-11-27 13:32 UTC
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #deb5ecd (2020-11-03 4:50)

**Host Operating System**
ubuntu

**Describe the bug**
when i upload any file it is now saying files not processed. If i try to upload via the panel i get the error code:
Argument 1 passed to App\Media\GetId3\GetId3MetadataManager::cleanUpString() must be of the type string, array given, called in /var/azuracast/www/src/Media/GetId3/GetId3MetadataManager.php on line 47

**To Reproduce**
1. Go to ftp or azura panel
2. uplaod some music
3. See error

**Expected behavior**
That the songs will upload fine with no error/

**Screenshots**
https://gyazo.com/0c887572993d9b81d6035b94dcd9a698

**Device(s):**
 - Device:  desktop pc 
 - OS: windows 10
 - Browser: edge
 - Version: dunno 

**Additional context**
I dont know if something glitched it but i cant upload anything now without getting this error. I havent even used all my space up i have like 4gb left to use.

**Comment by Vaalyn** [comment] 2020-11-27 18:20
Would you mind providing us with a file that triggers this problem?

I think there might be an ID3 tag in those files that returns data in a format (an array instead of a string) that the `GetId3MetadataManager` is currently not aware of.

**Comment by officialgamerfm** [comment] 2020-11-27 19:05
[006 - Prayer in C (Robin Schulz Radio Edit).zip](https://github.com/AzuraCast/AzuraCast/files/5609293/006.-.Prayer.in.C.Robin.Schulz.Radio.Edit.zip)
this is one of the songs in the album.

**Comment by SC2Mitch** [comment] 2020-11-27 21:43
Looking into this, tried the file you provided and the system provided this log:
```
Info Processing media for storage location Local: /var/azuracast/stations/test_main/media...
Info Sending message {class} with {alias} sender using {sender}

message
{
    "storage_location_id": 59,
    "path": "006_-_prayer_in_c_-28robin_schulz_radio_edit-29.mp3"
}
class
"App\\Message\\AddNewMediaMessage"
alias
0
sender
"Symfony\\Component\\Messenger\\Bridge\\Redis\\Transport\\RedisTransport"
```

When I looked into the ID3 via [ffprobe ](https://ffmpeg.org/ffprobe.html)and it returned this. 
```
root@vmi382976:~# ffprobe /006Prayer.mp3
ffprobe version 4.2.4-1ubuntu0.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mp3, from '/006Prayer.mp3':
  Metadata:
    title           : Prayer in C (Robin Schulz Radio Edit)
    album           : 100 Greatest Motivation Songs
    album_artist    : Various Artists
    track           : 6
    disc            : 1
    artist          : Lilly Wood And The Prick / Lilly Wood & The Prick / Robin Schulz
    genre           : Pop
    publisher       : PMEDIA NETWORK
    RELEASECOUNTRY  : PMEDIA NETWORK
    comment         : PMEDIA NETWORK
    copyright       : PMEDIA NETWORK
    lyrics-eng      : Downloaded From www.MusicDuty.Com
    date            : 2019
  Duration: 00:03:09.44, start: 0.025056, bitrate: 325 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 320 kb/s
    Metadata:
      encoder         : Lavc56.34
    Stream #0:1: Video: mjpeg (Progressive), yuvj444p(pc, bt470bg/unknown/unknown), 1200x1200 [SAR 300:300 DAR 1:1], 90k tbr, 90k tbn, 90k tbc (attached pic)
    Metadata:
      comment         : Cover (front)
```

**Comment by SC2Mitch** [comment] 2020-11-28 00:19
An additional user has provided a [extra MP3 file](https://www.dropbox.com/s/p7utrj4nksolo1f/02%20-%20Mirage.mp3?dl=1), logs for that file are as follows: 
```
Input #0, mp3, from '/Mirage.mp3':
  Metadata:
    title           : Mirage
    artist          : Armin van Buuren
    track           : 2/21
    album           : Mirage
    disc            : 1/2
    date            : 2010-09-15
    genre           : Trance, Electronic, House, Dance
    compilation     : 0
    TKEY            : Dm
    TMED            : CD
    TBPM            : 135
    TIPL            : arranger
    TDOR            : 2010-09-10
    Script          : Latn
    publisher       : Armada Music
    album_artist    : Armin van Buuren
    lyrics-XXX      : Instrumental
    artist-sort     : Buuren, van, Armin
    CATALOGNUMBER   : ARMA265
    MusicBrainz Album Type: album
    Artist Credit   : Armin van Buuren
    REPLAYGAIN_ALBUM_GAIN: -7.36 dB
    REPLAYGAIN_ALBUM_PEAK: 1.264272
    REPLAYGAIN_TRACK_GAIN: -8.52 dB
    REPLAYGAIN_TRACK_PEAK: 1.263919
    composer        : Armin van Buuren, Benno de Goeij
    MusicBrainz Album Status: Official
    ALBUMARTISTSORT : Buuren, van, Armin
    TSOC            : Buuren, van, Armin, Goeij, Benno, de
    Album Artist Credit: Armin van Buuren
    MusicBrainz Album Release Country: NL
    Acoustid Id     : da704ad9-8b32-430a-9e13-cb35505eba9a
    MusicBrainz Album Id: a8e45dd5-e2b6-333c-a6e4-56c554b1fe80
    MusicBrainz Artist Id: 477b8c0c-c5fc-4ad2-b5b2-191f0bf2a9df
    MusicBrainz Album Artist Id: 477b8c0c-c5fc-4ad2-b5b2-191f0bf2a9df
    MusicBrainz Release Group Id: 59d9034e-0c66-47f3-93ef-fe8d89472b8c
    MusicBrainz Release Track Id: 1a063658-d009-349c-b9ed-2ca82e84e5cc
    MusicBrainz Album Comment: exclusive Free Record Shop Netherlands limited edition
    iTunNORM        :  00001BC8 00001BC8 00004574 00004574 00000000 00000000 0000A1C8 0000A1C8 00000000 00000000
    Acoustid Fingerprint: AQADtHkqKVOKWswR5jPi6vgu9IUWId-FXoRj5sT04BzKpQ8ipdRxaN6Cxj1e4WiiLmjVBg_zoJdh-9CFqyLS-kKv4zLOpIV_5OKhC-9yCenV4M0e_Md3Y_orNJSCJ8gXLUV_TKK-45KWDTcptDma6njTQUfeo1KVwD7-I8wlEoeOnjlSbeNQH_-IfM3RLPsyPMcn49ilobnx41LKQ-8R7SF-eBKHL-jR8Md_fMrxnQhz5UKpDcJ_NF-IXsehxYp
  Duration: 00:06:41.71, start: 0.025056, bitrate: 366 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 320 kb/s
    Metadata:
      encoder         : LAME3.98r
    Side data:
      replaygain: track gain - -8.520000, track peak - 0.000029, album gain - -7.360000, album peak - 0.000029,
    Stream #0:1: Video: mjpeg (Baseline), yuvj444p(pc, bt470bg/unknown/unknown), 1426x1429, 90k tbr, 90k tbn, 90k tbc (attached pic)
    Metadata:
      comment         : Cover (front)
```

**Comment by SlvrEagle23** [comment] 2020-11-28 01:16
Looked into this and discovered the likely culprit: the PHP `Fileinfo` library is generally accurate with regards to the MIME type of files it's examining (based on the "magic headers" inside the files), but sometimes, when it can't identify a file, it just returns it as `application/octet-stream` instead, which is just the generic MIME type for an unidentified stream of bits and isn't processable by us.

Previously, we only fell back to extension-based MIME checking if no return value at all was returned by the file inspection, but I've updated the code to now also apply extension checking as well, which appears to resolve the issue for all affected files.

Please update to the latest rolling release and let me know if the issue is resolved on your end with your files.

**Comment by officialgamerfm** [comment] 2020-11-28 02:07
nice thanks , will get my host to update as soon as they can and ill get back to you!

**Comment by ImaCrea** [comment] 2020-11-29 22:39
hello there,
same issue here with a freshly installed and updated instance through auto-install docker script. :/

**Comment by ImaCrea** [comment] 2020-11-29 22:47
I was a bit quick sorry. So I managed to upload another album, I thought it was happening with every audio files. It's just that the two first albums I tried didn't work. 

Here's what I get in ffprobe for a file from the first album:
```
ffprobe version 4.0.2 Copyright (c) 2007-2018 the FFmpeg developers
  built with Apple LLVM version 9.1.0 (clang-902.0.39.2)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.0.2 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-opencl --enable-videotoolbox --disable-lzma
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
Input #0, mp3, from '/Users/pcfhstudio/Soulseek Downloads/complete/Gore/01 Dilemme.mp3':
  Metadata:
    title           : Dilemme
    artist          : Lous and the Yakuza
    track           : 1/10
    album           : GORE
    disc            : 1/1
    genre           : R&B
    TMED            : CD
    MusicBrainz Release Track Id: 81fee55b-ce16-489f-9529-6df43fa08bbb
    TORY            : 2020
    comment         : Ecoute le premier titre de Lous and The Yakuza en digital : https://LousATY.lnk.to/Dilemme
                    : Gore, son premier album maintenant disponible : https://LousATY.lnk.to/GORE
                    : 
                    : Rejoins les Yakuzas sur : 
                    : 
                    : • Chaîne Youtube : https://www.youtube.com/channel/UCz7f4Cl9tlNs26mOmc6-lbg?sub_confirmation=1 
                    : • Facebook : https://www.facebook.com/pages/category/Song/Lous-and-the-yakuza-2176094482451421/ 
                    : • Instagram: https://www.instagram.com/lousandtheyakuza/?hl=fr
                    : 
                    : ***********************************
                    : 
                    : Production Company : Scheme Engine 
                    : Réalisatrice vidéo : Wendy Morgan 
                    : Producteur exécutif : Jannie McInnes
                    : Productrice : Shabana Mansuri 
                    : DOP : Joel Honeywell 
                    : Chorégraphe : Abdou Nije
                    : Casting : Chloe Rosolek
                    : Stylist: Nathan Klein 
                    : Maquillage : Mary-Jane Gotidoc 
                    : Coiffeur : Nuriye Sonmez  
                    : Editeur : Pete Fullarton 
                    : Colour : Alex Gregory 
                    : Post House: The Mill 
                    : 
                    : London & Paris Dancers:
                    : Abdou Nije 
                    : Cal Hunt
                    : Jordan Adaji
                    : Hemedi Slate 
                    : Kanerflex  
                    : Kevin Bago 
                    : Kieron Simon 
                    : Saul Nash 
                    : Vivien-Chrys Samba 
                    : 
                    : ************************************
                    : 
                    : PAROLES : 
                    : 
                    : Au plus j'ai la haine, 
                    : Au plus ils me font de la peine.
                    : Ce n'est pas un drame,
                    : Si je ne fais plus la fête.
                    : Lous, es-tu sereine
                    : Ou fais-tu juste la guerre ?
                    : La vie est une chienne,
                    : Qu'il faut tenir en laisse 
                    : Vivre me hante
                    : Tout ce qui m'entoure m'a rendu méchante 
                    : Si je rate, je recommence
                    : Quand je suis triste, je chante 
                    : Ne jamais tout donner de moi, 
                    : Dans ce monde c'est le diable qui est roi, 
                    : Elles me disent que j’ai la poisse, 
                    : « Blague à part » devient « Lous à part » 
                    : 
                    : Seule, seule, seule
                    : 
                    : Si je pouvais je vivrais seule
                    : Loin des problèmes et des dilemmes 
                    : Na Na Na Na Na 
                    : Si je pouvais je vivrais seule
                    : Loin de mes chaines et des gens que j'aime 
                    : Na Na Na Na 
                    : 
                    : Si jamais je freine et que je ne fais plus de scènes 
                    : Laissez moi à l’arrière pour qu’à la source je me baigne 
                    : Ma blessure saigne et mon sang monte à la tête 
                    : Je reste la même et ce, quoi qu’il advienne 
                    : 
                    : Au plus j’ai la haine, au plus ils me font de la peine 
                    : Ma peau n’est pas noire, elle est couleur ébène 
                    : Lous es-tu sereine ou fait tu juste la guerre? 
                    : Tu n’es pas parfaite, ton erreur reste humaine. 
                    : 
                    : Seule, seule, seule, je veux être seule
                    : Seule…
                    : 
                    : Si je pouvais je vivrais seule,
                    : Loin des problèmes et des dilemmes 
                    : Na Na Na Na Na 
                    : Si je pouvais je vivrais seule
                    : Loin de mes chaines et des gens que j'aime 
                    : Na Na Na Na
                    : 
                    : Au plus j’avance, au plus je les devance
                    : Tant pis si tu ne suis pas la cadence
                    : Je ne sais même plus sur quel pied je danse
                    : Encore un nègre trop frais, ça dérange 
                    : 
                    : La mélodie me berce et me ronge
                    : Chaque mot me perce et donc je plonge
                    : Dans les profondeurs de mes songes
                    : Je nage, me noie, dans la pénombre
                    : 
                    : Si je pouvais je vivrais seule
                    : Loin de problèmes et des dilemmes 
                    : Na Na Na Na Na 
                    : Si je pouvais je vivrai seule
                    : Loin de mes chaines et des gens que j'aime 
                    : Na Na Na Na 
                    : 
                    : Seule, je vivrai seule
                    : Na Na Na Na Na
                    : Seule, je mourrai seule
                    : Na Na Na Na Na
    originalyear    : 2020
    album_artist    : Lous and the Yakuza
    TSO2            : Lous and the Yakuza
    artist-sort     : Lous and the Yakuza
    BARCODE         : 0194397238624
    Artists         : Lous and the Yakuza
    MusicBrainz Album Type: album
    publisher       : Smi Col (Sony Music Switzerland)
    MusicBrainz Album Status: official
    MusicBrainz Album Release Country: DE
    MusicBrainz Album Id: aa01b73f-0b0b-4e23-b05b-b8df21655657
    MusicBrainz Artist Id: 8a33dcf0-64b8-428c-8b64-828f8d85e2bb
    MusicBrainz Album Artist Id: 8a33dcf0-64b8-428c-8b64-828f8d85e2bb
    MusicBrainz Release Group Id: 97494cfd-52b2-445b-8ff7-78a73a35f8e1
    date            : 2020-10-16
  Duration: 00:03:05.76, start: 0.023021, bitrate: 323 kb/s
    Stream #0:0: Audio: mp3, 48000 Hz, stereo, fltp, 320 kb/s
    Metadata:
      encoder         : Lavc57.10
    Stream #0:1: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 500x450 [SAR 1:1 DAR 10:9], 90k tbr, 90k tbn, 90k tbc
    Metadata:
      comment         : Cover (front)
```

and from the second album :
```
  Metadata:
    title           : The Supermen
    artist          : David Bowie
    track           : 9/9
    album           : The Man Who Sold the World
    disc            : 1/1
    genre           : Rock
    TMED            : CD
    composer        : David Bowie
    MusicBrainz Release Track Id: 1a8a3fad-6ad1-367a-8425-808348020ad9
    TORY            : 1970
    comment         : With 1970's The Man Who Sold the World, David Bowie set aside his pop and singer-songwriter aspirations and headed in a harder-rocking direction. Producer Tony Visconti provided a thick, dense setting with guitarist Mick Ronson playing the role of guitar 
    publisher       : 東芝EMI 株式会社
    copyright       : http://www.demons-eye.org
    encoded_by      : http://www.demons-eye.org
    album_artist    : David Bowie
    TSO2            : Bowie, David
    artist-sort     : Bowie, David
    SCRIPT          : Latn
    ASIN            : B0009OAUJI
    originalyear    : 1970
    Artists         : David Bowie
    BARCODE         : 4988006831803
    TSRC            : USJT11500100/USJT19900022
    CATALOGNUMBER   : TOCP-53529
    MusicBrainz Album Type: album
    MusicBrainz Album Status: official
    MusicBrainz Album Release Country: JP
    Acoustid Id     : 945c768f-d681-45d8-91c7-ced06266c5f6
    MusicBrainz Album Id: d94e0f3a-bbcd-3961-ab49-c41f0cd15234
    MusicBrainz Artist Id: 5441c29d-3602-4898-b1a1-b77fa23b8e50
    MusicBrainz Album Artist Id: 5441c29d-3602-4898-b1a1-b77fa23b8e50
    MusicBrainz Release Group Id: 2536a41d-fde9-35d5-a6c6-cd4d94ffd916
    date            : 2005-07-06
    id3v2_priv.WM/UniqueFileIdentifier: A\x00M\x00G\x00a\x00_\x00i\x00d\x00=\x00R\x00 \x00 \x00 \x00 \x00 \x002\x004\x007\x009\x00;\x00A\x00M\x00G\x00p\x00_\x00i\x00d\x00=\x00P\x00 \x00 \x00 \x00 \x00 \x003\x007\x005\x003\x00;\x00A\x00M\x00G\x00t\x00_\x00i\x00d\x00=\x00T\x00 \x00 \x001\x005\x00
    id3v2_priv.WM/MediaClassSecondaryID: \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
    id3v2_priv.WM/WMCollectionGroupID: \x97\x17a\xe5\xfdP3F\x8d\x1d\xf0^d\x94]\x80
    id3v2_priv.WM/MediaClassPrimaryID: \xbc}`\xd1#\xe3\xe2K\x86\xa1H\xa4*(D\x1e
    id3v2_priv.WM/WMCollectionID: \x97\x17a\xe5\xfdP3F\x8d\x1d\xf0^d\x94]\x80
    id3v2_priv.WM/WMContentID: \x93R\x7f\xb4b(RA\x96\x93fmcq\x16E
    id3v2_priv.WM/Provider: A\x00M\x00G\x00\x00\x00
  Duration: 00:03:39.90, start: 0.000000, bitrate: 323 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 320 kb/s
    Stream #0:1: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 500x494 [SAR 1:1 DAR 250:247], 90k tbr, 90k tbn, 90k tbc
    Metadata:
      comment         : Cover (front)
```

hope it helps :)

**Comment by SlvrEagle23** [comment] 2020-11-30 12:08
@ImaCrea If you could send us the example file (i.e. via our [Discord](https://azuracast.com/discord) community) then we can continue diagnosing the issue. It's likely that the file looks like an unprocessable MIME type to us, and we just need to correct for that.

**Comment by ImaCrea** [comment] 2020-11-30 12:28
sure, here are two links :
https://nuage.liiib.re/s/eF4mmE9Y9jWi3wD
https://nuage.liiib.re/s/gLJL8n6JzEsHDmp

thanks for everything 🙏

**Comment by SlvrEagle23** [comment] 2020-11-30 13:32
@ImaCrea These issues should be fixed as of the latest rolling-release version. Thank you for your submission and help!

**Comment by ImaCrea** [comment] 2020-12-09 20:11
Great news, I'm gonna try that 👍

**Comment by ImaCrea** [comment] 2020-12-09 21:06
working like a charm, thank you!! 💎

**Closed** 2020-12-09 21:54 UTC
Labels: bug, in progress
