### ISSUE TITLE
https player links wont work

### ISSUE THREAD

**Issue by RonVerburg** [AzuraCast/AzuraCast#984] opened 2018-11-22 21:26 UTC
**Installation method**
Docker

**Host OS (for Docker installations)**
Ubuntu 16.04

**Describe the bug**
https stream links wont work in winamp (Icecast)

**To Reproduce**

**Relevant Logs**

**Screenshots**

**Device(s):**
All

**Additional context**
This url shows in Azuracast but wont play the stream
download pls https://streamsimpel.com/radio/8010/radio.mp3?1542921577
Now winamp opens but stream will not play

When i manualy open the pls file without ssl the stream is playing
http://streamsimpel.com/radio/8010/radio.mp3?1542921577
This is also with theM3U file.

SSL is working and proxy is enabled
https://streamsimpel.com

When i use the webplayer the stream is just working fine:
https://streamsimpel.com/radio/8010/radio.mp3?1542921575

What goes wrong here, any help is welcome :-)

**Comment by macbroadcast** [comment] 2018-11-22 21:34
Nothing wrong there :+1:

**Comment by Vaalyn** [comment] 2018-11-22 21:58
This problem was also mentioned in issue #935 and is most likely due to Winamp currently not supporting Let's Encrypt certificates. This is not an issue with AzuraCast but with Winamp. Let's Encrypt certificates are the standard for SSL certificates nowadays so it's up to Radionomy to add support for them in Winamp.

**Comment by RonVerburg** [comment] 2018-11-22 22:14
Thanks but ive found another solution that works with ss and winamp version 5>
https://streamsimpel.com/radio/8010/radio.mp3
so without ?1542921577 at the and of the url.
For now thanks!

**Comment by Vaalyn** [comment] 2018-11-22 22:17
That's interesting. Does anyone know why the url parameter affects Winamp at all? Something like that should not affect it in any way. Except if Winamp's url parsing is garbage.

**Comment by RonVerburg** [comment] 2018-11-23 08:19
It seems there is u update for this issue, after the last updat stream is not playing anymore on:
https://streamsimpel.com/radio/8010/radio.mp3
But now the links in the stream panel works also for winamp
https://streamsimpel.com/radio/8010/radio.mp3?1542960890

Thanks!

**Comment by Vaalyn** [comment] 2018-11-23 13:32
The numbers after the `radio.mp3` is just the current timestamp. This is a standard URL parameter that is there to prevent browsers and other software from caching the stream so that it doesn't try to restart from the point where you once disconnected. If this is not done it could happen that you get to hear a few seconds from a totally different song and then the stream would jump to the currently playing one after the cached audio stream has ended.

**Comment by RonVerburg** [comment] 2018-11-23 19:00
Hi aha thanks for that info

**Comment by SlvrEagle23** [comment] 2018-11-25 20:59
It seems this is a Winamp issue rather than something wrong with how we're generating URLs or serving the streams. I would say you should contact Radionomy for assistance on that end, but I wouldn't hold my breath that they would be of much help. In any case, this is likely not an error caused by something on AzuraCast's end, so I'm closing this ticket for now.

**Closed by SlvrEagle23** 2018-11-25 20:59 UTC
Labels: error
