### ISSUE TITLE
Listeners map

### ISSUE THREAD

**Issue by tonimad** [AzuraCast/AzuraCast#1131] opened 2019-01-31 00:23 UTC
I do not know if this is a mistake, but on the page of listeners, where the map with connected listeners appears, I can not see the city and other data.

Also, the accuracy is too inaccurate. I have IP Spain, but I appear in Germany.

Can someone review this in their installation?

**Comment by Vaalyn** [comment] 2019-01-31 08:53
AzuraCast uses the GeoLite 2 database for resolving IPs to locations. This process is by design quite inaccurate since providers often buy IP addresses from other regions of the world and assign them to their local residents. Often these databases also contain errors which lead to misidentifications and other inaccuracies.

You can try and download the GeoLite 2 City database from [here](https://dev.maxmind.com/geoip/geoip2/geolite2/) and search for your IPs in there to check if this is indeed due to the GeoIP database AzuraCast uses.

**Comment by tonimad** [comment] 2019-01-31 12:34
@Vaalyn thanks for your answer.

I've dinamic ip. I've checked my IP on iplocation.net and I now appear in Sweden 😂

I have found the file in (base)/geoip/GeoLite2-City.mmdb

**Closed** 2019-02-01 01:48 UTC
