### ISSUE TITLE
song titles and live listeners not working

### ISSUE THREAD

**Issue by surihost** [AzuraCast/AzuraCast#300] opened 2017-11-30 15:43 UTC
With the latest docker version i see this issue that live listeners and songs title are working  on the main dashboard.Please fix this.

**Comment by SlvrEagle23** [comment] 2017-11-30 15:47
@surihost This is the second report I've seen of this, but with no additional information that would help me diagnose the problem, which I don't see on any of my local (or on the public demo) instance.

If you could supply me with some additional details, it would be helpful, such as:
 - Is there any error on the developer console when viewing the homepage?
 - When you examine the network traffic, do you see websocket requests going through normally, or is there an error returned?
 - Does the station's profile page and/or public page still show the correct now playing data?

**Comment by surihost** [comment] 2017-11-30 16:04
No error on developer console 
The station profile page shows up the correct playing data.
Network traffic seems to be fine

**Comment by SlvrEagle23** [comment] 2017-11-30 16:11
Closing this as a duplicate of #297 -- Please follow that for updates. It's likely caused by the same issue.

**Closed by SlvrEagle23** 2017-11-30 16:11 UTC
