### ISSUE TITLE
"Time" column in Listener pages does not go above 24 hours

### ISSUE THREAD

**Issue by fnfzlznddzn** [AzuraCast/AzuraCast#5854] opened 2022-11-13 12:04 UTC
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #53080b1 (2022-08-23 4:36)

### What happened?

I've noticed the time connected in the listeners pages (both Live Listeners & Listener History) doesn't seem to go above 24h, it goes back to zero once 24 is reached. The time (sec) column is correct, but the conversion is incorrect:
![image 1](https://user-images.githubusercontent.com/45518224/201520594-d6122768-c758-4ce2-939e-0ab487bb6e3f.png)
According to Vaalyn in the Discord, 
> The formatTime method currently doesn't take into account more than 24h since it just uses the JS Date object to convert seconds to a "time" in order to format the seconds.

I would personally suggest that above 24 hours, the time column starts showing time in days & hours only, as at this point the minutes and seconds become negligible (and exact time can always be derived from the Time in seconds value).

**Comment by BusterNeece** [comment] 2022-11-14 03:56
Closing as duplicate of #5738, which is fixed in the latest Rolling Release.

**Closed by BusterNeece** 2022-11-14 03:57 UTC
Labels: needs investigation
