### ISSUE TITLE
 502 Bad Gateway Error After Updating from v0.19.3 to v0.19.4

### ISSUE THREAD

**Issue by simpsss** [AzuraCast/AzuraCast#6871] opened 2024-01-15 17:55 UTC
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.19.3

### What happened?

I recently attempted to update my AzuraCast installation from version v0.19.3 to v0.19.4. However, after successfully completing the update process, I encountered a persistent issue where the page consistently shows a "502 Bad Gateway" error.

![image](https://github.com/AzuraCast/AzuraCast/assets/51731449/f4a7cca5-ad4f-4a11-a547-76399be4a6dc)

### Relevant log output

```shell
Critical error in Nginx log: 

connect() to unix:/var/run/php-fpm-internal.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "POST /api/internal/...

Repeated errors in connection to php-fpm-internal.sock.
```

**Comment by BusterNeece** [comment] 2024-01-15 17:58
I'm really starting to wonder if there's some bug where folks are updating but not updating..._correctly_ somehow.

Can you try updating again, making sure to run `./docker.sh update-self` before `./docker.sh update`?

**Comment by lumper5** [comment] 2024-01-15 18:30
I tried manually updating "update-self" followed by "update" and got the same error.   I also tried  using the web (after rolling back) and I also tried updating sudo apt update && upgrade then doing a manual update.  All three methods failed.  I've been having no issue updating the rolling release for months now.

**Comment by BusterNeece** [comment] 2024-01-15 19:49
Closing as it appears this issue was caused by a custom `docker-compose.override.yml` file modifying the nginx contents. If you're running into a similar issue, check to make sure you aren't manually overriding some of the installation's files in your Docker configuration on the host device.

**Closed by BusterNeece** 2024-01-15 19:49 UTC
Labels: needs investigation
