### ISSUE TITLE
recursive folder

### ISSUE THREAD

**Issue by linksilver** [AzuraCast/AzuraCast#224] opened 2017-09-07 10:17 UTC
hello
i found that if you more than 3 levels of folder /media/first/second/third/file.mp3, azuracast doesnt add files to library with the medium scan

**Comment by linksilver** [comment] 2017-09-16 14:49
in fact the bug is that until the tracks are not added to a playlist they seems to not be added in the library and we cant prelisten them, but once the tracks are in a playlist no bug

**Comment by SlvrEagle23** [comment] 2018-04-08 03:13
@linksilver Back when this issue was filed, I couldn't reproduce the issue locally during my development and testing, and now that a significant rewrite of the system's code (including the synchronization steps) has been done, I've been able to run a few specific tests using recursive directories, and haven't been able to find any problems with parsing music files that are in long directories.

If you're still having trouble with this issue and would like me to look into it, please provide me with some specific example files and steps to reproduce the issue. Otherwise, I'm assuming the issue has been resolved in the intervening months.

**Closed by SlvrEagle23** 2018-04-08 03:13 UTC
Labels: bug

**Comment by Sendoushi** [comment] 2018-05-28 15:35
How can I sync the recursive folders? I've changed the folder to a mounted one on the manage station but I can't find any file in the "music files" tab.
