### ISSUE TITLE
 Login unsuccessful

### ISSUE THREAD

**Issue by danielrodrigotest** [AzuraCast/AzuraCast#1293] opened 2019-03-11 11:38 UTC
Hi, people...I updated to the new Azuracast version. However, I can't login from the page as admin/user, etc. There's a screenshot about the issue.
![Screenshot 2019-03-11 at 8 35 40 AM](https://user-images.githubusercontent.com/40525323/54121243-b9c1e600-43d8-11e9-93a8-aeeb58c569bf.png)

**Installation method** 
 Docker 

**Host OS (for Docker installations)**
 Ubuntu 18.10

**Describe the bug**
 Cannot login

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment] 2019-03-11 17:41
@danielrodrigotest Can you update your installation again? That should resolve the issue.

**Comment by SlvrEagle23** [comment] 2019-03-13 19:06
@danielrodrigotest Please let me know if the changes in the most recent updates fixed your issue so I can close this issue. Thanks!

**Comment by danielrodrigotest** [comment] 2019-03-13 21:58
It has the same problem. As a solution, I had to login as SSH and had to create a temporary password. Later, I logged into the platform and then, I set another new password. I tested with another admin account (backup account)

**Comment by SlvrEagle23** [comment] 2019-03-14 00:53
@danielrodrigotest As long as you were able to recover your account, that's good. We probably can't figure out what the cause of the original issue was now that the password has reset. Just let me know if it happens again.

**Closed by SlvrEagle23** 2019-03-14 00:53 UTC
Labels: bug, in progress
