### ISSUE TITLE
update.sh failed and broke all

### ISSUE THREAD

**Issue by EBII** [AzuraCast/AzuraCast#194] opened 2017-07-21 15:19 UTC
hello 
i recently install azuracast and i like it! may be three month

i try to update 
but it failed and now all is broken with missing table in mysql 

i try in root
./update.sh
./update.sh --full
./update.sh --limit @/var/azuracast/www/util/ansible/update.retry

the error message : 
TASK [azuracast-update : Clear AzuraCast Cache] *********************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/util/cli.php cache:clear", "delta": "0:00:00.191443", "end": "2017-07-21 17:09:10.514057", "failed": true, "rc": 1, "start": "2017-07-21 17:09:10.322614", "stderr": "\n                            \n  [RedisException]          \n  read error on connection  \n                            \n\ncache:clear", "stderr_lines": ["", "                            ", "  [RedisException]          ", "  read error on connection  ", "                            ", "", "cache:clear"], "stdout": "Router cache file cleared.", "stdout_lines": ["Router cache file cleared."]}
RUNNING HANDLER [azuracast-cron : restart cron] *********************************************************************************************************************************************
	to retry, use: --limit @/var/azuracast/www/util/ansible/update.retry

PLAY RECAP **********************************************************************************************************************************************************************************
localhost                  : ok=61   changed=15   unreachable=0    failed=1 
i will restore my container ...

**Comment by derkalle4** [comment] 2017-07-21 17:43
Same on my installation with latest update.sh executed some seconds ago. And after that an SQL error occured if I want to open the main page of a single station.
```
Doctrine \ DBAL \ Exception \ InvalidFieldNameException
An exception occurred while executing 'SELECT s0_.id AS id_0, s0_.song_id AS song_id_1, s0_.station_id AS station_id_2, s0_.playlist_id AS playlist_id_3, s0_.media_id AS media_id_4, s0_.request_id AS request_id_5, s0_.timestamp_cued AS timestamp_cued_6, s0_.sent_to_autodj AS sent_to_autodj_7, s0_.timestamp_start AS timestamp_start_8, s0_.duration AS duration_9, s0_.listeners_start AS listeners_start_10, s0_.timestamp_end AS timestamp_end_11, s0_.listeners_end AS listeners_end_12, s0_.unique_listeners AS unique_listeners_13, s0_.delta_total AS delta_total_14, s0_.delta_positive AS delta_positive_15, s0_.delta_negative AS delta_negative_16, s0_.delta_points AS delta_points_17, s1_.id AS id_18, s1_.station_id AS station_id_19, s1_.track_id AS track_id_20, s1_.timestamp AS timestamp_21, s1_.played_at AS played_at_22, s1_.ip AS ip_23, s2_.id AS id_24, s2_.station_id AS station_id_25, s2_.name AS name_26, s2_.type AS type_27, s2_.is_enabled AS is_enabled_28, s2_.play_per_songs AS play_per_songs_29, s2_.play_per_minutes AS play_per_minutes_30, s2_.schedule_start_time AS schedule_start_time_31, s2_.schedule_end_time AS schedule_end_time_32, s2_.play_once_time AS play_once_time_33, s2_.weight AS weight_34, s2_.include_in_automation AS include_in_automation_35, s3_.id AS id_36, s3_.text AS text_37, s3_.artist AS artist_38, s3_.title AS title_39, s3_.created AS created_40, s3_.play_count AS play_count_41, s3_.last_played AS last_played_42 FROM song_history s0_ LEFT JOIN station_requests s1_ ON s0_.request_id = s1_.id LEFT JOIN station_playlists s2_ ON s0_.playlist_id = s2_.id LEFT JOIN songs s3_ ON s0_.song_id = s3_.id WHERE s0_.station_id = ? AND s0_.timestamp_start >= ? AND s0_.listeners_start IS NOT NULL ORDER BY s0_.timestamp_start ASC' with params [1, "1500063767"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 's0_.sent_to_autodj' in 'field list'
```

**Comment by SlvrEagle23** [comment] 2017-07-21 19:09
@derkalle4 No no, don't manually go executing DB migrations. The migration engine will get out of date and you run the definite risk of hosing your entire installation.

Once again we have my very favorite situation happening here, where _not a single instance that I manage_ is demonstrating this issue, and yet multiple that I don't are.

I'm looking into it, but as of yet I can't reproduce the problem. Seems like it might be related to Redis's timeout settings.

**Comment by SlvrEagle23** [comment] 2017-07-21 19:17
Let's see if we can at least get some common ground between the folks experiencing the problem.

Would you all mind posting:
 - Host OS (14.04, 16.04)
 - Host architecture (x64/arm/etc)
 - Host location (VPS provider, if applicable)

**Comment by derkalle4** [comment] 2017-07-21 19:26
@SlvrEagle23 I can grant you access via Teamviewer to an SSH-Session of my server if needed. I can't give you (for security reasons) complete access to this machine. Of course a backup would be possible because it's not productive atm. If that's something for you just contact me privately. We will find a time slot.

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"

Virtualization: Proxmox 4 -> x64 architecture (container based virtualization)
Host location: webtropia, düsseldorf, germany (dedicated server)

**Comment by SlvrEagle23** [comment] 2017-07-21 20:03
@EBII @griffon56 @derkalle4 Welp...this one's probably a silly mistake on my part.

I mistook the third argument in the Redis connection parameters as the default _time to live_ for any cache entries that didn't have one set (since all do, it was set very low, 0.1 seconds)...the third argument is actually the default _timeout_ when making any connection.

My servers happen to be speedy enough that they can get in a Redis cache flush in 0.1 seconds, but it's quite reasonable to think it might take a little longer. I bumped the number up, and that should resolve the issue.

Sorry for the inconvenience everyone! Your updates should continue without issue now.

**Comment by SlvrEagle23** [comment] 2017-07-22 00:39
If anyone who was having the issue previously could let me know if this latest fix helps, or if the error is persisting, please let me know so I can close out the ticket or continue investigating.

**Comment by derkalle4** [comment] 2017-07-22 06:46
Okay so the error changed. I deleted my own created table before so at least the environment should be consistant. It somehow does not create the table only trying to add an missing column. So maybe there's a missing check if this table already exists.

```
TASK [azuracast-update : Update Database] ***************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/util/cli.php migrations:migrate --no-interaction --allow-no-migration", "delta": "0:00:00.094727", "end": "2017-07-22 06:43:45.218286", "failed": true, "rc": 1, "start": "2017-07-22 06:43:45.123559", "stderr": "\n                                                                               \n  [Doctrine\\DBAL\\Exception\\TableNotFoundException]                             \n  An exception occurred while executing 'ALTER TABLE song_history ADD sent_to  \n  _autodj TINYINT(1) NOT NULL':                                                \n  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.song_h  \n  istory' doesn't exist                                                        \n                                                                               \n\n                                                                               \n  [Doctrine\\DBAL\\Driver\\PDOException]                                          \n  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.song_h  \n  istory' doesn't exist                                                        \n                                                                               \n\n                                                                               \n  [PDOException]                                                               \n  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.song_h  \n  istory' doesn't exist                                                        \n                                                                               \n\nmigrations:migrate [--write-sql] [--dry-run] [--query-time] [--allow-no-migration] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--] [<version>]", "stderr_lines": ["", "                                                                               ", "  [Doctrine\\DBAL\\Exception\\TableNotFoundException]                             ", "  An exception occurred while executing 'ALTER TABLE song_history ADD sent_to  ", "  _autodj TINYINT(1) NOT NULL':                                                ", "  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.song_h  ", "  istory' doesn't exist                                                        ", "                                                                               ", "", "                                                                               ", "  [Doctrine\\DBAL\\Driver\\PDOException]                                          ", "  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.song_h  ", "  istory' doesn't exist                                                        ", "                                                                               ", "", "                                                                               ", "  [PDOException]                                                               ", "  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.song_h  ", "  istory' doesn't exist                                                        ", "                                                                               ", "", "migrations:migrate [--write-sql] [--dry-run] [--query-time] [--allow-no-migration] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--] [<version>]"], "stdout": "Loading configuration from the integration code of your framework (setter).\n                                                                    \n                    Doctrine Database Migrations                    \n                                                                    ", "stdout_lines": ["Loading configuration from the integration code of your framework (setter).", "                                                                    ", "                    Doctrine Database Migrations                    ", "                                                                    "]}
```

**Comment by SlvrEagle23** [comment] 2017-07-22 06:49
@derkalle4 This is exactly why I don't advise manually updating the database schema; AzuraCast keeps its own internal log of the DB schema's state so it can ensure it's always the latest version, and it will invariably cause problems to throw the DB out of whack with its expectations.

In this case, you should be able to create the table (minus the `sent_to_autodj` field) and let the migration script add the missing field. You'll have to play around a bit with it, or otherwise resynchronize the schema with a fresh install.

**Comment by derkalle4** [comment] 2017-07-22 06:58
@SlvrEagle23 thank you it's now working. But I needed to create the table. Maybe it wasn't working because I manually created and deleted the table. But the table shouldn't even get deleted after an update. That's what I did not understand.

If someone did the same messy stuff like me just delete and create the following table (use at your own risk, read twice before doing!):

```
CREATE TABLE song_history (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
song_id varchar(50) ,
station_id int(11) not null,
playlist_id int(11) null,
media_id int(11) null,
request_id int(11) null,
timestamp_cued int(11) null,
timestamp_start int(11) not null,
duration int(11) null,
listeners_start int(11) null,
timestamp_end int(11) not null,
listeners_end int(11) null,
unique_listeners int(11) null,
delta_total smallint not null,
delta_positive smallint not null,
delta_negative smallint not null,
delta_points smallint null
)ENGINE=INNODB;
```

**Comment by griffon56** [comment] 2017-07-22 07:24
The database now updates successfully :-)

**Comment by SlvrEagle23** [comment] 2017-07-22 07:24
@griffon56 Thank you for the update! Closing this issue.

**Closed by SlvrEagle23** 2017-07-22 07:24 UTC
Labels: bug
