### ISSUE TITLE
Be able to go forward in a file played in backend

### ISSUE THREAD

**Issue by rubensben** [AzuraCast/AzuraCast#1186] opened 2019-02-18 19:12 UTC
Hi AzuraCast team and amazed to see the great work  ! Here Rubens, from the SolarSoundSystem.org (we are building a network of sustainable sound systems) and also have a solar powered radio, Radio3s.org that I'm taking care of. I just switched from Airtime to Azuracast as the airtime dev was pretty dead and could not work on Ubuntu 12+ and realize they are some features that would improve greatly the platform 

Feature #002 : As in Airtime, it would be great to be able to select the time of the song played (only for preview mode) in order to know quicker if the song match for the playlist we want to include in (or not)

I'm adding other features as independent Issues as I've understood it's more practical development-wize. 
BEST !

**Comment by SlvrEagle23** [comment] 2019-02-19 00:27
This is a duplicate of #895. Please check existing issues before submitting new ones. Thanks!

**Closed by SlvrEagle23** 2019-02-19 00:27 UTC
