### ISSUE TITLE
Song Playback Timeline not working for any songs played "this morning"

### ISSUE THREAD

**Issue by MarkWasley** [AzuraCast/AzuraCast#4591] opened 2021-09-19 01:42 UTC
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #cbf1b7e (2021-09-16 18:50)

### What happened?

This is a strange one. The song playback timeline won't display any songs played "this morning". I am in New Zealand and this is what my station time zone is set to, so "this morning" is between 12pm - 12am UTC. This is also applicable on the demo installation. After 12pm (or 12am), all songs played today are displayed.

It also would be nice to be able to change the date format on this page and in other places where the date is used and displayed in the application. This would ideally be done by adding a date format box alongside the time zone in the Edit Station form.

**Comment by MarkWasley** [comment] 2022-01-13 00:24
This is still an issue, to date. The calendar appears to use UTC time.

Selecting a time period manually will provide data beginning from the day before you selected to start, to the day before you selected to end. For example, selecting from January 9 to January 13 will provide an API response as `/api/station/1/history?start=2022-01-08&end=2022-01-12&internal=true&rowCount=10&current=1&flushCache=true`.

**Comment by SlvrEagle23** [comment] 2022-01-14 11:59
@MarkWasley I'm struggling to reproduce this locally, even if I set the station's timezone to Auckland time, it seems to be functioning as expected.

I'm curious if this has something to do with the browser's timezone, and mine just isn't triggering it because my default timezone is UTC-5 (US/Chicago).

**Comment by flashradio** [comment] 2022-01-14 19:01
since the new update the station go silence

**Comment by flashradio** [comment] 2022-01-14 19:02
And do not working when I restart the station

**Comment by flashradio** [comment] 2022-01-14 19:06
Still on stream offline but does not soung

**Comment by flashradio** [comment] 2022-01-14 19:10
I mean does not sound, sorry

**Comment by SC2Mitch** [comment] 2022-01-14 19:15
@flashradio please create a new issue, this isn't the place to discuss other issues other than `Song playback timeline`

**Comment by flashradio** [comment] 2022-01-14 19:27
ok

**Comment by flashradio** [comment] 2022-01-14 19:28
Sorry but I m new here and does not know the plataform yet

**Comment by MarkWasley** [comment] 2022-01-15 04:50
@SlvrEagle23 I think you might be onto something. I used a Google Chrome extension to change my timezone to somewhere where it was the morning, which altered the data displayed and the menu clock. Changing my timezone on Windows didn't seem to do anything, but when I changed the date manually to a couple of days ago, the data and calendar recognised that date as "today" and used that to calculate what date was "yesterday", "last 7 days" etc...

Are you able to check when it is the morning in your timezone, please?

**Comment by SlvrEagle23** [comment] 2022-01-15 06:42
@MarkWasley Aha, I think I figured it out...the Datepicker Vue control has a default "ranges" value that depended on another property, but the other property wasn't available at the time the default was provided. I've moved it to be calculated later, which should mean that it's taking the proper timezone into account; that should help quite a lot with the date ranges.

**Comment by flashradio** [comment] 2022-01-15 17:32
Thanks. Its ok now. I update all playlists and seem to work on right
Miguel

**Comment by flashradio** [comment] 2022-01-15 17:44
Awesome, thanks!

**Comment by MarkWasley** [comment] 2022-01-15 23:36
@SlvrEagle23 Unfortunately, this didn't solve the issue. This morning, the timeline is only showing API data for yesterday, January 15. By default, the Datepicker is showing January 3 - January 16, but as mentioned above the API endpoint is for January 2 to January 15. This is persisting to 1pm UTC+13, so the start of the day UTC. "Today" button provides data for January 15, "Yesterday" for January 14 etc... I know the Datepicker is JavaScript, but it would be helpful if it was based on server time.

Could you also add please add the ability to change the date format throughout the application? In New Zealand we use a DD/MM/YYYY format, so the current American month first format can be a little annoying at times, I'm afraid. There's also the situation of the application log using UTC time. I'm not sure if this could be set to use a "master" application timezone?

@flashradio Could you kindly keep comments relating to your separate issue, in the relevant issue thread. Your comments are somewhat of a distraction to solving this issue and also get emailed to me as you have participated in this thread. I'm sure the AzuraCast team will be happy to help you and diagnose your issue in the relevant issue thread.

**Comment by SlvrEagle23** [comment] 2022-01-16 01:05
@MarkWasley The separate feature requests are independent from this and should be submitted over at https://features.azuracast.com/ just to ensure we can properly keep track of them. We've had many requests to add date/time formatting options, so we intend to add them at some point in the future.

If you manually pick Jan 16 on the datepicker, do you properly see the "missing" items?

**Comment by MarkWasley** [comment] 2022-01-16 01:47
@SlvrEagle23 Not before 1pm. Clicking the date manually (and any of the tabs) will still output the tracks for the day before desired from the database.

I thought adding date formatting would be a quick addition while on a similar wavelength, but I can be patient 🙂

**Comment by SlvrEagle23** [comment] 2022-01-16 01:50
@MarkWasley Adding a station-wide or system-wide setting is never necessarily a "quick addition", so yes, please submit a feature request.

So, to confirm, your station's timezone is also Auckland?

**Comment by MarkWasley** [comment] 2022-01-16 01:54
@SlvrEagle23 OK, I'll submit a feature request. Yes, it is.

**Comment by SlvrEagle23** [comment] 2022-01-16 09:14
@MarkWasley I'm looking into this a little deeper, and unfortunately it looks like our "Date Range Picker" isn't locale-aware and always defaults to the time zone that the browser prefers, which may not always match up with the station's time zone. This causes the adjustment back-and-forth between the browser-preferred date/times and the station time zones to be bumpy, especially if they depart as much from UTC as Auckland does.

I'm not sure that there's an immediate solution to this; replacing the library or modifying it would be the real solution, but I can't find any other datepicker libraries for VueJS 2 that _are_ locale-aware in the way we're needing.

On the flipside, we could just accept that the date range we're getting from the client is always going to be their browser's preferred timezone, and just do the adjustment on the server side by providing another parameter like "tz" that specifies the user's browser timezone. In any case, this would yield results that differ from what you're expecting, i.e. if you pick "Today" in your browser's timezone, you're really going to get "Today" in the station's timezone, which may or may not be the same (or what you're wanting).

**Comment by SlvrEagle23** [comment] 2022-04-08 05:40
@MarkWasley I updated the "Listeners" and "Station Playback Timeline" report pages to use your local timezone for its reporting, which in my testing fixed the issue with missing gaps in playback history. If you update to the latest Rolling Release version, you can help confirm that this issue is resolved for you as well. Thank you!

**Comment by flashradio** [comment] 2022-04-09 14:25
Its fixed now. Thanks

**Closed** 2022-04-09 14:43 UTC
Labels: bug, in progress, upstream, stable, rolling-release

**Comment by flashradio** [comment] 2022-04-11 06:23
Thank you!

**Comment by MarkWasley** [comment] 2022-04-11 10:49
@SlvrEagle23 I have seen your update and the issue has been fixed, thank you. The Date Range Picker needs to select and provide data from midnight to the end of the day at midnight. The tabs' (and calendar) current behaviour is providing data from the last 24 hours, last 48 hours etc... not day to day as has been the case up to present and what is desired. I can select the correct time underneath the calendar, but this should be set as default, as it always has been.

**Comment by flashradio** [comment] 2022-04-11 19:50
Thank you!
