### ISSUE TITLE
Help Please

### ISSUE THREAD

**Issue by reans** [AzuraCast/AzuraCast#227] opened 2017-09-08 12:09 UTC
I have a problem of my AzuraCast after the update. Before the update i used 64kbps bitrate in my stream but after I update my azuracast the 64kbps bit rate no more sound output in http://url:port/ and even in http://url:port/radio.mp3 it shows not supported. Ill change to 32kbps bitrate but still thesame no sound. but when I try to 96 and 128kbps there is sound. Anyone can help to fixed the issue? I try to fresh install the azuracast but still thesame the 32 and 64 kbps bitrate no sound output in the web.

**Comment by SlvrEagle23** [comment] 2017-09-18 03:30
@reans What radio frontend are you using? Icecast or Shoutcast?

**Comment by reans** [comment] 2017-09-18 04:29
sir, im using shoutcast, 32 and 64 no sound and the web player is error but when i try to icecast 32 and 64 is working fine. but 96 and 128 is working in shoutcast stream.

**Comment by SlvrEagle23** [comment] 2017-09-25 07:13
@reans Unfortunately, I'm not able to reproduce this in my testing environment. All bitrates work equally well in my setup, without any issues with the lower bitrates.

In my testing, however, I did notice one issue that may cause this problem: if any one of your mount points is specified as "public" (i.e. advertising to the YP directory), but the other ones _aren't_, ShoutCast will shut off the ones that aren't. Basically, the "public" flag is an "all or nothing" setting that has to be set across all streams or some streams won't work.

I'm closing this issue as I can't reproduce it locally, but you should look into the above issue, as it is specific to ShoutCast only and may cause the problem you're experiencing.

**Closed by SlvrEagle23** 2017-09-25 07:13 UTC
Labels: help wanted
