### ISSUE TITLE
AzuraCast is Live! AzuraCast.com

### ISSUE THREAD

**Issue by pwrj** [AzuraCast/AzuraCast#4906] opened 2021-12-21 01:20 UTC
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

v0.14.1

### What happened?

Somehow the error.mp3 (AzuraCast is Live!) file keeps on playing eventhough I have an active playlist with songs in there. See log below. Help please....

### Relevant log output

```shell
2021/12/20 20:02:01 >>> LOG START
2021/12/20 20:01:57 [main:3] Liquidsoap 2.0.1
2021/12/20 20:01:57 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.4.6 sedlex=2.3 menhirLib=20210419 curl=0.9.1 dtools=0.4.4 duppy=0.9.2 cry=0.6.5 mm=0.7.2 xmlplaylist=0.1.5 lastfm=0.3.3 ogg=0.7.0 ogg.decoder=0.7.0 vorbis=0.8.0 vorbis.decoder=0.8.0 opus=0.2.0 opus.decoder=0.2.0 speex=0.4.0 speex.decoder=0.4.0 mad=0.5.1 flac=0.3.0 flac.ogg=0.3.0 flac.decoder=0.3.0 dynlink=[distributed with Ocaml] lame=0.3.4 shine=0.2.2 frei0r=0.1.2 fdkaac=0.3.2 theora=0.4.0 theora.decoder=0.4.0 ffmpeg-avutil=1.1.0 ffmpeg-avcodec=1.1.0 ffmpeg-avdevice=1.1.0 ffmpeg-av=1.1.0 ffmpeg-avfilter=1.1.0 ffmpeg-swresample=1.1.0 ffmpeg-swscale=1.1.0 bjack=0.1.6 alsa=0.3.0 ao=0.2.3 samplerate=0.1.6 taglib=0.3.7 ssl=0.5.9 magic=0.7.3 camomile=1.0.2 inotify=2.3 yojson=1.7.0 faad=0.5.0 soundtouch=0.1.9 portaudio=0.2.2 pulseaudio=0.1.4 ladspa=0.2.0 dssi=0.1.3 tsdl=v0.9.8 tsdl_ttf=0 camlimages=4.2.6 cohttp-lwt-unix=2.5.5 prometheus-app=1.1 srt.constants=0.2.1 srt.types=0.2.1 srt.stubs=0.2.1 srt.stubs.locked=0.2.1 srt=0.2.1 lo=0.2.0 gd=1.0a5
2021/12/20 20:01:59 [clock:3] Using builtin (low-precision) implementation for latency control
2021/12/20 20:02:01 [playlist.basic:3] Wrong mime type application/csv for playlist!
2021/12/20 20:02:01 [playlist.basic:3] Wrong mime type application/csv for playlist!
2021/12/20 20:02:01 [playlist.basic:3] Wrong mime type application/csv for playlist!
2021/12/20 20:02:01 [playlist.basic:3] Wrong mime type application/csv for playlist!
2021/12/20 20:02:01 [playlist.basic:3] Wrong mime type application/csv for playlist!
2021/12/20 20:02:01 [playlist parser:3] No format found
2021/12/20 20:02:01 [playlist.basic:3] Wrong mime type application/csv for playlist!
2021/12/20 20:02:01 [playlist.basic:3] Wrong mime type application/csv for playlist!
2021/12/20 20:02:01 [playlist.basic:3] Wrong mime type application/csv for playlist!
2021/12/20 20:02:01 [playlist.basic:3] Wrong mime type application/csv for playlist!
2021/12/20 20:02:01 [playlist.basic:3] Wrong mime type application/csv for playlist!
2021/12/20 20:02:01 [playlist parser:3] No format found
2021/12/20 20:02:01 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz main.
2021/12/20 20:02:01 [frame:3] Video frame size set to: 1280x720
2021/12/20 20:02:01 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2021/12/20 20:02:01 [frame:3] Targeting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2021/12/20 20:02:01 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2021/12/20 20:02:01 [sandbox:3] Running inside a docker container, disabling sandboxing.
2021/12/20 20:02:01 [video.converter:3] Using preferred video converter: ffmpeg.
2021/12/20 20:02:01 [audio.converter:3] Using samplerate converter: ffmpeg.
2021/12/20 20:02:01 [harbor:3] Adding mountpoint '/' on port 8015
2021/12/20 20:02:01 [error_jingle:3] /usr/local/share/icecast/web/error.mp3 is static, resolving once for all...
2021/12/20 20:02:01 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 2).
2021/12/20 20:02:01 [local_1:3] Connecting mount sid#1 for @127.0.0.1...
2021/12/20 20:02:01 [local_1:3] Connection setup was successful.
2021/12/20 20:02:01 [clock.main:3] Streaming loop starts in auto-sync mode
2021/12/20 20:02:01 [clock.main:3] Delegating synchronisation to CPU clock
2021/12/20 20:02:01 [dummy:3] Source failed (no more tracks) stopping output...
2021/12/20 20:02:01 [output.file_0:3] Source failed (no more tracks) stopping output...
2021/12/20 20:02:01 [safe_fallback:3] Switch to error_jingle.
2021/12/20 20:02:28 [decoder:2] Decoding "/usr/local/share/icecast/web/error.mp3" ended: Mad.End_of_stream.
2021/12/20 20:02:29 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 2).
2021/12/20 20:02:56 [decoder:2] Decoding "/usr/local/share/icecast/web/error.mp3" ended: Mad.End_of_stream.
2021/12/20 20:02:56 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 2).
2021/12/20 20:03:23 [decoder:2] Decoding "/usr/local/share/icecast/web/error.mp3" ended: Mad.End_of_stream.
2021/12/20 20:03:24 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 2).
2021/12/20 20:03:51 [decoder:2] Decoding "/usr/local/share/icecast/web/error.mp3" ended: Mad.End_of_stream.
2021/12/20 20:03:51 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 2).
2021/12/20 20:04:18 [decoder:2] Decoding "/usr/local/share/icecast/web/error.mp3" ended: Mad.End_of_stream.
2021/12/20 20:04:19 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 2).
2021/12/20 20:04:46 [decoder:2] Decoding "/usr/local/share/icecast/web/error.mp3" ended: Mad.End_of_stream.
2021/12/20 20:04:46 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 2).
2021/12/20 20:05:14 [decoder:2] Decoding "/usr/local/share/icecast/web/error.mp3" ended: Mad.End_of_stream.
2021/12/20 20:05:14 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 2).
2021/12/20 20:05:41 [decoder:2] Decoding "/usr/local/share/icecast/web/error.mp3" ended: Mad.End_of_stream.
2021/12/20 20:05:42 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 2).
2021/12/20 20:06:09 [decoder:2] Decoding "/usr/local/share/icecast/web/error.mp3" ended: Mad.End_of_stream.
2021/12/20 20:06:09 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 2).
2021/12/20 20:06:36 [decoder:2] Decoding "/usr/local/share/icecast/web/error.mp3" ended: Mad.End_of_stream.
2021/12/20 20:06:37 [server:3] New client: 172.28.0.5.
2021/12/20 20:06:37 [server:3] Client 172.28.0.5 disconnected.
2021/12/20 20:06:37 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 2).
2021/12/20 20:07:04 [decoder:2] Decoding "/usr/local/share/icecast/web/error.mp3" ended: Mad.End_of_stream.
2021/12/20 20:07:04 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 2).
2021/12/20 20:07:31 [decoder:2] Decoding "/usr/local/share/icecast/web/error.mp3" ended: Mad.End_of_stream.
2021/12/20 20:07:32 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 2).
2021/12/20 20:07:59 [decoder:2] Decoding "/usr/local/share/icecast/web/error.mp3" ended: Mad.End_of_stream.
2021/12/20 20:07:59 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 2).
2021/12/20 20:08:26 [decoder:2] Decoding "/usr/local/share/icecast/web/error.mp3" ended: Mad.End_of_stream.
2021/12/20 20:08:27 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 2).
2021/12/20 20:08:54 [decoder:2] Decoding "/usr/local/share/icecast/web/error.mp3" ended: Mad.End_of_stream.
2021/12/20 20:08:54 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 2).
2021/12/20 20:09:22 [decoder:2] Decoding "/usr/local/share/icecast/web/error.mp3" ended: Mad.End_of_stream.
2021/12/20 20:09:22 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 2).
2021/12/20 20:09:49 [decoder:2] Decoding "/usr/local/share/icecast/web/error.mp3" ended: Mad.End_of_stream.
2021/12/20 20:09:50 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 2).
2021/12/20 20:10:17 [decoder:2] Decoding "/usr/local/share/icecast/web/error.mp3" ended: Mad.End_of_stream.
2021/12/20 20:10:17 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 2).
2021/12/20 20:10:44 [decoder:2] Decoding "/usr/local/share/icecast/web/error.mp3" ended: Mad.End_of_stream.
2021/12/20 20:10:45 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 2).
2021/12/20 20:11:12 [decoder:2] Decoding "/usr/local/share/icecast/web/error.mp3" ended: Mad.End_of_stream.
2021/12/20 20:11:12 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 2).
2021/12/20 20:11:39 [decoder:2] Decoding "/usr/local/share/icecast/web/error.mp3" ended: Mad.End_of_stream.
2021/12/20 20:11:40 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 2).
2021/12/20 20:12:07 [decoder:2] Decoding "/usr/local/share/icecast/web/error.mp3" ended: Mad.End_of_stream.
2021/12/20 20:12:07 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 2).
2021/12/20 20:12:34 [decoder:2] Decoding "/usr/local/share/icecast/web/error.mp3" ended: Mad.End_of_stream.
2021/12/20 20:12:35 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 2).
2021/12/20 20:13:02 [decoder:2] Decoding "/usr/local/share/icecast/web/error.mp3" ended: Mad.End_of_stream.
2021/12/20 20:13:03 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 2).
2021/12/20 20:13:30 [decoder:2] Decoding "/usr/local/share/icecast/web/error.mp3" ended: Mad.End_of_stream.
2021/12/20 20:13:30 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 2).
2021/12/20 20:13:57 [decoder:2] Decoding "/usr/local/share/icecast/web/error.mp3" ended: Mad.End_of_stream.
2021/12/20 20:13:58 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 2).
```

**Comment by SlvrEagle23** [comment] 2021-12-21 09:38
Closing as duplicate of #4897.

**Closed by SlvrEagle23** 2021-12-21 09:38 UTC
Labels: needs investigation

**Comment by pwrj** [comment] 2021-12-21 21:48
@SlvrEagle23 If this issue was addressed or solved, please point me to it. I'm still having the issue.....
