### ISSUE TITLE
Scheduled playlist do not play.

### ISSUE THREAD

**Issue by Seehed** [AzuraCast/AzuraCast#5675] opened 2022-08-14 09:08 UTC
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.17.3 Stable

### What happened?

I have scheduled a  playlist to play at a time, and when It comes to that time, it doesn't play the playlist at all, I enabled it, and disabled the Interrupt other songs to play at the scheduled time option, but it doesn't fix it. I run a national live show, and scheduling the playlist for it is very important for me.

**Comment by SlvrEagle23** [comment] 2022-08-15 01:28
Duplicate of #5632 .

**Closed by SlvrEagle23** 2022-08-15 01:28 UTC
Labels: needs investigation
