### ISSUE TITLE
AutoDJ - duplicate artist avoidance does not work properly

### ISSUE THREAD

**Issue by Abqehebter** [AzuraCast/AzuraCast#3957] opened 2021-03-31 14:06 UTC
**Using Docker installation method**
Yes.

**AzuraCast version**
Rolling Release #3419e58 (2021-03-31 5:36)

**Host Operating System**
Ubuntu 20.04 (2x) + Debian 9/10

**Describe the bug**
As described in the issue https://github.com/AzuraCast/AzuraCast/issues/3863 below, Artist avoidance no longer works correctly. I have a lot of the same artists at the end of the shuffle playlists, so it can't avoid them.

Example: My playlist runs through the 400 songs, at the end there are only 10 songs left, where 3-4 times the artist "Calvin Harris" is still in there - It just runs through this list without reshuffling the shuffle list (See logs, there is no "Duplicate prevention yielded no playable song; resetting song queue." log entry since the last rolling release updates for this.

**To Reproduce**
1. Go to Dashboard
2. Click on 'Administration'
3. Click on 'System Debugger'
4. Go to your station
5. Click on 'Rebuild AutoDJ Queue (Run Test)' > Until he has almost finished the playlist.
6. Go to your stations manage page
7. Click on 'More' > 'Playback Queue'
8. See if the same artists are still present
9. Check the station queue/history to see if he will let it play through

**Expected behavior**
According to the log, it hardly checks if there are too many of the same artists at the end, so it likes to play the same artist 3-4 times within a very short time at the end of the shuffle playlist.

Cause I can not judge exactly, according to my opinion, it may also be due to the internal AutoDJ History (https://github.com/AzuraCast/AzuraCast/commit/e8111cb88c074527c61cb031078722d82385d000), which has been added. Only the funny current is that he checks it with some playlists and with most just not or the check from the last update to it (https://github.com/AzuraCast/AzuraCast/commit/d2e4b621dd91f77b84883b66fbb24b588d88c095) fails somewhere.

I've definitely tested/checked it with a total of 4 servers, even had one AzuraCast instance reinstalled as well and one completely rebuilt.
I also tried it on one of my 4 servers without directories. The problem exists everywhere.

My **To Reproduce** procedure also reflects the normal daily routine of the playlist - Only thus it can be better or faster readjust.

**Relevant Logs**
```
[2021-03-31T13:32:31.684880+00:00] AzuraCast.NOTICE: Running sync task: "Aktuell läuft" Daten {"force":false} []
[2021-03-31T13:32:46.679892+00:00] AzuraCast.NOTICE: Running sync task: "Aktuell läuft" Daten {"force":false} []
[2021-03-31T13:33:01.312733+00:00] AzuraCast.NOTICE: Running sync task: 1-Minute Sync {"force":false} []
[2021-03-31T13:33:01.313737+00:00] AzuraCast.NOTICE: Running sync task: "Aktuell läuft" Daten {"force":false} []
[2021-03-31T13:33:16.311366+00:00] AzuraCast.NOTICE: Running sync task: "Aktuell läuft" Daten {"force":false} []
[2021-03-31T13:33:31.307547+00:00] AzuraCast.NOTICE: Running sync task: "Aktuell läuft" Daten {"force":false} []
[2021-03-31T13:33:46.311023+00:00] AzuraCast.NOTICE: Running sync task: "Aktuell läuft" Daten {"force":false} []
[2021-03-31T13:34:02.064272+00:00] AzuraCast.NOTICE: Running sync task: 1-Minute Sync {"force":false} []
[2021-03-31T13:34:02.065156+00:00] AzuraCast.NOTICE: Running sync task: "Aktuell läuft" Daten {"force":false} []
[2021-03-31T13:34:17.059302+00:00] AzuraCast.NOTICE: Running sync task: "Aktuell läuft" Daten {"force":false} []
```

**Screenshots**
![image](https://user-images.githubusercontent.com/42640247/113156269-1dc2db80-923a-11eb-9ea5-f52cf4782dd8.png)
![image](https://user-images.githubusercontent.com/42640247/113156667-7befbe80-923a-11eb-8a94-1198a108472d.png)

**Comment by Abqehebter** [comment] 2021-04-02 23:51
Well... what can I do about it @Vaalyn? Can't anyone recreate this? That is strongly difficult to have to run 3x the same artist to the end....

**Comment by MarkWasley** [comment] 2021-04-03 06:52
@Abqehebter Liam, I have [replied](https://github.com/AzuraCast/AzuraCast/issues/3863#issuecomment-812822849) to you on my  issue. In short, this is expected behaviour on all random and shuffled playlists and I have explained there the order of how duplicate prevention works.

**Comment by Abqehebter** [comment] 2021-04-03 10:23
@MarkWasley Ha. I haven't seen it. Thanks I will read it :)

**Comment by Vaalyn** [comment] 2021-04-23 16:00
I'm closing this issue since it looks like it has been resolved from looking at the comment on the thread that was linked to by Mark.

**Closed by Vaalyn** 2021-04-23 16:00 UTC
Labels: error
