### ISSUE TITLE
The WebDJ feature doesn't work: "ReferenceError: Webcast is not defined"

### ISSUE THREAD

**Issue by jhackett1** [AzuraCast/AzuraCast#3323] opened 2020-10-24 17:22 UTC
Hello,

When I try to use WebDJ, I get an error in the browser console after hitting the "Start streaming" button:

```
ReferenceError: Webcast is not defined
```

It seems to be failing on the code:

```
var encoder = (new Webcast.Encoder.Mp3({
  bitrate: 256,
  channels: 2,
  samplerate: 44100
 }));
```

The button changes to "stop streaming" and there's no indication in the UI that anything has gone wrong.

Why would this be?

**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #fb4f7de (2020-10-15 10:01) • Docker • PHP 7.4 

**Host Operating System**
Ubuntu

**To Reproduce**
1. Go to WebDJ
2. Enter username and password
3. Hit "start streaming"

**Expected behavior**
The stream starts and I can hear it on the radio

**Device(s):**
Found so far in Firefox and Chrome browsers

**Comment by jhackett1** [comment] 2020-10-24 17:28
just noticed that this only seems to happen if "Use Asynchronous Worker" is ticked, but even without that ticked it seems to fail silently (meaning that even though webdj claims to be streaming, the audio can't be heard on the radio.

**Comment by SC2Mitch** [comment] 2020-10-26 22:45
Taking a look, will give my findings in a moment.

**Comment by Vaalyn** [comment] 2020-10-29 19:44
I've been able to reproduce this problem on my test installation.
Not sure yet what exactly is missing / going wrong here.

**Comment by jaleeldgk** [comment] 2020-10-29 20:26
Did you notices that there is no notification or error or success when clicking on start streaming.
Either your credentials are correct or wrong it does nothing.
It should show notification that you are live or wrong credentials or any other.
I

**Comment by Vaalyn** [comment] 2020-10-29 20:29
> Did you notices that there is no notification or error or success when clicking on start streaming.
> Either your credentials are correct or wrong it does nothing.
> It should show notification that you are live or wrong credentials or any other.
> I

Yes, but I have not yet looked into why it's not working as intended.

**Comment by jhackett1** [comment] 2020-10-30 13:58
![Untitled(5)](https://user-images.githubusercontent.com/14189497/97713138-573ec180-1ab7-11eb-99c1-977913886d47.gif)

still having the issue, sadly. 

i only see the error in the console if i have "use asynchronous worker" selected. if that's not selected, it still seems to fail - azuracast doesn't detect any incoming stream.

i can stre

**Comment by Vaalyn** [comment] 2020-10-30 18:16
> still having the issue, sadly.

We have not released a fix for this problem so this is expected to still be a problem.

In the meantime we've most likely identified the issue to be because the JavaScript library for the Webcast protocol is automatically initializing an `AudioContext` on page load which is not allowed anymore on modern browsers.

We need to look into restructuring that library so that this `AudioContext` is only created after a user interaction because this is how modern browsers want that to be.

See the warning in the JavaScript console: `The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page.`

**Comment by torko1** [comment] 2020-11-02 18:59
> > still having the issue, sadly.
> 
> We have not released a fix for this problem so this is expected to still be a problem.
> 
> In the meantime we've most likely identified the issue to be because the JavaScript library for the Webcast protocol is automatically initializing an `AudioContext` on page load which is not allowed anymore on modern browsers.
> 
> We need to look into restructuring that library so that this `AudioContext` is only created after a user interaction because this is how modern browsers want that to be.
> 
> See the warning in the JavaScript console: `The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page.`

Hi Vaalyn,

Is there a workaround for this issue available?

Thanks

**Comment by Vaalyn** [comment] 2020-11-03 03:00
> Is there a workaround for this issue available?

No, at the moment there is neither a fix nor a workaround available for this issue.
I'll look into it in the next days though.

**Comment by SlvrEagle23** [comment] 2020-11-03 04:58
Turns out this was caused by a very minor, silly little thing. We recently updated our Vue components to be automatically generated and handled by our asset manager, but in doing so, it made their names match the class names, i.e. `Webcaster` instead of `webcaster`. Fixing this capitalization in one spot fixes the issue.

The fix is now available in the latest rolling release version.

**Closed by SlvrEagle23** 2020-11-03 04:58 UTC
