### ISSUE TITLE
NOT_RUNNING: nginx

### ISSUE THREAD

**Issue by mdrxy** [AzuraCast/AzuraCast#7365] opened 2024-08-03 04:26 UTC
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #4bef6d6 (2024-07-27 22:53)

### What happened?

I've done a **fresh** install of the repo and following the [dev environment steps](https://www.azuracast.com/docs/developers/getting-started/) but am unable to reach the web interface. Hosting on a freshly spun up DigitalOcean Ubuntu VPS. I commented out all `INIT_*` vars in `azuracast.env` before re-running `./docker.sh install-dev`. I also ran the following before install:

```
./docker.sh install-docker
./docker.sh install-docker-compose
./docker.sh install
```

### Relevant log output

```shell
2024-08-03 04:12:22,706 INFO spawned: 'nginx' with pid 184

nginx stdout | 2024/08/03 04:12:22 [emerg] 184#184: cannot load certificate "/var/azuracast/storage/acme/ssl.crt": PEM_read_bio_X509_AUX() failed (SSL: error:0480006C:PEM routines::no start line:Expecting: TRUSTED CERTIFICATE)
nginx stdout |
2024-08-03 04:12:22,811 WARN exited: nginx (exit status 1; not expected)
nginx: ERROR (spawn error)
2024-08-03 04:12:23,832 INFO spawned: 'nginx' with pid 204
2024-08-03 04:12:23,833 INFO success: vite entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Waiting for web server (nginx) to become available...
=====================================================

cURL error 7: Failed to connect to 127.0.0.1 port 6010 after 0 ms: Couldn't connect to server (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://127.0.0.1:6010/api/status
nginx stdout | 2024/08/03 04:12:23 [emerg] 204#204: cannot load certificate "/var/azuracast/storage/acme/ssl.crt": PEM_read_bio_X509_AUX() failed (SSL: error:0480006C:PEM routines::no start line:Expecting: TRUSTED CERTIFICATE)
nginx stdout |
2024-08-03 04:12:24,136 WARN exited: nginx (exit status 1; not expected)
cURL error 7: Failed to connect to 127.0.0.1 port 6010 after 0 ms: Couldn't connect to server (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://127.0.0.1:6010/api/status
cURL error 7: Failed to connect to 127.0.0.1 port 6010 after 0 ms: Couldn't connect to server (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://127.0.0.1:6010/api/status
cURL error 7: Failed to connect to 127.0.0.1 port 6010 after 0 ms: Couldn't connect to server (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://127.0.0.1:6010/api/status
2024-08-03 04:12:26,922 INFO spawned: 'nginx' with pid 205
cURL error 7: Failed to connect to 127.0.0.1 port 6010 after 0 ms: Couldn't connect to server (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://127.0.0.1:6010/api/status
nginx stdout | 2024/08/03 04:12:26 [emerg] 205#205: cannot load certificate "/var/azuracast/storage/acme/ssl.crt": PEM_read_bio_X509_AUX() failed (SSL: error:0480006C:PEM routines::no start line:Expecting: TRUSTED CERTIFICATE)
nginx stdout |
2024-08-03 04:12:27,922 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-08-03 04:12:27,922 WARN exited: nginx (exit status 1; not expected)
2024-08-03 04:12:28,927 INFO spawned: 'nginx' with pid 207
cURL error 7: Failed to connect to 127.0.0.1 port 6010 after 0 ms: Couldn't connect to server (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://127.0.0.1:6010/api/status
cURL error 7: Failed to connect to 127.0.0.1 port 6010 after 0 ms: Couldn't connect to server (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://127.0.0.1:6010/api/status
nginx stdout | 2024/08/03 04:12:28 [emerg] 207#207: cannot load certificate "/var/azuracast/storage/acme/ssl.crt": PEM_read_bio_X509_AUX() failed (SSL: error:0480006C:PEM routines::no start line:Expecting: TRUSTED CERTIFICATE)
nginx stdout |
2024-08-03 04:12:29,931 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-08-03 04:12:29,931 WARN exited: nginx (exit status 1; not expected)

> ./docker.sh cli azuracast:radio:restart

Restarting all radio stations...
--------------------------------

 0/1 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%[2024-08-03T04:09:00.131114+00:00] AzuraCast.INFO: Writing playlist file to disk... {"station":"AzuraTest Radio","playlist":"default"} []
[2024-08-03T04:09:00.466156+00:00] AzuraCast.DEBUG: Supervisor call to "supervisor.reloadConfig" [] []
[2024-08-03T04:09:00.628080+00:00] AzuraCast.DEBUG: Removing supervisor groups. ["station_8"] []
[2024-08-03T04:09:00.629676+00:00] AzuraCast.DEBUG: Supervisor call to "supervisor.stopProcessGroup" ["station_8",true] []
[2024-08-03T04:09:02.148951+00:00] AzuraCast.DEBUG: Supervisor call to "supervisor.removeProcessGroup" ["station_8"] []
[2024-08-03T04:09:02.159068+00:00] AzuraCast.DEBUG: Adding new supervisor groups. ["station_9"] []
[2024-08-03T04:09:02.161183+00:00] AzuraCast.DEBUG: Supervisor call to "supervisor.addProcessGroup" ["station_9"] []
[2024-08-03T04:09:02.172032+00:00] AzuraCast.DEBUG: Supervisor call to "supervisor.startProcessGroup" ["station_9"] []
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%[2024-08-03T04:09:13.002378+00:00] AzuraCast.DEBUG: Supervisor call to "supervisor.signalProcess" ["nginx","HUP"] []
[2024-08-03T04:09:13.035466+00:00] AzuraCast.ERROR: Supervisor fault: NOT_RUNNING: nginx {"faultString":"NOT_RUNNING: nginx","faultCode":70} []
[2024-08-03T04:09:13.073523+00:00] AzuraCast.ERROR: Supervisor\Exception\Fault\NotRunningException: NOT_RUNNING: nginx (uncaught exception) at /var/azuracast/www/vendor/supervisorphp/supervisor/src/Exception/SupervisorException.php line 32 while running console command `azuracast:radio:restart` {"exception":"[object] (Supervisor\\Exception\\Fault\\NotRunningException(code: 70): NOT_RUNNING: nginx at /var/azuracast/www/vendor/supervisorphp/supervisor/src/Exception/SupervisorException.php:32)"} []
[2024-08-03T04:09:13.081704+00:00] AzuraCast.WARNING: Console command `azuracast:radio:restart` exited with error code 70. [] []

In SupervisorException.php line 32:

  NOT_RUNNING: nginx
```

**Comment by caturria** [comment] 2024-08-09 03:39
I'm having this problem too. I would love to do some work on the scheduler, but Nginx won't start inside the development environment.

**Comment by BusterNeece** [comment] 2024-08-11 18:22
@caturria I was able to find and fix the cause of this issue. If you're running a local dev install, I'd recommend running:

```bash
git pull
rm docker-compose.override.yml
cp docker-compose.dev.yml docker-compose.override.yml
```

You can then restart your containers with:
```bash
docker compose down
docker compose up -d
```

...and the SSL cert situation should be resolved.

**Comment by mdrxy** [comment] 2024-08-11 22:04
Thanks @BusterNeece - no longer running into the `NOT_RUNNING` issue, though another has sprung up-

<img width="1512" alt="Screenshot 1" src="https://github.com/user-attachments/assets/3fab5d62-9ee3-40e6-86cf-5bf49e95b758">

Looks like the frontend is hanging. I've cleared app cache and tried rebuilding/restarting setup.

`/docs` loads just fine, in addition to Icecast pages (by appending `:8000`).

@caturria are you running into the same problem, or is it isolated to my installation?

**Comment by BusterNeece** [comment] 2024-08-11 22:21
@mdrxy Refreshing can fix that...otherwise check vite service in logs.

**Comment by mdrxy** [comment] 2024-08-11 22:33
@BusterNeece yep refreshing was my first attempt at troubleshooting, and then clearing browser + server cache, and then reinstalling from scratch but no dice sadly. Here's where we're at with vite logs:

```
node:internal/fs/watchers:247
    const error = new UVException({
                  ^

Error: ENOSPC: System limit for number of file watchers reached, watch '/var/azuracast/www/vendor/symfony/intl/Resources/data/languages/ks.php'
    at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
    at Object.watch (node:fs:2491:36)
    at createFsWatchInstance (file:///var/azuracast/www/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:42512:17)
    at setFsWatchListener (file:///var/azuracast/www/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:42559:15)
    at NodeFsHandler._watchWithNodeFs (file:///var/azuracast/www/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:42714:14)
    at NodeFsHandler._handleFile (file:///var/azuracast/www/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:42778:23)
    at NodeFsHandler._addToNodeFs (file:///var/azuracast/www/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:43020:21)
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (file:///var/azuracast/www/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:44213:10)
    at NodeFsHandler._addToNodeFs (file:///var/azuracast/www/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:43028:18) {
  errno: -28,
  syscall: 'watch',
  code: 'ENOSPC',
  path: '/var/azuracast/www/vendor/symfony/intl/Resources/data/languages/ks.php',
  filename: '/var/azuracast/www/vendor/symfony/intl/Resources/data/languages/ks.php'
}

Node.js v20.16.0
fatal error: all goroutines are asleep - deadlock!
{
  Stations: '/var/azuracast/www/frontend/js/pages/Stations.js',
  Recover: '/var/azuracast/www/frontend/js/pages/Recover.js',
  Login: '/var/azuracast/www/frontend/js/pages/Login.js',
  Dashboard: '/var/azuracast/www/frontend/js/pages/Dashboard.js',
  Admin: '/var/azuracast/www/frontend/js/pages/Admin.js',
  Account: '/var/azuracast/www/frontend/js/pages/Account.js',
  SetupStation: '/var/azuracast/www/frontend/js/pages/Setup/Station.js',
  SetupSettings: '/var/azuracast/www/frontend/js/pages/Setup/Settings.js',
  SetupRegister: '/var/azuracast/www/frontend/js/pages/Setup/Register.js',
  PublicWebDJ: '/var/azuracast/www/frontend/js/pages/Public/WebDJ.js',
  PublicSchedule: '/var/azuracast/www/frontend/js/pages/Public/Schedule.js',
  PublicRequests: '/var/azuracast/www/frontend/js/pages/Public/Requests.js',
  PublicPodcasts: '/var/azuracast/www/frontend/js/pages/Public/Podcasts.js',
  PublicPlayer: '/var/azuracast/www/frontend/js/pages/Public/Player.js',
  PublicOnDemand: '/var/azuracast/www/frontend/js/pages/Public/OnDemand.js',
  PublicHistory: '/var/azuracast/www/frontend/js/pages/Public/History.js',
  PublicFullPlayer: '/var/azuracast/www/frontend/js/pages/Public/FullPlayer.js',
  Layout: '/var/azuracast/www/frontend/js/layout.js'
}

  VITE v5.3.5  ready in 2593 ms

  ➜  Local:   http://localhost:5173/static/vite_dist
  ➜  Network: http://172.18.0.3:5173/static/vite_dist
node:internal/fs/watchers:247
    const error = new UVException({
                  ^

Error: ENOSPC: System limit for number of file watchers reached, watch '/var/azuracast/www/vendor/symfony/intl/Resources/data/languages/ks.php'
    at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
    at Object.watch (node:fs:2491:36)
    at createFsWatchInstance (file:///var/azuracast/www/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:42512:17)
    at setFsWatchListener (file:///var/azuracast/www/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:42559:15)
    at NodeFsHandler._watchWithNodeFs (file:///var/azuracast/www/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:42714:14)
    at NodeFsHandler._handleFile (file:///var/azuracast/www/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:42778:23)
    at NodeFsHandler._addToNodeFs (file:///var/azuracast/www/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:43020:21)
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (file:///var/azuracast/www/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:44213:10)
    at NodeFsHandler._addToNodeFs (file:///var/azuracast/www/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:43028:18) {
  errno: -28,
  syscall: 'watch',
  code: 'ENOSPC',
  path: '/var/azuracast/www/vendor/symfony/intl/Resources/data/languages/ks.php',
  filename: '/var/azuracast/www/vendor/symfony/intl/Resources/data/languages/ks.php'
}

Node.js v20.16.0
fatal error: all goroutines are asleep - deadlock!
{
  Stations: '/var/azuracast/www/frontend/js/pages/Stations.js',
  Recover: '/var/azuracast/www/frontend/js/pages/Recover.js',
  Login: '/var/azuracast/www/frontend/js/pages/Login.js',
  Dashboard: '/var/azuracast/www/frontend/js/pages/Dashboard.js',
  Admin: '/var/azuracast/www/frontend/js/pages/Admin.js',
  Account: '/var/azuracast/www/frontend/js/pages/Account.js',
  SetupStation: '/var/azuracast/www/frontend/js/pages/Setup/Station.js',
  SetupSettings: '/var/azuracast/www/frontend/js/pages/Setup/Settings.js',
  SetupRegister: '/var/azuracast/www/frontend/js/pages/Setup/Register.js',
  PublicWebDJ: '/var/azuracast/www/frontend/js/pages/Public/WebDJ.js',
  PublicSchedule: '/var/azuracast/www/frontend/js/pages/Public/Schedule.js',
  PublicRequests: '/var/azuracast/www/frontend/js/pages/Public/Requests.js',
  PublicPodcasts: '/var/azuracast/www/frontend/js/pages/Public/Podcasts.js',
  PublicPlayer: '/var/azuracast/www/frontend/js/pages/Public/Player.js',
  PublicOnDemand: '/var/azuracast/www/frontend/js/pages/Public/OnDemand.js',
  PublicHistory: '/var/azuracast/www/frontend/js/pages/Public/History.js',
  PublicFullPlayer: '/var/azuracast/www/frontend/js/pages/Public/FullPlayer.js',
  Layout: '/var/azuracast/www/frontend/js/layout.js'
}

  VITE v5.3.5  ready in 2075 ms

  ➜  Local:   http://localhost:5173/static/vite_dist
  ➜  Network: http://172.18.0.3:5173/static/vite_dist
```

This series of messages loops repeatedly.

**Comment by BusterNeece** [comment] 2024-08-12 00:18
@mdrxy Ah, definitely a valid issue and probably was causing a lot of performance issues for me on my dev installs too. Should be fixed as of latest commit, you can pull and rebuild with:

```bash
git pull
make update
```

**Closed** 2024-08-12 04:57 UTC
Labels: needs investigation
