### ISSUE TITLE
"Check Media Folders" function does not work.

### ISSUE THREAD

**Issue by djmuratb** [AzuraCast/AzuraCast#2209] opened 2019-12-10 02:10 UTC
**Docker** / Ubuntu 18.04.3 LTS
AzuraCast • v0.9.8, #**dbb688d** (2019-12-09 4:38) • Docker • PHP 7.4

"_Check Media Folders_" function does not work.
![image](https://iili.io/HAGyOv.png)

When I press the _run_ button, error appears as in the image.
.../admin/sync/medium
![image](https://iili.io/HAM9bR.png)

Windows 10 / Chrome

*Media files are in one folder only.
*My stations use the same folder and music.

**Comment by SlvrEagle23** [comment] 2019-12-13 06:59
Duplicate of #2207.

**Closed by SlvrEagle23** 2019-12-13 06:59 UTC
