### ISSUE TITLE
problem with podcasts

### ISSUE THREAD

**Issue by artem59k** [AzuraCast/AzuraCast#6953] opened 2024-02-18 19:11 UTC
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #3a202ca (2024-02-16 18:03)

### What happened?

Hello. On the public page of the podcast and on the RSS feed, for some unknown reason, episodes are displayed at the top of old old issues, and new issues begin at the bottom. You can also not download mp3. When I try to download via rss, the file is downloaded without an extension.

### Relevant log output

```shell
There are no logs on this situation
```

**Comment by edpenguin** [comment] 2024-02-22 12:48
There are a lot of changes and additions to the Podcast section which look v useful. Some issues we have come across so far:

- We cannot locate the link to download a specific show episode
- When viewing a podcast with many episodes, if you set the display to show say 10 episodes, it displays them in a jumbled fashion ie not in date order
- If you set the display to ALL (or a number greater than the actual number of episodes so that they all fit on 1 page) it shows them in correct order with oldest first, newest last
- Clicking the Episode link does not change the order, they remain showing oldest first, latest last
- We can add text to the details field but if we then edit the details we can save the changes on the back end but the change does not show on the Public Page
- URL's in the Details field do not display as a hyper link
- The download function on our plugin no longer works as we get: Error Method not allowed. Must be one of: OPTIONS The request method is not supported for the requested resource.

Being unable to locate the download link on the new version is currently a problem. Will there be (or is there) a download link ?

PS One function for the Podcast section that would be a great addition is a User role enabling that user to Upload/Edit etc one or more specific podcasts enabling show hosts to add their own notes etc.

**Comment by Vaalyn** [comment] 2024-02-23 09:23
> We cannot locate the link to download a specific show episode

The link is the same as before and can still be found in the podcasts RSS feed in the `item` -> `enclosure` tag.
Here an example from the demo installation [RSS feed](https://demo.azuracast.com/public/1/podcast/1eed229f-9a3b-6cdc-b3ae-3fa80f285db7/feed):
```
<enclosure url="https://demo.azuracast.com/api/station/1/public/podcast/1eed229f-9a3b-6cdc-b3ae-3fa80f285db7/episode/1eed229f-ad6a-67b8-bf93-07a7712a48e1/download" length="205.27" type="audio/mpeg"/>
```

This is just the URL of the podcast episode page from the browser just with a `/download` at the end.

> When viewing a podcast with many episodes, if you set the display to show say 10 episodes, it displays them in a jumbled fashion ie not in date order
> If you set the display to ALL (or a number greater than the actual number of episodes so that they all fit on 1 page) it shows them in correct order with oldest first, newest last
> Clicking the Episode link does not change the order, they remain showing oldest first, latest last

This definitely looks like a bug.

> We can add text to the details field when we make the initial post. If we then edit the details the changes are saved on the back end but do not show on the Public Page

I've just tested this, created a new podcast with a description, added an episode with a description, looked at it on the public pages, then edited both and looked at the pages again. Changes are correctly displayed and also contained in the RSS feed.
<img width="461" alt="image" src="https://github.com/AzuraCast/AzuraCast/assets/13745863/49c21fd9-45ad-45fb-802d-4a308d73f74f">
<img width="343" alt="image" src="https://github.com/AzuraCast/AzuraCast/assets/13745863/13d6cd39-d055-42fa-9591-61b7c700149b">

Maybe a browser cache or something that is causing it to not update for you?

> URL's in the Details field do not display as a hyper link

That's correct, there is currently no conversion of links or other special stuff being done with the description when rendering it. You'd need to make a feature request for this at https://azuracast.featureupvote.com/

> The download function on our plugin no longer works as we get:
> Error Method not allowed. Must be one of: OPTIONS The request method is not supported for the requested resource.

Are you doing a `GET` request to the URL I mentioned above?

**Comment by edpenguin** [comment] 2024-02-25 22:39
When I click the RSS Feed link in your post above I get

![image](https://github.com/AzuraCast/AzuraCast/assets/160861543/d9c28c26-fd97-4b8a-92f2-a508072d8422)

When I enter the enclosure url you supplied to download the file in a browser ie

https://demo.azuracast.com/api/station/1/public/podcast/1eed229f-9a3b-6cdc-b3ae-3fa80f285db7/episode/1eed229f-ad6a-67b8-bf93-07a7712a48e1/download

I get the same error image/message.

With all previous versions we would right click and copy the download link and that download link was then pasted in to Seriously Simple Podcasting and worked fine. After the update however none of these archived shows can be streamed or downloaded ... leading me to think that something has changed in the link structure possibly.

**Comment by Vaalyn** [comment] 2024-02-25 22:56
The links in my post are from the demo installation. This installation automatically resets after some time which will cause the links to change since the db entries will get new IDs rendering those in my post invalid.

**Comment by edpenguin** [comment] 2024-02-25 23:03
Ok. The key point is that all the old links we had for the past shows no longer work since we upgraded. Are we looking at having to re-do all those links ?

**Comment by Vaalyn** [comment] 2024-02-26 09:19
@edpenguin I have checked an older installation that is running on `#a28072d (2023-06-01 7:17)`, created a podcast & an episode there. The download URL has the exact same format as the one from my post above:

`https://xyz.com/api/station/4/podcast/1eed4852-50c4-6c7e-971d-27982c5d67bf/episode/1eed4852-fac3-6de2-8de8-ebdf12a4137f/download`

The format hasn't changed one bit and the long parts between `/podcast/` and `/episode/` as well as `/episode/` and `/download` are the UUIDs of the podcast & episode from the database field `id` of the `podcast` & `podcast_episode` tables. Those IDs never change, only if you completely delete and re-create the DB entries would those change. An update of the software will not change those.

If you have problems with old links then:
- Post one of those download links that is not working anymore
- Post a link to the podcasts public page

Otherwise I can't do anything else than to say "no nothing has changed as far as I can tell".

**Comment by edpenguin** [comment] 2024-02-26 09:22
@Vaalyn Thank you for the time you have taken to look into and test this and the clear explanation in your last post. I will go do some testing and get back here soon with an update.

**Comment by edpenguin** [comment] 2024-02-26 13:20
@Vaalyn So all our links are exactly as they were and conform to the formats you texted here: eg

https://**********.org/api/station/1/podcast/1ee55781-27c1-6ada-9612-1f52acf69f72/episode/1eece8aa-e992-6ff8-852a-d5c7dc48ccba/download

That's what is entered into the SSP box in wordpress and has always worked up until the upgrade

![image](https://github.com/AzuraCast/AzuraCast/assets/160861543/1c73d892-f50e-4fbe-9b12-98f69f825c32)

So the file format looks correct. It seems that it is no longer connecting in the new version.

PS The editing of the details field does work. Thx for the pointer on that.

**Comment by edpenguin** [comment] 2024-02-26 13:22
@Vaalyn So all our links are exactly as they were and conform to the formats you texted here: eg

https://**********.org/api/station/1/podcast/1ee55781-27c1-6ada-9612-1f52acf69f72/episode/1eece8aa-e992-6ff8-852a-d5c7dc48ccba/download

That's what is entered into the SSP box in wordpress and has always worked up until the upgrade

![image](https://github.com/AzuraCast/AzuraCast/assets/160861543/80c9f442-ddad-421c-80bc-0a8f37154958)

So the file format looks correct. It seems that it is no longer connecting in the new version.

PS The editing of the details field does work. Thx for the pointer on that.

**Comment by ChandigarIT** [comment] 2024-03-09 11:46
• v0.19.5 Stable • Docker • PHP 8.3

I am also having randomly ordered shows; it appears to follow no order at all, not date of upload, date of publishing, file name, nor content details. Clicking the "episode" button sometimes changes the order, but to something else completely random.

Also no download facility that was previously supported in Firefox.

![image](https://github.com/AzuraCast/AzuraCast/assets/108827431/3bfcef85-89a1-4f02-83c1-3dbfbe54e554)

**Comment by batsonjay** [comment] 2024-03-15 11:51
I'm not seeing randomly ordered shows at least as far as I've seen so far). BUT I note the following behavior in the Episodes list UX; I'm wondering if it's related?

Visiting the "Episodes" page (found by clicking "Episodes" button in the right-hand trio of buttons on /station/x/podcasts) causes the Episodes to be listed in what I *think* is alpha sort of filename order, or perhaps numeric sort of the Date Added of the file.

It *should* be (by default) increasing ordinal sort on Published At (which, actually, should be "Published On"). While the *display* of Episodes can be re-sortable by any column head, it should be very difficult (impossible?) for the RSS feed to be sorted in any other way other than ordinal increasing Published At(/On).

Perhaps these are related?

**Comment by ChandigarIT** [comment] 2024-03-28 16:43
The problem is still there...

![image](https://github.com/AzuraCast/AzuraCast/assets/108827431/ccb6be9c-fd1e-41ea-bbb0-bdea60f66efb)


Not in file name order, nor date of upload order. Clicking "Episodes" makes no difference.

**Comment by BusterNeece** [comment] 2024-03-28 18:52
@ChandigarIT Check the "Published At" dates on those podcasts. We are sorting by those now. If a publish date wasn't provided originally for an episode, it's set to the podcast's upload date, so they still sort chronologically by creation date, but if you've manually modified the publish dates, that will affect sorting.

**Comment by BusterNeece** [comment] 2024-04-17 05:56
This issue should be fixed as of the latest Rolling Releases. If you are still encountering episodes sorted out of order, just update the published date for the episodes so they line up correctly.

**Closed by BusterNeece** 2024-04-17 05:56 UTC
Labels: bug, needs investigation
