### ISSUE TITLE
Station Playback Timeline

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#397] opened 2018-01-31 11:18 UTC
the Station Playback Timeline list loads for a very long time until it loads all the songs, and only then collapses. If the songs are 500-1000 then the whole server hangs, you can make sure that all songs are not loaded, but only the amount specified in the filter?

**Comment by SlvrEagle23** [comment] 2018-02-01 11:59
@susl16c This was caused by missing security settings on the page's JavaScript. It should be fixed in the latest update. Please update and let me know.

**Comment by susl16c** [comment] 2018-02-01 12:29
Just tried to update and that's what

TASK [azuracast-update : Regenerate Doctrine Proxies] **************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/util/cli.php orm:generate-proxies", "delta": "0:00:00.507208", "end": "2018-02-01 12:28:59.284402", "msg": "non-zero return code", "rc": 1, "start": "2018-02-01 12:28:58.777194", "stderr": "\nIn MappingException.php line 61:\n                                                                               \n  File mapping drivers must have a valid directory path, however the given pa  \n  th [/var/azuracast/www/app/models] seems to be incorrect!                    \n                                                                               \n\norm:generate-proxies [--filter FILTER] [--] [<dest-path>]", "stderr_lines": ["", "In MappingException.php line 61:", "                                                                               ", "  File mapping drivers must have a valid directory path, however the given pa  ", "  th [/var/azuracast/www/app/models] seems to be incorrect!                    ", "                                                                               ", "", "orm:generate-proxies [--filter FILTER] [--] [<dest-path>]"], "stdout": "", "stdout_lines": []}

PLAY RECAP *********************************************************************
localhost                  : ok=7    changed=5    unreachable=0    failed=1

**Comment by FrBillyD** [comment] 2018-02-01 12:35
Hello @susl16c it's the same for me but the interface work fine.

**Comment by SlvrEagle23** [comment] 2018-02-01 12:55
@susl16c @FrBillyD Seems this was a minor issue caused by relocating the database models and not updating one spot.

Latest commit should fix it. Try it out and let me know.

**Comment by FrBillyD** [comment] 2018-02-01 13:02
Yup ! No error ! :smile: 

![image](https://user-images.githubusercontent.com/4552702/35679765-83d30c3a-0758-11e8-8dc8-b9b20564a5b0.png)

Thank you ! Always awesome !

**Comment by susl16c** [comment] 2018-02-01 14:27
Yes, this bug is fixed, thank you very much.

**Closed** 2018-02-01 14:28 UTC
Labels: bug
