### ISSUE TITLE
Abnormally high CPU load on the latest stable branch 

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#5575] opened 2022-07-06 09:15 UTC
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

 Rolling Release #729395f (2022-07-06 4:10)

### What happened?

Since updating to the latest rolling release, there has been a constant 100% CPU load.  All eight CPUs on the server are running at 100%. Before the update, CPU load was 30-40% and server load average (TOP) was 2-3, but now it's about 20!
![image](https://user-images.githubusercontent.com/2701228/177508744-27d5d119-3583-4844-9801-9091762a8464.png)

**Comment by ItsMitchh** [comment] 2022-07-06 10:16
We'll need more information about your system

Stations?
Playlist types on the stations?

**Comment by eranwo** [comment] 2022-07-06 10:37
@ItsMitchh In total, 40 stations run one random playlist each.
stereo tool - disabled
It worked fine until the latest update

**Comment by ItsMitchh** [comment] 2022-07-06 11:03
Can you run htop or a similar program to see which is using the most resources? It'll help us diagnose this problem.

**Comment by eranwo** [comment] 2022-07-06 11:34
![image](https://user-images.githubusercontent.com/2701228/177541115-1197f229-be74-4820-9054-8df981981e6f.png)

**Comment by eranwo** [comment] 2022-07-06 12:47
There are some stations that remain offline and play white noise.
Here is a Liquidsoap log from an "Offline Station".


```
Unknown position:

Error -1: Exception raised: Too many open files in inotify_init()
Raised by primitive operation at File_watcher_inotify.watch.(fun) in file "tools/file_watcher_inotify.ml", line 49, characters 19-38
Called from Tutils.mutexify in file "tools/tutils.ml", line 95, characters 14-17
Re-raised at Tutils.mutexify in file "tools/tutils.ml", line 101, characters 4-38
Called from Builtins_files.(fun) in file "builtins/builtins_files.ml", line 229, characters 20-43
Called from Evaluation.apply.f in file "lang/evaluation.ml", line 315, characters 8-12
Called from Evaluation.eval.ans.(fun) in file "lang/evaluation.ml", line 292, characters 46-56
Called from Stdlib__List.map in file "list.ml", line 92, characters 20-23
Called from Evaluation.eval.ans in file "lang/evaluation.ml", line 292, characters 18-60
Called from Evaluation.eval.ans.(fun) in file "lang/evaluation.ml", line 292, characters 46-56
Called from Stdlib__List.map in file "list.ml", line 92, characters 20-23
Called from Evaluation.eval.ans in file "lang/evaluation.ml", line 292, characters 18-60
Called from Evaluation.apply.f in file "lang/evaluation.ml", line 315, characters 8-12
Called from Tutils.finalize in file "tools/tutils.ml", line 105, characters 12-16
Re-raised at Tutils.finalize in file "tools/tutils.ml", line 111, characters 4-38
Called from Evaluation.apply.f in file "lang/evaluation.ml", line 315, characters 8-12
Called from Evaluation.eval in file "lang/evaluation.ml", line 239, characters 16-26
Called from Evaluation.apply.f in file "lang/evaluation.ml", line 315, characters 8-12
Called from Tutils.finalize in file "tools/tutils.ml", line 105, characters 12-16
Re-raised at Tutils.finalize in file "tools/tutils.ml", line 111, characters 4-38
Called from Evaluation.apply.f in file "lang/evaluation.ml", line 315, characters 8-12
Called from Evaluation.apply.f in file "lang/evaluation.ml", line 315, characters 8-12
Called from Tutils.finalize in file "tools/tutils.ml", line 105, characters 12-16
Re-raised at Tutils.finalize in file "tools/tutils.ml", line 111, characters 4-38
Called from Evaluation.apply.f in file "lang/evaluation.ml", line 315, characters 8-12
Called from Evaluation.eval in file "lang/evaluation.ml", line 287, characters 15-27
Called from Evaluation.apply.f in file "lang/evaluation.ml", line 315, characters 8-12
Called from Evaluation.eval_toplevel in file "lang/evaluation.ml", line 462, characters 38-46
Called from Runtime.type_and_run.(fun) in file "lang/runtime.ml", line 38, characters 13-43
Called from Tutils.finalize in file "tools/tutils.ml", line 105, characters 12-16
Re-raised at Tutils.finalize in file "tools/tutils.ml", line 111, characters 4-38
Called from Runtime.report in file "lang/runtime.ml", line 191, characters 12-23
```

**Comment by ItsMitchh** [comment] 2022-07-06 13:07
Can you go to C16 and C40 and provide us some Liquidsoap logs, the full Playlist configurations and media count? 

In these stations that have crashes, how many files are you using?

**Comment by eranwo** [comment] 2022-07-06 14:58
For each station, there is one playlist (default) with 200-300 songs
In c16, there are 320 songs in one playlist (the default playlist)
In c40, there are 208 songs in one playlist (the default playlist).

I am not sure where I can find the playlist configuration? 

c16 Liquidsoap log:
```
Unknown position:

Error -1: Exception raised: Too many open files in inotify_init()
Raised by primitive operation at File_watcher_inotify.watch.(fun) in file "tools/file_watcher_inotify.ml", line 49, characters 19-38
Called from Tutils.mutexify in file "tools/tutils.ml", line 95, characters 14-17
Re-raised at Tutils.mutexify in file "tools/tutils.ml", line 101, characters 4-38
Called from Builtins_files.(fun) in file "builtins/builtins_files.ml", line 229, characters 20-43
Called from Evaluation.apply.f in file "lang/evaluation.ml", line 315, characters 8-12
Called from Evaluation.eval.ans.(fun) in file "lang/evaluation.ml", line 292, characters 46-56
Called from Stdlib__List.map in file "list.ml", line 92, characters 20-23
Called from Evaluation.eval.ans in file "lang/evaluation.ml", line 292, characters 18-60
Called from Evaluation.eval.ans.(fun) in file "lang/evaluation.ml", line 292, characters 46-56
Called from Stdlib__List.map in file "list.ml", line 92, characters 20-23
Called from Evaluation.eval.ans in file "lang/evaluation.ml", line 292, characters 18-60
Called from Evaluation.apply.f in file "lang/evaluation.ml", line 315, characters 8-12
Called from Tutils.finalize in file "tools/tutils.ml", line 105, characters 12-16
Re-raised at Tutils.finalize in file "tools/tutils.ml", line 111, characters 4-38
Called from Evaluation.apply.f in file "lang/evaluation.ml", line 315, characters 8-12
Called from Evaluation.eval in file "lang/evaluation.ml", line 239, characters 16-26
Called from Evaluation.apply.f in file "lang/evaluation.ml", line 315, characters 8-12
Called from Tutils.finalize in file "tools/tutils.ml", line 105, characters 12-16
Re-raised at Tutils.finalize in file "tools/tutils.ml", line 111, characters 4-38
Called from Evaluation.apply.f in file "lang/evaluation.ml", line 315, characters 8-12
Called from Evaluation.apply.f in file "lang/evaluation.ml", line 315, characters 8-12
Called from Tutils.finalize in file "tools/tutils.ml", line 105, characters 12-16
Re-raised at Tutils.finalize in file "tools/tutils.ml", line 111, characters 4-38
Called from Evaluation.apply.f in file "lang/evaluation.ml", line 315, characters 8-12
Called from Evaluation.eval in file "lang/evaluation.ml", line 287, characters 15-27
Called from Evaluation.apply.f in file "lang/evaluation.ml", line 315, characters 8-12
Called from Evaluation.eval_toplevel in file "lang/evaluation.ml", line 462, characters 38-46
Called from Runtime.type_and_run.(fun) in file "lang/runtime.ml", line 38, characters 13-43
Called from Tutils.finalize in file "tools/tutils.ml", line 105, characters 12-16
Re-raised at Tutils.finalize in file "tools/tutils.ml", line 111, characters 4-38
Called from Runtime.report in file "lang/runtime.ml", line 191, characters 12-23
```
c40 Liquidsoap log:

```
Unknown position:

Error -1: Exception raised: Too many open files in inotify_init()
Raised by primitive operation at File_watcher_inotify.watch.(fun) in file "tools/file_watcher_inotify.ml", line 49, characters 19-38
Called from Tutils.mutexify in file "tools/tutils.ml", line 95, characters 14-17
Re-raised at Tutils.mutexify in file "tools/tutils.ml", line 101, characters 4-38
Called from Builtins_files.(fun) in file "builtins/builtins_files.ml", line 229, characters 20-43
Called from Evaluation.apply.f in file "lang/evaluation.ml", line 315, characters 8-12
Called from Evaluation.eval.ans.(fun) in file "lang/evaluation.ml", line 292, characters 46-56
Called from Stdlib__List.map in file "list.ml", line 92, characters 20-23
Called from Evaluation.eval.ans in file "lang/evaluation.ml", line 292, characters 18-60
Called from Evaluation.eval.ans.(fun) in file "lang/evaluation.ml", line 292, characters 46-56
Called from Stdlib__List.map in file "list.ml", line 92, characters 20-23
Called from Evaluation.eval.ans in file "lang/evaluation.ml", line 292, characters 18-60
Called from Evaluation.apply.f in file "lang/evaluation.ml", line 315, characters 8-12
Called from Tutils.finalize in file "tools/tutils.ml", line 105, characters 12-16
Re-raised at Tutils.finalize in file "tools/tutils.ml", line 111, characters 4-38
Called from Evaluation.apply.f in file "lang/evaluation.ml", line 315, characters 8-12
Called from Evaluation.eval in file "lang/evaluation.ml", line 239, characters 16-26
Called from Evaluation.apply.f in file "lang/evaluation.ml", line 315, characters 8-12
Called from Tutils.finalize in file "tools/tutils.ml", line 105, characters 12-16
Re-raised at Tutils.finalize in file "tools/tutils.ml", line 111, characters 4-38
Called from Evaluation.apply.f in file "lang/evaluation.ml", line 315, characters 8-12
Called from Evaluation.apply.f in file "lang/evaluation.ml", line 315, characters 8-12
Called from Tutils.finalize in file "tools/tutils.ml", line 105, characters 12-16
Re-raised at Tutils.finalize in file "tools/tutils.ml", line 111, characters 4-38
Called from Evaluation.apply.f in file "lang/evaluation.ml", line 315, characters 8-12
Called from Evaluation.eval in file "lang/evaluation.ml", line 287, characters 15-27
Called from Evaluation.apply.f in file "lang/evaluation.ml", line 315, characters 8-12
Called from Evaluation.eval_toplevel in file "lang/evaluation.ml", line 462, characters 38-46
Called from Runtime.type_and_run.(fun) in file "lang/runtime.ml", line 38, characters 13-43
Called from Tutils.finalize in file "tools/tutils.ml", line 105, characters 12-16
Re-raised at Tutils.finalize in file "tools/tutils.ml", line 111, characters 4-38
Called from Runtime.report in file "lang/runtime.ml", line 191, characters 12-23
```

**Comment by ItsMitchh** [comment] 2022-07-06 15:34
@eranwo 
![image](https://user-images.githubusercontent.com/29955942/177588470-cca913e5-f92b-448d-8502-6eba1a929229.png)
You can find the logs here, can you provide a much larger Liquidsoap Log too? I'll reach out to the Liquidsoap team. If you can post the logs in a gist, that'd be awesome.

**Comment by ItsMitchh** [comment] 2022-07-06 16:15
Thanks, lastly, shoutcast or IceCast?

**Comment by eranwo** [comment] 2022-07-06 17:07
IceCast

**Comment by eranwo** [comment] 2022-07-07 12:04
@ItsMitchh The same issue persists even when I duplicate all stations to another server with 12 CPUs
 `Rolling Release #64e2a48 (2022-07-07 2:30)`
![image](https://user-images.githubusercontent.com/2701228/177768544-6c053a52-6e85-4e3a-88b6-4d100bd21bc9.png)

**Comment by ItsMitchh** [comment] 2022-07-07 15:03
Thank you for the detailed reports. We've forwarded this onto the team at Liquidsoap with the aim to determine the root cause of this issue, your patience is greatly apprieciated.

**Comment by Blat4** [comment] 2022-07-10 06:30
I had this issue after updating.  I just cold rebooted the server and it fixed it for me. I've never seen all cores on my Intel Xeon Server @ 100% before.

**Comment by eranwo** [comment] 2022-07-10 06:51
@Blat4 What version of Azuracast you are using?

**Comment by Blat4** [comment] 2022-07-10 07:02
> @Blat4 What version of Azuracast you are using?

Rolling Release 64e2a48

**Comment by Blat4** [comment] 2022-07-10 07:06
@eranwo What CPU and Chipset are you using on both machines?

**Comment by eranwo** [comment] 2022-07-10 08:24
Having worked around this for a bit, I rolled back to version 0.17.1 and now it works well without CPU load (Load Average 3).
It appears that the problem starts after upgrading from version 0.17.1 to version 0.17.2 (and up)
I tested it on two servers with the same content (stations and songs).

**Comment by Sakretsos** [comment] 2022-07-16 14:13
hello @eranwo how it is possible to rollback, you use docker.sh update 0.17.1?

**Comment by rolradio** [comment] 2022-07-23 07:31
Just a tip..
I think the problem is with the log files.
Logs from Liquidsoap / shoutcast / icecast
If I stop /kill this via webmin then the CPU consumption drops enormously.

**Comment by eranwo** [comment] 2022-07-23 09:12
@rolradio That might be true, but there were logs in the previous versions too...

**Comment by ItsMitchh** [comment] 2022-07-23 15:44
Hi guys,

We believe we have located the exact cause of the problem which isn't present in the last stable version. As some users have mentioned it's indeed related to how we pull the logs across Azuracast. 

Due to Silver going through life issues currently we're unable to give an ETA on a fix. Sorry for any inconvenience.

**Comment by SlvrEagle23** [comment] 2022-07-23 16:15
Hello all; thank you for your patience as we work through this issue. As many of you know, I'm going through a housing emergency, but I wanted to make sure this was fixed, as it seems to be affecting a large swath of users.

I've pushed a fix that is currently deploying to the Rolling Release branch and will be available in the next few minutes. I'd strongly encourage anyone who's running into issues to update to the latest rolling version, and help verify that this resolves the issue; if so, we will try to tag a new stable version as soon as possible.

**Comment by eranwo** [comment] 2022-07-24 10:19
@SlvrEagle23 Thak you for the update! The CPU usage is much better after upgrading to Rolling Release #5ab3cf9 (2022-07-23 16:10), but not as good as version v0.17.1 Stable. 
Also, it took a very long time for the "Station Overview" to appear. 
And the **Nowplaying** does not updating

**Before update (version v0.17.1)**
![image](https://user-images.githubusercontent.com/2701228/180642496-6700521d-1526-4e0a-aa8d-e7b4fdd2c9bf.png)

**After update**
![image](https://user-images.githubusercontent.com/2701228/180642572-09e95798-60bd-45aa-acd6-a393a34d6704.png)

**Comment by ItsMitchh** [comment] 2022-07-24 12:16
Hi there 

Can you give us a htop reading? Or are you able to tell us what's using the most resources

**Comment by eranwo** [comment] 2022-07-24 13:17
![image](https://user-images.githubusercontent.com/2701228/180648741-e99c9285-7a1c-4015-8266-ba19b80484bb.png)

**Comment by eranwo** [comment] 2022-07-28 11:05
@ItsMitchh Hi, As you can see, after a while the CPU reaches almost 100%. If you need anything else, please do not hesitate to contact me

**Comment by ItsMitchh** [comment] 2022-07-29 01:48
I'm not entirely sure the best options then, the CPU usages in that list seem about accurate for Liquidsoap, I'd say don't use 40 stations on a singular server, as that's just commercial level.

**Closed** 2022-08-07 01:55 UTC
Labels: possible bug, unexpected behaviour, rolling-release

**Comment by eranwo** [comment] 2022-08-12 09:32
@ItsMitchh  Hi, In v0.17.3 Stable , CPU load appears to be back to normal
