### ISSUE TITLE
Multiple issues on HTTPS

### ISSUE THREAD

**Issue by replayfactory** [AzuraCast/AzuraCast#354] opened 2017-12-22 12:04 UTC
Hi there, 
When switching "Always Use HTTPS" to Yes on Admin settings page, I got multiple issues : 

**API**
/api/nowplaying and /api/nowplaying/{station_id}
always returns an empty json value for **now_playing > song > art**
but returns a correct value for **playing_next > song > art**
Switching back to http removes the issue

**Backend**
On Station Playback Timeline page, song source is always "Live Broadcast" on https
When switching back to http, the playlist source is correcly displayed.

I was able to reproduce thoses issues after a complete reinstall of azuracast.

As a workaround, I added an nginx block that redirect http to https but leave "Always Use HTTPS" to No.
So I can access Azuracast through https

---------------------
_Version v0.8.0-2017.12 Beta (Traditional).
PHP 7.2.0-2+ubuntu16.04.1+deb.sury.org+2, SlimPHP 3_

**Comment by SlvrEagle23** [comment] 2017-12-22 14:40
@replayfactory All valid issues, and all caused by the same problem: internal localhost calls from the station management services to the web app itself were also falling under the "force HTTPS" rules, which triggered HTTP 302 redirects for them that they can't handle. Since these requests are always from localhost, they can be exempted from normal HTTPS rules for browsers, and I've added such an exception into the code.

That should fix things. Let me know if it works on your end.

**Comment by amavarick** [comment] 2017-12-22 23:18
I setup a brand new Ubuntu with Docker AzuraCast.  I did not force https nor nginx proxy but did install and setup Let's Encrypt certificate using your instructions.  I'll test other ways but this is what I have so far...

```
Blocked loading mixed active content “http://.../static/fonts/roboto/Roboto-Regular-webfont.woff”
Blocked loading mixed active content “http://.../static/fonts/roboto/Roboto-Bold-webfont.woff”
Blocked loading mixed active content “http://.../static/fonts/roboto/Roboto-Medium-webfont.woff”
Loading mixed (insecure) display content “http://.................../api/station/1/art/ce4ee4e2e7d6a3e7aa4a3ad5” on a secure page
```
Please consider using a protocol relative URL for these or logic to forcing http or https based on URL?

**Comment by SlvrEagle23** [comment] 2017-12-23 00:16
@amavarick There's a good reason the "Always Use HTTPS" setting exists in the system: sometimes URLs are generated by cron tasks that don't know whether the resulting end URL will be accessed via an insecure or secure connection, and have to make a "best guess" effort; adding the setting makes that guess far more educated.

I'm aware of the existence of protocol-relative "//site-name" URLs, but I'm averse to using them, as every time I use them in an API, I get a number of people who say that their particular consumer of the API has no way of handling that type of URL, and doesn't understand the leading double-slashes to be indicating "whatever the current schema is".

In this case, there's still fortunately a possible answer: I've added the Content Security Policy header "upgrade insecure" which, if you're on a HTTPS connection already, will force all of the content on the page to likewise upgrade to HTTPS or simply not be displayed, rather than showing "mixed content" warnings. I've tested this locally, and it appears to resolve the issue fully even if you haven't explicitly set the "Always Use HTTPS" flag.

**Comment by amavarick** [comment] 2017-12-23 00:31
I updated my docker version and the CSP seems to upgrade http to https but the public radio does not play...
https://.../public/music
```
Invalid URI. Load of media resource  failed.
music
Error in parsing value for ‘width’.  Declaration dropped.
music
Content Security Policy: Upgrading insecure request ‘http://...:8000/radio.mp3?1513988817’ to use ‘https’ 
```
Changing my page from https to http then works with no errors.
http://.../public/music

**Comment by SlvrEagle23** [comment] 2017-12-23 00:45
@amavarick Neither Icecast nor Shoutcast serve directly via HTTPS. You also have to turn on radio station proxying, which will forward all requests through nginx (and thus, the proper security settings). I'm working on a more elegant way of explaining or resolving this.

**Comment by amavarick** [comment] 2017-12-23 04:08
That's right, stupid mistake on my part...

**Comment by replayfactory** [comment] 2017-12-23 10:52
@SlvrEagle23 Sounds good ! Both issues are solved. Best wishes for the festive season ;-)

**Comment by SlvrEagle23** [comment] 2017-12-23 16:10
@amavarick The latest update will automatically turn on proxying if you're visiting the public or admin pages from a secure connection, thus routing the radio traffic itself through the same secure connection.

That should take care of everything from this ticket!

**Closed by SlvrEagle23** 2017-12-23 16:10 UTC
Labels: bug
