### ISSUE TITLE
Remote url not working

### ISSUE THREAD

**Issue by PManuel1986** [AzuraCast/AzuraCast#5404] opened 2022-05-23 00:42 UTC
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.15.2 Stable

### What happened?

No matter what URL I try to transfer from a remote URL, it doesn't work

**Comment by Marcioghiraldelli** [comment] 2022-05-23 02:03
I reported the same error.

**Comment by nunotfc** [comment] 2022-05-25 05:33
#5395

**Comment by SC2Mitch** [comment] 2022-05-26 23:03
Duplicate of #5395

**Closed by SC2Mitch** 2022-05-26 23:03 UTC
Labels: needs investigation
