### ISSUE TITLE
AlbumArt Missing

### ISSUE THREAD

**Issue by jdrodriguez** [AzuraCast/AzuraCast#3654] opened 2021-01-11 17:21 UTC
I just updated to the latest version and suddenly the album arts are not showing up. Any recommendations?

**Comment by SlvrEagle23** [comment] 2021-01-12 02:21
@jdrodriguez Can you be more specific? Is album art just not working at all? Does it show up in the Media Manager for the files, but not on public pages when the same files are playing? We need more information to be able to diagnose this problem.

**Comment by SlvrEagle23** [comment] 2021-01-12 02:21
Closing as a duplicate of #3652.

**Closed by SlvrEagle23** 2021-01-12 02:21 UTC
Labels: error, needs more information

**Comment by jdrodriguez** [comment] 2021-01-12 16:38
The latest update fixed the issue. Thanks.
