### ISSUE TITLE
MP3 file uploads only after second try

### ISSUE THREAD

**Issue by Abqehebter** [AzuraCast/AzuraCast#4756] opened 2021-11-04 12:14 UTC
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #2c84d55 (2021-11-03 21:07)

### What happened?

As soon as I upload an MP3 file in the panel via Station, it gives me the following error on' first try....
After I uploaded the file a second time, it is where it should be.

We had the similar same mistake before here: https://github.com/AzuraCast/AzuraCast/issues/4357

![image](https://user-images.githubusercontent.com/42640247/140311191-544dfb81-6189-45e2-989b-aaf4ca15fdf5.png)

**Comment by SlvrEagle23** [comment] 2021-11-05 10:02
@SC2Mitch I can't reproduce this in my local installation; please let me know what steps you're going through to get the error indicated and/or what file I can use to reproduce it.

**Comment by Abqehebter** [comment] 2021-11-07 22:18
Difficult to reproduce, I must admit.
Sometimes the error comes and sometimes not.

**Comment by Vaalyn** [comment] 2021-11-08 04:49
Can you try getting the raw response of the request via the browsers network tab in the dev tools?
Maybe we can pin this further down by seeing what the server is sending back to you when this happens.

**Comment by Abqehebter** [comment] 2021-11-08 11:11
@Vaalyn Unfortunately, nothing special in the Network tab:
![image](https://user-images.githubusercontent.com/42640247/140731930-cd5354aa-2d56-4ae4-8ced-3c042cbcb031.png)
...but the same error in the console:
![image](https://user-images.githubusercontent.com/42640247/140731675-59aa27d8-e776-4903-bbaa-e0ef606a554f.png)

**Comment by SC2Mitch** [comment] 2022-01-22 18:34
Seems to be fixed now.

**Comment by Abqehebter** [comment] 2022-01-22 18:35
Seems so. Thanks for investigating.

**Closed by SC2Mitch** 2022-01-22 18:34 UTC
Labels: bug, unexpected behaviour, rolling-release
