### ISSUE TITLE
Weird error when requesting a song

### ISSUE THREAD

**Issue by christiansacks** [AzuraCast/AzuraCast#5373] opened 2022-05-13 20:55 UTC
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #ca0c8a3 (2022-04-28 12:01) • Docker • PHP 8.1

### What happened?

go to song request, press the last page button, start typing once it's got to the last page, this happens. Ideas?
![image](https://user-images.githubusercontent.com/40481087/168388386-222a929b-cfd9-4861-894f-aebb13024004.png)

**Comment by Vaalyn** [comment] 2022-05-13 21:08
Duplicate of https://github.com/AzuraCast/AzuraCast/issues/4034

**Closed by Vaalyn** 2022-05-13 21:08 UTC
Labels: duplicate
