### ISSUE TITLE
Listener stats not working anymore

### ISSUE THREAD

**Issue by surihost** [AzuraCast/AzuraCast#174] opened 2017-06-29 14:59 UTC
Hello,

I just updated azuracast and see that live listener stats not working anymore all of then showing 0, also the now playing status is not working keep showing " Song Title Song Artist"
     
in the station/reports/listeners it shows the ip's of the listener, but not on the google map,and as said before on the dashboard station overview evry station is showing 0 listener.

**Comment by surihost** [comment] 2017-06-30 13:51
I have reinstalled my vps again,and strange enough i see now the total listerners but the google map listerner stats is not working again also the listerner charts not working anymore.

**Comment by SlvrEagle23** [comment] 2017-06-30 14:15
@surihost This seems to be an issue specific to your installation. If you don't mind, I would like to take a look at it and see what the problem is. It may be in how your mount points are configured or otherwise different from what the system expects as its defaults.

**Comment by surihost** [comment] 2017-06-30 14:24
Ok just sent you an email.

**Comment by SlvrEagle23** [comment] 2017-06-30 14:47
@surihost Try updating...just changed something that should fix it.

**Comment by surihost** [comment] 2017-06-30 14:54
Ok i updated and google listener map is working now.
Please check the charts also on the dashboard, seems not to work anymore.

**Comment by SlvrEagle23** [comment] 2017-06-30 14:58
@surihost How long has that installation been running? It won't produce charts until at least a few hours have passed, to give it time to generate data.

**Comment by surihost** [comment] 2017-06-30 15:01
Oh ok, then have to wait for that.Cause i reinstalled it today.

**Comment by SlvrEagle23** [comment] 2017-06-30 15:03
@surihost Okay, it should start producing statistics soon. Closing this ticket as the listener map issue is fixed.

**Comment by surihost** [comment] 2017-06-30 15:41
I have sent you an email again, same thing happens again, on the dashboars all station listerner is showing 0.

**Closed** 2017-07-02 00:17 UTC
Labels: bug
