### ISSUE TITLE
Error On Installation

### ISSUE THREAD

**Issue by Ilario42** [AzuraCast/AzuraCast#506] opened 2018-03-20 19:59 UTC
- **Traditional**
- **Ubuntu 16.04 -->

TASK [influxdb : Set Up InfluxDB] ***********************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/util/cli.php azuracast:setup:influx", "delta": "0:00:00.018671", "end": "2018-03-20 15:53:12.810894", "msg": "non-zero return code", "rc": 255, "start": "2018-03-20 15:53:12.792223", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

**Comment by SlvrEagle23** [comment] 2018-03-20 21:09
If you manually run:
```
php /var/azuracast/www/util/cli.php azuracast:setup:influx
```
in your terminal, what do you see?

**Comment by kenshin869** [comment] 2018-03-21 00:53
Hello, it also happens to me

```
root@C5:/var/azuracast/www# php /var/azuracast/www/util/cli.php azuracast:setup:influx
The program 'php' can be found in the following packages:
 * php7.0-cli
 * hhvm
Try: apt install <selected package>
```
I tried to install php-7.0cli by hand the result was that I was asked to have the composer install it but I needed the php-7.1 version and still the errors some components of the composer needed php-7.2

```
TASK [azuracast-radio : include_tasks] ************************************************************************************************************************************************************
included: /var/azuracast/www/util/ansible/roles/azuracast-radio/tasks/x86.yml for localhost

TASK [azuracast-radio : Install IceCast-KH Dependencies] ******************************************************************************************************************************************
failed: [localhost] (item=[u'libxml2', u'libxslt1-dev', u'libvorbis-dev', u'libssl-dev', u'libcurl4-openssl-dev', u'pkg-config']) => {"cache_update_time": 1521593585, "cache_updated": false, "changed": false, "item": ["libxml2", "libxslt1-dev", "libvorbis-dev", "libssl-dev", "libcurl4-openssl-dev", "pkg-config"], "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'libssl-dev' -o APT::Install-Recommends=no' failed: E: There were unauthenticated packages and -y was used without --allow-unauthenticated\n", "rc": 100, "stderr": "E: There were unauthenticated packages and -y was used without --allow-unauthenticated\n", "stderr_lines": ["E: There were unauthenticated packages and -y was used without --allow-unauthenticated"], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nRecommended packages:\n  libssl-doc\nThe following packages will be upgraded:\n  libssl-dev\n1 upgraded, 0 newly installed, 0 to remove and 12 not upgraded.\nNeed to get 1584 kB of archives.\nAfter this operation, 68.6 kB disk space will be freed.\nWARNING: The following packages cannot be authenticated!\n  libssl-dev\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "Recommended packages:", "  libssl-doc", "The following packages will be upgraded:", "  libssl-dev", "1 upgraded, 0 newly installed, 0 to remove and 12 not upgraded.", "Need to get 1584 kB of archives.", "After this operation, 68.6 kB disk space will be freed.", "WARNING: The following packages cannot be authenticated!", "  libssl-dev"]}

RUNNING HANDLER [azuracast-user : send user notification] *****************************************************************************************************************************************
```
But it generates this other error

**Comment by SlvrEagle23** [comment] 2018-03-21 01:01
@Ilario42 @kenshin869 I've posted an update that should resolve the issue with the installer failing at the InfluxDB step. Try pulling down the updated code (`git reset --hard && git pull`) then re-running the installer steps on the readme, and let me know if that helps.

**Comment by kenshin869** [comment] 2018-03-21 10:48
Hello good morning, I have reinstalled it on a new server with ubuntu 16.04 and it does not give that error, but it has given another error later, attached last log.

```
TASK [php : Remove Old PHP Libraries] ***************************************************************************************************
ok: [localhost] => (item=[u'php5-common', u'php5-fpm', u'php5-cli', u'php5-phalcon', u'php7.0-fpm', u'php7.0-cli', u'php7.0-gd', u'php7.0-curl', u'php7.0-xml', u'php7.0-zip', u'php7.0-mysqlnd', u'php7.0-mbstring', u'php7.0-intl', u'php7.0-phalcon', u'php7.1-fpm', u'php7.1-cli', u'php7.1-gd', u'php7.1-curl', u'php7.1-xml', u'php7.1-zip', u'php7.1-mysqlnd', u'php7.1-mbstring', u'php7.1-intl', u'php7.1-redis'])

TASK [php : Install PHP 7.2] ************************************************************************************************************
changed: [localhost] => (item=[u'php7.2-fpm', u'php7.2-cli', u'php7.2-gd', u'php7.2-curl', u'php7.2-xml', u'php7.2-zip', u'php7.2-mysqlnd', u'php7.2-mbstring', u'php7.2-intl', u'php7.2-redis'])

TASK [php : List locales] ***************************************************************************************************************
changed: [localhost]

TASK [php : Create Locales] *************************************************************************************************************
failed: [localhost] (item=compiled) => {"changed": false, "item": "compiled", "msg": "The locales you've entered is not available on your system."}
changed: [localhost] => (item=de_DE.UTF-8)
changed: [localhost] => (item=es_ES.UTF-8)
changed: [localhost] => (item=fr_FR.UTF-8)
changed: [localhost] => (item=hu_HU.UTF-8)
changed: [localhost] => (item=it_IT.UTF-8)
changed: [localhost] => (item=pl_PL.UTF-8)
changed: [localhost] => (item=ru_RU.UTF-8)

RUNNING HANDLER [azuracast-user : send user notification] *******************************************************************************

PLAY RECAP ******************************************************************************************************************************
localhost                  : ok=44   changed=37   unreachable=0    failed=1

```

Error message

`The locales you've entered is not available on your system.`

Thank you very much for your attention and help.

**Comment by SlvrEagle23** [comment] 2018-03-21 14:50
@kenshin869 Ah, it appears I forgot to remove an installation step that is no longer needed in the newer codebase. If you don't mind, can you update and try again? It should be fixed.

**Comment by Ilario42** [comment] 2018-03-21 15:14
Man.... From a gigantic mistake now that you've updated
Please solve!
![image](https://user-images.githubusercontent.com/22561729/37718452-fa16138e-2d22-11e8-9fe0-ab061d1045fa.png)


https://hastebin.com/zoqifepeqa.tex

**Comment by Ilario42** [comment] 2018-03-21 15:30
I have solved the problem. BUT:

I have execute current commands: 
1) opam init -y && opam update && opam install -y taglib.0.3.3 mad.0.4.5 faad.0.3.3 fdkaac.0.2.1 lame.0.3.3 vorbis.0.7.0 cry.0.6.0 flac.0.1.2 opus.0.1.2 liquidsoap.1.3.3

2) sudo apt-get update && sudo apt-get install influxdb

**Comment by Ilario42** [comment] 2018-03-21 15:31
![image](https://user-images.githubusercontent.com/22561729/37719439-4b9708ec-2d25-11e8-8172-ea753e3c5ce1.png)

**Comment by kenshin869** [comment] 2018-03-21 16:42
Hello, the installation of php7 has already been established, it has generated two errors, one of them is that the test database does not exist, I imagine it is normal and I ignore it in fact the system ignores it and continues, the other for the new the installation apparently for something related to influxdb, says that it does not exist.

```
TASK [services : Set Redis service name] **********************************************************************************************************************************************************
ok: [localhost]

TASK [services : Enable and restart all core services] ********************************************************************************************************************************************
failed: [localhost] (item=influxdb) => {"changed": false, "item": "influxdb", "msg": "Could not find the requested service influxdb: host"}
changed: [localhost] => (item=mysql)
changed: [localhost] => (item=php7.2-fpm)
changed: [localhost] => (item=nginx)
changed: [localhost] => (item=redis)

RUNNING HANDLER [azuracast-user : send user notification] *****************************************************************************************************************************************

RUNNING HANDLER [azuracast-db-install : send mysql notification] **********************************************************************************************************************************

PLAY RECAP ****************************************************************************************************************************************************************************************
localhost                  : ok=77   changed=58   unreachable=0    failed=1

```

If I install manually, influxdb generates another error.

```
TASK [influxdb : Pause to allow InfluxDB to spin up] **********************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "elapsed": 300, "msg": "Timeout when waiting for 127.0.0.1:8086"}

```

It also generates another error regarding liquidsoap but not for the installation just in case it is attached.

```
TASK [supervisord : Kill legacy radio processes (if upgrading from older version)] ****************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["killall", "-q", "-9", "icecast2", "sc_serv", "liquidsoap"], "delta": "0:00:00.002866", "end": "2018-03-21 16:17:36.328812", "msg": "non-zero return code", "rc": 1, "start": "2018-03-21 16:17:36.325946", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
...ignoring

```
When you run the installer again this error does not come back out again.

Thanks.

**Comment by SlvrEagle23** [comment] 2018-03-21 19:39
@kenshin869 Other than the InfluxDB error, the other errors are known and acceptable, and the system ignores them and continues on purpose.

Is your installation working now?

**Comment by kenshin869** [comment] 2018-03-21 20:20
No, it still fails in the step influxdb is cut and does not get to start anything

**Comment by SlvrEagle23** [comment] 2018-03-21 20:22
@kenshin869 I discovered the cause of that and have updated the installation tools accordingly just now; please update and try again.

**Comment by ritche** [comment] 2018-03-22 17:11
I received this error while installing.

TASK [ufw : UFW - Turn on Firewall] ********************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "WARN: uid is 0 but '/'                                                                                         is owned by 1000\nERROR: problem running ufw-init\nmodprobe: ERROR: ../libkmod/                                                                                        libkmod.c:514 lookup_builtin_file() could not open builtin file '/lib/modules/2.                                                                                        6.32-042stab127.2/modules.builtin.bin'\nmodprobe: FATAL: Module nf_conntrack_ftp                                                                                         not found in directory /lib/modules/2.6.32-042stab127.2\nmodprobe: ERROR: ../li                                                                                        bkmod/libkmod.c:514 lookup_builtin_file() could not open builtin file '/lib/modu                                                                                        les/2.6.32-042stab127.2/modules.builtin.bin'\nmodprobe: FATAL: Module nf_nat_ftp                                                                                         not found in directory /lib/modules/2.6.32-042stab127.2\nmodprobe: ERROR: ../li                                                                                        bkmod/libkmod.c:514 lookup_builtin_file() could not open builtin file '/lib/modu                                                                                        les/2.6.32-042stab127.2/modules.builtin.bin'\nmodprobe: FATAL: Module nf_conntra                                                                                        ck_netbios_ns not found in directory /lib/modules/2.6.32-042stab127.2\niptables-                                                                                        restore: line 4 failed\niptables-restore: line 77 failed\niptables-restore: line                                                                                         36 failed\nip6tables-restore: line 4 failed\nip6tables-restore: line 138 failed                                                                                        \nip6tables-restore: line 36 failed\nsysctl: permission denied on key 'net.ipv4.                                                                                        tcp_sack'\n\nProblem running '/etc/ufw/before.rules'\nProblem running '/etc/ufw/                                                                                        user.rules'\nProblem running '/etc/ufw/before6.rules'\nProblem running '/etc/ufw                                                                                        /user6.rules'\n\n"}

RUNNING HANDLER [azuracast-user : send user notification] **********************

RUNNING HANDLER [azuracast-db-install : send mysql notification] ***************

PLAY RECAP *********************************************************************
localhost                  : ok=72   changed=55   unreachable=0    failed=1

**Comment by SlvrEagle23** [comment] 2018-03-22 17:22
I don't want to have a single thread devoted to every possible installation error with the traditional installer, as these issues are actually totally different and unrelated to one another.

The initial issue of InfluxDB failing to install (and other installation failures that resulted from updates to the code on my end) have, it appears, been resolved.

@ritche Your issue appears to be related to the installation of the UFW firewall and unrelated to the other problems in this thread, so you should make a new issue about it. Be sure to specify what version of Ubuntu you're running in that new thread.

It's worth noting that issues like this are precisely why I strongly recommend using the Docker installation method if at all possible, because using this method I can prebuild entire images that already have the necessary software set up and configured exactly as it needs to be, without just crossing my fingers and hoping it all installs on your machine with your specific software setup. If this were a bigger project with a budget or more than one developer, we might be able to provide better support for those kinds of questions, but as it stands right now, resources are very limited.

**Closed by SlvrEagle23** 2018-03-22 17:22 UTC
Labels: bug

**Comment by ritche** [comment] 2018-03-23 06:33
Hi,

I am using Ubuntu 16.04.1 LTS and I got a lot of errors also installing docker error.

E: Sub-process /usr/bin/dpkg returned an error code (1).

Can you provide which distro and version we can use without problem?

**Comment by SlvrEagle23** [comment] 2018-03-23 14:34
@ritche As I mentioned above, please create a new issue with any other questions. Your issue, while it also relates to installation in general, does not relate to the already-resolved issue in this thread.

**Comment by Ilario42** [comment] 2018-03-23 19:18
@SlvrEagle23 
New error: 
TASK [influxdb : Pause to allow InfluxDB to spin up] ***************************
fatal: [localhost]: FAILED! => {"changed": false, "elapsed": 300, "msg": "Timeou                                                                                                                                                             t when waiting for 127.0.0.1:8086"}
