### ISSUE TITLE
Webhook Menu Error

### ISSUE THREAD

**Issue by pde-system-integration** [AzuraCast/AzuraCast#3526] opened 2020-12-09 04:39 UTC
pls help me check why I get error when clicking menu WebHook
![image](https://user-images.githubusercontent.com/72959779/101585799-1a99aa80-3a13-11eb-82e2-cda06cf8755f.png)
Many thanks!

**Comment by SlvrEagle23** [comment] 2020-12-09 08:10
Closing as duplicate of #3520 .

**Closed by SlvrEagle23** 2020-12-09 08:10 UTC
