### ISSUE TITLE
Disable duplicate songs

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#420] opened 2018-02-10 12:04 UTC
Tell me please how can I turn off the repetition of the songs, so that there is mixing, but the songs did not repeat? Thank you very much.

**Comment by SlvrEagle23** [comment] 2018-02-10 14:21
@susl16c I'd also prefer if we could avoid the repetition of github issues, particularly since the last one, also _started by you_, is still open and pending a response.

Closed as duplicate of #406.

**Closed by SlvrEagle23** 2018-02-10 14:21 UTC
