### ISSUE TITLE
Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

### ISSUE THREAD

**Issue by KoenJonguh** [AzuraCast/AzuraCast#328] opened 2017-12-12 13:49 UTC
I want to install AzuraCast on my Ubuntu 17.04 server but i got that error.
Anyone help please?

Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

**Comment by SlvrEagle23** [comment] 2017-12-12 23:18
@KoenJonguh Sometimes the first portion of the installer (which installs Docker Compose and Docker itself) makes changes that require a restart before the second half can complete.

I'll be updating the instructions on the main readme shortly to include the Docker installation as a separate step, so people know there's frequently a reboot or logout needed between the two.

**Comment by KoenJonguh** [comment] 2017-12-13 12:57
hi! 
Thanks. I rebooted and tried to update it but got this error back. 

_**"If it's at a non-standard location, specify the URL with the DOCKER_HOST environ                                      ment variable.
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is i                                      t running?"**_

I really want this software to workkk, what could i do to fix this?

**Comment by KoenJonguh** [comment] 2017-12-13 13:15
I just removed my AzuraCast folder and started from the beginning. so from step 1.
At step 3 _**"./docker-install.sh"**_ I got the same error. 3 times.

![errorazura](https://user-images.githubusercontent.com/28997723/33940634-095cb470-e010-11e7-814f-792e89f5d675.PNG)

**Comment by SlvrEagle23** [comment] 2017-12-13 13:19
@KoenJonguh If Docker doesn't appear to be running, the installer won't be able to complete no matter what.

You may need to enable and start the Docker service for your environment. It may be something as simple as `systemctl enable docker` and `systemctl start docker`.

**Comment by KoenJonguh** [comment] 2017-12-13 13:31
Hi! thanks,

This is what i get after i do `systemctl enable docker`
![error_systemctl_enable](https://user-images.githubusercontent.com/28997723/33941253-3f8d9ff8-e012-11e7-9c2e-7c6915f006f0.PNG)

And this after `systemctl start docker`
![error_systemctl_start](https://user-images.githubusercontent.com/28997723/33941258-491838c6-e012-11e7-87cb-449a7be1be58.PNG)
I'm sorry, i'm still a beginner

**Comment by SlvrEagle23** [comment] 2017-12-13 13:34
@KoenJonguh Something's wrong with your Docker install...I can't tell from looking at it what the problem is, but you may be able to fix it by uninstalling and reinstalling Docker.

**Comment by KoenJonguh** [comment] 2017-12-13 13:38
hi, Thanks :)

so.. this happens when i try to uninstall it

![dockeruninstall](https://user-images.githubusercontent.com/28997723/33941517-3bd91c4c-e013-11e7-9af2-2eff9b094a7b.PNG)

**Comment by SlvrEagle23** [comment] 2017-12-13 13:39
@KoenJonguh The issues you're having aren't with AzuraCast but with Docker, so I would recommend that you seek out help from the Docker community at large for the issue. You can search the web for most of these issues and find general solutions, but I'm not in the position to offer tech support for a product that isn't mine.

**Comment by KoenJonguh** [comment] 2017-12-13 13:40
ah okay, thank you for your help :)

**Comment by KoenJonguh** [comment] 2017-12-13 14:35
I completely reinstalled my server and tried it again. Still the same problem. I'm using ubuntu 16.04.

**Comment by HiseEiichi** [comment] 2017-12-14 01:59
@KoenJonguh Have you tried the traditional installation? I tested it on a VM and it worked perfectly.

**Comment by SlvrEagle23** [comment] 2017-12-16 18:04
@KoenJonguh I'm closing this issue, as it relates far more to Docker than it does to AzuraCast, whose Docker installation should work just fine once you're able to resolve whatever issue is affecting Docker.

If I had a guess at the problem, I'd say it's probably that there's already an instance of Docker installed on your server image, and that should be removed prior to using the Docker CE installer that's included in the AzuraCast instructions.

**Closed by SlvrEagle23** 2017-12-16 18:04 UTC
