### ISSUE TITLE
Stream stop working after 6-8 hours

### ISSUE THREAD

**Issue by MyTheValentinus** [AzuraCast/AzuraCast#884] opened 2018-10-21 15:40 UTC
**Installation method**
Docker

**Host OS (for Docker installations)**
Ubuntu 18.04

**Describe the bug**
After 6-8 hours of listening the stream, it's cut.
I already changed the codec to encode without sucess, same problem.
I changed the nginx reverse proxy read_tiemout and send_timeout too without sucess.
No error report in logs

**To Reproduce**
Monitor the audio stream long time

Tested on multiple clients (VLC, Firefox, Chrome, Multiple CURL Libs)

**Comment by CodeSteele** [comment] 2018-10-21 16:10
@MyTheValentinus can you check and see if your config folder has core dump files like #876?

Does the stream auto-restart or do you have to do something to start it up again?

**Comment by MyTheValentinus** [comment] 2018-10-21 16:17
I need to refresh used client.
No core dump in my config folder.
See files list: https://pastebin.com/raw/Z9qSFqRi

**Comment by CodeSteele** [comment] 2018-10-21 16:27
Ah okay so just the player disconnects? Hmm, this is going to be annoying to reproduce, lots of non-AzuraCast issues may be causing it (any kind of network quality issue), I'm also not entirely sure there aren't going to be side-effects by blocking stuff accessing `/api/` in #848 being as some _internal_ services use it too (though I'd imagine their failures would happen pretty quickly), so you need to whitelist all the other docker instances.

If you run multiple players in parallel do they all drop at the same time?

**Comment by MyTheValentinus** [comment] 2018-10-21 16:39
Please, do not shuffle problems. This problem was not related with my previous issue "`/api/`" (between all my containers there use default nginx container without whitelist).
Clients not drop at the same time. In my case for testing i use the direct url (internal) of your icecast fork, i can not determine which component is involved, icecast ? Docker ?
There as why i write a issue here.

**Comment by CodeSteele** [comment] 2018-10-21 17:10
> Please, do not shuffle problems.

Consider it just notes on basically what I should follow up on (reproduce in our environment) if I struggle to reproduce the issue with a standard install.

But yeah you're correct that this is a different issue to track separately.

> Clients not drop at the same time. In my case for testing i use the direct url (internal) of your icecast fork, i can not determine which component is involved, icecast ? Docker ?

Well if the clients don't all drop at the same time, it suggests that the service is at least healthy (eg: not crashing), but that also means I can't exactly go jumping on blaming our fork of Icecast (an easy blame for me to go fix something I caused), and that it now can be pretty much anything else in the stack (from network -> Icecast)

I'll have to run some streams overnight and see if I can reproduce.

---

I'll defer to @SlvrEagle23 on the best logs to have you pull at this point if I can't reproduce it.

**Comment by MyTheValentinus** [comment] 2018-10-21 17:12
Okay, i waiting your tests to see if you have the same problem. Have a good tests :)

**Comment by SlvrEagle23** [comment] 2018-10-21 20:51
@MyTheValentinus Check the station logs (`docker-compose logs -f stations`). You may be seeing a flood of error log items from Liquidsoap. @CodeSteele is correct in that blocking the `/api` endpoint may actually be contributing to this, as Liquidsoap uses that endpoint to retrieve the next song to play, and if it fails to retrieve it, it'll just keep trying over and over again.

**Comment by MyTheValentinus** [comment] 2018-10-21 21:01
Some error:
decode error (3-4 times / day):
`2018/10/21 19:10:54 [decoder:3] Unable to decode "/var/azuracast/stations/radio/media/final complet/01 Cimarr\195\178n.wma" as {audio=1+;video=0;midi=0}!`

Another error:
`
2018/10/21 12:29:10 [azuracast_next_song:3] Prepared "/var/azuracast/stations/radio/media/final complet/Portishead_Dummy_Glory Box.mp3" (RID 4).
2018/10/21 12:29:10 [fallback_6031:3] Switch to azuracast_next_song_cued with transition.
2018/10/21 12:29:10 [dummy:3] Source failed (no more tracks) stopping output...
2018-10-21 12:29:11,493 INFO success: station_1_backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
`

And restart error ?: https://pastebin.com/raw/ajebwP4j

**Comment by CodeSteele** [comment] 2018-10-21 21:12
@MyTheValentinus that pastebin clip needs to contain lines before that, I only see where it core dumps and moves on. I'd like to see a quite a few lines before that.

Also we don't support WMA out of the box as per #495. Though it _shouldn't_ cause Liquidsoap to crash.

**Comment by MyTheValentinus** [comment] 2018-10-22 09:04
Hello @CodeSteele, before theses lines nothing with error or anormal log.

But today, i grep the word "error" in logs, the results was interesting:
https://pastebin.com/raw/LatFa9P5
I do not know if the cuts take place at the same time

**Comment by MyTheValentinus** [comment] 2018-11-01 13:15
Hello, 
Update from last crash:
```
2018-09-30 13:26:40     INFO    [ADMINCGI sid=1] Title updated [Desconocido - Pista 01]
2018-09-30 13:27:10     DEBUG   [SRC 127.0.0.1:36142 sid=1] Remote socket closed while waiting for data.
2018-09-30 13:27:10     INFO    [SRC 127.0.0.1:36142 sid=1] SHOUTcast 1 source disconnected.
2018-09-30 13:27:10     INFO    [MAIN] Exiting threads...
2018-09-30 13:27:10     INFO    [MAIN] Terminating listeners...
2018-09-30 13:27:10     INFO    [MAIN] Terminating sources...
... (Here, some lines, for each client close http connection)
2018-09-30 13:27:10     INFO    [STATS] Peak numbers: #1:9,Total: 9
2018-09-30 13:27:10     INFO    [BANDWIDTH] Total: 7015220965, Sent: 3615242589, Recv: 3399978376
2018-09-30 13:27:10     INFO    [MAIN] Shutdown after 1 day 15 hours 21 minutes 6 seconds running

```

**Comment by MyTheValentinus** [comment] 2018-11-01 13:51
From latest update (2018/11/01) of all dockers, my station crash lot of. Without log

**Comment by MyTheValentinus** [comment] 2018-11-02 10:00
Last crash, the logs:
```
2018/11/02 09:57:11 [radio_5050_local_1:3] Connection setup was successful.
2018/11/02 09:57:11 [threads:3] Created thread "wallclock_main" (1 total).
2018/11/02 09:57:11 [clock.wallclock_main:3] Streaming loop starts, synchronized with wallclock.
2018/11/02 09:57:11 [radio_5050_live_switch:3] Switch to radio_5050_playlist_fallback.
2018/11/02 09:57:11 [radio_5050_playlist_fallback:3] Switch to blank_6027.
2018/11/02 09:57:11 [radio_5050_next_song:3] Prepared "/var/azuracast/stations/radio_5050/media/final complet/XX.mp3" (RID 2).
2018/11/02 09:57:11 [radio_5050_playlist_fallback:3] Switch to radio_5050_cue_cut with transition.
2018/11/02 09:57:11 [dummy:3] Source failed (no more tracks) stopping output...
2018-11-02 09:57:12,818 INFO success: station_1_backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018/11/02 09:57:28 main.go:90: Change in content: triggering web hook
2018/11/02 09:57:32 main.go:90: Change in content: triggering web hook
```

**Comment by MyTheValentinus** [comment] 2018-11-02 10:02
Crash on api of azuracast that handle next music song ?

**Comment by MyTheValentinus** [comment] 2018-11-02 10:03
And the web log:
```
[02-Nov-2018 09:57:11] WARNING: [pool www] child 3101 said into stderr: "[2018-11-02 10:57:11] AzuraCast.ERROR: Return value of NowPlaying\Adapter\Icecast::_getXmlNowPlaying() must be of the type array, null returned {"file":"/var/azuracast/www/vendor/azuracast/nowplaying/src/Adapter/Icecast.php","line":126,"code":0} {"station":{"id":1,"name":"Radio 50/50"}}"

```

**Comment by CodeSteele** [comment] 2018-11-02 11:32
>  station_1_backend (terminated by SIGSEGV (core dumped)

That would be liquidsoap segmentation faulting, so same as #876.

See this comment specifically: https://github.com/AzuraCast/AzuraCast/issues/876#issuecomment-432494910

So it's an upstream problem we've been unable to reproduce, I may have to do something silly and drop an entire media library into AzuraCast and see if it has to do with LiquidSoap dealing with very large playlists (I notice you have nearly 1600 tracks), it's the only factor I can think of.

**Comment by CodeSteele** [comment] 2018-11-02 11:34
I'm going to close this being as I updated #876 to specifically address LiquidSoap segfaulting.

**Closed by CodeSteele** 2018-11-02 11:34 UTC
Labels: duplicate, error
