### ISSUE TITLE
MariaDB does not start after upgrade: [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed

### ISSUE THREAD

**Issue by aripisprecer** [AzuraCast/AzuraCast#5741] opened 2022-09-17 18:36 UTC
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

- upgraded to the latest rolling version and it seems that MariaDB is not able to start anymore
- could be that `LimitMEMLOCK=2M` in `/etc/systemd/system/mariadb.service.d/limitcore.conf` leads to this the problem

### Relevant log output

```shell
2022-09-17 18:06:14 0 [Note] mysqld (server 10.9.2-MariaDB-1:10.9.2+maria~ubu2204) starting as process 93 ...
2022-09-17 18:06:14 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2022-09-17 18:06:14 0 [Note] InnoDB: Number of transaction pools: 1
2022-09-17 18:06:14 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
2022-09-17 18:06:14 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
2022-09-17 18:06:14 0 [Warning] mysqld: io_uring_queue_init() failed with ENOMEM: try larger memory locked limit, ulimit -l, or https://mariadb.com/kb/en/systemd/#configuring-limitmemlock under systemd (262144 bytes required)
2022-09-17 18:06:14 0 [Warning] InnoDB: liburing disabled: falling back to innodb_use_native_aio=OFF
2022-09-17 18:06:14 0 [Note] InnoDB: Initializing buffer pool, total size = 128.000MiB, chunk size = 2.000MiB
2022-09-17 18:06:14 0 [Note] InnoDB: Completed initialization of buffer pool
2022-09-17 18:06:14 0 [ERROR] InnoDB: File ./ib_logfile0 was not found
2022-09-17 18:06:14 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
2022-09-17 18:06:14 0 [Note] InnoDB: Starting shutdown...
2022-09-17 18:06:14 0 [ERROR] Plugin 'InnoDB' init function returned error.
2022-09-17 18:06:14 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2022-09-17 18:06:14 0 [Note] Plugin 'FEEDBACK' is disabled.
2022-09-17 18:06:14 0 [ERROR] Unknown/unsupported storage engine: InnoDB
2022-09-17 18:06:14 0 [ERROR] Aborting
```

**Comment by AndreBlin** [comment] 2022-09-17 19:30
same here :(

**Comment by ItsMitchh** [comment] 2022-09-17 19:40
We're aware of users having issues with the latest rolling release, be patient and we're working on it.

**Comment by BusterNeece** [comment] 2022-09-18 00:33
@aripisprecer @AndreBlin We've identified the cause of this issue and a fix has been published to the Rolling Release version. Please update and confirm that the issue is fixed for your installation. Thanks for your patience!

**Comment by unzelnet** [comment] 2022-09-18 08:19
Still the same problem.
Not solved here..

**Comment by BusterNeece** [comment] 2022-09-18 08:20
@unzelnet One of our Rolling Release updates resulted in some data corruption; if you have a backup of your installation, I'd recommend restoring that as the easiest way of resolving the issue. Sorry for the inconvenience, there are some issues with our database (MariaDB).

**Comment by BusterNeece** [comment] 2022-09-18 09:54
If you don't have a backup and need to restore the situation, here's what you may be able to do:

SSH into your server

`cd /var/azuracast` (or wherever it's installed)

Run `docker-compose exec web bash` to get into the running container as root

Inside the container: 

```
supervisorctl stop mariadb
touch /var/lib/mysql/ib_logfile0
touch /var/lib/mysql/ib_logfile1
chown mysql:mysql /var/lib/mysql/ib_*
supervisorctl stop mariadb
```

You should now be able to exit the container (via `exit`), then re-attempt the update.

**Comment by aripisprecer** [comment] 2022-09-18 10:15
> @aripisprecer @AndreBlin We've identified the cause of this issue and a fix has been published to the Rolling Release version. Please update and confirm that the issue is fixed for your installation. Thanks for your patience!

I've tried the update too and it's not solving the issue.

I have restored the VM with a working version of Azura 0.15.2 stable, switched to rolling update channel but i cant pull the images because of a docker limitation... i think i have to wait some time before pulling it again:

`
 [OK] Server configuration complete!


Pulling mariadb                 ... error
Pulling redis                   ... error
Pulling stations                ... error
Pulling web                     ... error
Pulling nginx_proxy             ... done
Pulling nginx_proxy_letsencrypt ... done

ERROR: for mariadb  Head "https://ghcr.io/v2/azuracast/db/manifests/latest": denied

ERROR: for web  Head "https://ghcr.io/v2/azuracast/web/manifests/latest": denied

ERROR: for redis  Head "https://ghcr.io/v2/azuracast/redis/manifests/latest": denied

ERROR: for stations  Head "https://ghcr.io/v2/azuracast/radio/manifests/latest": denied
ERROR: Head "https://ghcr.io/v2/azuracast/db/manifests/latest": denied
Head "https://ghcr.io/v2/azuracast/web/manifests/latest": denied
Head "https://ghcr.io/v2/azuracast/redis/manifests/latest": denied
Head "https://ghcr.io/v2/azuracast/radio/manifests/latest": denied
Removing network azuracast_backend
`

**Comment by BusterNeece** [comment] 2022-09-18 10:19
@aripisprecer You may have an out-of-date `docker.sh` file, since we've now switched to a single-container setup; you may need to run `docker.sh update-self` first.

**Comment by aripisprecer** [comment] 2022-09-18 10:25
> docker.sh update-self

@BusterNeece i followed the update steps and already did that before:

`./docker.sh update-self
New Docker utility script downloaded.
`

**Comment by BusterNeece** [comment] 2022-09-18 10:25
@aripisprecer Do you have a `docker-compose.override.yml` file?

**Comment by aripisprecer** [comment] 2022-09-18 10:26
yes, i have an old file:

`-rw-r--r--  1 root root 4.8K Sep  7  2021 docker-compose.override.yml`

**Comment by BusterNeece** [comment] 2022-09-18 10:27
@aripisprecer You may need to update that file as well.

In any case, that's a different issue than the one originally reported here.

**Comment by aripisprecer** [comment] 2022-09-18 10:30
ok, should i rename/remove it before re-trying to upgrade?

**Comment by BusterNeece** [comment] 2022-09-18 10:31
@aripisprecer Depends on what you have in it.

Since you're not having this specific issue, though, let's close this GitHub issue. We can continue this if needed on our Discord https://discord.gg/azuracast

**Closed by BusterNeece** 2022-09-18 10:31 UTC
Labels: bug, rolling-release

**Comment by AndreBlin** [comment] 2022-09-18 11:53
> @aripisprecer @AndreBlin We've identified the cause of this issue and a fix has been published to the Rolling Release version. Please update and confirm that the issue is fixed for your installation. Thanks for your patience!

Thank you for the quick and comprehensive troubleshooting. I made a backup last night just to be on the safe side. After you informed me that the problems were solved I updated the container.  Everything is fine here. Thank you very much and best regards.
