### ISSUE TITLE
Playing now API broken.

### ISSUE THREAD

**Issue by markus-dark-green** [AzuraCast/AzuraCast#3392] opened 2020-11-10 10:54 UTC
Rolling Release #6de636f (2020-11-10 3:06) 

For some Songs the playing now api does not provide the correct artwork link. It falls back to the default picture.  Additionaly the playlist attribute is empty and  duration is 0
Also the custom  attributes are missing.
It often happens when playlists are switched <-- just a guess

Any suggestions?

thx in advance and thx for this super cool project

**Comment by markus-dark-green** [comment] 2020-11-12 09:40
Any news on this or am i alone with this behaviour ?

**Comment by Paulio759** [comment] 2020-11-13 22:37
You are not alone on this, I reported a simmilar issue (#3347) and there seems to be a few more related issues on here.

**Comment by markus-dark-green** [comment] 2020-11-14 12:18
Thx so far.

**Comment by dturrina** [comment] 2020-11-17 07:44
Having the same issue, even with the very last installation (rolling e1e8a7b)

**Comment by SlvrEagle23** [comment] 2020-11-18 23:32
Closing as a likely duplicate of #3347.

**Closed by SlvrEagle23** 2020-11-18 23:32 UTC
