### ISSUE TITLE
Install script changes ownership of user directory causing install to fail. 

### ISSUE THREAD

**Issue by scottprovost** [AzuraCast/AzuraCast#1347] opened 2019-03-27 08:10 UTC
The damages the operating system and makes other software fail. Changing the ownership of the user directory back does not help. I will spin up more versions and try but it looks like none of your installation instructions work on any version of any Linux distro.

**Comment by Vaalyn** [comment] 2019-03-27 10:15
Which install script did you use, the one for the recommended Docker installation or the advanced Bare-metal installation? What operating system are you using? What software is failing after the installation?

Since the Docker script doesn't touch anything apart from Docker & Docker-Compose on the host I'm assuming it's the advanced Bare-metal installation. Can you post any error messages that you encountered? Without any information apart from "damages the operating system and makes other software fail" we can't diagnose what's exactly happening here. Keep in mind that the Bare-metal installation **will** modify your system by installing additional software packages like Liquidsoap, NGINX, MariaDB etc. and also uninstall packages like apache2 and lighttp because they would conflict with the software needed for AzuraCast.

Apart from that I'd like to recommend you to use the Docker installation method instead of the Bare-metal one. With Docker AzuraCast is running in isolated containers and won't touch your host system apart from installing Docker & Docker-Compose. Docker installations are also easier to debug for us so we can provide better support for this type of installation.

**Comment by scottprovost** [comment] 2019-03-27 21:12
The docker installs completely fail constantly reinstalling composer or the following error.
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

The install script was run on an a several clean Ubuntu installs following the direction on your site.

**Comment by scottprovost** [comment] 2019-03-28 01:56
Several more test where the software failed to install. 
This time on Ubuntu Studio. It went farther than any standard Linux install. 
At this time the determination is that this software is unusable on any available linux when following the published install directions on the web page.

ERROR: for azuracast_web_1  Cannot start service web: driver failed programming external connectivity on endpoint azuracast_web_1 (b1315ec9bd51283cd6d97bb764bb4d415da3aa1bf1d1b41cc24c3f37b0480247): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use

ERROR: for web  Cannot start service web: driver failed programming external connectivity on endpoint azuracast_web_1 (b1315ec9bd51283cd6d97bb764bb4d415da3aa1bf1d1b41cc24c3f37b0480247): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
ERROR: Encountered errors while bringing up the project.
user1@user1-KVM:~$ 
This was cleared up by
sudo apt-get remove apache*
Since the script does not check for available ports and change the port used as needed.

**Comment by SlvrEagle23** [comment] 2019-03-28 03:06
@scottprovost I'm sorry you're running into issues, but it's not accurate to say that the software is not installable using our standard installation instructions.

With regard to the Docker installation, our installer tool (`./docker.sh install`) will detect if a non-root user is being used to install Docker, and it will exit after installing Docker and instruct you that you need to reboot both to allow the `docker` group membership to take effect and to allow the Docker daemon to spin up.

It appears that in your second attempt with Docker, you were able to get it spun up, but you had a port conflict on port 80. Our instructions do specifically mention that AzuraCast should be installed on a freshly installed server, but it is always possible that even a freshly installed server would have Apache (or nginx, etc) installed and would be using port 80. Because our Docker installation is meant to be platform-independent, it intentionally doesn't modify the host's packages in any way, so it would be up to the server operator to remove any packages that may be causing port conflicts.

The bare-metal installation uses a series of Ansible scripts that are easily inspected via our main GitHub repository. One key aspect of these scripts is that it takes your current directory into consideration when running, and sets it as the "base" directory for the AzuraCast installation; as part of this, it also sets this directory to be owned by the newly created `azuracast` user. Our [bare-metal installation instructions](https://www.azuracast.com/install_traditional.html) are very clear about cloning the repository in the proper `/var/azuracast/www` directory, as they supply the following commands to be executed in the terminal:

```bash
sudo apt-get update
sudo apt-get install -q -y git

sudo mkdir -p /var/azuracast/www
cd /var/azuracast/www
sudo git clone https://github.com/AzuraCast/AzuraCast.git .

sudo chmod a+x install.sh
./install.sh
```

If you simply clone the repository (or download it directly via GH's releases) and drop it into an arbitrary directory, it will consider that directory to be its new "base" directory and thus modify the permissions of that directory (and the one above it) to be owned by the `azuracast` user. However, simply running `chown -R original_user /path/to/parent/dir` should resolve that.

If you're running an Ubuntu Desktop version, you should either use the Docker installer (which will work on anything 16.04 and newer) or you should specifically be running one of the LTS distros (16.04 or 18.04). Desktop flavors or derivatives of these distros should still work without issue.

Again, my apologies for any inconvenience you encountered as a result of our software. We're a very small team of volunteers and the project is primarily the result of my own personal development work over many years, so we don't really have the time or resources to focus on improving our documentation. We will, however, eagerly accept any pull requests to help refine our documentation and make it more accurate or safer for our users.

**Comment by scottprovost** [comment] 2019-03-28 05:04
I was asked to look at this project by a group that failed after many attempts to get it installed. I have been unable to independently certify that it is in fact well maintained or routinely install-able by a typical admin.
What I would like to do is create a deb and an RPM. This way the instructions are given to the computer via the package.

**Comment by SlvrEagle23** [comment] 2019-03-28 05:08
@scottprovost What specifically was preventing the installation in their case? It's impossible for us to debug or address issues without logs from the installer or other details.

We've definitely considered building a .deb package for AzuraCast, specifically for our already supported distributions of Ubuntu 16.04 and 18.04. We have not had the time or resources to build this package, though, and our (recommended) Docker installation uses images that are already automatically built by our configuration, all but removing the need to package the software for the host OS.

**Comment by CodeSteele** [comment] 2019-03-28 06:00
Video showing a 4 minute install on a fresh Ubuntu Server 18.04: https://youtu.be/qA-jsb9zuSI

```
steele@steele:~$ ls -lh
total 20K
-rw-rw-r-- 1 steele steele 1.8K Mar 28 05:48 azuracast.env
-rw-rw-r-- 1 steele steele 2.9K Mar 28 05:48 docker-compose.yml
-rwxrwxr-x 1 steele steele 9.2K Mar 28 05:47 docker.sh
steele@steele:~$ ls -lh /home
total 4.0K
drwxr-xr-x 4 steele steele 4.0K Mar 28 05:48 steele
```

Home directory permissions look fine. We'll need full reproduction steps and knowledge for any other systems you've tried to install it on (Ubuntu Studio is mentioned as one of the platforms attempted, what others?).

**Comment by CodeSteele** [comment] 2019-03-28 06:20
And a traditional install: https://youtu.be/3whc1WxHbF4

And user home directories after:
```
steele@steele:~$ ls -lh
total 0
steele@steele:~$ cd ..
steele@steele:/home$ ls -lh
total 4.0K
drwxr-xr-x 5 steele steele 4.0K Mar 28 06:05 steele
steele@steele:/home$
```
And AzuraCast's 
```
steele@steele:/var/azuracast/www$ ls -lh
total 488K
-rw-r--r--  1 root      root       38 Mar 28 06:03 ansible.cfg
-rw-r--r--  1 root      root     1.4K Mar 28 06:03 azuracast.dev.env
-rw-r--r--  1 root      root     1.8K Mar 28 06:03 azuracast.sample.env
drwxr-xr-x  2 root      root     4.0K Mar 28 06:03 bin
-rw-r--r--  1 root      root      691 Mar 28 06:03 codeception.yml
-rw-r--r--  1 root      root     3.2K Mar 28 06:03 CODE_OF_CONDUCT.md
-rw-r--r--  1 root      root     2.8K Mar 28 06:03 composer.json
-rw-r--r--  1 root      root     319K Mar 28 06:03 composer.lock
drwxr-xr-x  4 root      root     4.0K Mar 28 06:03 config
-rw-r--r--  1 root      root     5.7K Mar 28 06:03 CONTRIBUTING.md
-rw-r--r--  1 root      root      138 Mar 28 06:03 crowdin.yaml
-rw-r--r--  1 root      root     3.0K Mar 28 06:03 docker-compose.dev.yml
-rw-r--r--  1 root      root      227 Mar 28 06:03 docker-compose.migrate.yml
-rw-r--r--  1 root      root     2.9K Mar 28 06:03 docker-compose.sample.yml
-rw-r--r--  1 root      root      206 Mar 28 06:03 docker-compose.static.yml
-rw-r--r--  1 root      root      205 Mar 28 06:03 docker-compose.testing.yml
-rw-r--r--  1 root      root     3.0K Mar 28 06:03 docker-migrate.sh
-rwxr-xr-x  1 root      root     9.2K Mar 28 06:03 docker.sh
-rw-r--r--  1 azuracast www-data  185 Mar 28 06:13 env.ini
-rwxr-xr-x  1 root      root      783 Mar 28 06:03 install.sh
-rw-r--r--  1 root      root      12K Mar 28 06:03 LICENSE.txt
-rw-r--r--  1 root      root     1.1K Mar 28 06:03 phpstan.neon
drwxr-xr-x  2 root      root     4.0K Mar 28 06:03 plugins
-rw-r--r--  1 root      root     9.8K Mar 28 06:03 README.md
drwxr-xr-x  3 root      root     4.0K Mar 28 06:03 resources
drwxr-xr-x 19 root      root     4.0K Mar 28 06:03 src
-rw-r--r--  1 root      root     8.3K Mar 28 06:03 SUPPORT.md
drwxr-xr-x  7 root      root     4.0K Mar 28 06:03 templates
drwxr-xr-x  6 root      root     4.0K Mar 28 06:03 tests
-rw-r--r--  1 root      root      926 Mar 28 06:03 uninstall.sh
-rwxr-xr-x  1 root      root     2.1K Mar 28 06:14 update.sh
drwxr-xr-x  5 root      root     4.0K Mar 28 06:03 util
drwxr--r-- 44 azuracast www-data 4.0K Mar 28 06:13 vendor
drwxr-xr-x  3 root      root     4.0K Mar 28 06:03 web
```

**Comment by Vaalyn** [comment] 2019-03-28 09:40
> The docker installs completely fail constantly reinstalling composer or the following error.
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

>The install script was run on an a several clean Ubuntu installs following the direction on your site.

After the script has finished installing Docker you are prompted by the installation to log-out or restart your system to complete the Docker installation. Failing to do this will stop you from continuing the installation.

Here is the exact output of the script:
```
You must log out or restart to apply necessary Docker permissions changes.
Restart, then continue installing using this script.
```

If there is anything unclear with the wording of the scripts output please let us know.

> ERROR: for web Cannot start service web: driver failed programming external connectivity on endpoint azuracast_web_1 (b1315ec9bd51283cd6d97bb764bb4d415da3aa1bf1d1b41cc24c3f37b0480247): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
> ERROR: Encountered errors while bringing up the project.
> user1@user1-KVM:~$
> This was cleared up by
> sudo apt-get remove apache*
> Since the script does not check for available ports and change the port used as needed.

In order to be platform-independent the Docker installation script does not try to check for installed software that may conflict with anything from AzuraCast. As Docker containers have nearly nothing that could directly conflict with anything on the host system the amount of errors that can be encountered here is pretty small and in most cases is a trivial `address already in use` error. In our [support documentation](https://github.com/AzuraCast/AzuraCast/blob/master/SUPPORT.md#use-non-standard-ports) we have a section where we point out how to change the default ports of AzuraCast. This part should ideally be mentioned in our installation guide too but this will most likely stay a manual task that the administrator has to perform.

Also I'd like to point out that checking if the default port is already in use and automatically adjust that is not something that many software packages that are installed with Docker do. For most software that I know you'll have to manually edit the `docker-compose.yml` to change the port/s used by the container/s.

> I was asked to look at this project by a group that failed after many attempts to get it installed. I have been unable to independently certify that it is in fact well maintained or routinely install-able by a typical admin.

We have thousands of users, many who have basically no advanced *nix system administration knowledge, have successfully installed AzuraCast and were able to report issues they had with the installation or the software itself without blaming the project of being unusable and bad maintained, and were also able to provide us with the information necessary to help resolve their problems.

This is in my opinion clearly proof that even non-typical admins are able to install AzuraCast with the documentation that we provide.

When reporting issues to us I'd like to remind you to fill out the issue template that we provide for creating new issues here on GitHub. This will help with diagnosing a problem without having to spend unnecessary time trying to get the needed information by repeatedly asking for that.

**Comment by Vaalyn** [comment] 2019-05-23 15:50
Closing this issue as we can neither reproduce the issue or get any other reports about this.

**Closed by Vaalyn** 2019-05-23 15:50 UTC
Labels: error
