### ISSUE TITLE
Nowsync Error

### ISSUE THREAD

**Issue by fidegr** [AzuraCast/AzuraCast#4096] opened 2021-04-30 06:55 UTC
AzuraCast • v0.12.4 Stable • Docker • PHP 8.0

Hello, we have detected that the media sync has not worked for a couple of days. We paste the log with the error. What could be the problem?

Loading...[2021-04-30T06:55:41.133328+00:00] AzuraCast.NOTICE: Running sync task: 5-Minute Sync {"force":true} []
[2021-04-30T06:55:41.134937+00:00] AzuraCast.DEBUG: Successfully acquired the "{resource}" lock. {"resource":{"Symfony\\Component\\Lock\\Key":"lock_sync_medium"}} []
[2021-04-30T06:55:41.135484+00:00] AzuraCast.DEBUG: Expiration defined for "{resource}" lock for "{ttl}" seconds. {"resource":{"Symfony\\Component\\Lock\\Key":"lock_sync_medium"},"ttl":600.0} []
[2021-04-30T06:55:41.141582+00:00] AzuraCast.DEBUG: Expiration defined for "{resource}" lock for "{ttl}" seconds. {"resource":{"Symfony\\Component\\Lock\\Key":"lock_sync_medium"},"ttl":600.0} []
[2021-04-30T06:55:41.141800+00:00] AzuraCast.DEBUG: Starting sub-task: CheckMediaTask [] []
[2021-04-30T06:55:41.144890+00:00] AzuraCast.INFO: Processing media for storage location Local: /var/azuracast/stations/Agora_sol_radio/media... [] []
[2021-04-30T06:55:41.350059+00:00] AzuraCast.ERROR: App\Entity\StationMedia::needsReprocessing(): Argument #2 ($dbModifiedTime) must be of type int, null given, called in /var/azuracast/www/src/Sync/Task/CheckMediaTask.php on line 195 {"file":"/var/azuracast/www/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php","line":80,"code":0} []

root@radiobot:/var/azuracast# ./docker.sh cli sync:run --force medium
Starting azuracast_redis    ... done
Starting azuracast_stations ... done
Starting azuracast_mariadb  ... done
Starting up AzuraCast services...
Services started up and ready!
[2021-04-30T07:22:43.060743+00:00] AzuraCast.NOTICE: Running sync task: 5-Minute Sync {"force":true} []
[2021-04-30T07:23:34.771396+00:00] AzuraCast.ERROR: Doctrine\DBAL\Exception\LockWaitTimeoutException: An exception occurred while executing 'UPDATE storage_location SET storage_used = ? WHERE id = ?' with params ["14630355177", 13]:  SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction (uncaught exception) at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 54 while running console command `sync:run` {"exception":"[object] (Doctrine\\DBAL\\Exception\\LockWaitTimeoutException(code: 0): An exception occurred while executing 'UPDATE storage_location SET storage_used = ? WHERE id = ?' with params [\"14630355177\", 13]:\n\nSQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:54)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: HY000): SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: HY000): SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:112)"} []
[2021-04-30T07:23:34.772006+00:00] AzuraCast.WARNING: Console command `sync:run` exited with error code 1. [] []

In AbstractMySQLDriver.php line 54:

  An exception occurred while executing 'UPDATE storage_location SET storage_used = ? WHERE id = ?' with params ["14630355177", 13]:

  SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction

In Exception.php line 18:

  SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction

In PDOStatement.php line 112:

  SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction

sync:run [--force] [--] [<task>]

**Comment by SC2Mitch** [comment] 2021-04-30 08:05
Duplicate of #4095 thanks for the report.

**Closed by SC2Mitch** 2021-04-30 08:05 UTC
Labels: issue template not used, stable, unexpected behaviour
