### ISSUE TITLE
Ubuntu 20.04 - Install Fails At Very End

### ISSUE THREAD

**Issue by IKHNetworks** [AzuraCast/AzuraCast#3772] opened 2021-02-04 21:40 UTC
**Using Docker installation method**

No
**AzuraCast version**

**Host Operating System**

Ubuntu 20.04 - Proxmox LXC Container
**Describe the bug**

TASK [azuracast-setup : Migrate Legacy Configuration (Update Mode)] *****************************************
changed: [localhost]

TASK [azuracast-setup : Run AzuraCast Setup (Update Mode)] **************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/bin/console azuracast:setup --update", "delta": "0:00:00.273425", "end": "2021-02-04 21:30:27.374674", "msg": "non-zero return code", "rc": 1, "start": "2021-02-04 21:30:27.101249", "stderr": "[2021-02-04T21:30:27.365612+00:00] AzuraCast.ERROR: Doctrine\\DBAL\\Exception\\ConnectionException: An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known (uncaught exception) at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 while running console command `azuracast:setup` {\"exception\":\"[object] (Doctrine\\\\DBAL\\\\Exception\\\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\\n[previous exception] [object] (Doctrine\\\\DBAL\\\\Driver\\\\PDO\\\\Exception(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)\\n[previous exception] [object] (PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)\"} []\n[2021-02-04T21:30:27.366444+00:00] AzuraCast.WARNING: Console command `azuracast:setup` exited with error code 1. [] []\n\nIn AbstractMySQLDriver.php line 112:\n                                                                               \n  An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddr  \n  esses: getaddrinfo failed: Name or service not known                         \n                                                                               \n\nIn Exception.php line 18:\n                                                                               \n  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name o  \n  r service not known                                                          \n                                                                               \n\nIn PDOConnection.php line 38:\n                                                                               \n  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name o  \n  r service not known                                                          \n                                                                               \n\nIn PDOConnection.php line 38:\n                                                                               \n  PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or s  \n  ervice not known                                                             \n                                                                               \n\nazuracast:setup [--update] [--load-fixtures] [--release]", "stderr_lines": ["[2021-02-04T21:30:27.365612+00:00] AzuraCast.ERROR: Doctrine\\DBAL\\Exception\\ConnectionException: An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known (uncaught exception) at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 while running console command `azuracast:setup` {\"exception\":\"[object] (Doctrine\\\\DBAL\\\\Exception\\\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\\n[previous exception] [object] (Doctrine\\\\DBAL\\\\Driver\\\\PDO\\\\Exception(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)\\n[previous exception] [object] (PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)\"} []", "[2021-02-04T21:30:27.366444+00:00] AzuraCast.WARNING: Console command `azuracast:setup` exited with error code 1. [] []", "", "In AbstractMySQLDriver.php line 112:", "                                                                               ", "  An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddr  ", "  esses: getaddrinfo failed: Name or service not known                         ", "                                                                               ", "", "In Exception.php line 18:", "                                                                               ", "  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name o  ", "  r service not known                                                          ", "                                                                               ", "", "In PDOConnection.php line 38:", "                                                                               ", "  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name o  ", "  r service not known                                                          ", "                                                                               ", "", "In PDOConnection.php line 38:", "                                                                               ", "  PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or s  ", "  ervice not known                                                             ", "                                                                               ", "", "azuracast:setup [--update] [--load-fixtures] [--release]"], "stdout": "\nAzuraCast Setup\n===============\n\nWelcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...\n * Environment: Production\n * Installation Method: Ansible\n\n ! [NOTE] Running in update mode.                                               \n\n\nRunning Database Migrations\n---------------------------", "stdout_lines": ["", "AzuraCast Setup", "===============", "", "Welcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...", " * Environment: Production", " * Installation Method: Ansible", "", " ! [NOTE] Running in update mode.                                               ", "", "", "Running Database Migrations", "---------------------------"]}

RUNNING HANDLER [azuracast-cron : restart cron] *************************************************************

PLAY RECAP **************************************************************************************************
localhost                  : ok=78   changed=39   unreachable=0    failed=1    skipped=16   rescued=0    ignored=1   

root@test:/var/azuracast/www# 

**To Reproduce**

**Expected behavior**

Expected to be able to see a welcome page - everything goes fine until the very end - when it tries to introduce the welcome to azuracast message. 
**Relevant Logs**

TASK [azuracast-setup : Migrate Legacy Configuration (Update Mode)] *****************************************
changed: [localhost]

TASK [azuracast-setup : Run AzuraCast Setup (Update Mode)] **************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/bin/console azuracast:setup --update", "delta": "0:00:00.273425", "end": "2021-02-04 21:30:27.374674", "msg": "non-zero return code", "rc": 1, "start": "2021-02-04 21:30:27.101249", "stderr": "[2021-02-04T21:30:27.365612+00:00] AzuraCast.ERROR: Doctrine\\DBAL\\Exception\\ConnectionException: An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known (uncaught exception) at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 while running console command `azuracast:setup` {\"exception\":\"[object] (Doctrine\\\\DBAL\\\\Exception\\\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\\n[previous exception] [object] (Doctrine\\\\DBAL\\\\Driver\\\\PDO\\\\Exception(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)\\n[previous exception] [object] (PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)\"} []\n[2021-02-04T21:30:27.366444+00:00] AzuraCast.WARNING: Console command `azuracast:setup` exited with error code 1. [] []\n\nIn AbstractMySQLDriver.php line 112:\n                                                                               \n  An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddr  \n  esses: getaddrinfo failed: Name or service not known                         \n                                                                               \n\nIn Exception.php line 18:\n                                                                               \n  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name o  \n  r service not known                                                          \n                                                                               \n\nIn PDOConnection.php line 38:\n                                                                               \n  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name o  \n  r service not known                                                          \n                                                                               \n\nIn PDOConnection.php line 38:\n                                                                               \n  PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or s  \n  ervice not known                                                             \n                                                                               \n\nazuracast:setup [--update] [--load-fixtures] [--release]", "stderr_lines": ["[2021-02-04T21:30:27.365612+00:00] AzuraCast.ERROR: Doctrine\\DBAL\\Exception\\ConnectionException: An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known (uncaught exception) at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 while running console command `azuracast:setup` {\"exception\":\"[object] (Doctrine\\\\DBAL\\\\Exception\\\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\\n[previous exception] [object] (Doctrine\\\\DBAL\\\\Driver\\\\PDO\\\\Exception(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)\\n[previous exception] [object] (PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)\"} []", "[2021-02-04T21:30:27.366444+00:00] AzuraCast.WARNING: Console command `azuracast:setup` exited with error code 1. [] []", "", "In AbstractMySQLDriver.php line 112:", "                                                                               ", "  An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddr  ", "  esses: getaddrinfo failed: Name or service not known                         ", "                                                                               ", "", "In Exception.php line 18:", "                                                                               ", "  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name o  ", "  r service not known                                                          ", "                                                                               ", "", "In PDOConnection.php line 38:", "                                                                               ", "  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name o  ", "  r service not known                                                          ", "                                                                               ", "", "In PDOConnection.php line 38:", "                                                                               ", "  PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or s  ", "  ervice not known                                                             ", "                                                                               ", "", "azuracast:setup [--update] [--load-fixtures] [--release]"], "stdout": "\nAzuraCast Setup\n===============\n\nWelcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...\n * Environment: Production\n * Installation Method: Ansible\n\n ! [NOTE] Running in update mode.                                               \n\n\nRunning Database Migrations\n---------------------------", "stdout_lines": ["", "AzuraCast Setup", "===============", "", "Welcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...", " * Environment: Production", " * Installation Method: Ansible", "", " ! [NOTE] Running in update mode.                                               ", "", "", "Running Database Migrations", "---------------------------"]}

RUNNING HANDLER [azuracast-cron : restart cron] *************************************************************

PLAY RECAP **************************************************************************************************
localhost                  : ok=78   changed=39   unreachable=0    failed=1    skipped=16   rescued=0    ignored=1   

root@test:/var/azuracast/www# 
**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 
**Additional context**

Ubuntu 20.04 LXC Image - Ansible Install - OpenVZ is used by Proxmox so that's the console it uses for accessing ubuntu 20.04 
Same thing on the raspberry pi 4

**Comment by SlvrEagle23** [comment] 2021-02-04 22:19
Closing as duplicate of #3754.

**Closed by SlvrEagle23** 2021-02-04 22:19 UTC
Labels: error
