### ISSUE TITLE
Unattended install fails on ubuntu 20, manual install give an IP error

### ISSUE THREAD

**Issue by kris20061982** [AzuraCast/AzuraCast#3856] opened 2021-03-02 19:55 UTC
On a clean ubuntu 20 instance form servercheap.net, using the unattended install command returns the below:

```
root@kris:~# mkdir -p /var/azuracast
root@kris:~# cd /var/azuracast
root@kris:/var/azuracast# curl -fsSL https://raw.githubusercontent.com/AzuraCast/AzuraCast/master/docker.sh > docker.sh
root@kris:/var/azuracast# chmod a+x docker.sh
root@kris:/var/azuracast# yes 'Y' | ./docker.sh setup-release
Writing default .env file...
Prefer stable release versions of AzuraCast? [y/N] root@kris:/var/azuracast# yes '' | ./docker.sh install
Docker does not appear to be installed. Install Docker now? [Y/n] # Executing docker install script, commit: 3d8fe77c2c46c5b7571f94b42793905e5b3e42e4
+ sh -c apt-get update -qq >/dev/null
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
+ sh -c curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | apt-key add -qq - >/dev/null
Warning: apt-key output should not be parsed (stdout is not a terminal)
+ sh -c echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable" > /etc/apt/sources.list.d/docker.list
+ sh -c apt-get update -qq >/dev/null
+ [ -n  ]
+ sh -c apt-get install -y -qq --no-install-recommends docker-ce >/dev/null
+ sh -c docker version
Client: Docker Engine - Community
 Version:           20.10.4
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        d3cb89e
 Built:             Thu Feb 25 07:05:27 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.4
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Thu Feb 25 07:03:23 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:

  sudo usermod -aG docker your-user

Remember that you will have to log out and back in for this to take effect!

WARNING: Adding a user to the "docker" group will grant the ability to run
         containers which can be used to obtain root privileges on the
         docker host.
         Refer to https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
         for more information.
Docker Compose does not appear to be installed. Install Docker Compose now? [Y/n] Creating default AzuraCast settings file...
Retrieving default docker-compose.yml file...
Customize AzuraCast ports? [y/N] Set up LetsEncrypt? [y/N] WARNING: The LETSENCRYPT_EMAIL variable is not set. Defaulting to a blank string.
WARNING: The LETSENCRYPT_HOST variable is not set. Defaulting to a blank string.
Pulling mariadb                 ... done
Pulling redis                   ... done
Pulling stations                ... done
Pulling web                     ... done
Pulling nginx_proxy             ... done
Pulling nginx_proxy_letsencrypt ... done
WARNING: The LETSENCRYPT_EMAIL variable is not set. Defaulting to a blank string.
WARNING: The LETSENCRYPT_HOST variable is not set. Defaulting to a blank string.
Creating network "azuracast_backend" with driver "bridge"
Creating network "azuracast_frontend" with driver "bridge"
Creating volume "azuracast_nginx_proxy_vhosts" with default driver
Creating volume "azuracast_db_data" with default driver
Creating volume "azuracast_letsencrypt" with default driver
Creating volume "azuracast_letsencrypt_html" with default driver
Creating volume "azuracast_letsencrypt_acme" with default driver
Creating volume "azuracast_shoutcast2_install" with default driver
Creating volume "azuracast_geolite_install" with default driver
Creating volume "azuracast_sftpgo_data" with default driver
Creating volume "azuracast_station_data" with default driver
Creating volume "azuracast_www_vendor" with default driver
Creating volume "azuracast_tmp_data" with default driver
Creating volume "azuracast_redis_data" with default driver
Creating volume "azuracast_backups" with default driver
Creating azuracast_redis    ... done
Creating azuracast_stations ... done
Creating azuracast_mariadb  ... done
```

It stays at `Creating azuracast_mariadb  ... done` forever.

Using manual install returns the following:

```
root@kris:~# mkdir -p /var/azuracast
root@kris:~# cd /var/azuracast
root@kris:/var/azuracast# curl -fsSL https://raw.githubusercontent.com/AzuraCast/AzuraCast/master/docker.sh > docker.sh
root@kris:/var/azuracast# chmod a+x docker.sh
root@kris:/var/azuracast# ./docker.sh install
Docker does not appear to be installed. Install Docker now? [Y/n] y
# Executing docker install script, commit: 3d8fe77c2c46c5b7571f94b42793905e5b3e42e4
+ sh -c apt-get update -qq >/dev/null
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
+ sh -c curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | apt-key add -qq - >/dev/null
Warning: apt-key output should not be parsed (stdout is not a terminal)
+ sh -c echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable" > /etc/apt/sources.list.d/docker.list
+ sh -c apt-get update -qq >/dev/null
+ [ -n  ]
+ sh -c apt-get install -y -qq --no-install-recommends docker-ce >/dev/null
+ sh -c docker version
Client: Docker Engine - Community
 Version:           20.10.4
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        d3cb89e
 Built:             Thu Feb 25 07:05:27 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.4
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Thu Feb 25 07:03:23 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:

  sudo usermod -aG docker your-user

Remember that you will have to log out and back in for this to take effect!

WARNING: Adding a user to the "docker" group will grant the ability to run
         containers which can be used to obtain root privileges on the
         docker host.
         Refer to https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
         for more information.
Docker Compose does not appear to be installed. Install Docker Compose now? [Y/n] y
Writing default .env file...
Prefer stable release versions of AzuraCast? [y/N] y
Creating default AzuraCast settings file...
Retrieving default docker-compose.yml file...
Customize AzuraCast ports? [y/N] n
Set up LetsEncrypt? [y/N] n
WARNING: The LETSENCRYPT_EMAIL variable is not set. Defaulting to a blank string.
WARNING: The LETSENCRYPT_HOST variable is not set. Defaulting to a blank string.
Pulling mariadb                 ... done
Pulling redis                   ... done
Pulling stations                ... done
Pulling web                     ... done
Pulling nginx_proxy             ... done
Pulling nginx_proxy_letsencrypt ... done
WARNING: The LETSENCRYPT_EMAIL variable is not set. Defaulting to a blank string.
WARNING: The LETSENCRYPT_HOST variable is not set. Defaulting to a blank string.
Creating network "azuracast_backend" with driver "bridge"
Creating network "azuracast_frontend" with driver "bridge"
Creating volume "azuracast_nginx_proxy_vhosts" with default driver
Creating volume "azuracast_db_data" with default driver
Creating volume "azuracast_letsencrypt" with default driver
Creating volume "azuracast_letsencrypt_html" with default driver
Creating volume "azuracast_letsencrypt_acme" with default driver
Creating volume "azuracast_shoutcast2_install" with default driver
Creating volume "azuracast_geolite_install" with default driver
Creating volume "azuracast_sftpgo_data" with default driver
Creating volume "azuracast_station_data" with default driver
Creating volume "azuracast_www_vendor" with default driver
Creating volume "azuracast_tmp_data" with default driver
Creating volume "azuracast_redis_data" with default driver
Creating volume "azuracast_backups" with default driver
Creating azuracast_stations ... done
Creating azuracast_mariadb  ... done
Creating azuracast_redis    ... done
Starting up AzuraCast services...
🖥️－🎵－🎶📻 Waiting...Services started up and ready!
AzuraCast Setup
(Environment: production)

AzuraCast Setup
===============

Welcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...
 * Environment: Production
 * Installation Method: Docker


Running Database Migrations
---------------------------



Generating Database Proxy Classes
---------------------------------


 Processing entity "App\Entity\SettingsTable"
 Processing entity "App\Entity\StorageLocation"
 Processing entity "App\Entity\StationMedia"
 Processing entity "App\Entity\CustomField"
 Processing entity "App\Entity\StationQueue"
 Processing entity "App\Entity\Station"
 Processing entity "App\Entity\StationPlaylist"
 Processing entity "App\Entity\StationRequest"
 Processing entity "App\Entity\StationPlaylistMedia"
 Processing entity "App\Entity\UnprocessableMedia"
 Processing entity "App\Entity\StationMediaCustomField"
 Processing entity "App\Entity\SongHistory"
 Processing entity "App\Entity\StationStreamer"
 Processing entity "App\Entity\RolePermission"
 Processing entity "App\Entity\StationMount"
 Processing entity "App\Entity\StationRemote"
 Processing entity "App\Entity\StationWebhook"
 Processing entity "App\Entity\SftpUser"
 Processing entity "App\Entity\StationPlaylistFolder"
 Processing entity "App\Entity\Listener"
 Processing entity "App\Entity\ApiKey"
 Processing entity "App\Entity\AuditLog"
 Processing entity "App\Entity\StationStreamerBroadcast"
 Processing entity "App\Entity\Relay"
 Processing entity "App\Entity\MessengerMessage"
 Processing entity "App\Entity\Role"
 Processing entity "App\Entity\StationSchedule"
 Processing entity "App\Entity\Analytics"
 Processing entity "App\Entity\User"

 Proxy classes generated to "/var/azuracast/www_tmp/proxies"

Reload System Data
------------------



 [OK] Local cache flushed.




 [OK] All message queues cleared.



Refreshing All Stations
-----------------------


Restarting all radio stations...
--------------------------------

    0 [▓░░░░░░░░░░░░░░░░░░░░░░░░░░░]


[2021-03-02T19:51:15.846153+00:00] AzuraCast.ERROR: Could not fetch remote IP: Syntax error [] []

 [OK] AzuraCast installation complete!

      Visit http:// to complete setup.


WARNING: The LETSENCRYPT_EMAIL variable is not set. Defaulting to a blank string.
WARNING: The LETSENCRYPT_HOST variable is not set. Defaulting to a blank string.
azuracast_redis is up-to-date
azuracast_mariadb is up-to-date
azuracast_stations is up-to-date
Creating azuracast_web ... done
Creating nginx_proxy   ... done
Creating nginx_proxy_letsencrypt ... done
root@kris:/var/azuracast#
```

**Comment by SlvrEagle23** [comment] 2021-03-04 04:28
@kris20061982 This error shouldn't actually prevent your installation from functioning (as fetching your remote IP address is just a convenience tool we use to try to automatically determine a base URL for your installation), but the cause of the error was likely due to downtime in our update notification service (which also handles the external-IP ping process), which has since been resolved.

**Comment by Vaalyn** [comment] 2021-04-23 17:30
Closing this issue since this was most likely caused by a downtime of our update notification service as mentioned and there have been no further reports or replies here.

**Closed by Vaalyn** 2021-04-23 17:30 UTC
Labels: error
