### ISSUE TITLE
Where could i see my login and password to connect mixxx using icecast?

### ISSUE THREAD

**Issue by 7miguelsilva7** [AzuraCast/AzuraCast#1276] opened 2019-03-09 12:42 UTC
Where could i see my login and password to connect mixxx using icecast?

I try to connect using login and password of a streamer/DJ (Is it a correct way?) but mixxx say login and password are wrong.

**Comment by LordHelmchen666** [comment] 2019-03-09 15:40
Should working. Are you are sure your settings correct? User, password, host, mount, port?
https://github.com/AzuraCast/azuracast.com/blob/master/StreamingSoftware.md

**Comment by 7miguelsilva7** [comment] 2019-03-09 16:33
Yes I am! I did as show here: https://github.com/AzuraCast/azuracast.com/blob/master/StreamingSoftware.md

I set login and password very easy both to test, but doesn't work. when I try to conect I see this error message:

"Socket is busy
Por favor verifique a sua conexão com a internet e verifique se o seu usuário e senha estão corretos."

**Comment by SlvrEagle23** [comment] 2019-03-09 21:32
@7miguelsilva7 You're specifically using the settings from the Streamers/DJs page, not the source password for the Icecast/SHOUTcast station itself, right?

Can I see a screenshot of your configuration? It seems like something else may be trying to connect to that same port at the same time.

**Comment by 7miguelsilva7** [comment] 2019-03-10 00:59
Right!
Here some screenshot:
![Captura de tela de 2019-03-09 21-43-13](https://user-images.githubusercontent.com/16270181/54079181-930b8e80-42b6-11e9-968a-d2e5ad72a955.png)
![Captura de tela de 2019-03-09 21-50-24](https://user-images.githubusercontent.com/16270181/54079182-9a329c80-42b6-11e9-813a-914c0bece8c9.png)
![Captura de tela de 2019-03-09 21-50-58](https://user-images.githubusercontent.com/16270181/54079183-9e5eba00-42b6-11e9-98be-23c47ce1946d.png)

**Comment by 7miguelsilva7** [comment] 2019-03-14 19:23
when i try to connect using BUTT I see this error:
![butt](https://user-images.githubusercontent.com/16270181/54385465-720bba80-4675-11e9-8471-23e06a1becdd.png)

**Comment by LordHelmchen666** [comment] 2019-03-14 21:12
Port 8000? Shouldn't it be 8005?

**Comment by 7miguelsilva7** [comment] 2019-03-15 11:25
> Port 8000? Shouldn't it be 8005?
And mountpoint / ?

Yes, I've tried everithng.

Now it is working!
I didn't know you shoul have to stop autoDJ on panel ZuraCast before start connect to live streaming, I thought it was automatically, but not. I didn't know username was "source".

it Working with settings:

host: ServerIP
Port: 8000
User: source
Password: source password
Mount point: /radio.mp3

**Comment by Vaalyn** [comment] 2019-03-15 11:56
@7miguelsilva7 You do **not** have to stop the liquidsoap autodj for streamer to be able to connect to the stream. When using the DJ accounts feature you are connecting to the stream through liquidsoap so `PC` -> `liquidsoap` -> `IceCast`. What you are now doing is connecting to the IceCast server directly as source which is not the best thing you could do and for normal web radios I'd advise to not do that.

When you try to connect to AzuraCast with a DJ account and the following settings you'll need to choose `ShoutCast` as the protocol since that is the protocol that liquidsoap operates on here:

`Host`: Server IP / Domain
`Port`: 8005
`Password`: <dj username>:<dj password>

**Comment by 7miguelsilva7** [comment] 2019-03-15 13:00
> @7miguelsilva7 You do **not** have to stop the liquidsoap autodj for streamer to be able to connect to the stream. When using the DJ accounts feature you are connecting to the stream through liquidsoap so `PC` -> `liquidsoap` -> `IceCast`. What you are now doing is connecting to the IceCast server directly as source which is not the best thing you could do and for normal web radios I'd advise to not do that.
> 
> When you try to connect to AzuraCast with a DJ account and the following settings you'll need to choose `ShoutCast` as the protocol since that is the protocol that liquidsoap operates on here:
> 
> `Host`: Server IP / Domain
> `Port`: 8005
> `Password`: {dj username}:{dj password}

Didn't work.
When I use like this
> `Host`: Server IP / Domain
> `Port`: 8005
> `Password`: {dj username}:{dj password}

I see this error:
"Socket is busy"

On field User what must you write?

**Comment by Vaalyn** [comment] 2019-03-15 13:05
When you create a DJ account you enter a `Streamer Username` this is the user that you need to enter. Again please make sure that you select the correct streaming protocol (`ShoutCast`) in Mixxx or Butt and to enter the `username:password` in the `password` field.

**Comment by 7miguelsilva7** [comment] 2019-03-15 13:18
Didn't work:

Even using Shoutcast, ipDomain, user, user:user, 8005,  /

![Captura de tela de 2019-03-15 10:13:33](https://user-images.githubusercontent.com/16270181/54433753-5eab2e80-470b-11e9-81b8-b03723c4c796.png)

**Comment by Vaalyn** [comment] 2019-03-15 13:23
This is how I've setup my Mixxx config for my test server: http://prntscr.com/myai5p
And this is what my AzuraCast page says about the connection details: http://prntscr.com/myaiyk

Please try to match that with the equivalent values for your installation.

**Comment by LordHelmchen666** [comment] 2019-03-15 13:44
Try it like Vaalyn wrote or try this
type: Icecast 2
Mount: /
host: 34.73.100.255
Port: 8006
login: djname
pasword: djpassword

This working for me with mixxx, idjc and Sam Broadcaster

**Comment by 7miguelsilva7** [comment] 2019-03-15 14:18
@LordHelmchen666 
How open ports?

**Comment by 7miguelsilva7** [comment] 2019-03-15 14:19
Didn't work
> type: Icecast 2
> Mount: /
> host: 34.73.100.255
> Port: 8005
> login: myUSerDJ
> pasword: myPassowrdDJ

**Comment by Vaalyn** [comment] 2019-03-15 14:23
@7miguelsilva7  If you want I can try connecting to your AzuraCast from my machine and see if this is an issue with the server / installation or your client. If you'd like me to do that please create a DJ Account for me and send me the user and password to vaalyndev@gmail.com

**Comment by 7miguelsilva7** [comment] 2019-03-15 14:24
> This is how I've setup my Mixxx config for my test server: http://prntscr.com/myai5p
> And this is what my AzuraCast page says about the connection details: http://prntscr.com/myaiyk
> Please try to match that with the equivalent values for your installation.

@Vaalyn 
Didn't work

Just work when I use like this:

> host: ServerIP
> Port: 8000
> User: source
> Password: source password
> Mount point: /radio.mp3

**Comment by 7miguelsilva7** [comment] 2019-03-15 14:29
@Vaalyn I sent a email.

**Comment by Vaalyn** [comment] 2019-03-15 14:50
Thank you, I've tested with Mixxx and Butt and I think that what @LordHelmchen666 said about your ports is correct. Please make sure to open the ports from 8005 to 8010 by using `ufw allow 8005:8010/tcp`.

**Comment by 7miguelsilva7** [comment] 2019-03-15 16:18
@Vaalyn, Thank you for test it!
I'll ask to server to open these ports.

Thanks!

**Comment by 7miguelsilva7** [comment] 2019-03-16 20:48
Now is working!
After open the port 8005 everything is working like a charm!
Thanks for everyone!

**Comment by Vaalyn** [comment] 2019-03-16 22:05
@7miguelsilva7 That's good to hear. I'll close this issue now that the problem is resolved. 👍

**Closed by Vaalyn** 2019-03-16 22:05 UTC
Labels: error
