### ISSUE TITLE
Error when using Azuracast on the Microsoft Azure platform

### ISSUE THREAD

**Issue by alencarwell** [AzuraCast/AzuraCast#2731] opened 2020-04-24 13:28 UTC
Friends all right?

I installed Azuracast on Linux Centos 7 on the Microsoft Azure platform.

However, the Azure network structure itself, virtual machines do not receive public fixed IP, but internal dynamic IP.

Therefore, any access to specific ports, it is necessary to create a NAT inside the Azure panel and point the port to the internal IP of the virtual machine where Azuracast is installed.

So far I managed to make it work, the connection with streaming works normally, I use Shoutcast technology.

However, an error happens that I couldn't solve.

The Linux Centos 7 firewall itself is disabled.

But in the Azuracast panel it does not appear how many users are online and does not show the name of the song and artist and in the part where it shows that the Shoutcast is online, it appears offline.

I am attaching the two screens of the Azuracast panel for you to see.

Do you know if I still have to open another door besides 80, 443, 2022?

<img width="1419" alt="Captura de Tela 2020-04-24 às 10 24 23" src="https://user-images.githubusercontent.com/64265553/80217592-59125e80-8616-11ea-9acd-bc4ac5d64a36.png">
<img width="1433" alt="Captura de Tela 2020-04-24 às 10 24 44" src="https://user-images.githubusercontent.com/64265553/80217604-5ca5e580-8616-11ea-8f28-6273b531cf7c.png">

**Comment by alencarwell** [comment] 2020-04-25 13:48
I installed Ubuntu Server, and also the same problem.

It does not work correctly on the Microsoft Azure platform.

Certainly, it is something connected to the Firewall.

Since the virtual machine does not have a fixed IP, but an internal IP.

**Comment by alencarwell** [comment] 2020-04-25 17:57
AMAZON AWS SAME PROBLEM.....

**Comment by CodeSteele** [comment] 2020-04-27 06:14
@alencarwell it's _very likely_ caused by SELinux, so you have a few options:

1) Use a Debian-based system, Debian, Ubuntu, etc. won't ship with SELinux enabled
2) Disable SELinux, personally I prefer to keep it on, but...
3) Properly configure SELinux, this is a huge pain, requires lots of looking at logs, we don't support SELinux configurations so we don't have instructions available for you, so you're kind of on your own with that one -- if you're running SELinux we assume that you're proficient in that system and able to troubleshoot it yourself.

Let me know if there are any other questions or you have issues with SELinux Disabled/Debian based systems and I'll reopen.

**Comment by alencarwell** [comment] 2020-04-27 13:10
Hello budy, how are you.

But this information I did not understand.

Because on Ubuntu Server SElinux is not installed by default.

Read this:

So how do we disable SELinux on Ubuntu?

There is no need. SELinux is not installed by default in Ubuntu. Security Enhanced Linux is primarily used by the Red Hat based Linux distributions, that includes Red Hat Enterprise Linux, CentOS and Fedora.

Debian based distributions, including Ubuntu do not deliver SELinux by default, instead they use a system called AppArmor for Mandatory Access Control (AppArmor is disabled by default on Ubuntu).

https://www.configserverfirewall.com/ubuntu-linux/disable-selinux-ubuntu/

**Comment by CodeSteele** [comment] 2020-04-27 17:04
Ah yeah, just noticed this:

> I installed Azuracast on Linux Centos 7 on the Microsoft Azure platform.

But noticed you mentioning Ubuntu on the other VM you deployed.

As far as AWS goes, it's likely your security group configuration or something else on AWS, in reality you only need port 80 and 443 open if you've enabled "Use Web Proxy for Radio" under the administration section (you'll have to open other ports for DJing though)

**Comment by CodeSteele** [comment] 2020-06-04 17:34
What _exactly_ do you mean by "nothing appears from the radio data"? As in the user count is always "0" on your reports?

**Comment by alencarwell** [comment] 2020-06-04 18:23
Yes, the name of the radio does not appear and the number of listeners connected does not appear and where it shows if the Shoutcast is ONLINE, shows only OFFLINE and if you choose to START the radio, a message comes saying that the radio is already online, but it appears OFFLINE .

See the images there ...

**Comment by alencarwell** [comment] 2020-06-04 18:36
The firewall is not, because I disabled it.
SELINUX is also not.
I don't know what else to do to resolve this.

Look at another server, see what the standard screen looks like and working.
Compare with the first screen that I attached here when I opened the ticket.

![Capturar](https://user-images.githubusercontent.com/64265553/83797520-288ffc80-a679-11ea-90c6-80d477a1a877.PNG)

**Comment by alencarwell** [comment] 2020-06-04 18:43
This old server that I posted the image on now, I need to stop it because the streaming on it is constantly changing for a few seconds, in fact it's less than a second, but it's constant, I need to stop it and migrate my radio to the new server, you know .

However, the new server has this problem, it does not show the name of the radio and the listeners connected and it keeps appearing as if the Shoutcast was stopped.

But if you play on the main Azuracast page, the audio works normally.

**Comment by CodeSteele** [comment] 2020-06-05 07:54
Can you open your browser's console window and let me know if there are any errors in it?

You said it works fine from the public page, just not from the admin page?

**Comment by alencarwell** [comment] 2020-06-05 12:05
No, the public page also doesn't play my audio anymore.

And on the administration page, my radio data no longer appears.

**Comment by CodeSteele** [comment] 2020-06-05 14:04
Can you check your AzuraCast logs: https://www.azuracast.com/help/logs/

Also include logs from your Browser's console window.

**Comment by CodeSteele** [comment] 2020-06-06 05:16
Deploying 20.04 to Azure to test currently.

**Comment by CodeSteele** [comment] 2020-06-06 05:33
Confirming 20.04 works fine, going to deploy Centos

**Comment by CodeSteele** [comment] 2020-06-06 06:11
Deployed TunnelBiz CentOS 7 minimal install, docker-compose doesn't install correctly
Deployed the CentOS 8.1 install from Azure and it doesn't install docker-compose in the expected location

Under both cases I'm getting this error:
```
Docker does not appear to be installed. Install Docker now? [Y/n]
# Executing docker install script, commit: 26ff363bcf3b3f5a00498ac43694bf1c7d9ce16c
+ sh -c 'yum install -y -q yum-utils'
+ sh -c 'yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo'
Adding repo from: https://download.docker.com/linux/centos/docker-ce.repo
+ '[' stable '!=' stable ']'
+ sh -c 'yum makecache'
CentOS-8 - AppStream                                                                                                                                                                   251 kB/s | 3.5 kB     00:00
CentOS-8 - Base                                                                                                                                                                        182 kB/s | 3.1 kB     00:00
CentOS-8 - Extras                                                                                                                                                                      5.0 kB/s | 1.5 kB     00:00
Docker CE Stable - x86_64                                                                                                                                                              163 kB/s | 3.5 kB     00:00
Metadata cache created.
+ '[' -n '' ']'
+ sh -c 'yum install -y -q docker-ce'
Error:
 Problem: package docker-ce-3:19.03.11-3.el7.x86_64 requires containerd.io >= 1.2.2-3, but none of the providers can be installed
  - cannot install the best candidate for the job
  - package containerd.io-1.2.10-3.2.el7.x86_64 is excluded
  - package containerd.io-1.2.13-3.1.el7.x86_64 is excluded
  - package containerd.io-1.2.13-3.2.el7.x86_64 is excluded
  - package containerd.io-1.2.2-3.3.el7.x86_64 is excluded
  - package containerd.io-1.2.2-3.el7.x86_64 is excluded
  - package containerd.io-1.2.4-3.1.el7.x86_64 is excluded
  - package containerd.io-1.2.5-3.1.el7.x86_64 is excluded
  - package containerd.io-1.2.6-3.3.el7.x86_64 is excluded
```

So the docker install script isn't even working properly (something we don't provide support for), @alencarwell I need the exact image you're using on Azure so I can reproduce where you're at.

**Comment by alencarwell** [comment] 2020-08-02 00:25
You can't understand this error.
I am 5 hours installing and installing Azuracast and none of them work correctly.

It seems to be something in Docker, but I can't seem to solve it.

I don't use Azure or AWS anymore, because the problem doesn't come from them, but from Docker.

Now I'm installing it on Centos 7 and it doesn't work at all.

So I tried Centos 8 and the process of installing Docker is much better, but the error continues.

That is, it does not show the data of the music and the artist, nor listeners connected to the radio.

Is anyone experiencing this problem?

I followed the Azuracast documentation exactly, and the error always happens ....

**Comment by alencarwell** [comment] 2020-08-02 13:11
I just installed the clean Centos 8.
And I followed this Docker tutorial:

https://www.linuxtechi.com/install-docker-ce-centos-8-rhel-8/

But even so, the same error occurs.
In other words, the station's data and online listeners do not appear.

I really don't know where to check the problem.

**Comment by alencarwell** [comment] 2020-08-02 16:45
{"code":408,"message":"Now Playing data has not loaded yet. Please try again later.","formatted_message":"Now Playing data has not loaded yet. Please try again later.","extra_data":[],"success":false}

**Comment by CodeSteele** [comment] 2020-08-02 20:54
There are some fun issues with CentOS8 right now:

- Docker will not install cleanly, needs to have `yum install -y https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm` run prior to running Docker's supplied "one command install" script.
- When the script ends, docker isn't enabled by default (What?!) and you must run `systemctl enable docker && systemctl start docker` and re-run the start script.


After those holdups the containers come up with the following loop, forever:

```
2020/08/02 20:53:01 Problem with dial: dial tcp 172.18.0.4:3306: connect: no route to host. Sleeping 1s
2020/08/02 20:53:01 Problem with dial: dial tcp 172.18.0.3:6379: connect: no route to host. Sleeping 1s
2020/08/02 20:53:01 Problem with dial: dial tcp 172.18.0.2:8086: connect: no route to host. Sleeping 1s
2020/08/02 20:53:03 Problem with dial: dial tcp 172.18.0.3:6379: connect: no route to host. Sleeping 1s
2020/08/02 20:53:05 Problem with dial: dial tcp 172.18.0.3:6379: connect: no route to host. Sleeping 1s
```

I'd honestly at this point say to not hold your breath for CentOS support unless a community member wants to contribute all these fixes (including upstream fixes for docker?)

**Comment by alencarwell** [comment] 2020-08-02 21:10
I did not understand your answer.

So Centos 8 is not supported by Azuracast?

After all, which one should I use?

I have already tested Centos 7, 8 and Ubuntu Server.

All the same error happens.

I am months and months with this problem and I do not find a solution.

**Comment by alencarwell** [comment] 2020-08-02 21:14
If only Ubuntu Server runs Azuracast, can you send me the installation step by step?

Because the documentation on the Azuaracast website is not enough.

If you follow the step by step of the Azuarcast website, it will give an error.

**Comment by CodeSteele** [comment] 2020-08-02 21:30
@alencarwell you'll have to provide the error you're running into, we have thousands of installs of AzuraCast using the provided documentation, it should work out of the box.


For reference, Redhat has been aiming to ditch Docker support for awhile: http://crunchtools.com/why-no-docker/ and is probably what we're running into.

**Comment by alencarwell** [comment] 2020-08-02 21:35
But the error is what I've been talking about for months.

The panel simply does not show anything related to connected listeners and does not show any data from the station.

Remembering that my radio does not use autodj, I use Radioboss and send my audio using the aac codec.

However, the panel shows that the Shoutcast is stopped, look at the first photo I posted here, the panel shows as if the radio was stopped.

I am now installing Ubuntu Server right now.

I will go with the official documentation to install Docker and then the Azuracast documentation.

But I did it yesterday, and it didn't work, it made the same mistake.

But I will try again.

**Comment by alencarwell** [comment] 2020-08-02 22:45
I now see a problem installing on Ubuntu Server.

The installation error step by step says that the docker.sh command is running without root privileges.

However, at the beginning of the command, I put SUDO.

Really, I'm giving it up, I used it for so long and now I have to give it up.

**Comment by alencarwell** [comment] 2020-08-02 23:31
LOOK ERROR ON UBUNTU SERVER:

ubuntu@audio:/var/azuracast$ sudo curl -fsSL https://raw.githubusercontent.com/AzuraCast/AzuraCast/master/docker.sh > docker.sh
-bash: docker.sh: Permission denied
ubuntu@audio:/var/azuracast$

**Comment by alencarwell** [comment] 2020-08-02 23:54
I can't understand this error, I have a server running Centos8 and Azuaracast 10.2 and it works normally.

The song data and connected listeners appear.

But if I upgrade to the new version of Azuaracast, there are two problems:

The LetsEncrypt certificate stops working and Azuaracast stops showing music data and listeners online, remembering that on this server I always use Shoutcast v2.

You really can't understand ...

**Comment by SlvrEagle23** [comment] 2020-08-03 00:58
@alencarwell Try setting the `/var/azuracast` directory to be owned by you first:

```
sudo chown -R ubuntu:ubuntu /var/azuracast
```

...then follow the regular Docker install instructions.

Many of these errors are very standard for Linux. We are happy to help as much as we can, but it helps to have some understanding of the Linux terminal when installing.

**Comment by CodeSteele** [comment] 2020-08-03 01:01
Yeah when you slap `sudo` on the front of `curl` you're elevating that single command to run as root, but the output redirection `> docker.sh` is not and does not have access to the directory. @SlvrEagle23 shows how to fix that.

AzuraCast documentation does say:

>  You should be an administrator user with either root access or the ability to use the sudo command.

Running as root would fix this problem (and is the easier solution), the "ability to use the sudo command" assumes some proficiency with it.

**Comment by alencarwell** [comment] 2020-08-03 11:38
Regardless of my technical knowledge or not, it is a fact that we have a bug in this version.

Jpa made more than 30 installations on Centos 8, more than 8 installations on Centos 7 and 5 installations on Ubuntu Server 20.

I know how to install Centovacast, Cpanel, Media Cpanel.

But Azuracast especially has little installation documentation and little support because it is a free product.

I've been talking about this problem for months, the panel installation takes place without any problems. But when creating the first radio, the problem happens, that is, there is nothing in the radio data and the Shoutcast appears as offline, but if you play the radio on the radio list page, the radio plays.

How to explain it?

I was once told that it could be SELINUX, but even disabling the problem continues.

Just look closely at the photos I posted here months ago and see the problem.

I believe that until now you have not yet understood the problem that I have been describing for months.

**Comment by CodeSteele** [comment] 2020-08-03 15:15
> It is a fact that we have a bug in this version.

This is you writing an incorrect command with `sudo`, this is not a bug with our software, our documentation has been updated to reflect how to simply elevate using sudo so you don't have the issue you ran into.

> But Azuracast especially has little installation documentation and little support because it is a free product.

I've already spent hours spinning up CentOS systems and my own money on Azure spinning up VMs there, any more snark and your tickets will be closed, this is honestly way more time than we'd like to spend with someone struggling when we have so many deploys (including many more I deployed as part of this ticket).

> I've been talking about this problem for months, the panel installation takes place without any problems. But when creating the first radio, the problem happens, that is, there is nothing in the radio data and the Shoutcast appears as offline, but if you play the radio on the radio list page, the radio plays.

You still have not provided logs for us, which we asked for back on June 5th: https://www.azuracast.com/help/logs/

**Comment by alencarwell** [comment] 2020-08-04 22:22
Hello, I came here now to be as objective as possible, as I believe you have not yet understood the BUG that exists in Azuracast, I consider it to be a BUG because I am following all documentation from both Azuracast and Docker. And I already posted these pictures of the problem as soon as I opened this ticker, but I will post again.

Now following the new recommendations you made there on the Azuracast website, I am using Ubuntu Server 20.04.1

SEE:


![Captura de tela de 2020-08-04 19-17-27](https://user-images.githubusercontent.com/64265553/89351162-ce66e400-d687-11ea-8d36-1137f4871e7b.png)

**Comment by alencarwell** [comment] 2020-08-04 22:25
Now comes the version of Azuracast that I installed and I followed the Docker documentation in this series:

https://docs.docker.com/engine/install/ubuntu/

And note that I am sending audio to this radio that I created, using the AAC codec together with the Radioboss Software in the latest version.

Note that the audio is playing, but the panel does not show the connected listener or the name of the song that is playing:

SEE:

![Captura de tela de 2020-08-04 19-04-17](https://user-images.githubusercontent.com/64265553/89351367-40d7c400-d688-11ea-8894-5eba12759518.png)

**Comment by alencarwell** [comment] 2020-08-04 22:28
Now look at the radio panel, the Shoutcast is running normally, but the panel says that the Shoutcast is stopped and the data of the music that is playing, does not appear on the panel, this is the error that I have been fighting since April, and I have tried everything and do not find any information on what may be causing this error.

I am using the following version of the Shoutcast:

Currently Installed Version
SHOUTcast version "SHOUTcast DNAS / posix (linux x64) v2.5.5.733 (Oct 9 2017) libcurl / 7.53.1 OpenSSL / 1.1.0e zlib / 1.2.11 expat / 2.2.0" is installed.

AND

Currently Installed Version
"GeoLite2-City (2020-08-04)" version of GeoLite is already installed.

![Captura de tela de 2020-08-04 19-05-27](https://user-images.githubusercontent.com/64265553/89351600-ba6fb200-d688-11ea-8ac4-29add4a8d42a.png)

**Comment by alencarwell** [comment] 2020-08-04 22:30
I think now I was clearer, I hope you understand the problem and help me with this terrible problem.

Thank you very much for all your help!

**Comment by Vaalyn** [comment] 2020-08-05 00:07
@alencarwell please post the content of the `liquidsoap.log`, `sc_serv.log` and `app.log` which can be found on the page `/admin/logs` on your AzuraCast web panel. (Don't forget to remove any information that should not be public, like IPs and so on).

Without knowing what the software is writing in the logs it's a guessing game when trying to debug/understand this problem. Yeah I can see that there is information missing on the page (like the song title) and that SC is reported as being offline (although you can hear the stream) but I can not see from a screenshot why that might be. Which is why the logs that were requested on the 5th of June (and again yesterday) are so crucial to even be able to help.

**Comment by alencarwell** [comment] 2020-08-05 00:25
@Vaalyn  and @CodeSteele and @SlvrEagle23 

I did not pass the logs because it seemed obvious, because it is a recurring problem, just install it there and you could see the error.

But I believe that if you can enter my server, I think it would be even better because then you would actually see what has been causing this.

You can handle this server without any problems, it is running a Datacenter in Miami USA and it is a virtual machine controlled by Hyper-V, so I have a backup of the complete image, after you identify the problem, just tell me what the problem is and I I will restore the backup and I will make the correction and inform you here about the solution.

SSH SERVER DATA:

IP: 192.240.115.61
USER: silviotavares
PASS: test @ 2108

Same username and password to enter Azuracast.

I'm sending the audio to this server, on port 8000, so they can test it better.

**Comment by alencarwell** [comment] 2020-08-05 01:15
Did anyone mess with the server?
It started to work at that very moment.
I didn't move anything ....

Please, if someone moved, tell me what they did, I am months with this problem ....

![Captura de tela de 2020-08-04 22-14-17](https://user-images.githubusercontent.com/64265553/89360836-fe21e600-d69f-11ea-88e6-3c65b237556b.png)

**Comment by Vaalyn** [comment] 2020-08-05 01:16
I've been so free to log in and look at the logs there myself. This is what I found:
```
AzuraCast.ERROR: Call to a member function recalculate() on null {"file":"/var/azuracast/www/src/Entity/Api/NowPlaying.php","line":71,"code":0} []
```

So I first looked if the ShoutCast admin panel is showing the title, which it did. Then I manually ran the `Now Playing Data` Sync Task on the admin page which showed me this:
```
Setup not complete; halting synchronized task.
```

I visited `/setup` entered the URL from my browser and submitted the form. After that Everything seems to work just fine.

So all in all this seems to me like it was caused by not completing the setup after the installation.

@SlvrEagle23 @CodeSteele could we prevent users from accessing the web panel completely until this setup is finished or are we already doing that?

**Comment by alencarwell** [comment] 2020-08-05 01:20
But that doesn't make a lot of sense, as I've run the installation more than 40 times since April.

And all installations, on Centos 7 and 8 and Ubuntu Server 20.04 gave the same error.

Therefore, it is clear that we have a serious installation error.

Could you tell me step by step what you did?

Because I will restore the backup of the server and the error will come back again.

And of course, I can only thank you for helping me with this problem that is causing me a lot of problems.

Thank you.

**Comment by Vaalyn** [comment] 2020-08-05 01:35
@alencarwell Please test it for yourself:

1. Go to the `/login` page and login with your account
2. Edit your browser URL from `/dashboard` to `/setup`
3. Copy your browser URL into the `System-URL` field
4. Click on `Save Changes`
5. Either wait until next now playing sync or go to `/admin` scroll down and run the task on the left side called `Now Playing Data`

I have no idea why but I've seen a few people posting a problem here on GitHub that ultimately was caused by the setup not being completed. To detect if the setup is completed there is 1 field in the database that contains a timestamp of the time when the setup was completed. If that's not set, the setup is not completed.

If you can shine a light on what exactly you did after the initial `./docker.sh install` that would help identify what went wrong there. Have you seen the last setup screen (posted a screenshot above in my other response)? Have you completed that step by clicking on the `Save Changes` button? Where there any errors or unusual things happening when you submitted that form?

I have tried to find out how people end up with this issue but apart from just skipping the step I have frankly no idea how that can happen. There is not much going on when finishing the last setup step before setting that db field and if the step failed somehow the process sends you back to the setup instead of the dashboard. See [this part](https://github.com/AzuraCast/AzuraCast/blob/6f66ff072b2217317dc43f6ddf2c4745f14bcc03/src/Controller/Frontend/SetupController.php#L201-L219) of the controller.

**Comment by alencarwell** [comment] 2020-08-05 01:46
@Vaalyn 

Got it, I really have no words to thank you.

If you ever come to Brazil, look for me, I will be happy to help you here.

Thanks for the help.

Now we will wait to see if they discover this problem and so that others do not go through everything I went through here, because my knowledge in Linux and in programming is very little.

**Comment by Vaalyn** [comment] 2020-08-05 01:56
I've looked into some other issue threads here on GitHub and noticed that a check for the setup completion was added around 2 days after the release of AzuraCast 0.10.3 which would have send you straight to the setup when you login. This would have prevented you from doing anything until completing the last step of the setup.

If there is no identifiable bug when saving the last setup step I would say this can't happen on the latest rolling-release version and can currently only happen when using the 0.10.3 release version. I would classify this as a resolved issue with an already existing fix in the latest AzuraCast rolling-release, so I'll close this issue here.

**Closed** 2020-08-05 01:56 UTC
Labels: error

**Comment by alencarwell** [comment] 2020-08-05 02:02
Then I already think that you are rushing.
Because I installed Ubuntu Server 20.4 with Azuracast 10.3 today.

And yet the error happens.

So it is obvious that there is a problem.

**Comment by Vaalyn** [comment] 2020-08-05 02:07
> Because I installed Ubuntu Server 20.4 with Azuracast 10.3 today.

This right here is the issue, you are installing a version that has been released on the 22nd of June which is 2 days before the fix I mentioned was added. Change the `PREFER_RELEASE_BUILDS` to false in `azuracast.env` and you'll get the latest rolling-release version.

WARNING: when using the latest rolling release it can happen that you encounter bugs/issues that have yet to be fixed since you are then using the most up to date version that exists.

**Comment by alencarwell** [comment] 2020-08-05 11:40
One more reason why you didn't close the ticket.

How am I going to put the new version into production and it can cause several other errors, it doesn't make sense.

I restored my server backup and the error returned.

I did exactly what you said and solved the problem.

But when you restart the server, the error returns and again you need to execute what you said.

Imagine when I register all my radios, I will always have to monitor this bug.

So it is a fact that we have a bug.

I believe that you did hurry to close the ticket, because the problem will not be solved.

**Comment by Vaalyn** [comment] 2020-08-05 20:00
> How am I going to put the new version into production and it can cause several other errors, it doesn't make sense.

AzuraCast is beta software, there is no 1.0 release so regardless of if you are using the "stable" release or the "rolling" release you will most likely encounter bugs. Software without bugs does not exist and more so if said software is currently in beta. You can either use the rolling releases if you need one of the patches that were released after your "stable" version or you have to wait for the next "stable" release.

> But when you restart the server, the error returns and again you need to execute what you said.

This I do not really understand. Can you verify for me if I understand you correctly?
When you reboot the server then the database field with the timestamp I talked about is reset and you can execute the last `/setup` step again? If so would you mind giving me another test instance to look at?

>Imagine when I register all my radios, I will always have to monitor this bug.

The field in the database that has been empty on the test instance you provided is only written to in one point of the entire AzuraCast application so there is no way (that I can see or imagine) where a simple reboot would reset this field.

This is the code that sets that db field:
```
$this->settingsRepo->setSetting(Entity\Settings::SETUP_COMPLETE, time())
```

Which is called from the last setup step [here](https://github.com/AzuraCast/AzuraCast/blob/master/src/Controller/Frontend/SetupController.php#L208).

When I do a [search over the entire GitHub repository](https://github.com/AzuraCast/AzuraCast/search?q=%24this-%3EsettingsRepo-%3EsetSetting%28Entity%5CSettings%3A%3ASETUP_COMPLETE&unscoped_q=%24this-%3EsettingsRepo-%3EsetSetting%28Entity%5CSettings%3A%3ASETUP_COMPLETE) for `$this->settingsRepo->setSetting(Entity\Settings::SETUP_COMPLETE`, apart from the setup step the only other part of the code that sets that field is an automatic test case that is only executed when running all tests, which is never done on an installation.

From my point of view the issue of not seeing that the setup is not completed has already been fixed and I can find no part of the code that would reset that field. If I can verify that it does indeed reset when you reboot then I'll gladly reopen this issue as that would be something that can be debugged and fixed. But from the information that I currently have I can not see any bug that has not yet been fixed here.
