### ISSUE TITLE
Music Overlay

### ISSUE THREAD

**Issue by Rafaelrds2017** [AzuraCast/AzuraCast#1360] opened 2019-03-28 14:11 UTC
Music Overlay
When you have a musical request, the music starts playing on top of the current one. Play two songs at the same time. A Current and the request.

**Comment by SlvrEagle23** [comment] 2019-03-28 14:32
@Rafaelrds2017 This is caused by the same issue as #1356 and should be fixed as of the latest update.

**Closed by SlvrEagle23** 2019-03-28 14:32 UTC
