### ISSUE TITLE
does not display a button in the settings

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#648] opened 2018-07-04 15:54 UTC
does not display a button in the settings
![543543](https://user-images.githubusercontent.com/23697714/42286451-9e9bace4-7fbb-11e8-890b-2456ee12b7b8.png)

**Comment by susl16c** [comment] 2018-09-25 09:16
Maybe after a few months you make a button, it's horrible not comfortable in the work?

**Comment by SlvrEagle23** [comment] 2018-09-25 09:29
@susl16c This appears to be caused by a missing translation for the "Save Changes" text. We're not deliberately stopping a button from being displayed on the form, this has to do with your specific localization. It should be fixed in CrowdIn, then reported back here so I can reimport the fixed version.

**Comment by susl16c** [comment] 2018-09-25 09:31
Yes, but why is it displayed elsewhere correctly?

**Comment by susl16c** [comment] 2018-09-25 11:49
I just updated everything today and saw that there are not any changes for a long time and decided to write here.

**Comment by SlvrEagle23** [comment] 2018-09-25 12:27
@susl16c Are you using a custom translation?

I can verify that on the settings and branding pages, "Save Changes" is the exact text used on the submit button, the same as any other page.

I did find one minor issue with the branding page that should've been fixed as of this morning. That shouldn't be related to this issue, though.

**Comment by susl16c** [comment] 2018-09-25 13:08
for my language I use my translation, but I showed you the result in English and this translation is not mine, but it is laid by you and there the same thing is displayed.

**Comment by SlvrEagle23** [comment] 2018-09-25 13:42
@susl16c Looking at the [demo site](https://demo.azuracast.com/) along with my own local installation, this isn't happening on any language.

There may be something wrong with your translation files, but at this point unless you can show me another instance that's doing the same thing (or some further logs indicating why yours is doing that) I'm closing this as "can't reproduce".

**Comment by susl16c** [comment] 2018-09-25 18:32
What other magazines do you need to tell me I will show?

**Comment by SlvrEagle23** [comment] 2018-09-25 19:40
@susl16c If you're on a traditional install, you may want to try running `composer install --no-dev` manually at the `/var/azuracast/www` folder. This shouldn't be necessary for the Docker installation.

It's possible that your AzuraForms dependency has fallen out of date.

**Comment by susl16c** [comment] 2018-09-26 06:16
I last night completely re-installed the whole project and restored from backups nothing had changed, as there was no button so it is not, I use Centos 7 +docker

**Comment by SlvrEagle23** [comment] 2018-10-18 03:14
@susl16c After quite some time, I finally was able to see the error for myself on a production instance of AzuraCast that I was managing. I found the source of the problem and it should be fixed now.

**Closed by SlvrEagle23** 2018-10-18 03:14 UTC
Labels: bug
