### ISSUE TITLE
All listeners are disconnected from the stream 

### ISSUE THREAD

**Issue by RemBdev** [AzuraCast/AzuraCast#946] opened 2018-11-12 21:23 UTC
**Installation method**
Traditional (Icecast)

**Host OS (for Docker installations)**
Ubuntu 16.04

**Describe the bug**
All the listeners were disconnected from the stream. When de Live-DJ accidentally his UTP cable pulled out of his laptop.

**Expected behavior**
I don't know, but it isn't OK all the listeneres need to reload for the stream because they were disconected.

**Relevant Logs**
_Icecast Error Log_
> 2018-11-12  22:13:42] WARN fserve/fserve_client_create req for file "/usr/local/share/icecast/web/radio.mp3" No such file or directory
> [2018-11-12  22:13:42] WARN fserve/fserve_client_create req for file "/usr/local/share/icecast/web/radio.mp3" No such file or directory
> [2018-11-12  22:13:43] WARN fserve/fserve_client_create req for file "/usr/local/share/icecast/web/radio.mp3" No such file or directory
> [2018-11-12  22:13:43] WARN source/source_set_intro Cannot open intro for /radio.mp3 "/usr/local/share/icecast/web//radio.mp3": No such file or directory

_Supervisord Log_
> 2018-11-12 22:13:42,214 INFO exited: station_1_backend (terminated by SIGSEGV (core dumped); not expected)
> 2018-11-12 22:13:43,218 INFO spawned: 'station_1_backend' with pid 27810
> 2018-11-12 22:13:45,088 INFO success: station_1_backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

**Device(s):**
 - Device: All
 - OS: All
 - Browser: All
 - Version: -

**Additional context**
This is the second time in a week. I don't know what happend the first time.

**Comment by CodeSteele** [comment] 2018-11-13 01:07
When was the last time you updated? The radio.mp3 files missing should be fixed as of about a week or two ago. Though this should be a minor issue.

The SIGSEGV issue in the supervisord log is a duplicate of #876 and does cause disconnects.

**Closed by CodeSteele** 2018-11-13 01:07 UTC
Labels: duplicate

**Comment by RemBdev** [comment] 2018-11-13 10:57
@CodeSteele Update was on 6-11-2018
