### ISSUE TITLE
Listeners statistics - Audience - I don't understand???

### ISSUE THREAD

**Issue by radiograndparis** [AzuraCast/AzuraCast#2997] opened 2020-06-29 15:52 UTC
Hello everyone, who could explain to me how the audience statistics are calculated? I see 0.85 listeners / hour ... that doesn't match live listeners. I do not understand???
Thank you very much for your help!

**Comment by ITC-Media** [comment] 2020-06-30 05:12
Same to me, that statistics graphic makes no sense to me.

**Comment by MrSleeps** [comment] 2020-06-30 14:59
If my understanding is correct it's the mean listeners, influx is a time series database. Just round up or down accordingly..

**Comment by ITC-Media** [comment] 2020-07-08 12:12
![Screenshot](https://user-images.githubusercontent.com/13119092/86917095-de40e600-c124-11ea-8234-13459ee71ce8.png)

This Statistics makes no sense to me. Maybe this error is only in the german language, because in Demo Website is correct.

**Comment by CodeSteele** [comment] 2020-08-10 16:07
This is a duplicate of #2748

**Closed by CodeSteele** 2020-08-10 16:07 UTC
