### ISSUE TITLE
media manager: Loading forever

### ISSUE THREAD

**Issue by silvaalex2021** [AzuraCast/AzuraCast#4009] opened 2021-04-13 16:10 UTC
**Using Docker installation method**
Yes

**AzuraCast version**
6fcd9ad (2021-04-13 8:28)

**Host Operating System**
Ubuntu 20.04

**Describe the bug**
I have some folders with a lot of music files (900+), which are used for general rotation. Media manager used to display the files in these folders without problems, but now this is no longer the case. 

Instead of displaying the files, all I get now is a "loading..." message, and it remains until I press f5 to reload the page or use the side menu to browse to another section of azuracast. navigating to another folder using the top menu of the Media manager also does not work, the message will remain there, even when navigating to the root folder.

**Screenshots**
![image](https://user-images.githubusercontent.com/77082907/114585027-9cb40d00-9c59-11eb-9b6e-7e775744d4e7.png)

about the screenshot: The page looks like this due to an chrome extension that I use to increase the contrast, because I have low vision and it is more comfortable.

**Device(s):**

- Device: Desktop
- OS: Windows 10
- Browser: Chrome
- Version: 89.0.4389.114

**Comment by SC2Mitch** [comment] 2021-04-13 16:25
Can you open your browser console (f12 for most browsers, navigate to Network and refresh the page, it should catch the errors.

**Comment by silvaalex2021** [comment] 2021-04-13 16:39
@SC2Mitch


![image](https://user-images.githubusercontent.com/77082907/114588742-66788c80-9c5d-11eb-8703-fe206b68faf5.png)

**Comment by SlvrEagle23** [comment] 2021-04-13 19:35
@silvaalex2021 Click the red request for `list?internal=true...` and look at the response, it should be an error message; copy and paste that error message here.

**Comment by silvaalex2021** [comment] 2021-04-13 19:57
@SlvrEagle23 here's what i got from the "headers" tab.


Request URL: http://my.server.ip.adress/api/station/1/files/list?internal=true&rowCount=10&current=1&flushCache=true&currentDirectory=Geral-internacional
Request Method: GET
Status Code: 500 Internal Server Error
Remote Address: my.server.ip.adress:80
Referrer Policy: no-referrer-when-downgrade
Connection: keep-alive
Content-Type: text/html; charset=UTF-8
Date: Tue, 13 Apr 2021 19:46:35 GMT
Server: nginx
Transfer-Encoding: chunked
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate
Accept-Language: pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7
Connection: keep-alive
Cookie:
Host: my.server.ip.adress
Referer: http://my.server.ip.adress/station/1/files
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36
internal: true
rowCount: 10
current: 1

**Comment by SlvrEagle23** [comment] 2021-04-13 20:03
@silvaalex2021 Anything in the "response" tab? You're very close to giving us the exception data we need; please look around in that console and see if you can find anything relating to the exception and post it here.

**Comment by silvaalex2021** [comment] 2021-04-13 20:13
@SlvrEagle23 "this request has no response data available".

unfortunately that's all i got in the "response" tab. I will keep trying to see if I can get something that can help you ...

**Comment by silvaalex2021** [comment] 2021-04-13 21:27
@SlvrEagle23 I think now I have looked in the right place! (maybe)??? 🙂

Error
vendor-8109e4aa55.js:1 GET http://35.247.248.47/api/station/1/files/list?internal=true&rowCount=10&current=1&flushCache=true&currentDirectory=Geral-internacional 500 (Internal Server Error)
 
Error
StationsMedia-9f7023c5f7.js:1 Uncaught (in promise) TypeError: Cannot read property 'message' of undefined
    at StationsMedia-9f7023c5f7.js:1
 
(anonymous)
@
StationsMedia-9f7023c5f7.js:1
 
Promise.catch (async)
  
 
loadItems
@
StationsMedia-9f7023c5f7.js:1
 
(anonymous)
@
bootstrap-vue-d1e4fe5b8b.min.js:10
 
(anonymous)
@
vue-fb19233884.min.js:6
 
qe
@
vue-fb19233884.min.js:6
 
Promise.then (async)
  
 
ze
@
vue-fb19233884.min.js:6
 
Ye
@
vue-fb19233884.min.js:6
 
e.$nextTick
@
vue-fb19233884.min.js:6
 
componentUpdated
@
bootstrap-vue-d1e4fe5b8b.min.js:10
 
fr
@
vue-fb19233884.min.js:6
 
(anonymous)
@
vue-fb19233884.min.js:6
 
c
@
vue-fb19233884.min.js:6
 
He
@
vue-fb19233884.min.js:6
 
n
@
vue-fb19233884.min.js:6
 
x
@
vue-fb19233884.min.js:6
 
(anonymous)
@
vue-fb19233884.min.js:6
 
x
@
vue-fb19233884.min.js:6
 
(anonymous)
@
vue-fb19233884.min.js:6
 
x
@
vue-fb19233884.min.js:6
 
(anonymous)
@
vue-fb19233884.min.js:6
 
x
@
vue-fb19233884.min.js:6
 
(anonymous)
@
vue-fb19233884.min.js:6
 
e._update
@
vue-fb19233884.min.js:6
 
r
@
vue-fb19233884.min.js:6
 
fn.get
@
vue-fb19233884.min.js:6
 
fn.run
@
vue-fb19233884.min.js:6
 
un
@
vue-fb19233884.min.js:6
 
(anonymous)
@
vue-fb19233884.min.js:6
 
qe
@
vue-fb19233884.min.js:6
 
Promise.then (async)
  
 
ze
@
vue-fb19233884.min.js:6
 
Ye
@
vue-fb19233884.min.js:6
 
(anonymous)
@
vue-fb19233884.min.js:6
 
fn.update
@
vue-fb19233884.min.js:6
 
ce.notify
@
vue-fb19233884.min.js:6
 
set
@
vue-fb19233884.min.js:6
 
pn.set
@
vue-fb19233884.min.js:6
 
changeDirectory
@
StationsMedia-9f7023c5f7.js:1
 
click
@
StationsMedia-9f7023c5f7.js:1
 
He
@
vue-fb19233884.min.js:6
 
n
@
vue-fb19233884.min.js:6
 
Yr.o._wrapper
@
vue-fb19233884.min.js:6
 
 
 
Network Log Row Name: list?internal=true&rowCount=10&current=1&flushCache=true&currentDirectory=Geral-internacional/api/station/1/files, Status: 500Internal Server Error, Type: xhr, Initiator: ​Script, Size: 187 B0 B, Time: 471 ms469 ms

**Comment by Vaalyn** [comment] 2021-04-15 12:51
@silvaalex2021 on the following screenshot you can see what text you need to copy & paste here for us. I don't have an error there so I can only show you a screenshot with a normal response but it is the same place where you will find the error info that we need:

![image](https://user-images.githubusercontent.com/13745863/114871669-cf950700-9df9-11eb-9a7b-167641e1d6ea.png)

**Comment by silvaalex2021** [comment] 2021-04-15 13:23
@Vaalyn Sorry but i searched this tab before, but there is nothing to show ... so I went to the "console" tab and pasted the result ...

![scr](https://user-images.githubusercontent.com/77082907/114876280-8da59a00-9dd4-11eb-9475-994625a08905.png)

**Comment by Vaalyn** [comment] 2021-04-15 13:25
@silvaalex2021 alright, please go to the `Administration` -> `System Logs` and look into the `AzuraCast Application Log` for any errors happening at the time where you opened the media manager. There should be something there related to this problem.

**Comment by silvaalex2021** [comment] 2021-04-15 13:37
@Vaalyn 

[2021-04-15T13:33:17.318226+00:00] AzuraCast.NOTICE: Running sync task: Now Playing Data {"force":false} []
[2021-04-15T13:33:32.308790+00:00] AzuraCast.NOTICE: Running sync task: Now Playing Data {"force":false} []
[2021-04-15T13:33:47.310985+00:00] AzuraCast.NOTICE: Running sync task: Now Playing Data {"force":false} []
[2021-04-15T13:33:57.563367+00:00] AzuraCast.WARNING: Not found. {"file":"/var/azuracast/www/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php","line":91,"code":404} []
[2021-04-15T13:33:58.063035+00:00] AzuraCast.CRITICAL: Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 167936 bytes) in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 112 [] []
[2021-04-15T13:34:01.558189+00:00] AzuraCast.NOTICE: Running sync task: 1-Minute Sync {"force":false} []
[2021-04-15T13:34:01.596661+00:00] AzuraCast.NOTICE: Running sync task: Now Playing Data {"force":false} []
[2021-04-15T13:34:02.702886+00:00] AzuraCast.WARNING: Not found. {"file":"/var/azuracast/www/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php","line":91,"code":404} []
[2021-04-15T13:34:03.177478+00:00] AzuraCast.CRITICAL: Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 167936 bytes) in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 112 [] []
[2021-04-15T13:34:16.405488+00:00] AzuraCast.NOTICE: Running sync task: Now Playing Data {"force":false} []

**Comment by Vaalyn** [comment] 2021-04-15 13:53
@silvaalex2021 this is the problem:

```
AzuraCast.CRITICAL: Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 167936 bytes)
```

You can find a tutorial on how to increase the allowed memory for PHP in our docs here: https://docs.azuracast.com/en/administration/docker#increase-php-allowed-memory

It is a bit strange though that you encounter an out of memory error when viewing just 10 entries per page.

When I look at one of my stations where I have around the same number of songs in a directory I don't encounter any errors. Not even when switching from `10` per page to `ALL`. Not sure why this happens on your installation...

**Comment by silvaalex2021** [comment] 2021-04-15 17:50
@Vaalyn I raised the memory limit to 1024M, but to no avail. The log "critical error" message has disappeared, but the file list still refuses to load.

**Comment by Vaalyn** [comment] 2021-04-15 17:58
@silvaalex2021 please check the browsers network tab again. Is it still giving a `Status Code: 500 Internal Server Error` or is it some other error code / error now?

Is there any other error now showing in the Application Logs?

**Comment by silvaalex2021** [comment] 2021-04-15 18:14
@Vaalyn Oh, god!

Take a look!

[2021-04-15T18:07:39.861436+00:00] AzuraCast.CRITICAL: Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 163840 bytes) in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 132 [] []


it didn't disappear, it just took longer to show up... ... definitely, something is wrong!

**Comment by Vaalyn** [comment] 2021-04-15 18:19
@silvaalex2021 there is definitely something wrong but since I'm unable to reproduce this on any of my test and production installations I'd need to look at this specific installation directly to see where this is coming from.

If that's okay for you could you send me SSH credentials and an admin user account for your AzuraCast installation to vaalyndev@gmail.com?

**Comment by silvaalex2021** [comment] 2021-04-15 18:53
@Vaalyn I sent you two emails, because in the first one I forgot to indicate the SSH port

**Comment by Vaalyn** [comment] 2021-04-15 20:55
Short update on my findings so far:

The `ListAction` that is called dies when fetching the array result from the `$mediaQuery` [here](https://github.com/AzuraCast/AzuraCast/blob/main/src/Controller/Api/Stations/Files/ListAction.php#L142-L143).

I'm not quite sure yet why it's consuming so much memory there.

I think it's possible that after Silver rewrote the `partial` queries in anticipation for their removal in Doctrine 3.0 something is now being accidentally selected there that returns a huge amount of data. I'm wondering though why I can't easily replicate this yet.

I'll be continuing to look into this tomorrow.

For debugging purposes here is the media query generated by Doctrine:

```
SELECT s0_.id AS id_0,
       s0_.storage_location_id AS storage_location_id_1,
       s0_.album AS album_2,
       s0_.genre AS genre_3,
       s0_.lyrics AS lyrics_4,
       s0_.isrc AS isrc_5,
       s0_.length AS length_6,
       s0_.length_text AS length_text_7,
       s0_.path AS path_8,
       s0_.mtime AS mtime_9,
       s0_.amplify AS amplify_10,
       s0_.fade_overlap AS fade_overlap_11,
       s0_.fade_in AS fade_in_12,
       s0_.fade_out AS fade_out_13,
       s0_.cue_in AS cue_in_14,
       s0_.cue_out AS cue_out_15,
       s0_.art_updated_at AS art_updated_at_16,
       s0_.unique_id AS unique_id_17,
       s0_.song_id AS song_id_18,
       s0_.text AS text_19,
       s0_.artist AS artist_20,
       s0_.title AS title_21,
       s1_.id AS id_22,
       s1_.media_id AS media_id_23,
       s1_.field_id AS field_id_24,
       s1_.field_value AS field_value_25,
       s2_.id AS id_26,
       s2_.playlist_id AS playlist_id_27,
       s2_.media_id AS media_id_28,
       s2_.weight AS weight_29,
       s2_.last_played AS last_played_30,
       s3_.id AS id_31,
       s3_.station_id AS station_id_32,
       s3_.name AS name_33,
       s3_.type AS type_34,
       s3_.source AS source_35,
       s3_.playback_order AS playback_order_36,
       s3_.remote_url AS remote_url_37,
       s3_.remote_type AS remote_type_38,
       s3_.remote_timeout AS remote_timeout_39,
       s3_.is_enabled AS is_enabled_40,
       s3_.is_jingle AS is_jingle_41,
       s3_.play_per_songs AS play_per_songs_42,
       s3_.play_per_minutes AS play_per_minutes_43,
       s3_.play_per_hour_minute AS play_per_hour_minute_44,
       s3_.weight AS weight_45,
       s3_.include_in_requests AS include_in_requests_46,
       s3_.include_in_on_demand AS include_in_on_demand_47,
       s3_.include_in_automation AS include_in_automation_48,
       s3_.backend_options AS backend_options_49,
       s3_.avoid_duplicates AS avoid_duplicates_50,
       s3_.played_at AS played_at_51,
       s3_.queue AS queue_52,
       s0_.storage_location_id AS storage_location_id_53,
       s1_.media_id AS media_id_54,
       s1_.field_id AS field_id_55,
       s2_.playlist_id AS playlist_id_56,
       s2_.media_id AS media_id_57,
       s3_.station_id AS station_id_58
FROM station_media s0_
LEFT JOIN station_media_custom_field s1_ ON s0_.id = s1_.media_id
LEFT JOIN station_playlist_media s2_ ON s0_.id = s2_.media_id
LEFT JOIN station_playlists s3_ ON s2_.playlist_id = s3_.id
AND (s3_.station_id = X)
WHERE s0_.storage_location_id = X
  AND s0_.path LIKE 'Geral-internacional/%'
  AND s0_.path NOT LIKE 'Geral-internacional/%/%'
```

**Comment by InstabilSpielt** [comment] 2021-04-16 07:11
I also have the problem since an update (rolling release) a few days ago, but only when one or more songs in the folder have been assigned to a playlist.

**Comment by Vaalyn** [comment] 2021-04-16 17:07
Thanks to the access to the installation that @silvaalex2021 has provided me with I've been able to track down exactly what data is using up all the memory.

As can bee seen in the query I posted above the `$mediaQuery` is unnecessarily fetching the whole queue of the playlists associated to each row. This was due to the mentioned removal of the partial selects in the `ListAction`. From my testings this was resulting in the database returning ~217mb of raw data. After my changes in the PR I built this is now down to 0.29mb for the directory in the station that was provided to me.

**Comment by Vaalyn** [comment] 2021-04-18 07:19
@silvaalex2021 could you update your AzuraCast installation to the latest rolling-release version and check if this has completely resolved this issue?

**Comment by silvaalex2021** [comment] 2021-04-18 17:13
@Vaalyn yes, I can confirm that after updating to the last released version, the problem has disappeared, now I am even able to see all of the 900+ files from within the folder at once without any problem. thank you very much for your help!

**Comment by Vaalyn** [comment] 2021-04-18 17:37
😃  thank you for testing and confirming that the fix is working.

I'll close this issue as resolved then.

**Closed by Vaalyn** 2021-04-18 17:37 UTC
Labels: error
