### ISSUE TITLE
Azuracast doesn´t run after One-Click installation on Dgitalocean

### ISSUE THREAD

**Issue by feder-ico** [AzuraCast/AzuraCast#5063] opened 2022-02-02 18:27 UTC
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.12

### What happened?

I installed Azuracast from Digitalocean Marketplace and when I tried on the droplet public IP nothing happens and connection is refused, like no server is running.
Docker service is running but there is no containers or images.
`docker ps` and `docker images` retieve only headers.
It semms like the installation has not been performed.
The folder /var/azuracast exists, so I tried  
`chmod a+x docker.sh`
`./docker.sh install`
and after selecting "y" for stable I got some errors like this:

> ERROR: Invalid interpolation format for "installer" option in service "services": "ghcr.io/azuracast/web:${AZURACAST_VERSION:-latest}"

Is there any know issue with Digitalocean One-Click installation?
I thought One-Click installation would be safest but, should I install Azuracast manually?

Thanks in advance for any support.

### Relevant log output

```shell
ERROR: Invalid interpolation format for "installer" option in service "services": "ghcr.io/azuracast/web:${AZURACAST_VERSION:-latest}"
ERROR: Invalid interpolation format for "installer" option in service "services": "ghcr.io/azuracast/web:${AZURACAST_VERSION:-latest}"
ERROR: Invalid interpolation format for "installer" option in service "services": "ghcr.io/azuracast/web:${AZURACAST_VERSION:-latest}"
```

**Comment by SC2Mitch** [comment] 2022-02-02 18:48
thanks for the report, will take a look at it

**Comment by SC2Mitch** [comment] 2022-02-04 02:59
Thanks for the report, we're working a fix, sit tight.

**Comment by feder-ico** [comment] 2022-02-04 08:52
I finally managed to make it run performing the update, issuing the following:

```
cd /var/azuracast
./docker.sh update-self
./docker.sh update
```

But I think the fix you are working on is still needed.

Best regards.

**Comment by janek** [comment] 2022-02-04 14:45
I had the same issue, your fix solved it immediately @feder-ico. Bless you for posting, and only 6h ago - glad I was doing this today and not yesterday ;)

**Comment by SlvrEagle23** [comment] 2022-02-05 18:36
We've submitted an updated image to DigitalOcean's marketplace, so new deploys should experience far fewer issues.

**Comment by SC2Mitch** [comment] 2022-02-10 21:10
Should be fixed now, let us know if its not.

**Closed by SC2Mitch** 2022-02-10 21:10 UTC
Labels: bug, in progress

**Comment by spa086** [comment] 2022-02-20 18:18
> Should be fixed now, let us know if its not.

ERROR: Invalid interpolation format for "installer" option in service "services": "ghcr.io/azuracast/web:${AZURACAST_VERSION:-latest}"
ERROR: Invalid interpolation format for "installer" option in service "services": "ghcr.io/azuracast/web:${AZURACAST_VERSION:-latest}"
ERROR: Invalid interpolation format for "web" option in service "services": "ghcr.io/azuracast/web:${AZURACAST_VERSION:-latest}"
ERROR: Invalid interpolation format for "web" option in service "services": "ghcr.io/azuracast/web:${AZURACAST_VERSION:-latest}"
ERROR: Invalid interpolation format for "web" option in service "services": "ghcr.io/azuracast/web:${AZURACAST_VERSION:-latest}"

somthing went wrong... i think

**Comment by SC2Mitch** [comment] 2022-02-20 18:22
@spa086 your using a out of date docker-compose file, we have docs to resolve this issue

https://docs.azuracast.com/en/user-guide/troubleshooting#invalid-interpolation-format-related-errors

**Comment by spa086** [comment] 2022-02-20 19:19
> @spa086 your using a out of date docker-compose file, we have docs to resolve this issue
> 
> https://docs.azuracast.com/en/user-guide/troubleshooting#invalid-interpolation-format-related-errors

I have seen that. But apparently I'm doing something wrong, because:
ERROR: Invalid interpolation format for "web" option in service "services": "ghcr.io/azuracast/web:${AZURACAST_VERSION:-latest}"

**Comment by SlvrEagle23** [comment] 2022-02-20 20:56
@spa086 The latest Marketplace image should fix this, but you may be able to fix this by running:

```
cd /var/azuracast
./docker.sh update-self
./docker.sh install-docker
./docker.sh install-docker-compose
./docker.sh install
```

**Comment by billapto** [comment] 2022-03-29 20:11
Hi all,
i got the same error 
ERROR: Invalid interpolation format for "installer" option in service "services": "ghcr.io/azuracast/web:${AZURACAST_VERSION:-latest}"
ERROR: Invalid interpolation format for "installer" option in service "services": "ghcr.io/azuracast/web:${AZURACAST_VERSION:-latest}"
ERROR: Invalid interpolation format for "web" option in service "services": "ghcr.io/azuracast/web:${AZURACAST_VERSION:-latest}"
ERROR: Invalid interpolation format for "web" option in service "services": "ghcr.io/azuracast/web:${AZURACAST_VERSION:-latest}"
ERROR: Invalid interpolation format for "web" option in service "services": "ghcr.io/azuracast/web:${AZURACAST_VERSION:-latest}"

Set installation directory on /var/azuracast 
Did the /docker.sh update-self / /docker.sh update and still nothing.

I tried this on a rpi4.

any help would be appreciated

**Comment by SlvrEagle23** [comment] 2022-03-30 03:08
@billapto This isn't caused by the same thing as the DigitalOcean error mentioned above, but you should be able to fix it by running:

```
./docker.sh install-docker-compose
```

...then re-running the installation. This error is caused by your Docker Compose version being out of date.

**Comment by FynnZW** [comment] 2022-04-01 17:19
Seems the error has reappeared, the digital ocean public IP gives no response.
When I log in the console to manually restart Docker, the process ist stuck on:
``` 
Starting up AzuraCast services...
🖥️🎵－🎶－📻 Waiting...
```

**Comment by Bazzy-B** [comment] 2022-04-26 16:31
> Seems the error has reappeared, the digital ocean public IP gives no response. I tried this image: https://marketplace.digitalocean.com/apps/azuracast When I log in the console to manually restart Docker, the process ist stuck on:
> 
> ```
> Starting up AzuraCast services...
> 🖥️🎶－🎵－📻 Waiting...Timed out waiting for services to start.
> ```

having exactly the same problem after doing the 1 click install

**Comment by 440music** [comment] 2022-05-13 23:07
The install started and looks as if it will complete without errors. Seems my docker-composer was my issue. 
New to AzuraCast but not new to online Broadcasting I have a history of 24 plus years

**Comment by FynnZW** [comment] 2022-05-14 00:53
> The install started and looks as if it will complete without errors. Seems my docker-composer was my issue.
> New to AzuraCast but not new to online Broadcasting I have a history of 24 plus years

Can you publish your fixed docker-compose then?

**Comment by SC2Mitch** [comment] 2022-05-14 00:56
If users are still having issue with this, please create a new issue. 

For docker-compose issues, please run this command and attempt the process again. 

```
cd /var/azuracast
./docker.sh install-docker
./docker.sh install-docker-compose
```
