### ISSUE TITLE
Question. How do I update my Ansible installation correctly?

### ISSUE THREAD

**Issue by drno88** [AzuraCast/AzuraCast#3507] opened 2020-12-04 19:09 UTC
Ubuntu 16.04 x32 , Ubuntu 18.04 x32
Version - 0.9.6

I installed Azuracast Ansible in the following way.
`sudo mkdir -p /var/azuracast/www 
cd /var/azuracast/www
wget https://github.com/AzuraCast/AzuraCast/archive/0.9.6.tar.gz
sudo chmod a+x install.sh 
./install.sh 
`
Now when you try to update the installation, the update is performed, but the version does not change.

If I understand correctly, I need to replace the www folder with the folder from the new version and run the update file.
In this case, I get a bunch of different errors.
Perhaps I am acting incorrectly?

**Comment by Vaalyn** [comment] 2020-12-04 19:26
You should follow this guide from our website for updating Ansible installations: https://www.azuracast.com/administration/system/updating.html#ansible-installations

**Comment by drno88** [comment] 2020-12-05 07:16
I followed the official instructions, but then no update happens. Attach log file
[update.sh.log](https://github.com/AzuraCast/AzuraCast/files/5646653/update.sh.log)

**Comment by Vaalyn** [comment] 2020-12-05 16:04
I don't have much experience with our Ansible version but there should be a flag called `--full` that you could add to the command like this: `./update.sh --full` to try if that helps.

**Comment by Radio-Quergedacht** [comment] 2020-12-05 16:09
I have the information that Ansible version is actually no longer supported

**Comment by Vaalyn** [comment] 2020-12-05 16:14
@Radio-Quergedacht it is correct that Ansible is not officially supported for general users and that we recommend to switch to using Docker, see the warning on this page here: https://www.azuracast.com/install/ansible.html#installing

For me that means I'll not provide extensive support with diagnosing issues like I do with Docker installations. I'll point people in the right direction of where to look into or link to pages with more information though.

**Comment by drno88** [comment] 2020-12-05 19:30
I would be happy to switch to Docker, but some of my PCs do not support 64 bit systems ...

**Comment by SlvrEagle23** [comment] 2020-12-05 19:45
@drno88 The issue with your installation is that you installed directly from a downloaded source code copy here on GitHub rather than even using the regular Ansible installation instructions.

If you're on a release build downloaded from this site, the only way to replace it with a newer version is to remove the code from its folder (making sure to keep the `env.ini` file in the base directory by copying it somewhere else first) and replace it with a newer download from the same page.

Alternately, once you've removed the code from the folder (and backed up the `env.ini` file), you can do the following:

1. Run the first parts of the Ansible installation:

```bash
sudo apt-get update 
sudo apt-get install -q -y git 
 
sudo mkdir -p /var/azuracast/www 
cd /var/azuracast/www 
sudo git clone https://github.com/AzuraCast/AzuraCast.git . 
```

2. Copy the `env.ini` file you backed up back into `/var/azuracast/www`.

3. Instead of running the installer, run the update script:

```bash
cd /var/azuracast/www
bash update.sh --full
```

**Comment by drno88** [comment] 2020-12-05 20:26
@SlvrEagle23 
judging by the log, the update was successful, but now I get this error

Warning: require(/var/azuracast/www/vendor/autoload.php): failed to open stream: No such file or directory in /var/azuracast/www/web/index.php on line 5

Fatal error: require(): Failed opening required '/var/azuracast/www/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/azuracast/www/web/index.php on line 5

**Comment by drno88** [comment] 2020-12-05 20:38
TASK [azuracast-radio : Add Audiowaveform PPA] ****************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "apt cache update failed"}

**Comment by dougllasvieira** [comment] 2020-12-07 22:11
> @SlvrEagle23
> judging by the log, the update was successful, but now I get this error
> 
> Warning: require(/var/azuracast/www/vendor/autoload.php): failed to open stream: No such file or directory in /var/azuracast/www/web/index.php on line 5
> 
> Fatal error: require(): Failed opening required '/var/azuracast/www/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/azuracast/www/web/index.php on line 5

I'm getting the same error after installing on ansiable = / I don't like the docker

**Comment by Vaalyn** [comment] 2020-12-11 20:25
Could you try updating again?
There have been some updates for Ansible in the last 24h that might help with the problem of the autoload require failing.
I have just tested installing Ansible and have not run into that error so I think that should be fixed.

As we are not providing support for Ansible installations and I'm unable to reproduce any errors on installing via Ansible I'll close this issue now.

> I don't like the docker

In general the Ansible installation method is intended for users who are able to investigate and fix issues by them self and ideally also contribute those fixes back to the project. If you don't like Docker that's okay but keep in mind that we are not providing support for Ansible installations so when you encounter problems your are mostly on your own with that.

**Closed by Vaalyn** 2020-12-11 20:25 UTC

**Comment by drno88** [comment] 2020-12-13 11:18
Everything worked. Thank you so much for your work!
