### ISSUE TITLE
NGINX errors after upgrade 

### ISSUE THREAD

**Issue by YosefAdPro** [AzuraCast/AzuraCast#3929] opened 2021-03-16 18:56 UTC
**Using Docker installation method**

Yes

**AzuraCast version**

Rolling Release #d7d3439 (2021-02-17 19:40) 

**Host Operating System**

Ubuntu 20.4

**Describe the bug**

I'm trying to upgrade from Rolling Release #d7d3439 (2021-02-17 19:40)
 to latest rolling version, And after the upgrade I do not have access to the interface.
When I go to the server I get a welcome page for Nginx.
I do not have any custom environment file
The errors I found in the log.

**To Reproduce**

**Expected behavior**

**Relevant Logs**

```nginx_proxy_letsencrypt    | Reloading nginx proxy (41aa87cac62b6d78880606f743457a3db01b357c8ceee4597a8c59e500d33e49)...
nginx_proxy_letsencrypt    | 2021/03/16 18:36:18 Generated '/etc/nginx/conf.d/default.conf' from 6 containers
nginx_proxy_letsencrypt    | 2021/03/16 18:36:18 [warn] 54#54: duplicate MIME type "text/css" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt    | 2021/03/16 18:36:18 [warn] 54#54: duplicate MIME type "application/javascript" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt    | 2021/03/16 18:36:18 [warn] 54#54: duplicate MIME type "application/json" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt    | 2021/03/16 18:36:18 [warn] 54#54: duplicate MIME type "application/x-javascript" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt    | 2021/03/16 18:36:18 [warn] 54#54: duplicate MIME type "text/xml" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt    | 2021/03/16 18:36:18 [warn] 54#54: duplicate MIME type "application/xml" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt    | 2021/03/16 18:36:18 [warn] 54#54: duplicate MIME type "application/xml+rss" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt    | 2021/03/16 18:36:18 [warn] 54#54: duplicate MIME type "text/javascript" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt    | 2021/03/16 18:36:18 Generated '/app/letsencrypt_service_data' from 6 containers
nginx_proxy_letsencrypt    | 2021/03/16 18:36:18 Running '/app/signal_le_service'
nginx_proxy_letsencrypt    | 2021/03/16 18:36:18 Watching docker events
nginx_proxy_letsencrypt    | 2021/03/16 18:36:18 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
nginx_proxy_letsencrypt    | Reloading nginx proxy (41aa87cac62b6d78880606f743457a3db01b357c8ceee4597a8c59e500d33e49)...
nginx_proxy_letsencrypt    | 2021/03/16 18:36:19 Generated '/etc/nginx/conf.d/default.conf' from 6 containers
nginx_proxy_letsencrypt    | 2021/03/16 18:36:19 [warn] 75#75: duplicate MIME type "text/css" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt    | 2021/03/16 18:36:19 [warn] 75#75: duplicate MIME type "application/javascript" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt    | 2021/03/16 18:36:19 [warn] 75#75: duplicate MIME type "application/json" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt    | 2021/03/16 18:36:19 [warn] 75#75: duplicate MIME type "application/x-javascript" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt    | 2021/03/16 18:36:19 [warn] 75#75: duplicate MIME type "text/xml" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt    | 2021/03/16 18:36:19 [warn] 75#75: duplicate MIME type "application/xml" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt    | 2021/03/16 18:36:19 [warn] 75#75: duplicate MIME type "application/xml+rss" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt    | 2021/03/16 18:36:19 [warn] 75#75: duplicate MIME type "text/javascript" in /etc/nginx/conf.d/default.conf:32
```

```nginx_proxy                | WARNING: /etc/nginx/dhparam/dhparam.pem was not found. A pre-generated dhparam.pem will be used for now while a new one
nginx_proxy                | is being generated in the background.  Once the new dhparam.pem is in place, nginx will be reloaded.
nginx_proxy                | Generating DSA parameters, 4096 bit long prime
nginx_proxy                | forego     | starting dockergen.1 on port 5000
nginx_proxy                | forego     | starting nginx.1 on port 5100
nginx_proxy                | nginx.1    | 2021/03/16 18:36:17 [error] 38#38: *2 open() "/usr/share/nginx/html/login" failed (2: No such file or directory), client: , server: localhost, request: "GET /login HTTP/1.1", host: "91..."

nginx_proxy                | dockergen.1 | 2021/03/16 18:36:17 Generated '/etc/nginx/conf.d/default.conf' from 6 containers
nginx_proxy                | dockergen.1 | 2021/03/16 18:36:17 Running 'nginx -s reload'
nginx_proxy                | dockergen.1 | 2021/03/16 18:36:17 Error running notify command: nginx -s reload, exit status 1
nginx_proxy                | dockergen.1 | 2021/03/16 18:36:17 Watching docker events
nginx_proxy                | dockergen.1 | 2021/03/16 18:36:17 Generated '/etc/nginx/conf.d/default.conf' from 6 containers
nginx_proxy                | dockergen.1 | 2021/03/16 18:36:17 Running 'nginx -s reload'
nginx_proxy                | dockergen.1 | 2021/03/16 18:36:17 Error running notify command: nginx -s reload, exit status 1
```

```

mariadb_1                  | 2021-03-16 18:35:48 0 [Warning] 'proxies_priv' entry '@% root@540efe9ff8c4' ignored in --skip-name-resolve mode.
mariadb_1                  | 2021-03-16 18:35:48 0 [Note] Reading of all Master_info entries succeeded
mariadb_1                  | 2021-03-16 18:35:48 0 [Note] Added new Master_info '' to hash table
mariadb_1                  | 2021-03-16 18:35:48 0 [Note] mysqld: ready for connections.
mariadb_1                  | Version: '10.5.8-MariaDB-1:10.5.8+maria~focal'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
mariadb_1                  | 2021-03-16 18:35:48 0 [Note] InnoDB: Buffer pool(s) load completed at 210316 18:35:48
mariadb_1                  | 2021-03-16 18:36:02 3 [Warning] Aborted connection 3 to db: 'azuracast' user: 'azuracast' host: '172.24.0.5' (Got an error reading communication packets)
mariadb_1                  | 2021-03-16 18:36:15 5 [Warning] Aborted connection 5 to db: 'azuracast' user: 'azuracast' host: '172.24.0.5' (Got an error reading communication packets)

```

**Screenshots**

**Device(s):**

- Device: 
- OS: 
- Browser: 
- Version: 

**Additional context**

**Comment by SlvrEagle23** [comment] 2021-03-18 13:30
@YosefAdPro I'm unsure from the logs what might be causing this problem. You shouldn't be seeing a welcome page for nginx regardless of how the application is set up, as no part of our system keeps the welcome page in place and all components use custom configuration.

It's possible that nginx got updated/installed on your host computer, and is conflicting with your AzuraCast instance of nginx and is occupying the relevant ports. You may be able to confirm this by trying to update your AzuraCast installation; if you see an error like "cannot bind to port 80" (or 443), then that further suggests that's the case. Uninstalling nginx from the host and then rebooting will fix it, if that's the cause.

**Comment by Vaalyn** [comment] 2021-04-23 16:40
Closing this issue since there have been no further replies.

**Closed by Vaalyn** 2021-04-23 16:40 UTC
Labels: error
