### ISSUE TITLE
cloudflare proxy ssl problem with azuracast

### ISSUE THREAD

**Issue by suricloud** [AzuraCast/AzuraCast#3621] opened 2021-01-02 01:03 UTC
**Using Docker installation method**

yes
**AzuraCast version**
Rolling Release #a5cf430 (2021-01-01 20:47)

**Host Operating System**

ubuntu 20.04
**Describe the bug**

azuracast panel doenst work good after cloudfare is enabeld on it

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by Vaalyn** [comment] 2021-01-02 16:33
> azuracast panel doenst work good after cloudfare is enabeld on it

This description is pretty nondescript. Please describe what exactly is not working, provide us with screenshots, logs and errors from your browsers JavaScript console.

**Comment by radio-schlauti** [comment] 2021-01-02 22:46
So we at Cloudflare have no problems either

**Comment by suricloud** [comment] 2021-01-03 15:25
Hi,

here a screenshot:

https://paste.pics/202a806e11472ea1b4accd6f7638ac5c

**Comment by Vaalyn** [comment] 2021-01-03 16:20
@suricloud Since you have only provided a screenshot and not the other information that I requested I can't help you much here.

As far as I'm aware things like this happened for other users due to CloudFlares `Rocket Loader` that is causing issues due to the strict `Content Security Policy` in AzuraCast. You should disable `Rocket Loader` in your CloudFlare settings.

You should be able to see an error in your JavaScript console about this (if Rocket Loader is the cause of this issue on your installation).

**Comment by Vaalyn** [comment] 2021-04-27 08:53
Closing this issue as resolved since there have been no further replies.

**Closed by Vaalyn** 2021-04-27 08:53 UTC
Labels: needs more information
