### ISSUE TITLE
Check on Liquidsoap Installation and rdis

### ISSUE THREAD

**Issue by maletazul** [AzuraCast/AzuraCast#3533] opened 2020-12-09 20:27 UTC
**Using Docker installation method**
No

**AzuraCast version**
Last Dev in Ansible

**Host Operating System**
 Ubuntu 16.04, 18.04, 20

**Describe the bug**
Error installing ubuntu 64Bits vmware clean install: 

1 - TASK [azuracast-radio : Check on Liquidsoap Installation] **********************************************************************************************************
FAILED - RETRYING: Check on Liquidsoap Installation (60 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (59 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (58 retries left).
changed: [localhost]

2 - TASK [redis : Restart Redis service] *******************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not find the requested service redis: host"}

**To Reproduce**
./install.sh 
Checking for Ansible: install ok installed
Installing AzuraCast (Environment: production)

PLAY [all] *********************************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************************
[DEPRECATION WARNING]: Distribution Ubuntu 18.04 on host localhost should use /usr/bin/python3, but is using /usr/bin/python for backward compatibility with prior 
Ansible releases. A future Ansible release will default to using the discovered platform python for this host. See 
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information. This feature will be removed in version 2.12. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
ok: [localhost]

TASK [init : debug] ************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "Running Ansible on localhost with OS Ubuntu bionic 18.04 x86_64 (production)"
}

TASK [init : fail] *************************************************************************************************************************************************
skipping: [localhost]

TASK [init : fail] *************************************************************************************************************************************************
skipping: [localhost]

TASK [init : Add multiverse repository] ****************************************************************************************************************************
ok: [localhost] => (item=deb http://archive.ubuntu.com/ubuntu bionic multiverse)
changed: [localhost] => (item=deb-src http://archive.ubuntu.com/ubuntu/  bionic multiverse)
ok: [localhost] => (item=deb http://archive.ubuntu.com/ubuntu bionic-updates multiverse)
changed: [localhost] => (item=deb-src http://archive.ubuntu.com/ubuntu/  bionic-updates multiverse)

TASK [init : Update apt] *******************************************************************************************************************************************
changed: [localhost]

TASK [init : Install system packages] ******************************************************************************************************************************
changed: [localhost]

TASK [init : Install Focal Packages (20.04)] ***********************************************************************************************************************
skipping: [localhost]

TASK [init : Install Bionic Packages (18.04 only)] *****************************************************************************************************************
ok: [localhost]

TASK [init : Install Xenial Packages (16.04 only)] *****************************************************************************************************************
skipping: [localhost]

TASK [init : Update pip components] ********************************************************************************************************************************
ok: [localhost]

TASK [azuracast-user : Generate AzuraCast Password] ****************************************************************************************************************
changed: [localhost]

TASK [azuracast-user : Create Groups] ******************************************************************************************************************************
ok: [localhost] => (item=www-data)
ok: [localhost] => (item=admin)

TASK [azuracast-user : Create AzuraCast User] **********************************************************************************************************************
changed: [localhost]

TASK [azuracast-user : Modify www-data User] ***********************************************************************************************************************
ok: [localhost]

TASK [azuracast-config : Write environment configuration file] *****************************************************************************************************
ok: [localhost]

TASK [azuracast-config : Set up environment file] ******************************************************************************************************************
ok: [localhost]

TASK [azuracast-config : Set Permissions on Base App Folder] *******************************************************************************************************
ok: [localhost] => (item=/var/azuracast)

TASK [azuracast-config : Clear temp directory] *********************************************************************************************************************
changed: [localhost]

TASK [azuracast-config : Create System Folders] ********************************************************************************************************************
changed: [localhost] => (item=/var/azuracast/www_tmp)
changed: [localhost] => (item=/var/azuracast/www_tmp/proxies)
ok: [localhost] => (item=/var/azuracast/stations)
ok: [localhost] => (item=/var/azuracast/geoip)
ok: [localhost] => (item=/var/azuracast/dbip)
ok: [localhost] => (item=/var/azuracast/backups)
ok: [localhost] => (item=/var/azuracast/servers)
ok: [localhost] => (item=/var/azuracast/servers/shoutcast2)
changed: [localhost] => (item=/var/azuracast/servers/icecast2)

TASK [azuracast-radio : Install IceCast-KH-AC Dependencies] ********************************************************************************************************
ok: [localhost]

TASK [azuracast-radio : Download IceCast-KH-AC Source] *************************************************************************************************************
ok: [localhost]

TASK [azuracast-radio : Extract IceCast-KH-AC Source] **************************************************************************************************************
changed: [localhost]

TASK [azuracast-radio : Build IceCast-KH-AC] ***********************************************************************************************************************
changed: [localhost]

TASK [azuracast-radio : Clear OPAM directory] **********************************************************************************************************************
changed: [localhost]

TASK [azuracast-radio : Add OPAM/OCaml Repository] *****************************************************************************************************************
ok: [localhost]

TASK [azuracast-radio : Install Liquidsoap Dependencies] ***********************************************************************************************************
ok: [localhost]

TASK [azuracast-radio : Initialize OPAM (Bionic)] ******************************************************************************************************************
changed: [localhost]

TASK [azuracast-radio : Initialize OPAM (Focal)] *******************************************************************************************************************
skipping: [localhost]

TASK [azuracast-radio : Build and Install Liquidsoap and Dependencies] *********************************************************************************************
changed: [localhost]

TASK [azuracast-radio : Check on Liquidsoap Installation] **********************************************************************************************************
FAILED - RETRYING: Check on Liquidsoap Installation (60 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (59 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (58 retries left).
changed: [localhost]

TASK [azuracast-radio : Link Liquidsoap binary (Xenial/Bionic)] ****************************************************************************************************
ok: [localhost]

TASK [azuracast-radio : Link Liquidsoap binary (Focal)] ************************************************************************************************************
skipping: [localhost]

TASK [azuracast-radio : Add Audiowaveform PPA] *********************************************************************************************************************
ok: [localhost]

TASK [azuracast-radio : Install Audiowaveform] *********************************************************************************************************************
ok: [localhost]

TASK [Install supervisord from repo] *******************************************************************************************************************************
ok: [localhost]

TASK [Change supervisord configuration] ****************************************************************************************************************************
ok: [localhost]

TASK [Remove old core supervisord configuration] *******************************************************************************************************************
ok: [localhost]

TASK [supervisord : Kill legacy radio processes (if upgrading from older version)] *********************************************************************************
skipping: [localhost]

TASK [Trigger manual restart of supervisord (if not already running)] **********************************************************************************************
skipping: [localhost]

TASK [Uninstall web server packages that may conflict with nginx] **************************************************************************************************
ok: [localhost]

TASK [Unhold nginx-related packages for updates] *******************************************************************************************************************
ok: [localhost] => (item=nginx)
ok: [localhost] => (item=nginx-common)
ok: [localhost] => (item=nginx-extras)

TASK [Remove any older nginx] **************************************************************************************************************************************
changed: [localhost]

TASK [Install nginx] ***********************************************************************************************************************************************
changed: [localhost]

TASK [Create nginx ssl directory] **********************************************************************************************************************************
changed: [localhost] => (item=/etc/nginx/ssl)

TASK [nginx : Create self-signed SSL cert] *************************************************************************************************************************
changed: [localhost]

TASK [Remove default nginx site symlink] ***************************************************************************************************************************
changed: [localhost]

TASK [Add nginx global config] *************************************************************************************************************************************
changed: [localhost]

TASK [Add app-specific nginx site] *********************************************************************************************************************************
changed: [localhost]

TASK [Link app-specific nginx site] ********************************************************************************************************************************
changed: [localhost]

TASK [Turn sendfile off on nginx for local development] ************************************************************************************************************
skipping: [localhost]

TASK [php : Add PHP PPA repository] ********************************************************************************************************************************
ok: [localhost]

TASK [php : Remove Old PHP Libraries] ******************************************************************************************************************************
ok: [localhost]

TASK [php : Install PHP 7.4] ***************************************************************************************************************************************
ok: [localhost]

TASK [php : Configure PHP FPM Pool] ********************************************************************************************************************************
ok: [localhost]

TASK [Configure php-fpm php.ini] ***********************************************************************************************************************************
ok: [localhost] => (item={u'option': u'post_max_size', u'value': u'50M'})
ok: [localhost] => (item={u'option': u'short_open_tag', u'value': u'On'})
ok: [localhost] => (item={u'option': u'upload_max_filesize', u'value': u'50M'})

TASK [Configure php-cli php.ini] ***********************************************************************************************************************************
ok: [localhost] => (item={u'option': u'short_open_tag', u'value': u'On'})

TASK [redis : Add Redis PPA repository] ****************************************************************************************************************************
ok: [localhost]

TASK [redis : Install Redis] ***************************************************************************************************************************************
ok: [localhost]

TASK [redis : Set Redis service name] ******************************************************************************************************************************
ok: [localhost]

TASK [redis : Restart Redis service] *******************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not find the requested service redis: host"}

RUNNING HANDLER [azuracast-user : send user notification] **********************************************************************************************************

PLAY RECAP *********************************************************************************************************************************************************
localhost                  : ok=51   changed=21   unreachable=0    failed=1    skipped=9    rescued=0    ignored=0   

**Relevant Logs**
I dont know what log you guys need @SlvrEagle23

**Comment by Takumi86ES** [comment] 2020-12-09 20:39
I recommend using Ubuntu 16.04

**Comment by maletazul** [comment] 2020-12-09 21:04
@Takumi86ES i have one AWS vm with 18 and i dont have any issues installing.
Why you recommend 16, any specific issue?

**Comment by maletazul** [comment] 2020-12-10 10:08
@SlvrEagle23 , some step forward after git pull , but now new errors:

TASK [azuracast-setup : Run AzuraCast Setup (Install Mode)] ********************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/bin/console azuracast:setup", "delta": "0:00:00.194258", "end": "2020-12-10 10:07:09.521340", "msg": "non-zero return code", "rc": 1, "start": "2020-12-10 10:07:09.327082", "stderr": "\nIn AbstractMySQLDriver.php line 61:\n                                                                               \n  An exception occurred while executing 'SELECT t0.setting_key AS setting_key  \n  _1, t0.setting_value AS setting_value_2 FROM settings t0':                   \n                                                                               \n  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settin  \n  gs' doesn't exist                                                            \n                                                                               \n\nIn Exception.php line 18:\n                                                                               \n  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settin  \n  gs' doesn't exist                                                            \n                                                                               \n\nIn PDOConnection.php line 125:\n                                                                               \n  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settin  \n  gs' doesn't exist                                                            \n                                                                               \n\nazuracast:setup [--update] [--load-fixtures] [--release]", "stderr_lines": ["", "In AbstractMySQLDriver.php line 61:", "                                                                               ", "  An exception occurred while executing 'SELECT t0.setting_key AS setting_key  ", "  _1, t0.setting_value AS setting_value_2 FROM settings t0':                   ", "                                                                               ", "  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settin  ", "  gs' doesn't exist                                                            ", "                                                                               ", "", "In Exception.php line 18:", "                                                                               ", "  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settin  ", "  gs' doesn't exist                                                            ", "                                                                               ", "", "In PDOConnection.php line 125:", "                                                                               ", "  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settin  ", "  gs' doesn't exist                                                            ", "                                                                               ", "", "azuracast:setup [--update] [--load-fixtures] [--release]"], "stdout": "", "stdout_lines": []}

RUNNING HANDLER [azuracast-user : send user notification] **********************

RUNNING HANDLER [azuracast-db-install : send mysql notification] ***************

PLAY RECAP *********************************************************************
localhost                  : ok=85   changed=36   unreachable=0    failed=1    skipped=12   rescued=0    ignored=1

**Comment by SlvrEagle23** [comment] 2020-12-10 11:15
@maletazul This is the same error as #3517, so I'm closing this as a duplicate of this.

For an unsupported installation medium, I'm sure doing a lot of support of it lately...

**Closed by SlvrEagle23** 2020-12-10 11:15 UTC
