### ISSUE TITLE
Slow downloads/Stopped Downloads of backup zips

### ISSUE THREAD

**Issue by JanieUwU** [AzuraCast/AzuraCast#4636] opened 2021-09-30 23:02 UTC
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.14.1

### What happened?

Suddenly a month or two ago downloads for them slowed down to take around 2 hours, now it takes ages. Download estimate is saying 2 days but before it even downloads 60mb it just stops and goes to 0kbps and nothing happens, it just stops. I only see one error in the logs which I will post below but I don't know if that's the issue. I do backup media with it which makes the zip about 2gb in size if that is the problem? Can someone please help.

### Relevant log output

```shell
[2021-09-30T22:07:14.269713+00:00] AzuraCast.WARNING: Not found. {"file":"/var/azuracast/www/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php","line":91,"code":404} []
```

**Comment by SlvrEagle23** [comment] 2021-09-30 23:22
@JanieUwU Just curious, do you have your backups stored somewhere like S3? Or are you using it with the default settings?

**Comment by JanieUwU** [comment] 2021-09-30 23:50
> @JanieUwU Just curious, do you have your backups stored somewhere like S3? Or are you using it with the default settings?

I use default settings, saving to the default backup folder

**Comment by JanieUwU** [comment] 2021-10-01 00:28
This is the furthest I got to downloading it now it just froze again
![image](https://user-images.githubusercontent.com/63387805/135547859-72344733-8801-420f-b5fd-3c80f176b23b.png)
@SlvrEagle23

**Comment by JanieUwU** [comment] 2021-10-01 00:50
@SlvrEagle23 I think I may have found the issue. I am using cloudflare for DNS and routing to the server, and it seems to be causing the issue. I went to the server's direct ip instead of using the domain name and im getting these speeds.
![image](https://user-images.githubusercontent.com/63387805/135549365-79b33eca-4932-4a04-a3b8-52e221561149.png)

**Comment by Vaalyn** [comment] 2021-10-01 08:13
@JanieUwU this thread from the CloudFlare community might be related to the issue you are seeing: https://community.cloudflare.com/t/slow-performance-with-large-uncached-file-via-cloudflare/299065/21

The thread is ~2 months old and seems similar to me.

As far as I understood the thread it's related to the caching settings on CloudFlare free plans and the max file size for their cache. I'd try disabling the caching for this type of files.

Since this issue is most likely caused by CloudFlare and not by AzuraCast I'll close this issue here.
If you find out that there is something that can be done on the AzuraCast side to automatically fix this for all CloudFlare users please let us know.

**Closed by Vaalyn** 2021-10-01 08:13 UTC
Labels: needs investigation

**Comment by JanieUwU** [comment] 2021-10-01 09:01
@Vaalyn Yea idk if it is that, I saw some other issues people had and noticed that cloudflare ratelimits the DNS traffic if you use their proxy service. I turned the proxy service off and now everything works as intended. I wish I could use it as I like the service but it was also causing issues with listening to the stream audio and it kept cutting the audio out. Turning the proxy off also fixed this.
