### ISSUE TITLE
Media processing problem

### ISSUE THREAD

**Issue by julianborghuis** [AzuraCast/AzuraCast#5398] opened 2022-05-21 12:27 UTC
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

 Rolling Release #dee9278 (2022-05-20 4:50) • Docker • PHP 8.1

### What happened?

I uploaded around 500 numbers, and after few hours i saw that the unproccessed queu is at 20000, and also growing.
after i was thinking, i restarted the server. Then no further solves, again, maybe restart the docker instance, this worked, now its not anymore growing and it is processing.

I have this problem since the last updates. Its really difficult to handle this.

### Relevant log output

```shell
Not avalible
```

**Comment by SC2Mitch** [comment] 2022-05-21 15:46
Been unable to reproduce this on a local machine

Attempted to upload 1k files, it processed in approximately 15, the processed queue did climb up but eventually cleared itself down to 0.

**Comment by julianborghuis** [comment] 2022-05-21 19:05
How do I fix this on my system,

Its not always this issue

**Comment by SC2Mitch** [comment] 2022-05-21 19:17
Not sure, this is most likely a issue with your hosting provider / server. Unable to replicate this issue across a production and 2x dev machines. 

Closing due to the lack of information, I don't believe this is an AzuraCast related issue.

**Closed by SC2Mitch** 2022-05-21 19:17 UTC
Labels: needs more information, needs investigation, can't reproduce
