### ISSUE TITLE
Several problems after latest upgrade and radio now is not working

### ISSUE THREAD

**Issue by FiloSpaTeam** [AzuraCast/AzuraCast#3629] opened 2021-01-04 11:12 UTC
**Using Docker installation method**
Yes

**AzuraCast version**
AzuraCast • Rolling Release #b74a0c4 (2021-01-04 8:35)

**Host Operating System**
Ubuntu 20.04.1 LTS

**Describe the bug**
After last upgrade radio stops working

**To Reproduce**
Just upgrated

**Expected behavior**

**Relevant Logs**
```
mariadb_1                  | 2021-01-04 11:02:09 0 [ERROR] Incorrect definition of table mysql.event: expected column 'sql_mode' at position 14 to have type set('REAL_AS_FLOAT','PIPES_AS_CONCAT','ANSI_QUOTES','IGNORE_SPACE','IGNORE_BAD_TABLE_OPTIONS','ONLY_FULL_GROUP_BY','NO_UNSIGNED_SUBTRACTION','NO_DIR_IN_CREATE','POSTGRESQL','ORACLE','MSSQL','DB2','MAXDB','NO_KEY_OPTIONS','NO_TABLE_OPTIONS','NO_FIELD_OPTIONS','MYSQL323','MYSQL40','ANSI','NO_AUTO_VALUE_ON_ZERO','NO_BACKSLASH_ESCAPES','STRICT_TRANS_TABLES','STRICT_ALL_TABLES','NO_ZERO_IN_DATE','NO_ZERO_DATE','INVALID_DATES','ERROR_FOR_DIVISION_BY_ZERO','TRADITIONAL','NO_AUTO_CREATE_USER','HIGH_NOT_PRECEDENCE','NO_ENGINE_SUBSTITUTION','PAD_CHAR_TO_FULL_LENGTH','EMPTY_STRING_IS_NULL','SIMULTANEOUS_ASSIGNMENT'), found type set('REAL_AS_FLOAT','PIPES_AS_CONCAT','ANSI_QUOTES','IGNORE_SPACE','IGNORE_BAD_TABLE_OPTIONS','ONLY_FULL_GROUP_BY','NO_UNSIGNED_SUBTRACTION','NO_DIR_IN_CREATE','POSTGRESQL','ORACLE','MSSQL','DB2','MAXDB','NO_KEY_OPTIONS','NO_TABLE_OPTIONS','NO_FIELD_OPTIONS','MYSQL323','MYSQL40','ANSI','NO_AUTO_V...

web_1                      | [2021-01-04T11:11:19.260108+00:00] AzuraCast.ERROR: Remote server has no mount points listed. {"response":"<?xml version=\"1.0\"?>\n<icestats>\n  <admin>icemaster@localhost</admin>\n  <banned_IPs>0</banned_IPs>\n  <build>133-g4bdfa25</build>\n  <client_connections>144</client_connections>\n  <clients>1</clients>\n  <connections>75</connections>\n  <file_connections>0</file_connections>\n  <host>radio.unitoo.it</host>\n  <listener_connections>0</listener_connections>\n  <listeners>0</listeners>\n  <location>AzuraCast</location>\n  <outgoing_kbitrate>262</outgoing_kbitrate>\n  <server_id>Icecast 2.4.0-kh15-ac1</server_id>\n  <server_start>04/Jan/2021:12:07:04 +0100</server_start>\n  <source_client_connections>0</source_client_connections>\n  <source_relay_connections>0</source_relay_connections>\n  <source_total_connections>0</source_total_connections>\n  <sources>0</sources>\n  <stats>0</stats>\n  <stats_connections>0</stats_connections>\n  <stream_kbytes_read>0</stream_kbytes_read>\n  <stream_kbytes_sent>0</stream_kbytes_sent>\n</icestats>\n"} {"station":{"id":1,"name":"LiveRadio"}}
web_1                      | [2021-01-04T11:11:19.260610+00:00] AzuraCast.WARNING: Could not fetch XML data; falling back to public JSON. [] {"station":{"id":1,"name":"LiveRadio"}}
web_1                      | [2021-01-04T11:11:19.351420+00:00] AzuraCast.ERROR: Response does not contain a "source" listing; the stream may be hidden or misspelled. {"response":"{\"icestats\":{\"admin\":\"icemaster@localhost\",\"banned_IPs\":0,\"build\":\"133-g4bdfa25\",\"host\":\"radio.unitoo.it\",\"location\":\"AzuraCast\",\"outgoing_kbitrate\":262,\"server_id\":\"Icecast 2.4.0-kh15-ac1\",\"server_start\":\"04/Jan/2021:12:07:04 +0100\",\"stream_kbytes_read\":0,\"stream_kbytes_sent\":0}}"} {"station":{"id":1,"name":"LiveRadio"}}

```

**Screenshots**

**Device(s):**

**Additional context**

**Comment by Vaalyn** [comment] 2021-01-04 11:38
Hey, do you know from which version you have updated?

I have updated my test installation and my live station today and haven't encountered any issues there.

Since we haven't changed the Docker image for our DB container since October (and the last change to the MariaDB version was in February 2020) I'd like to know more about your installation to find out what has happened there.

**Comment by FiloSpaTeam** [comment] 2021-01-04 12:09
Hi! Yes. I rollback with a snapshot because restore (automatic backup) not worked too.

```Patrocinato da AzuraCast • Rolling Release #e4e7f8c (2020-12-24 1:33) ```

**Comment by laodikea** [comment] 2021-03-27 17:44
I faced this same problem on 7th of February after updating my rolling release Azuracast installation on Ubuntu 20.04. I don't remember any database related log messages, but web_1 erros were same and radio stopped working. Reinstallation and restoring from backup didn't help, but reinstalling stable version worked and the radio has been working since then. 

I'm going to install azuracast to another server, and update the current installation to check if this problem happens again.

**Comment by laodikea** [comment] 2021-05-02 21:05
Today I tested more:

I have 2 servers with Azuracast installed (on Docker method):

Server 1: v0.12.4 stable
Server 2: Rolling Release #d955d63 (2020-12-20 2:17) 

I faced the problem which I mentioned in my last message on the server 1. There was rolling release version of Azuracast before but on the 7th of February I noticed that after upgrading the radio was not online anymore and I installed stable v0.12 version of Azuracast and the radio started working. Today I upgraded the Azuracast from v0.12 to v0.12.4. There is one streamer streaming via Shoutcast to the radio, but after update the azuracast says that stream is offline. This text shows on the station profile shows "stream offline" text on "On the air" box and no sound can be heard. 

Then I tried to add two mp3 tracks to playlist and play them, but after like 2 seconds the tracks became silent. However, the tracks seemed to play through when I watched the "On the air" box on the profile status page. 

The same Shoutcast streamer is still streaming to both server 1 and server 2 and that same stream can be heard with Server 2 but not on server 1. The settings are the same between the servers (only domain name differs), as far as I know.

I can't see those web_1 errors mentioned on the first post on the server 1 today, when I checked logs on Administration -> System Logs or any other errors. I can post more logs tomorrow. 

The LiquidSoap Log shows following lines among other things: 

````
2021/05/02 15:18:46 [lang:3] Authenticating DJ: n
2021/05/02 15:18:46 [lang:3] AzuraCast DJ Auth Response: true
2021/05/02 15:18:46 [decoder:3] Method "MAD" accepted "audio/mpeg".
2021/05/02 15:18:46 [lang:3] DJ Source connected! Last authenticated DJ: n - [("icy-name", "nettiboksi"), ("icy-url", "nettiboksi"), ("icy-irc", "shoutcast"), ("icy-pub", "1"), ("icy-br", "90")]
2021/05/02 15:18:47 [lang:3] AzuraCast Live Connected Response: true
2021/05/02 15:18:47 [input_streamer:3] Decoding...
2021/05/02 15:18:47 [lang:3] AzuraCast Raw Response: 
2021/05/02 15:18:47 [lang:3] AzuraCast Raw Response: 
2021/05/02 15:18:49 [lang:3] AzuraCast Raw Response: 
2021/05/02 15:18:50 [lang:3] AzuraCast Raw Response: 
2021/05/02 15:18:51 [live_fallback:3] Switch to audio_to_stereo_38812 with transition.
```

Is it possible to install certain version of Azuracast, like test if v0.12.1 works or not? Or what else should I check?

**Comment by laodikea** [comment] 2021-05-04 14:29
I found the answer for my first question from here: https://github.com/AzuraCast/AzuraCast/discussions/3873 and the second question is anwered on that other issue referenced above. I'm going to continue debugging of this problem during this week.

**Comment by FiloSpaTeam** [comment] 2021-05-07 08:41
Mine too it's working. Switched to stable release

**Comment by laodikea** [comment] 2021-05-08 19:47
This issue is maybe same than this: https://github.com/AzuraCast/AzuraCast/issues/3790 and this: https://github.com/AzuraCast/AzuraCast/issues/3771. The latest suggests that this is only problem with info at the management page, and the radio itself is working. 

My problems with mp3 tracks are maybe caused by playing around too fast after installation. Maybe a little bit patience would be good :)

**Comment by SlvrEagle23** [comment] 2021-05-08 19:49
It seems like whatever the original issues were, they were resolved by recent updates which is good to hear.

If there are other issues popping up, feel free to create those as new issues on their own; closing this issue as resolved.

**Closed by SlvrEagle23** 2021-05-08 19:49 UTC
Labels: needs investigation, possible bug, upstream
