### ISSUE TITLE
Scheduled playlist set as sequential, but playing in random mode

### ISSUE THREAD

**Issue by silvaalex2021** [AzuraCast/AzuraCast#3910] opened 2021-03-11 16:06 UTC
**Using Docker installation method**
Yes

**AzuraCast version**
V 0.12.2 stable

**Host Operating System**
Ubuntu 20.04

**Describe the bug**
I will try my best, since English is not my native language ...

I have some scheduled playlists with pre-recorded shows that need to be played in exact order. So I set them up to play sequentially and scheduled them as follows:

Show 1 (120 min split into 6 20 minute parts)
scheduled to play between 6:00 am and 8:00 am

Instead of playing like this:
Part 01.mp3
part 02.mp3
part 03.mp3
part 04.mp3
part 05.mp3
part 06.mp3

AutoDJ is playing everything randomly, part 02, part 01, part 06, part 04 and so on.

I've tried everything to get this to work, but with azuracast AutoDJ it is not possible, it only works when using manual AutoDJ.

**To Reproduce**
1: Create a playlist like this:
type: General rotation;
weight: 25;
Avoid duplicates: No;
Play order: Sequential.

2: schedule to play at some time period.

3: When the time comes, watch the Nest song Queue.

**Expected behavior**
AutoDJ should respect the sequential playlist configuration, and play the files exactly in the order in which they appear in the playlist.

**Comment by Abqehebter** [comment] 2021-03-11 22:54
It's the same Issue like #3842 ?

**Comment by silvaalex2021** [comment] 2021-03-11 23:45
@Abqehebter In the meantime, while our friends are working on a fix for this problem, I use some trickery to make things work as expected.

I created a Bash script that uses SOX to concatenate the files prior to their execution, and the resulting file is the only one to be added to the playlist. This way I can play the entire show as a single 2-hour mp3 file instead of adding the 6 separate files to the playlist, and the guys can keep sending me their shows like they always did while our radio was running on CentovaCast

**Comment by SlvrEagle23** [comment] 2021-03-22 15:06
I've pushed an update to the Rolling Release channel that will make sequential playlists be less aggressive with resetting their internal queues, so they shouldn't do it the first time they fail to be able to produce a non-duplicate track.

**Comment by silvaalex2021** [comment] 2021-03-22 19:49
@SlvrEagle23 let's see if it works!

I have already tried to manually reset the "internal play queue" via the drop-down menu next to the affected playlists hoping that azuracast would rebuild the queue in the correct order, but to no avail! maybe this was not the right place to do that!

**Comment by SlvrEagle23** [comment] 2021-03-23 16:49
Closing as a likely duplicate of #3863.

**Closed by SlvrEagle23** 2021-03-23 16:49 UTC
