### ISSUE TITLE
Direct stream Remote URL playlist not working.

### ISSUE THREAD

**Issue by mrdavi5** [AzuraCast/AzuraCast#2578] opened 2020-03-26 19:53 UTC
Using Docker installation method
Yes

Host Operating System
Ubuntu 18.04

Describe the bug
With latest update, Remote URL Playlist no longer works.

To Reproduce
Edit playlist, source, remote URL playlist
Using http://external_IP:8000/stream 
Remote URL type: DIRECT STREAM URL 

Expected behavior
Play from remote source, direct or playlist.

**Comment by SlvrEagle23** [comment] 2020-03-27 03:12
@mrdavi5 Closing as likely duplicate of #2578.

**Closed by SlvrEagle23** 2020-03-27 03:12 UTC
