### ISSUE TITLE
Various errors after update to 0.9.5.1

### ISSUE THREAD

**Issue by gammaw** [AzuraCast/AzuraCast#1677] opened 2019-06-19 11:55 UTC
After above update we experience strange behaviour: 
- `docker compose up` will not proceed (doesn't print anything, never terminates); 
- Music file uploads don't work (progress bar starts and disappears immediately); 
- Music file picture cannot be changed (see browser error message below).

A reboot of the host machine (Digital Ocean) solves these issues but they return at some point. Any idea?  

![image](https://user-images.githubusercontent.com/28865986/59763155-3cd8bf00-9299-11e9-987f-54007f7b5371.png)

**Comment by ErnestPH** [comment] 2019-06-19 11:58
run the update again…

**Comment by gammaw** [comment] 2019-06-19 12:00
@ErnestPH thanks, but why? :) Was there a specific issue and fix we missed?

**Comment by ErnestPH** [comment] 2019-06-19 12:03
Could be the update missed something? I do find this effective… Just try it and test again.

**Comment by gammaw** [comment] 2019-06-19 12:13
@ErnestPH what do you mean the update missed something? I'd like to know the root cause of above behaviour. Addition: there has been a Linux kernel update recently.

**Comment by ErnestPH** [comment] 2019-06-19 12:20
are there error logs?…

What I am trying to mean, that there were some cases (for instances… some experienced, file upload was not working after updating) but then when they updated the server, it fixes the issue. I have tried it… Are you certain that you have the latest build?

**Comment by gammaw** [comment] 2019-06-19 13:01
I didn't find errors in the logs available through the GUI but I'm sure there are errors logged somewhere.

**Comment by SC2Mitch** [comment] 2019-06-19 14:23
@gammaw Consult the console for the errors, they appear there. #1678 for the logs you may want.

**Comment by gammaw** [comment] 2019-06-19 18:48
@SC2Mitch for https://github.com/AzuraCast/AzuraCast/issues/1678 I have the same. Thanks for pointing out! In case of changing art work (with the nginx 500 error) I don't see anything in the console.

**Comment by SlvrEagle23** [comment] 2019-06-19 18:50
@SC2Mitch @gammaw You're both having the same issue. Closing in favor of #1678.

**Closed by SlvrEagle23** 2019-06-19 18:50 UTC

**Comment by gammaw** [comment] 2019-06-19 18:54
@SlvrEagle23 one error is in common but I don't know if the others have the same root cause. Let's see.

**Comment by SlvrEagle23** [comment] 2019-06-19 18:56
@gammaw @SC2Mitch I need one of you, either of you, anyone on earth really, to get me those Docker container logs before I can conclusively say, but I strongly suspect there's a common root cause here.
