### ISSUE TITLE
NChan / Websocket "now playing" not updating

### ISSUE THREAD

**Issue by nokturnal** [AzuraCast/AzuraCast#2696] opened 2020-04-18 18:09 UTC
**Using Docker installation method**

Yes, by following these instructions: https://websiteforjust200.com/how-to-configure-vps-to-stream-online-radio-shows/

**Host Operating System**

Ubuntu 18.04

**Describe the bug**

When "Use WebSockets for Now Playing Updates" is checked, updates do not occur in the default radio player.  Unchecking this (reverting back to the setTimeout API calls) makes the player work as expected.

**To Reproduce**

I have tested this by letting the current song transition to the the next, and by interrupting the currently playing song with a live broadcast.  In both cases, the audio works as expected but the now playing information in the player does not update.

Also, I am noticing in the Chrome & FF dev tools that the WS connection appears to connect as expected, but no messages are ever being sent.

**Relevant Logs**

[2020-04-18T17:58:17.761659+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
[2020-04-18T17:58:20.438513+00:00] AzuraCast.INFO: Received "DJ connected" ping from Liquidsoap. {"station_id":1,"station_name":"Some Station","dj":"nokturnal"} []
[2020-04-18T17:58:32.790697+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
[2020-04-18T17:58:47.776859+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
[2020-04-18T17:58:53.282574+00:00] AzuraCast.INFO: Received "DJ disconnected" ping from Liquidsoap. {"station_id":1,"station_name":"Some Station","dj":"nokturnal"} []
[2020-04-18T17:58:58.300095+00:00] AzuraCast.INFO: New message of type App\Message\UpdateNowPlayingMessage added to queue. [] []
[2020-04-18T17:59:00.315884+00:00] AzuraCast.INFO: Handling message of type App\Message\UpdateNowPlayingMessage. [] []
[2020-04-18T17:59:02.276868+00:00] AzuraCast.INFO: Running 1-minute sync task [] []

To my newb eye this seems all above board.

**Device(s):**
 - Device:  Desktop
 - OS:  Windows 10
 - Browser: Chrome Version  FireFox Developer 76.0b5 (64-bit)
 - Version:  81.0.4044.113 (Official Build) (64-bit)
---
 - Device:  Desktop
 - OS:  Windows 10
 - Browser: FireFox Developer 
 - Version:  76.0b5 (64-bit)
---
 - Device:  Pixel 3 XL
 - OS:  Android 10
 - Browser: Chrome
 - Version:  81.0.4044.111

**Additional context**

Other settings:
- "Use Web Proxy for Radio" unchecked
- SSL installed (via the LetsEncrypt instructions)
- "Always Use HTTPS" checked
- "API 'Access-Control-Allow-Origin' header" is empty

**Comment by SlvrEagle23** [comment] 2020-06-19 09:27
@nokturnal Sorry I didn't get back to this one sooner. We haven't been able to reproduce this issue locally, and I suspect that's because for quite a while now we've actually used the "multi-site" configuration (with nginx_proxy) on our local development environments, creating a slightly different environment than is present in production AzuraCast environments. Over the last few months, though, we've merged those configurations so now all installations (with updated Docker Compose files) use the multi-site configuration with the nginx_proxy in front of the services.

This may change how you're encountering this bug, or it may resolve it altogether. Please let me know if it continues to be an issue on the latest version of the application with the latest Docker Compose file.

**Comment by andrew-occ** [comment] 2020-06-19 12:04
> This may change how you're encountering this bug, or it may resolve it altogether. Please let me know if it continues to be an issue on the latest version of the application with the latest Docker Compose file.

@SlvrEagle23 you hit the nail right on the head.  After updating, I have confirmed that the WS is now sending messages to the bundled default web player.  

I will do some more testing on my custom players, but it appears everything is resolved after following the instructions here: https://www.azuracast.com/administration/system/updating.html

Thank you @SlvrEagle23 :)

**Comment by nokturnal** [comment] 2020-06-19 12:08
> This may change how you're encountering this bug, or it may resolve it altogether. Please let me know if it continues to be an issue on the latest version of the application with the latest Docker Compose file.

@SlvrEagle23 you hit the nail right on the head.  After updating, I can confirm that the WS is now sending messages to the bundled default web player.  

I will do some more testing on my custom players, but it appears everything is resolved after following the instructions here: https://www.azuracast.com/administration/system/updating.html

Thank you @SlvrEagle23 :)

**Comment by SlvrEagle23** [comment] 2020-06-19 15:15
@nokturnal Good to hear! :)

**Closed by SlvrEagle23** 2020-06-19 15:15 UTC
Labels: error
