### ISSUE TITLE
M3u pls files generated for itune winamp media player

### ISSUE THREAD

**Issue by fast97** [AzuraCast/AzuraCast#2663] opened 2020-04-12 19:16 UTC
I noticed that the m3u and pls file generated on the profile page does not work with itune. if we could have compatible files generated without having to modify it manually it would be good for customers.

**Comment by SlvrEagle23** [comment] 2020-04-12 19:59
@fast97 Closing as a duplicate of your second issue, #2664. Please only open one issue at a time.

**Closed by SlvrEagle23** 2020-04-12 19:59 UTC

**Comment by fast97** [comment] 2020-04-12 21:07
Ok yes
Thank
