### ISSUE TITLE
Scheduled playlists and streamers missing from schedule API

### ISSUE THREAD

**Issue by chrisulloa** [AzuraCast/AzuraCast#7117] opened 2024-05-17 00:52 UTC
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#68f2282 (2024-05-16 17:54)

### What happened?

As of version 0.19.7, the schedule API is no longer functioning correctly. The calendar views are missing scheduled playlists and streamers.

The `/api/station/[stationId]/playlists/schedule` endpoint is not returning results for scheduled streamers and playlists.

Expected Behavior:
All scheduled playlists and streamers are listed in the schedule.

Current Behavior:
Only playlists and streamers with a weekly recurrence (no start and end date) are displayed.

### Relevant log output

```shell
Cannot find any relevant logs
```

**Comment by BusterNeece** [comment] 2024-05-17 08:00
@chrisulloa This isn't the first report I'm seeing of this, but in my local development I can't reproduce it at all. I've tried scheduled playlists with same-day start and end, overnight playlists, ones set to play only on certain days, ones set to play on all days, ones with a start and end date, ones _without_ a start or end date...and they all show up on the calendar perfectly.

I'd honestly like to look at an installation that's having this problem to see exactly how its playlist/DJ schedule is configured, because I just can't figure it out from my end right now.

**Comment by BusterNeece** [comment] 2024-05-17 17:37
Closing in favor of #7098 which is reporting the same issue.

**Closed by BusterNeece** 2024-05-17 17:37 UTC
Labels: bug, needs investigation, rolling-release
