### ISSUE TITLE
Auto DJ Stops Playing Song Queue

### ISSUE THREAD

**Issue by JanieUwU** [AzuraCast/AzuraCast#2751] opened 2020-04-26 14:16 UTC
**Using Docker installation method**
 Yes

**Host Operating System**
 Debian 10

**Describe the bug**

When using the skip current song button, it skips to the next song in the queue but after auto DJ resumes playing it just selects a random song. Does not continue the queue and keeps displaying as the song will be played next but never does continue it.

Added extra to this is that when viewing the song history the history sometimes chooses not to display a recently played song. I noticed that it shows the last 2 played and the 3 will not be shown on the list and then the 4th and 5th will be shown then the 6th won't.

**To Reproduce**

1. Press skip button on the dashboard.
2. Let song play.
3.Observe the station's Auto DJ playing random songs instead of what the song queue says is next.
4. Restart station to get station playing normally again.

**Expected behavior**

The song to be skipped and the queue continues playing as normal and the song history to show every last played song.
**Relevant Logs**

[2020-04-26T14:09:17.266399+00:00] AzuraCast.ERROR: Playlist "Vocaloid" did not return a playable track. {"playlist_id":2,"playlist_order":"shuffle","allow_duplicates":false} {"station":{"id":1,"name":"Radio"}}
[2020-04-26T14:09:17.266635+00:00] AzuraCast.INFO: Found track that avoids duplicate title and artist. {"media_id":113} {"station":{"id":1,"name":"Radio"}}
[2020-04-26T14:09:17.304241+00:00] AzuraCast.INFO: Playable track found and registered. {"next_song":"StationMedia 166bd3853fd8a0bad02a99b8: Pokemon Company - Mimikyu's Song"} {"station":{"id":1,"name":"Radio"}}
[2020-04-26T14:09:32.131849+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
[2020-04-26T14:09:47.128510+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
[2020-04-26T14:09:50.208776+00:00] AzuraCast.WARNING: Not found. {"file":"/var/azuracast/www/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php","line":93,"code":404} []
[2020-04-26T14:09:58.119189+00:00] AzuraCast.INFO: New message of type App\Message\UpdateNowPlayingMessage added to queue. [] []
[2020-04-26T14:10:00.135333+00:00] AzuraCast.INFO: Handling message of type App\Message\UpdateNowPlayingMessage. [] []
**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

Powered by AzuraCast • v0.10.1, #c7e2c3f (2020-04-26 12:47) • Docker • PHP 7.4

**Comment by SlvrEagle23** [comment] 2020-04-27 06:14
@JanieUwU This is valid and I am able to reproduce it locally: while the very next track is the correct one, the tracks _after_ that go completely off the rails and throw things off. Investigating this and will update further.

**Comment by SlvrEagle23** [comment] 2020-05-08 05:30
Follow the upstream issue on the Liquidsoap issue tracker as: savonet/liquidsoap#1198

**Comment by JanieUwU** [comment] 2020-06-16 13:15
is this still an ongoing fix? :(

**Comment by SlvrEagle23** [comment] 2020-06-16 14:14
@JanieUwU It's still on my list of items to complete. I haven't made progress on it due to a number of real world issues.

**Comment by JanieUwU** [comment] 2021-04-15 04:29
@SlvrEagle23 any news on this? I'd like to reinstall azuracast again when I can get my new server up and running

**Comment by SlvrEagle23** [comment] 2021-04-15 04:55
@JanieUwU The Liquidsoap team has said that they'll build a fix for this into Liquidsoap 2.0, which is currently in its early testing stages.

I would like to think that AzuraCast is useful enough to want to use even still, given that this issue only affects skipping songs.

**Comment by JanieUwU** [comment] 2021-04-15 06:01
> @JanieUwU The Liquidsoap team has said that they'll build a fix for this into Liquidsoap 2.0, which is currently in its early testing stages.
> 
> I would like to think that AzuraCast is useful enough to want to use even still, given that this issue only affects skipping songs.

Oh it is, yeah I will be still using it it's amazing I was just hoping since I do tend to skip songs a lot! Thanks for the update however!

**Closed** 2024-11-27 23:42 UTC
Labels: bug, in progress, upstream, stable, rolling-release
