### ISSUE TITLE
Error Autodj Liquid

### ISSUE THREAD

**Issue by fast97** [AzuraCast/AzuraCast#4890] opened 2021-12-16 23:17 UTC
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

Hello for 2 days I have 2 station which stops and which starts again in auto dj and the live direct works. Can help me because I have already restarted deleting all the playlists without success. I will have to restart or do an update to get back to normal. But after its stops. Thank you

### Relevant log output

```shell
Log :
Fatal error: exception Error while trying to bind server/telnet socket: Address already in use in bind()
Raised at file "tools/server.ml", line 463, characters 16-59
Called from file "tools/server.ml", line 477, characters 19-34
Called from file "tools/lifecycle.ml", line 33, characters 8-14
Called from file "tools/lifecycle.ml", line 33, characters 8-14
Called from file "tools/lifecycle.ml", line 33, characters 8-14
Called from file "tools/lifecycle.ml", line 33, characters 8-14
Called from file "tools/lifecycle.ml", line 33, characters 8-14
Called from file "src/dtools_impl.ml", line 455, characters 10-16
Re-raised at file "src/dtools_impl.ml", line 466, characters 8-15
Called from file "list.ml", line 110, characters 12-15
Called from file "src/dtools_impl.ml", line 458, characters 10-35
Re-raised at file "src/dtools_impl.ml", line 466, characters 8-15
Called from file "list.ml", line 110, characters 12-15
Called from file "src/dtools_impl.ml", line 458, characters 10-35
Re-raised at file "src/dtools_impl.ml", line 466, characters 8-15
Called from file "main.ml" (inlined), line 566, characters 15-51
Called from file "runner.ml", line 25, characters 9-22
```

**Comment by SlvrEagle23** [comment] 2021-12-17 04:58
@fast97 Which Rolling Release version are you on? Updating may help resolve this issue, as we've been working hard on Liquidsoap-related fixes over the last few days and weeks.

**Comment by fast97** [comment] 2021-12-17 07:06
Hello , version :  Rolling Release #4299683 (2021-12-16 6:15) • Docker • PHP 8.1
I think I'm on the latest version. I restart and restart the server the services are restarted I wait to see if it remains normal and does not cut. Thank you

**Comment by SC2Mitch** [comment] 2021-12-19 17:27
Ive had this error a few times but I'm not exactly sure on the root cause of it, flagging for further review.

Questions: When this happens does your machine have high CPU usages? And does this impact other stations?

**Comment by fast97** [comment] 2021-12-19 19:45
Hello, I don't think the problem is with the machine. at the moment only one station is faulty and is using port 8000. Live is working well. Autodj seems to have worked, but no sound. the others are working well. But the memory initially was not that high either. I have 29 stations on the machine. I will update tonight as there are 16 and see if that fixes the problem.
![cap32](https://user-images.githubusercontent.com/51033222/146688532-87b52a76-3af8-4a18-843d-82354668f9d3.png)

**Comment by joshms123** [comment] 2021-12-20 09:17
I am also having this issue; the station will just randomly crash.

**Comment by fast97** [comment] 2021-12-20 10:00
Update this morning the problem seems to be resolved. I wait a few hours to see if it's yours.
  Rolling Release # a2eb5d0 (2021-12-19 18:50) • Docker • PHP

**Comment by SlvrEagle23** [comment] 2021-12-21 09:40
Closing in favor of #4897, as this has been identified as a more widespread issue.

**Closed by SlvrEagle23** 2021-12-21 09:40 UTC
Labels: bug, liquidsoap error, rolling-release
