### ISSUE TITLE
Station metadata dashboard bug

### ISSUE THREAD

**Issue by kbysfm** [AzuraCast/AzuraCast#297] opened 2017-11-27 22:44 UTC
Brand new AzuraCast (docker) install. Spun up a Shoutcast instance with a streamer account. I'm using BUTT on the "air" PC which connects to AzuraCast with streamer cred. Everything has been working, profile page is showing unique listeners as well as artist/album metadata. However for some reason the dashboard is not showing metadata.

Dashboard:
![screen shot 2017-11-27 at 4 30 08 pm](https://user-images.githubusercontent.com/25082477/33293063-1c61d7fc-d391-11e7-80f4-3590ce3b7919.png)

Profile page:
![screen shot 2017-11-27 at 4 41 52 pm](https://user-images.githubusercontent.com/25082477/33293287-e9014d92-d391-11e7-845c-d25355129c7d.png)

Thanks @SlvrEagle23 for everything you do man!

**Comment by SlvrEagle23** [comment] 2017-11-27 22:45
@kbysfm When you're on the station homepage, if you open the dev tools (i.e. "Inspect Element" on the page) and go to the console tab, do you see any errors?

**Comment by kbysfm** [comment] 2017-11-28 14:41
@SlvrEagle23 no errors, i even have all levels showing just to be sure.

**Comment by kbysfm** [comment] 2017-11-30 15:11
@SlvrEagle23 just realized my test environment synchronization task have been running consistently and metadata appears within the dashboard. Whereas on the recent install, I have to manually run the task and reload the system admin page then if I go to the dashboard the metadata appears. 

The test environment is the docker install on MacOS and the new install (docker) is on RHEL. 

Thoughts?

**Comment by SlvrEagle23** [comment] 2017-11-30 15:23
@kbysfm That suggests the cron Docker container isn't running properly for some reason. If you run `docker ps`, do you see a running `azuracast_cron` container on the troublesome instance?

**Comment by SlvrEagle23** [comment] 2017-11-30 16:13
@kbysfm I've received a number of reports of problems with the now-playing data on the homepage, which suggests that the websocket-based updates are causing a number of unpredictable issues that are difficult or impossible for me to preemptively fix with my setup. The best kind of bug!

I've updated the AzuraCast app dashboard (the homepage of the app) to switch to the older "long polling" style of connection, which should be less prone to this type of issue.

Please update and let me know if this resolves the issue on the homepage. Other pages haven't been fixed yet, and will only be updated once I can verify that this actually resolves the problem.

**Comment by surihost** [comment] 2017-11-30 16:21
I have just updated,but still the same

**Comment by SlvrEagle23** [comment] 2017-11-30 16:26
@surihost So, just to be very very clear here, since this is one of those "I don't see what you're seeing" types of bugs:
 - You **do** see the correct now playing data elsewhere on the system, but
 - You **don't** see the correct data on the homepage, but
 - There's **no** error on your console or network traffic?

Not to depart from my normally sunny disposition here on Github, but I'm about at the end of my rope with this series of bug reports. I can't reproduce these problems on _any_ of my local boxes, and without having admin-level access to the reporters' AzuraCast instances, I can't proceed any further with trying to resolve this issue.

I apologize for the lack of options here, but as a single developer working on a huge project like this one, constantly fighting impossible little bugs like this one is driving me a little nuts.

If you're interested in further resolving this issue, please contact me via e-mail at loobalightdark@gmail.com. Thank you.

**Comment by surihost** [comment] 2017-11-30 16:32
i have sent email

**Comment by SlvrEagle23** [comment] 2017-11-30 16:40
@surihost After looking at your instance, there was a very clear error in the Now Playing synchronization (it hadn't been run in 40 hours, and the error appears any time you try to run it) that might've been the cause of the problem entirely.

Please update and let me know if it is resolved after allowing a minute or so for now playing data to update.

**Comment by surihost** [comment] 2017-11-30 16:53
I have running the instance for 2 days now but the porblem was already there.
For now its still not updating ,also the listener stats shows 0

**Comment by SlvrEagle23** [comment] 2017-11-30 16:54
@surihost I meant update **again**. I pushed a fix out after looking at your instance just seconds before I sent my message.

**Comment by surihost** [comment] 2017-11-30 17:01
i just updated again,and now it seems to be working again :)
Thanks

**Comment by kbysfm** [comment] 2017-12-01 19:43
@SlvrEagle23 just ran the update - no change. Synchronization hasn't ran for 25+ hrs. I went ahead and ran the task but like I mentioned earlier I have to manually run the task for the now playing data to show. If I navigate away and come back to the dashboard the metadata disappears.

**Comment by SlvrEagle23** [comment] 2017-12-01 23:21
@kbysfm So if you manually run the synchronization via the web console, there's no error, but it won't run automatically?

If you're referring to the now playing sync, try refreshing it a few times over the course of about a minute and see if any visible error appears. Sometimes the nowplaying sync will "skip" if it was run too recently, and you won't see any errors.

Otherwise, can you try manually running the sync manually, i.e. via running:
`docker-compose run --rm cli azuracast_cli sync:run [nowplaying|short|medium|long]` (change the last variable based on which sync process isn't running)

**Comment by SlvrEagle23** [comment] 2017-12-02 15:42
@kbysfm If the sync task is running fine, without any errors, it may be as simple as running `docker-compose up -d cron` to spin up the cron container, as that may not be running for whatever reason.

If that fails because the cron container _is_ already running, try `docker-compose logs -f cron` and see if the logs reveal anything interesting.

I'm working to diagnose this in fairly vague terms because without direct access to the AzuraCast instance I can't really tell you immediately what the problem is.

**Comment by kbysfm** [comment] 2017-12-02 23:45
@SlvrEagle23 is it normal for "Attaching to azuracast_cron" to take awhile after running `docker-compose logs -f cron`?

`docker-compose up -d cron` appears to be running. redis_1, influxdb_1, stations, mariadb_1, web_1 and cron are up-to-date.

I get why you're being vague and I hope I'm providing enough information to help diagnose the problem. Anywho, I'm confident that you will find a solution.

**Comment by SlvrEagle23** [comment] 2017-12-13 00:12
@kbysfm Have you been able to reach any resolution on this issue? I'm not sure that there's much else I can do to diagnose it from here.

**Comment by kbysfm** [comment] 2017-12-13 15:43
@SlvrEagle23 still fighting it. In the next day or so I plan on changing my test environment over to our server IP block. This should help me compare each system more closely. I was unable to see the cron logs - unless i'm doing something wrong. I really think something sketchy is going on between RHEL 6 and docker.

**Comment by kbysfm** [comment] 2017-12-13 22:24
@SlvrEagle23 **new update** - Mac Mini running latest docker and AzuraCast is working like a champ. Metadata is working great. So back to RHEL, do you think installing AzuraCast under /opt directory might contribute to this issue? In theory it shouldn't matter because it's all contained in docker. It seems like a cron issue, but why is it a cron issue on one system and not the other? Very inconsistent and confusing! I'll dig deeper tomorrow.

**Comment by SlvrEagle23** [comment] 2017-12-13 22:26
@kbysfm Yeah, I think this has something to do with the specifics of your setup on RHEL. I have no idea what the implications of this are, but is SELinux enabled? That could majorly affect Docker in weird ways.

**Comment by kbysfm** [comment] 2017-12-13 22:32
It's set to permissive. I'll dig deeper tomorrow for sure. Thanks for the follow up!

**Comment by kbysfm** [comment] 2017-12-14 21:42
Haven't had much time to mess with it today. What I have noticed and this may be a Mac OS thing (sigh) is that the listener view is showing the same IP address - 172.18.0.1 for any user that connects. Proxy issue?

**Comment by SlvrEagle23** [comment] 2017-12-14 21:48
@kbysfm If you're on Icecast, this is a known issue (ticket #293) and is pending action on the part of the makers of Icecast-KH itself.

**Comment by kbysfm** [comment] 2017-12-14 21:51
@SlvrEagle23 unfortunately i'm on Shoutcast. I've been reading through #293 thinking it could help. Then again that's an Icecast problem.

**Comment by SlvrEagle23** [comment] 2017-12-14 21:58
@kbysfm I don't have any reports of that same issue happening on Shoutcast. The AzuraCast public demo server runs Shoutcast and proxies all traffic through the same nginx rules, and it shows the original and proper IP for users.

I've found that, when listening locally on my local dev Docker instance from the computer itself, it always reports as the Docker gateway IP (the one you mentioned). However, when listening on other computers pointed at that machine, the IP reports correctly.

**Comment by kbysfm** [comment] 2017-12-14 22:03
@SlvrEagle23 i may reboot the server and see what happens. There were a couple of networking changes that could have affected the system. I was able to remote into my PC at home and kick off the player as well as jump on LTE and the same IP is listed for all connections. If it's not one thing...

Out of curiosity, what OS is running on the demo server? 

Thanks!

**Comment by SlvrEagle23** [comment] 2017-12-14 22:04
@kbysfm Ubuntu 16.04 for both the traditional and Docker test servers.

For my local dev, I'm on ElementaryOS (which is downstream from 16.04 itself).

**Comment by kbysfm** [comment] 2017-12-14 22:05
If anything I could always punt and install Ubuntu 16.04 and install docker. Perhaps that will be the fix.

**Comment by surihost** [comment] 2017-12-14 23:35
I again have this same problem, no data on dashboard about current listeners and now playing
I have centos 7 with docker

**Comment by inetactief** [comment] 2017-12-15 10:20
I have the same problem no nowplaying and listeners, running on Centos 7. 
I update it 2 times. Restart the server. Try to check the cron.

**Comment by kbysfm** [comment] 2017-12-15 22:34
@SlvrEagle23 success! Installed Ubuntu 16.04, reinstalled docker version of AzuraCast on the mac mini, synchronization tasks are firing and real IPs are showing! Phew... Definitely not a fix, but a work around.

**Comment by inetactief** [comment] 2017-12-16 08:54
I add a extra streaming account now on SHOUTcast v2, same problem in dashboard.  Before i test it on Icecast. We use the not the default firewall of CentOS but Arno's Iptables Firewall. We try to disabled that (no firewall) and restart docker, but same problem. 
Let me know how to help you or send some log files

**Comment by kbysfm** [comment] 2017-12-17 13:56
@inetactief RHEL and CentOS are very similar and for that reason you may be experiencing the same issue that I was on RHEL. Perhaps CentOS and RHEL conflict with synchronization task for some reason. Which version of AzuraCast do you have installed? Traditional or Docker?

**Comment by inetactief** [comment] 2017-12-17 16:02
I have install Version v0.8.0-2017.12 Beta (Docker). When is check on VMware 6.5 i see 3 ips, 2 LAN ips  and 1 public ip address that i install for CentOS 7.

**Comment by kbysfm** [comment] 2018-01-02 16:54
@SlvrEagle23 my colleague and I are about to start narrowing down the RHEL / Ubuntu differences. Do you mind if I leave this ticket open to keep you up-to-date?

**Comment by inetactief** [comment] 2018-01-03 11:50
Yes please leave it open, and keep me up-to-date! 
Is there a update log of the versions? So i can check this... no i try update every 4 days..

**Comment by SlvrEagle23** [comment] 2018-01-03 19:45
@kbysfm Sure, keep us updated if you discover what's going on with RHEL/CentOS specifically.

@inetactief If you're following this thread, any changes to the code related to this ticket will appear inline with the comments. You can also see the specific code changes (and the issues they correspond to) that have been made by following the commit history: https://github.com/AzuraCast/AzuraCast/commits/master

**Comment by inetactief** [comment] 2018-01-11 10:48
Hi SlvrEagle23 do you have found something? We wil use it but waiting for to solve this isu.

**Comment by inetactief** [comment] 2018-02-01 11:55
No updates for the listeners updates and now playing?

**Comment by SlvrEagle23** [comment] 2018-02-01 11:58
@inetactief There are no updates on this issue. If there were updates, as I said, you'll see them on this page.

I would appreciate if people assisted in helping try to diagnose the cause of the problems, rather than just asking why I haven't fixed them myself, when I'm still unsure of what the problem is in the first place, nor any steps I can take on my end to resolve it.

**Comment by SlvrEagle23** [comment] 2018-02-03 15:36
I've been working on investigating this issue further, and have spun up a test server running the latest version of CentOS. I was able to pull down the Docker installer without issue, pull down the AzuraCast docker images, install the system and get the station up and running. I've also been able to observe that cron tasks are running perfectly on this test instance.

If there's something preventing CentOS installations from working correctly, it's possible that it might've been fixed by a recent change to the way AzuraCast installations are handled, in that the entire codebase for the system is now contained within the Docker image itself, rather than pulled down by the user and mounted as a volume. If there were permission issues involved with using CentOS, this would've removed them as a class of error.

At this point, though, there's nothing further I can do to test the issue, as my tests show that AzuraCast is fully compatible with the latest version of CentOS, with no modifications required.

If anyone else has any insight into this issue and would like to reopen this issue for further evaluation, please respond to this ticket and mention me directly.

**Closed by SlvrEagle23** 2018-02-03 15:36 UTC
Labels: bug

**Comment by inetactief** [comment] 2018-02-23 10:52
Hi SlvrEagle thank you! I do update and look like the listener counter works again and the playlist. Not on every grafic do work,"example the "Listeners Per Station and Listeners Across All Stations on the dashboard. 
What the best way to remove AzuraCast Docker and reinstall? I hope i do not install centOS again.

**Comment by inetactief** [comment] 2018-02-27 10:41
I use docker-uninstall.sh and afther that.. install : 
docker-compose pull
docker-compose run --rm cli azuracast_install
docker-compose up -d
Setup the server. And playlist works fine and listener count on dashboard
But when we log on the station the page 1 and page /reports/listeners do not update (google maps works)
We see on page /admin by SYNCHRONIZATION TASKS Now Playing Data
Jan 1, 1970 12:00am UTC
586 months ago

1-Minute Sync
Song Requests Queue
Jan 1, 1970 12:00am UTC
586 months ago

5-Minute Sync
Check Media Folders
Jan 1, 1970 12:00am UTC
586 months ago
How to enabled automatic SYNCHRONIZATION TASKS?

**Comment by inetactief** [comment] 2018-02-27 10:44
When we run by hand SYNCHRONIZATION TASKS the listeners show in google maps.
I hope someone can help. I check the crontab -e But it is empty

**Comment by SlvrEagle23** [comment] 2018-02-27 15:16
@inetactief There is a specific Docker container called "cron" that runs all the scheduled jobs, including the synchronizations. I'm not sure what the problem is, but something is preventing that from running correctly on CentOS. That's part of what we have to look into here.

**Comment by inetactief** [comment] 2018-02-27 16:09
Okay let me know what i must check for you if it is there or running. 
When i do (show all containers)  docker ps -l i see something like cron:
                                                                                                                                      azuracast_cron
8a1f532af386        azuracast/azuracast_nginx:latest      "nginx -g 'daemon of…"   6 hours ago         Up 6 hours               0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp
