### ISSUE TITLE
Glitch after uploading and editing media during playback

### ISSUE THREAD

**Issue by gammaw** [AzuraCast/AzuraCast#1268] opened 2019-03-08 17:44 UTC
Hi, 

I had the following issue: a song was being played, the right metadata was shown (via API and also on the radio's interface). I uploaded another media in the meanwhile and edited it after upload (title and cover added) and saved it. All seemed all right but then I realized that Azuracast started showing invalid metadata (no title, no artwork; see picture). The web API didn't send the correct data either. 

Unfortunately, restarting the radio wasn't an option because it was a one-hour show that we couldn't restart from the beginning (because of the timetable). 

Any idea why it happened? Does Azuracast not tolerate uploading and editing media during playback (i.e., restart may be necessary)? 

Thanks, 

Peter

![image](https://user-images.githubusercontent.com/28865986/54044968-9af10300-41d0-11e9-9efb-2ecb1b702e78.png)

**Comment by SlvrEagle23** [comment] 2019-03-09 22:16
@gammaw This shouldn't be caused by a sort of read-write race condition between AzuraCast and Liquidsoap, because Liquidsoap's reads are rather sporadic and shouldn't lock up against Azura's.

If you manually run the Now Playing sync task, does it provide any sort of error message? Did any of the related services actually fail?

**Comment by gammaw** [comment] 2019-03-10 01:15
I didn't run the Now Playing task. I didn't now about it to be honest. But now I found it on the web interface. What is it good for? 

I don't know which service failed, the player was usable (the radio was on air) but the song's title was gone during playback (although I changed the title of another song).

**Comment by SlvrEagle23** [comment] 2019-03-10 04:47
@gammaw There are a set of routine ("cron") tasks that happen under the hood every 15 seconds, minute, 5 minutes and hour in AzuraCast to help keep things clean, process unprocessed media, etc.

The "Now Playing" sync is the task that's run every 15 seconds and that checks for changes to the currently playing song or the listener count, then updates the database and clients hitting the `/api/nowplaying` endpoints.

Manually running it in the administration page will do that same check except in the foreground, so you can immediately see any errors that come up.

**Comment by gammaw** [comment] 2019-03-21 18:36
@SlvrEagle23 the error seems to be deterministic. Every time a song is running and I upload, edit and save a (big) file during playback, the metadata in Azuracast gets lost. After it happens the nowplaying API returns something like this:

`{"id":"...","text":"Stream Offline","artist":"","title":"","album":"","lyrics":"","art":"...\/static\/img\/generic_song.jpg","custom_fields":[]}}` (Dots is some data I deleted in the example.)

I manually ran the Now Playing task, it didn't return any error. 

Any idea?

**Comment by Vaalyn** [comment] 2019-03-22 11:17
Can you check for any errors or other information that may be related to this issue in the Liquidsoap and also AzuraCast Application logs? You can find them in the System Administration.

**Comment by gammaw** [comment] 2019-03-24 15:25
@Vaalyn the glitch happened again and I found following error in the Azuracast Application Log> 

`[2019-03-24 15:18:29] AzuraCast.ERROR: NowPlaying adapter error: Request returned status 400: <b>mount does not exist</b>  [] {"station":{"id":1,"name":"[NAME OF THE RADIO]"}}`

The problem happened again, while a custom playlist was playing a long song, after we uploaded a new song (around 150MB). edited metadata of it and saved it (took long time, as usual).

**Comment by gammaw** [comment] 2019-04-02 06:24
@Vaalyn @SlvrEagle23 we had this issue a couple of times again but this time when a standard Azuracast playlist (general rotation) was being played. This is the error message I find in the Liquidsoap log:  

```
2019/04/02 06:14:14 [xyz_radio_local_1:2] Error while sending data: could not write data to host: Broken pipe in write()!
2019/04/02 06:14:14 [xyz_radio_local_1:3] Closing connection...
2019/04/02 06:14:14 [xyz_radio_local_1:3] Will try to reconnect in 3.00 seconds.
2019/04/02 06:14:18 [xyz_radio_local_1:3] Connecting mount /radio.mp3 for source@127.0.0.1...
2019/04/02 06:14:18 [xyz_radio_local_1:3] Connection setup was successful.
2019/04/02 06:14:29 [clock.wallclock_main:2] We must catchup 5.54 seconds!
2019/04/02 06:15:16 [clock.wallclock_main:2] We must catchup 3.65 seconds!
```

Azuracast cannot recover from this error state except via station restart (Utilities -> Restart Broadcasting). We're running a docker 0.9.4.1 installation. 

Any idea?

**Comment by SlvrEagle23** [comment] 2019-04-02 21:41
@gammaw The more I look at this issue, the more I think this has to do with the fact that writing metadata to a large file (like a 150MB MP3) is somewhat CPU intensive for a small portion of time on account of the `getid3` library we use. The brief heavy CPU load is causing Liquidsoap's internal counters to go out of whack, causing the "we must catchup" problem to cascade down and cause longer-term failure on the station.

I suspect this may be a sign of under-allocation of resources on the server. If the server's running close to its current capacity already, then some of the routine tasks involved in maintaining the station inside AzuraCast may throw it into a state where it can't maintain stable broadcasting.

There's no evidence from any of the logs that I'm seeing that this is being caused by a specific interaction between AzuraCast's metadata editing component and Liquidsoap, or that this only happens when editing a file that Liquidsoap is itself currently playing.

**Comment by Vaalyn** [comment] 2019-05-23 16:07
Closing this issue as it was probably caused by the same underlying issue as issue 1288 which was resolved by changing faulty hardware.

**Closed by Vaalyn** 2019-05-23 16:07 UTC
Labels: error
