### ISSUE TITLE
Music search is case sensitive

### ISSUE THREAD

**Issue by RemBdev** [AzuraCast/AzuraCast#748] opened 2018-08-25 14:45 UTC
**Installation method**
Traditional

**Host OS (for Docker installations)**
Ubuntu 16.04

**Describe the bug**
Search in the music collection doesn't work well. If "2 unlimited - No limit" is in the music collection, and i search on it. "No results found!" is returned. "2 Unlimited" works.

**Screenshots**
![4bbfd4208dc73710822635bd2d813521](https://user-images.githubusercontent.com/29834979/44619332-0141b400-a885-11e8-9ec9-e8f725693630.gif)

**Comment by SlvrEagle23** [comment] 2018-08-26 05:11
Closing both because it's a duplicate of #663, but because both issues were just resolved in the latest update, which changes the MariaDB collation of the database to `utf8mb4_general_ci`, which returns case-insensitivity to the search results.

**Closed by SlvrEagle23** 2018-08-26 05:11 UTC
