### ISSUE TITLE
Unable to skip songs when a Remote URL(Direct Stream) Playlist is scheduled

### ISSUE THREAD

**Issue by nunotfc** [AzuraCast/AzuraCast#5490] opened 2022-06-11 11:58 UTC
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

344220d (2022-06-11 11:00) • Docker • PHP 8.1

### What happened?

hello, i click skip song in my control panel and it does nothing. if you want some log, please point me in right direction, and i shurely provide it.

EDITED BY ITSMITCH

I've checked this users installation and have concluded that the API calls do indeed happen, but nothing appears to happen on the Liquidsoap side of things. It may require a inspection by a senior developer to determin the root cause of this. 

One important thing I note that there's no 
`2022/06/30 21:33:27 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/nextsong' with body: ` logs at all when a song is skipped. 

API call ref: {"success":true,"message":"Música ignorada.","formatted_message":"Música ignorada."} (Portugese) 
but absolutely nothing is happening in the Liquidsoap logs, 

### Relevant log output
```
Skip sent at 
{"success":true,"message":"Música ignorada.","formatted_message":"Música ignorada."}  
Request URL: https://stream.renovagames.com/api/station/1/backend/skip
Request Method: POST
Status Code: 200 
Remote Address: 

Liquidsoap Logs before skip and after 
2022/06/30 18:23:48 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/feedback' with body: {
2022/06/30 18:23:48 [lang:3]   "song_id": "deb68bf7ef1743b3cd2315f2bbd917f8",
2022/06/30 18:23:48 [lang:3]   "playlist_id": "6",
2022/06/30 18:23:48 [lang:3]   "media_id": "319"
2022/06/30 18:23:48 [lang:3] }
2022/06/30 18:23:48 [lang:3] API feedback - Response (200): true
```

**Comment by SC2Mitch** [comment] 2022-06-11 13:10
Should be fixed in the latest rolling, can you confirm? @nunotfc

**Comment by nunotfc** [comment] 2022-06-11 13:16
a3b0ee5 (2022-06-11 12:21) • Docker • PHP 8.1
nothing changed.

**Comment by SC2Mitch** [comment] 2022-06-11 13:19
When you skip the song, check your Liquidsoap log and post it here, contact me on Discord if you need further help.

**Comment by nunotfc** [comment] 2022-06-11 13:24
2022/06/11 10:21:42 [next_song:3] Prepared "/var/azuracast/stations/renovaradio/media/gerais/Marshmello x Jonas Brothers - Leave Before You Love Me (Official Music Video).mp3" (RID 35).
[mp3float @ 0x7f587401a080] Could not update timestamps for skipped samples.
2022/06/11 10:21:42 [cue_next_song:3] Cueing in...
2022/06/11 10:21:42 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/nextsong' with body: 
2022/06/11 10:21:42 [lang:3] API nextsong - Response (200): annotate:title="Promo",artist="RenovaRadio",duration="1.00",song_id="35e36061fd81438ce8331db3712dd422",media_id="1876",liq_amplify="0.00dB",jingle_mode="true":media:promos/renovaradiobira.mp3
[mp3 @ 0x7f586c01b840] Estimating duration from bitrate, this may be inaccurate
[mp3 @ 0x7f586c01b840] Estimating duration from bitrate, this may be inaccurate
2022/06/11 10:21:42 [cross_0:3] Analysis: -17.665891dB / -23.377106dB (4.96s / 4.96s)
2022/06/11 10:21:53 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/feedback' with body: {
2022/06/11 10:21:53 [lang:3]   "song_id": "b03eb298ee6d9f6685a60d2273193044",
2022/06/11 10:21:53 [lang:3]   "playlist_id": "6",
2022/06/11 10:21:53 [lang:3]   "media_id": "828"
2022/06/11 10:21:53 [lang:3] }
2022/06/11 10:21:53 [lang:3] API feedback - Response (200): true

**Comment by nunotfc** [comment] 2022-06-11 13:31
how i can contact you on discord? i doesnt see anything unusual i the logs.

**Comment by nunotfc** [comment] 2022-06-30 18:29
updated for latest rolling. nothing changed.

**Comment by ItsMitchh** [comment] 2022-06-30 19:54
We're going to somehow need more information than nothing changed. I'm unable to reproduce this locally.

**Comment by ItsMitchh** [comment] 2022-06-30 21:35
I've conducted a look at your machine and updated the issue, flagging for the team to have a look if they got time.

**Comment by MarkWasley** [comment] 2022-07-01 21:22
As per the discussions on Discord, the Skip Song button is also not working for me in "rare cases". The rare cases are when a Remote URL (direct stream) playlist is scheduled. Both @nunotfc and I have disabled them and this allows skipping. I suggest updating the title of this issue to reflect the "rare cases" are when Remote URL playlists are scheduled as, as far as we know, this is the only circumstance where the Skip Song button doesn't work. I suggest it could be caused by the code generated, or position, of relevant lines in the Liquidsoap configuration file.

**Comment by SlvrEagle23** [comment] 2022-07-07 04:13
Fixed in latest Rolling Release.

**Closed by SlvrEagle23** 2022-07-07 04:13 UTC
Labels: bug, unexpected behaviour, rolling-release
