### ISSUE TITLE
does not show which loses the songs

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#304] opened 2017-12-01 08:43 UTC
does not show which loses the songs for the proxy, if it works without a proxy then everything is displayed and does not consider unique users.

**Comment by SlvrEagle23** [comment] 2017-12-01 22:04
I'm not 100% sure I understand the text of this issue, but it seems to be a duplicate of #293, which is currently in the process of being resolved.

**Closed by SlvrEagle23** 2017-12-01 22:04 UTC
