### ISSUE TITLE
Behind a Proxy Redirect on Port behind the proxy

### ISSUE THREAD

**Issue by Optischa** [AzuraCast/AzuraCast#7116] opened 2024-05-16 13:22 UTC
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Latest

### What happened?

If you use a Ngnix proxy and are on the station view of a station and then press F5 to reload, you will be redirected to the port where the Azuracast frontend is running. This only happens on the station side. On all other pages it works that you stay on the URL without port.

**Comment by LordHelmchen666** [comment] 2024-05-18 14:07
happens to me also when i turn on "Prefer Browser URL" in system settings.
Then in 
- Dashboard the Albumart is not shown because the port is added (https://stream.eisradio.de:12443/api/station/eisradio/art/86e5ea4f4f1203e086d5a136)
- In some links port added
![Screenshot_20240518_155527](https://github.com/AzuraCast/AzuraCast/assets/43477041/fdeb8be0-e815-47c7-9343-e0770da53250)
- Waveforms not visible
![Screenshot_20240518_155759](https://github.com/AzuraCast/AzuraCast/assets/43477041/0b7793e9-7d4f-4ad2-b9e8-a708db3df63b)
- Restart Broadcasting redirects to https://stream.eisradio.de:12443/station/1

Turning off "Prefer Browser URL" everything is working. But showing in Dashbord
![Screenshot_20240518_160211](https://github.com/AzuraCast/AzuraCast/assets/43477041/23f03eea-854f-4b5a-aa7e-4d56580faec1)

For your information. I am using Virtualmin, Apache, Azuracast Docker.


```
# Proxy to Azuracast Port 12443
SSLProxyEngine on
ProxyRequests Off
ProxyPreserveHost On
SSLProxyVerify None
SSLProxyCheckPeerCN Off
SSLProxyCheckPeerName Off
ProxyPass / https://0.0.0.0:12443/
ProxyPassReverse / https://0.0.0.0:12443/
ProxyPassMatch "^(/listen/eisradio|/radio/8000)/(.*)$" "http://0.0.0.0:8000/$1?$args"
ProxyPassReverse  "^(/listen/eisradio|/radio/8000)/(.*)$" "http://0.0.0.0:8000/$1?$args"
ProxyPassMatch "^(/webdj/eisradio|/radio/8005)(/?)(.*)$" "http://0.0.0.0:8005/$2"
ProxyPassReverse  "^(/webdj/eisradio|/radio/8005)(/?)(.*)$" "http://0.0.0.0:8005/$2"
```

**Comment by wegGehamstert** [comment] 2024-05-18 14:57
Yeah, that's the same problem that we have. All of the mount points will no longer work because it's routing to a new port.
(@Optischa is working with me on the same station)

**Comment by henkiewie** [comment] 2024-05-20 12:06
Turning off preferered browser worked for me also. I got connection refused in the (f12) browser console for the picture and the mp3 sound on all stations when using the default public page. Since my local domain is also in NPM I use that as base url. The yellow message only shows up when going to the local IP. Strangely going straight to the `[extranalURL]/listen/[stationname]/radio.mp3` the sound kept working. Glad I found this.

**Comment by henkiewie** [comment] 2024-05-21 05:47
definitely something wrong/changed with whats behind preferred browser URL option. My browser gives connection refused
<img width="880" alt="Screenshot 2024-05-21 at 07 34 02" src="https://github.com/AzuraCast/AzuraCast/assets/74558874/d71c196c-d364-414d-bc7c-e8bc28a83bef">
 to the music stream (radio.mp3) and pictures /api/.... It hink because the inside portnumber is added to the URL?
Turning it off gives the local (inside) ipaddress or URL. depending on the site base URL.
Hope it can be updated in the next release.

**Comment by henkiewie** [comment] 2024-05-22 08:25
Because I was not sure when this "bug" was introduced I dit a rollback to 0.19.4 `./docker.sh rollback 0.19.4` in /var/azuracast and everything is working as expected with the preferred browser URL on.

**Comment by wegGehamstert** [comment] 2024-05-22 11:01
> Because I was not sure when this "bug" was introduced I did a rollback to 0.19.4 `./docker.sh rollback 0.19.4` in /var/azuracast and everything is working as expected with the preferred browser URL on.

That's the same thing that i noticed too. At some point, there was a change betweeten 0.19.4 and 0.19.5 wich let to this issue. I will search in the commits for the exact point where it changed..

**Comment by wegGehamstert** [comment] 2024-05-22 12:28
I was able to get the timeframe betweeten 0.19.4 and 0.19.5 

05.01.2024 (0.19.4)
20.02.2024 (0.19.5)

Now i need to track down that commit that changed that behavior

**Comment by BusterNeece** [comment] 2024-05-22 12:30
I'll take a look too :)

**Comment by BusterNeece** [comment] 2024-05-22 14:06
Alright, so I looked into this and I have some good news and some bad news.

The bad news is that the fix from 0.19.4 and 0.19.5 isn't actually a bug per se. It just fixed things such that if you actually do use AzuraCast on a non-standard port, the application recognized that fact and updated your base URL accordingly if "Prefer Browser URL" was turned on. This is desirable in cases where nonstandard ports are used intentionally and the application is served out to the web on those ports.

However, in my investigation I also noticed that we don't currently honor the `X-Forwarded-Port` and `X-Forwarded-Host` HTTP headers. Those headers are sent by "upstream" proxies in order to let you know what the original URL that the user requested was (which we otherwise would have no way of knowing).

As of the latest version of the Rolling Release channel, we now honor those headers correctly and will update the base URL to reflect them if they're present.

If you're setting up your own custom reverse proxy in front of AzuraCast, this may mean that you have to start actually setting that header. In nginx, you can do so with these config lines:

```
# Check if a X-Forwarded-Proto header (set by reverse-proxy) is already present. If not take the scheme used to call our nginx server.
map $http_x_forwarded_proto $x_forwarded_proto {
    default $http_x_forwarded_proto;
    ""      $scheme; # Note that if the reverse-proxy does not add a X-Forwarded-Proto header, it may be incorrect if the protocol used by the reverse proxy is not the same as the one on which your nginx server is listening. In this case you have no solution than harcode the correct value.
}

# Check if a X-Forwarded-Host header (set by reverse-proxy) is already present. If not take the value of the 'Host' header.
map $http_x_forwarded_host $x_forwarded_host {
    default $http_x_forwarded_host;
    ""      $http_host;
}

# Set the default port of each scheme/protocol (80 for http, 443 for https)
map $x_forwarded_proto $default_http_port {
    default 80;
    "https" 443;
}

# Extract the real port of the client request url (unfortunatly nginx has no variable to get this info)
map $http_host $request_port {
    default                 $default_http_port; # If port not explicitely defined in url take the default one associated to the calling scheme/protocol (80 for http, 443 for https)
    "~^[^\:]+:(?<p>\d+)$"   $p;
}

# Check if a X-Forwarded-Port header (set by reverse-proxy) is already present. If not take the port from the client request url
map $http_x_forwarded_port $x_forwarded_port {
    default $http_x_forwarded_port;
    ""      $request_port;
}

proxy_set_header X-Forwarded-Proto $x_forwarded_proto;
proxy_set_header X-Forwarded-Host $x_forwarded_host;
proxy_set_header X-Forwarded-Port $x_forwarded_port;
```

**Comment by henkiewie** [comment] 2024-05-22 14:26
OK. Thanks for the deep dive 🤿 . Now I will have to dive into how these headers are set in the
 nginx proxy manager I am using. I believe I am not the only one 😄.
My proxy is using the standard ports I changed the port numbers in the Azura docker container because they all run on the same machine.
There is an option to add your own headers, but they look a bit different then your example nginx config.
<img width="505" alt="Screenshot 2024-05-22 at 16 17 31" src="https://github.com/AzuraCast/AzuraCast/assets/74558874/b52788e7-24f5-40a4-91dd-3785bf74ce13">
I am already using the custom location `/login` moving to the public page to hide the login page.
I will maybe ask for some help in the github NPM discussions.
Regards,
Henk

**Comment by BusterNeece** [comment] 2024-05-22 14:30
@henkiewie It might actually be sending those headers already...check and see if updating to the latest Rolling Release fixes things; if so then it's already sending those headers and you're good to go without any modifications.

Also, just to clarify something, but "NPM" is the name of another very common piece of software used in our development process (Node Package Manager) so you may want to spell out that you're referring to "nginx proxy manager" instead just to avoid confusion.

**Comment by henkiewie** [comment] 2024-05-22 14:37
> @henkiewie It might actually be sending those headers already...check and see if updating to the latest Rolling Release fixes things; if so then it's already sending those headers and you're good to go without any modifications.
> 
> Also, just to clarify something, but "NPM" is the name of another very common piece of software used in our development process (Node Package Manager) so you may want to spell out that you're referring to "nginx proxy manager" instead just to avoid confusion.

I will try that first. And yes I mean Nginx Proxy Manager. 😆. I did not know of the existence of the package that's included in Azuracast.

**Comment by henkiewie** [comment] 2024-05-22 14:47
> > @henkiewie It might actually be sending those headers already...check and see if updating to the latest Rolling Release fixes things; if so then it's already sending those headers and you're good to go without any modifications.
> > Also, just to clarify something, but "NPM" is the name of another very common piece of software used in our development process (Node Package Manager) so you may want to spell out that you're referring to "nginx proxy manager" instead just to avoid confusion.
> 
> I will try that first. And yes I mean Nginx Proxy Manager. 😆. I did not know of the existence of the package that's included in Azuracast.

The rolling release adds the port number in 0.9.4 it wasn't not there.

**Comment by henkiewie** [comment] 2024-05-22 15:20
> So it dosent fix the issue for you?
No it did not it gave the same error as in the stable release It added the internal portnumber to the public page for the picture and and radio.mp3 as in my first post. In 0.9.4  So the public page showing but without the picture and the play button does not work.

**Comment by henkiewie** [comment] 2024-05-22 15:32
> Are you on the rolling release? I don't get your problem. And do you mean the version number 0.19.4? I hope that your not on 0.9.4

Yes I switched to the rolling release and my problem was back. Switching back to 0.19.4 😄  makes it working again. For me the problem is clear in the 0.19.4 its not adding any portnumber to the picture and radio.mp3. Thats why it was working for me.

**Comment by wegGehamstert** [comment] 2024-05-22 15:40
> > Are you on the rolling release? I don't get your problem. And do you mean the version number 0.19.4? I hope that your not on 0.9.4
> 
> Yes I switched to the rolling release and my problem was back. Switching back to 0.19.4 😄 makes it working again. For me the problem is clear in the 0.19.4 its not adding any portnumber to the picture and radio.mp3. Thats why it was working for me.


Thats weird, i think the problem is then on your side? We will test it in a few hours and will report if it work.

**Comment by BusterNeece** [comment] 2024-05-22 16:46
@henkiewie Let's try this again; I've loosened the rules for what will remove the port number so that more proxies will set it off...try updating and it should kick in now.

**Comment by henkiewie** [comment] 2024-05-22 16:53
> @henkiewie Let's try this again; I've loosened the rules for what will remove the port number so that more proxies will set it off...try updating and it should kick in now.

Just when i was wondering why the port should be respected because for me and many docker users its the main reason for using a proxy. You Already came with the solution no more connection refused in my setup. @BusterNeece 🚀 
          // A vast majority of reverse proxies will be proxying to the default web ports, so
          // if *any* X-Forwarded-* value is set, unset the port in the request.

**Comment by Optischa** [comment] 2024-05-22 16:56
WoRkInGß Or WhAt

**Comment by henkiewie** [comment] 2024-05-22 16:57
> WoRkInGß Or WhAt



> WoRkInGß Or WhAt

Yes it is. On the rolling release that is.

**Comment by wegGehamstert** [comment] 2024-05-22 16:58
> Yeah, that's the same problem that we have. That's the reason why we even encountered this bug and why we turned the "Prefer Browser URL" off. If turned on, all of the mount points will no longer work and all of the other stuff that @LordHelmchen666 mentioned is not working because it's routing to a new port. (@Optischa is working with me on the same station)
> 
>  2024-05-18.17-01-03.mp4 
> The only option is then to turn the "Prefer Browser URL" off, but then you get the big yellow box with the warning. So to make this clear, it dosent bother me that we have this setting off but it's very annoying that a reload on the overview page of a station will route you do the URL with the Port inside

Is this issue also fixed?

**Comment by henkiewie** [comment] 2024-05-22 17:16
> Is the issue that @Optischa wrote, also fixed? The problem that the reloading the stationssite directs you to the URL with the port?

I did not test that. But for me a refresh still gives me the picture and the stream, So no inside portnumber in the url for the picture and the stream

**Comment by LordHelmchen666** [comment] 2024-05-22 17:28
Works fine here. could not find an issue anymore.

**Closed** 2024-05-22 18:03 UTC
Labels: needs investigation

**Comment by wegGehamstert** [comment] 2024-05-22 20:34
Works for me too! Thank you so much for your fix!
