### ISSUE TITLE
Song length

### ISSUE THREAD

**Issue by AnUnknowsTygerosy** [AzuraCast/AzuraCast#1405] opened 2019-04-05 12:19 UTC
**Installation method**

Bare-metal

**Host OS (for Docker installations)**

Ubuntu 16.04

**Describe the bug**

I installed latest update and song length stopped working. All songs have 00:00:00 length. All worked fine before last update (v0.9.4.2)

**Screenshots**

![image](https://user-images.githubusercontent.com/39670563/55626953-4039cf80-57ad-11e9-9f5a-df01479be353.png)
![image](https://user-images.githubusercontent.com/39670563/55626978-53e53600-57ad-11e9-8159-b9ae25cd8782.png)
![image](https://user-images.githubusercontent.com/39670563/55627146-c229f880-57ad-11e9-93e3-ab5d5c5a582e.png)

**Comment by AnUnknowsTygerosy** [comment] 2019-04-05 12:38
And.. Its not showing next playing song
![image](https://user-images.githubusercontent.com/39670563/55628250-83e20880-57b0-11e9-821c-3c24d3422298.png)

**Comment by afonsosantos** [comment] 2019-04-05 18:00
> **Installation method**
> 
> Bare-metal
> 
> **Host OS (for Docker installations)**
> 
> Ubuntu 16.04
> 
> **Describe the bug**
> 
> I installed latest update and song length stopped working. All songs have 00:00:00 length. All worked fine before last update (v0.9.4.2)
> 
> **Screenshots**
> 
> ![image](https://user-images.githubusercontent.com/39670563/55626953-4039cf80-57ad-11e9-9f5a-df01479be353.png)
> ![image](https://user-images.githubusercontent.com/39670563/55626978-53e53600-57ad-11e9-8159-b9ae25cd8782.png)
> ![image](https://user-images.githubusercontent.com/39670563/55627146-c229f880-57ad-11e9-93e3-ab5d5c5a582e.png)

Some musics from my station doesn't show the duration also.

**Comment by AnUnknowsTygerosy** [comment] 2019-04-06 07:23
So.. how to fix it?

**Comment by SlvrEagle23** [comment] 2019-04-06 07:26
@AnUnknowsTygerosy We'll need to see logs from Liquidsoap; I suspect that its "feedback" mechanism with AzuraCast isn't working correctly. Can you send us the relevant logs?

Also, sometimes visiting Utilities > Restart Broadcasting regenerates the necessary identifying keys and fixes the issue.

**Comment by AnUnknowsTygerosy** [comment] 2019-04-06 07:33
Okay.. i will try it. And logs.. I will send it, when I will be on pc.

**Comment by afonsosantos** [comment] 2019-04-06 10:08
Can i send them too? It's happening to me also.

**Comment by AnUnknowsTygerosy** [comment] 2019-04-06 11:49
My logs:
```2019/04/06 11:46:49 [playlist_normal:3] Finished with "/var/azuracast/stations/cloudradio/media/Normal/ellie_goulding_a_diplo_swae_lee_-_close_to_me.mp3".
2019/04/06 11:46:49 [playlist_normal:3] Prepared "/var/azuracast/stations/cloudradio/media/Normal/bad_bunny_a_drake_-_mia.mp3" (RID 3).
2019/04/06 11:46:50 [lang:3] AzuraCast Feedback Response: OK
2019/04/06 11:46:52 [lang:3] AzuraCast Raw Response: 
2019/04/06 11:46:52 [lang:3] AzuraCast Error: Delaying subsequent requests...
2019/04/06 11:46:58 [lang:3] AzuraCast Raw Response: 
2019/04/06 11:46:58 [lang:3] AzuraCast Error: Delaying subsequent requests...
2019/04/06 11:47:03 [lang:3] AzuraCast Raw Response: 
2019/04/06 11:47:03 [lang:3] AzuraCast Error: Delaying subsequent requests...
2019/04/06 11:47:09 [lang:3] AzuraCast Raw Response: 
2019/04/06 11:47:09 [lang:3] AzuraCast Error: Delaying subsequent requests...
2019/04/06 11:47:14 [lang:3] AzuraCast Raw Response: 
2019/04/06 11:47:14 [lang:3] AzuraCast Error: Delaying subsequent requests...
2019/04/06 11:47:20 [lang:3] AzuraCast Raw Response: 
2019/04/06 11:47:20 [lang:3] AzuraCast Error: Delaying subsequent requests...
2019/04/06 11:47:25 [lang:3] AzuraCast Raw Response: 
2019/04/06 11:47:25 [lang:3] AzuraCast Error: Delaying subsequent requests...
2019/04/06 11:47:31 [lang:3] AzuraCast Raw Response: 
2019/04/06 11:47:31 [lang:3] AzuraCast Error: Delaying subsequent requests...
2019/04/06 11:47:36 [lang:3] AzuraCast Raw Response: 
2019/04/06 11:47:36 [lang:3] AzuraCast Error: Delaying subsequent requests...
2019/04/06 11:47:41 [lang:3] AzuraCast Raw Response: 
2019/04/06 11:47:41 [lang:3] AzuraCast Error: Delaying subsequent requests...
2019/04/06 11:47:47 [lang:3] AzuraCast Raw Response: 
2019/04/06 11:47:47 [lang:3] AzuraCast Error: Delaying subsequent requests...
2019/04/06 11:47:53 [lang:3] AzuraCast Raw Response: 
2019/04/06 11:47:53 [lang:3] AzuraCast Error: Delaying subsequent requests...
2019/04/06 11:47:58 [lang:3] AzuraCast Raw Response: 
2019/04/06 11:47:58 [lang:3] AzuraCast Error: Delaying subsequent requests...
2019/04/06 11:48:04 [lang:3] AzuraCast Raw Response: 
2019/04/06 11:48:04 [lang:3] AzuraCast Error: Delaying subsequent requests...

**Comment by SlvrEagle23** [comment] 2019-04-06 21:35
@AnUnknowsTygerosy This means either you have no music in your general rotation playlists, or AzuraCast itself is running into an error.

If it's the latter, you'll see that in the AzuraCast application log, which you can view from the global "Administration" > "Log Viewer" page.

**Comment by afonsosantos** [comment] 2019-04-06 23:36
> @AnUnknowsTygerosy This means either you have no music in your general rotation playlists, or AzuraCast itself is running into an error.
> 
> If it's the latter, you'll see that in the AzuraCast application log, which you can view from the global "Administration" > "Log Viewer" page.

In my case, the musics that don't show it's durstion are in the only playlist that i've got.

**Comment by SlvrEagle23** [comment] 2019-04-07 00:07
@afonsosantos You should also post your AzuraCast application log (same instructions, via the global administration and then "Log Viewer") as it may have some additional information about what's going on.

**Comment by afonsosantos** [comment] 2019-04-07 11:31
> @afonsosantos You should also post your AzuraCast application log (same instructions, via the global administration and then "Log Viewer") as it may have some additional information about what's going on.

Hi,

**Here is the Liquidsoap log:**

```
2019/04/07 11:27:04 >>> LOG START
2019/04/07 11:27:04 [main:3] Liquidsoap 1.3.6
2019/04/07 11:27:04 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.4.1 dtools=0.4.1 duppy=0.8.0 cry=0.6.1 mm=0.4.0 ogg=0.5.2 vorbis=0.7.1 opus=0.1.2 mad=0.4.5 flac=0.1.4 flac.ogg=0.1.4 dynlink=[distributed with Ocaml] lame=0.3.3 fdkaac=0.2.1 taglib=0.3.3 ssl=0.5.7 camomile=1.0.1 faad=0.4.0
2019/04/07 11:27:04 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
2019/04/07 11:27:04 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2019/04/07 11:27:04 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2019/04/07 11:27:04 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2019/04/07 11:27:04 [decoder:3] Method "MAD" accepted "/usr/local/share/icecast/web/error.mp3".
2019/04/07 11:27:04 [threads:3] Created thread "generic queue #1".
2019/04/07 11:27:04 [threads:3] Created thread "generic queue #2".
2019/04/07 11:27:04 [threads:3] Created thread "non-blocking queue #1".
2019/04/07 11:27:04 [threads:3] Created thread "non-blocking queue #2".
2019/04/07 11:27:04 [harbor:3] Adding mountpoint '/' on port 8005
2019/04/07 11:27:04 [playlist_jingles:3] Loading playlist...
2019/04/07 11:27:04 [playlist_jingles:3] No mime type specified, trying autodetection.
2019/04/07 11:27:04 [playlist_jingles:3] Playlist treated as format application/x-mpegURL
2019/04/07 11:27:04 [playlist_jingles:3] Successfully loaded a playlist of 6 tracks.
2019/04/07 11:27:04 [playlist_msicas:3] Loading playlist...
2019/04/07 11:27:04 [playlist_msicas:3] No mime type specified, trying autodetection.
2019/04/07 11:27:04 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/radioafonsosantos/media/Jingles/Outros/jingle_06.mp3".
2019/04/07 11:27:04 [playlist_msicas:3] Playlist treated as format application/x-mpegURL
2019/04/07 11:27:04 [playlist_msicas:3] Successfully loaded a playlist of 138 tracks.
2019/04/07 11:27:04 [single_6447:3] "/usr/local/share/icecast/web/error.mp3" is static, resolving once for all...
2019/04/07 11:27:04 [playlist_jingles:3] Prepared "/var/azuracast/stations/radioafonsosantos/media/Jingles/Outros/jingle_06.mp3" (RID 2).
2019/04/07 11:27:04 [radioafonsosantos_local_1:3] Connecting mount /radio-128.mp3 for source@127.0.0.1...
2019/04/07 11:27:04 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/radioafonsosantos/media/Jingles/Outros/jingle_04.mp3".
2019/04/07 11:27:04 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/radioafonsosantos/media/M\195\186sicas/m-24_-_final_song.mp3".
2019/04/07 11:27:04 [radioafonsosantos_local_1:3] Connection setup was successful.
2019/04/07 11:27:04 [radioafonsosantos_local_2:3] Connecting mount /radio-64.mp3 for source@127.0.0.1...
2019/04/07 11:27:04 [lang:3] AzuraCast Raw Response: annotate:title="Já Decidi",artist="DJ Ademar, Boy Teddy",duration="233.",song_id="799fa519eccc0c277641cc15cfeefa86",media_id="38",genre="38",playlist_id="2":/var/azuracast/stations/radioafonsosantos/media/Músicas/dj_ademar-2C_boy_teddy_-_ja_decidi.mp3
2019/04/07 11:27:04 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/radioafonsosantos/media/M\195\186sicas/dj_ademar-2C_boy_teddy_-_ja_decidi.mp3".
2019/04/07 11:27:04 [radioafonsosantos_local_2:3] Connection setup was successful.
2019/04/07 11:27:04 [threads:3] Created thread "wallclock_main" (1 total).
2019/04/07 11:27:04 [clock.wallclock_main:3] Streaming loop starts, synchronized with wallclock.
2019/04/07 11:27:04 [radioafonsosantos_live_switch:3] Switch to rotate_6455.
2019/04/07 11:27:04 [rotate_6455:3] Switch to map_metadata_6434.
2019/04/07 11:27:05 [dummy:3] Source failed (no more tracks) stopping output...
2019/04/07 11:27:08 [playlist_jingles:3] Finished with "/var/azuracast/stations/radioafonsosantos/media/Jingles/Outros/jingle_06.mp3".
2019/04/07 11:27:08 [radioafonsosantos_next_song:3] Prepared "/var/azuracast/stations/radioafonsosantos/media/M\195\186sicas/dj_ademar-2C_boy_teddy_-_ja_decidi.mp3" (RID 6).
2019/04/07 11:27:08 [playlist_jingles:3] Prepared "/var/azuracast/stations/radioafonsosantos/media/Jingles/Outros/jingle_04.mp3" (RID 4).
2019/04/07 11:27:08 [rotate_6455:3] Switch to radioafonsosantos_autodj_fallback with forgetful transition.
2019/04/07 11:27:08 [radioafonsosantos_autodj_fallback:3] Switch to radioafonsosantos_cue_cut.
2019/04/07 11:27:08 [smart_cross_6488:3] Analysis: -24.933215dB / -12.726358dB (4.55s / 4.57s)
2019/04/07 11:27:08 [smart_crossfade:3] No transition: using default.
2019/04/07 11:27:13 [lang:3] AzuraCast Feedback Response: OK
2019/04/07 11:27:30 [server:3] New client: 172.18.0.6.
2019/04/07 11:27:30 [server:3] Client 172.18.0.6 disconnected.
2019/04/07 11:27:30 [radioafonsosantos_local_1:3] Performing user-requested skip
2019/04/07 11:27:30 [radioafonsosantos_next_song:3] Finished with "/var/azuracast/stations/radioafonsosantos/media/M\195\186sicas/dj_ademar-2C_boy_teddy_-_ja_decidi.mp3".
2019/04/07 11:27:30 [playlist_msicas:3] Prepared "/var/azuracast/stations/radioafonsosantos/media/M\195\186sicas/m-24_-_final_song.mp3" (RID 5).
2019/04/07 11:27:30 [radioafonsosantos_autodj_fallback:3] Switch to random_6436 with forgetful transition.
2019/04/07 11:27:30 [random_6436:3] Switch to radioafonsosantos_playlist_msicas_cue.
2019/04/07 11:27:30 [lang:3] AzuraCast Raw Response: annotate:title="In My Blood",artist="Shawn Mendes",duration="208.",song_id="c4f18c1f2226e761597bae18f74ce145",media_id="107",genre="107",playlist_id="2":/var/azuracast/stations/radioafonsosantos/media/Músicas/shawn_mendes_-_in_my_blood.mp3
2019/04/07 11:27:30 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/radioafonsosantos/media/M\195\186sicas/shawn_mendes_-_in_my_blood.mp3".
2019/04/07 11:27:30 [smart_cross_6488:3] Analysis: -11.624784dB / -20.414595dB (4.52s / 4.52s)
2019/04/07 11:27:30 [smart_crossfade:3] No transition: using default.
2019/04/07 11:27:35 [lang:3] AzuraCast Feedback Response: OK
```
**AzuraCast application log:**
```
[2019-04-07 11:23:01] AzuraCast.INFO: Running message queue processor for 300 seconds. [] []
[2019-04-07 11:23:02] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-04-07 11:23:02] AzuraCast.INFO: Running 1-minute sync task [] []
[2019-04-07 11:23:04] AzuraCast.ERROR: NowPlaying adapter error: Request returned status 400: <b>mount does not exist</b>  [] {"station":{"id":1,"name":"Rádio Afonso Santos"}}
[2019-04-07 11:23:17] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-04-07 11:23:17] AzuraCast.ERROR: NowPlaying adapter error: Request returned status 400: <b>mount does not exist</b>  [] {"station":{"id":1,"name":"Rádio Afonso Santos"}}
[2019-04-07 11:23:32] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-04-07 11:23:32] AzuraCast.ERROR: NowPlaying adapter error: Request returned status 400: <b>mount does not exist</b>  [] {"station":{"id":1,"name":"Rádio Afonso Santos"}}
[2019-04-07 11:23:47] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-04-07 11:23:47] AzuraCast.ERROR: NowPlaying adapter error: Request returned status 400: <b>mount does not exist</b>  [] {"station":{"id":1,"name":"Rádio Afonso Santos"}}
[2019-04-07 11:24:02] AzuraCast.INFO: Running 1-minute sync task [] []
[2019-04-07 11:24:02] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-04-07 11:24:02] AzuraCast.ERROR: NowPlaying adapter error: Request returned status 400: <b>mount does not exist</b>  [] {"station":{"id":1,"name":"Rádio Afonso Santos"}}
[2019-04-07 11:24:17] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-04-07 11:24:17] AzuraCast.ERROR: NowPlaying adapter error: Request returned status 400: <b>mount does not exist</b>  [] {"station":{"id":1,"name":"Rádio Afonso Santos"}}
[2019-04-07 11:24:32] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-04-07 11:24:32] AzuraCast.ERROR: NowPlaying adapter error: Request returned status 400: <b>mount does not exist</b>  [] {"station":{"id":1,"name":"Rádio Afonso Santos"}}
[2019-04-07 11:24:47] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-04-07 11:24:47] AzuraCast.ERROR: NowPlaying adapter error: Request returned status 400: <b>mount does not exist</b>  [] {"station":{"id":1,"name":"Rádio Afonso Santos"}}
[2019-04-07 11:25:03] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-04-07 11:25:03] AzuraCast.INFO: Running 5-minute sync task [] []
[2019-04-07 11:25:03] AzuraCast.INFO: Running 1-minute sync task [] []
[2019-04-07 11:25:04] AzuraCast.ERROR: NowPlaying adapter error: Request returned status 400: <b>mount does not exist</b>  [] {"station":{"id":1,"name":"Rádio Afonso Santos"}}
[2019-04-07 11:25:17] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-04-07 11:25:18] AzuraCast.ERROR: NowPlaying adapter error: Request returned status 400: <b>mount does not exist</b>  [] {"station":{"id":1,"name":"Rádio Afonso Santos"}}
[2019-04-07 11:25:32] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-04-07 11:25:33] AzuraCast.ERROR: NowPlaying adapter error: Request returned status 400: <b>mount does not exist</b>  [] {"station":{"id":1,"name":"Rádio Afonso Santos"}}
[2019-04-07 11:25:47] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-04-07 11:25:48] AzuraCast.ERROR: NowPlaying adapter error: Request returned status 400: <b>mount does not exist</b>  [] {"station":{"id":1,"name":"Rádio Afonso Santos"}}
[2019-04-07 11:26:02] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-04-07 11:26:02] AzuraCast.INFO: Running 1-minute sync task [] []
[2019-04-07 11:26:03] AzuraCast.ERROR: NowPlaying adapter error: Request returned status 400: <b>mount does not exist</b>  [] {"station":{"id":1,"name":"Rádio Afonso Santos"}}
[2019-04-07 11:26:17] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-04-07 11:26:17] AzuraCast.ERROR: NowPlaying adapter error: Request returned status 400: <b>mount does not exist</b>  [] {"station":{"id":1,"name":"Rádio Afonso Santos"}}
[2019-04-07 11:26:32] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-04-07 11:26:32] AzuraCast.ERROR: NowPlaying adapter error: Request returned status 400: <b>mount does not exist</b>  [] {"station":{"id":1,"name":"Rádio Afonso Santos"}}
[2019-04-07 11:26:47] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-04-07 11:26:47] AzuraCast.ERROR: NowPlaying adapter error: Request returned status 400: <b>mount does not exist</b>  [] {"station":{"id":1,"name":"Rádio Afonso Santos"}}
[2019-04-07 11:27:02] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-04-07 11:27:02] AzuraCast.INFO: Running 1-minute sync task [] []
[2019-04-07 11:27:03] AzuraCast.ERROR: NowPlaying adapter error: Request returned status 400: <b>mount does not exist</b>  [] {"station":{"id":1,"name":"Rádio Afonso Santos"}}
[2019-04-07 12:27:13] AzuraCast.INFO: New message of type App\Message\UpdateNowPlayingMessage added to queue. [] []
[2019-04-07 11:27:14] AzuraCast.INFO: Handling message of type App\Message\UpdateNowPlayingMessage. [] []
[2019-04-07 11:27:17] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-04-07 11:27:32] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-04-07 12:27:35] AzuraCast.INFO: New message of type App\Message\UpdateNowPlayingMessage added to queue. [] []
[2019-04-07 11:27:36] AzuraCast.INFO: Handling message of type App\Message\UpdateNowPlayingMessage. [] []
[2019-04-07 11:27:47] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-04-07 11:28:04] AzuraCast.INFO: Running 1-minute sync task [] []
[2019-04-07 11:28:04] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-04-07 11:28:04] AzuraCast.INFO: Running message queue processor for 300 seconds. [] []
[2019-04-07 11:28:17] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-04-07 11:28:32] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-04-07 11:28:47] AzuraCast.INFO: Running Now Playing sync task [] []
```

**Comment by AnUnknowsTygerosy** [comment] 2019-04-07 11:45
This is my AzuraCast log:
```
[2019-04-07 11:41:15] AzuraCast.INFO: New message of type App\Message\UpdateNowPlayingMessage added to queue. [] []
[2019-04-07 11:41:16] AzuraCast.INFO: Handling message of type App\Message\UpdateNowPlayingMessage. [] []
[2019-04-07 11:41:17] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-04-07 11:41:32] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-04-07 11:41:47] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-04-07 11:42:02] AzuraCast.INFO: Running 1-minute sync task [] []
[2019-04-07 11:42:02] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-04-07 11:42:17] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-04-07 11:42:32] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-04-07 11:42:47] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-04-07 11:43:01] AzuraCast.INFO: Running 1-minute sync task [] []
[2019-04-07 11:43:01] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-04-07 11:43:12] AzuraCast.INFO: New message of type App\Message\UpdateNowPlayingMessage added to queue. [] []
[2019-04-07 11:43:13] AzuraCast.INFO: Handling message of type App\Message\UpdateNowPlayingMessage. [] []
[2019-04-07 11:43:16] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-04-07 11:43:31] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-04-07 11:43:46] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-04-07 11:44:01] AzuraCast.INFO: Running 1-minute sync task [] []
[2019-04-07 11:44:01] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-04-07 11:44:02] AzuraCast.INFO: New message of type App\Message\UpdateNowPlayingMessage added to queue. [] []
[2019-04-07 11:44:03] AzuraCast.INFO: Handling message of type App\Message\UpdateNowPlayingMessage. [] []
[2019-04-07 11:44:16] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-04-07 11:44:21] AzuraCast.INFO: New message of type App\Message\UpdateNowPlayingMessage added to queue. [] []
[2019-04-07 11:44:22] AzuraCast.INFO: Handling message of type App\Message\UpdateNowPlayingMessage. [] []

**Comment by SlvrEagle23** [comment] 2019-04-08 23:02
@afonsosantos @AnUnknowsTygerosy This one's weird. I really don't know what's causing it, and without looking directly at your AzuraCast installations I probably wouldn't be able to tell, since the logs aren't being much help.

Would either of you mind e-mailing me the details of your AzuraCast installation?

**Comment by afonsosantos** [comment] 2019-04-08 23:04
I can provide you access to my installation. Can you provide me an e-mail?

**Comment by SlvrEagle23** [comment] 2019-04-09 21:36
@afonsosantos @AnUnknowsTygerosy I haven't had a chance to diagnose this issue further. Please be patient. I apologize for any inconvenience.

**Comment by afonsosantos** [comment] 2019-04-09 22:18
> @afonsosantos @AnUnknowsTygerosy I haven't had a chance to diagnose this issue further. Please be patient. I apologize for any inconvenience.

Have you had a chance to access my AzuraCast instance?

**Comment by SlvrEagle23** [comment] 2019-04-09 22:49
@afonsosantos I'm looking at your installation right now and it appears every song has a duration associated with it and is properly showing this in both the public player and the station's profile.

Is this only happening with certain songs? Is it the same songs every time?

**Comment by afonsosantos** [comment] 2019-04-09 22:51
> @afonsosantos I'm looking at your installation right now and it appears every song has a duration associated with it and is properly showing this in both the public player and the station's profile.
> 
> Is this only happening with certain songs? Is it the same songs every time?

Yeah, it's just happening with some songs, and they are always the same, like M$ - Final Song

**Comment by SlvrEagle23** [comment] 2019-04-09 23:26
@AnUnknowsTygerosy @afonsosantos The problem has been identified and fixed. It was a single line of code that was present within the AzuraCast AutoDJ but not with Liquidsoap-managed playlists, so they weren't showing duration tracking properly.

Please update your installations and let me know if you encounter the issue any further.

**Comment by afonsosantos** [comment] 2019-04-09 23:27
> @AnUnknowsTygerosy @afonsosantos The problem has been identified and fixed. It was a single line of code that was present within the AzuraCast AutoDJ but not with Liquidsoap-managed playlists, so they weren't showing duration tracking properly.
> 
> Please update your installations and let me know if you encounter the issue any further.

I will update and provide the result. Thanks!

**Comment by afonsosantos** [comment] 2019-04-09 23:35
@SlvrEagle23 Just logged in and saw it happen again

![image](https://user-images.githubusercontent.com/46262740/55841781-9057bf80-5b28-11e9-9824-54493a123478.png)

**Comment by SlvrEagle23** [comment] 2019-04-09 23:36
@afonsosantos After a full update and the stations were restarted?

**Comment by afonsosantos** [comment] 2019-04-09 23:37
> @afonsosantos After a full update and the stations were restarted?

Yeah, after `./docker.sh update-self` and `./docker.sh update`

**Comment by SlvrEagle23** [comment] 2019-04-09 23:39
@afonsosantos It may take a minute or two for Composer's Packagist repository to pick up the latest commit. Once you're on commit version 30f855 (you can check from the site's footer) it should be fixed.

**Comment by afonsosantos** [comment] 2019-04-09 23:40
> @afonsosantos It may take a minute or two for Composer's Packagist repository to pick up the latest commit. Once you're on commit version 30f855 (you can check from the site's footer) it should be fixed.

You mean **30f8552**?

![image](https://user-images.githubusercontent.com/46262740/55841928-399eb580-5b29-11e9-9eb6-7402da72694f.png)

**Comment by SlvrEagle23** [comment] 2019-04-10 02:34
@afonsosantos I pulled that exact song down locally so I could see if I could verify what's causing the problem, and I was able to fix it with the code changes I published.

At this point, I'm fresh out of ideas if it's continuing to happen on your installation.

Leaving this issue closed as "can't reproduce" at this point.

**Comment by AnUnknowsTygerosy** [comment] 2019-04-10 15:57
Okay.. I maybe found my problem. Its something with playlists. If I will use only default playlist, song length will be normal.. If I will make my own playlist (scheduling etc..), songs will be without length.

**Comment by afonsosantos** [comment] 2019-04-10 15:59
I have 2 playlist: one for the songs (all default settings), and other for the jingles (everey 3 songs).

**Comment by SlvrEagle23** [comment] 2019-04-10 21:51
I have an idea. Bear with me.

**Comment by SlvrEagle23** [comment] 2019-04-10 22:11
@AnUnknowsTygerosy @afonsosantos Update your installations to the latest rolling-release version. I've made a small but significant change to how Liquidsoap's AutoDJ feedback works that should significantly improve its reliability.

**Comment by afonsosantos** [comment] 2019-04-10 22:14
I'll update and then feedback the result!

**Comment by SlvrEagle23** [comment] 2019-04-10 22:15
@afonsosantos Make sure you're on version `21204af`.

**Comment by afonsosantos** [comment] 2019-04-10 22:26
Just finished updating and logging in the web interface:

![image](https://user-images.githubusercontent.com/46262740/55917640-fa836980-5be7-11e9-9170-fcbf109563b0.png)

Had to click on the Restart button

**Comment by AnUnknowsTygerosy** [comment] 2019-04-10 22:26
Yeah.. I think its working. I will test it more tomorrow.. now Iam going to sleep.

**Comment by AnUnknowsTygerosy** [comment] 2019-04-10 22:30
Yeah.. but one small problem for me. One song will end, then AzuraCast error message will play and then second song will play. Also.. Next playing song still not showing :/

**Comment by afonsosantos** [comment] 2019-04-10 22:33
@SlvrEagle23 Still not working...

![image](https://user-images.githubusercontent.com/46262740/55917897-0b80aa80-5be9-11e9-880f-f10f35c4e907.png)

**Comment by SlvrEagle23** [comment] 2019-04-10 23:10
@AnUnknowsTygerosy Those are different problems and should be in different issues, but I'm glad that this particular issue is fixed.

@afonsosantos At this point, your setup is just cursed. There's nothing left to be done on the code end.

**Comment by AnUnknowsTygerosy** [comment] 2019-04-10 23:12
So.. I will must open new issue for that?

**Comment by SlvrEagle23** [comment] 2019-04-10 23:22
@AnUnknowsTygerosy Please do, and please describe in that issue exactly what playlists you have set up on your station. It sounds like your setup is specialized and is causing problems because of that.

**Comment by afonsosantos** [comment] 2019-04-10 23:26
> @AnUnknowsTygerosy Those are different problems and should be in different issues, but I'm glad that this particular issue is fixed.
> 
> @afonsosantos At this point, your setup is just cursed. There's nothing left to be done on the code end.

I think i'll leave it like that... Thanks for your help anyway!

**Comment by SlvrEagle23** [comment] 2019-04-10 23:30
@afonsosantos Sorry for being so blunt, I just do all of this work on basically a volunteer basis and it takes huge chunks of my day, so I don't want to sit and spend multiple _days_ on a single problem.

I can take one last look at your system if you want...I strongly suspect it has to do with the fact that there's a dollar sign in the song title, and that's causing Icecast to produce a different song "hash" than the one Liquidsoap is expecting and sending.

**Comment by afonsosantos** [comment] 2019-04-10 23:33
> @afonsosantos Sorry for being so blunt, I just do all of this work on basically a volunteer basis and it takes huge chunks of my day, so I don't want to sit and spend multiple _days_ on a single problem.
> 
> I can take one last look at your system if you want...I strongly suspect it has to do with the fact that there's a dollar sign in the song title, and that's causing Icecast to produce a different song "hash" than the one Liquidsoap is expecting and sending.

Don't worry, i perfectly understand that. What you are creating is just amazing and we must than you for the time you spent making it. Yeah, go ahead and take a look again, just let me disable 2FA...

**Comment by SlvrEagle23** [comment] 2019-04-10 23:59
@afonsosantos 

![Screenshot from 2019-04-10 18-58-14](https://user-images.githubusercontent.com/6744885/55921517-c47fbe80-5bc2-11e9-9fe0-05f24bfbab65.png)

From your installation's profile page, after a restart of the station.

**Comment by afonsosantos** [comment] 2019-04-11 00:01
So, was the playlist the problem?

**Comment by SlvrEagle23** [comment] 2019-04-11 00:02
@afonsosantos I'm not sure what the problem was...but it's not doing it now.

**Comment by afonsosantos** [comment] 2019-04-11 00:03
> @afonsosantos I'm not sure what the problem was...but it's not doing it now.

Let me delete the old playlist and create a new one, to see if that's the problem

**Comment by SlvrEagle23** [comment] 2019-04-11 06:40
@afonsosantos In your case, the answer might be something a little harder to deal with: your server may be running too slow, and unable to "keep up" with itself.

There's a constant back-and-forth going on between Liquidsoap and AzuraCast, and normally we count on the fact that these requests take just a few milliseconds to process, which is how we're able to put the correct metadata _just_ ahead of the next-playing song before the system detects that it plays. If, for whatever reason, there's something slowing that feedback loop down (i.e. poor server performance, other processes on the same server, etc), the "feedback" step can happen _after_ the next song has already cued up and is playing, which would result in problems like this one.

If it's possible for you to put your AzuraCast instance on a VPS somewhere in a data center, rather than on your home computer, I would be very interested to see if those same issues happen there.

That's also likely why we're having so much trouble reproducing the issues: my local development setup is quite optimized and runs faster than many servers, and our testing servers that we use are DigitalOcean VPSes, which tend to perform very quickly as well. If it's an issue isolated to slower machines, it would be much harder for us to reproduce.

In any case, thank you for your patience in this back-and-forth testing process. I think for now we can close this issue. I will continue working to try to optimize things even further as I get the chance.

**Closed by SlvrEagle23** 2019-04-11 06:40 UTC
Labels: error

**Comment by afonsosantos** [comment] 2019-04-11 10:00
Right now, i dont have a vps, but i'll let you know when i buy One. Thanks for your help!!
