### ISSUE TITLE
Media Sync tries to fetch metadata of directories and errors out on S3 storage locations

### ISSUE THREAD

**Issue by KyleJCrb** [AzuraCast/AzuraCast#4028] opened 2021-04-16 21:42 UTC
**Using Docker installation method**
Yes

**AzuraCast version**
v0.12.3 Stable

**Host Operating System**
Debian 10

**Describe the bug**
Following the update to the latest v0.12.3 of AzuraCast, the 5-Minute Sync job does not finish within the time limit and is cut off early due to an excessive amount of time taken to process remote media stored in an S3 bucket

**To Reproduce**
Set up a remote S3 bucket storage location and attempt to run 5-Minute Sync 

**Expected behavior**
The 5-Minute Sync to complete

**Relevant Logs**
`[2021-04-16T21:18:10.841539+00:00] AzuraCast.NOTICE: Running sync task: 5-Minute Sync {"force":true} []
[2021-04-16T21:18:10.843202+00:00] AzuraCast.DEBUG: Successfully acquired the "{resource}" lock. {"resource":{"Symfony\\Component\\Lock\\Key":"lock_sync_medium"}} []
[2021-04-16T21:18:10.843416+00:00] AzuraCast.DEBUG: Expiration defined for "{resource}" lock for "{ttl}" seconds. {"resource":{"Symfony\\Component\\Lock\\Key":"lock_sync_medium"},"ttl":600.0} []
[2021-04-16T21:18:10.846911+00:00] AzuraCast.DEBUG: Starting sub-task: CheckMediaTask [] []
[2021-04-16T21:18:10.853599+00:00] AzuraCast.INFO: Processing media for storage location Local: /var/azuracast/stations/kngi_network/media... [] []
[2021-04-16T21:18:10.872036+00:00] AzuraCast.DEBUG: Media processed for "Local: /var/azuracast/stations/kngi_network/media". {"total_size":"0 (0.0 B)","total_files":0,"already_queued":0,"unchanged":0,"updated":0,"created":0,"deleted":0,"not_processable":0} []
[2021-04-16T21:18:10.875829+00:00] AzuraCast.INFO: Processing media for storage location S3: https://kngi-storage.us-east-1.linodeobjects.com... [] []
[2021-04-16T21:22:17.333966+00:00] AzuraCast.DEBUG: Media processed for "S3: https://kngi-storage.us-east-1.linodeobjects.com". {"total_size":"251176776781 (251.2 GB)","total_files":3120,"already_queued":52,"unchanged":2963,"updated":0,"created":0,"deleted":0,"not_processable":105} []
[2021-04-16T21:22:17.337573+00:00] AzuraCast.DEBUG: Timer "CheckMediaTask" completed in 246.491 second(s). [] []
[2021-04-16T21:22:17.338981+00:00] AzuraCast.DEBUG: Starting sub-task: CheckFolderPlaylistsTask [] []
[2021-04-16T21:22:17.340454+00:00] AzuraCast.INFO: Processing auto-assigning folders for station... {"station":"KNGI Network"} []
[2021-04-16T21:22:17.658264+00:00] AzuraCast.ERROR: Unable to retrieve the metadata for file at location: kngi/NGI/shows/2020.  {"file":"/var/azuracast/www/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php","line":80,"code":0} []
[2021-04-16T21:22:17.659971+00:00] AzuraCast.INFO: Worker stopped due to time limit of {timeLimit}s exceeded {"timeLimit":300} []`

**Device(s):**

- Device: Desktop
- OS: Windows 10
- Browser: Chrome
- Version: 90

**Comment by Vaalyn** [comment] 2021-04-17 10:54
Could you try increasing the time limit by following this tutorial?

https://docs.azuracast.com/en/administration/sync-tasks#increase-execution-timeout

**Comment by KyleJCrb** [comment] 2021-04-17 13:15
Changing these settings seems to have no effect. It still times out after 300 seconds. I triple-checked to make sure I uncommented the settings in the azuracast.env file and tried several different values along with restarting Docker every time, but it hasn't made any difference.

**Comment by Vaalyn** [comment] 2021-04-17 13:39
Thank you for checking.

As far as I can currently see this seems to be caused by the filesystem library not being able to retrieve the metadata for one or multiple from the S3 location and thus crashing the sync processing. The timeout error is a bit misleading here.

I'm not sure if this is due to a bug in the filesystem library or if this is a problem on Linode's side or with a specific file.

Could you check if the `kngi/NGI/shows/2020.` file that is mentioned in the metadata error has any issues / if it exist / can be accessed through linodes s3 interface / can you view metadata of that file via their s3 interface?

**Comment by KyleJCrb** [comment] 2021-04-17 14:14
The "file" is actually a folder with MP3s stored inside of it. It's fully accessible and viewable via Cyberduck, and I am able to download the files within that folder via web browser. That folder has a playlist assigned to it which I've removed, but that just causes the same error to occur with a different folder.

**Comment by KyleJCrb** [comment] 2021-04-17 15:21
I tried an experiment by deleting my media playlists in AzuraCast. After deleting them all, the 5-Minute Sync process worked perfectly, but after recreating and assigning a folder to a new playlist and then running the sync manually, the error started occurring again at that folder.

**Comment by Vaalyn** [comment] 2021-04-17 15:45
Thank you for doing all these tests.
This should help us find the exact cause of this issue.

I have already re-classified this as a bug.

**Comment by lghcdh** [comment] 2021-04-18 08:59
This issue looks very similar to my own, reported 10 days ago.
https://github.com/AzuraCast/AzuraCast/issues/3992.

**Comment by Vaalyn** [comment] 2021-04-18 18:40
I have found the cause of this issue and have submitted a fix for this.

**Comment by KyleJCrb** [comment] 2021-04-18 19:02
> This issue looks very similar to my own, reported 10 days ago.
> #3992.

Interestingly, it looks like I also have ghosted duplicate folders visible in AzuraCast's file manager, so we're likely having the same issue. These folders aren't visible on Linode's file manager or through Cyberduck, so I think it's a bug with AzuraCast itself.

**Comment by Vaalyn** [comment] 2021-04-18 21:03
@KyleJCrb please update to the latest rolling-release and test if the fix I submitted resolves this problem for you.

**Comment by KyleJCrb** [comment] 2021-04-18 21:40
@Vaalyn The problem seems to be fixed and the 5-Minute Sync completes successfully. Thank you for the quick turnaround!

**Comment by Vaalyn** [comment] 2021-04-19 08:24
Wonderful, thank you for confirming it fixed 👍 

I'll close this issue as resolved then.

**Closed by Vaalyn** 2021-04-19 08:24 UTC
Labels: bug
