### ISSUE TITLE
Public radio page - intermittent album artwork

### ISSUE THREAD

**Issue by amavarick** [AzuraCast/AzuraCast#359] opened 2017-12-26 13:50 UTC
https://azuracastdomain.tld/public/music

Seems the album art intermittently appears.  Some items to note, this is on the same song.  When a new song starts, the album doesn't appear, shows bad link icon.  After so many seconds the album art appears... then in same song it disappears again and after a few seconds appears again on the same song.  This behavior is identical whether I am just on the page whether the player is playing or stopped.  Seems like there's conflicting calls?

![image](https://user-images.githubusercontent.com/20918832/34357951-6e56446e-ea19-11e7-87cb-31f004616768.png)
![image](https://user-images.githubusercontent.com/20918832/34357966-87717ea0-ea19-11e7-930a-c0b4190cca15.png)

Its expecting to find the artwork at the following un-resolvable domain:
https://nginx/api/station/1/....

![image](https://user-images.githubusercontent.com/20918832/34357362-7a6ecb5e-ea14-11e7-952c-72d9204738f1.png)

**Comment by SlvrEagle23** [comment] 2017-12-26 22:51
@amavarick This one seems to be caused by the "Prefer Browser URL" setting being set to "Yes", then the internal API calls between various parts of the AzuraCast system getting confused and preferring what, to them, is their "browser URL", which is http://nginx or http://localhost, depending on the install type.

This should be fixed now.

**Comment by amavarick** [comment] 2017-12-26 23:50
Confirmed, artwork is displaying properly.  Thank you very much.

**Comment by amavarick** [comment] 2017-12-27 00:00
Sorry I may have been premature in response.  Using desktop, no issues with album artwork now.

I tried on my Android/Chrome and the public radio does not display artwork or id3 data using an unencrypted connection http.  It will play the radio though through the web player.

If I change the URL from http to https, everything works fine.  I do have Let's encrypt cert natively installed as you have implemented but have "always use https" set to no.

**Comment by SlvrEagle23** [comment] 2017-12-27 00:05
@amavarick If you visit the site on your browser via HTTP, what URL is it using for the images? Provided the "always use HTTPS" setting is not set to "Yes", it shouldn't interfere with HTTP connections at all.

**Comment by amavarick** [comment] 2017-12-27 00:17
Note: Neither the images or the mp3 meta id3 is showing on http.
The URL is the /static/img/generic_song.jpg
I have "always use HTTPS" set to no but do have your implementation of Let's encrypt installed.

**Comment by SlvrEagle23** [comment] 2017-12-27 00:19
@amavarick If a song has no album art, it won't show anything on the public page (specifically to avoid showing blank album art for people whose music collections have no art at all), so the generic art won't ever show up.

Do all of your songs have album art specified? If not, skip ahead until you reach one that does and test it there.

**Comment by amavarick** [comment] 2017-12-27 00:41
All but 2 of my albums have artwork.  The particular ones tested have all artwork and meta.

To be clearer, if I switch from http to https, everything appears fine.  If I switch from https to http that same song goes to the generic_song artwork and blanks out the metadata to show "Song Title" and "Song Artist" in place of the actual title and artist.  Pictures are worth a thousand words...

HTTP page of public radio, actually playing the radio
![image](https://user-images.githubusercontent.com/20918832/34367124-861ff9b8-ea74-11e7-8c1c-f04317de33ad.png)

HTTPS page of public radio, actually playing the radio... same song as http above.
![image](https://user-images.githubusercontent.com/20918832/34367139-ba355554-ea74-11e7-8bca-6b096d751d09.png)

**Comment by SlvrEagle23** [comment] 2017-12-27 00:46
@amavarick If you look at the browser inspector, specifically the "Network" panel, then reload the page...you should see some sort of error with the HTTP version of the page. Seeing the default artwork with the generic labels like that implies that the now-playing data isn't making it through at all, which will produce an error of some sort in that console and in the network panel.

**Comment by amavarick** [comment] 2017-12-27 00:50
I cannot reproduce this issue on desktop where I can easily bring up the console and view the errors as you've seen me post above.  It is only appearing on Android Chrome.  I need to research how I can bring up the inspector on an Android.

**Comment by SlvrEagle23** [comment] 2017-12-27 00:52
@amavarick Ahh, that's always going to be hard to diagnose. The basics of setting up remote debugging can be found here: https://developers.google.com/web/tools/chrome-devtools/remote-debugging/

**Comment by amavarick** [comment] 2017-12-27 01:07
Now that's a cool thing to do!  Thanks for the link, it was invaluable to capture the the debugging data.  The logs were full of this:
![image](https://user-images.githubusercontent.com/20918832/34367384-034205fa-ea78-11e7-8202-2514debfa8f7.png)

**Comment by amavarick** [comment] 2017-12-27 01:24
Okay, very frustrated at myself.  I have "Adblock Plus" installed on my rooted Android.  Disabling that made non-encrypted public radio work fine.  Very sorry for wasting the last 45 minutes of your life.

I initially ruled out adblocking because I was able to access the same site with https.  I thought my adblock software was hosts file based just matching URL... apparently its more.  This issue I believe is completely resolved.

**Closed** 2017-12-27 06:05 UTC
Labels: bug
