### ISSUE TITLE
cannot upload songs from web ui

### ISSUE THREAD

**Issue by bilias** [AzuraCast/AzuraCast#1827] opened 2019-08-08 14:22 UTC
**Using Docker installation method**
Yes

**Host Operating System**
CentOS 7 / Ubuntu 18.04

**Describe the bug**
Cannot upload songs over the web ui. I can upload and the songs are listed using the ssh method. No errors anywhere.

**Relevant Logs**
docker-compose logs shows only this:

web_1       | 2019/08/08 13:03:40 [warn] 61#61: *1 a client request body is buffered to a temporary file /tmp/azuracast_nginx_client/1/0/0000000001, client: xx.xx.xx.xx, server: localhost, request: "POST /admin/install/shoutcast HTTP/1.1", host: "yy.yy.yy.yy", referrer: "http://yy.yy.yy.yy/admin/install/shoutcast"
web_1       | 2019/08/08 13:04:08 [warn] 61#61: *89 a client request body is buffered to a temporary file /tmp/azuracast_nginx_client/2/0/0000000002, client: xx.xx.xx.xx, server: localhost, request: "POST /station/1/files/upload HTTP/1.1", host: "yy.yy.yy.yy", referrer: "http://yy.yy.yy.yy/station/1/files"
web_1       | 2019/08/08 13:04:21 [warn] 61#61: *89 a client request body is buffered to a temporary file /tmp/azuracast_nginx_client/3/0/0000000003, client: xx.xx.xx.xx, server: localhost, request: "POST /station/1/files/upload HTTP/1.1", host: "yy.yy.yy.yy", referrer: "http://yy.yy.yy.yy/station/1/files"

using 
docker-compose exec --user="azuracast" web bash
I see no files (only directories) in /tmp/azuracast_nginx_client

Running the 5 min cron job (over web) does not produce any warning.
All these are with the latest version: 0.9.6

**Comment by SlvrEagle23** [comment] 2019-08-08 16:20
@bilias This one was caused by a silly error on my part; I was testing some functionality locally and accidentally committed a debug statement in the Flow upload manager. I removed it and things should be back to normal. Sorry about that!

**Closed by SlvrEagle23** 2019-08-08 16:20 UTC
Labels: bug
