### ISSUE TITLE
Tracks not added to queue as expected

### ISSUE THREAD

**Issue by MarkWasley** [AzuraCast/AzuraCast#3863] opened 2021-03-06 08:34 UTC
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #4cd090d (2021-02-22 22:17)

**Host Operating System**
Alpine Linux Version 3.13.2

**Describe the bug**
As I understand, the logic for AzuraCast deciding which track to cue when working with a shuffled playlist involves placing all tracks that haven't played in the duplicate prevention timeframe (which I have set to 3 hours) in the `$eligibleTracks`/`$notPlayedEligibleTracks` arrays.

Once the function passes to the `getDistinctTrack` function, it does a couple of checks to ensure the track doesn't consist of the same title or artist, as has played within the duplicate prevention timeframe (i.e. not in `$playedTracks`). There appears to be no methodology to the way the array is built and this is causing some tracks to play more frequently than others by the same artist, for example and some tracks will play vary rarely.

I have added a couple of lines to the code in Queue.php, to log what is happening when running these functions to build the queue.

In the preventDuplicates function, underneath `$notPlayedEligibleTracks = [];`.
`$notPlayedEligibleTracksToDisplayInLog = []`

In the foreach loop:
```
			$notPlayedEligibleTracksToDisplayInLog[] = [
				"media_id" => $mediaId,
				"title" => $track['title'],
				"artist" => $track['artist']
			];
```

Before `$mediaId = self::getDistinctTrack($notPlayedEligibleTracks, $playedTracks)`, to log the tracks that can be played.

`$this->logger->info('Tracks that can be Played:', $notPlayedEligibleTracksToDisplayInLog);`

See extracts from my logs below to see what I am experiencing. You will see I have added in another line of code to log when an artist match is found. I have a line for title matches, but there were none to appear in these extracts.

Because I this endlessly repeating, I never get to the point of '`Duplicate prevention yielded no playable song; resetting song queue`'.

Is anyone else experiencing this as well?

**To Reproduce**
1. Use default playlist, set to General Rotation, playlist weight of 3 (default) and Shuffled playback order.
2. Enable Avoid Duplicate Artists/Titles.
3. Set Duplicate Prevention Time Range in your station AutoDJ settings.
4. Keep an eye on which tracks are being cued.

I also have my AutoDJ Queue Length set to 20.

**Expected behavior**
Keep playing the shuffled playlist of `$eligibleTracks`, without altering the order of the array. Played tracks will be removed from the array, but if a track can not be played, keep it in the array and try to play it when cueing the next song. Eventually, it should play once the duplicate prevention timeframe has expired. The least recently played song by an artist should be played, before playing any song again.

**Relevant Logs**
The `$notPlayedEligibleTracksToDisplayInLog` array has been shortened for brevity.

```
[2021-03-06T05:01:32.320264+00:00] AzuraCast.INFO: AzuraCast AutoDJ is calculating the next song to play... [] {"station":{"id":1,"name":"Station Mark"}}
[2021-03-06T05:01:32.390781+00:00] AzuraCast.INFO: 1 playable playlist(s) of type "default_unscheduled" found. {"playlists":[{"id":1,"name":"default","weight":3}]} {"station":{"id":1,"name":"Station Mark"}}
[2021-03-06T05:01:32.391617+00:00] AzuraCast.INFO: Tracks that can be Played: [{"media_id":58,"title":"Celeste","artist":"Ezra Vine"},{"media_id":13,"title":"Coffee and Cream","artist":"Ben Lummis"},{"media_id":143,"title":"In the Neighbourhood","artist":"Sisters Underground"},{"media_id":119,"title":"You'll Never Walk Alone","artist":"Michael Ball. Captain Tom Moore & The NHS Voices of Care Choir"},{"media_id":168,"title":"December","artist":"Yumi Zouma"},{"media_id":14,"title":"They Can't Take That Away","artist":"Ben Lummis"},{"media_id":92,"title":"How Great Thou Art","artist":"John Rowles"},{"media_id":138,"title":"Will You Sing With Me","artist":"Renée Therése & Cooper's Run"},{"media_id":42,"title":"Chicken Fried","artist":"Denis Henderson"},{"media_id":9,"title":"Even The Nights Are Better","artist":"Anne Murray"}] {"station":{"id":1,"name":"Station Mark"}}
[2021-03-06T05:01:32.393153+00:00] AzuraCast.INFO: Found track that avoids duplicate title and artist. {"media_id":58} {"station":{"id":1,"name":"Station Mark"}}
[2021-03-06T05:01:32.408253+00:00] AzuraCast.INFO: Playable track found and registered. {"next_song":"StationMedia db206d4024de9d56994acbc4: Ezra Vine - Celeste"} {"station":{"id":1,"name":"Station Mark"}}

[2021-03-06T05:04:47.151533+00:00] AzuraCast.INFO: AzuraCast AutoDJ is calculating the next song to play... [] {"station":{"id":1,"name":"Station Mark"}}
[2021-03-06T05:04:47.189527+00:00] AzuraCast.INFO: 1 playable playlist(s) of type "default_unscheduled" found. {"playlists":[{"id":1,"name":"default","weight":3}]} {"station":{"id":1,"name":"Station Mark"}}
[2021-03-06T05:04:47.190447+00:00] AzuraCast.INFO: Tracks that can be Played: [{"media_id":13,"title":"Coffee and Cream","artist":"Ben Lummis"},{"media_id":143,"title":"In the Neighbourhood","artist":"Sisters Underground"},{"media_id":119,"title":"You'll Never Walk Alone","artist":"Michael Ball. Captain Tom Moore & The NHS Voices of Care Choir"},{"media_id":168,"title":"December","artist":"Yumi Zouma"},{"media_id":14,"title":"They Can't Take That Away","artist":"Ben Lummis"},{"media_id":92,"title":"How Great Thou Art","artist":"John Rowles"},{"media_id":138,"title":"Will You Sing With Me","artist":"Renée Therése & Cooper's Run"},{"media_id":42,"title":"Chicken Fried","artist":"Denis Henderson"},{"media_id":9,"title":"Even The Nights Are Better","artist":"Anne Murray"},{"media_id":118,"title":"Streetlights","artist":"Marianne Leigh & Jamie McDell"}] {"station":{"id":1,"name":"Station Mark"}}
[2021-03-06T05:04:47.191825+00:00] AzuraCast.INFO: Found track that avoids duplicate title and artist. {"media_id":13} {"station":{"id":1,"name":"Station Mark"}}
[2021-03-06T05:04:47.217528+00:00] AzuraCast.INFO: Playable track found and registered. {"next_song":"StationMedia 84be03770945d3365a6faf65: Ben Lummis - Coffee and Cream"} {"station":{"id":1,"name":"Station Mark"}}

[2021-03-06T05:08:05.207571+00:00] AzuraCast.INFO: AzuraCast AutoDJ is calculating the next song to play... [] {"station":{"id":1,"name":"Station Mark"}}
[2021-03-06T05:08:05.247558+00:00] AzuraCast.INFO: 1 playable playlist(s) of type "default_unscheduled" found. {"playlists":[{"id":1,"name":"default","weight":3}]} {"station":{"id":1,"name":"Station Mark"}}
[2021-03-06T05:08:05.248273+00:00] AzuraCast.INFO: Tracks that can be Played: [{"media_id":48,"title":"Woke Up Late","artist":"Drax Project & Hailee Steinfeld"},{"media_id":145,"title":"Special","artist":"Six60"},{"media_id":133,"title":"One Day","artist":"Opshop"},{"media_id":53,"title":"Big Norm","artist":"Ebony"},{"media_id":51,"title":"Kimbolton","artist":"Eb & Sparrow"},{"media_id":65,"title":"That Girl","artist":"Grace Kelly"},{"media_id":134,"title":"Be Kind","artist":"Owen Mac"},{"media_id":141,"title":"Nothing to Regret","artist":"Robinson"},{"media_id":101,"title":"Home","artist":"Kaylee Bell"},{"media_id":89,"title":"Aussie Proud","artist":"Jodi Vaughan"}] {"station":{"id":1,"name":"Station Mark"}}
[2021-03-06T05:08:05.249307+00:00] AzuraCast.INFO: Found track that avoids duplicate title and artist. {"media_id":48} {"station":{"id":1,"name":"Station Mark"}}
[2021-03-06T05:08:05.270410+00:00] AzuraCast.INFO: Playable track found and registered. {"next_song":"StationMedia e8bf47b1cd885b6add728804: Drax Project & Hailee Steinfeld - Woke Up Late"} {"station":{"id":1,"name":"Station Mark"}}

[2021-03-06T05:12:47.703354+00:00] AzuraCast.INFO: AzuraCast AutoDJ is calculating the next song to play... [] {"station":{"id":1,"name":"Station Mark"}}
[2021-03-06T05:12:47.745389+00:00] AzuraCast.INFO: 1 playable playlist(s) of type "default_unscheduled" found. {"playlists":[{"id":1,"name":"default","weight":3}]} {"station":{"id":1,"name":"Station Mark"}}
[2021-03-06T05:12:47.746143+00:00] AzuraCast.INFO: Tracks that can be Played: [{"media_id":71,"title":"Pretty Girl","artist":"Hannah May"},{"media_id":161,"title":"Lipstick Stains","artist":"Vickie Evans"},{"media_id":82,"title":"Life in Sunshine","artist":"Jamie McDell"},{"media_id":91,"title":"I've Been Everywhere","artist":"John Hore"},{"media_id":95,"title":"Why Don't We Just Dance","artist":"Josh Turner"},{"media_id":103,"title":"Light On","artist":"Kaylee Bell"},{"media_id":80,"title":"Back of My Mind","artist":"Jamie McDell & Rai Thistlethwayte"},{"media_id":138,"title":"Will You Sing With Me","artist":"Renée Therése & Cooper's Run"},{"media_id":15,"title":"Take Me Home Country Roads","artist":"Bevan Gardiner"},{"media_id":76,"title":"On the Run","artist":"Into the East"}] {"station":{"id":1,"name":"Station Mark"}}
[2021-03-06T05:12:47.751293+00:00] AzuraCast.INFO: Artist has played too recently, so can't cue track. {"media_id":71,"title":"Pretty Girl","artist":"Hannah May"} {"station":{"id":1,"name":"Station Mark"}}
[2021-03-06T05:12:47.751542+00:00] AzuraCast.INFO: Artist has played too recently, so can't cue track. {"media_id":161,"title":"Lipstick Stains","artist":"Vickie Evans"} {"station":{"id":1,"name":"Station Mark"}}
[2021-03-06T05:12:47.751820+00:00] AzuraCast.INFO: Artist has played too recently, so can't cue track. {"media_id":82,"title":"Life in Sunshine","artist":"Jamie McDell"} {"station":{"id":1,"name":"Station Mark"}}
[2021-03-06T05:12:47.752081+00:00] AzuraCast.INFO: Found track that avoids duplicate title and artist. {"media_id":91} {"station":{"id":1,"name":"Station Mark"}}
[2021-03-06T05:12:47.770889+00:00] AzuraCast.INFO: Playable track found and registered. {"next_song":"StationMedia aaee8b8a5c11fcd5e71497dd: John Hore - I've Been Everywhere"} {"station":{"id":1,"name":"Station Mark"}}

[2021-03-06T05:15:21.242185+00:00] AzuraCast.INFO: AzuraCast AutoDJ is calculating the next song to play... [] {"station":{"id":1,"name":"Station Mark"}}
[2021-03-06T05:15:21.335645+00:00] AzuraCast.INFO: 1 playable playlist(s) of type "default_unscheduled" found. {"playlists":[{"id":1,"name":"default","weight":3}]} {"station":{"id":1,"name":"Station Mark"}}
[2021-03-06T05:15:21.339814+00:00] AzuraCast.INFO: Tracks that can be Played: [{"media_id":100,"title":"Be With You","artist":"Kaylee Bell"},{"media_id":138,"title":"Will You Sing With Me","artist":"Renée Therése & Cooper's Run"},{"media_id":126,"title":"Oh Canada","artist":"Nadia Reid"},{"media_id":129,"title":"Forever in Blue Jeans","artist":"Neil Diamond"},{"media_id":154,"title":"Nature","artist":"The Fourmyula"},{"media_id":153,"title":"Nature (UK Version)","artist":"The Fourmyula"},{"media_id":168,"title":"December","artist":"Yumi Zouma"},{"media_id":5,"title":"Done and Gone","artist":"Ainslie Allen"},{"media_id":117,"title":"Tumblin Down (US Version)","artist":"Maria Dallas"},{"media_id":76,"title":"On the Run","artist":"Into the East"},{"media_id":70,"title":"Passenger Seat","artist":"Hannah May"}] {"station":{"id":1,"name":"Station Mark"}}
[2021-03-06T05:15:21.341103+00:00] AzuraCast.INFO: Found track that avoids duplicate title and artist. {"media_id":100} {"station":{"id":1,"name":"Station Mark"}}
[2021-03-06T05:15:21.408064+00:00] AzuraCast.INFO: Playable track found and registered. {"next_song":"StationMedia 436d81bfd3b31db0ad75dca2: Kaylee Bell - Be With You"} {"station":{"id":1,"name":"Station Mark"}}
```

**Comment by SlvrEagle23** [comment] 2021-03-06 11:10
@MarkWasley What do you mean by:

>  There appears to be no methodology to the way the array is built and this is causing some tracks to play more frequently than others by the same artist, for example and some tracks will play vary rarely.

While the functions leading up to `getDistinctTrack` do tend to rearrange the array layout a bit, both the `playedTracks` and `eligibleTracks` arrays come from reasonable places: the former from the station's playback history merged with its current queue, and the latter from an internal queue associated with each playlist, which has an element popped off of it any time a track is played from it.

If you can identify specific areas in the AutoDJ queue builder code where we could improve the functionality of the system, we would be more than happy to review a pull request.

**Comment by MarkWasley** [comment] 2021-03-06 11:42
@SlvrEagle23 I am referring to the way the array (which is shown in my log) is ordered. When it is time to cue the third track, you'll see the first ten eligible tracks are completely different to what was available to be played initially. The rest of the entries, as well as future arrays, are random. The track, _In the Neighbourhood_, should've played. I would like the AutoDJ to play the entire internal queue before reordering/resetting the array, which I'm sure is what happened in the past.

**Comment by SlvrEagle23** [comment] 2021-03-06 11:48
@MarkWasley It sounds like you're describing the "random" playlist playback order, which does indeed randomize the eligible tracks at every single queue build process. The "shuffled" playback order should build a single playback queue for a playlist, play through it in its entirety, then reshuffle the playlist and run through it again.

**Comment by MarkWasley** [comment] 2021-03-06 12:00
@SlvrEagle23 This is a shuffled playlist, which is why I don't understand why this is happening. Is it like this on your installation?

**Comment by Abqehebter** [comment] 2021-03-07 16:27
Normally I didn't want to interfere, and from the code I wrote in the old issue that I don't discover much.

The same problem here is touched.
The shuffle function sometimes plays more like the random function and does not play all tracks.

Example with my playlist with 145 songs: 90 songs run through and through, but there are many that don't even get to it (As far as I understand this correctly here in the issue)
Logical and also okay that songs sometimes play more often to possibly also use the "Avoid Duplicate Artists/Titles function", but shuffles he does not properly - Feels as I said rather after the random function with me.

(If I have written past the topic, excuse me)

**Comment by Abqehebter** [comment] 2021-03-09 10:42
@MarkWasley Sorry for the ping. It's like you said in issue #3889 that it should not normally shuffle the shuffle playlist but check the tracks in the queue, did I understand that correctly? Correct me if I am wrong.

And currently looking for the reason why he is shuffling them anyway? Just so I know that again for me.

**Comment by Abqehebter** [comment] 2021-03-22 20:10
@SlvrEagle23 This may sound a bit crazy, but I can imagine why the complete internal shuffle list resets: The media sync (Every 5 minutes) makes sure that changes are made no matter if a new track exists or not, it just resets the list after 5 minutes.
The best way to test this is to look at the shuffle list, run the 5 min media sync manually, and look at the list again.

If you've already figured this out, then I seem to have missed something.

**Comment by MarkWasley** [comment] 2021-03-22 20:43
@Abqehebter, @SlvrEagle23 I was actually just about to add this. I did some further investigation yesterday and found that the internal queue is reset after the 5-Minute Sync. After doing some more debugging, I found that the internal queue does not reset after commenting out the `CheckFolderPlaylists` task in TaskLocator.php.

I have already had a successful run of my complete playlist, with the queue and duplicate prevention working as it should, as I have outlined as expected behaviour above. This is without the most recent commit 55ea4fa8da70c1345b7978fe0b90ce3547c07072. I would appreciate @SlvrEagle23 explaining the benefit of removing the block of code in that commit, as the '`Duplicate prevention yielded no playable song; resetting song queue.`' part is necessary, as this creates a new queue and logs it, when the queue is empty.

**Comment by SlvrEagle23** [comment] 2021-03-23 16:55
I've redirected a few other reported issues over to this one, as I believe I've figured out the one unifying thing causing all of these queue problems:

 - There was a section of code in the "Check Station Playlist Folders" task that basically added every single track in a folder to a playlist, regardless of whether it was already in the playlist or not, and
 - There was a later section in `StationPlaylistMediaRepository` that would add that newly added track to the queue, even if it already existed on the playlist.

For those of you adding entire folders to playlists, basically both of these together would have broken the queue system entirely. The reason we didn't detect this earlier is because in my local testing I tend to add single individual files to playlists instead of entire folders, which is how we weren't able to reproduce the issues locally until a few folks pointed out they may be related to the playlist folders functionality.

@MarkWasley The latest commits removing the queue-rebuilding function from the duplicate prevention were intended to fix this issue, but of course this wasn't the cause of the problem in the first place, so it's likely I'll revert that commit shortly.

In the latest Rolling Release update, I've completely rewritten how the "Check Playlist Folders" task works. The previous iteration was woefully under-optimized, and I suspect it was a point of failure for a lot of especially large installations that were having trouble with sync tasks failing or running out of memory. The newer code manages a much smaller set of data and also incorporates safety checks to avoid trying to add a file to a playlist that already exists in it. The downstream "rebuild the queue if a media file already exists in a playlist" bug was also fixed, but with the newly rewritten task, it should never even be invoked.

I'd encourage anyone running into this issue to please test the latest Rolling Release commit (`e11990`) and confirm that it helps.

**Comment by Abqehebter** [comment] 2021-03-23 16:57
Many big thanks to both parties! Will test immediately.

**Comment by MarkWasley** [comment] 2021-03-23 23:04
I can confirm that the queue is now working as it should, not resetting every five minutes. I have also tested uploading new tracks to a folder, through SSH and the Music Files interface and this adds the tracks to the playlist with the `CheckFolderPlaylistsTask`. It also adds them to the rest of the queue, but shuffles the queue at the same time.

Here is a screenshot of my queue (the blurred part are tracks that have been sent to the AutoDJ between screenshots), before I uploaded the new tracks: 

![Queue before uploading new tracks](https://user-images.githubusercontent.com/25557014/112229011-12e6d480-8c97-11eb-8ab6-48ace7e0fc66.png)

Here is a screenshot of my queue after I uploaded the new tracks (partially redacted for privacy of the artist):

![Queue after uploading new tracks](https://user-images.githubusercontent.com/25557014/112229541-0616b080-8c98-11eb-841e-559efb404901.png)

Is it possible to just add any new tracks to the end of the queue and not shuffle again?

**Comment by Abqehebter** [comment] 2021-03-23 23:40
What I noticed at the end of the shuffle playlist was that there were still some of the same artists in there that he then had to play. Shouldn't the list reset itself as soon as this is the case? Has not quite worked for me yet. If someone here could confirm this?

**Comment by SlvrEagle23** [comment] 2021-03-24 10:38
@MarkWasley The latest commit prevents this reshuffle from happening when items are added to the queue.

@Abqehebter I had removed this function (resetting the queue if duplicate prevention isn't possible) because I suspected it might be the cause of this error, but it turns out it wasn't, so I reverted that commit, so if you update again today it should be back to doing that as normal.

**Comment by Abqehebter** [comment] 2021-03-24 12:06
@SlvrEagle23 Currently I often get these messages in my log (see below) which somehow tell me that he could not reshuffle the list. I have now installed the latest rolling release update and wait until I have found something again. This only happens at the end of the playlist, not in the middle.

```
[2021-03-24T11:56:01.348728+00:00] AzuraCast.NOTICE: Running sync task: 1-Minute Sync {"force":false} []
[2021-03-24T11:56:01.358957+00:00] AzuraCast.NOTICE: Running sync task: Now Playing Data {"force":false} []
[2021-03-24T11:56:01.728513+00:00] AzuraCast.WARNING: Playlist "charts" did not return a playable track. {"playlist_id":31,"playlist_order":"shuffle","allow_duplicates":false} {"station":{"id":2,"name":"Station2"}}
[2021-03-24T11:56:01.728710+00:00] AzuraCast.WARNING: Duplicate prevention yielded no playable song; resetting song queue. [] {"station":{"id":2,"name":"Station2"}}
[2021-03-24T11:56:01.729562+00:00] AzuraCast.WARNING: No way to avoid same title OR same artist; using least recently played song. {"media_id":2643} {"station":{"id":2,"name":"Station2"}}
```

**Comment by Abqehebter** [comment] 2021-03-24 13:18
So after the update, nothing appears in the log for my one station. So the list has only a few songs and quite a few artist repeats, which somehow do not bother him (See screenshot).

After the list was empty, he shuffled again and it worked again until the end, because he will probably have many songs there again, which will consist of the same artist.

Conclusion: The shuffle reset that should take effect, does not work towards the end with me at least. It just plays the list normally to the end.

![image](https://user-images.githubusercontent.com/42640247/112315820-cb6a4380-8caa-11eb-9b0f-dbb664cc09a1.png)

**Comment by Abqehebter** [comment] 2021-03-25 11:20
My mistake. That was my charts playlist that goes only one hour with many duplications. However, the error persists with me that he does not want to shuffle the list towards the end, despite that he should notice that the same artists are in there.

@MarkWasley can you possibly adjust this or does it work normally with the artist avoidance? I need a second opinion to see if I have done something wrong...

**Comment by MarkWasley** [comment] 2021-04-03 06:47
@Abqehebter Sorry for the delay in responding to you. I have been preparing the below explanation on how duplicate prevention works for you. What you are experiencing is expected behaviour on all random and shuffled playlists. To explain the order of how duplicate prevention works, using a shuffled playlist, as an example:

1. If Avoid Duplicate Artists/Titles is enabled (ticked) in Edit Playlist, then continue (if not, then AutoDJ will select the first track in the internal queue to cue for playback).
https://github.com/AzuraCast/AzuraCast/blob/4971ca1773053eaf13c8e363a88d3e88d5816632/src/Radio/AutoDJ/Queue.php#L487
2. If `$allowDuplicates` is not `true`, then run the `preventDuplicates` function, passing the internal queue (`$mediaQueue`), `$recentSongHistory` and `$allowDuplicates` as variables used in the function as `$eligibleTracks`, `$playedTracks` and `$allowDuplicates` respectively. `$allowDuplicates` is set while looping through all eligible playlists. This loop will attempt to play tracks from playlists with no duplicates first, then if a `$mediaId` is still not returned, loop through again allowing duplicates. I think it is clear what the other variables represent.
https://github.com/AzuraCast/AzuraCast/blob/4971ca1773053eaf13c8e363a88d3e88d5816632/src/Radio/AutoDJ/Queue.php#L132-L153 https://github.com/AzuraCast/AzuraCast/blob/4971ca1773053eaf13c8e363a88d3e88d5816632/src/Radio/AutoDJ/Queue.php#L501
3. `preventDuplicates` checks if the internal queue/`$eligibleTracks` array is empty, which is only useful for random playlists. This is moot for shuffled playlists, as there is already a check on [Line 483](https://github.com/AzuraCast/AzuraCast/blob/4971ca1773053eaf13c8e363a88d3e88d5816632/src/Radio/AutoDJ/Queue.php#L483) of Queue.php to see if it is empty before this function is run. If it is, then the function returns `null` and goes back to the `getRandomMediaIdFromPlaylist` function, returning as `null`. The functions trace back to the eligible playlists loop, as shown in step 2 above, with `$allowDuplicates` set to `true`.
4. An array titled `$latestSongIdsPlayed` is created containing the `timestamp_cued` (or `timestamp_start` if it doesn't exist) of all tracks in `$playedTracks`, associating that data with each track's `song_id`. An entry won't be made if that `song_id` is already in the array.
https://github.com/AzuraCast/AzuraCast/blob/4971ca1773053eaf13c8e363a88d3e88d5816632/src/Radio/AutoDJ/Queue.php#L533-L541
5. An array titled `$notPlayedEligibleTracks` is created containing all the track data, if that track's `song_id` is not in `$latestSongIdsPlayed`.
https://github.com/AzuraCast/AzuraCast/blob/4971ca1773053eaf13c8e363a88d3e88d5816632/src/Radio/AutoDJ/Queue.php#L545-L552
6. The `getDistinctTrack` function is run, passing the arrays just created as variables.
https://github.com/AzuraCast/AzuraCast/blob/4971ca1773053eaf13c8e363a88d3e88d5816632/src/Radio/AutoDJ/Queue.php#L554
7. `getDistinctTrack` creates arrays for duplicate artists, titles and `$latestSongIdsPlayed` (again).
https://github.com/AzuraCast/AzuraCast/blob/4971ca1773053eaf13c8e363a88d3e88d5816632/src/Radio/AutoDJ/Queue.php#L641-L643
   1. All titles and artists in `$playedTracks` are checked and entered into the arrays. Another `$latestSongIdsPlayed` array is created containing the `timestamp_cued` (or `timestamp_start` if it doesn't exist) of all tracks. An entry won't be made if that `song_id` is already in the array.
https://github.com/AzuraCast/AzuraCast/blob/4971ca1773053eaf13c8e363a88d3e88d5816632/src/Radio/AutoDJ/Queue.php#L645-L665
    2. All titles and artists in `$eligibleTracks` are checked for matches in the arrays. If a direct title match is found, the loop skips to the next track. If an artist match is found, the track data is entered into a new array titled `$eligibleTracksWithoutSameTitle`, associating that data with each track's `$mediaId`. If an artist match is not found, demonstrated with the `$artistMatchFound` variable remaining `false`, this track's `$mediaId` is returned to the `getShuffledMediaIdFromPlaylist` function and this track will be cued for playback.
https://github.com/AzuraCast/AzuraCast/blob/4971ca1773053eaf13c8e363a88d3e88d5816632/src/Radio/AutoDJ/Queue.php#L667-L701
    3. All tracks in `$eligibleTracksWithoutSameTitle` are checked for their `song_id` in `$latestSongIdsPlayed`. An array titled `$mediaIdsByTimePlayed` is created containing the track's value, which is the `timestamp_cued` (or `timestamp_start` if it doesn't exist), associating that data with each track's `$mediaId`. An entry will be assigned a value of '0' if a track is not matched. The array is then sorted in ascending order, according to the value, meaning all the not matched tracks will be first in the array, followed by the matched tracks sorted by timestamp. When an artist can not be avoided, a track with a title that has not been matched in `$latestSongIdsPlayed` will be played, as this will have a value of '0' in `$mediaIdsByTimePlayed`. 
https://github.com/AzuraCast/AzuraCast/blob/4971ca1773053eaf13c8e363a88d3e88d5816632/src/Radio/AutoDJ/Queue.php#L703-L711
    4. The function returns the first array key (`$mediaId`) in `$mediaIdsByTimePlayed`.
https://github.com/AzuraCast/AzuraCast/blob/4971ca1773053eaf13c8e363a88d3e88d5816632/src/Radio/AutoDJ/Queue.php#L713
8. If the `$mediaId` is no longer `null`, this is returned to the `getShuffledMediaIdFromPlaylist` function and this track will be cued for playback. If it is and `$allowDuplicates` is not `true`, then the function returns `null` and goes back to the `getShuffledMediaIdFromPlaylist` function, returning as `null`. The functions trace back to the eligible playlists loop, as shown in step 2 above, with `$allowDuplicates` set to `true`.
https://github.com/AzuraCast/AzuraCast/blob/4971ca1773053eaf13c8e363a88d3e88d5816632/src/Radio/AutoDJ/Queue.php#L556-L563
9. `$allowDuplicates` is set to `true`, so this block of code will now run. The `$allowDuplicates` variable in `preventDuplicates` is still passed as `false`, so the function will still return as `null`. The internal queue will be reset and `preventDuplicates` will be run a third time, with `$allowDuplicates` passed as `true`. I have noticed that if the final track has a direct title match in the `$titles` array, the internal queue will be reset at this step, which is not ideal.
https://github.com/AzuraCast/AzuraCast/blob/4971ca1773053eaf13c8e363a88d3e88d5816632/src/Radio/AutoDJ/Queue.php#L488-L499
10. As the internal queue has now been reset, the process restarts from step 4.
11. If the `$mediaId` remains `null`, there is no way to avoid a duplicate title or artist. The `$allowDuplicates` block of code is run. This is similar to the block of code in the `getDistinctTrack` function shown in Step 7 iii but uses the entire internal queue to return the least recently played track. This track's `$mediaId` is returned to the `getShuffledMediaIdFromPlaylist` function and this track will be cued for playback. This step will be infinite until you start getting tracks that haven't played within the duplicate prevention timeframe. This is common when you have a playlist with not enough unique titles or artists, to meet your duplicate prevention timeframe. You can avoid this by decreasing the timeframe, or adding more unique tracks to your playlist.
https://github.com/AzuraCast/AzuraCast/blob/4971ca1773053eaf13c8e363a88d3e88d5816632/src/Radio/AutoDJ/Queue.php#L565-L587

Earlier this year in conversations with @Vaalyn, one of the developers of AzuraCast, I suggested making duplicate prevention configurable per playlist and separating the feature so users can prevent duplicate titles or artists, or both. This may help you.

I also have thought of a new suggestion to store the original artist of a track in the database. This would be fetched from track metadata when uploaded, or added in the Music Files interface. This would mean different compositions with the same title, where they are not covers, will be allowed to be played. For example, _Jump_, _Best of My Love_, _Money_, _Shout_, _Gloria_, _Lady_, _Daniel_, _Photograph_, _A Thousand Years_, _America_, _Who's that Girl?_, to name a few.

I will wait for your reply and then, as the original issue has been fixed, will be closing this issue.

**Comment by Abqehebter** [comment] 2021-04-03 11:12
@MarkWasley So, where to start. First of all, thank you for the more than detailed explanation of how the AutoDJ with Shuffle/Random mainly works with the duplicate avoidance.
My intention was never to say here I send you the error and you just fix it. No, I was also rather the solution finder type, only I'm really not as well informed as you in the whole.

There is a lot of code behind it, a lot of time and really smart thinking, so I find it a pity that not so many dare to code. So hats off in the first place.

I must admit, I put the AutoDJ with me also strongly under pressure, I have a pretty long playlist (400-500 songs) and the rest is relatively short (around 100-200 songs) in a total of 12 stations.
There I could look myself, what I could improve. Thanks again for the tips at the end!

To the conclusion, I thank you nevertheless very much for the voluntary employment and am curious, in how far this everything is still adapted in the range AutoDJ and duplicate behavior. I hope, we will come back to it and are somehow still in contact with it.

But I think this step was important in this issue, that the shuffle playlist can shuffle properly again!

---
**Small question towards the end: I could take out of step 9-11 that it resets the internal queue only if the $title is the same, only with a duplicate artist it doesn't happen, correct? There I am currently unsure still.**

**Closed** 2021-04-10 01:44 UTC
Labels: bug, in progress
