### ISSUE TITLE
Repeating music from a single artist

### ISSUE THREAD

**Issue by Rafaelrds2017** [AzuraCast/AzuraCast#1341] opened 2019-03-24 15:25 UTC
Hello. He is repeating many songs from the same artist.
If  create a rule for this not to occur, I am grateful.

Ex: plays (x) artist, plays another song after a few minutes or hours.

**Comment by SlvrEagle23** [comment] 2019-03-25 10:42
@Rafaelrds2017 This is a duplicate of #181, which has been around for quite some time. Please follow that issue for updates.

**Closed by SlvrEagle23** 2019-03-25 10:42 UTC
