### ISSUE TITLE
Number of digits in the port for live encoder to other server is limited

### ISSUE THREAD

**Issue by rolradio** [AzuraCast/AzuraCast#1696] opened 2019-06-24 11:32 UTC
**Using Docker installation method**
YES

**Host Operating System**
Unbuntu 16

**Describe the bug**

I also use azuracast as an encoder for streaming live to radionomy. (with the live relay function) That works perfectly. (the live stream port is 11266 here)
However, my last new station has received a high live port. Namely port 37436
If I enter this in Azuracast and try to save it, I immediately get a message that this number is too large. Can I still adjust this somewhere so that I can enter it?
**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

The number of digits in the live encoder port to another server is limited, can I set it somewhere that a much higher port is possible?

**Comment by Vaalyn** [comment] 2019-06-24 11:57
If I'm not mistaken the problem is [this DB column](https://github.com/AzuraCast/AzuraCast/blob/master/src/Entity/StationRemote.php#L134). It is set to the type [`smallint`](https://mariadb.com/kb/en/library/smallint/) (signed) which is limited to the integer range -32768 to 32767. To fix this issue we should change this column from signed to unsigned so that it can fully represent all possible ports.

**Comment by rolradio** [comment] 2019-06-24 13:42
Super!!!
Thank you for the quick solution.
Thank you for all the work you do.

**Comment by SlvrEagle23** [comment] 2019-06-25 06:51
@rolradio The change by @Vaalyn has been merged into the application, so you should be able to update and see this issue be resolved.

**Closed by SlvrEagle23** 2019-06-25 06:51 UTC
Labels: bug

**Comment by rolradio** [comment] 2019-06-25 21:15
@SlvrEagle23 and @Vaalyn ..  Thank you!
