### ISSUE TITLE
playback errors

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#301] opened 2017-11-30 15:54 UTC
WebSocket connection to 'wss:/api/live/nowplaying/1' failed: Error during WebSocket handshake: Unexpected response code: 200 
When inserting the player to another site, these errors occur constantly

**Comment by susl16c** [comment] 2017-11-30 16:03
If I turn off the player, then there is a
 
        if (!($station instanceof Entity\Station) || !$station->isEnablePublicPage()) {
            throw new \App\Exception(_('Station not found!'));
        }

PHPSESSID	lle2fqdbq515mt4a494c7vrjpt
Session
APP_8AC97_referrer_login	Array ( )
APP_8AC97_auth_appauth_user	Array ( [user_id] => 1 )
APP_8AC97_alerts	Array ( )
nibble_forms	Array ( [_crsf_token] => Array ( ) )
APP_8AC97_csrf	Array ( [files] => Array ( [key] => TGzu2FfzaZ [timestamp] => 1512056351 ) )
Server/Request Data
USER	azuracast
HOME	/var/azuracast
HTTP_COOKIE	PHPSESSID=lle2fqdbq515mt4a494c7vrjpt
HTTP_ACCEPT_LANGUAGE	ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7
HTTP_ACCEPT_ENCODING	gzip, deflate, br

**Comment by SlvrEagle23** [comment] 2017-11-30 16:10
@susl16c It appears as if you're reporting the same issue as #300 and #297. I'm closing this as a duplicate of those.

**Closed by SlvrEagle23** 2017-11-30 16:10 UTC
