### ISSUE TITLE
Could not update (solved)

### ISSUE THREAD

**Issue by LordHelmchen666** [AzuraCast/AzuraCast#882] opened 2018-10-21 13:33 UTC
**Installation method**
Docker

**Host OS (for Docker installations)**
Ubuntu 16.04.

**Describe the bug**
When i run ./docker.sh update i get 

> ERROR: Couldn't find env file: /root/azuracast.env

**Comment by amavarick** [comment] 2018-10-21 13:50
I had the same problem, follow this to resolve.

https://mobile.twitter.com/AzuraCast/status/1053144044203896832

**Comment by LordHelmchen666** [comment] 2018-10-21 13:51
Thanks. Done it that way everything is fine.

**Comment by CodeSteele** [comment] 2018-10-21 14:39
Duplicate of #878

**Closed by CodeSteele** 2018-10-21 14:39 UTC
Labels: duplicate
