### ISSUE TITLE
Improved built-in player

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#434] opened 2018-02-15 07:51 UTC
Excuse me, please, I have an idea to improve the player. Is it possible to add a rewind of songs? If he gets a DJ, he should listen to the song before adding it to the air and it would not be bad that he could listen to them and rewind in the panel.
![cvdsvdsv](https://user-images.githubusercontent.com/23697714/36245826-0e28f47c-123e-11e8-9aa1-76a012244665.png)
Do not be angry at me, thank you very much for your hard work.

**Comment by SlvrEagle23** [comment] 2018-02-15 14:59
Closing as the built-in radio player is intended primarily as a _radio_ player, which would exclude any seeking functionality by design. The fact that it also can be used to preview media files in the file manager is entirely secondary to its main purpose.

**Closed by SlvrEagle23** 2018-02-15 14:59 UTC
