### ISSUE TITLE
Entity has to be managed or scheduled for removal for single computation

### ISSUE THREAD

**Issue by ecutsa** [AzuraCast/AzuraCast#1068] opened 2018-12-25 11:20 UTC
hello
i didnt find anything in the logs, i have a huge database of songs but it worked fine on other instances, i got this error on a fresh install after the first scan 

sudo -u azuracast  php /var/azuracast/www/util/cli.php  syn:run medium
Running Medium (5-minutes) Sync...

In UnitOfWork.php line 502:
                                                                                                                                     
  Entity has to be managed or scheduled for removal for single computation App\Entity\StationMedia@000000006d1b2abe000000003ef8abb4

**Comment by SlvrEagle23** [comment] 2018-12-27 00:45
Duplicate of #1052.

**Closed by SlvrEagle23** 2018-12-27 00:45 UTC
Labels: bug
