### ISSUE TITLE
Invalid stereotool library

### ISSUE THREAD

**Issue by CyberMixRo** [AzuraCast/AzuraCast#6644] opened 2023-10-03 05:44 UTC
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #0791831 (2023-10-01 5:33)

### What happened?

Hello,

Testing last rolling release ”Rolling Release #0791831 (2023-10-01 5:33)” i discover as StereoTool still have problems and can not be used: 

- upload succesfully now ”x86/64 Linux Thimeo-ST plugin” (https://download.thimeo.com/Stereo_Tool_Generic_plugin.zip)
- uploading Stereotool preset succesfully (are shared presets for stereotool available to download free at https://forums.stereotool.com/viewforum.php?f=10)
- restarting broadcasting (Liquidsoap and streaming server) to apply changes
- streaming server starting norma
- liquidsoap do not start and get this error:

`Error 14: Uncaught runtime error:
type: invalid,
message: "Invalid stereotool library",
stack: at audio.liq, line 232, char 6-73,
at audio.liq, line 232, char 6-73,
at /var/azuracast/stations/radio/config/liquidsoap.liq, line 193 char 8 - line 198 char 1`

Checking this error, it”s generated by loading the Stereotool library 

Please let me know if are necessary some more information for this issue fix.

Thank you

**Comment by BusterNeece** [comment] 2023-10-08 00:03
We can confirm this is an issue with the latest Stereo Tool plugin. On my end, I've confirmed that we're using the correct version for your architecture (i.e. `intel64` for `x86_64` arch), but Liquidsoap isn't liking it for some reason. Tagging @toots on this one and pending an upstream investigation into it.

**Comment by toots** [comment] 2023-10-15 22:49
This looks like a bug upstream. This simple example fails:
```c
#include <dlfcn.h>
#include <stdio.h>
#include <assert.h>

int main() {
  void *handle;
  void *(*stereoTool_Create)(const char* key);
  void (*stereoTool_Delete)(void *st_instance);

  handle = dlopen("/tmp/Stereo_Tool_Generic_plugin_1010/libStereoTool_intel64.so", RTLD_LAZY);
  stereoTool_Create = (void *(*)(const char* key)) dlsym(handle, "stereoTool_Create");

  void* st = stereoTool_Create(NULL);
  assert(st);

  stereoTool_Delete(st);
  dlclose(handle);
}
```

Compile:
```shell
$ gcc -o test ./test.c
```

Execute:
```shell
$ ./test

Warning: Cannot set realtime priority, run with sudo for realtime control.
./test: symbol lookup error: /tmp/Stereo_Tool_Generic_plugin_1010/libStereoTool_intel64.so: undefined symbol: _ZN9PresetsSTC1Eb

**Comment by toots** [comment] 2023-10-15 22:49
I'm emailing upstream.

**Comment by hansvanzutphen** [comment] 2023-10-15 23:41
This appears to be a bug in this specific build. For Intel/AMD, we have had requests to build a library without X11 dependencies, so we have 2 versions: One named libStereoTool_intel64.so and one libStereoToolX_intel64.so. The non-X version was still using our old (pre-version 10) preset system, but the files for that were not included, hence the missing PresetsST.

This is fixed in the latest beta version: https://download.thimeo.com/libStereoTool_BETA1011-015.zip

It only affects the non-X11 Intel/AMD Linux build; the Windows, macOS and ARM Linux builds should not be affected.

**Comment by BusterNeece** [comment] 2023-10-15 23:56
@hansvanzutphen Thank you for looking into this. Is it expected that the zip file format will change again like this? We've noticed fairly significant changes to the plugin folder structure with each released version, which has made it exceptionally difficult for us to process the files. Since StereoTool is proprietary, we can't bundle it with the app directly but instead instruct users to download it via the site and then upload the zip file, which means we have to write code that handles parsing these files as they're uploaded.

**Comment by hansvanzutphen** [comment] 2023-10-16 00:07
Sorry for the reorganization, I didn't realize that you let people upload the .zip file in its entirety!

What promted me to change them was actually that I thought that it would be hard for 'general' users to figure out which exact file they needed. The old file structure had been unchanged for many years, but we have kept adding new files to it, and some of the older file names did not indicate at all what the target system was.

The new layout should be much clearer, and we're not planning to make any further changes to it. But again, I wasn't aware that you were parsing it yourself. If you want, we can still provide a .zip file specificially for LiquidSoap which follows the old structure, for some time to come. At some point I would prefer that you move towards the new structure, since it's so much clearer for end users what's in it.

I was planning to put direct links to the library files on our site such that people don't need to download the .zip file anymore.  But if you're able to just parse the entire .zip file, that's probably easier because then people can't upload then wrong file.

Let me know what you want me to do with the file names and directory structure.

**Comment by BusterNeece** [comment] 2023-10-16 00:11
@hansvanzutphen We can absolutely update our code to parse the new format, that would be no problem, so there's no need to ship an older version just for Liquidsoap purposes. We just wanted to make sure the format wasn't still due to change again in the future, so I didn't spend any time writing a parser for that beta file only to have it change again.

One of the advantages of the old format is that it had the version of Stereotool being used in the actual extracted folder path, so we could use that to determine which version the user had uploaded. In the absence of that file, we'll have to do it the "right" way (i.e. possibly hooking into the .so file and seeing if there's a `getVersion`-type thing in there somewhere), but that would also allow users to upload the libStereoTool.so file directly, so it may end up being something we implement.

**Comment by hansvanzutphen** [comment] 2023-10-16 00:18
This is still a beta build, so I can easily put the version number back - that's just 2 lines of code.

There is this function:
stereoTool_GetSoftwareVersion

Which returns the version number * 1000 as an integer (should be 10110 for version 10.11; 9920 for 9.92).
BUT: This version number has no room for beta version indications. So if you want to be able to show beta versions as well, I should probably put it back in the directory structure.

**Comment by BusterNeece** [comment] 2023-10-16 00:20
@hansvanzutphen That would be great if it was in the directory structure. I'm looking into if there's a simple way for us to call functions inside arbitrary `.so` libraries via PHP without directly including them, and it's not looking simple, so string parsing would be preferred. :D

**Comment by BusterNeece** [comment] 2023-10-16 06:02
I've updated our Rolling Release version to allow the `libStereoTool_xx.so` files to be uploaded directly, which will allow users to upload the file from the new beta format even if we don't support extracting and parsing the zip file directly, giving folks another option (and also one that's significantly smaller when uploading).

I've tested with the latest version in the beta URL you provided above, and I can confirm that Liquidsoap works just fine with StereoTool enabled with that version.

**Comment by hansvanzutphen** [comment] 2023-10-16 08:19
Ok, great! Aside from that, here's the new .zip file format. The directory inside the .zip file is called libStereoTool_BETA1011-016 (for version 10.11, BETA016).
https://download.thimeo.com/libStereoTool_BETA1011-016.zip

 The directory inside the release version will just be called libStereoTool_1011 - I expect to release this version tomorrow.

**Comment by hansvanzutphen** [comment] 2023-10-16 08:22
Oh, just for info: The 32 bit ARM binaries are missing in this last .zip file. The 32 bit ARM build takes 24 hours to complete, I didn't want to wait for that.

**Comment by toots** [comment] 2023-10-16 13:52
Ha yes arm32 is annoying for compilation. We've been using a arm32 docker image run by a arm64 host to do the job, this seems to be working fine though creating the initial image was tricky.

**Closed** 2023-10-16 18:20 UTC
Labels: bug, upstream, needs investigation, liquidsoap 2.0
