### ISSUE TITLE
Liquidsoap Problem Connect DJ

### ISSUE THREAD

**Issue by sheiyla** [AzuraCast/AzuraCast#3659] opened 2021-01-11 20:24 UTC
**Using Docker installation method**
yes

**AzuraCast version**
latest

**Host Operating System**
Ubuntu 16.04

**Describe the bug**
2021/01/11 20:22:17 [lang:3] AzuraCast DJ Auth Response: Error: Cannot check permission with no user set. on /var/azuracast/www/src/Acl.php L136

**Comment by SC2Mitch** [comment] 2021-01-11 20:37
Duplicate of #3653

**Comment by Vaalyn** [comment] 2021-01-11 21:29
Closing as duplicate

**Closed by Vaalyn** 2021-01-11 21:29 UTC
Labels: duplicate
