### ISSUE TITLE
liquidsoap crashing randomly

### ISSUE THREAD

**Issue by nunotfc** [AzuraCast/AzuraCast#4919] opened 2021-12-23 14:28 UTC
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

59e5107 (2021-12-23 10:05) • Docker • PHP 8.1

### What happened?

hello,
dont know why and when but my station keeps crashing, sometings in the midle of a song giving error 404 and just playing the jingle playlists. i think liquidsoap is restarting.
i will provide some log.

### Relevant log output

```shell
http://www.renovagames.com/log.txt
```

**Comment by SlvrEagle23** [comment] 2021-12-23 15:06
This might be a duplicate of #4897. Please post the log you have into that thread and follow it for updates, as we're working with the Liquidsoap team to identify and fix any issues that may be appearing.

**Closed by SlvrEagle23** 2021-12-23 15:06 UTC
Labels: needs investigation
