### ISSUE TITLE
Streaming to an external icecast2-server fails with hostname but not IP

### ISSUE THREAD

**Issue by MrSteelMiner** [AzuraCast/AzuraCast#1303] opened 2019-03-14 13:06 UTC
I tried to connect and stream to an external icecast2-server but it's not working. What have I to do?
My external icecast2-server is running v2.4.2 on port 80.
Mount-Config:
`    <mount type="normal">
        <mount-name>/dev1</mount-name>
        <username>dev1</username>
        <password> _HIDDEN_ </password>
        <relay-shoutcast-metadata>1</relay-shoutcast-metadata>
        
        
        <fallback-mount>/laut_sr</fallback-mount>
        <fallback-override>1</fallback-override>
    </mount>`
Streaming from butt-software is working to this mount.

In azuracast-webinterface I use the following config:
`Remote Station Listening URL: http://name.domain:80
Remote Station Listening Mountpoint/SID: /dev1
Broadcast AutoDJ to Remote Station: Yes
AutoDJ Format: MP3
AutoDJ Bitrate (kbps): 320
Remote Station Source Port: 80
Remote Station Source Mountpoint/SID: _empty_
Remote Station Source Username: dev1
Remote Station Source Password: _HIDDEN_
YP-directory: false`

I restarted the station multiple times (update-installation and so on), but azuracast isn't connecting to icecast.
Liquid-Soap-Config (Log Viewer):
`output.icecast(%mp3(samplerate=44100, stereo=true, bitrate=320, id3v2=true), id="party_relay_2", host = "name.domain", port = 80, user = "dev1", password = "_HIDDEN_", mount = "/dev1", name = "StayRadio Party", description = "Dein Party-Sender", genre = "Party", url = "https://stayradio.de", public = false, encoding = "UTF-8", radio)`

Note:
`_HIDDEN_` is of course replaced by the real password, same for `name.domain`

Thanks in advance!

**Comment by MrSteelMiner** [comment] 2019-03-14 13:08
Liquidsoap Log:
`2019/03/14 14:07:49 [party_relay_1:2] Connection failed: Failure("inet_addr_of_string")
2019/03/14 14:07:49 [party_relay_1:3] Will try again in 3.00 sec.
2019/03/14 14:07:49 [party_relay_2:3] Connecting mount /dev1 for dev1@name.domain...
2019/03/14 14:07:49 [party_relay_2:2] Connection failed: Failure("inet_addr_of_string")
2019/03/14 14:07:49 [party_relay_2:3] Will try again in 3.00 sec.`

**Comment by MrSteelMiner** [comment] 2019-03-14 13:12
seen this https://github.com/savonet/liquidsoap/issues/496
I will try using the IP and not the hostname

**Comment by Vaalyn** [comment] 2019-03-16 00:15
This issue is related to the same underlying issue as #756 which was already fixed for the docker installations by an OPAM update a while ago. Around 3 days ago there was an update to the ansible scripts to use OPAM 2. Which version of AzuraCast are you currently using?

**Comment by MrSteelMiner** [comment] 2019-03-18 08:09
latest version. Still not working with hostname

**Comment by Vaalyn** [comment] 2019-03-18 12:25
Could you check which OPAM version you've installed?

**Comment by MrSteelMiner** [comment] 2019-03-18 14:04
Version 2.0.2

**Comment by preterive** [comment] 2019-03-25 14:31
Sam Problem, is a bug of liquidsoap i think. Error: inet_addr_of_string

It was already there in 1.3.3 and got fixed in 1.3.3-1 .

**Comment by preterive** [comment] 2019-03-25 14:32
@MrSteelMiner is this a laut.fm Station too? Please watch my thread in the laut.fm Forum

**Comment by MrSteelMiner** [comment] 2019-03-25 14:44
Yes, it's a laut.fm station. But it doesn't work with my own icecast either. So I use the IP as workaround and so I can live with it

**Comment by Vaalyn** [comment] 2019-03-25 14:44
@preterive AzuraCast should already be using Liquidsoap v1.3.6 meaning this issue should be fixed already. If you have any additional information regarding this issue 

@MrSteelMiner What version of Liquidsoap is running on your installation? (`liquidsoap --version`)

**Comment by MrSteelMiner** [comment] 2019-03-25 14:46
@Vaalyn 1.3.6

**Comment by preterive** [comment] 2019-03-25 14:47
Hello,
i have the same problem like @MrSteelMiner since i updated to Version 1.3.6

**Comment by Vaalyn** [comment] 2019-03-25 14:50
Okay, and you both are using Laut.fm, correct?

Can you test if this problem may be related to Laut.fm and if that feature works correctly with other external relays?

**Comment by MrSteelMiner** [comment] 2019-03-25 14:52
@Vaalyn I tested it with a normal icecast and this also doesn't work (tested it 2 weeks ago)

**Comment by Vaalyn** [comment] 2019-03-25 14:53
@MrSteelMiner Thank you for the information. Then it's pretty clear that the general functionality has a problem that is not caused by a single 3rd party.

**Comment by SlvrEagle23** [comment] 2019-03-25 14:54
@MrSteelMiner @preterive What installation type are you all using?

This could be caused by a failure of either the host OS or container OS to resolve a domain name. With Docker, DNS resolution should always point to your host's DNS resolver configuration, which you may need to update to reference an external DNS resolver (i.e. 1.1.1.1 for CloudFlare or 8.8.8.8 for Google)

**Comment by MrSteelMiner** [comment] 2019-03-25 14:56
the host (traditional installation) resolves the hostname correctly (ping).

**Comment by SlvrEagle23** [comment] 2019-03-25 15:03
@MrSteelMiner @preterive @Vaalyn Figured this one out. When LS fixed it, the fix was actually with the `cry` OCaml library, not with LS itself. They published 0.6.1 as a fix, but we hard-lock our dependencies on OPAM to avoid unexpected update issues, and we had locked to 0.6.0, which didn't have the fix.

Updating both the Docker and bare-metal installations now to resolve that.

**Comment by SlvrEagle23** [comment] 2019-03-25 15:09
@MrSteelMiner @preterive @Vaalyn Docker image is now rebuilding on the Docker Hub; if you're on bare-metal you can run the updater script now and it should bring you to the newest version, which should fix the issue.

**Comment by preterive** [comment] 2019-03-25 15:12
Thanks! I would try it now.

**Comment by preterive** [comment] 2019-03-25 15:28
Works, could be closed.

**Comment by SlvrEagle23** [comment] 2019-03-25 15:30
Good to hear. New Docker image has finished building and is live as well.

**Closed by SlvrEagle23** 2019-03-25 15:30 UTC
Labels: error
