### ISSUE TITLE
Live disconnection and reconnection of playlists.

### ISSUE THREAD

**Issue by Ilario42** [AzuraCast/AzuraCast#669] opened 2018-07-15 10:03 UTC
Hello. I'm doing some live streaming of the radio, but when I disconnect and start the playlist, cover and title remain blocked by the last song before direct

**Comment by SlvrEagle23** [comment] 2018-08-16 11:01
@Ilario42 This is unfortunately a common problem experienced by many people streaming live broadcasts via Icecast and Shoutcast. It isn't a problem caused by AzuraCast but rather a problem that is common to most streaming environments: when you first connect as a live DJ, the broadcast doesn't receive and process the metadata that you initially connected with until it changes, at which point it receives and processes the change.

The easy fix for this is to always play a short bumper song when connecting, maybe 15-30 seconds, then immediately fade to another song, which will trigger the necessary metadata update. If you're manually updating metadata for your live broadcast, be sure to send the update at least once after connecting to ensure the streaming software receives it correctly.

**Closed by SlvrEagle23** 2018-08-16 11:01 UTC
Labels: bug
