### ISSUE TITLE
unable to install or update azuracast

### ISSUE THREAD

**Issue by silvaalex2021** [AzuraCast/AzuraCast#4151] opened 2021-05-09 23:26 UTC
hello,

it started with me not being able to update my azuracast installation on ubuntu 20.04, as I commented here: https://github.com/AzuraCast/AzuraCast/discussions/4150

now i have created new testing instances (ubuntu 18.04 and 20.04) to test and am also not able to install azracast on 
these instances.

There are no error messages during installation. the only thing that goes wrong is a "timeout when waiting for services to start".

when trying to access the dashboard, I get a "502 bad gateway" error.

any ideas?

**Comment by SC2Mitch** [comment] 2021-05-10 00:52
@silvaalex2021 can you attempt to install or update again? We have since resolved the issue.

**Comment by SC2Mitch** [comment] 2021-05-10 10:50
We have confirmed this issue has been since resolved in the latest release.

**Comment by nagraniadvbt2020** [comment] 2021-05-10 10:51
I also can't install AzuraCast - I get 502 Bad Gateway or File not found or AzuraCast installs, but Icecast2 and Liquidsoap don't work

**Closed by SC2Mitch** 2021-05-10 10:50 UTC
Labels: bug, in progress
