### ISSUE TITLE
Play Once per x Songs Error

### ISSUE THREAD

**Issue by emiryapici** [AzuraCast/AzuraCast#3022] opened 2020-07-11 10:17 UTC
**Using Docker installation method**

Yes
**AzuraCast version**

v.0.10.3 #e850aa1
**Host Operating System**

Ubuntu 18.04.4
**Describe the bug**

I have a playlist that includes my radio jingles. I have set it to play between 1 song but sometimes it plays 2 jingles, no songs.

**Expected behavior**

It should play only one jingle between songs

**Comment by ogrenci01** [comment] 2020-07-16 16:30
Hi @emiryapici;

This is a known issue. The AzuraCast Team is working on the issue. You can be a little patient.

**Comment by SlvrEagle23** [comment] 2020-07-17 23:26
Closing as a likely duplicate of #2631.

**Closed by SlvrEagle23** 2020-07-17 23:26 UTC
