### ISSUE TITLE
Nginx cannot handle URL Stub with - in it

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#5147] opened 2022-02-22 02:29 UTC
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Latest rolling 

### What happened?

I was debugging a machine for a user and noticed this issue coming up a fair amount, I was able to locate it to Nginx not liking our URL Stubs using the `-` in them

We should also see if it's possible to add a migration in to change this for users automatically to remove the `-` from the URL path. 

### Relevant log output

```shell
web_1       | 2022/02/22 02:23:14 [error] 93#93: *1 open() "/usr/share/nginx/html/pub/testing-_" failed (2: No such file or directory), client: 127.0.0.1, server: , request: "POST /pub/testing-_ HTTP/1.1", host: "localhost:9010"
```

**Comment by Vaalyn** [comment] 2022-02-22 02:50
Closing as duplicate of #3696

**Closed by Vaalyn** 2022-02-22 02:50 UTC
Labels: needs investigation
