### ISSUE TITLE
Scheduled Playlists

### ISSUE THREAD

**Issue by s7ntax** [AzuraCast/AzuraCast#5638] opened 2022-08-01 12:19 UTC
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.17.1 Stable

### What happened?

Has anyone ever got this to work. I have tried many times and the scheduled time comes and goes and nothing happens. I set it to interrupt other songs at scheduled playlist time but nothing.

The only way I can broadcast a play list at a set time is to disable the other playlists and restart broadcasting, then skip any tracks that were previously in the queue, even that is problematic and often fails to play the playlist.

It is very difficult to control any of the autoplay functions in Azuracast because of this.

**Comment by samtypicalgamer** [comment] 2022-08-14 08:57
I’m having this same issue too and it’s supposed to re broadcast a national show I run it’s not playing at the scheduled time. It just continues with the normal music playlist.

**Comment by SlvrEagle23** [comment] 2022-08-15 01:28
Duplicate of #5632.

**Closed by SlvrEagle23** 2022-08-15 01:28 UTC
Labels: needs investigation

**Comment by advtelecom** [comment] 2022-09-07 10:15
I saw that when setting the times in the "schedule" the main error is that the page on the browser is not updated. I'll explain. After saving the schedule in a playlist and subsequently changing the schedule in another playlist, it happens that I see the times set in the previous playlist. I saw that the problem is solved if every time I save I refresh the browser. This is the current version installed:
Rolling Release #[53080b1](https://github.com/AzuraCast/AzuraCast/commit/53080b15be4cf39ff18afdaa122d4cc3b526ad7f) (2022-08-23 4:36) • Docker • PHP 8.1
