### ISSUE TITLE
public page music is dead

### ISSUE THREAD

**Issue by hillbilly-mark** [AzuraCast/AzuraCast#1893] opened 2019-08-21 01:06 UTC
This issue started 2 updates ago and was not corrected in the last release.

The music no longer plays from the public page or the iframe api.

I found the solution dated 23 days ago but these setting still evade me.  Where are the located?  How should they be set for a docker install of azuracast?

**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
See above

**To Reproduce**
https://vps8.hillbillyradio.net/public/rock

**Expected behavior**
To hear the music

**Relevant Logs**
Nothing stands out.  Plenty of warning.  The most relevant looking lines are:
[2019-08-20 23:12:18] WARN connection/get_ssl_certificate Invalid private key file /etc/nginx/ssl/ssl.key (system lib) [2019-08-20 23:12:18] WARN slave/slave_startup process has 65536 max file descriptor limit [2019-08-20 23:12:50] WARN connection/get_ssl_certificate Invalid private key file /etc/nginx/ssl/ssl.key (system lib) [2019-08-20 23:12:50] WARN slave/slave_startup process has 65536 max file descriptor limit 

**Screenshots**

**Device(s):**
 - Device: any
 - OS: any
 - Browser: any
 - Version: any

**Additional context**
I expect this to be handled in the latest update but the problem is still there.  At this point i regret making the last two update.  Highly recommended should really say use with extreme caution.  This update could break your stream.

**Comment by SlvrEagle23** [comment] 2019-08-21 01:10
@hillbilly-mark Our recent updates didn't break streams across the world, so it isn't necessary for us to warn that the updates should be applied with "extreme caution".

In your case, it appears you're using a service like CloudFlare that's preventing direct access to port 8000. There's a setting called "Use Web Proxy for Radio" near the top of the system settings form (available from the System Administration page) that you can turn on to work around this limitation.

**Comment by hillbilly-mark** [comment] 2019-08-21 01:23
I am not using cloudflair or any such service.  This is served from vitual machine with all ports open.  No other containers use anything in 8000 range

The music relays to non ssl icecast relays just fine.  It breaks on the web pages using default streams.  If you choose a sfc choice from the player dropdown you will find music.  But at this point you have broken the page encryption.   I believe it is a ssl problem.

**Comment by SlvrEagle23** [comment] 2019-08-21 01:25
@hillbilly-mark I have not broken your server's encryption. None of the updates I have released in the recent few months have had anything to do with how we serve SSL certificates, with LetsEncrypt or nginx.

If you turn on the setting I referred to, does it fix the issue? From my own tests with your server it absolutely should.

**Comment by hillbilly-mark** [comment] 2019-08-21 01:38
I meant it as the non encyrpted muic feed breaking it.  Which is what to expect.   Not you personally.  I found the web proxy setting.  That was the fix.  Thank you.  Btw.  I love azuracast.  You have taken liquidsoap , one of the hardest known apps to install, to new heights.  Keep on rockin!

**Comment by SlvrEagle23** [comment] 2019-08-21 01:46
@hillbilly-mark Thank you. Glad the issue is resolved.

**Closed** 2019-08-21 01:46 UTC
Labels: error
