### ISSUE TITLE
Now playing artist field empty

### ISSUE THREAD

**Issue by HDman** [AzuraCast/AzuraCast#3255] opened 2020-10-09 13:03 UTC
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #c65e686 (2020-10-09 9:38) • Docker • PHP 7.4

**Host Operating System**
Ubuntu 20.04.1 LTS

**Describe the bug**
Now playing song title, don't show correcly. Both artist and title (artist - title) are on the same row. In Dashboard and Public page. 
I don't use AutoDJ, only livestream. Is this correct layout? or is this new and it should look like this? I really what to know.

The artist field is still there: "now-playing-artist". I wish song title still should split up. It's looks so much better.
![image](https://user-images.githubusercontent.com/18250650/95584702-6f826a00-0a3e-11eb-90e0-1cb1815ce01d.png)
HTML from Public page

![image](https://user-images.githubusercontent.com/18250650/95582933-b15de100-0a3b-11eb-9130-20c8a118d1c7.png)
Public page

![image](https://user-images.githubusercontent.com/18250650/95583289-2e895600-0a3c-11eb-946b-964f7f4540d6.png)
Dashboard

**Expected behavior**
Row 1: title
Row 2: artist
![image](https://user-images.githubusercontent.com/18250650/95582913-a440f200-0a3b-11eb-92d0-542c9eadfec8.png)
Public page

![image](https://user-images.githubusercontent.com/18250650/95583965-3ac1e300-0a3d-11eb-9649-ccd84db68416.png)
Dashboard

**Device(s):**
 - Device: Desktop
 - OS: Windows 10
 - Browser: chrome
 - Version: 86.0.4240.75 (Officiell version) (64 bitar)

**Comment by SlvrEagle23** [comment] 2020-10-09 19:57
Duplicate of #3226.

**Closed by SlvrEagle23** 2020-10-09 19:57 UTC
