### ISSUE TITLE
Exception after updateto the latest veriosn

### ISSUE THREAD

**Issue by aripisprecer** [AzuraCast/AzuraCast#1018] opened 2018-12-02 17:12 UTC
**Installation method**
"Traditional" installation method.

**Host OS (for Docker installations)**
Ubuntu 18.04.1

**Describe the bug**
I got an error when trying to update to the latest version.
Please see below the console logs and the logs displayed on the AzuraCast panel.

**Relevant Logs**
The console logs when i've tried to update:
`TASK [azuracast-setup : Run AzuraCast Setup (Update Mode)] ****************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/util/cli.php azuracast:setup --update", "delta": "0:00:04.202852", "end": "2018-12-02 16:57:19.772801", "msg": "non-zero return code", "rc": 1, "start": "2018-12-02 16:57:15.569949", "stderr": "\nIn AbstractMySQLDriver.php line 126:\n                        \n  An exception occurred while executing 'ALTER TABLE `song_history` DROP FORE  \n  IGN KEY FK_2AD16164A0BDB2F3':                                                \n                     \n  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN   \n  KEY `FK_2AD16164A0BDB2F3`; check that it exists                              \n                  \n\nIn PDOConnection.php line 109:\n          \n  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN   \n  KEY `FK_2AD16164A0BDB2F3`; check that it exists                              \n       \n\nIn PDOConnection.php line 107:\n                                                                               \n  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN   \n  KEY `FK_2AD16164A0BDB2F3`; check that it exists                              \n                                                                               \n\nazuracast:setup [--update] [--load-fixtures]", "stderr_lines": ["", "In AbstractMySQLDriver.php line 126:", "                                                                 ", "  An exception occurred while executing 'ALTER TABLE `song_history` DROP FORE  ", "  IGN KEY FK_2AD16164A0BDB2F3':                                                ", "                                                                    ", "  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN   ", "  KEY `FK_2AD16164A0BDB2F3`; check that it exists                              ", "                                                                       ", "", "In PDOConnection.php line 109:", "                                                                     ", "  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN   ", "  KEY `FK_2AD16164A0BDB2F3`; check that it exists                              ", "                                                                        ", "", "In PDOConnection.php line 107:", "                                                                      ", "  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN   ", "  KEY `FK_2AD16164A0BDB2F3`; check that it exists                              ", "                                                                         ", "", "azuracast:setup [--update] [--load-fixtures]"], "stdout": "\nAzuraCast Setup\n===============\n\nWelcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...\n * Environment: Production\n * Installation Method: Traditional\n\n ! [NOTE] Running in update mode.                                              \n\nMigrating Legacy Configuration\n------------------------------\n\nConfiguration already set up.\n\nSetting Up InfluxDB\n-------------------\n\nDatabase created.\nRetention policies updated.\nContinuous queries created.\nInfluxDB databases created.\nRouter cache file cleared.\nLocal cache flushed.\n\nRunning Database Migrations\n---------------------------\n\nLoading configuration from the integration code of your framework (setter).\n                                                                \n                    Doctrine Database Migrations           \n                                                                    \n\nMigrating up to 20181126073334 from 20180826011103\n\n  ++ migrating 20180826043500\n\n     -> ALTER DATABASE `azuracast` CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci\n     -> ALTER TABLE `song_history` DROP FOREIGN KEY FK_2AD16164A0BDB2F3\nMigration 20180826043500 failed during Execution. Error An exception occurred while executing 'ALTER TABLE `song_history` DROP FOREIGN KEY FK_2AD16164A0BDB2F3':\n\nSQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN KEY `FK_2AD16164A0BDB2F3`; check that it exists", "stdout_lines": ["", "AzuraCast Setup", "===============", "", "Welcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...", " * Environment: Production", " * Installation Method: Traditional", "", " ! [NOTE] Running in update mode.                                               ", "", "Migrating Legacy Configuration", "------------------------------", "", "Configuration already set up.", "", "Setting Up InfluxDB", "-------------------", "", "Database created.", "Retention policies updated.", "Continuous queries created.", "InfluxDB databases created.", "Router cache file cleared.", "Local cache flushed.", "", "Running Database Migrations", "---------------------------", "", "Loading configuration from the integration code of your framework (setter).", "        ", "                    Doctrine Database Migrations                    ", "                             ", "", "Migrating up to 20181126073334 from 20180826011103", "", "  ++ migrating 20180826043500", "", "     -> ALTER DATABASE `azuracast` CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci", "     -> ALTER TABLE `song_history` DROP FOREIGN KEY FK_2AD16164A0BDB2F3", "Migration 20180826043500 failed during Execution. Error An exception occurred while executing 'ALTER TABLE `song_history` DROP FOREIGN KEY FK_2AD16164A0BDB2F3':", "", "SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN KEY `FK_2AD16164A0BDB2F3`; check that it exists"]}

PLAY RECAP ****************************************************************************************************************
localhost                  : ok=15   changed=3    unreachable=0    failed=1`

The logs on the Azura Cast panel:
`500

An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.short_name AS short_name_3, t0.is_enabled AS is_enabled_4, t0.frontend_type AS frontend_type_5, t0.frontend_config AS frontend_config_6, t0.backend_type AS backend_type_7, t0.backend_config AS backend_config_8, t0.adapter_api_key AS adapter_api_key_9, t0.description AS description_10, t0.url AS url_11, t0.genre AS genre_12, t0.radio_base_dir AS radio_base_dir_13, t0.radio_media_dir AS radio_media_dir_14, t0.nowplaying AS nowplaying_15, t0.nowplaying_timestamp AS nowplaying_timestamp_16, t0.automation_settings AS automation_settings_17, t0.automation_timestamp AS automation_timestamp_18, t0.enable_requests AS enable_requests_19, t0.request_delay AS request_delay_20, t0.request_threshold AS request_threshold_21, t0.disconnect_deactivate_streamer AS disconnect_deactivate_streamer_22, t0.enable_streamers AS enable_streamers_23, t0.is_streamer_live AS is_streamer_live_24, t0.enable_public_page AS enable_public_page_25, t0.needs_restart AS needs_restart_26, t0.has_started AS has_started_27, t0.api_history_items AS api_history_items_28, t0.current_streamer_id AS current_streamer_id_29, t0.current_streamer_id AS current_streamer_id_30 FROM station t0': SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.genre' in 'field list'
AbstractMySQLDriver.php : 80 `

**Comment by SlvrEagle23** [comment] 2018-12-02 17:15
@aripisprecer This is usually caused by an update being interrupted partially through the process, or otherwise failing mid-migration. Resolving this issue is frankly quite difficult, as your database is in a state of being halfway between one migration and another.

When was the last time you updated?

**Comment by aripisprecer** [comment] 2018-12-02 17:19
The last time was in june and since than, every update fails.

**Comment by aripisprecer** [comment] 2018-12-02 17:29
i would try to manually execute the scripts. I have a backup of the container wher AzuraCast in installed.

Could you guide me trough?

**Comment by CodeSteele** [comment] 2018-12-04 05:43
I would probably argue to just export your music and re-import into a new instance, this will likely be a bit of work if we're looking at months of patches being bad.

**Closed** 2019-02-16 18:15 UTC
Labels: error, wontfix
