### ISSUE TITLE
Can't Upload Files

### ISSUE THREAD

**Issue by SagnikSRHUSE** [AzuraCast/AzuraCast#1197] opened 2019-02-19 16:43 UTC
**Installation method**
Docker

**Host OS (for Docker installations)**
Debian 9 Stretch

**Describe the bug**
After creating a Station, the Base Station Directory and Custom Media Directory remain unpopulated as a result of which, new files cannot be uploaded.

**Expected behavior**
Files should upload

**Relevant Logs**
`web_1       | Feb 19 16:39:39 7b11953009f4 php-fpm[46]: [WARNING] [pool www] child 60 said into stderr: "[2019-02-19 16:39:39] AzuraCast.ERROR: Impossible to create the root directory "/album_art". mkdir(): Permission denied {"file":"/var/azuracast/www/vendor/league/flysystem/src/Adapter/Local.php","line":113,"code":0} []"`

**Comment by SlvrEagle23** [comment] 2019-02-19 17:08
@SagnikSRHUSE This is a valid bug that was caused by some changes I made to how the station form is processed under the hood.

If you created a station while this issue was present, you may want to update your installation and recreate the station to ensure all the proper directories are set and the configuration is written. Otherwise, the bug should be fixed now.

**Closed by SlvrEagle23** 2019-02-19 17:08 UTC
Labels: bug

**Comment by SagnikSRHUSE** [comment] 2019-02-19 17:29
Updating and recreating the station worked fine. Thanks for the quick fix.
