### ISSUE TITLE
Slim Application Error / Backups

### ISSUE THREAD

**Issue by zloysystem** [AzuraCast/AzuraCast#4486] opened 2021-08-13 20:04 UTC
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #019c294 (2021-08-08)

### What happened?

Good day gentlemen.
you can reproduce this error:
https://*******/admin/backups/configure
1) Setting up backups
2) choose a scheduled backup time
3) save
> * it is when the copy time parameter is selected that the error occurs

.

**Comment by SC2Mitch** [comment] 2021-08-13 20:15
Verified.

**Comment by Abqehebter** [comment] 2021-08-13 21:31
Already fixed in the latest rolling release version. See here: https://github.com/AzuraCast/AzuraCast/issues/4467

**Comment by Vaalyn** [comment] 2021-08-13 21:35
The error mentioned by @Abqehebter is fixed in the latest rolling-release but there seems to be another issue there although I'm not sure if it's the one that's being discussed here. This happens on the latest-rolling release when saving with an empty `Number of Backup Copies to Keep` field due to a type error in our forms library:

```
AzuraCast.ERROR: round(): Argument #1 ($num) must be of type int|float, string given {"file":"/var/azuracast/www/vendor/azuracast/azuraforms/src/Field/Number.php","line":28,"code":0} []
```

**Comment by Abqehebter** [comment] 2021-08-13 21:38
Absolutely right, I didn't notice. I can reproduce this:

`Slim Application Error`

**Comment by Vaalyn** [comment] 2021-08-13 21:41
@zloysystem @SC2Mitch is the error you both found the same as the one I posted above?

**Comment by SC2Mitch** [comment] 2021-08-13 21:47
Correct ^^

**Comment by zloysystem** [comment] 2021-08-13 22:12
when filling in all the fields except the time, the error does not occur, that's why I wrote that when filling out the field, the time)

**Comment by Abqehebter** [comment] 2021-08-13 22:31
@zloysystem All good, I just read over it because the error so already existed :)

**Comment by zloysystem** [comment] 2021-08-14 11:34
@Abqehebter and by the way, the panel does not have a notification about the update to the Rolling Release # aa6b197 (2021-08-13)

**Comment by Abqehebter** [comment] 2021-08-14 11:35
Did you turn off the notification?

**Closed** 2021-08-14 11:35 UTC
Labels: bug, stable, rolling-release

**Comment by zloysystem** [comment] 2021-08-14 11:42
@Abqehebter no, they are always on, that's the point, I didn't know about the update ...

**Comment by zloysystem** [comment] 2021-08-14 11:45
@Abqehebter updated in the usual way, the problem went away, but there were no notifications, I always try to update to the latest temporary version, but here there is no call, no hello))
thanks everyone for your time😎
