### ISSUE TITLE
Detailed listener statistics

### ISSUE THREAD

**Issue by jonikane** [AzuraCast/AzuraCast#479] opened 2018-03-10 21:23 UTC
Is it possible to have detailed statistics of the listeners, by country, by player, by browser, as in Centova cast or similar?
![report_listeners_stats](https://user-images.githubusercontent.com/7109309/37246854-4280682c-24a9-11e8-8971-859296ce922c.jpg)

**Comment by SlvrEagle23** [comment] 2018-03-11 05:18
Closing as a duplicate of #309 .

The reason you're not seeing this item immediately fulfilled is because it's significantly more difficult to implement than you might be thinking. Our current statistics system doesn't store this level of detail over a long span of time, and it would require re-engineering our entire time-series storage to add those fields.

In the end, it would certainly be nice to have this granular of information (which is why I've left the previous ticket open, as it is something that I will eventually get back around to, given enough time and energy), but it's not something I can implement quickly on my own.

**Closed by SlvrEagle23** 2018-03-11 05:18 UTC
