### ISSUE TITLE
File view of playlist does not display songs 

### ISSUE THREAD

**Issue by pixel-paul** [AzuraCast/AzuraCast#3098] opened 2020-08-20 11:22 UTC
**Using Docker installation method**
Yes

**AzuraCast version**
Powered by AzuraCast • v0.10.3, #e9c79f2 (2020-08-18 4:16) Rolling

**Host Operating System**
CentOS7

**Describe the bug**
List view of playlist does not show tracks

**To Reproduce**

1. Go to 'Playlists'
2. Click on 'No. of Songs link'
3. No songs are displayed

**Expected behavior**
A list of songs in the playlist (in this example, it should display 132 tracks)

**Screenshots**
![Screenshot_2020-08-20 Music Files](https://user-images.githubusercontent.com/389303/90764112-bf1aa400-e2df-11ea-95eb-8e1e79778cdd.png)

**Comment by SlvrEagle23** [comment] 2020-08-20 14:51
If you open your web inspector console (usually F12), then click "Network", then retry loading the page, you may be able to see an error message (if there is one).

In this case, I suspect it may also be caused by your playlist having spaces in its name.

**Comment by LordHelmchen666** [comment] 2020-08-20 14:54
I get the same error.

> Source-Map-Fehler: Error: request failed with status 404
> Ressourcen-Adresse: https://stream.eisradio.de/static/dist/lib/bootstrap/bootstrap-7fd2f04e75.bundle.min.js
> Source-Map-Adresse: bootstrap.bundle.min.js.map
> Source-Map-Fehler: Error: request failed with status 404
> Ressourcen-Adresse: https://stream.eisradio.de/static/dist/lib/bootstrap-vue/bootstrap-vue-484d959dc2.min.js
> Source-Map-Adresse: bootstrap-vue.min.js.map
> Source-Map-Fehler: Error: request failed with status 404
> Ressourcen-Adresse: https://stream.eisradio.de/static/dist/lib/moment/moment-7b3adc3f29.min.js
> Source-Map-Adresse: moment.min.js.map
> Source-Map-Fehler: Error: request failed with status 404
> Ressourcen-Adresse: https://stream.eisradio.de/static/dist/lib/moment/locales-36c20445a3.min.js
> Source-Map-Adresse: locales.min.js.map
>

**Comment by pixel-paul** [comment] 2020-08-20 17:10
It looks like the JSON response is empty:

`GET https://my.stream.fm/api/station/1/files/list?internal=true&rowCount=0&current=1&searchPhrase=playlist:Tuesday&file=`

Response payload:

'{"current":1,"rowCount":0,"total":0,"rows":[]}'

In this case, there is 1 track in the playlist

**Comment by SlvrEagle23** [comment] 2020-08-24 04:03
@beefour Good catch. This optimization is helpful in the general file exploring sense (by avoiding pulling unnecessary media records when browsing the root directory of very large, hierarchical collections), but it does seem to have broken playlist searching.

Will work on this shortly.

**Comment by SlvrEagle23** [comment] 2020-08-24 04:14
This should be fixed as of the latest update.

**Closed by SlvrEagle23** 2020-08-24 04:14 UTC
Labels: bug, in progress

**Comment by pixel-paul** [comment] 2020-08-24 08:01
Thanks @SlvrEagle23.
