### ISSUE TITLE
Using Custom ssl Certificate .cer

### ISSUE THREAD

**Issue by DanRedA** [AzuraCast/AzuraCast#4162] opened 2021-05-13 01:12 UTC
**Using Docker installation method?**
Yes

**AzuraCast version:**
Latest version

**Host Operating System:**
Ubuntu 20.04

**Describe the bug:**
Custom certificate not applied

**Steps to reproduce:**

Hi,
I bought a domain name which I pointed to a vm on oracle cloud, where i made the docker installation.
With the domain name I received a ssl certificate which consisted of three files: a private key (.key), a primary certificate (.cer), and an intermediate certificate (.cer) by digicert.
On the digicert website they have an instructions page for installing certificates on nginx installations (https://www.digicert.com/kb/csr-ssl-installation/nginx-openssl.htm) where one needs to concatenate the primary and intermediate files in to a bundle.crt file.

I then followed the azuracast docs instructions for using the custom certificate, I used the bundle.crt file in the docker-compose.override.yml:

version: '2.2'

services: 
  nginx_proxy:
    volumes: 
      - /home/ubuntu/prueba/bundle.crt:/etc/nginx/certs/frentelocalradio.com.crt:ro
      - /home/ubuntu/prueba/_.frentelocalradio.com_private_key.key:/etc/nginx/certs/frentelocalradio.com.key:ro

  stations:
    volumes:
      - /home/ubuntu/prueba/bundle.crt:/etc/nginx/certs/frentelocalradio.com.crt:ro
      - /home/ubuntu/prueba/_.frentelocalradio.com_private_key.key:/etc/nginx/certs/frentelocalradio.com.key:ro
      
Finally I updated the docker installation.

Although I read somewhere that the .cer and .crt files are interchangeable, do I need to convert the .cer files to .crt before making the bundle.crt file?

Thanks a lot, great product and great community.

**Expected behavior:**

Ssl certificate running.

**Relevant logs:**

**Screenshots:**

**Device(s):**

- Device: 
- OS: 
- Browser: Chrome
- Version: 

**Additional context:**

**Comment by YosefAdPro** [comment] 2021-05-13 14:03
Try this


``` yaml
services:
  web:
    volumes:
     - /home/ubuntu/prueba/_.frentelocalradio.com.crt:/etc/letsencrypt/selfsigned.crt:ro
     - /home/ubuntu/prueba/_.frentelocalradio.com_private_key.key:/etc/letsencrypt/selfsigned.key:ro

  stations:
    volumes:
      - /home/ubuntu/prueba/_.frentelocalradio.com.crt:/etc/nginx/certs/default.crt:ro
      - /home/ubuntu/prueba/_.frentelocalradio.com_private_key.key:/etc/nginx/certs/default.key:ro

  nginx_proxy:
    volumes:
      - /home/ubuntu/prueba/_.frentelocalradio.com.crt:/etc/nginx/certs/default.crt:ro
      - /home/ubuntu/prueba/_.frentelocalradio.com_private_key.key:/etc/nginx/certs/default.key:ro

**Comment by DanRedA** [comment] 2021-05-15 15:20
Yosef,

Thanks a lot, the code seems to be working!
I renamed the bundle.crt file to _.frentelocalradio.com.crt
Modified the docker-compose.override.yml with the code you sent.
At this point the SSL wasn´t working yet, so I ran ./docker.sh install to configure the ports and the let´s encrypt certificate which I hadn't done yet, refreshed the override file, went to the browser and typed the full web address and it was done!!!

Again thank you, :)

**Comment by YosefAdPro** [comment] 2021-05-15 21:19
happy to help.
Close this sheet if the issue is resolved.

**Comment by DanRedA** [comment] 2021-05-15 21:23
First thing getting home, thanks again

**Closed** 2021-05-16 01:14 UTC
Labels: question
