### ISSUE TITLE
LiquidSoap Shoutcast Encoder Issue

### ISSUE THREAD

**Issue by MagiskSec** [AzuraCast/AzuraCast#3019] opened 2020-07-08 15:45 UTC
**Using Docker installation method**
No

**AzuraCast version**
v0.10.3, #2abb8bf (2020-07-08 7:03) • Ansible • PHP 7.4

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
On one of my stations in AzuraCast (not all of them), when encoding using the ShoutCast v1 settings, the server does not provide any meaningful response and does not connect the client. The client will connect fine with IceCast. This is for all streamers and on multiple devices. 

**To Reproduce**
Enable Streamers/DJs, create a streamer account and connect using the Shoutcast v1 Instructions. 

**Expected behavior**
I expected it to encode over the Liquidsoap AutoDJ stream.

**Relevant Logs**
Not even showing the connection coming through in the liquidsoap logs.

**Additional context**
There are no customisation to the Liquidsoap configuration and it seems to work fine on another station on the same AzuraCast installation.

**Comment by SlvrEagle23** [comment] 2020-07-08 19:42
@MagiskSec Likely a duplicate of issue #2989; I am able to track down the cause of this issue and am working on it.

**Closed by SlvrEagle23** 2020-07-08 19:42 UTC
