### ISSUE TITLE
Album Art not working since latest update & Unable to delete album art

### ISSUE THREAD

**Issue by MrSleeps** [AzuraCast/AzuraCast#2820] opened 2020-05-08 21:44 UTC
Running v0.10.2, #cadb119 (2020-05-08 6:46) (docker) on debian 9.

Same issue as mellis85:

"GET https://localhost/api/station/1/art/ae6ed881e61675f45689fa15-1586687574.jpg net::ERR_CONNECTION_REFUSED"

**Comment by MrSleeps** [comment] 2020-05-08 21:54
Also, when I try to delete album art from files I get a 500 server error:

500
File not found at path: 9ff9f96ded9406a2aa6f98ff.jpg
Filesystem.php : 389

**Comment by SlvrEagle23** [comment] 2020-05-08 22:27
@MrSleeps Closing as duplicate of #2814.

**Closed by SlvrEagle23** 2020-05-08 22:27 UTC
