### ISSUE TITLE
API "Access-Control-Allow-Origin" header setting is not being applied

### ISSUE THREAD

**Issue by Vaalyn** [AzuraCast/AzuraCast#3399] opened 2020-11-11 02:13 UTC
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #d9b682c (2020-11-10 16:12)

**Host Operating System**
Ubuntu 20.04

**Describe the bug**
When I set the `API "Access-Control-Allow-Origin" header` the value is not being set to the respective header on the response.

**To Reproduce**
1. Set value of the setting to the domain of a website
2. Go to the website
3. Open JavaScript console in browser
4. Make GET request, see it failing due to CORS
5. Look into network tab of browser and look for the header value

I used jQuery:
```
$.get('https://azuracast.example.com/api/station/1/requests', function(data) {
    console.log(data);
});
```

**Expected behavior**
The header value should be correctly set to the response

**Device(s):**
 - Device: MacBook Pro Mid 2014 15"
 - OS: macOS 10.15.6
 - Browser: Chrome
 - Version: 86

**Additional context**

I've already identified one problem with the code in the [`Middleware\Modules\Api`](https://github.com/AzuraCast/AzuraCast/blob/master/src/Middleware/Module/Api.php#L62). As you can see in that line the resulting `Response` object of the 2 `withHeader()` calls is not being set to the `$response` variable.

Fixing this alone does not fix the general issue though. From what it looks like I think the [fetching of the `Origin`](https://github.com/AzuraCast/AzuraCast/blob/master/src/Middleware/Module/Api.php#L53) from the header values of the request is not working. It looks like that header does not exist on the request since the check for emptiness [here](https://github.com/AzuraCast/AzuraCast/blob/master/src/Middleware/Module/Api.php#L54) results in a `false` and the code inside the `if` was never executed in my testing.

**Comment by Vaalyn** [comment] 2020-11-11 02:23
My guess is that the `Origin` is not being set by the NGINX proxy or the web NGINX.

**Comment by SlvrEagle23** [comment] 2020-11-11 02:31
@Vaalyn Is this a limitation of our nginx proxy in front of the server? When I built out the CORS functionality that didn't exist and it worked fine. 🤔

**Comment by Vaalyn** [comment] 2020-11-11 02:51
@SlvrEagle23 I'm guessing a bit here but I think it might be that NGINX does not forward an `Origin` header by default and that we have to add a `proxy_set_header X-Forwarded-Origin $http_origin` in the proxy NGINX and set that to the `Origin` header in the web NGINX.

**Comment by VTCAKAVSMoACE** [comment] 2020-11-11 06:28
FTR this is the same project as: https://github.com/AzuraCast/AzuraCast/issues/1105

Default docker configuration in use, nothing special with our proxy config.

**Comment by SlvrEagle23** [comment] 2020-11-20 08:19
This should now be fixed as of the latest code release, which both ensures that the "Origin" header is proxied through both the nginx_proxy and the nginx on the `web` container itself, and fixes the parsing errors that may have prevented the header from working as intended previously.

**Closed by SlvrEagle23** 2020-11-20 08:19 UTC
Labels: bug
