### ISSUE TITLE
Liquidsoap still tries to broadcast to local Icecast server when connect to remote server is selected.

### ISSUE THREAD

**Issue by Quartizer** [AzuraCast/AzuraCast#1107] opened 2019-01-20 21:26 UTC
Hello. If choosing to connect to a remote server rather than use ice cast on the local server, liquid soap still tries to broadcast to the local server with default mount point (/radio.mp3) at 128 kbps. It even reverts to this default behaviour after having used icecast2 and created multiple customised mount points, then switched to using a remote server.

Thanks for all the work you do on Azuracast, it's soon to be the difference between me DJing on my station and coding for it. :)

**Comment by SlvrEagle23** [comment] 2019-01-26 20:40
@Quartizer This could be caused by inconsistencies in the various controllers that handled editing station data. Try editing your station's profile again and saving it, and this issue should be fixed, with the station no longer attempting to broadcast locally even if local broadcasting isn't enabled.

**Closed by SlvrEagle23** 2019-01-26 20:40 UTC
Labels: bug
