### ISSUE TITLE
Problem with &host on public page

### ISSUE THREAD

**Issue by Keyraus** [AzuraCast/AzuraCast#3334] opened 2020-10-26 16:52 UTC
**Using Docker installation method**

**AzuraCast version**

**Host Operating System**
debian 10

**Describe the bug**
The public page have this error in the console so there is no sound
GET http://%26host:8000/radio.mp3?1603730282 net::ERR_NAME_NOT_RESOLVED

**To Reproduce**
idk how to reproduce

**Expected behavior**
i expected that you can explain me what i've done wrong

**Device(s):**
 - Device: Desktop 
 - OS: win10
 - Browser: chrome and vivaldi and firefox
 - Version: last

**Additional context**
i use another ngingx on the host 
firewall allow 8000
and the router forward 8000 port to host 

i hope that i missed nothing important to say
already welcome to take the time to read this message and sorry for all mistake in my writing i'm french

**Comment by SC2Mitch** [comment] 2020-10-26 22:23
Docker or ansible? What version are you running on? 

I'm unable to replicate this issue without any kind of logs, my local machines are working as intended. I do have a small feeling that the other nginx is causing some kind of issues.

**Comment by Hyro-san** [comment] 2020-10-30 16:29
Hi, i'm with him so i'll add more detail. So we're using docker last version we found. And we had no problem to host the website and to start a station. But when we go on the player there is no sound so we check with the console of Chrome. The error we got is "http://&host:8000/radio.mp3?1604074790", I guess the &host would be "www.exemple.com". This isn't only the player but in the entire website. We reinstalled the docker many times the docker but nothing changed. Here some images : 
![extremelybad](https://user-images.githubusercontent.com/62421823/97731329-4604ad80-1ad5-11eb-88d1-2cc49179b35c.png)
![ohnothisisbad](https://user-images.githubusercontent.com/62421823/97731330-469d4400-1ad5-11eb-96a0-d7de1d0d7316.png)
![pleaseno](https://user-images.githubusercontent.com/62421823/97731331-469d4400-1ad5-11eb-9e76-e3da14b367ca.png)
![verybad](https://user-images.githubusercontent.com/62421823/97731333-469d4400-1ad5-11eb-9ffa-fda7cab0c3d0.png)
![veryverybad](https://user-images.githubusercontent.com/62421823/97731336-4735da80-1ad5-11eb-9278-69c64c0014dd.png)

**Comment by Keyraus** [comment] 2020-10-30 18:41
OK sorry the problem is solved it was the nginx conf on the host machine where i was using &host and not $host 
 
`
server {
        listen 80;
        listen [::]:80;

        server_name www.example.com;

        location / {
                proxy_pass http://127.0.0.1:6480;

                proxy_set_header Host $host; 

                }
}
`

**Comment by Vaalyn** [comment] 2020-10-30 18:43
👍  closing this issue now as resolved

**Closed by Vaalyn** 2020-10-30 18:43 UTC
Labels: error
