### ISSUE TITLE
Update error! Service down!

### ISSUE THREAD

**Issue by lalafunn** [AzuraCast/AzuraCast#2017] opened 2019-09-29 17:02 UTC
Azuracast is totally down after the latest update:

ocramius/package-versions: ...done generating version class
[29-Sep-2019 17:00:37 UTC] PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Azura\Doctrine\Repository::__construct() must be an instance of Symfony\Component\Serializer\Serializer, instance of Doctrine\ORM\Mapping\ClassMetadata given, called in /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/Repository/DefaultRepositoryFactory.php on line 68 and defined in /var/azuracast/www/vendor/azuracast/azuracore/src/Doctrine/Repository.php:38
Stack trace:
#0 /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/Repository/DefaultRepositoryFactory.php(68): Azura\Doctrine\Repository->__construct(Object(Doctrine\ORM\EntityManager), Object(Doctrine\ORM\Mapping\ClassMetadata))
#1 /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/Repository/DefaultRepositoryFactory.php(50): Doctrine\ORM\Repository\DefaultRepositoryFactory->createRepository(Object(Doctrine\ORM\EntityManager), 'App\\Entity\\Sett...')
#2 /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(713): Doctrine\ORM\Repository\DefaultRepositoryFactory->getRepository(O in /var/azuracast/www/vendor/azuracast/azuracore/src/Doctrine/Repository.php on line 38
2019/09/29 17:00:37 Command exited with error: exit status 255

**Comment by ErnestPH** [comment] 2019-09-29 20:46
Need more details. Like installation method. what OS? Please follow the format. thanks

**Comment by SlvrEagle23** [comment] 2019-09-29 21:59
@lalafunn We've identified the cause of this issue (to summarize, the Doctrine entity manager can't be loaded in the same request that flushes the Redis cache, as the cache is out of date at that point) and resolved it in our latest code updates.

Please update again and let us know if you continue to encounter any issues.

**Comment by SlvrEagle23** [comment] 2019-09-29 22:00
Closing as duplicate of #2016.

**Closed by SlvrEagle23** 2019-09-29 22:00 UTC
Labels: bug, in progress
