### ISSUE TITLE
Ban IP address

### ISSUE THREAD

**Issue by stardevelop** [AzuraCast/AzuraCast#2519] opened 2020-03-16 21:42 UTC
Advanced Banned IP Addresses feature does not work as it should.
Although, I ban an IP address and restart the station but still the IP is listening to the stream.

**Comment by stardevelop** [comment] 2020-03-16 21:46
I need to stop some streamrippers that use Winamp plugin to rip.

**Comment by YosefAdPro** [comment] 2020-03-17 10:29
I think it's the same as

https://github.com/AzuraCast/AzuraCast/issues/2467

**Comment by SlvrEagle23** [comment] 2020-03-18 16:10
Closing as a likely duplicate of #2467.

**Closed by SlvrEagle23** 2020-03-18 16:10 UTC
