### ISSUE TITLE
Top 5 VOTE!

### ISSUE THREAD

**Issue by Ilario42** [AzuraCast/AzuraCast#642] opened 2018-07-03 11:09 UTC
It would be very nice if you can enable the top 5 at a station that you want. Users can vote for a song in a list, depending on the vote, go up or down a list, and start this list every 60 minutes. Once you have finished the top 5 you start with a normal playlist to give the time to vote. At the end of 60 minutes users can no longer vote and the top 5 starts

**Comment by SlvrEagle23** [comment] 2018-08-16 10:58
Closing as duplicate of #79. Voting has already been requested, but represents a significant time investment in order to do it right and ensure that the results matter and can be easily managed/viewed by station administrators, which is why it hasn't been taken on yet.

**Closed by SlvrEagle23** 2018-08-16 10:58 UTC
