### ISSUE TITLE
After Update no Playlists are played

### ISSUE THREAD

**Issue by GalbanMayer** [AzuraCast/AzuraCast#4768] opened 2021-11-09 13:59 UTC
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #4cbb9dd

### What happened?

Everything works fine to restream playlists into my network. 
After updating as allways this does not work anymore. Nothing has change so far in configuration.

I get a log on the station:
_At /var/azuracast/stations/br2/config/liquidsoap.liq, line 28, char 41-44:
Error 6: Cannot apply that parameter because the function at /var/azuracast/stations/br2/config/liquidsoap.liq, line 28, char 26-37
has no argument labeled "max"!_

A look into the liquidsoap.liq on this line:
playlist_default = mksafe(input.http(max=5., "https://dispatcher.xxxx.xxx/mp3/mid"))

I hope you can help me - Thank you very much.

Galban

### Relevant log output

```shell
_At /var/azuracast/stations/br2/config/liquidsoap.liq, line 28, char 41-44:
Error 6: Cannot apply that parameter because the function at /var/azuracast/stations/br2/config/liquidsoap.liq, line 28, char 26-37
has no argument labeled "max"!_
```

**Comment by Abqehebter** [comment] 2021-11-09 14:00
Duplicate of: https://github.com/AzuraCast/AzuraCast/issues/4761

**Comment by SC2Mitch** [comment] 2021-11-09 14:05
Duplicate, we're looking into these issues now.

**Closed by SC2Mitch** 2021-11-09 14:05 UTC
Labels: duplicate, needs investigation
