### ISSUE TITLE
Scheduled playlist problem doesnt start on time

### ISSUE THREAD

**Issue by stemvantwente** [AzuraCast/AzuraCast#1762] opened 2019-07-19 13:37 UTC
Installation method
"Traditional" installation method.

Host OS (for Docker installations)
Ubuntu 1804 (VPS) 

Describe the bug
I use Scheduled playlist with direct stream url this is working fine but I use a playlist who plays 1 song each 60 minutes, and 1 who plays a jingle every 120min.

Now when the time is there and the direct stream Scheduled playlist kicks in I first hear a song from the 60 minutes playlist and then a jingle from the 120 min and then finally I hear the Scheduled playlist for the direct stream url? This only happens 1 time so its not repeating only at the start of the direct stream Scheduled playlist.

Can someone tell me why this is? and can I disable this? so that the direct stream Scheduled playlist starts directly at the time I say it to play?

I'm using Interrupt other songs to play at scheduled time. for the scheduled direct link playlist.
Or do I need to say Only play one track at scheduled time in the 60 minutes and 120 minutes playlist? is this the problem?

Sorry for my English its not that good :)

Greets
Roy

**Comment by SlvrEagle23** [comment] 2019-07-19 23:28
Closing as duplicate of #1761.

**Closed by SlvrEagle23** 2019-07-19 23:28 UTC
Labels: error, question
