### ISSUE TITLE
Move button does not work

### ISSUE THREAD

**Issue by radiolize** [AzuraCast/AzuraCast#1413] opened 2019-04-08 04:26 UTC
Hello!

Installation Method: Docker

When I click a folder then go and select a song and click move button, a pop-up opens and says "Loading" and never loads anything, writes "Loading" forever.

Greetings!

**Comment by Vaalyn** [comment] 2019-04-08 09:22
Hi, which browser are you using and could you check if there are any errors either in the browsers JavaScript console or in the application logs?

**Comment by radiolize** [comment] 2019-04-11 07:48
Browser: Chrome

When I refresh just a music folder console error appears:

`Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
    at Grid.commands (https://my.radiolize.com/station/1/files:368:99)
    at Object.<anonymous> (https://my.radiolize.com/static/js/bootgrid/jquery.bootgrid.updated.js:625:50)
    at Function.each (https://my.radiolize.com/static/dist/lib/jquery/jquery-a09e13ee94.min.js:2:2573)
    at Object.<anonymous> (https://my.radiolize.com/static/js/bootgrid/jquery.bootgrid.updated.js:620:19)
    at Function.each (https://my.radiolize.com/static/dist/lib/jquery/jquery-a09e13ee94.min.js:2:2573)
    at Grid.renderRows (https://my.radiolize.com/static/js/bootgrid/jquery.bootgrid.updated.js:594:15)
    at update (https://my.radiolize.com/static/js/bootgrid/jquery.bootgrid.updated.js:200:24)
    at Object.success (https://my.radiolize.com/static/js/bootgrid/jquery.bootgrid.updated.js:238:21)
    at u (https://my.radiolize.com/static/dist/lib/jquery/jquery-a09e13ee94.min.js:2:27457)
    at Object.fireWith [as resolveWith] (https://my.radiolize.com/static/dist/lib/jquery/jquery-a09e13ee94.min.js:2:28202)`

when I click to move button, console error appears:

`files:368 Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
    at Grid.commands (https://my.radiolize.com/station/1/files:368:99)
    at Object.<anonymous> (https://my.radiolize.com/static/js/bootgrid/jquery.bootgrid.updated.js:625:50)
    at Function.each (https://my.radiolize.com/static/dist/lib/jquery/jquery-a09e13ee94.min.js:2:2573)
    at Object.<anonymous> (https://my.radiolize.com/static/js/bootgrid/jquery.bootgrid.updated.js:620:19)
    at Function.each (https://my.radiolize.com/static/dist/lib/jquery/jquery-a09e13ee94.min.js:2:2573)
    at Grid.renderRows (https://my.radiolize.com/static/js/bootgrid/jquery.bootgrid.updated.js:594:15)
    at update (https://my.radiolize.com/static/js/bootgrid/jquery.bootgrid.updated.js:200:24)
    at Object.success (https://my.radiolize.com/static/js/bootgrid/jquery.bootgrid.updated.js:238:21)
    at u (https://my.radiolize.com/static/dist/lib/jquery/jquery-a09e13ee94.min.js:2:27457)
    at Object.fireWith [as resolveWith] (https://my.radiolize.com/static/dist/lib/jquery/jquery-a09e13ee94.min.js:2:28202)`

**Comment by Vaalyn** [comment] 2019-04-11 07:57
Thank you for posting these JS errors. The problem is coming from this [line](https://github.com/AzuraCast/AzuraCast/blob/master/templates/stations/files/index.js.phtml#L176) here and is caused by the JS function btoa / atob not being able to handle multibyte unicode characters, see [MDN](https://developer.mozilla.org/de/docs/Web/API/WindowBase64/btoa#Unicode-Zeichenketten). On the MDN page there is a solution that will allow these functions to work with multibyte unicode characters.

**Comment by radiolize** [comment] 2019-04-11 10:21
Is there anything I can do? I'm not coder btw :)

**Comment by Vaalyn** [comment] 2019-04-11 10:22
@radiolize I'll implement the fix after work so when I've done that and it's merged I'll let you know so that you can test it.

**Comment by SlvrEagle23** [comment] 2019-04-11 17:17
@radiolize The fix by @Vaalyn is merged in the main repository. In a few minutes, you can update your installation and the issue should be resolved. :)

**Closed by SlvrEagle23** 2019-04-11 17:17 UTC
Labels: bug
