### ISSUE TITLE
Now Playing Metadata does not update on latest iOS 14.0

### ISSUE THREAD

**Issue by jbsix** [AzuraCast/AzuraCast#3188] opened 2020-09-21 02:02 UTC
**Using Docker installation method**

Yes

**AzuraCast version**

Rolling Release #0aa4071 (2020-09-20 17:59) • PHP 7.4 

**Host Operating System**

Ubuntu 18.04

**Describe the bug**

Now Playing metadata not updating iOS

**To Reproduce**

1. Go to player on public page on browser on iOS
2. Click on play button
3. Now playing correctly display metadata 
4. Next song plays 
5. Now playing metadata does not update

**Expected behavior**

Now playing should update on iOS (words as expected on desktop)

**Relevant Logs**

**Screenshots**

**Device(s):**
Safari iOS versions 13.x and 14

**Additional context**

**Comment by Vaalyn** [comment] 2020-09-21 16:15
I can't reproduce this on my iPad Pro with iPadOS 14. Can't test on an iPhone since my iPhone 6 does not support iOS 14.

**Comment by jbsix** [comment] 2020-09-22 00:03
Update: disabled WebSockets for Now Playing Updates on admin, system settings page and Now Playing metadata seems to work as expected on latest iOS. Thanks for the reply and for your time to test and reproduce (unsuccessfully).

**Comment by Vaalyn** [comment] 2020-09-22 12:44
Just tested this on the iPhone of a friend with iOS 14 with my local test/dev installation and still can't reproduce this.
The only thing I'd still need to test would be an AzuraCast instance with SSL enabled to check if maybe secure WebSockets are having a problem.

**Comment by Vaalyn** [comment] 2020-09-24 18:22
Have just tested it again on my live station (again with the iPhone of a friend) with SSL enabled (and on the newest rolling release version) and still no issues there.

@jbsix Would you mind checking if you can see the issue happening on my radio station with your iPhone?

https://radio.bronyradiogermany.com/public/brg

**Comment by Vaalyn** [comment] 2020-10-06 17:37
Closing since I can't reproduce this issue.

**Closed by Vaalyn** 2020-10-06 17:37 UTC

**Comment by jbsix** [comment] 2020-10-15 22:37
thanks for testing @Vaalyn as mentioned since disabling "WebSockets for Now Playing Updates" on the admin settings, fixed the issue.

**Comment by Vaalyn** [comment] 2020-10-15 22:40
@jbsix I would still like to know if you can reproduce that issue with your iPhone on my station (see the link I posted above) since disabling that functionality is not a fix but a workaround and I simply can't reproduce this myself.

**Comment by jbsix** [comment] 2020-10-15 23:05
sorry for misunderstanding, yes confirming that I am able to reproduce the issue on your station (Safari iOS 14.0.1) and not only does the metadata not update as expected, the progress bar also does not update as expected. Tested on Chrome browser and unable to reproduce the issue. Isolated the issue to Safari and perhaps an issue with my device (since I have some experimental Webkit features enabled). Hope this helps.
