### ISSUE TITLE
 move media files to another directory.

### ISSUE THREAD

**Issue by xbeatorg** [AzuraCast/AzuraCast#2720] opened 2020-04-22 18:14 UTC
Hi,

I want to store all music files in /media/azuracast.

Using Docker installation method
Yes, standard installation.

Host Operating System
Debian 10/64

I did like the documentation, 
https://www.azuracast.com/help/docker/#mounting-a-directory-into-a-station
but I still got an error

500
Directory "/ media / azuracast" was not created
Station.php: 663

files : docker-compose.override.yml
-----------------------------------
version: '2.2'

services:
  web:
    volumes:
     - /media/azuracast:/var/azuracast/music

  stations:
    volumes:
     - /media/azuracast:/var/azuracast/music

------------------------------------------------------------
cd /var/azuracast/www/AzuraCast
docker-compose down
docker-compose up -d

I thank all the help I could have.
no: my mother tongue is French and so I say thank you google ;-)

**Comment by CodeSteele** [comment] 2020-04-27 06:47
That 500 error suggests that you've changed the Custom Media Directory under "Administration", do _not_ do this.

Additionally your volumes should be pointed to your station's media directory, eg:

` - /media/azuracast:/var/azuracast/stations/[station_name]/media/`

The documentation is slightly wrong, I'll make a correction on that.

**Comment by xbeatorg** [comment] 2020-04-27 07:51
I modified the file: compose.override.yml

services:
the Web:
volumes:
- / media / azuracast: / var / azuracast / stations / xbeat / media /

stations:
volumes:
- / media / azuracast: / var / azuracast / stations / xbeat / media /

then

cd / var / azuracast / www / AzuraCast
docker-composer down
docker-compose up -d

and still nothing to change, should we change in the radio web interface?

the / media / azuracast directory must have specific permission, and the owner must be my login or root?

**Comment by CodeSteele** [comment] 2020-04-27 07:58
Can you show me this variable in the station profile manager:

![image](https://user-images.githubusercontent.com/31152835/80348148-580e4680-883b-11ea-97de-c0e263ddbe7f.png)

**Comment by xbeatorg** [comment] 2020-04-27 08:22
![Capture d’écran du 2020-04-27 10-20-09](https://user-images.githubusercontent.com/64160586/80350243-b7d31480-8870-11ea-9044-4096ca901661.png)


yes it is well like that, it is me I do not have access to / media / azuracast it gives me the file which finds it / var / lib / docker / volumes / azuracast_station_data / _data / xbeat / media

**Comment by xbeatorg** [comment] 2020-04-27 10:21
I noticed an inconsistency in the logs, basically I see the list of files in the default directory, it's trying to find the new one and there is no file, and it still uploads to the old directory too.

2020/04/27 10:16:25 [request: 3] Nonexistent file or ill-formed URI "/var/azuracast/stations/test/media/03_-_cardiocleptomanie.mp3"!

it's like if he wants to read in the new one but list the files of the default directory

**Comment by CodeSteele** [comment] 2020-04-27 16:44
Did you re-run your scan/re-upload files to /media/azuracast? It won't automatically move your files there.

**Comment by xbeatorg** [comment] 2020-04-27 17:42
yes with the command ./docker.sh cli azuracast: media: reprocess
it scans me it does not find the audio files, it always searches in the default directory even with the modifications

**Comment by CodeSteele** [comment] 2020-04-27 18:34
If you upload a new song via the UI, does it show up in `/media/azuracast` on the host? Do you get an error?

**Comment by xbeatorg** [comment] 2020-04-27 18:39
no it always goes to / var / lib / docker / volumes / azuracast_station_data / _data / xbeat / media ...

I do not understand anymore

**Comment by xbeatorg** [comment] 2020-04-27 18:46
the azuracast file is in /var/azuracast/www/AzuraCast/ and not in / var/azuracast/ it can be

**Comment by CodeSteele** [comment] 2020-04-28 06:02
I'll see about spending some time doing a fresh install/following the docs and seeing if I can't reproduce the issue, if the docs work out of the box then something was messed up along the way.

**Comment by xbeatorg** [comment] 2020-04-28 06:07
I can give you access to the dedicated server, it is a recent rental, watching you or if not I do a new installation and I start from 0

**Comment by CodeSteele** [comment] 2020-04-28 06:10
We generally try to avoid hopping on people's servers resolving configuration issues (it's very time intensive to be providing support services for free), but I can definitely make sure that the documents are clear and concise for the benefit of the community at large. So I'll start there.

**Comment by xbeatorg** [comment] 2020-04-28 06:10
I also thought I would do a new install on a dedicated intern to see what is happening more closely.

**Comment by CodeSteele** [comment] 2020-04-28 06:12
That may be a good plan (start with a known working good config), let me know if you plan on doing that and I'll await your result before re-reviewing the documentation.

**Comment by xbeatorg** [comment] 2020-04-28 06:16
normal, I will do a new install and I come back afterwards ;-)

thank you very much for your help ;-)

**Comment by xbeatorg** [comment] 2020-04-28 06:16
I work a lot with debian, here it is a debian 10/64, what do you recommend as an operating system?

**Comment by CodeSteele** [comment] 2020-04-28 06:45
Debian 10 should be fine, it's what I use a lot of the time.

**Comment by xbeatorg** [comment] 2020-04-28 07:15
well these parties for a Debian install 10/64 on a test server ;-)
see you later ;-)

**Comment by xbeatorg** [comment] 2020-04-29 05:55
Hello,
I still do not know what miracle it works after several modifications, several tracks to follow, I will still do an install test because I must know, the why of how ;-)

Have a good day

**Closed** 2020-07-12 12:31 UTC
Labels: wontfix
