### ISSUE TITLE
Icecast-KH & AAC+ Codec

### ISSUE THREAD

**Issue by ifadli** [AzuraCast/AzuraCast#92] opened 2017-02-08 04:54 UTC
Hi,
Can i use IceCast-KH for frontend and select codec manually for use AAC+ ?

**Comment by ifadli** [comment] 2017-02-18 18:39
problem solved :) .

**Comment by SlvrEagle23** [comment] 2017-05-17 21:07
Re-closing as duplicate of #69

**Closed by SlvrEagle23** 2017-05-17 21:07 UTC
Labels: duplicate
