### ISSUE TITLE
API Slim Application Error on already started radio station

### ISSUE THREAD

**Issue by Sakretsos** [AzuraCast/AzuraCast#5388] opened 2022-05-18 10:29 UTC
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #c720d95 (2022-05-18 1:54)

### What happened?

Hello, the problem here is when i send a post call in order to stop or start a radio station with the bellow api call:
https://URL/api/station/ID/frontend/stop
or
https://URL/api/station/ID/frontend/start

I get the success output that you can see bellow:

`{
    "success": true,
    "message": "Service started.",
    "formatted_message": "Service started."
}`

But when i send again a request to an already stopped radio i get Slim Application Error instead of **success: false** and the reason that cant hit again the same command, like radio station already stopped.

**Comment by SC2Mitch** [comment] 2022-05-26 23:02
Hi there, 

can you update and try again? We believe this should be fixed.

If not, we do have a new .env flag that you can use called `SHOW_DETAILED_ERRORS` you may need to turn that to `true` to work.

**Comment by Sakretsos** [comment] 2022-05-27 08:24
Hello @SC2Mitch,
Happy friday!
Well, i test it again and i get error 500 internal server error.
But i think a better way is to get an json output like the bellow.
```
{
    "success": false,
    "message": "Service already started.",
    "formatted_message": "Service already started."
}
```
Thanks,
Ioannis

**Comment by SC2Mitch** [comment] 2022-05-27 11:56
Thanks Ioannis, will flag it up as a possible bug. I cannot reproduce this but hopefully someone can have a look.

**Comment by Sakretsos** [comment] 2022-05-27 12:00
Hello again @SC2Mitch, 

You can easily reproduce it through postman or i can help you from somehow.

Thanks,
Ioannis

**Comment by SC2Mitch** [comment] 2022-05-27 12:44
Oh yep, can reproduce this, flagging up as a bug.

**Comment by Sakretsos** [comment] 2022-05-28 13:14
Hello @SC2Mitch,

Bellow you can find some screenshots from postman.
![start_again](https://user-images.githubusercontent.com/8127121/170827168-cb2ace30-2924-4991-b1b0-1525ade7ce41.JPG)
![normally_start](https://user-images.githubusercontent.com/8127121/170827170-5bb00961-fad4-42b8-94f2-d833a40444d2.JPG)

**Comment by SlvrEagle23** [comment] 2022-06-29 08:30
I realize this answer is delayed, but to answer this question: we return a response in the format that the HTTP request calls for, so if either of the two conditions is true, we return a JSON response even in the case of errors:
 - The request is coming from AJAX (the `X-Requested-With` header is `XMLHttpRequest`)
 - The request has an `Accept` header with the value `application/json`.

It appears Postman, by default, may not be sending either, but if you're making API calls from a client program, you can control the headers above to ensure JSON is always returned.

**Closed by SlvrEagle23** 2022-06-29 08:30 UTC
Labels: bug, unexpected behaviour, rolling-release, api
