### ISSUE TITLE
#Erro offline radios

### ISSUE THREAD

**Issue by Rafaelrds2017** [AzuraCast/AzuraCast#1390] opened 2019-04-03 01:01 UTC
Some Radios come out of the air repeatedly.

Any updates available to fix?

Att
Rafael

**Comment by SlvrEagle23** [comment] 2019-04-03 01:08
@Rafaelrds2017 This is not a good message body for a GitHub issue.

Care to be more specific?

**Comment by Rafaelrds2017** [comment] 2019-04-03 01:14
I recently installed the system, and released today.

But some radios are disconnecting. It stays on the air for a few minutes, then stops, and gets offline status.

Sorry for not being specific, because I do not speak English and I am a lay person. I hope you have understood.

**Comment by Rafaelrds2017** [comment] 2019-04-03 01:16
I found an equal error in: # 1319

**Comment by SlvrEagle23** [comment] 2019-04-03 03:20
@Rafaelrds2017 Is this specifically when you're broadcasting using a streamer/DJ account, or just when the AutoDJ is running?

Also, can you supply any possibly relevant logs from the Log Viewer (in Utilities), particularly the Liquidsoap log?

**Comment by Vaalyn** [comment] 2019-05-23 15:59
Closing the issue as there hasn't been an answer in over a month and critical information to reproduce the issue is missing. As it stands we cannot debug this issue without further information. If you still encounter this problem feel free to let us now and don't forget to include the relevant logs that were mentioned.

**Closed by Vaalyn** 2019-05-23 15:59 UTC
Labels: error
