### ISSUE TITLE
Sending now playing via http

### ISSUE THREAD

**Issue by seanbts** [AzuraCast/AzuraCast#2788] opened 2020-05-02 19:55 UTC
Hi,
Is it possible to send now playing information via a http post command, we use magic rds software which has the option of sending updates via http get commands?

Thanks, Sean

**Comment by SlvrEagle23** [comment] 2020-05-04 02:05
@seanbts Hello! This is likely a duplicate of #2249.

**Closed by SlvrEagle23** 2020-05-04 02:05 UTC
