### ISSUE TITLE
hcheduled playlists are not playing never

### ISSUE THREAD

**Issue by nunotfc** [AzuraCast/AzuraCast#4938] opened 2022-01-02 12:54 UTC
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

0cc3008 (2021-12-30 19:56) • Docker • PHP 8.1

### What happened?

hello,
i really dont know how explain this bug.
The scheduled playlists are never playing, for example if i have one playlist all fridays thath plays at 12 pm.
it appens with all scheduled playlists.
i have no log, because i dont know what to search for. liquidsoap simply skips the playlist and keeps playing songs, is like these playlists are all disabled.

**Comment by Abqehebter** [comment] 2022-01-05 14:30
I can confirm a similar problem. The song queue just goes crazy at certain points and rolls over when it suddenly realizes that there is still a scheduled song that needs to come in between.

**Comment by nunotfc** [comment] 2022-01-05 17:03
i doesnt have more any problem related to song queue. what i did?
autodj queue not rebuilding i passed this step;
i went to individual playlist, reshufled and cleared queue of each one;
verify if you have some warning about nopwplaying sync tasks. after doing this, if it is, run manually via docker.sh;
it appears i'm crazy but i believe that 2 or 3 ishues posted by me are related.

**Comment by Abqehebter** [comment] 2022-01-05 17:06
All the tasks have now received a whole new and better system on the latest rolling release version. I no longer assume that the error is due to this, but rather to the song queue or Liquidsoap itself.

**Comment by SC2Mitch** [comment] 2022-01-06 02:58
Without any sort of logs or pictures, or anything, we can't do anything. Please be detailed as possible when it comes to scheduled playlists. Going to close this as there's nowhere near enough information to debug this. 

kind regards

**Closed by SC2Mitch** 2022-01-06 02:58 UTC
Labels: needs investigation

**Comment by nunotfc** [comment] 2022-01-06 11:15
it can be closed now. after update sync processes it started working.

**Comment by nunotfc** [comment] 2022-01-06 11:15
dont know why i cant close
