### ISSUE TITLE
Buffer overrun

### ISSUE THREAD

**Issue by ismaelazanza** [AzuraCast/AzuraCast#2774] opened 2020-04-30 01:29 UTC
Sorry for the question, but I want to increase the buffer because I have this error. Where can it be done?

2020/04/29 19:10:29 [electrofactory_input_streamer:3] New metadata chunk ? -- 086. Tarzan Boy - Baltimora.
2020/04/29 19:11:40 [electrofactory_live_fallback:3] Switch to cross_7715 with forgetful transition.
2020/04/29 19:11:40 [dummy:3] Source failed (no more tracks) stopping output...
2020/04/29 19:11:45 [electrofactory_live_fallback:3] Switch to audio_to_stereo_7738 with transition.
2020/04/29 19:11:55 [dummy:3] Source failed (no more tracks) stopping output...
2020/04/29 19:11:55 [electrofactory_live_fallback:3] Switch to cross_7715 with forgetful transition.
2020/04/29 19:12:02 [electrofactory_live_fallback:3] Switch to audio_to_stereo_7738 with transition.
2020/04/29 19:12:06 [electrofactory_input_streamer:3] Buffer overrun: Dropping 0.01s. Consider increasing the max buffer size!
2020/04/29 19:12:06 [electrofactory_input_streamer:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2020/04/29 19:12:06 [electrofactory_input_streamer:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2020/04/29 19:12:06 [electrofactory_input_streamer:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2020/04/29 19:12:06 [electrofactory_input_streamer:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!

**Comment by CodeSteele** [comment] 2020-05-01 05:58
Duplicate of #1900

**Closed by CodeSteele** 2020-05-01 05:58 UTC

**Comment by ismaelazanza** [comment] 2020-05-01 23:20
I have opened this question since in # 1900, they do not provide a solution to the problem presented

**Comment by CodeSteele** [comment] 2020-05-02 00:19
I re-opened #1900, not sure when someone will have the chance to look into it though.

**Comment by lramilo** [comment] 2021-01-23 15:10
When playing a remote URL playlist, I found a workaround using a dummy output, manually adding this to Liquidsoap configuration:

`output.dummy(id="DUMMY_STREAM_OUTPUT", fallible=true, playlist_live)`

Details are explained on [#3701](https://github.com/AzuraCast/AzuraCast/issues/3701)

**Comment by julianodls** [comment] 2021-03-16 17:19
Error
As I resolve, my radio is crashing
2021/03/16 13:37:40 [input_streamer:3] Buffer overrun: Dropping 0.05s. Consider increasing the max buffer size!
