### ISSUE TITLE
Automatic Backup wont run

### ISSUE THREAD

**Issue by LordHelmchen666** [AzuraCast/AzuraCast#1637] opened 2019-06-07 16:38 UTC
The nightly backup don't run. I have it activated at 03:00 and keep 3 backups. But it "Never run". I couldn't find any related logs.
Install is Docker on Ubuntu 18.04

**Comment by gammaw** [comment] 2019-06-16 07:54
I guess I have the same issue. This is how my config looks like. Is it a problem with the zero (number of backup copies)? Btw, where is the backup supposed to be copied to? 

![image](https://user-images.githubusercontent.com/28865986/59561127-997b7600-901c-11e9-8efa-90465153541e.png)

**Comment by Vaalyn** [comment] 2019-06-16 10:47
@gammaw The config should be fine like this. The `Number of Backup Copies to Keep` if set to 0 will just lead to AzuraCast never deleting any old backups. If you set a number here this will mean that backups that are older than the number of days you entered will be automatically deleted.

The backup directory is located inside the web container at `/var/azuracast/backups`. If you need to access these backup files directly from outside of the container or if you want to automatically store them on a network drive you can mount the directory from the host machine to that directory via the `docker-compose.override.yml`. I did this with an NFS mount like this:

```
version: '2.2'

services:
    web:
        volumes:
            - /mnt/backup:/var/azuracast/backups
```

**Comment by gammaw** [comment] 2019-06-16 17:08
@Vaalyn thanks. The problem is, like @LordHelmchen666 also says, that there is no backup. The GUI shows "Never run" and, also, `/var/azuracast/backups` is empty. What do you thing is wrong?

**Comment by Vaalyn** [comment] 2019-06-16 17:11
@gammaw @LordHelmchen666 I'm not sure why it's not running yet. I've configured a backup on my test installation and will see if that works or not. In the meanwhile could you try doing a manual backup and see if any errors are shown?

**Comment by gammaw** [comment] 2019-06-17 20:52
@Vaalyn Ack. Manual backup works seems to work flawlessly.

**Comment by SlvrEagle23** [comment] 2019-06-18 01:14
@LordHelmchen666 @gammaw This should be fixed; thanks to @Vaalyn for the quick fix! :)

**Closed by SlvrEagle23** 2019-06-18 01:14 UTC
Labels: bug, in progress
