### ISSUE TITLE
the live broadcast sound is broken up and down

### ISSUE THREAD

**Issue by istahilagi** [AzuraCast/AzuraCast#1359] opened 2019-03-28 14:10 UTC
Ubuntu 16.04
**Installation method**
Docker 
when I live broadcast, I find the sound up and down

**Comment by istahilagi** [comment] 2019-03-28 14:15
this is the link stream ... after I update, the sound is broken when the live broadcast 
http://172.245.180.148:8010/Langitan?1553781621

**Comment by CodeSteele** [comment] 2019-03-28 14:17
Looks like a possible duplicate of #1349

**Comment by istahilagi** [comment] 2019-03-28 14:19
then, what is the solution?

**Comment by SlvrEagle23** [comment] 2019-03-28 14:20
@istahilagi What is your DJ buffer? It sounds like you need to turn it up. It's a configurable setting in the station profile.

**Comment by istahilagi** [comment] 2019-03-28 14:22
I use  radio caster

**Comment by SlvrEagle23** [comment] 2019-03-28 14:23
@istahilagi No no, I mean in AzuraCast, there is a setting in your station profile named "DJ/Streamer Buffer Time (Seconds)" (that's its English name, it may be translated). You should increase this number, then restart your station and see if it resolves the issue.

**Comment by Vaalyn** [comment] 2019-03-28 14:24
@istahilagi Pleas go to the `Station Profile` page, then `Edit Station Profile` go to the `Auto DJ` tab then look for the `DJ/Streamer Buffer Time (Seconds)` field. By default this should be set to `5`. Please try setting it to `10` and then restart your station.

**Comment by istahilagi** [comment] 2019-03-28 14:26
yes, it worked ... thank you very much :)

**Comment by SlvrEagle23** [comment] 2019-03-28 14:27
@istahilagi It sounds much better now! Glad we could help.

**Closed by SlvrEagle23** 2019-03-28 14:27 UTC
Labels: error

**Comment by istahilagi** [comment] 2019-06-11 13:21
I experienced this problem again.
"Advanced DJ / Streamer Buffer Time (Seconds)" I have filled in 5 and 10, but there are still interruptions during live

**Comment by lramilo** [comment] 2021-01-23 15:11
When playing a remote URL playlist, I found a workaround using a dummy output, manually adding this to Liquidsoap configuration:

`output.dummy(id="DUMMY_STREAM_OUTPUT", fallible=true, playlist_live)`

Details are explained on [#3701](https://github.com/AzuraCast/AzuraCast/issues/3701)
