### ISSUE TITLE
After updating to latest version via docker.sh /update the Song Information are not shown on Public Page

### ISSUE THREAD

**Issue by karndt84** [AzuraCast/AzuraCast#837] opened 2018-10-05 20:46 UTC
**Installation method**
Docker

**Host OS (for Docker installations)**
Debian 4.9.88

After updating to latest version via docker.sh /update the Song Information are not shown on Public Page

![unbenannt2](https://user-images.githubusercontent.com/9092791/46565917-14c94b80-c916-11e8-85b8-6b2f130888cb.JPG)

**Comment by SlvrEagle23** [comment] 2018-10-05 23:40
@karndt84 If you look at the Network tab on the browser's inspector and click on the HTTP request that generated the 500 error (it should be red), does it tell you any additional information?

**Comment by karndt84** [comment] 2018-10-06 00:40
![image](https://user-images.githubusercontent.com/9092791/46565600-3247e680-c911-11e8-8cdc-7c553240454d.png)

**Comment by SlvrEagle23** [comment] 2018-10-06 02:29
@karndt84 Looked into it and found it was caused by the fact that modifying a URL's port is considered giving the URL an "authority" (something after the scheme but before the path) in the spec, which led to it misparsing. Built in a special check that works around this, should be fixed across the board. Update and let me know.

**Closed by SlvrEagle23** 2018-10-06 02:29 UTC
Labels: bug

**Comment by karndt84** [comment] 2018-10-06 07:49
Thanks, it worked
