### ISSUE TITLE
Song Listener Impact

### ISSUE THREAD

**Issue by StringSurfer** [AzuraCast/AzuraCast#1938] opened 2019-09-05 11:53 UTC
Hi there.
Suddenly the Song Listener Impact page produces a 500 error page.
The link is at station/1/reports/performance
The Duplicate Songs is also having issues when I open the link station/1/reports/duplicates
I only have 1 radio at this server, and it has never been a problem before.
It occurred after the latest "Code Cleanup" update.
Just for ino :)

OS: CentOs 7
Docker Installation
Opera Browser

**Comment by SlvrEagle23** [comment] 2019-09-06 00:26
@StringSurfer Can you check the logs and see if there are any messages detailing what's specifically going wrong? I can't reproduce this locally, and I'm not 100% sure that it has anything to do with the code quality commit.

**Comment by StringSurfer** [comment] 2019-09-06 12:19
The only errors I can see are these:
12:01:44] WARN source/source_set_intro Cannot open intro for /radio.mp3 "/usr/local/share/icecast/web//radio.mp3": No such file or directory
[2019-08-27  11:03:15] WARN fserve/fserve_client_create req for file "/usr/local/share/icecast/web/nmaplowercheck1566896557" No such file or directory
[2019-08-27  11:03:15] WARN fserve/fserve_client_create req for file "/usr/local/share/icecast/web/evox/about" No such file or directory
[2019-08-27  11:03:16] WARN connection/http_client_request unhandled request type from 185.100.87.249
[2019-08-27  11:03:28] WARN fserve/fserve_client_create req for file "/usr/local/share/icecast/web/HNAP1" No such file or directory
[2019-08-27  15:44:27] WARN fserve/fserve_client_create req for file "/usr/local/share/icecast/web/robots.txt" No such file or directory
[2019-08-30  12:39:33] WARN slave/slave_startup process has 65536 max file descriptor limit

**Comment by SlvrEagle23** [comment] 2019-09-06 13:26
@StringSurfer The log of interest would be the AzuraCast log, available via the system administration log viewer. Generally any 500 errors would register there.

**Comment by StringSurfer** [comment] 2019-09-06 13:49
[2019-09-06T13:42:46.820182+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-09-06T13:43:01.402913+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-09-06T13:43:01.456554+00:00] AzuraCast.INFO: Running 1-minute sync task [] []
[2019-09-06T13:43:09.590280+00:00] AzuraCast.INFO: Running message queue processor for 300 seconds. [] []
[2019-09-06T13:43:16.259487+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-09-06T13:43:31.236565+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-09-06T13:43:46.243181+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-09-06T13:43:48.085558+00:00] AzuraCast.INFO: New message of type App\Message\UpdateNowPlayingMessage added to queue. [] []
[2019-09-06T13:43:50.085457+00:00] AzuraCast.INFO: Handling message of type App\Message\UpdateNowPlayingMessage. [] []
[2019-09-06T13:44:01.859721+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-09-06T13:44:01.887193+00:00] AzuraCast.INFO: Running 1-minute sync task [] []
[2019-09-06T13:44:16.655101+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-09-06T13:44:31.669894+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-09-06T13:44:46.670447+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-09-06T13:45:02.369300+00:00] AzuraCast.INFO: Running 5-minute sync task [] []
[2019-09-06T13:45:02.442543+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-09-06T13:45:02.459006+00:00] AzuraCast.INFO: Running 1-minute sync task [] []
[2019-09-06T13:45:17.099941+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-09-06T13:45:32.095494+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-09-06T13:45:47.079969+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-09-06T13:46:01.672778+00:00] AzuraCast.INFO: Running 1-minute sync task [] []
[2019-09-06T13:46:01.689478+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-09-06T13:46:16.498564+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-09-06T13:46:31.499865+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-09-06T13:46:46.499862+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-09-06T13:47:02.099508+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-09-06T13:47:02.118530+00:00] AzuraCast.INFO: Running 1-minute sync task [] []
[2019-09-06T13:47:16.909852+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-09-06T13:47:31.923776+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-09-06T13:47:46.926554+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-09-06T13:47:50.776683+00:00] AzuraCast.INFO: New message of type App\Message\UpdateNowPlayingMessage added to queue. [] []
[2019-09-06T13:47:52.776500+00:00] AzuraCast.INFO: Handling message of type App\Message\UpdateNowPlayingMessage. [] []
[2019-09-06T13:47:52.922554+00:00] AzuraCast.INFO: AzuraCast AutoDJ is calculating the next song to play... [] {"station":{"id":1,"name":"FavorittRadio.Com"}}
[2019-09-06T13:47:52.933122+00:00] AzuraCast.INFO: Playable playlists of type "once_per_x_minutes" found. {"8":3} {"station":{"id":1,"name":"FavorittRadio.Com"}}
[2019-09-06T13:47:52.934627+00:00] AzuraCast.INFO: Found track that avoids title and artist match! {"media_id":1821} {"station":{"id":1,"name":"FavorittRadio.Com"}}
[2019-09-06T13:47:52.940850+00:00] AzuraCast.INFO: Playable track found and registered. [] {"station":{"id":1,"name":"FavorittRadio.Com"}}
[2019-09-06T13:48:01.561754+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-09-06T13:48:01.564091+00:00] AzuraCast.INFO: Running 1-minute sync task [] []
[2019-09-06T13:48:13.331175+00:00] AzuraCast.INFO: Running message queue processor for 300 seconds. [] []
[2019-09-06T13:48:16.356579+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-09-06T13:48:31.353209+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-09-06T13:48:46.356764+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-09-06T13:49:01.956060+00:00] AzuraCast.INFO: Running 1-minute sync task [] []
[2019-09-06T13:49:01.995475+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-09-06T13:49:16.779983+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-09-06T13:49:31.779711+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-09-06T13:49:46.778510+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-09-06T13:50:02.578389+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-09-06T13:50:02.604757+00:00] AzuraCast.INFO: Running 5-minute sync task [] []
[2019-09-06T13:50:02.606920+00:00] AzuraCast.INFO: Running 1-minute sync task [] []

**Comment by StringSurfer** [comment] 2019-09-06 13:51
No 500 messages there, and I`ve tried compose-down, and compose -up -d, with no luck. Ran an update afterwards, but the errors still persists. Now I even can`t save passwords, or playlists without errors. May be a chmod error?

**Comment by SlvrEagle23** [comment] 2019-09-06 14:00
@StringSurfer I'm really not sure what would be causing those errors. I know that with CentOS, historically we've had some permissions issues that are difficult to pin down and diagnose.

If you want, you can join our [Slack server](https://www.azuracast.com/slack) for more detailed support. We may need to look directly at your installation to figure out the problem..

**Comment by StringSurfer** [comment] 2019-09-06 14:24
Joined :)

**Comment by Vaalyn** [comment] 2021-04-20 13:01
Closing as resolved since there has been no recent reports regarding the Song Listener Impact page failing.

**Closed by Vaalyn** 2021-04-20 13:01 UTC
Labels: bug
