### ISSUE TITLE
Unable to run backups via CLI - StorageLocationRepository::findByType(): Argument #2 ($id) must be of type int. string given

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#5348] opened 2022-05-05 21:02 UTC
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#97aaaa3

### What happened?

I'm currently in the middle of updating some documentation and came across this issue, can't for the life of me figure it out, so posting it here. 

Attempting to execute > `./docker.sh cli azuracast:backup --exclude-media main.zip` returns a large error, no backup file 

### Relevant log output

```shell
[2022-05-05T20:58:29.013867+00:00] AzuraCast.ERROR: TypeError: App\Entity\Repository\StorageLocationRepository::findByType(): Argument #2 ($id) must be of type int, string given, called in /var/azuracast/www/src/Console/Command/Backup/BackupCommand.php on line 82 (uncaught exception) at /var/azuracast/www/src/Entity/Repository/StorageLocationRepository.php line 16 while running console command `azuracast:backup` {"exception":"[object] (TypeError(code: 0): App\\Entity\\Repository\\StorageLocationRepository::findByType(): Argument #2 ($id) must be of type int, string given, called in /var/azuracast/www/src/Console/Command/Backup/BackupCommand.php on line 82 at /var/azuracast/www/src/Entity/Repository/StorageLocationRepository.php:16)"} []
[2022-05-05T20:58:29.015955+00:00] AzuraCast.WARNING: Console command `azuracast:backup` exited with error code 1. [] []
[05-May-2022 20:58:29 UTC] PHP Fatal error:  Uncaught TypeError: App\Entity\Repository\StorageLocationRepository::findByType(): Argument #2 ($id) must be of type int, string given, called in /var/azuracast/www/src/Console/Command/Backup/BackupCommand.php on line 82 and defined in /var/azuracast/www/src/Entity/Repository/StorageLocationRepository.php:16
Stack trace:
#0 /var/azuracast/www/src/Console/Command/Backup/BackupCommand.php(82): App\Entity\Repository\StorageLocationRepository->findByType()
#1 /var/azuracast/www/vendor/symfony/console/Command/Command.php(291): App\Console\Command\Backup\BackupCommand->execute()
#2 /var/azuracast/www/vendor/symfony/console/Application.php(1007): Symfony\Component\Console\Command\Command->run()
#3 /var/azuracast/www/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#4 /var/azuracast/www/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#5 /var/azuracast/www/bin/console(17): Symfony\Component\Console\Application->run()
#6 {main}
  thrown in /var/azuracast/www/src/Entity/Repository/StorageLocationRepository.php on line 16

Fatal error: Uncaught TypeError: App\Entity\Repository\StorageLocationRepository::findByType(): Argument #2 ($id) must be of type int, string given, called in /var/azuracast/www/src/Console/Command/Backup/BackupCommand.php on line 82 and defined in /var/azuracast/www/src/Entity/Repository/StorageLocationRepository.php on line 16

TypeError: App\Entity\Repository\StorageLocationRepository::findByType(): Argument #2 ($id) must be of type int, string given, called in /var/azuracast/www/src/Console/Command/Backup/BackupCommand.php on line 82 in /var/azuracast/www/src/Entity/Repository/StorageLocationRepository.php on line 16

Call Stack:
    0.0001     349800   1. {main}() /var/azuracast/www/bin/console:0
    0.2216    3045160   2. Symfony\Component\Console\Application->run($input = ???, $output = ???) /var/azuracast/www/bin/console:17
    0.2340    3121360   3. Symfony\Component\Console\Application->doRun($input = class Symfony\Component\Console\Input\ArgvInput { protected $definition = class Symfony\Component\Console\Input\InputDefinition { private array $arguments = [...]; private int $requiredCount = 2; private $lastArrayArgument = NULL; private $lastOptionalArgument = NULL; private array $options = [...]; private array $negations = [...]; private array $shortcuts = [...] }; protected $stream = NULL; protected $options = ['exclude-media' => TRUE]; protected $arguments = ['command' => 'azuracast:backup', 'path' => 'main.zip']; protected $interactive = TRUE; private array $tokens = [0 => 'azuracast:backup', 1 => '--exclude-media', 2 => 'main.zip']; private array $parsed = [] }, $output = class Symfony\Component\Console\Output\ConsoleOutput { private int ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { private bool $decorated = TRUE; private array $styles = [...]; private $styleStack = class Symfony\Component\Console\Formatter\OutputFormatterStyleStack { ... } }; private ${Symfony\Component\Console\Output\StreamOutput}stream = resource(2) of type (stream); private $stderr = class Symfony\Component\Console\Output\StreamOutput { private int ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { ... }; private $stream = resource(3) of type (stream) }; private array $consoleSectionOutputs = [] }) /var/azuracast/www/vendor/symfony/console/Application.php:171
    0.2832    3853336   4. Symfony\Component\Console\Application->doRunCommand($command = class App\Console\Command\Backup\BackupCommand { private ${Symfony\Component\Console\Command\Command}application = class App\Console\Application { private array ${Symfony\Component\Console\Application}commands = [...]; private bool ${Symfony\Component\Console\Application}wantHelps = FALSE; private ${Symfony\Component\Console\Application}runningCommand = ...; private string ${Symfony\Component\Console\Application}name = 'AzuraCast Command Line Tools (Production)'; private string ${Symfony\Component\Console\Application}version = '0.16.0'; private ${Symfony\Component\Console\Application}commandLoader = class Symfony\Component\Console\CommandLoader\ContainerCommandLoader { ... }; private bool ${Symfony\Component\Console\Application}catchExceptions = TRUE; private bool ${Symfony\Component\Console\Application}autoExit = TRUE; private ${Symfony\Component\Console\Application}definition = class Symfony\Component\Console\Input\InputDefinition { ... }; private ${Symfony\Component\Console\Application}helperSet = class Symfony\Component\Console\Helper\HelperSet { ... }; private ${Symfony\Component\Console\Application}dispatcher = class Azura\SlimCallableEventDispatcher\SlimCallableEventDispatcher { ... }; private ${Symfony\Component\Console\Application}terminal = class Symfony\Component\Console\Terminal { ... }; private string ${Symfony\Component\Console\Application}defaultCommand = 'list'; private bool ${Symfony\Component\Console\Application}singleCommand = FALSE; private bool ${Symfony\Component\Console\Application}initialized = TRUE; private ${Symfony\Component\Console\Application}signalRegistry = class Symfony\Component\Console\SignalRegistry\SignalRegistry { ... }; private array ${Symfony\Component\Console\Application}signalsToDispatchEvent = [...] }; private ?string ${Symfony\Component\Console\Command\Command}name = 'azuracast:backup'; private ?string ${Symfony\Component\Console\Command\Command}processTitle = NULL; private array ${Symfony\Component\Console\Command\Command}aliases = []; private ${Symfony\Component\Console\Command\Command}definition = class Symfony\Component\Console\Input\InputDefinition { private array $arguments = [...]; private int $requiredCount = 1; private $lastArrayArgument = NULL; private $lastOptionalArgument = NULL; private array $options = [...]; private array $negations = [...]; private array $shortcuts = [...] }; private bool ${Symfony\Component\Console\Command\Command}hidden = FALSE; private string ${Symfony\Component\Console\Command\Command}help = ''; private string ${Symfony\Component\Console\Command\Command}description = 'Back up the AzuraCast database and statistics (and optionally media).'; private ${Symfony\Component\Console\Command\Command}fullDefinition = class Symfony\Component\Console\Input\InputDefinition { private array $arguments = [...]; private int $requiredCount = 2; private $lastArrayArgument = NULL; private $lastOptionalArgument = NULL; private array $options = [...]; private array $negations = [...]; private array $shortcuts = [...] }; private bool ${Symfony\Component\Console\Command\Command}ignoreValidationErrors = FALSE; private ?Closure ${Symfony\Component\Console\Command\Command}code = NULL; private array ${Symfony\Component\Console\Command\Command}synopsis = []; private array ${Symfony\Component\Console\Command\Command}usages = []; private ${Symfony\Component\Console\Command\Command}helperSet = class Symfony\Component\Console\Helper\HelperSet { private array $helpers = [...] }; protected App\Environment $environment = class App\Environment { protected array $data = [...]; protected array $defaults = [...] }; protected Doctrine\ORM\EntityManagerInterface $em = class App\Doctrine\DecoratedEntityManager { protected $wrapped = class Doctrine\ORM\EntityManager { ... }; protected Closure $createEm = class Closure { virtual $closure = "$this->{closure}", ... } }; protected App\Entity\Repository\StorageLocationRepository $storageLocationRepo = class App\Entity\Repository\StorageLocationRepository { protected string $entityClass = 'App\\Entity\\StorageLocation'; protected Doctrine\Persistence\ObjectRepository $repository = class Doctrine\ORM\EntityRepository { ... }; protected App\Doctrine\ReloadableEntityManagerInterface $em = class App\Doctrine\DecoratedEntityManager { ... }; protected Symfony\Component\Serializer\Serializer $serializer = class Symfony\Component\Serializer\Serializer { ... }; protected App\Environment $environment = class App\Environment { ... }; protected Psr\Log\LoggerInterface $logger = class Monolog\Logger { ... } } }, $input = class Symfony\Component\Console\Input\ArgvInput { protected $definition = class Symfony\Component\Console\Input\InputDefinition { private array $arguments = [...]; private int $requiredCount = 2; private $lastArrayArgument = NULL; private $lastOptionalArgument = NULL; private array $options = [...]; private array $negations = [...]; private array $shortcuts = [...] }; protected $stream = NULL; protected $options = ['exclude-media' => TRUE]; protected $arguments = ['command' => 'azuracast:backup', 'path' => 'main.zip']; protected $interactive = TRUE; private array $tokens = [0 => 'azuracast:backup', 1 => '--exclude-media', 2 => 'main.zip']; private array $parsed = [] }, $output = class Symfony\Component\Console\Output\ConsoleOutput { private int ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { private bool $decorated = TRUE; private array $styles = [...]; private $styleStack = class Symfony\Component\Console\Formatter\OutputFormatterStyleStack { ... } }; private ${Symfony\Component\Console\Output\StreamOutput}stream = resource(2) of type (stream); private $stderr = class Symfony\Component\Console\Output\StreamOutput { private int ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { ... }; private $stream = resource(3) of type (stream) }; private array $consoleSectionOutputs = [] }) /var/azuracast/www/vendor/symfony/console/Application.php:299

[2022-05-05T20:58:29.016539+00:00] AzuraCast.CRITICAL: Fatal error: Uncaught TypeError: App\Entity\Repository\StorageLocationRepository::findByType(): Argument #2 ($id) must be of type int, string given, called in /var/azuracast/www/src/Console/Command/Backup/BackupCommand.php on line 82 and defined in /var/azuracast/www/src/Entity/Repository/StorageLocationRepository.php:16 Stack trace: #0 /var/azuracast/www/src/Console/Command/Backup/BackupCommand.php(82): App\Entity\Repository\StorageLocationRepository->findByType() #1 /var/azuracast/www/vendor/symfony/console/Command/Command.php(291): App\Console\Command\Backup\BackupCommand->execute() #2 /var/azuracast/www/vendor/symfony/console/Application.php(1007): Symfony\Component\Console\Command\Command->run() #3 /var/azuracast/www/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand() #4 /var/azuracast/www/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun() #5 /var/azuracast/www/bin/console(17): Symfony\Component\Console\Application->run() #6 {main}   thrown in /var/azuracast/www/src/Entity/Repository/StorageLocationRepository.php on line 16 [] []
```

**Comment by Vaalyn** [comment] 2022-05-05 22:56
If I'm not mistaken the cause of this error is this line here:
https://github.com/AzuraCast/AzuraCast/blob/main/src/Console/Command/Backup/BackupCommand.php#L42

The last parameter is the value that is used if none is given for this option (in this case an empty string).

Then later on the value of that option is put into the following variable:
```php
$storageLocationId = $input->getOption('storage-location-id');
```

And then used in the method call for fetching the storage location here:

```php
$storageLocation = $this->storageLocationRepo->findByType(
    Entity\Enums\StorageLocationTypes::Backup,
    $storageLocationId
);
```

This method requires the 2nd parameter (in this case the value of `$storageLocationId`) to be an `int` but the default of the option used to initialize the variable is a string.

Before the method call there is a check that should prevent this from happening if the value is `null` but this doesn't work for empty strings 😉 

I have created a draft PR with a possible fix for this but I'll need your help to test this out @SC2Mitch since I'm currently not at home and can't test it myself.

**Closed** 2022-05-06 15:20 UTC
Labels: possible bug, php error, rolling-release
