### ISSUE TITLE
Folders lose their link to playlists

### ISSUE THREAD

**Issue by fidegr** [AzuraCast/AzuraCast#3973] opened 2021-04-05 06:07 UTC
AzuraCast • Rolling Release #10f6ba8 (2021-04-03 14:04) • Docker • PHP 7.4

Hello,
for a few days we have detected that the link of some folders with their respective playlists has started to disappear. As soon as there is a file change inside the folder, it loses the link with its playlist.

**Comment by eranwo** [comment] 2021-04-06 06:42
I'm having the same issue after upgrade today to Rolling Release #168327f (2021-04-06 1:02). 
Inside the directory it seems to be ok . 
I did not see any issue with the streaming, just the playlist column is empty.
![image](https://user-images.githubusercontent.com/2701228/113668736-5855c980-96bb-11eb-8a88-e9bbf32bc757.png)

![image](https://user-images.githubusercontent.com/2701228/113668883-93f09380-96bb-11eb-87ee-d27bc7b372f7.png)

**Comment by SlvrEagle23** [comment] 2021-04-06 11:27
@fidegr @eranwo We have identified the cause of this; it was caused by our upstream transition to V2 of the Flysystem library; we've updated our code accordingly to work around this issue, and that's currently being published to the Rolling Release branch; you'll need to reassign any removed folders back to those playlists, but they should persist without any issue after updating.

**Closed** 2021-04-10 02:00 UTC
Labels: bug, in progress
