### ISSUE TITLE
Waiting...Timed out waiting for services to start. azuracast docker. ubuntu 20.04

### ISSUE THREAD

**Issue by SaschaDK** [AzuraCast/AzuraCast#3710] opened 2021-01-25 00:19 UTC
Hi there.
when I try to install azuracast with docker I get this error when installing "Waiting ... Timed out waiting for services to start." i have tried on several different servers to see if there was anything with the speed of the hardware. but I get the same error.
if I try to run the installation command again it starts something Database Migrations. is it normal?
i also can not get ssl to work. even though I enter domain and mail during setup. when I visit web interface ssl is not valid.
i have tried a synology nas ds916 + and i could not get anything to work at all.
and on a virtual ubuntu 20.04 where it worked partially after the second attempt

I thank you many times for the help

/Sascha

**Comment by Abqehebter** [comment] 2021-01-31 00:48
I have exactly the same error... Had hoped that after a complete reinstall from the server itself and from AzuraCast it would fix some of my internal errors. Currently I only get a message from the web service that it is starting. The installation takes much longer than usual and I get too many timeouts on my end. Bit stupid at the moment.

**Comment by SlvrEagle23** [comment] 2021-01-31 15:27
Closing as duplicate of #3613.

**Closed by SlvrEagle23** 2021-01-31 15:27 UTC
