### ISSUE TITLE
playlist rotation rules

### ISSUE THREAD

**Issue by efsysefsys** [AzuraCast/AzuraCast#42] opened 2016-09-21 08:32 UTC
maby u can make playlist rotation rules.

**Example : Playlist rules** somthing like that

```
Do not play same artist within ( 120 ) minutes  - minutes can change
Do not play same title within ( 240 ) minutes - minutes can change
Do not play same track within ( 60 ) minutes - minutes can change

or do  not play same artist within ( 5 ) songs .. .  etc
```

because if playlist dont have rules if is standart shuffle playlist sometimes u listen same song after 2 songs after 1 song or 7 songs.

I think need php or pyton skript or maby sql table or column.Who save played songs and check time , etc .because i now some people create this function with php and liquidsoap

**Comment by SlvrEagle23** [comment] 2016-09-21 21:24
I've noticed this issue too, and it appears that it's caused by the LiquidSoap script being programmed to reload playlist contents too frequently. Each time the playlist contents are reloaded, the "shuffler" resets, and since the reloads are so close to one another, that means the same songs can play very close to one another. Updating it to "watch" will only trigger a playlist reload if the file's modified time changes, so while no changes are being made to the file no reloads will happen at all.

**Comment by efsysefsys** [comment] 2016-09-21 23:02
liquidsoap can independently store data last played tracks , it can be used ,to make rules.
Or you can type php script .Who will follow the server time . Saves the current playing song title and play time , date in database.And include this script to liquidsoap.In php script needs to impose regulations if hours or specify the time when the song was played then replace him with another or anything like that.I thing need sql help

**Comment by SlvrEagle23** [comment] 2017-05-16 07:46
Closing this issue, as putting AzuraCast in charge of the next playing song also allows it to implement this exact kind of functionality, which it now does; it will strongly avoid playing the most recently played songs.

**Closed by SlvrEagle23** 2017-05-16 07:46 UTC
Labels: enhancement
