### ISSUE TITLE
Docker install error

### ISSUE THREAD

**Issue by jonikane** [AzuraCast/AzuraCast#1603] opened 2019-05-29 16:53 UTC
**Using Docker installation method**
Yes

**Host Operating System**
Centos 7 X86 64 Minimal

**Describe the bug**
It is impossible to install Azuracast Panel on vps with centos.
It gave me an error.
![azuracast_docker_install_error](https://user-images.githubusercontent.com/7109309/58575743-aafe0900-823a-11e9-8842-953aaaa8c793.jpg)

**Comment by Vaalyn** [comment] 2019-05-29 17:02
Your OS is missing a package that our installer needs to run `which` you'll need to install it via `yum install which`. Then try running the installation again.

**Comment by jonikane** [comment] 2019-05-29 17:07
witch install done and docker but it gave another error on docker-composer
![azuracast_docker_install_error_1](https://user-images.githubusercontent.com/7109309/58576585-93c01b00-823c-11e9-84cd-ab0b58738924.jpg)

**Comment by Vaalyn** [comment] 2019-05-29 17:12
Have you installed Docker manually? After installing `which` our installer would have done that automatically. There are some additional steps that you have to do when installing Docker which are also done automatically by our installer so the easiest thing would be to remove the manually installed Docker from your system and let our installer do that.

**Comment by jonikane** [comment] 2019-05-29 17:13
I have used this guide:

mkdir -p /var/azuracast
cd /var/azuracast

curl -L https://raw.githubusercontent.com/AzuraCast/AzuraCast/master/docker.sh > docker.sh
chmod a+x docker.sh
./docker.sh install

**Comment by Vaalyn** [comment] 2019-05-29 17:26
Sorry, I overlooked that the script already installed it in your first screenshot. 😅 

After installing Docker the script tells you to log out or restart your server to apply the permission changes necessary for Docker to work.

```
You must log out or restart to apply necessary Docker permissions changes.
```

You can actually see this line in your first screenshot.

**Comment by jonikane** [comment] 2019-05-29 17:33
![azuracast_docker_install_error_2](https://user-images.githubusercontent.com/7109309/58578230-329a4680-8240-11e9-86d9-ccaa1495ebd0.jpg)

**Comment by Vaalyn** [comment] 2019-05-29 17:39
The official Docker installer that our installer uses seems to not automatically start the Docker Daemon after the installation.

From their documentation:
```
... On RPM-based distributions, you need to start it manually...
```

Try running `sudo systemctl start docker` and then run the script again.

**Comment by jonikane** [comment] 2019-05-29 17:54
i do that, but it gave this error:
![azuracast_docker_install_error_3](https://user-images.githubusercontent.com/7109309/58579519-2cf23000-8243-11e9-9cef-2856da516e9f.jpg)

**Comment by Vaalyn** [comment] 2019-05-29 17:57
Do what the error tells you, execute `systemctl status docker.service` and `journalctl -xe` to get more details about why it didn't start.

**Comment by jonikane** [comment] 2019-05-29 17:58
![azuracast_docker_install_error_4](https://user-images.githubusercontent.com/7109309/58579852-c7eb0a00-8243-11e9-95a8-808327af04ee.jpg)

**Comment by Vaalyn** [comment] 2019-05-29 18:08
Please be more careful when copy-pasting commands into your terminal!

You have copied 2 commands with the word `and` between them into your terminal. You have to execute them as 2 separate commands, that's why I put them into these code blocks: `xxxxx`

**Comment by jonikane** [comment] 2019-05-29 18:09
ah ok.
i will see that

thank you

**Comment by jonikane** [comment] 2019-05-29 18:15
There is another way to install this?
I´m getting to many errors
![azuracast_docker_install_error_5](https://user-images.githubusercontent.com/7109309/58580889-0f729580-8246-11e9-8432-53247c842a9a.jpg)

**Comment by jonikane** [comment] 2019-05-29 18:24
![azuracast_docker_install_error_6](https://user-images.githubusercontent.com/7109309/58581399-5f9e2780-8247-11e9-827f-b014d6e6e847.jpg)

**Comment by Vaalyn** [comment] 2019-05-29 19:04
We generally recommend using Ubuntu 18.04 or Debian 9 as the host OS as Centos often causes the weirdest errors.

**Comment by jonikane** [comment] 2019-05-29 19:09
ah ok

I will try that.

Thank you

**Comment by eliasestrada** [comment] 2019-06-01 06:59
Greetings, I'm using Ubuntu CyberPanel on 18.04 but I can not install azuracast using the docker manager, someone has a guide to do it.

**Comment by Vaalyn** [comment] 2019-06-02 12:15
@eliasestrada You should create a separate issue for this.

**Comment by Vaalyn** [comment] 2019-06-12 13:47
@jonikane I assume the issue is resolved so I'll close it now. If you still need help getting AzuraCast installed via Docker let me know.

**Closed by Vaalyn** 2019-06-12 13:47 UTC
Labels: error
