### ISSUE TITLE
NowPlaying sync task not working since 0.17.4 update

### ISSUE THREAD

**Issue by balmasedano** [AzuraCast/AzuraCast#5814] opened 2022-10-29 12:57 UTC
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.17.4

### What happened?

Since the last update, the now playing sync task is not working properly.

First, stations list at dashboard doesn't work. When I manage a station, they appear as disconnected. When I manually execute ./docker.sh cli azuracast:sync:nowplaying, all starts working and all the station list correctly at the main dashboard, but song titles don't update automatically. I have to re-execute the manual command via CLI.

During the manual sync, I get some errors, like these:

* AzuraCast.ERROR: Request returned status code 400.
* Symfony\Component\Lock\Exception\LockConflictedException

Thank you!

### Relevant log output

```shell
[2022-10-29T12:51:42.469460+00:00] AzuraCast.WARNING: Could not fetch XML data; falling back to public JSON. [] {"station":{"id":7,"name":"RockStar"}}
[2022-10-29T12:51:42.592754+00:00] AzuraCast.ERROR: Request returned status code 400. {"body":""} {"station":{"id":7,"name":"RockStar"}}

[2022-10-29T12:49:33.498066+00:00] AzuraCast.ERROR: Symfony\Component\Lock\Exception\LockConflictedException:  (uncaught exception) at /var/azuracast/www/vendor/symfony/lock/Store/RedisStore.php line 179 while running console command `azuracast:sync:nowplaying` {"exception":"[object] (Symfony\\Component\\Lock\\Exception\\LockConflictedException(code: 0):  at /var/azuracast/www/vendor/symfony/lock/Store/RedisStore.php:179)"} []
[2022-10-29T12:49:33.498464+00:00] AzuraCast.WARNING: Console command `azuracast:sync:nowplaying` exited with error code 1. [] []

In RedisStore.php line 179:
                                                              
  [Symfony\Component\Lock\Exception\LockConflictedException]
```

**Comment by balmasedano** [comment] 2022-10-29 13:01
I think this issue can be related to #5807

**Comment by BusterNeece** [comment] 2022-10-30 11:27
Closing as duplicate of #5807.

**Closed by BusterNeece** 2022-10-30 11:27 UTC
Labels: needs investigation
