### ISSUE TITLE
Fix for the Artworks

### ISSUE THREAD

**Issue by NicoxDJ** [AzuraCast/AzuraCast#3673] opened 2021-01-14 17:01 UTC
I'm starting directly without system information, because this is something that never worked properly.
So there are different type of Artwork storage in the files. getID3 finds it in different arrays.
I had the same problem before (in one file manager that i created), and i made deep analyzing of all the tags from different kind of files (mp3 and m4a).
So after digging in your code i found out that you use:
```
if (!empty($info['attached_picture'][0])) {
            $metadata->setArtwork($info['attached_picture'][0]['data']);
        } elseif (!empty($info['comments']['picture'][0])) {
            $metadata->setArtwork($info['comments']['picture'][0]['data']);
        }
```
So you're searching only in `attached_picture` and in `comments`

What i'm using is:
```
if (isset($getID3->info['id3v2']['APIC'][0]['data'])) { 
	$cover = $getID3->info['id3v2']['APIC'][0]['data'];
} elseif (isset($getID3->info['id3v2']['PIC'][0]['data'])) { 
	$cover = $getID3->info['id3v2']['PIC'][0]['data']; 
} elseif (isset($getID3->info['comments']['picture'][0]['data'])) { 
	$cover = $getID3->info['comments']['picture'][0]['data'];
} else { 
	$cover = null; 
}
```
So this is enough to display all kind of m4a's too. Right now AzuraCast didn't display many m4a files artworks. I don't know which exactly, it's mixed. If you need, tell me and i'll send you exact m4a that didn't show artwork.

PS: I continue to digg, for one of the songs that didn't display artwork. Actually there is artwork for that song in the .albumart folder. With the same unique_id. So than maybe it's some problem with the API finding the Artworks?
Even in the dashboard, there is not artwork showed.
![](https://i.imgur.com/6oljIsM.png)
![](https://i.imgur.com/OAYgg6B.png)
![](https://i.imgur.com/jPPFxsg.png)
![](https://i.imgur.com/SiREziI.png)
![](https://i.imgur.com/j3eTAYC.png)

**Comment by NicoxDJ** [comment] 2021-01-14 18:04
OK, Last information. It's about the PLAY NOW artwork only. As you see on the photos below, it loads the image while is in Playing Next, but in Now Playing no.
![](https://i.imgur.com/rnOrfSB.png)
![](https://i.imgur.com/rvQgnuY.png)

**Comment by Vaalyn** [comment] 2021-01-14 19:21
I've submitted a PR that adds those 2 additional fields to the lookup in our code.
Thank you for providing us with those. 👍 

@NicoxDJ can you send me the file where the artwork was extracted but not used and the one were the artwork was shown in the playing next but was not used when it was played? I'll try to reproduce that on my test installation then.

**Comment by NicoxDJ** [comment] 2021-01-14 19:34
@Vaalyn i sent you email with the song

**Comment by Vaalyn** [comment] 2021-01-14 19:58
Have tested the file on my test installation and it's correctly showing me the artwork:

![image](https://user-images.githubusercontent.com/13745863/104642475-3eec4500-56ab-11eb-83ec-24fbc215c094.png)


So it's most likely not related to the audio file itself.

**Comment by NicoxDJ** [comment] 2021-01-14 20:07
Hm, i checked all images permissions, looks fine. I cleared all caches that is possible with the console binary. I restart the server. It's still the same. In Now Playing not showing, in Playing next is fine. And this is only for m4a. Mp3 are fine in the both fields. I didn't get the last updates with the ACL.. if they are important?

**Comment by Vaalyn** [comment] 2021-01-14 20:12
@NicoxDJ you mean the update with `Fix Acl error on actions without a user like internal API calls`?

If so then yeah that might be related **if**(!) you are on a rolling-release version equal to or higher than 7441d13472fd3d16958fa313889d38257d29aebe and lower than 03b79d93e69bd6de36a6c8d70ac54006abdda000 there.

Which version are you on currently?

**Comment by NicoxDJ** [comment] 2021-01-14 20:14
@Vaalyn Rolling Release #1d70420 (2021-01-07 9:37). Just hitting the short update

**Comment by NicoxDJ** [comment] 2021-01-14 21:06
@Vaalyn nope, same deal :( Even i just catch one mp3 that is doing the same thing.

**Comment by Paulio759** [comment] 2021-01-19 22:27
@NicoxDJ We have the same issue with the images. It followed an update some months ago. There were also problems with track name etc in the API but these seem to have been resolved now. The images are still not working properly though which it a big problem for us.

**Comment by NicoxDJ** [comment] 2021-01-26 09:45
@Vaalyn @SlvrEagle23 Hey guys, even more strange thing. My AutoDJ Queue Length is set to 10. I've notice that after running few hours normal, it start overloading the queue. It reach numbers like 25-39... and than the station stops, while the Liquidsoap is still running.
It's really big mess up. After restart, it starts again properly, and again, filling queue, and stops.

![](https://i.imgur.com/32fJq2d.png)
![](https://i.imgur.com/IkViv3Q.png)
![](https://i.imgur.com/XQ2i2ZL.png)

**Comment by SlvrEagle23** [comment] 2021-01-26 10:35
@NicoxDJ And neither you nor anybody else who can manage your installation is using the "Queue" function from the Media Manager? The system absolutely should never be letting the queue overrun like that on its own, unless people are adding to the queue directly.

**Comment by NicoxDJ** [comment] 2021-01-26 10:40
@SlvrEagle23 Nope. I think these songs right now are skipped by Liquidsoap. i.e. it thinks they are not playable somehow. I forgot to mention, that before restart i have to clear the queue from mysql, and then it's fine. Or else it's not running after restart too.

**Comment by NicoxDJ** [comment] 2021-01-26 11:00
@SlvrEagle23 this problem appears after the update in the beginning of this year. The whole Christmas was fine. 
I just wen't to delete the queue again, and i've notice something strange:
![](https://i.imgur.com/qAAyGPu.png)

The first songs have media_id and are not sent to Liquidsoap.
Than this error (in the log field), and the rest of the files doesn't have media_id but are sent to Liquidsoap
```
[{"message":"AzuraCast AutoDJ is calculating the next song to play...","context":[],"level":200,"level_name":"INFO","channel":"AzuraCast","datetime":"2021-01-22T21:52:33.013112+00:00","extra":{"station":{"id":1,"name":"Radio Club-BG"}},"formatted":"[2021-01-22T21:52:33.013112+00:00] AzuraCast.INFO: AzuraCast AutoDJ is calculating the next song to play... [] {\"station\":{\"id\":1,\"name\":\"Radio Club-BG\"}}\n"},{"message":"AutoDJ recent song playback history","context":{"history_once_per_x_songs":[{"song":"ALMA - Fake Gucci","cued_at":"2021-01-23 00:24:43","duration":187,"sent_to_autodj":false},{"song":"Ellie Goulding & Juice WRLD - Hate Me","cued_at":"2021-01-23 00:23:54","duration":186,"sent_to_autodj":false},{"song":"Tory Lanez - Hillside (feat. Wiz Khalifa & Mansa)","cued_at":"2021-01-23 00:18:36","duration":209,"sent_to_autodj":false},{"song":"David Guetta - She Knows How to Love Me (feat. Jess Glynne & Stefflon Don)","cued_at":"2021-01-23 00:14:32","duration":181,"sent_to_autodj":false},{"song":"Maria Karakusheva & DJ Borra - Harmony","cued_at":"2021-01-23 00:10:51","duration":234,"sent_to_autodj":false},{"song":"Lil Nas X & Cardi B - Rodeo","cued_at":"2021-01-23 00:07:50","duration":158,"sent_to_autodj":false},{"song":"Logic - Keanu Reeves","cued_at":"2021-01-23 00:03:48","duration":226,"sent_to_autodj":false},{"song":"Angel Stoxx Feat. Drew - Let Go (Extended Mix)","cued_at":"2021-01-22 23:59:33","duration":336,"sent_to_autodj":false},{"song":"Tommy Genesis - You Know Me (MadeinTYO Remix)","cued_at":"2021-01-22 23:55:57","duration":187,"sent_to_autodj":false},{"song":"ScHoolboy Q - THat Part (feat. Kanye West)","cued_at":"2021-01-22 23:52:07","duration":null,"sent_to_autodj":true},{"song":"A$AP Ferg - Wigs (feat. City Girls & Antha)","cued_at":"2021-01-22 23:51:56","duration":179,"sent_to_autodj":true},{"song":"Akcent - Deeply In Love (feat. Jordan)","cued_at":"2021-01-22 23:48:19","duration":null,"sent_to_autodj":null},{"song":"Tamta - Replay","cued_at":"2021-01-22 23:45:35","duration":173,"sent_to_autodj":null},{"song":"Kid Ink - Bunny Ranch","cued_at":"2021-01-22 23:42:52","duration":163,"sent_to_autodj":null},{"song":"Future - How Can I Not (feat. Young Scooter)","cued_at":"2021-01-22 23:39:01","duration":231,"sent_to_autodj":null}],"history_duplicate_prevention":[{"song":"ALMA - Fake Gucci","cued_at":"2021-01-23 00:24:43","duration":187,"sent_to_autodj":false},{"song":"Ellie Goulding & Juice WRLD - Hate Me","cued_at":"2021-01-23 00:23:54","duration":186,"sent_to_autodj":false},{"song":"Tory Lanez - Hillside (feat. Wiz Khalifa & Mansa)","cued_at":"2021-01-23 00:18:36","duration":209,"sent_to_autodj":false},{"song":"David Guetta - She Knows How to Love Me (feat. Jess Glynne & Stefflon Don)","cued_at":"2021-01-23 00:14:32","duration":181,"sent_to_autodj":false},{"song":"Maria Karakusheva & DJ Borra - Harmony","cued_at":"2021-01-23 00:10:51","duration":234,"sent_to_autodj":false},{"song":"Lil Nas X & Cardi B - Rodeo","cued_at":"2021-01-23 00:07:50","duration":158,"sent_to_autodj":false},{"song":"Logic - Keanu Reeves","cued_at":"2021-01-23 00:03:48","duration":226,"sent_to_autodj":false},{"song":"Angel Stoxx Feat. Drew - Let Go (Extended Mix)","cued_at":"2021-01-22 23:59:33","duration":336,"sent_to_autodj":false},{"song":"Tommy Genesis - You Know Me (MadeinTYO Remix)","cued_at":"2021-01-22 23:55:57","duration":187,"sent_to_autodj":false},{"song":"A$AP Ferg - Wigs (feat. City Girls & Antha)","cued_at":"2021-01-22 23:51:56","duration":179,"sent_to_autodj":true},{"song":"ScHoolboy Q - THat Part (feat. Kanye West)","cued_at":"2021-01-22 23:52:22","duration":null,"sent_to_autodj":null},{"song":"Akcent - Deeply In Love (feat. Jordan)","cued_at":"2021-01-22 23:48:19","duration":243,"sent_to_autodj":null},{"song":"Tamta - Replay","cued_at":"2021-01-22 23:45:35","duration":173,"sent_to_autodj":null},{"song":"Kid Ink - Bunny Ranch","cued_at":"2021-01-22 23:42:52","duration":163,"sent_to_autodj":null},{"song":"Future - How Can I Not (feat. Young Scooter)","cued_at":"2021-01-22 23:39:01","duration":231,"sent_to_autodj":null},{"song":"Kiesza - Phantom of the Dance Floor","cued_at":"2021-01-22 23:35:18","duration":223,"sent_to_autodj":null},{"song":"Quavo - 200 000","cued_at":"2021-01-22 23:31:03","duration":255,"sent_to_autodj":null},{"song":"Ty Dolla $ign - Blas\u00e9 (feat. Future & Rae Sremmurd)","cued_at":"2021-01-22 23:26:26","duration":277,"sent_to_autodj":null},{"song":"Jay Sean - Make My Love Go (feat. Sean Paul)","cued_at":"2021-01-22 23:22:57","duration":209,"sent_to_autodj":null},{"song":"Lil Baby & Saint Vinci - Looking for 30's","cued_at":"2021-01-22 23:18:57","duration":240,"sent_to_autodj":null},{"song":"Tech N9ne - Erbody but Me (feat. Bizzy & Krizz Kaliko)","cued_at":"2021-01-22 23:15:46","duration":191,"sent_to_autodj":null},{"song":"Chris Brown & Tyga - Lights Out (feat. Fat Trel)","cued_at":"2021-01-22 23:11:04","duration":286,"sent_to_autodj":null},{"song":"Topic - Fly Away (feat. Lili Pistorius)","cued_at":"2021-01-22 23:07:53","duration":199,"sent_to_autodj":null},{"song":"Years & Years - Sanctify","cued_at":"2021-01-22 23:04:48","duration":189,"sent_to_autodj":null},{"song":"Amira - Lonely (Extended Version)","cued_at":"2021-01-22 23:00:24","duration":275,"sent_to_autodj":null},{"song":"Busta Rhymes feat. Missy Elliott - How We Do It Over Here (Maga Remix)","cued_at":"2021-01-22 22:57:16","duration":193,"sent_to_autodj":null},{"song":"Ice Cube - On Them Pills","cued_at":"2021-01-22 22:53:26","duration":230,"sent_to_autodj":null},{"song":"Oriana - False Start","cued_at":"2021-01-22 22:50:04","duration":202,"sent_to_autodj":null},{"song":"Yall - Hundred Miles (feat. Gabriela Richardson)","cued_at":"2021-01-22 22:47:18","duration":166,"sent_to_autodj":null},{"song":"Beyonc\u00e9 & JAY-Z - FRIENDS","cued_at":"2021-01-22 22:41:41","duration":344,"sent_to_autodj":null},{"song":"Dj Esco - Juice Feat. Future","cued_at":"2021-01-22 22:38:25","duration":201,"sent_to_autodj":null},{"song":"eleven7four - We Met In France","cued_at":"2021-01-22 22:35:48","duration":157,"sent_to_autodj":null},{"song":"Sergio - Lately","cued_at":"2021-01-22 22:32:57","duration":178,"sent_to_autodj":null},{"song":"Macklemore - Corner Store (feat. Dave B & Travis Thompson)","cued_at":"2021-01-22 22:28:31","duration":266,"sent_to_autodj":null}]},"level":100,"level_name":"DEBUG","channel":"AzuraCast","datetime":"2021-01-22T21:52:41.145670+00:00","extra":{"station":{"id":1,"name":"Radio Club-BG"}},"formatted":"[2021-01-22T21:52:41.145670+00:00] AzuraCast.DEBUG: AutoDJ recent song playback history {\"history_once_per_x_songs\":[{\"song\":\"ALMA - Fake Gucci\",\"cued_at\":\"2021-01-23 00:24:43\",\"duration\":187,\"sent_to_autodj\":false},{\"song\":\"Ellie Goulding & Juice WRLD - Hate Me\",\"cued_at\":\"2021-01-23 00:23:54\",\"duration\":186,\"sent_to_autodj\":false},{\"song\":\"Tory Lanez - Hillside (feat. Wiz Khalifa & Mansa)\",\"cued_at\":\"2021-01-23 00:18:36\",\"duration\":209,\"sent_to_autodj\":false},{\"song\":\"David Guetta - She Knows How to Love Me (feat. Jess Glynne & Stefflon Don)\",\"cued_at\":\"2021-01-23 00:14:32\",\"duration\":181,\"sent_to_autodj\":false},{\"song\":\"Maria Karakusheva & DJ Borra - Harmony\",\"cued_at\":\"2021-01-23 00:10:51\",\"duration\":234,\"sent_to_autodj\":false},{\"song\":\"Lil Nas X & Cardi B - Rodeo\",\"cued_at\":\"2021-01-23 00:07:50\",\"duration\":158,\"sent_to_autodj\":false},{\"song\":\"Logic - Keanu Reeves\",\"cued_at\":\"2021-01-23 00:03:48\",\"duration\":226,\"sent_to_autodj\":false},{\"song\":\"Angel Stoxx Feat. Drew - Let Go (Extended Mix)\",\"cued_at\":\"2021-01-22 23:59:33\",\"duration\":336,\"sent_to_autodj\":false},{\"song\":\"Tommy Genesis - You Know Me (MadeinTYO Remix)\",\"cued_at\":\"2021-01-22 23:55:57\",\"duration\":187,\"sent_to_autodj\":false},{\"song\":\"ScHoolboy Q - THat Part (feat. Kanye West)\",\"cued_at\":\"2021-01-22 23:52:07\",\"duration\":null,\"sent_to_autodj\":true},{\"song\":\"A$AP Ferg - Wigs (feat. City Girls & Antha)\",\"cued_at\":\"2021-01-22 23:51:56\",\"duration\":179,\"sent_to_autodj\":true},{\"song\":\"Akcent - Deeply In Love (feat. Jordan)\",\"cued_at\":\"2021-01-22 23:48:19\",\"duration\":null,\"sent_to_autodj\":null},{\"song\":\"Tamta - Replay\",\"cued_at\":\"2021-01-22 23:45:35\",\"duration\":173,\"sent_to_autodj\":null},{\"song\":\"Kid Ink - Bunny Ranch\",\"cued_at\":\"2021-01-22 23:42:52\",\"duration\":163,\"sent_to_autodj\":null},{\"song\":\"Future - How Can I Not (feat. Young Scooter)\",\"cued_at\":\"2021-01-22 23:39:01\",\"duration\":231,\"sent_to_autodj\":null}],\"history_duplicate_prevention\":[{\"song\":\"ALMA - Fake Gucci\",\"cued_at\":\"2021-01-23 00:24:43\",\"duration\":187,\"sent_to_autodj\":false},{\"song\":\"Ellie Goulding & Juice WRLD - Hate Me\",\"cued_at\":\"2021-01-23 00:23:54\",\"duration\":186,\"sent_to_autodj\":false},{\"song\":\"Tory Lanez - Hillside (feat. Wiz Khalifa & Mansa)\",\"cued_at\":\"2021-01-23 00:18:36\",\"duration\":209,\"sent_to_autodj\":false},{\"song\":\"David Guetta - She Knows How to Love Me (feat. Jess Glynne & Stefflon Don)\",\"cued_at\":\"2021-01-23 00:14:32\",\"duration\":181,\"sent_to_autodj\":false},{\"song\":\"Maria Karakusheva & DJ Borra - Harmony\",\"cued_at\":\"2021-01-23 00:10:51\",\"duration\":234,\"sent_to_autodj\":false},{\"song\":\"Lil Nas X & Cardi B - Rodeo\",\"cued_at\":\"2021-01-23 00:07:50\",\"duration\":158,\"sent_to_autodj\":false},{\"song\":\"Logic - Keanu Reeves\",\"cued_at\":\"2021-01-23 00:03:48\",\"duration\":226,\"sent_to_autodj\":false},{\"song\":\"Angel Stoxx Feat. Drew - Let Go (Extended Mix)\",\"cued_at\":\"2021-01-22 23:59:33\",\"duration\":336,\"sent_to_autodj\":false},{\"song\":\"Tommy Genesis - You Know Me (MadeinTYO Remix)\",\"cued_at\":\"2021-01-22 23:55:57\",\"duration\":187,\"sent_to_autodj\":false},{\"song\":\"A$AP Ferg - Wigs (feat. City Girls & Antha)\",\"cued_at\":\"2021-01-22 23:51:56\",\"duration\":179,\"sent_to_autodj\":true},{\"song\":\"ScHoolboy Q - THat Part (feat. Kanye West)\",\"cued_at\":\"2021-01-22 23:52:22\",\"duration\":null,\"sent_to_autodj\":null},{\"song\":\"Akcent - Deeply In Love (feat. Jordan)\",\"cued_at\":\"2021-01-22 23:48:19\",\"duration\":243,\"sent_to_autodj\":null},{\"song\":\"Tamta - Replay\",\"cued_at\":\"2021-01-22 23:45:35\",\"duration\":173,\"sent_to_autodj\":null},{\"song\":\"Kid Ink - Bunny Ranch\",\"cued_at\":\"2021-01-22 23:42:52\",\"duration\":163,\"sent_to_autodj\":null},{\"song\":\"Future - How Can I Not (feat. Young Scooter)\",\"cued_at\":\"2021-01-22 23:39:01\",\"duration\":231,\"sent_to_autodj\":null},{\"song\":\"Kiesza - Phantom of the Dance Floor\",\"cued_at\":\"2021-01-22 23:35:18\",\"duration\":223,\"sent_to_autodj\":null},{\"song\":\"Quavo - 200 000\",\"cued_at\":\"2021-01-22 23:31:03\",\"duration\":255,\"sent_to_autodj\":null},{\"song\":\"Ty Dolla $ign - Blas\u00e9 (feat. Future & Rae Sremmurd)\",\"cued_at\":\"2021-01-22 23:26:26\",\"duration\":277,\"sent_to_autodj\":null},{\"song\":\"Jay Sean - Make My Love Go (feat. Sean Paul)\",\"cued_at\":\"2021-01-22 23:22:57\",\"duration\":209,\"sent_to_autodj\":null},{\"song\":\"Lil Baby & Saint Vinci - Looking for 30's\",\"cued_at\":\"2021-01-22 23:18:57\",\"duration\":240,\"sent_to_autodj\":null},{\"song\":\"Tech N9ne - Erbody but Me (feat. Bizzy & Krizz Kaliko)\",\"cued_at\":\"2021-01-22 23:15:46\",\"duration\":191,\"sent_to_autodj\":null},{\"song\":\"Chris Brown & Tyga - Lights Out (feat. Fat Trel)\",\"cued_at\":\"2021-01-22 23:11:04\",\"duration\":286,\"sent_to_autodj\":null},{\"song\":\"Topic - Fly Away (feat. Lili Pistorius)\",\"cued_at\":\"2021-01-22 23:07:53\",\"duration\":199,\"sent_to_autodj\":null},{\"song\":\"Years & Years - Sanctify\",\"cued_at\":\"2021-01-22 23:04:48\",\"duration\":189,\"sent_to_autodj\":null},{\"song\":\"Amira - Lonely (Extended Version)\",\"cued_at\":\"2021-01-22 23:00:24\",\"duration\":275,\"sent_to_autodj\":null},{\"song\":\"Busta Rhymes feat. Missy Elliott - How We Do It Over Here (Maga Remix)\",\"cued_at\":\"2021-01-22 22:57:16\",\"duration\":193,\"sent_to_autodj\":null},{\"song\":\"Ice Cube - On Them Pills\",\"cued_at\":\"2021-01-22 22:53:26\",\"duration\":230,\"sent_to_autodj\":null},{\"song\":\"Oriana - False Start\",\"cued_at\":\"2021-01-22 22:50:04\",\"duration\":202,\"sent_to_autodj\":null},{\"song\":\"Yall - Hundred Miles (feat. Gabriela Richardson)\",\"cued_at\":\"2021-01-22 22:47:18\",\"duration\":166,\"sent_to_autodj\":null},{\"song\":\"Beyonc\u00e9 & JAY-Z - FRIENDS\",\"cued_at\":\"2021-01-22 22:41:41\",\"duration\":344,\"sent_to_autodj\":null},{\"song\":\"Dj Esco - Juice Feat. Future\",\"cued_at\":\"2021-01-22 22:38:25\",\"duration\":201,\"sent_to_autodj\":null},{\"song\":\"eleven7four - We Met In France\",\"cued_at\":\"2021-01-22 22:35:48\",\"duration\":157,\"sent_to_autodj\":null},{\"song\":\"Sergio - Lately\",\"cued_at\":\"2021-01-22 22:32:57\",\"duration\":178,\"sent_to_autodj\":null},{\"song\":\"Macklemore - Corner Store (feat. Dave B & Travis Thompson)\",\"cued_at\":\"2021-01-22 22:28:31\",\"duration\":266,\"sent_to_autodj\":null}]} {\"station\":{\"id\":1,\"name\":\"Radio Club-BG\"}}\n"},{"message":"Playlist has no schedule items; skipping schedule time check.","context":[],"level":100,"level_name":"DEBUG","channel":"AzuraCast","datetime":"2021-01-22T21:52:41.146569+00:00","extra":{"playlist":{"id":20,"name":"The Voice"},"station":{"id":1,"name":"Radio Club-BG"}},"formatted":"[2021-01-22T21:52:41.146569+00:00] AzuraCast.DEBUG: Playlist has no schedule items; skipping schedule time check. [] {\"playlist\":{\"id\":20,\"name\":\"The Voice\"},\"station\":{\"id\":1,\"name\":\"Radio Club-BG\"}}\n"},{"message":"1 playable playlist(s) of type \"default_unscheduled\" found.","context":{"playlists":[{"id":20,"name":"The Voice","weight":5}]},"level":200,"level_name":"INFO","channel":"AzuraCast","datetime":"2021-01-22T21:52:41.146762+00:00","extra":{"station":{"id":1,"name":"Radio Club-BG"}},"formatted":"[2021-01-22T21:52:41.146762+00:00] AzuraCast.INFO: 1 playable playlist(s) of type \"default_unscheduled\" found. {\"playlists\":[{\"id\":20,\"name\":\"The Voice\",\"weight\":5}]} {\"station\":{\"id\":1,\"name\":\"Radio Club-BG\"}}\n"},{"message":"Found track that avoids duplicate title and artist.","context":{"media_id":21366},"level":200,"level_name":"INFO","channel":"AzuraCast","datetime":"2021-01-22T21:52:41.156129+00:00","extra":{"station":{"id":1,"name":"Radio Club-BG"}},"formatted":"[2021-01-22T21:52:41.156129+00:00] AzuraCast.INFO: Found track that avoids duplicate title and artist. {\"media_id\":21366} {\"station\":{\"id\":1,\"name\":\"Radio Club-BG\"}}\n"},{"message":"Playable track found and registered.","context":{"next_song":"StationMedia 89d15dad7d95aa53eaf99c36: Stitches - Spaz Out"},"level":200,"level_name":"INFO","channel":"AzuraCast","datetime":"2021-01-22T21:53:59.497134+00:00","extra":{"station":{"id":1,"name":"Radio Club-BG"}},"formatted":"[2021-01-22T21:53:59.497134+00:00] AzuraCast.INFO: Playable track found and registered. {\"next_song\":\"StationMedia 89d15dad7d95aa53eaf99c36: Stitches - Spaz Out\"} {\"station\":{\"id\":1,\"name\":\"Radio Club-BG\"}}\n"}]
```

**Comment by NicoxDJ** [comment] 2021-02-01 20:28
@SlvrEagle23 @Vaalyn I start digging in the code.
Something is not sending the right id to the API controller. This is causing not getting the unique_id (for the artwork), if this is missing, it can't build the image url. I build manually artwork url from song, that the artwork doesn't appear. So i find the song in the database, and manually get the unique_id. Than i build the link, and it shows the artwork. So something doesn't send the ID. Like i said it in few posts above. It's not storing it in the song_history too: https://github.com/AzuraCast/AzuraCast/issues/3673#issuecomment-760475913

**Comment by NicoxDJ** [comment] 2021-02-01 21:48
@SlvrEagle23 @Vaalyn HINT:
Something is wrong with NowPlayingCurrentSong
That's as far as i succeed to debug. I don't know this framework, but i can't find nothing.
For example i can't find the model where is adding the artwork entries into the object.
Here is example with song that is displaying the proper artwork, and this that doesn't get the right object of the file, and information like `duration`, `genre`, `album` and etc is even missing:
![](https://i.imgur.com/CXSrVbR.png)
![](https://i.imgur.com/QpUE95b.png)

**Comment by NicoxDJ** [comment] 2021-02-01 22:37
UPDATE: While debugging, maybe the queue builder pick some songs. I had about 10 songs in a row with artwork, and then again songs without artwork. I was just thinking that somehow i fix it while updating files, but nope...

**Comment by SlvrEagle23** [comment] 2021-02-01 22:49
@NicoxDJ The problem is very likely that we don't recognize the currently playing song as a `StationMedia` record and instead just register it as a regular `Song` record without the typical rich metadata that accompanies a `StationMedia` record type.

This is a frequent problem because occasionally we don't get the necessary "feedback" response from Liquidsoap, or Icecast's metadata is just slightly different than what we sent it, making it impossible for us to make an exact match to a track we cued up for playback.

Typical causes of the problem are rebooting the radio service and skipping tracks, both of which cause Liquidsoap to "jump" off the AzuraCast AutoDJ for a single track, playing through its own fallback playlists instead.

We continue to look into ways to resolve this, but haven't found a reliable way of allowing Liquidsoap to skip tracks or restart gracefully while allowing it a few seconds of delay for the first queue response to come through.

**Comment by eranwo** [comment] 2021-03-04 08:17
@SlvrEagle23 Thanks for the in-depth explanation.
I understand that, but at the same time I think it is necessary to invest the most effort  fix this problem, 
which is actually part of the core of the system (And worked without special problems until the beginning of the current year). 
Inaccuracies in reporting the song names or duration cause severe damage to system reliability.

Therefore, in my opinion, it may be necessary to suspend developments of new features and concentrate on restoring the good stability to the system and features at the basic level.

**Comment by SlvrEagle23** [comment] 2021-03-04 11:11
@eranwo Our development process is always a balancing act between adding new features and fixing bugs that get reported. There is no reason for us to suspend all new feature development for bug fixes, when we already devote a fair amount of time to bug fixes.

Many issues (including this one) are long-established and haven't just popped up recently, and we've explained what causes them multiple times. Devoting more time to fixing this issue solely from our side wouldn't help much, since we're dependent on a lot of upstream software to accomplish this, and that software isn't likely to change its fundamental structure any time soon.

**Comment by SlvrEagle23** [comment] 2021-03-07 01:51
I'm closing this issue as it has departed quite a lot from the original issue that was reported, which has indeed been resolved in our latest bug fixes.

**Closed by SlvrEagle23** 2021-03-07 01:51 UTC
Labels: enhancement
