### ISSUE TITLE
Uninstall script and health script

### ISSUE THREAD

**Issue by athensguy** [AzuraCast/AzuraCast#154] opened 2017-06-06 19:05 UTC
It'd be good to have uninstall script to remove AzuraCast services instead of doing that manually (in case user wanted to re-install clean version)

Also should have like health script to check if system is healthy and all requirements for permission and services are there

**Comment by SlvrEagle23** [comment] 2017-06-12 00:39
@athensguy Thoughts on both of these items:

- An uninstall script could be helpful (especially for the purpose you mentioned, fresh-reinstalling AzuraCast on the same box), but the question is how much to actually uninstall. A script that wipes the installed Ubuntu packages would be quick and easy, but it wouldn't necessarily remove the data stored in various places.

- I like to think that the update script doubles as a system health script in that it sets all the appropriate permissions, ensures the caches are flushed and restarts the appropriate services. In the worst-case scenario, you can also run `./update.sh --full` to force every aspect of the update process to run, which certainly doubles as a health check.

**Comment by SlvrEagle23** [comment] 2017-09-25 07:39
I'm closing this issue, as the progression of the application is showing a steady push toward containerization, for both speed and compatibility reasons. By design, the containers are portable and only save a small portion of their data onto the disk. The Docker uninstall script removes these files already, and for system health, there are a large number of monitoring tools available for Docker itself that can be attached to it.

**Closed by SlvrEagle23** 2017-09-25 07:39 UTC
Labels: enhancement

**Comment by SlvrEagle23** [comment] 2018-02-19 23:40
@athensguy Update on this issue: an uninstaller for the traditional installation is now available in the codebase. It was created as part of the "Traditional to Docker" migrator tool (see #423) but can be run independently to remove the full stack of software associated with AzuraCast.

**Comment by ZandercraftGames** [comment] 2020-06-18 20:04
Dang... That uninstall script is very destructive to any system running more than just azuracast.

**Comment by SlvrEagle23** [comment] 2020-06-18 22:37
@ZandercraftGames Our Ansible installation, much moreso than our recommended Docker installation, depends on a "clean" server to install its necessary package dependencies, which are far-reaching; uninstalling those packages can also likewise be destructive if you have other things depending on the same services AzuraCast installed.

This is one of many reasons we prefer the compartmentalized approach Docker takes.
