### ISSUE TITLE
lock_ratelimit.login error

### ISSUE THREAD

**Issue by rgriep** [AzuraCast/AzuraCast#6455] opened 2023-07-27 07:25 UTC
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #203ca2c (2023-07-25 22:05)

### What happened?

Hi,

I got the next error and wasn't able to login.

500
Failed to acquire the "lock_ratelimit.login-87_209_223_46" lock.
vendor/symfony/lock/Lock.php : L123

After a total restart, it works again. What can be the reason of this error? And how to solve it without a restart of the system.

Kind regards,
Robert

**Comment by BusterNeece** [comment] 2023-08-01 10:06
Duplicate of #6179.

**Closed by BusterNeece** 2023-08-01 10:06 UTC
Labels: needs investigation
