### ISSUE TITLE
AzuraCast Crash

### ISSUE THREAD

**Issue by radiolize** [AzuraCast/AzuraCast#1805] opened 2019-08-01 08:03 UTC
Docker, Ubuntu

Hey guys. Looks like happened a crash because of memory but it's weird as I have 20 GB of ram and my ssd's still had more than 1 TB space. Also there are never more than 5-10 listener total of my stations. There was a 502 bad gateway error displaying on my AzuraCast address and I have made an AzuraCast update again and it looks normal now. (I were already updated it yesterday too) it happened the first time to me. Here some logs.

**Liquidsoap log from one of my stations:**

> 2019/08/01 04:23:30 [clock.wallclock_main:2] Source radio_antalya_local_2 failed while streaming: No space left on device in fork()!
2019/08/01 04:23:30 [clock.wallclock_main:3] Raised by primitive operation at file "unix.ml", line 938, characters 9-15
2019/08/01 04:23:30 [clock.wallclock_main:3] Called from file "unix.ml", line 1012, characters 6-115
2019/08/01 04:23:30 [clock.wallclock_main:3] Re-raised at file "unix.ml", line 1018, characters 6-13
2019/08/01 04:23:30 [clock.wallclock_main:3] Called from file "lang/lang_builtins.ml", line 1482, characters 48-78
2019/08/01 04:23:30 [clock.wallclock_main:3] Called from file "lang/lang_builtins.ml", line 1542, characters 82-96
2019/08/01 04:23:30 [clock.wallclock_main:3] Called from file "lang/lang_values.ml", line 971, characters 14-20
2019/08/01 04:23:30 [clock.wallclock_main:3] Called from file "lang/lang_values.ml", line 922, characters 39-50
2019/08/01 04:23:30 [clock.wallclock_main:3] Called from file "list.ml", line 67, characters 20-23
2019/08/01 04:23:30 [clock.wallclock_main:3] Called from file "lang/lang_values.ml", line 922, characters 12-54
2019/08/01 04:23:30 [clock.wallclock_main:3] Called from file "lang/lang_values.ml", line 922, characters 39-50
2019/08/01 04:23:30 [clock.wallclock_main:3] Called from file "list.ml", line 67, characters 20-23
2019/08/01 04:23:30 [clock.wallclock_main:3] Called from file "lang/lang_values.ml", line 922, characters 12-54
2019/08/01 04:23:30 [clock.wallclock_main:3] Called from file "lang/lang_values.ml", line 971, characters 14-20
2019/08/01 04:23:30 [clock.wallclock_main:3] Called from file "lang/lang_values.ml", line 922, characters 39-50
2019/08/01 04:23:30 [clock.wallclock_main:3] Called from file "list.ml", line 67, characters 20-23
2019/08/01 04:23:30 [clock.wallclock_main:3] Called from file "list.ml", line 67, characters 32-39
2019/08/01 04:23:30 [clock.wallclock_main:3] Called from file "lang/lang_values.ml", line 922, characters 12-54
2019/08/01 04:23:30 [clock.wallclock_main:3] Called from file "lang/lang_values.ml", line 971, characters 14-20
2019/08/01 04:23:30 [clock.wallclock_main:3] Called from file "lang/lang_values.ml", line 922, characters 39-50
2019/08/01 04:23:30 [clock.wallclock_main:3] Called from file "list.ml", line 67, characters 20-23
2019/08/01 04:23:30 [clock.wallclock_main:3] Called from file "lang/lang_values.ml", line 922, characters 12-54
2019/08/01 04:23:30 [clock.wallclock_main:3] Called from file "lang/lang_values.ml", line 894, characters 18-29
2019/08/01 04:23:30 [clock.wallclock_main:3] Called from file "lang/lang_values.ml", line 971, characters 14-20
2019/08/01 04:23:30 [clock.wallclock_main:3] Called from file "tools/tutils.ml", line 85, characters 14-18
2019/08/01 04:23:30 [clock.wallclock_main:3] Re-raised at file "tools/tutils.ml", line 85, characters 48-55
2019/08/01 04:23:30 [clock.wallclock_main:3] Called from file "lang/lang_values.ml", line 971, characters 14-20
2019/08/01 04:23:30 [clock.wallclock_main:3] Called from file "lang/lang_values.ml", line 971, characters 14-20
2019/08/01 04:23:30 [clock.wallclock_main:3] Called from file "tools/tutils.ml", line 85, characters 14-18
2019/08/01 04:23:30 [clock.wallclock_main:3] Re-raised at file "tools/tutils.ml", line 85, characters 48-55
2019/08/01 04:23:30 [clock.wallclock_main:3] Called from file "operators/on_metadata.ml", line 40, characters 20-70
2019/08/01 04:23:30 [clock.wallclock_main:3] Called from file "list.ml", line 85, characters 12-15
2019/08/01 04:23:30 [clock.wallclock_main:3] Called from file "source.ml", line 535, characters 12-26
2019/08/01 04:23:30 [clock.wallclock_main:3] Called from file "outputs/output.ml", line 174, characters 8-18
2019/08/01 04:23:30 [clock.wallclock_main:3] Called from file "clock.ml", line 160, characters 17-25
2019/08/01 04:23:30 [radio_antalya_local_2:3] Closing connection...
2019/08/01 04:23:30 [main:3] Shutdown started!
2019/08/01 04:23:30 [main:3] Waiting for threads to terminate...
2019/08/01 04:23:30 [threads:3] Shuting down thread wallclock_main
2019/08/01 04:23:30 [radio_antalya_local_1:3] Closing connection...
2019/08/01 04:23:30 [playlist_turkce_anons:3] Finished with "/var/azuracast/stations/radio_antalya/media/ANONSLAR/turkce_en_iyi_radio.mp4".
2019/08/01 04:23:30 [playlist_default_playlist:3] Finished with "/var/azuracast/stations/radio_antalya/media/New Wave Slow English/chris_cohen_-_caller_no.99.mp3".
2019/08/01 04:23:30 [radio_antalya_next_song:3] Finished with "/var/azuracast/stations/radio_antalya/media/New Wave Slow English/tops_-_evening.mp3".
2019/08/01 04:23:30 [clock.wallclock_main:3] Streaming loop stopped.
2019/08/01 04:23:30 [threads:3] Thread "wallclock_main" terminated (0 remaining).
2019/08/01 04:23:30 [main:3] Threads terminated.
2019/08/01 04:23:30 [threads:3] Shutting down scheduler...
2019/08/01 04:23:30 [threads:3] Scheduler shut down.
2019/08/01 04:23:30 [threads:3] Thread "non-blocking queue #1" terminated.
2019/08/01 04:23:30 [threads:3] Shutting down queues...
2019/08/01 04:23:30 [threads:3] Thread "non-blocking queue #2" terminated.
2019/08/01 04:23:30 [threads:3] Thread "generic queue #2" terminated.
2019/08/01 04:23:30 [threads:3] Thread "generic queue #1" terminated.
2019/08/01 04:23:30 [threads:3] Queues shut down
2019/08/01 04:23:30 [server:3] Closing socket.
2019/08/01 04:23:30 [main:3] Cleaning downloaded files...
2019/08/01 04:23:30 [main:3] Freeing memory...
2019/08/01 04:23:30 >>> LOG END
2019/08/01 10:34:14 >>> LOG START

**Docker log:**

> web_1       | 2019/08/01 07:37:03 Waiting for: tcp://mariadb:3306
web_1       | 2019/08/01 07:37:03 Waiting for: tcp://influxdb:8086
web_1       | 2019/08/01 07:37:03 Connected to tcp://influxdb:8086
web_1       | 2019/08/01 07:37:03 Connected to tcp://mariadb:3306
web_1       | *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
web_1       | *** Running /etc/my_init.d/10_syslog-ng.init...
web_1       | Aug  1 07:37:03 8dcddb858a97 syslog-ng[25]: syslog-ng starting up; version='3.13.2'
web_1       | *** Running /etc/my_init.d/php.sh...
web_1       | 2019/08/01 07:37:04 Command finished successfully.
web_1       | *** Running /etc/my_init.d/php_workers.sh...
web_1       | Adding 1 additional workers
web_1       | Adding worker 1...
web_1       | Done
web_1       | *** Running /etc/my_init.d/touch_cron.sh...
web_1       | *** Booting runit daemon...
web_1       | *** Runit started as PID 48
web_1       | Aug  1 07:37:05 8dcddb858a97 cron[55]: (CRON) INFO (pidfile fd = 3)
web_1       | Aug  1 07:37:05 8dcddb858a97 cron[55]: (CRON) INFO (Running @reboot jobs)
web_1       | [2019-08-01 07:37:05] AzuraCast.INFO: Running message queue processor for 300 seconds. [] []
web_1       | [2019-08-01 07:37:05] AzuraCast.INFO: Running message queue processor for 300 seconds. [] []
web_1       | Aug  1 07:37:06 8dcddb858a97 php-fpm[62]: [NOTICE] fpm is running, pid 62
web_1       | Aug  1 07:37:06 8dcddb858a97 php-fpm[62]: [NOTICE] ready to handle connections
web_1       | Aug  1 07:37:06 8dcddb858a97 php-fpm[62]: [NOTICE] systemd monitor interval set to 10000ms
**web_1       | Aug  1 07:37:08 8dcddb858a97 php-fpm[62]: [WARNING] [pool www] server reached max_children setting (3), consider raising it**
web_1       | Aug  1 07:37:17 8dcddb858a97 php-fpm[62]: [WARNING] [pool www] child 92 said into stderr: "[2019-08-01 07:37:17] AzuraCast.INFO: New message of type App\Message\UpdateNowPlayingMessage added to queue. [] []"
web_1       | [2019-08-01 07:37:19] AzuraCast.INFO: Handling message of type App\Message\UpdateNowPlayingMessage. [] []
web_1       | Aug  1 07:37:24 8dcddb858a97 php-fpm[62]: [WARNING] [pool www] child 94 said into stderr: "[2019-08-01 07:37:24] AzuraCast.INFO: New message of type App\Message\UpdateNowPlayingMessage added to queue. [] []"

**Comment by SC2Mitch** [comment] 2019-08-01 14:11
I had the same issue at around 9:30 this morning, (UTC)
Traced it back to LiquidSoap crashing as well and it brought down the whole azura host for some reason, resulting in bad gateway errors
```
2019/08/01 09:25:28 [threads:2] Queue generic queue #2 crashed with exception No space left on device in fork()
Raised by primitive operation at file "unix.ml", line 938, characters 9-15
Called from file "unix.ml", line 1012, characters 6-115
Re-raised at file "unix.ml", line 1018, characters 6-13
Called from file "lang/lang_builtins.ml", line 1482, characters 48-78
Called from file "lang/lang_builtins.ml", line 1542, characters 82-96
Called from file "lang/lang_values.ml", line 971, characters 14-20
Called from file "lang/lang_values.ml", line 922, characters 39-50
Called from file "list.ml", line 67, characters 20-23
Called from file "lang/lang_values.ml", line 922, characters 12-54
Called from file "lang/lang_values.ml", line 922, characters 39-50
Called from file "list.ml", line 67, characters 20-23
Called from file "lang/lang_values.ml", line 922, characters 12-54
Called from file "lang/lang_values.ml", line 971, characters 14-20
Called from file "lang/lang_values.ml", line 922, characters 39-50
Called from file "list.ml", line 67, characters 20-23
Called from file "list.ml", line 67, characters 32-39
Called from file "lang/lang_values.ml", line 922, characters 12-54
Called from file "lang/lang_values.ml", line 971, characters 14-20
Called from file "lang/lang_values.ml", line 922, characters 39-50
Called from file "list.ml", line 67, characters 20-23
Called from file "lang/lang_values.ml", line 922, characters 12-54
Called from file "lang/lang_values.ml", line 894, characters 18-29
Called from file "lang/lang_values.ml", line 971, characters 14-20
Called from file "tools/tutils.ml", line 85, characters 14-18
Re-raised at file "tools/tutils.ml", line 85, characters 48-55
Called from file "sources/req_simple.ml", line 103, characters 32-52
Re-raised at file "sources/req_simple.ml", line 109, characters 10-17
Called from file "sources/request_source.ml", line 351, characters 10-31
Called from file "sources/request_source.ml", line 339, characters 13-26
Called from file "duppy.ml", line 394, characters 20-24
Called from file "duppy.ml", line 151, characters 61-77
Called from file "duppy.ml", line 279, characters 14-23
Called from file "duppy.ml", line 313, characters 7-24
Called from file "duppy.ml", line 350, characters 9-15
Called from file "duppy.ml", line 356, characters 5-9
Called from file "tools/tutils.ml", line 216, characters 19-55

2019/08/01 09:25:28 [threads:1] PANIC: Liquidsoap has crashed, exiting.,
```
I'm trying to trace the Docker logs currently to see what happened at that time as well.

**Comment by SlvrEagle23** [comment] 2019-08-03 03:57
We've discussed this issue via our Mattermost channel, found the cause and pushed an update resolving it.

**Closed by SlvrEagle23** 2019-08-03 03:57 UTC
Labels: error
