### ISSUE TITLE
shoutcast

### ISSUE THREAD

**Issue by lovefmhits** [AzuraCast/AzuraCast#3469] opened 2020-11-26 19:53 UTC
**Using Docker installation method**

**AzuraCast version**

**Host Operating System**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by lovefmhits** [comment] 2020-11-26 19:53
bonjour  je vien  install  shoutcast  dans azurcast  mais  j ai un message 
502 Bad Gateway
nginx j ai redemarre  le server  mais j ai  toujour  le meme message 
je ne vois pas crois faire  merci  de  pour tout info  sur  install

**Comment by SpeedyCharly** [comment] 2020-12-01 06:54
Premièrement, ce forum est anglais, tu ne verra donc pas beaucoup d'action sur une question dans une autre langue.  Permet moi de traduire ton message.
TRANSLATED question from **lovefmhits**;
Hello, I have just installed Shoutcast in Azuracast, but it always fails on the same error message;
**502 Bad Gateway
nginx**
Tried restarting the server, but to no avail - I don't see what else I can try.  Thanks for any info of Shoutcast install and insights on what I'm doing wrong here... Thanks in advance

**Comment by lovefmhits** [comment] 2020-12-01 15:54
Hello
Speedy Charly
I just read you so I didn't see it for the language
So here is the problem is installed from shoutcast I let it install but inpossible to make it work I thank you for your answer

**Comment by lovefmhits** [comment] 2020-12-01 18:11
Hello
Speedy Charly
I just read you so I didn't see it for the language
So here is the problem is installed from shoutcast I let it install but
inpossible to make it work I thank you for your answer

Le mar. 1 déc. 2020 à 07:54, Speedy Charly <notifications@github.com> a
écrit :

**Comment by Vaalyn** [comment] 2020-12-11 20:55
Closing as I'm unable to reproduce this.

I'm able to successfully install the latest shoutcast DNAS version as well as create a station using shoutcast. It's also playing correctly when adding music to it.

**Closed by Vaalyn** 2020-12-11 20:55 UTC

**Comment by SpeedyCharly** [comment] 2020-12-12 02:27
Vaalyn;
That response on your part is anything but helpful; basically shutting down lovefmhits without addressing his problem in any useful manner.... The least you could have done is ask him to describe what he did in detail to try and pinpoint the source of his problem... never a good policy to dismiss clients out of hand; word gets around!

**Comment by Vaalyn** [comment] 2020-12-12 02:47
@SpeedyCharly I'm sorry if my answer is coming off as being dismissive but this issue was created in french which I can't speak/read (yes, you translated it but this project is only communicating in english) and the poster has completely ignored the issue template that we supply users with in order for them to give us meaningful information about their systems and the issue they are having so we are even able to diagnose anything.

If a user is not even putting any effort into creating an issue I'm not going to put more time into pulling that information from those users. I've already tested installing Shoutcast, creating a station with that set as the Station Frontend, adding music to it, adding that to a playlist and listening to the stream. All without any issues so I'm unable to reproduce the problem that was stated as being `I have just installed Shoutcast in Azuracast, but it always fails on the same error message; 502 Bad Gateway` and `the problem is installed from shoutcast I let it install but inpossible to make it work`.

> never a good policy to dismiss clients out of hand; word gets around!
The users of a free open source software are **not** clients and I'm not getting paid to provide support so the minimum I expect from users who want help with a problem is that they put at least **some** effort into describing their issues and providing basic information about their installation.

To you @SpeedyCharly I'd recommend to not hand out "threats" of "word gets around!" as that is neither respectful nor constructive in any way and against our Code of Conduct.

If this is an issue on an installation that you are personally involved with then instead of berating me you could put in the effort to provide the information that we request from issue creators by yourself.

**Comment by SpeedyCharly** [comment] 2020-12-12 02:58
I am appalled that you would be taking the high road on this; 
• I am in no way involved with the problem installation; mine is exactly the same and working fine; i only tried to help by translating for the author
• My 'word gets around' wasn't a veiled threat, but a simple statement of fact; you may not consider people who don't pay as clients, but they are just that nonetheless, and if you want you product to rise to the top of the heap and survive the competition, you must go all the way to help as much as possible....  just good business!!!
• You as a tech adviser will get the respect you deserve, and that is mostly defined by the way you deal with the people you interact with....  Totally unimpressed at this juncture, sorry to say

**Comment by SlvrEagle23** [comment] 2020-12-12 03:19
@SpeedyCharly There's no need to continue this discussion further, as I think you fundamentally misunderstand the role of open-source software maintainers in the support ecosystem.

We are not a company trying to compete for market share; we're volunteers contributing our work to the public interest so that everyone can use it. We contribute an _extensive_ amount of work to the public good, and because without that contribution there simply _wouldn't be_ an open-source software option in this category, there is no expectation that we go out of our way to provide support the way a paid enterprise would.

I don't say this just to avoid providing support; we actually _do_ provide a huge deal of support via both here and our Discord communities. This support, however, is something we do as a token of generosity to the community, and not something we are obliged to provide; as our software's license (and effectively any open-source software license) says, our software is provided as-is with no warranty. One of the guiding principles of open-source is that if you identify a problem, you are entitled to fix it yourself (as you have access to the code), and can then contribute those fixes back to the project itself if you want.

What @Vaalyn has said in closing the original issue is entirely correct: the issue doesn't meet our baseline expectations. Since we field support questions from tens of thousands of stations, we have to establish clear baselines to make our support process simpler, and those baselines include both following our issue template and communicating in English, as this is the language our support is provided in.

There are many, many people who view our work with AzuraCast as an obligation that is owed to them because they choose to use software that we make. While we are always happy to see more users using our software, we also likewise stand up for the principles that the work of any open-source developer is _always_ good enough just by virtue of existing at all. We aren't motivated by profit or competition or other things that enterprise operations are, and that's part of why we enjoy this work in the first place.

Given the simple resolution to this issue is to create a new GitHub issue in English that follows our predefined issue template, there is no cause for concern or action here.

**Comment by SpeedyCharly** [comment] 2020-12-12 03:27
The original poster is obviously a newbie and was probably unaware of protocol.  Vaalin might have been better to politely bring him up to speed before doing something that remains, IMHO, totally unhelpful and dismissive...

**Comment by SlvrEagle23** [comment] 2020-12-12 03:41
@SpeedyCharly Perhaps, but nothing that was said was disrespectful. It's correct that we can't reproduce the error with the information we're given, so we have no real alternative to close the issue until and unless we're provided with more information that can work with.

If the issue persists, the original requester can just make a new issue (making sure to follow the template). We have many issues that come through our systems on a daily basis and we have to process them in a manner that works for us.

**Comment by lovefmhits** [comment] 2020-12-12 03:57
hello I just saw the messages on the question that I asked to install shoudcast and yes I did not find the souics but hey I will search well as it should I is very good that the software is open souce but it was a question because I am new and always difficult for a little novelty found immediately
thank you again
