### ISSUE TITLE
error sending emails

### ISSUE THREAD

**Issue by nunotfc** [AzuraCast/AzuraCast#4750] opened 2021-10-31 16:31 UTC
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

0be5c9b (2021-10-31 1:00) • Docker • PHP 8.0

### What happened?

i'm atempting to send e-mails, they not come. and i get this error:
[2021-10-31T16:26:30.821010+00:00] AzuraCast.ERROR: Handling "Symfony\Component\Mailer\Messenger\SendEmailMessage" failed: Connection could not be established with host "ssl://smtp.gmail.com:587": stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages: error:1408F10B:SSL routines:ssl3_get_record:wrong version number {"file":"/var/azuracast/www/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php","line":80,"code":0} []

**Comment by Vaalyn** [comment] 2021-10-31 19:36
Duplicate of #4682

**Closed by Vaalyn** 2021-10-31 19:36 UTC
Labels: duplicate
