### ISSUE TITLE
Music name does not appear

### ISSUE THREAD

**Issue by jonikane** [AzuraCast/AzuraCast#393] opened 2018-01-26 13:27 UTC
Hello,

When I have the server configured on Icecast, and I'm going to broadcast with Shoutcast v1 encoder with pass style: user: pass, the name of the song in the broadcast program appears, it does not appear in the air on Icecast, but before it appeared.

Am I setting something wrong?

Thank you

**Comment by FrBillyD** [comment] 2018-01-26 14:28
Hello ! Same problem for me since long time. But, is not a problem for me that's why I did not talk about it. I thought it came from me... Apparently not.

Thanks ! 😸

**Comment by SlvrEagle23** [comment] 2018-02-01 17:37
Closing as duplicate of #310

**Closed by SlvrEagle23** 2018-02-01 17:37 UTC
