### ISSUE TITLE
Schedules won't start directly on time, how to do????

### ISSUE THREAD

**Issue by master-magic** [AzuraCast/AzuraCast#2746] opened 2020-04-25 20:18 UTC
i have now on a stream some file's of more than a hour (dj mixes) and I put them in separate folders with the dj name and also in schedules the dj mixes in separate maps so it works very good, but I get the problem when there is playing a file from 20 hours til 21 hours and it is more than an hour of music, that file still plays after 21 hours when the next one must start and is been link on 21 hours to start, but it does nothing, there is a songs that plays after that mix that is not in the schedule that time.
how to fix this that every file start on the good hour and work like I want it ????

maybe a little difficult for some people, but I want to make it perfectly like I will.

**Comment by cmarina** [comment] 2020-04-25 22:27
I’ve got the same issue

**Comment by master-magic** [comment] 2020-04-25 22:30
@cmarina nice to know I'm not alone with that problem.....

**Comment by ismaelazanza** [comment] 2020-04-26 00:28
Also the same problem, the tracks do not play at the indicated time, sometimes it does it with about 20 minutes later, and something strange is that when the programmed program ends it repeats again.

**Comment by master-magic** [comment] 2020-04-26 01:43
i have for the time being put the tracks all in one map and one playlist that must play from that hour till that hour on the day I pick, and that works, 
I think it's when there are to much schedules the system don't now when to start and take the normal playlist.
that is what I now seen with tests.
maybe can someone tell the good way so this works like we want with separate schedules???
it's a very good system, but the schedules are not yet ok or we do something wrong ????

**Comment by bebjakub** [comment] 2020-04-28 17:33
@SlvrEagle23 the same issue here. I updated AzuraCast today on the production, unfortunately. The schedule is crazy. Check it out, pls.

**Comment by SlvrEagle23** [comment] 2020-04-28 21:20
@bebjakub "The schedule is crazy" means absolutely nothing to us from a development, diagnostic or technical standpoint.

This issue is likely a duplicate of our "super-issue" for scheduling, #2631.

For years now, I've been the only person to make any changes to our AutoDJ scheduler, and I've never had any assistance or pull requests on this specific code, but we have about 20 people complaining that "something" is wrong with it, though most of those issues lack any information or debugging or logs or anything that I could use to improve it.

Needless to say, the scheduler and the problems associated with it have become a thorn in my side that I absolutely no longer want to deal with. Clearly something is going wrong that is a bit beyond my capabilities as a singular developer, but I am not able to fix it any easier with these kinds of issues.

**Closed by SlvrEagle23** 2020-04-28 21:20 UTC
