### ISSUE TITLE
History incorrectly shows track being played twice in a row

### ISSUE THREAD

**Issue by pacija** [AzuraCast/AzuraCast#5747] opened 2022-09-21 13:40 UTC
### Installation Method

Ansible Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #7719208 (2022-09-07 0:52)

### What happened?

Hi,

I have two playlists - one with music (general rotation, weight 3), the other one with jingles (once per 3 songs). Jingles are generally short (7s shortest, 34s longest). Crossfading is set to 6s.

Everything works great, except for the fact that song history incorrectly shows the track being played before the jingle as being played again after the jingle, even though this is not true. Not every time though, but quite frequently.

![twice](https://user-images.githubusercontent.com/14246467/191516339-238f0f10-14c7-4d3b-bf79-7a0f174f2334.png)

On above image we see correct fact that "Alan Cook - Running Away (Remix)" from "Playlist: Standard" started at 2:47 PM. The track is 5:16 long, so we see another correct fact that "The Legend Of Kaspar Hauser - Do The Headbanger" from "Playlist: Jingles" started some 5 minutes later, at 2:52 PM.

But then we see incorrect fact that "Alan Cook - Running Away (Remix)" from "Playlist: Standard" started again at 2:52 PM, and right after that, the correct fact that "Beau Sexon - Don't Tell Me No Lies (12" Version)" started also at the same time at 2:52 PM.

Here's another example with another jingle:

![another](https://user-images.githubusercontent.com/14246467/191518217-f38849ef-7e10-4b78-a544-2f23318efc2c.png)

Finally, here's situation where it does not happen:

![correct](https://user-images.githubusercontent.com/14246467/191518800-782fe095-c220-413f-88b5-95c9ea50502f.png)

Thank you in advance,

**Comment by pawelzet** [comment] 2022-09-27 12:31
I have the same issue on my configuration with docker after upgrading to 0.17.3. In fact these songs were played just once. 
![Screenshot 2022-09-27 at 14 29 47](https://user-images.githubusercontent.com/46452256/192526791-046ce0c8-1da0-4d12-8ef5-dfbbf71c597b.png)

**Comment by mkbwr** [comment] 2022-10-26 11:11
This is still an issue (Rolling Release 5c3241f on Docker).

Jingle mode is active, selecting a jingle but in fact when the jingle plays the previous song title is being duplicated.

**Comment by BusterNeece** [comment] 2022-10-26 11:16
Closing as duplicate of #5589 -- Follow that issue and the associated Liquidsoap issue for info.

**Closed by BusterNeece** 2022-10-26 11:16 UTC
Labels: needs investigation
