### ISSUE TITLE
Can't Switch Themes

### ISSUE THREAD

**Issue by ArranLH** [AzuraCast/AzuraCast#1856] opened 2019-08-14 11:14 UTC
**Using Docker installation method**

Yes
**Host Operating System**

Ubuntu 18,04
**Describe the bug**

Unable to Switch Theme. 

**To Reproduce**

https://i.imgur.com/nkwvrSo.png
**Expected behavior**

White screen with 302 status
https://i.imgur.com/WJoztpO.png

**Relevant Logs**

Nothing relevant in the logs
**Screenshots**

**Device(s):**
Windows 10 
Chrome Browser

**Additional context**
v0.9.6, #90d0042 (2019-08-12 19:51)

**Comment by SC2Mitch** [comment] 2019-08-14 14:13
Weird work around, if you click on the 'Change Theme' and go back to your radio, it'd of switched the themes.

**Comment by ArranLH** [comment] 2019-08-14 21:19
That's very strange- when I submitted the report it stayed on the light theme.

**Comment by afonsosantos** [comment] 2019-08-14 23:44
@ArranLH Did you try to change the theme via `My Account - Change Profile - Site Theme`?

**Comment by ArranLH** [comment] 2019-08-15 00:08
Hi there!
Yeah that's just worked without flaw. It still doesn't redirect when you click the option in the menu though. This could possibly be a client issue?
https://i.imgur.com/aTy063P.png

**Comment by afonsosantos** [comment] 2019-08-15 00:09
Humm, i'm not sure. Do you have any extension in the browser that may be blocking that? Do you see any errors in the console?

**Comment by SlvrEagle23** [comment] 2019-08-15 00:33
Should be fixed now. Was a small error caused by our recent framework upgrade.

**Closed by SlvrEagle23** 2019-08-15 00:33 UTC
Labels: bug
