### ISSUE TITLE
Shoutcast broadcast stops when AutoDJ is stopped

### ISSUE THREAD

**Issue by ogrenci01** [AzuraCast/AzuraCast#3383] opened 2020-11-07 07:16 UTC
**Using Docker installation method**
Ansible

**AzuraCast version**
#deb5ecd

**Host Operating System**
Ubuntu 18.04. LTS

**Describe the bug**
Shoutcast broadcast stops when AutoDJ is stopped. Shoutcast starts normally when Auto DJ restarts. This problem occurs at any station.

**To Reproduce**
1. Go to 'Station Profil'
2. Scroll down to 'AutoDJ Service'
3. Click on 'Stop'
![image1](https://user-images.githubusercontent.com/24523085/98434543-b0bf7580-20e1-11eb-9304-6efd28eaa605.jpg)

**Expected behavior**
Shoutcast broadcast stops when AutoDJ is stopped. Shoutcast starts normally when Auto DJ restarts. This problem occurs at any station.

**Relevant Logs**
I don't know which records to add.

**Device(s):**
 - Device: PC
 - OS: Windows 10
 - Browser: Chrome
 - Version: Latest

**Additional context**
I know there is no official support for Ansible. A similar issue may apply to Docker. Thanks for everything.

**Comment by h4de5** [comment] 2020-11-09 09:32
I think this is expected behaviour? without the autodj to provide which files to play, the broadcasting service does not have anything to stream.

**Comment by Vaalyn** [comment] 2020-11-10 15:02
I've looked into this and found the source of the issue.

In general this is luckily not really stopping the SHOUTcast service but just showing it as not running when the AutoDJ is stopped. This is due to a small bug in the API for the station profile that accesses the backend (AutoDJ) status for both the backend and frontend (SHOUTcast in this case).

I'll prepare a fix for this.

**Comment by Vaalyn** [comment] 2020-11-10 16:52
Should be fixed as per my PR #3394

**Closed by Vaalyn** 2020-11-10 16:52 UTC
Labels: bug
