### ISSUE TITLE
Update Failure

### ISSUE THREAD

**Issue by williambatson** [AzuraCast/AzuraCast#3161] opened 2020-09-10 16:59 UTC
DONE

**Using Docker installation method**

YES

**AzuraCast version**

AzuraCast • v0.10.3, #9811fbb (2020-06-22 4:38) 

**Host Operating System**

uBUNTU 18.04

**Describe the bug**

UPDATE FAILS OR ENDS PREMATURELY DUE TO AN ERROR  REPORTED BELOW I'VE NOT SEEN BEFORE
**To Reproduce**

UPDATE PROGRAM TO STOP ALLL SERVICES, UPDATE THEM, THEN RESTART ALL AS USUAL

**Relevant Logs**
Using Docker -  run update as normal  -   file with the following
  ++ migrating 20161006030903
     -> DROP TABLE IF EXISTS user_manages_station
     -> DELETE FROM role_has_actions WHERE role_id NOT IN (SELECT id FROM role)
     -> DELETE FROM role_has_actions WHERE action_id NOT IN (SELECT id FROM action)
     -> ALTER TABLE role_has_actions ADD CONSTRAINT FK_50EEC1BDD60322AC FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE
Migration 20161006030903 failed during Execution. Error An exception occurred while executing 'ALTER TABLE role_has_actions ADD CONSTRAINT FK_50EEC1BDD60322AC FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE':
SQLSTATE[HY000]: General error: 1005 Can't create table `azuracast`.`role_has_actions` (errno: 121 "Duplicate key on write or update")
In AbstractMySQLDriver.php line 106:
  An exception occurred while executing 'ALTER TABLE role_has_actions ADD CONSTRAINT FK_50EEC1BDD60322AC FOREIGN
  KEY (role_id) REFERENCES role (id) ON DELETE CASCADE':
  SQLSTATE[HY000]: General error: 1005 Can't create table `azuracast`.`role_has_actions` (errno: 121 "Duplicate k
  ey on write or update")
In PDOConnection.php line 83:
  SQLSTATE[HY000]: General error: 1005 Can't create table `azuracast`.`role_has_actions` (errno: 121 "Duplicate k
  ey on write or update")
In PDOConnection.php line 78:
  SQLSTATE[HY000]: General error: 1005 Can't create table `azuracast`.`role_has_actions` (errno: 121 "Duplicate k
  ey on write or update")
azuracast:setup [--update] [--load-fixtures] [--release]
2020/09/04 15:55:42 Command exited with error: exit status 1
Update complete!

**Screenshots**

![screeerror](https://user-images.githubusercontent.com/41510663/92767819-52c61a00-f34c-11ea-9fd9-51278e8148d7.png)

**Comment by SlvrEagle23** [comment] 2020-09-10 21:50
@williambatson Why the caps? :/

The error is self-explanatory in this case; your `role_has_actions` table has something in it that won't let the foreign key constraint apply correctly. Normally we check for and remove duplicates automatically, so this must be an unexpected one that we don't normally encounter during the routine update process.

I could probably fix it by looking at your installation and just cleaning up that table via a direct MySQL editor, but if you're comfortable doing that yourself you can do the same.

**Comment by williambatson** [comment] 2020-09-11 01:38
Sorry for caps.. one handed typist these days :/       Replied to you direct on Slack,   Thank you as always for all you do!

**Comment by SlvrEagle23** [comment] 2020-09-11 05:05
@williambatson This is caused by an error specific to the stable release, and has been fixed by a Composer dependency update in the rolling release.

We will be releasing a new point release for the stable release channel shortly to ensure everyone gets the fix to avoid the issue.

**Closed by SlvrEagle23** 2020-09-11 05:05 UTC

**Comment by fast97** [comment] 2020-09-11 14:58
Hello after a restore I have the same problem can you help me?
Thank you

**Comment by radiolize** [comment] 2020-09-17 15:31
Exactly the same issue happened to us and still couldn't figure it out. @SlvrEagle23 can you please share the solution if it's possible?

**Comment by SlvrEagle23** [comment] 2020-09-17 16:14
@radiolize Until we release a new stable version, it is recommended to just update to the latest rolling-release version instead, where this issue has been fixed. This will involve modifying your `.env` file to change the `PREFER_RELEASE_BUILDS` from `stable` to `latest`.

**Comment by radiolize** [comment] 2020-09-17 19:25
Solved, thanks @SlvrEagle23
