### ISSUE TITLE
Issues with Liquidsoap

### ISSUE THREAD

**Issue by radio2019** [AzuraCast/AzuraCast#2235] opened 2019-12-23 20:00 UTC
Does anyone know what this error message means;

2/23 19:57:59 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2019/12/23 19:57:59 [decoder:3] Method "MAD" accepted "/usr/local/share/icecast/web/error.mp3".
2019/12/23 19:57:59 [sandbox:3] Running inside a docker container, disabling sandboxing..
init: exception encountered during start phase:
Error while trying to bind server/telnet socket: Address already in use in bind()
2019/12/23 19:57:59 [video.converter:3] Couldn't find preferred video converter: gavl.

How can this be solved?

**Comment by SlvrEagle23** [comment] 2019-12-24 04:09
@radio2019 This error shouldn't be happening on Docker installations unless you have multiple stations using the same Liquidsoap broadcasting port, but that should be prevented by our system automatically checking for port conflicts when attempting to save changes to stations.

It could be that you somehow wound up with two Liquidsoap instances running for the same station, in which case running `docker-compose restart stations` on the host computer inside the AzuraCast directory (usually `/var/azuracast`) should fix it.

**Comment by radio2019** [comment] 2019-12-24 09:55
Thank you for your quick answer.
Two stations should use the same AzuraCast instance.
The bug fix looks difficult if you are not into programming language.

**Comment by radio2019** [comment] 2019-12-24 17:06
Can anyone do this task for me?
I'm willing to pay for it.
Looking forward to your help.
Thank you.

**Comment by SlvrEagle23** [comment] 2019-12-24 17:55
@radio2019 I don't understand what you mean. Multiple stations _can_ use a single AzuraCast instance.

Are you saying you want more than one station to use the same Liquidsoap instance? That's also possible, as long as you configure the second station not to have an AutoDJ, and then set the first one up to broadcast to the second. It's a bit complicated, but you definitely can't do it the other way, where you just run the same Liquidsoap instance twice.

**Comment by radio2019** [comment] 2019-12-24 20:03
So there is now way to use the AutoDJ on both stations?
Of course, I would like to do that.

**Comment by SlvrEagle23** [comment] 2019-12-27 17:28
@radio2019 You can definitely run an AutoDJ on both stations.

I'm trying to explain that you can't have both stations sitting on the same ports, i.e. both of them are broadcasting on port 8000 and have their AutoDJs on ports 8004/5/6. That's not how our setup works; each station has its own reserved ports, and new stations should use new ports instead.

The system will automatically do this for you. It's possible that this is a duplicate of another issue that was reported about trying to reuse a previously deleted station's port reservations.

**Comment by SlvrEagle23** [comment] 2019-12-29 12:40
Closing this as it's likely related to #2236.

**Closed by SlvrEagle23** 2019-12-29 12:40 UTC
Labels: error
