### ISSUE TITLE
file pot

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#750] opened 2018-08-26 17:24 UTC
file pot - why there was much less time for translation?
In this file I did not find half the lines and the new ones that you added them there are not.

**Comment by SlvrEagle23** [comment] 2018-08-26 21:59
@susl16c Be patient please. There's no such thing as "less time" for translation; I haven't been pushing any releases out, and won't until the translations are in for any modified locales.

I've regenerated the translation files to include the latest strings, so you can submit translations to them immediately.

**Comment by susl16c** [comment] 2018-08-27 05:42
And why do you close the question without deciding it, in that file I did not find many translations at all, what did you add.

**Comment by SlvrEagle23** [comment] 2018-08-27 23:26
@susl16c I closed it because there's nothing different going on with translations right now versus any time in the past. Sometimes I'll be working heavily on a section, so I won't generate the new locale strings until I'm confident the section is "finalized", to avoid unnecessarily asking volunteers to translate strings that will no longer be used.

I'm not sure what your specific request is, so I closed the issue to avoid piling on top of my already very high issues queue.

**Comment by SlvrEagle23** [comment] 2018-08-30 00:42
@susl16c I looked again at how I'm generating the .po locale file, and it does indeed appear there was a problem where it was missing a significant number of the translated strings.

I apologize for closing the issue early, but it should now be fixed, and the locale file should now have all strings from across the application in it again.

Your translations are very difficult for me to read and understand sometimes, so I don't know what the problem is. In the future, if a communication issue arises, it may be helpful to try to find a peer you can work with who is fluent in technical English and can relay your concerns through this GitHub issues section.

**Closed by SlvrEagle23** 2018-08-30 00:42 UTC

**Comment by susl16c** [comment] 2018-08-31 08:51
Thank you very much for your hard work, you understood me well, the problem was just in incomplete words of phrases, you solved the problem. Thank you
