### ISSUE TITLE
Cronjob do not work

### ISSUE THREAD

**Issue by inetactief** [AzuraCast/AzuraCast#1209] opened 2019-02-23 12:42 UTC
Al cronjob do not automatic run on
v0.9.2, #1899410 (2019-02-20 18:07) • Docker • PHP 7.2 on CentOS 7.

On version v0.9.1 i have the same problem, how can run this cronjobs?
Normal i check crontab -e to check it.

**Comment by Vaalyn** [comment] 2019-02-23 14:30
When you open the `System Administration` page you can see these panels at the bottom of the page: http://prntscr.com/mp2p31. Click on the `Run Task` button to manually execute them.

Before you do this please check when they were last run and check your logs at `System Administration` -> `System Logs` for any errors and post them here.

**Comment by inetactief** [comment] 2019-02-23 14:48
Yes i can do this by hand. The radio station now playing wigdet do not work. 

The nowplaying give errror:
cURL error 7: Failed to connect to caster04.streampakket.com port 8318: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
CurlFactory.php : 185
Some station use relay i see..

The 5 and 60 min works fine when i click on run, no errors.

I see only in Azuracast app log: [2019-02-22 09:30:35] AzuraCast.INFO: Running message queue processor for 300 seconds. [] []

**Comment by SlvrEagle23** [comment] 2019-02-23 23:47
@inetactief It appears the error is with your remote relay URL. If a connection is refused (i.e. doesn't just time out or return as "not found"), then this is considered an exception and stops processing of other now-playing data so it can be addressed.

**Comment by inetactief** [comment] 2019-02-24 07:15
We remove the relay url.
But the not still work automatic...

How can the task work automatically? Please where can i check the commands for automatic run?

**Comment by SlvrEagle23** [comment] 2019-02-24 18:10
@inetactief You can manually run the CLI task as `./docker.sh cli azuracast:sync nowplaying` and see if it returns any errors.

**Comment by inetactief** [comment] 2019-02-25 09:10
Hi,

we get : [root@localhost azura]# ./docker.sh cli azuracast:sync nowplaying
Starting azuracast_redis_1 ...
Starting azuracast_redis_1 ... done
Starting azuracast_mariadb_1 ... done
Starting azuracast_stations ... done
2019/02/25 09:11:51 Waiting for: tcp://mariadb:3306
2019/02/25 09:11:51 Waiting for: tcp://influxdb:8086
2019/02/25 09:11:51 Connected to tcp://mariadb:3306
2019/02/25 09:11:51 Connected to tcp://influxdb:8086


  Command "azuracast:sync" is not defined.

  Did you mean one of these?
      azuracast:account:reset-password
      azuracast:account:set-administrator
      azuracast:api:docs
      azuracast:config:migrate
      azuracast:internal:auth
      azuracast:internal:djoff
      azuracast:internal:djon
      azuracast:internal:nextsong
      azuracast:internal:uptime-wait
      azuracast:media:reprocess
      azuracast:radio:restart
      azuracast:settings:list
      azuracast:settings:set
      azuracast:setup
      azuracast:setup:fixtures
      azuracast:setup:influx


2019/02/25 09:11:52 Command exited with error: exit status 1

**Comment by SlvrEagle23** [comment] 2019-02-25 18:48
@inetactief Sorry, it's `./docker.sh cli sync:run nowplaying`.

**Comment by inetactief** [comment] 2019-02-25 19:37
[root@localhost azura]# ./docker.sh cli sync:run nowplaying
Starting azuracast_redis_1 ...
Starting azuracast_redis_1 ... done
Starting azuracast_mariadb_1 ... done
Starting azuracast_stations ... done
2019/02/25 19:39:41 Waiting for: tcp://mariadb:3306
2019/02/25 19:39:41 Waiting for: tcp://influxdb:8086
2019/02/25 19:39:41 Connected to tcp://mariadb:3306
2019/02/25 19:39:41 Connected to tcp://influxdb:8086
[2019-02-25 19:39:41] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-02-25 19:39:42] AzuraCast.ERROR: NowPlaying adapter error: Request returned status 404: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>404 Not Found</title> </head><body> <h1>Not Found</h1> <p>The requested URL /status-json.xsl was not found on this server.</p> <p>Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.</p> </body></html>  [] {"station":{"id":3,"name":"Radio Assembly of Zion "}}
2019/02/25 19:39:44 Command finished successfully.

**Comment by SlvrEagle23** [comment] 2019-02-25 20:45
@inetactief What version of Icecast are you trying to connect to? This issue may be caused by using a version that doesn't have the `/status-json.xsl` file (usually pre-2.4.2), but our system should be gracefully "failing over" to the XML now-playing data if necessary. Will look into this on the NowPlaying library.

**Comment by inetactief** [comment] 2019-02-26 07:20
Hi i check the info page of Icecast we see 
Icecast 2.4.0-kh10-ac4, how can we update Icecast?

**Comment by SlvrEagle23** [comment] 2019-02-26 07:29
@inetactief Wait...that's an AzuraCast installation's Icecast. The internal Icecast should definitely never be throwing a 404 like that.

Can you e-mail me with your specific installation URL and Icecast URL? I need to investigate that.

**Comment by inetactief** [comment] 2019-02-26 07:30
yes what is your email address?

**Comment by SlvrEagle23** [comment] 2019-02-26 07:31
@inetactief buster@busterneece.com

**Comment by inetactief** [comment] 2019-03-11 10:10
Hi Buster, 

Do you recive my last email? 
I do not install the last update AzuraCast 0.9.3 running now on 0.9.2

**Comment by SlvrEagle23** [comment] 2019-03-11 15:32
@inetactief Can you update to the latest version? I definitely can't resolve issues if you aren't on the latest rolling release, as that's the only release that includes my fixes.

**Comment by inetactief** [comment] 2019-03-12 06:33
We have update to 0.9.3 but it run not automatic. When we do it by hand it look like i have good output.

**Comment by SlvrEagle23** [comment] 2019-03-12 07:12
@inetactief What does `docker-compose logs -f web` say? There should be a cron task that runs every minute and it should be showing you the status of that process.

**Comment by inetactief** [comment] 2019-03-12 07:21
I see every minute in the log this:
web_1       | Mar 12 07:20:01 56245b9f24f9 cron[43]: (*system*) NUMBER OF HARD LINKS > 1 (/etc/crontab)
web_1       | Mar 12 07:20:01 56245b9f24f9 cron[43]: (*system*azuracast) NUMBER OF HARD LINKS > 1 (/etc/cron.d/azuracast)
web_1       | Mar 12 07:20:01 56245b9f24f9 cron[43]: (*system*certbot) NUMBER OF HARD LINKS > 1 (/etc/cron.d/certbot)
web_1       | Mar 12 07:20:01 56245b9f24f9 cron[43]: (*system*php) NUMBER OF HARD LINKS > 1 (/etc/cron.d/php)

But my status is in Systeembeheer (dutch) 

Nu speelt gegevens
12 maart 2019 om 07:35:59 CET
46 minuut geleden

1 minuut synchronisatie
Verzoeknummers in wachtrij
12 maart 2019 om 07:28:19 CET
53 minuut geleden

5 minuten synchronisatie
Check media mappen
12 maart 2019 om 07:28:26 CET
53 minuut geleden

**Comment by inetactief** [comment] 2019-03-12 07:23
And the new version 0,9.3 have a big load on the server?? 
%Cpu0  : 51.6 us,  3.2 sy,  0.0 ni, 41.9 id,  0.0 wa,  0.0 hi,  3.2 si,  0.0 st
%Cpu1  : 90.0 us,  3.3 sy,  0.0 ni,  6.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  8015636 total,   912052 free,  1441604 used,  5661980 buff/cache
KiB Swap:  8257532 total,  7947428 free,   310104 used.  5992872 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
20080 michelvd  20   0  923440 318068   8404 S  86.7  4.0  52:04.69 liquidsoap
19955 michelvd  20   0  594012  50684   9200 S  16.7  0.6   9:39.08 liquidsoap
19897 michelvd  20   0  604136  59320   9320 S  10.0  0.7   5:19.43 liquidsoap
20038 michelvd  20   0  604136  59360   9232 S  10.0  0.7   5:27.90 liquidsoap
19201 root      20   0   64596  19000   4212 S   6.7  0.2   2:20.88 supervisord
19992 michelvd  20   0  594012  48992   8752 S   6.7  0.6   3:35.22 liquidsoap
18707 polkitd   20   0 1944408 152724  11284 S   3.3  1.9   0:12.49 mysqld
19863 michelvd  20   0  604136  58672   8800 S   3.3  0.7   3:43.03 liquidsoap
24575 michelvd  20   0  463308  17112   9084 S   3.3  0.2   0:00.05 php-fpm7.2

**Comment by SlvrEagle23** [comment] 2019-03-12 07:44
@inetactief I pushed an update to the Web container that should fix the issue preventing cron jobs from working properly. Please update and let me know if it helps.

As for the load issue, this is already being tracked as issue #1291.

**Comment by SlvrEagle23** [comment] 2019-03-13 19:06
@inetactief Please let me know if your cron jobs are running again so I can close this issue.

**Comment by inetactief** [comment] 2019-03-14 11:43
Thanks you! When we do a update the stations are go offline. So i can not do this every day.
So next week a do a update in the evening (late). I let you know

**Closed** 2019-03-20 01:26 UTC
Labels: bug, in progress

**Comment by inetactief** [comment] 2019-03-20 08:15
It woks yesterday night i update the to the last version
Thank you!
