### ISSUE TITLE
Little Bug in Playlist Once A Day

### ISSUE THREAD

**Issue by LordHelmchen666** [AzuraCast/AzuraCast#1158] opened 2019-02-08 16:55 UTC
**Installation method**
Docker

**Host OS (for Docker installations)**
Ubuntu 16.04

**Describe the bug**
When using Playlist Once A Day it produces wrong entry in liquidsoap.liq if you leave days blank.

**To Reproduce**
1. Go to 'Playlists'
2. Click on 'Add Playlist'
3. Choose 'Daily' and leave blank 'Scheduled Play Days of Week'
4. See in liquidsoap.liq `({ ( 0w) and 16h15m }, playlist_impressum)` which means play at Sunday 16h15m.

**Expected behavior**
Entry in liquidsoap.liq should be `({ (1w or 2w or 3w or 4w or 5w or 6w or 0w) and 16h15m }, playlist_impressum)` or `({16h15m }, playlist_impressum)`

**Comment by Vaalyn** [comment] 2019-02-08 18:46
I've looked a bit into this issue and could reproduce it. The bug seems not to be in the generation of the Liquidsoap config file but with the saving of the playlist in the database. The `play_once_days` has a value of `0`. When selecting no days this should be empty.

**Comment by SlvrEagle23** [comment] 2019-02-09 21:10
@Vaalyn Probably a product of the new serializer/deserializer that handles converting to/from Doctrine entities. It should be intelligently looking at the type of the `setFoo` method's first parameter and casting appropriately, but it seems to be messing up here. Will investigate as I get a chance.

**Comment by SlvrEagle23** [comment] 2019-02-12 17:35
@LordHelmchen666 Should be fixed as of the latest update.

**Closed by SlvrEagle23** 2019-02-12 17:35 UTC
Labels: bug, in progress
