### ISSUE TITLE
install shoutcast error 500

### ISSUE THREAD

**Issue by YosefAdPro** [AzuraCast/AzuraCast#1568] opened 2019-05-22 10:53 UTC
Hello,

i use bare-metal
After upgrading version 0.9.4 to version 0.9.5, on the install shoutcast page receiving error 500 .

500
Input type "" not found.
AbstractForm.php : 325

![image](https://user-images.githubusercontent.com/11810187/58169208-e166e180-7c98-11e9-930b-d7df80a2d80b.png)

**Comment by MrSteelMiner** [comment] 2019-05-22 14:43
Try: https://github.com/AzuraCast/AzuraCast/issues/1503#issuecomment-489110708

**Comment by Vaalyn** [comment] 2019-05-23 13:21
I'd recommend you to do an update to the latest rolling release version (updating without the `--release` flag) as I can't reproduce this issue on the newest version.

**Comment by reans** [comment] 2019-05-27 08:10
Same issue here. New installtion of azuracast with docker method. Host OS ubuntu 18.10
After setup the azuracast i upload the shoutcast file but this is the error after uploading the file 

![image](https://user-images.githubusercontent.com/27730047/58405289-a8b07900-8099-11e9-8ccf-6562472fbf35.png)

anyone can help to solve this issue?

**Comment by SlvrEagle23** [comment] 2019-05-27 15:37
@YosefAdPro @reans This issue has been fixed as of the latest rolling release update.

**Closed by SlvrEagle23** 2019-05-27 15:37 UTC
Labels: error
