### ISSUE TITLE
After upgrade DJ Streamers cannot connect

### ISSUE THREAD

**Issue by dinosd** [AzuraCast/AzuraCast#3658] opened 2021-01-11 18:22 UTC
Although credentials and connection parameters are correct I get the following message in Liquidsoap log:

 AzuraCast Feedback Response: Error: Cannot check permission with no user set. on /var/azuracast/www/src/Acl.php L136

**Comment by smilingpeanut** [comment] 2021-01-11 18:45
Duplicate of #3653.

**Comment by Vaalyn** [comment] 2021-01-11 21:28
Closing as duplicate

**Closed by Vaalyn** 2021-01-11 21:28 UTC
Labels: duplicate
