### ISSUE TITLE
Public schedule page does not show all the playlists

### ISSUE THREAD

**Issue by jrp596** [AzuraCast/AzuraCast#4505] opened 2021-08-20 07:53 UTC
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.14.0

### What happened?

*Public schedule page does not show all the playlists.
*Playlist name is not showing.

>Public page 

![Untitled](https://user-images.githubusercontent.com/59512192/130199109-ae6ee4a9-97a7-4251-bbf2-4c74a5f01ec5.png)

>Playlist schedule page

![Untitled](https://user-images.githubusercontent.com/59512192/130199601-90cf6a66-5cfe-4251-91cb-f2f3c54503c2.png)

**Comment by Abqehebter** [comment] 2021-08-20 10:53
I can confirm this in Rolling Release #02c653a (2021-08-20 3:22):

Public page:
![image](https://user-images.githubusercontent.com/42640247/130222865-13298df0-6280-45c4-802b-360bb6cf859b.png)

Playlist schedule page:
![image](https://user-images.githubusercontent.com/42640247/130222811-5b058cb0-df8f-44a7-a579-898c538dffc4.png)

**Comment by GeertSurkijn** [comment] 2021-08-30 22:10
This error I get on mine, it is not finding the libraries...
![image](https://user-images.githubusercontent.com/8115472/131412293-08ee0426-6717-4703-8637-7022f82fb58a.png)

**Comment by LordHelmchen666** [comment] 2021-09-02 15:28
Errors are the same on my site.

I don't want to open new issue, so i post here.
Would be nice if we could write a short description of the show  and upload a show logo. Maybe shown with popup when you click showname.

**Comment by SC2Mitch** [comment] 2021-09-24 09:05
This should be fixed in the latest rolling, can someone verify please?

**Comment by Abqehebter** [comment] 2021-09-24 09:39
I will test it.

**Comment by Abqehebter** [comment] 2021-09-24 09:44
Always empty.
Intern:
![image](https://user-images.githubusercontent.com/42640247/134654510-8a064313-ad88-4607-bdd3-56db40b46b1e.png)
Public:
![image](https://user-images.githubusercontent.com/42640247/134654539-9c0e9d05-6143-4822-a729-fb0648ee3aac.png)

**Comment by SlvrEagle23** [comment] 2021-09-24 19:02
@Abqehebter On my local end, the latest fixes on Rolling Release do indeed fix that page as well. I'll have to see why a playlist might not be appearing on the schedule page now. If you're getting any sort of console logs, please let me know.

**Comment by Abqehebter** [comment] 2021-09-24 19:05
Nevermind, it seems to work after some time. Not directly after creating the playlist, but it works!
![image](https://user-images.githubusercontent.com/42640247/134727250-f98402a0-55c3-4ad7-a498-366b2ac758ec.png)

**Comment by SlvrEagle23** [comment] 2021-09-24 19:06
@Abqehebter Ah, that's just the cache in action; since it's a public-facing page, the data is cached more aggressively than it is on the private pages, to ensure the public can't just overload the system by looking at an embedded component.

**Closed by SlvrEagle23** 2021-09-24 19:06 UTC
Labels: bug, needs investigation, stable, rolling-release, frontend, api
