### ISSUE TITLE
Scheduled tracks that interrupt other songs are played after a live show 

### ISSUE THREAD

**Issue by wegGehamstert** [AzuraCast/AzuraCast#7160] opened 2024-05-30 18:22 UTC
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #5397ec2

### What happened?

I don't know whether this is a bug or a feature request. However, I think it is a behavior that should not be like this. 

If a playlist is supposed to play a track at a certain time and a live broadcast takes place during this time, it is played immediately after the end of the broadcast. Which can be far too late, depending on the situation, and is then no longer really appropriate. 

I think it would be better for many people if the track wasn't put in the queue when a live broadcast is taking place.

![image](https://github.com/AzuraCast/AzuraCast/assets/78315888/9147e2be-6b24-4e65-a028-7af38895260b)
Here you can see what happens. The 08:00 Jingle should be played at 20:00. But because the live broadcast was started at 19:55 it was just sitting there.

**Comment by BusterNeece** [comment] 2024-05-31 06:02
Flagging this as "in progress" just so the stale bot doesn't eat it...you're correct that this likely isn't the intended behavior, but I'm not immediately sure how to reliably prevent it. We may just have to avoid pushing to the interrupting queue if the current DJ is live.

**Comment by wegGehamstert** [comment] 2024-05-31 08:00
That would a good idea..
Maybe someboey else have a solution how to approach this

**Comment by BusterNeece** [comment] 2024-11-27 17:52
Closing as implementing our new "interrupting" method (as described in #7554) will not be subject to this issue.

**Closed by BusterNeece** 2024-11-27 17:52 UTC
Labels: bug, in progress, rolling-release
