### ISSUE TITLE
Strange queue activity

### ISSUE THREAD

**Issue by NicoxDJ** [AzuraCast/AzuraCast#3549] opened 2020-12-12 14:24 UTC
**Using Docker installation method**
No

**AzuraCast version**
Rolling Release #98276e6 (2020-12-09 16:22)

**Host Operating System**
Ubuntu 18.04 LTS

**Describe the bug**
Hello, i've notice somethings strange and i'll try to explain it. It's been 12 days since i'm running christmas songs on my station. You know i had problem with adding new songs into the station #3490 . Since than i almost listen/monitoring the radio 16hrs per day. What i've notice, is that the only newly added songs are rotating. Even not all of them. I'm listen the same songs almost every hour. The playlist contains 379 songs, and i think the maximum 50 of them are rotating. I don't know if the code is build in that way, to rotate the newly songs more, but its driving me crazy, because i add some really old songs like from 1970, and its mostly rotating them. No one will love to listen these old songs almost always. I've trying restarting, reseting cache, 1min-3min-5min-1hrs syncs, nothing worked out. And also the problem #2972 with the wrong next song still exist. I'm thinking over to format everything and start over with new clear install (with docker, if it support now ARM).

**Device(s):**
 - Device: Raspberry Pi 3B+

**Comment by NicoxDJ** [comment] 2020-12-13 19:13
Hey @Vaalyn, what does unsupported actually mean? Can you help me at least with pointing me to the QueryBuilder which is sending songs to the Liquidsoap? Maybe i can digg around there and fix it?

**Comment by Vaalyn** [comment] 2020-12-13 20:15
Unsupported means `A question or report that may be (or is) caused by using an unsupported configuration (i.e. Ansible)` which in regards to what that actually means is that we will not be spending time on trying to diagnose issues on those installations since the Ansible installation is meant for users who are able to diagnose issues by themself and also fix them. If it is a general problem that is affecting a lot of users and is clearly not caused by the installation being on Ansible then that's something different.

Since we are not officially supporting Ansible installations I'm tagging issues with installations that are using Ansible with that label in order to correctly categorize them.

In regards to the logic that is responsible for the AutoDJ that would be the [Scheduler](https://github.com/AzuraCast/AzuraCast/blob/master/src/Radio/AutoDJ/Scheduler.php) and the [Queue](https://github.com/AzuraCast/AzuraCast/blob/master/src/Radio/AutoDJ/Queue.php).

**Comment by scotchale** [comment] 2020-12-13 23:55
I didn't spent 16hrs listening but I notice that some songs are frequently passed (sometimes also in the same hour) and a lot of others are not. Maybe having a dedicated report page, like "how many times songs are played" can help!

Using Docker installation method
Yes

AzuraCast version
v0.11.2 Stable

Host Operating System
Debian 10 (Buster)

**Comment by scotchale** [comment] 2020-12-14 00:09
Sorry, I notice now that the report exists: having 2000songs and more, the first is played 25 times while a lot are not played yet. My device with the station shutdown every day at 5am and turn on at the 8am, maybe that can affect?

**Comment by NicoxDJ** [comment] 2020-12-14 10:22
@Vaalyn @scotchale Well, i edit the playlist "Song Playback Order" from "Shuffled" to "Random". So far is better. At least it plays older songs too. So i just have to see why shuffled is doing this. According to the description, it have to shuffle thru all songs and than repeat. I have 18.6hours of music in that playlist. So basically for 5 days since i fix my problem and run the new songs this should be 1.29 times for a song per day. For 5 days should be 6.45 times played of each song, right? But the "Most Played Songs in the last month" says 10 songs all with play count from 51 to 48 times. Only one of all these is old song, the rest are the newly added songs. And the songs are working if you queue them manually which means they are not corrupted or something else. I don't really think this is Ansible problem.

**Comment by scotchale** [comment] 2020-12-19 14:52
In my case, it was because i assigned a folder to a plylist and after i assigned also the subfolders and (not happy yet) i assigned single files inside that folders. So i had songs 3times assigned to the playlist. Removing all the assignament and saving only 1 time the big folder to the playlist i solved (and number of songs in the playlist counter give me the real number, instead of the sum of triplicated songs). Maybe it's good to prevent this error not giving the possibility to add the same playlist on a song or on a folder that already have this assigned.

**Closed** 2021-03-16 09:29 UTC
Labels: unsupported
