### ISSUE TITLE
Most of listeners are from 192.168.0.6 ???

### ISSUE THREAD

**Issue by hecgua** [AzuraCast/AzuraCast#3038] opened 2020-07-16 21:28 UTC
I realized a few moments ago that most of the radio listeners IP's is 192.168.0.6 on Icecast. This issue is in all my stations and in all the mount points. I suppose this started since the last update,  v0.10.3, #23af29f (2020-07-12 23:33) Rolling • Docker • PHP 7.4. I just restarted  one radio and the issue remains. Is this a bug?

![Screenshot_15](https://user-images.githubusercontent.com/58102945/87724323-e16d4f00-c780-11ea-8790-8aa2fe0eb8bd.png)

Curiously , there was a bug before this update with songs request IP's because they were showing the IP number 172.31.0.4 in all requests and now they are showing the correct request IP.

**Comment by pixel-paul** [comment] 2020-07-16 21:43
Yes, this is a known issue. I raised this here: #2898

**Comment by SlvrEagle23** [comment] 2020-07-17 23:08
Closing as a duplicate of #2898.

**Closed by SlvrEagle23** 2020-07-17 23:08 UTC
