### ISSUE TITLE
Getting errors running updates

### ISSUE THREAD

**Issue by Moderndayfreak** [AzuraCast/AzuraCast#1864] opened 2019-08-15 15:30 UTC
**Using Docker installation method**

Yes
**Host Operating System**

Ubuntu 18
**Describe the bug**

Getting Errors when running updates for the latest version of Azuracast

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 
Desktop
**Additional context**

root@azuracast:~# /var/azuracast/
-bash: /var/azuracast/: Is a directory
root@azuracast:~# ./docker.sh update-self
New Docker utility script downloaded.
root@azuracast:~# ./docker.sh update
Pulling mariadb  ... done
Pulling influxdb ... done
Pulling redis    ... done
Pulling stations ... done
Pulling web      ... done
Stopping root_redis_1    ... done
Stopping root_mariadb_1  ... done
Stopping root_influxdb_1 ... done
Removing root_redis_1    ... done
Removing root_mariadb_1  ... done
Removing root_influxdb_1 ... done
Removing network root_default
Error response from daemon: remove azuracast_www_data: volume is in use - [a1246                                                                           e7c18734f2d8dead7523a9782906b0d6478e3ff4613d1aa392e3c3ce151]
Error response from daemon: remove azuracast_tmp_data: volume is in use - [a1246                                                                           e7c18734f2d8dead7523a9782906b0d6478e3ff4613d1aa392e3c3ce151, 061f160f360c0376fb7                                                                           eaceac4928ec7d932785f8e2a5223546f3a33283d88a5]
Creating network "root_default" with the default driver
Creating root_influxdb_1 ...
Creating root_mariadb_1  ...
Creating root_redis_1    ...
Creating azuracast_stations ... error

Creating root_influxdb_1    ... done
Creating root_mariadb_1     ... done
Creating root_redis_1       ... done
emove (or rename) that container to be able to reuse that name.

ERROR: for stations  Cannot create container for service stations: Conflict. The                                                                            container name "/azuracast_stations" is already in use by container "061f160f36                                                                           0c0376fb7eaceac4928ec7d932785f8e2a5223546f3a33283d88a5". You have to remove (or                                                                            rename) that container to be able to reuse that name.
ERROR: Encountered errors while bringing up the project.
root_redis_1 is up-to-date
root_influxdb_1 is up-to-date
root_mariadb_1 is up-to-date
Creating azuracast_stations ... error

ERROR: for azuracast_stations  Cannot create container for service stations: Con                                                                           flict. The container name "/azuracast_stations" is already in use by container "                                                                           061f160f360c0376fb7eaceac4928ec7d932785f8e2a5223546f3a33283d88a5". You have to r                                                                           emove (or rename) that container to be able to reuse that name.

ERROR: for stations  Cannot create container for service stations: Conflict. The                                                                            container name "/azuracast_stations" is already in use by container "061f160f36                                                                           0c0376fb7eaceac4928ec7d932785f8e2a5223546f3a33283d88a5". You have to remove (or                                                                            rename) that container to be able to reuse that name.
ERROR: Encountered errors while bringing up the project.
Update complete!
root@azuracast:~# ./docker.sh update-self && echo "y" | ./docker.sh update
New Docker utility script downloaded.
Pulling mariadb  ... done
Pulling influxdb ... done
Pulling redis    ... done
Pulling stations ... done
Pulling web      ... done
Stopping root_mariadb_1  ... done
Stopping root_redis_1    ... done
Stopping root_influxdb_1 ... done
Removing root_mariadb_1  ... done
Removing root_redis_1    ... done
Removing root_influxdb_1 ... done
Removing network root_default
Error response from daemon: remove azuracast_www_data: volume is in use - [a1246e7c18734f2d8dead7523a9782906b0d6478e3ff4613d1aa392e3c3ce151]
Error response from daemon: remove azuracast_tmp_data: volume is in use - [a1246e7c18734f2d8dead7523a9782906b0d6478e3ff4613d1aa392e3c3ce151, 061f160f360c0376fb7eaceac4928ec7d932785f8e2a5223546f3a33283d88a5]
Creating network "root_default" with the default driver
Creating root_influxdb_1 ...
Creating azuracast_stations ... error
Creating root_mariadb_1     ...
Creating root_influxdb_1    ... done

Creating root_mariadb_1     ... done
Creating root_redis_1       ... done

ERROR: for stations  Cannot create container for service stations: Conflict. The container name "/azuracast_stations" is already in use by container "061f160f360c0376fb7eaceac4928ec7d932785f8e2a5223546f3a33283d88a5". You have to remove (or rename) that container to be able to reuse that name.
ERROR: Encountered errors while bringing up the project.
root_redis_1 is up-to-date
root_influxdb_1 is up-to-date
root_mariadb_1 is up-to-date
Creating azuracast_stations ... error

ERROR: for azuracast_stations  Cannot create container for service stations: Conflict. The container name "/azuracast_stations" is already in use by container "061f160f360c0376fb7eaceac4928ec7d932785f8e2a5223546f3a33283d88a5". You have to remove (or rename) that container to be able to reuse that name.

ERROR: for stations  Cannot create container for service stations: Conflict. The container name "/azuracast_stations" is already in use by container "061f160f360c0376fb7eaceac4928ec7d932785f8e2a5223546f3a33283d88a5". You have to remove (or rename) that container to be able to reuse that name.
ERROR: Encountered errors while bringing up the project.
Update complete!
root@azuracast:~#

Still getting these update messages when logging in:

https://snag.gy/fM8lq7.jpg

**Comment by afonsosantos** [comment] 2019-08-21 12:03
@Moderndayfreak Hi!

Looks like some volumes are still in use, even after the upgrader deactivates them. You coul try to issue `docker-compose down` and after try to update.

**Comment by SlvrEagle23** [comment] 2019-08-22 00:09
@Moderndayfreak This is a duplicate of #1876 and you should follow the instructions from that thread to resolve it.

**Closed by SlvrEagle23** 2019-08-22 00:09 UTC
Labels: error
