### ISSUE TITLE
Dropbox Storage can not be added

### ISSUE THREAD

**Issue by markgajones** [AzuraCast/AzuraCast#3529] opened 2020-12-09 10:44 UTC
**Using Docker installation method**

Yes 
**AzuraCast version**

**Host Operating System**

Ubuntu 16.04
**Describe the bug**

Cannot add Dropbox storage location
**To Reproduce**

Go to Admin/Storage locations
Click on "Add Stprage Location"
then on "Dropbox"
Enter the path (in this case, "dropbox"
set the size to 1gb
add the access token
**Expected behavior**

The ability to access files from DropBox.
**Relevant Logs**

×
App\Exception\ValidationException at /var/azuracast/www/src/Controller/Api/AbstractApiCrudController.php L148: Object(App\Entity\StorageLocation).adapter: The value you selected is not a valid choice. (code 8e179f1b-97aa-4560-a02f-2a8b42e49df7)
**Screenshots**

![image](https://user-images.githubusercontent.com/1552546/101619548-57fa3a00-3a0b-11eb-9c06-2bb48c705d68.png)
**Device(s):**
 - Device:  PC
 - OS:  Windows 10
 - Browser:  Chrome
 - Version:  Version 87.0.4280.88 (Official Build) (64-bit)

**Additional context**

**Comment by SlvrEagle23** [comment] 2020-12-09 10:50
@markgajones Thank you for the report! Closing this issue as this is a duplicate of #3527 which we are working on fixing at the moment.

**Closed by SlvrEagle23** 2020-12-09 10:50 UTC
