### ISSUE TITLE
Can't load request modal window

### ISSUE THREAD

**Issue by dturrina** [AzuraCast/AzuraCast#3271] opened 2020-10-13 13:54 UTC
Hi,

after a fresh Azuracast Docker install on Debian (provided by Linode), I can't load the song request modal window in the public page.
I've seen that all 899 songs are loaded by checking HTTP answer through Chrome Developer tools, but the dark overlay doesn't go away, so I have to refresh the page in order to see it properly.
You can check the issue on my webpage, http://radio.poesiasenzaveli.it .

Recently played history works well, though.

**Comment by dturrina** [comment] 2020-10-14 06:12
I found out that in the HTML code, the <div id="modal-request"> is _inside_ the <div id="modal-history">, as you can see by attached code (lines 195-251), a </div> is missing. The only customization I brought to the page is inside the azuracast customization part, adding some CSS lines in order to change background and add transparency to radio window (ll. 26-35).
[bug-div.txt](https://github.com/AzuraCast/AzuraCast/files/5375972/bug-div.txt)

**Comment by SlvrEagle23** [comment] 2020-10-14 06:12
@dturrina I found the cause of this, a missing `</div>` from a recent commit that improved the visuals of the Song History modal (which is on that same page).

This should be fixed as of the latest update. If you follow our updating instructions for your installation and it should resolve the issue.

**Closed by SlvrEagle23** 2020-10-14 06:12 UTC

**Comment by dturrina** [comment] 2020-10-14 06:15
Rolling or stable relase, please? Thank you

**Comment by SlvrEagle23** [comment] 2020-10-14 06:16
@dturrina The fix is in the latest rolling release version.
