### ISSUE TITLE
All sorts of playlists except the general rotation for music don't seem to work.

### ISSUE THREAD

**Issue by thedavidde** [AzuraCast/AzuraCast#1364] opened 2019-03-28 19:27 UTC
Hello,

All sorts of playlists except the general rotation for music don't seem to work. No jingles or adverts are played. The once per hour feature doesn't work as well. I tried it with a remote file URL and it just endlessly looped one or two seconds of the middle of it.

Greetings

David

**Comment by SlvrEagle23** [comment] 2019-03-28 19:32
@thedavidde When was your last update? I've been working on this all day today, and as of around 4-5pm UTC several of these issues should be fixed.

**Comment by thedavidde** [comment] 2019-03-28 20:01
We have installed the latest update.  Unfortunately there are still no elements contributions from other playlists played.

**Comment by Ficreet** [comment] 2019-03-28 20:56
I confirm that I have the same problem with the last update installed. Only the music is played all the time, jingles or interruptions, any of them, do not work

**Comment by SlvrEagle23** [comment] 2019-03-28 21:24
@thedavidde @Ficreet I've identified the cause of the problem and published a fix in the code. Please update and let me know if the issue is resolved.

We're in the process of trying to consolidate our "Manual AutoDJ" and AzuraCast's own "AutoDJ" classes, to take AzuraCast back out of the business of handling scheduling on its own, which was causing a significant number of problems.

**Comment by Ficreet** [comment] 2019-03-28 21:38
After the update, and for my part, it seems that the problem is indeed solved (I did have a jingle that started between the musics). To be confirmed for other persons

In any case, thank you for the speed of reaction, it is a pleasure. Good continuation to you!

**Comment by thedavidde** [comment] 2019-03-28 22:20
It works for me too. Many Thanks! 

What is not working yet is an MP3 which I have integrated via remote URL. (http://aktuell.wissenin60sekunden.de/aktuell.mp3) This sounds when playing like a CD that hangs.

**Comment by tonimad** [comment] 2019-03-28 22:33
If you run a fresh installation with the latest update in "Ubuntu Bare-metal Installation", when you create the first radio station, the following error appears in the "On the Air" section:

`Stream offline`

( !! ) And also, the audio "error.mp3" does not play.

**Comment by chourmovs** [comment] 2019-03-29 08:39
Regression fix confirmed ^^
Thx boss

**Closed** 2019-03-29 18:46 UTC
Labels: error, in progress

**Comment by SlvrEagle23** [comment] 2019-03-29 18:47
@tonimad That's another issue, albeit a fairly minor one as it only affects stations with no contents that were just created, which technically *are* offline (as my error message doesn't really count as a station). If you don't mind creating another GitHub issue for that, though, I can take a look.
