### ISSUE TITLE
No sound on public site with HTTPS configured

### ISSUE THREAD

**Issue by NadjaNeville** [AzuraCast/AzuraCast#1786] opened 2019-07-26 22:32 UTC
Docker installation on Ubuntu 18.04.2 LTS

No log entries, stream is running fine when opening the stream page directly, public page has no sound though. The installation is using all standard port ranges no overrides, all like the factory delivered it aside from installing let's encrypt it certificate via the docker script. The "always use HTTPS" box is checked, but unchecking it doesn't change the issue. 

Public page opens and shows everything, just has no sound although the progress bar is advancing showing music playing.

Is there any way to make sound happen on the public page with a setting in the nginx configs or somewhere else?

**Comment by ErnestPH** [comment] 2019-07-26 22:42
What browser are you using?

**Comment by NadjaNeville** [comment] 2019-07-28 14:48
Tested in Chrome, Firefox and Microsoft Edge, same in every browser, public page has no sound.

**Comment by Kerneltroll** [comment] 2019-07-28 15:49
On chrome, go to your website, load up chrome console (F12), click play and see what errors are something and post them here?

**Comment by Kerneltroll** [comment] 2019-07-28 15:49
Also, are firewalls opened for the radio ports?

**Comment by SlvrEagle23** [comment] 2019-07-28 22:56
@NadjaNeville Update again to the latest version and this should be fixed. Ansible installs had an issue with our tagged release version that prevented them from picking up Now Playing data correctly.

**Closed by SlvrEagle23** 2019-07-28 22:56 UTC

**Comment by NadjaNeville** [comment] 2019-07-29 11:02
@SlvrEagle23 I am using docker now as ansible is not supported any more. Updated to latest but the public page is still mute.

**Comment by TheOncomingStorm** [comment] 2019-10-18 16:10
I can confirm this. I don't have a previous copy of Azuracast since this is my first install or else I might be able to see what change caused it, and unfortunately I'm installed via docker so it wouldn't be easy to clone the github and see what the issue is.

**Comment by SlvrEagle23** [comment] 2019-10-20 05:45
@NadjaNeville @TheOncomingStorm In a majority of cases, this is caused by the "Enable Web Proxy" setting needing to be turned on for your given configuration, but not being turned on.

This is so common (due to things like CloudFlare) that I've opted to set the default for this setting to be _enabled_ on new installations, as we encounter a significant number of users coming and asking us why their radio stations won't play once they've enabled HTTPS.

**Comment by TheOncomingStorm** [comment] 2019-10-20 15:08
I have Cloudflare on other sites but not on this one as I am currently only accessing it through the IP address since we are testing the software and don't even have a domain for it yet.

**Comment by gozfly** [comment] 2021-01-02 01:01
> able We

Thank you!
Problem solved.
"Enable Web Proxy" ON

**Comment by huhas12** [comment] 2021-01-12 10:25
Hello, 

I've setted up AzuraCast with docker in a Google VM instance. Having trouble though with sound. 

I use chrome console to see the problem and I am getting the following:

Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
just4music.live:1 Uncaught (in promise) DOMException: Failed to load because no supported source was found.
DevTools failed to load SourceMap: Could not load content for https://34.89.141.188/static/dist/lib/bootstrap/bootstrap.bundle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://34.89.141.188/static/dist/lib/bootstrap-vue/bootstrap-vue.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://34.89.141.188/static/dist/lib/moment/moment.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://34.89.141.188/static/dist/lib/moment/locales.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://34.89.141.188/static/dist/lib/bootstrap-vue/bootstrap-vue.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

I am new to AzuraCast any detailed instructions will be much appreciated !
