### ISSUE TITLE
When you have flac

### ISSUE THREAD

**Issue by keiranchippendaleuk** [AzuraCast/AzuraCast#5701] opened 2022-08-30 19:56 UTC
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#53080b1 

### What happened?

Hey,

so when you make a flac stream and remove the mp3 stream the meta data and now playing api breaks so you have to adda mp3 stream hidden for that to work
![image](https://user-images.githubusercontent.com/100867528/187531118-4c5b320f-b510-43b8-8b70-a2e9c73e58ba.png)

**Comment by CarlTheObeseCat** [comment] 2022-08-30 20:02
^ more info here:
the api does output metadata for now playing but it wont use it.

**Comment by ItsMitchh** [comment] 2022-09-03 22:00
Flac have been a thorn in our side for a while, but I'll flag this up, thanks for the reports.

**Comment by Vaalyn** [comment] 2022-09-07 17:54
Closing as duplicate of https://github.com/AzuraCast/AzuraCast/issues/5008

Icecast does currently not support metadata in `ogg/flac` or `ogg/opus` streams which is why this is breaking.

**Closed by Vaalyn** 2022-09-07 17:54 UTC
Labels: bug, rolling-release, api
