### ISSUE TITLE
DJ / Streamer Buged 

### ISSUE THREAD

**Issue by Samh629** [AzuraCast/AzuraCast#3655] opened 2021-01-11 17:26 UTC
**Using Docker installation method**
Yes

**AzuraCast version** 
This information can be located within the footer of your AzuraCast installation - Rolling Release #cca4592 (2021-01-11 13:09)

**Host Operating System**

**Expected behavior**

**Relevant Logs**
2021/01/11 17:11:59 [simulator_fm_safe_fallback:3] Switch to compress_7856 with transition.
2021/01/11 17:11:59 [simulator_fm_live_fallback:3] Switch to cross_7822.
2021/01/11 17:11:59 [simulator_fm_requests_fallback:3] Switch to simulator_fm_autodj_fallback.
2021/01/11 17:11:59 [simulator_fm_autodj_fallback:3] Switch to fallback_7795.
2021/01/11 17:11:59 [fallback_7795:3] Switch to delay_7794.
2021/01/11 17:11:59 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/simulator_fm/media/Power Intos/lizzo_-_juice_-28sfm_power_intro-29.mp3".
2021/01/11 17:11:59 [lang:3] AzuraCast Feedback Response: 
2021/01/11 17:12:02 [lang:3] Authenticating DJ: test
2021/01/11 17:12:02 [lang:3] AzuraCast DJ Auth Response: 
2021/01/11 17:13:25 [lang:3] Authenticating DJ: test
2021/01/11 17:13:25 [lang:3] AzuraCast DJ Auth Response: Error: Cannot check permission with no user set. on /var/azuracast/www/src/Acl.php L136
2021/01/11 17:14:53 [playlist_beatmix:3] Prepared "/var/azuracast/stations/simulator_fm/media/beatmixs/giant_dontfeellikecrying_hellomylove_id.mp3" (RID 6).
2021/01/11 17:14:53 [playlist_simulator_fm_main:3] Prepared "/var/azuracast/stations/simulator_fm/media/Main Songs/25 - Jonas Brothers - Sucker.mp3" (RID 9).
2021/01/11 17:14:53 [fallback_7795:3] Switch to rotate_7790 with forgetful transition.
2021/01/11 17:14:53 [rotate_7790:3] Switch to cue_playlist_beatmix.
2021/01/11 17:14:53 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/simulator_fm/media/beatmixs/thankunext_dancingwithastranger_dontcallmeup_id.mp3".
2021/01/11 17:14:53 [cross_7822:3] Analysis: -81.491510dB / -12.405768dB (2.97s / 2.99s)
2021/01/11 17:14:53 [crossfade:3] No transition: using default.
2021/01/11 17:14:53 [lang:3] AzuraCast Raw Response: Error: Cannot check permission with no user set. on /var/azuracast/www/src/Acl.php L136
2021/01/11 17:14:53 [lang:3] AzuraCast Feedback Response: Error: Cannot check permission with no user set. on /var/azuracast/www/src/Acl.php L136
2021/01/11 17:15:27 [playlist_beatmix:3] Prepared "/var/azuracast/stations/simulator_fm/media/beatmixs/thankunext_dancingwithastranger_dontcallmeup_id.mp3" (RID 11).
2021/01/11 17:15:27 [rotate_7790:3] Switch to simulator_fm_schedule_switch with forgetful transition.
2021/01/11 17:15:27 [simulator_fm_schedule_switch:3] Switch to simulator_fm_standard_playlists.
2021/01/11 17:15:27 [simulator_fm_standard_playlists:3] Switch to cue_playlist_simulator_fm_main.
2021/01/11 17:15:27 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/simulator_fm/media/Main Songs/Ti\195\171sto - Adagio For Strings.mp3".
2021/01/11 17:15:28 [cross_7822:3] Analysis: -20.374248dB / -16.795696dB (2.98s / 3.02s)
2021/01/11 17:15:28 [crossfade:3] No transition: using default.
2021/01/11 17:15:28 [lang:3] AzuraCast Raw Response: Error: Cannot check permission with no user set. on /var/azuracast/www/src/Acl.php L136
2021/01/11 17:15:31 [lang:3] AzuraCast Feedback Response: Error: Cannot check permission with no user set. on /var/azuracast/www/src/Acl.php L136
2021/01/11 17:15:48 [server:3] New client: 172.18.0.6.
2021/01/11 17:15:48 [lang:3] DJ Source disconnected! Current live DJ: 
2021/01/11 17:15:48 [lang:3] AzuraCast Live Disconnected Response: Error: Cannot check permission with no user set. on /var/azuracast/www/src/Acl.php L136
2021/01/11 17:15:48 [server:3] Client 172.18.0.6 disconnected.

**Screenshots**

**Device(s):**
 - Device:  Desktop
 - OS: Windows
 - Browser: chrome>
 - Version: n/a

**Comment by Samh629** [comment] 2021-01-11 17:29
![Uploading unknown.png…]()

**Comment by smilingpeanut** [comment] 2021-01-11 17:33
Duplicate of #3653 .

**Comment by Vaalyn** [comment] 2021-01-11 21:28
Closing as duplicate

**Closed by Vaalyn** 2021-01-11 21:28 UTC
Labels: duplicate
