### ISSUE TITLE
Stream Offline and no metadata displayed for Live streamer 

### ISSUE THREAD

**Issue by jackerman426** [AzuraCast/AzuraCast#3568] opened 2020-12-15 21:04 UTC
**Using Docker installation method**
Yes

**AzuraCast version**
v0.11.1 Stable • Docker • PHP 7.4

**Host Operating System**
Ubuntu 20.04

**Describe the bug**
When some DJ streamers starts streaming to the server from MIXXX, Azuracast does not receive the metadata of the streamer. The API reports that the user is not live and the front end profile reports Now Playing as Stream Offline, the audio is normally broadcasted as expected. This happens to only certain streamers and not all of them. They both have mac version of mixxx but on the other hand others also use mac and we never experience this issue. For some reason after 1 2 songs or sometimes immediately no metadata are sent to azura and it displays as stream offline.
Liquidsoap icecast issue maybe?

**To Reproduce**

**Expected behavior**
It should display the streamer name and the song metadata

**Relevant Logs**
2020/12/15 21:59:22 [lang:3] AzuraCast DJ Auth Response: true
2020/12/15 21:59:22 [decoder:3] Method "MAD" accepted "audio/mpeg".
2020/12/15 21:59:22 [lang:3] DJ Source connected! Last authenticated DJ: stafot - [("Authorization", "Basic c3RhZm90OnN0YWZvdDEzMTI="), ("Host", "radio.avlikos.gr:8005"), ("User-Agent", "libshout/2.4.1"), ("Content-Type", "audio/mpeg"), ("ice-public", "1"), ("ice-name", " "), ("ice-description", "This stream is online for testing purposes!"), ("ice-genre", "Live Mix"), ("ice-url", "https://www.mixxx.org"), ("ice-irc", " "), ("ice-aim", " "), ("ice-icq", " "), ("ice-audio-info", "bitrate=128")]
2020/12/15 21:59:22 [server:3] New client: 172.18.0.3.
2020/12/15 21:59:22 [server:3] Client 172.18.0.3 disconnected.
2020/12/15 21:59:22 [lang:3] AzuraCast Live Connected Response: recording
2020/12/15 21:59:22 [avlikos_input_streamer:3] Decoding...
2020/12/15 21:59:25 [lang:3] Authenticating DJ: stafot
2020/12/15 21:59:25 [lang:3] AzuraCast DJ Auth Response: true
2020/12/15 21:59:25 [avlikos_input_streamer:3] New metadata chunk ? --  - ??????? - ?? Express ??? ?????? _ Maskes - To Express Tou Notou (Official Audio Video)-possEkV4_ro.
2020/12/15 21:59:32 [avlikos_live_fallback:3] Switch to audio_to_stereo_8168 with transition.
2020/12/15 22:02:15 [lang:3] Authenticating DJ: stafot
2020/12/15 22:02:15 [lang:3] AzuraCast DJ Auth Response: true
2020/12/15 22:02:15 [avlikos_input_streamer:3] New metadata chunk ? --  - .
2020/12/15 22:06:40 [lang:3] Authenticating DJ: stafot
2020/12/15 22:06:40 [lang:3] AzuraCast DJ Auth Response: true
2020/12/15 22:06:40 [avlikos_input_streamer:3] New metadata chunk ? --  - .```
......

**Screenshots**
![Screenshot 2020-12-15 at 22 57 13](https://user-images.githubusercontent.com/2330996/102272180-a7b39680-3f20-11eb-962e-ff7303d7727b.png)

**Device(s):**
 - OS: Mac OS Big Sur
 - Mixxx 2.3 beta

**Comment by Vaalyn** [comment] 2020-12-15 21:25
This looks like 

This looks quite odd to me:
```
New metadata chunk ? -- - ??????? - ?? Express ??? ?????? _ Maskes - To Express Tou Notou (Official Audio Video)-possEkV4_ro.

New metadata chunk ? -- - .

New metadata chunk ? -- - .```
```

Would you mind sending me the files for that at vaalyndev@gmail.com so I can test it on my Mac with Mixxx?
It looks like this might be related to issue with the audio files themself.

**Comment by mtzakris** [comment] 2020-12-16 07:26
Yes indeed its odd. I can send you the files but we have tested that and its not related to the files. This happens only to two particular streamers streaming from mixxx - mac. But the combination itself is not enough since other users can normally stream without this issue.
Could it be the case that the internet connection is unstable-low and a sudden drop could lead to this?

**Comment by Vaalyn** [comment] 2020-12-16 08:10
Well I'm not sure what is causing this but as you can see from the log lines that I mentioned AzuraCast receives very strange metadata. If that's due to a connection problem, broken metadata in files, wrongly configured Mixxx, etc... I don't really know. I'm asking for the file/s to test if those might have something to do with it or not so that we can try to narrow it down a bit.

Can you also find out which Mixxx version they are using exactly so I can try reproducing it with the same version?

**Comment by mtzakris** [comment] 2020-12-16 12:21
Hello @Vaalyn we have investigated further and we saw that the cause of the issue is the Mixxx 2.3 beta of Mac OS. When users downgraded to the lts Mixxx 2.2.3 or 2.2.4 the metadata are displayed correctly.
Also I noticed that the Mixxx removed the beta download of their listings https://downloads.mixxx.org/

**Comment by jackerman426** [comment] 2020-12-16 13:46
We found the bug. 
In Mixxx 2.3 beta when you try to load a music library the metadata of the songs are not loaded at all. This causes azuracast to not be able to display the data and thus display Stream Offline.

**Comment by Vaalyn** [comment] 2020-12-16 22:50
Good to hear that you've found out why this was happening.

Since this was only occurring in a beta version of Mixxx (which is now not available on the download page) I'll close this issue.
When Mixxx 2.3 is released and this issue still exists please let us know.

**Closed by Vaalyn** 2020-12-16 22:50 UTC
Labels: upstream
