### ISSUE TITLE
Deleting songs often does not work the first time

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#3117] opened 2020-08-26 10:02 UTC
**Using Docker installation method**

**AzuraCast version**
v0.10.3, #ffa6d6b (2020-07-15 8:00) Rolling

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
When trying to delete especially multiple songs or a directory with multiple songs from "music files",  after the "applying delede" massage,  nothing happens
Sometimes it is necessary to click on "Delete" several times until it's completely deleted.

**Comment by SlvrEagle23** [comment] 2020-08-27 02:40
@eranwo We need some more information on the specifics of your setup.

Are you sharing the directory with other stations? Do you see any error messages in your console (usually visible by hitting F12 in a browser) or on the "Network" tab of the console? If so, you can paste those error messages here.

**Comment by SC2Mitch** [comment] 2020-08-27 13:23
I've been looking into this, and I may of found the cause, providing logs below.  Hope this is helpful for you @SlvrEagle23 

Nginx Proxy Logs
`nginx_proxy_1              | nginx.1    | crosshost.ml %%%- - [27/Aug/2020:13:20:13 +0000] "PUT /api/station/32/files/batch HTTP/2.0" 500 3233 "https://crosshost.ml/station/32/files" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36 Edg/84.0.522.63"
`
Console Log
`StationMedia-89ddf53795.js:1 Error: Request failed with status code 500
`

Full raw error 
```
Error: Request failed with status code 500
    at e.exports (vendor-4f4c72221a.js:1)
    at e.exports (vendor-4f4c72221a.js:1)
    at XMLHttpRequest.a.onreadystatechange (vendor-4f4c72221a.js:1)

```
&&
```
PUT https://crosshost.ml/api/station/32/files/batch ERR 500
(anonymous) @ vendor-4f4c72221a.js:1
e.exports @ vendor-4f4c72221a.js:1
e.exports @ vendor-4f4c72221a.js:1
Promise.then (async)
s.request @ vendor-4f4c72221a.js:1
s.<computed> @ vendor-4f4c72221a.js:1
(anonymous) @ vendor-4f4c72221a.js:1
doBatch @ StationMedia-89ddf53795.js:1
(anonymous) @ StationMedia-89ddf53795.js:1
Promise.then (async)
doDelete @ StationMedia-89ddf53795.js:1
He @ vue-fb19233884.min.js:6
n @ vue-fb19233884.min.js:6
Yr.o._wrapper @ vue-fb19233884.min.js:6

```

**Comment by SlvrEagle23** [comment] 2020-08-29 01:42
@SC2Mitch That is helpful, but I need the actual error message from the web application that triggers that 500 error message. It would either be in the "Network" field (by clicking the red 500 request and then clicking the "Response"), or in the server logs via `docker-compose logs -f web`.

**Comment by SC2Mitch** [comment] 2020-08-29 01:55
On it. 

```
A new entity was found through the relationship 'App\Entity\StationPlaylistMedia#media' that was not configured to cascade persist operations for entity: StationMedia e1790d61370c5b32909cd9b3: -5Bmv-5D -E1-84-92-E1-85-AA-E1-84-89-E1-85-A1 -28hwa sa-29 - -E1-84-86-E1-85-A1-E1-84-85-E1-85-B5-E1-84-8B-E1-85-A1 -28maria - 29. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}).
ORMInvalidArgumentException.php : 102

```

**Comment by SlvrEagle23** [comment] 2020-08-29 04:48
@eranwo @SC2Mitch Should be helped by latest commit.

**Comment by SC2Mitch** [comment] 2020-08-29 22:12
Errors are still being thrown, trying to trace the error code down.

**Comment by FiloSpaTeam** [comment] 2020-10-06 12:44
AzuraCast v0.10.4 #28fd48c (2020-10-02 3:21)

```ERROR: A new entity was found through the relationship 'App\Entity\StationPlaylistMedia#media' that was not configured to cascade persist operations for entity: StationMedia b3fb7e454c3d69199cb48dc4: Julien e Paolo - #UnitooCast: Scientificast - Repellenti per ignobel. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}). {"file":"/var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php","line":102,"code":0} []```

**Comment by SlvrEagle23** [comment] 2020-10-09 03:13
@FiloSpaTeam Please update to the latest rolling release version and verify that this issue is still happening; it should be fixed due to changes we've made in how we process media deletion.

**Comment by Vaalyn** [comment] 2021-04-20 13:31
Closing this issue as resolved since there have been no recent reports of this problem happening.

**Closed by Vaalyn** 2021-04-20 13:31 UTC
Labels: bug
