### ISSUE TITLE
Playlists with remote stream URLs constantly eat up a listener slot at the remote

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6096] opened 2023-02-20 06:21 UTC
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #f38c25b (2023-02-17 10:48)

### What happened?

This _is_ probably intended (due to a known LiquidSoap problem), but a nuisance nevertheless: If you set up several playlists with remote stream URLs, for syndication of shows or news from other services, each "eats up" a listener slot at the remote, appearing to be listening at the remote end 24 hours a day, 7 days a week.

Let’s say I wish to syndicate news, or, in my case, three 2-hour-shows a week from a friend’s station, I’d have 4 streams listening the whole time, totally messing up the other station’s statistics and getting complaints. This was actually brought up to me by a partner station who complained about that my LiquidSoap was "listening" 24/7 while only supposed to take over a 2-hour show. Besides, it’s eating up valuable bandwidth.

I’m totally aware that this is in essence a workaround for an upstream bug, but couldn’t another way be found to handle this in order to avoid complaints? Maybe like setting up the stream only a few minutes before the actual starting time (if it was a time-scheduled playlist), and dropping it afterwards?

Besides, I couldn’t yet make time-scheduled remote stream playlists work… :-(

_Not too high priority, but you might get complaints from partner stations or media providers._

**Comment by BusterNeece** [comment] 2023-02-20 06:33
Closing as upstream; there is nothing at all we can do about this issue, and it is likely completely by design by virtue of the way remote URL playlists work.

**Closed by BusterNeece** 2023-02-20 06:33 UTC
Labels: needs investigation

**Comment by amacleod457** [comment] 2023-02-20 07:01
In Azuracast, create a secondary station, with only a looped message, stating that the current stream is unavailable.
On the production station, create the remote URL schedules as you would for the times you want to retransmit other sources, but set it up to pull from the secondary station.
It can eat bandwidth and waste a few CPU cycles 24/7 on the local machine without bothering anyone.
Then, install mpg123 or mpg321 and Ices0 or EZStream or something simple.
Fire up the simple streamer.
Write a BASH script that calls timeout 7200 mpg123 -q <URL>
where <URL> is the remote station you actually want to broadcast, and 7200 is the number of seconds you want to be connected and pulling data from the actual remote station.
You'll want to also feed the output from mpg123 to the Ices0 or EZstream program through a tee pipe or something.
Then when you want to bring up the remote stream, mpg123 will connect there, when and only it is needed. The timeout will drop it when desired. The first Azuracast station will eat bandwidth and CPU all day listening to the second station's error loop, until EZStream or Ices0 connects to it and feeds it the output from mpg123.

Sorry this isn't all that detailed, but I figured I'd throw something together since it appears this  seems not getting addressed anytime soon.

**Comment by Moonbase59** [comment] 2023-02-20 10:09
Thanks for the creative input, @amacleod457 :-)

I’ll probably run along with some such construct, or look up how I did it in the "olden times" and set something up in the VM but outside of the Docker.

I can understand @BusterNeece closing this since it’s an upstream problem and one simply can’t fix everyone else’s bugs. Nevertheless, syndication is often used in real stations, and making a "hackfest" out of it cannot be what end-users want and need.

**Comment by BusterNeece** [comment] 2023-02-20 10:11
As a note, if you're able to run this up the ladder to Liquidsoap, and they tell you that AzuraCast has been doing it wrong in our config and how to fix it...by all means, we'll update our config ASAP. I'm just not aware of having been notified of that so far.

**Comment by Moonbase59** [comment] 2023-02-20 11:05
Experience in the past shows it being hard to convince them, but let’s see… ;-) I’ll probably have to check out some of my old LiquidSoap code, and yours first.
