### ISSUE TITLE
Pink Pop-Up when saving music to any playlist

### ISSUE THREAD

**Issue by themadcap1976** [AzuraCast/AzuraCast#2195] opened 2019-12-04 20:38 UTC
Powered by AzuraCast • v0.9.8, #7fea11f (2019-12-03 0:46) • Docker • PHP 7.4

I'm getting this random pop up when saving a song to a playlist. I'm not sure why this is happening? The logs look clean. The only issue I'm having is scheduled playlists not working, all else is working.
![Screen Shot 2019-12-04 at 3 31 40 PM](https://user-images.githubusercontent.com/32073620/70179309-d95a1680-16ab-11ea-9d11-e72b44a13124.png)

**Comment by SC2Mitch** [comment] 2019-12-04 20:50
Having the same issue, it does save it to the playlist, but it doesn't return the correct string.

**Comment by eranwo** [comment] 2019-12-04 21:01
Same issue in my
see also https://github.com/AzuraCast/AzuraCast/issues/2193

**Comment by ogrenci01** [comment] 2019-12-05 10:40
Hi Everybody;

I have same issue and I am using Ansible v0.9.8 with PHP 7.2.

**Comment by lalafunn** [comment] 2019-12-05 14:39
Same issue here.

**Comment by SlvrEagle23** [comment] 2019-12-05 20:11
@themadcap1976 When you run into that error, the best way for us to diagnose it is to open your inspector console (in most browsers, it's F12), click the "Network" tab, then attempt to make the request again; you'll likely see a request that shows up in red or has a 500 error code. Click that request and view its response, and you should see an error message. Let us know what that error message says.

**Comment by SlvrEagle23** [comment] 2019-12-05 20:20
@themadcap1976 I found the cause of this issue and it should be fixed now.

**Closed by SlvrEagle23** 2019-12-05 20:20 UTC
Labels: error, needs more information
