### ISSUE TITLE
No sound output on Public Page using browser (desktop or phone) when using shoutcast broadcasting

### ISSUE THREAD

**Issue by djeokis** [AzuraCast/AzuraCast#3905] opened 2021-03-11 07:50 UTC
**Using Docker installation method**

Yes

**AzuraCast version**

v0.12.2 Stable

**Host Operating System**

Ubuntu 20.04.2 LTS 

**Describe the bug**

Updated to latest stable version of Azuracast, Under Broadcasting, it was selected under IceCast, Public Page Player works fine, When switched to ShoutCast, public Page player shows current track playing, but no audio output. Does broadcast to shoutcast, used a phone app to verify, but on web (Using Chrome Browser ) no audio output, under the Public Page.

**To Reproduce**

1. Go to '..Administration  - Stations - Edit - Broadcasting.'
2. Click on '..IceCast - save Changes - Refresh Public Page, you can hear sound -- do step 1 and select ShoutCast - save changes -
refresh Public Page, no audio.
 
**Expected behavior**

To have audio output on IceCast or Shoutcast. 

**Relevant Logs**

N/A

**Screenshots**

No Audio

**Device(s):**

- Device: Phone and Desktop
- OS: Win10 / Android ( Latest )
- Browser: Chrome, Firefox
- Version: Chrome Version 88.0.4324.190 (Official Build) (64-bit)

**Additional context**

Link for station when under Shoutcast  > https://lsradio503.com/public/latinos_songs_radio
Used XiiaLive Android app : http://lsradio503.com:8000/radio.mp3
<img width="853" alt="radioLS" src="https://user-images.githubusercontent.com/74470687/110753039-43446280-8203-11eb-9605-5fa01caa431e.png">

**Comment by SlvrEagle23** [comment] 2021-03-11 08:57
@djeokis It's possible this has something to do with the SHOUTcast licensing restrictions, i.e. you can only broadcast at 128kbps by default, and you have to input a license key for the newest version to basically work at all. We strongly recommend using Icecast wherever possible.

**Comment by YosefAdPro** [comment] 2021-03-11 09:42
@djeokis You are trying to use SHOUTcast with HTTPS, and it requires a license. work with the Web Proxy.

**Comment by djeokis** [comment] 2021-03-11 16:13
Hi. Like i mentioned before, i updated to v0.12.2, previous version worked just fine, without any issues. I have another station that has the previous version and everything still works fine. So could it be that 0.12.2 broke that setting/feature? If that were the case, how can i downgrade to previous version? Thank you for the advice and help. Very appreciated.

**Comment by SlvrEagle23** [comment] 2021-03-11 22:14
@djeokis What version were you on before upgrading to 0.12.2? We haven't made any changes lately that would affect SHOUTcast's ability to broadcast, but several months ago we started allowing direct HTTPS connections to the radio frontend ports (i.e. port 8000) since Icecast was able to reliably take advantage of the same SSL certificate that the main nginx server was using; SHOUTcast, however, charges for this functionality (for who knows what reason) and wouldn't be able to benefit from it, so you'd have to turn on the "Use Web Proxy" setting instead.

In any case, we don't officially support SHOUTcast as it's a proprietary, commercial, closed-source binary that we can't inspect or fix, so we're extremely limited in our ability to support it.

**Comment by SpeedyCharly** [comment] 2021-03-14 04:09
Looks to me like you're trying to push a Shoutcast V2 broadcast through a pipe (AzuraCast) that accepts only ShoutCast V1 streams...

**Comment by Vaalyn** [comment] 2021-04-23 17:06
Closing this issue since there haven't been any further replies and the issue seems to be caused by the licensing of ShoutCast which needs a subscription in order to use HTTPS.

For future reference, if you are using ShoutCast with the free version in order to use HTTPS you will need to activate the `Use Web Proxy` setting.

**Closed by Vaalyn** 2021-04-23 17:06 UTC
Labels: error, unsupported
