### ISSUE TITLE
Station sometimes (rarely) shows "Stream Offline" and is missing metadata even though audio is playing properly

### ISSUE THREAD

**Issue by nickrobillard** [AzuraCast/AzuraCast#2790] opened 2020-05-02 21:05 UTC
**Using Docker installation method**
Yes. Running release 0.9.6.5.

**Host Operating System**
Ubuntu 18.04

**Host Hardware Specs**
8 core Intel(R) Xeon(R) CPU @ 2.50GHz
8GB RAM
Network storage on 10G local network. HDD with 773G available disk space. (**Update**: Since this last occurred, we have moved to SSD storage.)

**Describe the bug**
Every once in a while, a station's `meta.status` will show as "offline" and the now playing API JSON `now_playing.text` will show as "Stream Offline". Other `now_playing` metadata is also missing (shown below). However, the stream audio is still playing as expected and once the current track has finished, the problem goes away and the expected metadata is even shown in song history for the track that used to show as "Stream Offline". (More details below in _Additional Context_)

**To Reproduce**
This seems to happen about once every couple weeks but there is no obvious trigger. Using Icecast 2.4 with Liquidsoap. I've looked through the github issues related to "Stream Offline" behavior and I have tried to include all things that were asked for in other issues.

**Expected behavior**
Stream meta data to appear and not show "Stream Offline".

**Relevant Logs**
Response from Now Playing cron task at `/admin/debug/sync/nowplaying`:
```
Info
Running Now Playing sync task
Debug
HTTP client GET call to http://stations:8000/admin/stats produced response 200
Debug
HTTP client GET call to http://stations:8000/admin/listclients?mount=%2Fdubandbass%2Fuhifi produced response 200
Debug
Response for mount point
mount
"\/dubandbass\/uhifi"
response
{
    "current_song": {
        "text": "",
        "artist": "",
        "title": ""
    },
    "listeners": {
        "current": 3,
        "unique": 3,
        "total": 3,
        "clients": [
            {
                "uid": "452015",
                "ip": "67.21.195.211",
                "user_agent": "Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/81.0.4044.113 Safari\/537.36",
                "connected_seconds": 3319
            },
            {
                "uid": "452279",
                "ip": "216.165.226.124",
                "user_agent": "AppleCoreMedia\/1.0.0.17D50 (iPhone; U; CPU OS 13_3_1 like Mac OS X; en_us)",
                "connected_seconds": 2038
            },
            {
                "uid": "452409",
                "ip": "37.213.137.210",
                "user_agent": "Mozilla\/5.0 (Linux; Android 10; Mi A2 Lite) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/81.0.4044.117 Mobile Safari\/537.36",
                "connected_seconds": 1516
            }
        ]
    },
    "meta": {
        "status": "offline",
        "bitrate": 256,
        "format": "audio\/mpeg"
    }
}
station
{
    "id": 1,
    "name": "Dub & Bass"
}
Debug
HTTP client GET call to http://stations:8000/admin/stats produced response 200
Debug
HTTP client GET call to http://stations:8000/admin/listclients?mount=%2Fdubandbass%2Fhifi produced response 200
...
```

liquidsoap.log
```
2020/05/02 05:10:34 [lang:3] AzuraCast Feedback Response: OK
2020/05/02 06:09:51 [lang:3] AzuraCast Raw Response: annotate:title="Badmon Radio Episode #036 w/Anthologic & SPARXY",artist="Anthologic & Sparxy",duration="7561.",song_id="5dfe357c07bcdfe2c946663795ce9d50",media_id="478",playlist_id="12":/var/azuracast/stations/dubandbass/media/badmon_radio_episode_036_w_anthologic__sparxy.mp3
2020/05/02 06:09:51 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/dubandbass/media/badmon_radio_episode_036_w_anthologic__sparxy.mp3".
2020/05/02 06:10:31 [dubandbass_next_song:3] Prepared "/var/azuracast/stations/dubandbass/media/badmon_radio_episode_036_w_anthologic__sparxy.mp3" (RID 1).
2020/05/02 06:10:31 [cross_7704:3] Analysis: -24.951057dB / -88.181301dB (2.97s / 2.99s)
2020/05/02 06:10:31 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/05/02 06:10:31 [lang:3] AzuraCast Feedback Response: OK
2020/05/02 08:15:49 [lang:3] AzuraCast Raw Response: annotate:title="Badmon Radio Episode #033 w/Anthologic & Aphotic",artist="Anthologic",duration="9102.",song_id="01aa3e1d2bca5e84eca5d93838c99b60",media_id="475",playlist_id="12":/var/azuracast/stations/dubandbass/media/badmon_radio_episode_033_w_anthologic__aphotic.mp3
2020/05/02 08:15:49 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/dubandbass/media/badmon_radio_episode_033_w_anthologic__aphotic.mp3".
2020/05/02 08:16:29 [dubandbass_next_song:3] Prepared "/var/azuracast/stations/dubandbass/media/badmon_radio_episode_033_w_anthologic__aphotic.mp3" (RID 2).
2020/05/02 08:16:29 [cross_7704:3] Analysis: -86.296056dB / -92.974719dB (2.96s / 3.00s)
2020/05/02 08:16:29 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/05/02 08:16:29 [lang:3] AzuraCast Feedback Response: OK
2020/05/02 10:47:28 [lang:3] AzuraCast Raw Response: annotate:title="the dose with niko 11.29.2016",duration="7471.",song_id="c946316e1de99f6a8ba859e13d901f1e",media_id="562",playlist_id="12":/var/azuracast/stations/dubandbass/media/the_dose_with_niko_11.29.2016.mp3
2020/05/02 10:47:28 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/dubandbass/media/the_dose_with_niko_11.29.2016.mp3".
2020/05/02 10:48:08 [dubandbass_next_song:3] Prepared "/var/azuracast/stations/dubandbass/media/the_dose_with_niko_11.29.2016.mp3" (RID 1).
2020/05/02 10:48:08 [cross_7704:3] Analysis: -88.283468dB / -77.892446dB (2.98s / 3.02s)
2020/05/02 10:48:08 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/05/02 10:48:08 [lang:3] AzuraCast Feedback Response: OK
2020/05/02 12:51:56 [lang:3] AzuraCast Raw Response: annotate:title="1N 7H3 M1X TV/Radio LIVE 20130531",artist="nonXero",duration="4206.",song_id="0a2594fec3e7eeece9a76005b085f60c",media_id="420",playlist_id="12":/var/azuracast/stations/dubandbass/media/1n7h3m1xtvlive20130531_with_nonxero_dubplate.fm_.mp3
2020/05/02 12:51:56 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/dubandbass/media/1n7h3m1xtvlive20130531_with_nonxero_dubplate.fm_.mp3".
2020/05/02 12:52:37 [dubandbass_next_song:3] Prepared "/var/azuracast/stations/dubandbass/media/1n7h3m1xtvlive20130531_with_nonxero_dubplate.fm_.mp3" (RID 2).
2020/05/02 12:52:37 [cross_7704:3] Analysis: -80.793825dB / -20.409312dB (3.00s / 3.00s)
2020/05/02 12:52:37 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/05/02 12:52:37 [lang:3] AzuraCast Feedback Response: OK
2020/05/02 14:02:00 [lang:3] AzuraCast Raw Response: annotate:title="the dose with niko 10.25.2016",duration="7286.",song_id="1c0e9f21743016b24882fa51202d5702",media_id="560",playlist_id="12":/var/azuracast/stations/dubandbass/media/the_dose_with_niko_10.25.2016.mp3
2020/05/02 14:02:00 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/dubandbass/media/the_dose_with_niko_10.25.2016.mp3".
2020/05/02 14:02:40 [dubandbass_next_song:3] Prepared "/var/azuracast/stations/dubandbass/media/the_dose_with_niko_10.25.2016.mp3" (RID 1).
2020/05/02 14:02:40 [cross_7704:3] Analysis: -72.754528dB / -28.234054dB (2.98s / 3.02s)
2020/05/02 14:02:40 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/05/02 14:02:40 [lang:3] AzuraCast Feedback Response: OK
2020/05/02 14:02:54 [clock.wallclock_main:2] We must catchup 10.67 seconds!
2020/05/02 14:02:54 [dubandbass_local_1:2] Error while sending data: could not write data to host: Broken pipe in write()!
2020/05/02 14:02:54 [dubandbass_local_1:3] Closing connection...
2020/05/02 14:02:54 [dubandbass_local_1:3] Will try to reconnect in 3.00 seconds.
2020/05/02 14:02:54 [dubandbass_local_2:2] Error while sending data: could not write data to host: Broken pipe in write()!
2020/05/02 14:02:54 [dubandbass_local_2:3] Closing connection...
2020/05/02 14:02:54 [dubandbass_local_2:3] Will try to reconnect in 3.00 seconds.
2020/05/02 14:02:54 [dubandbass_local_3:2] Error while sending data: could not write data to host: Broken pipe in write()!
2020/05/02 14:02:54 [dubandbass_local_3:3] Closing connection...
2020/05/02 14:02:54 [dubandbass_local_3:3] Will try to reconnect in 3.00 seconds.
2020/05/02 14:02:58 [dubandbass_local_3:3] Connecting mount /dubandbass/lofi for source@127.0.0.1...
2020/05/02 14:02:58 [dubandbass_local_3:3] Connection setup was successful.
2020/05/02 14:02:58 [dubandbass_local_2:3] Connecting mount /dubandbass/hifi for source@127.0.0.1...
2020/05/02 14:02:58 [dubandbass_local_2:3] Connection setup was successful.
2020/05/02 14:02:58 [dubandbass_local_1:3] Connecting mount /dubandbass/uhifi for source@127.0.0.1...
2020/05/02 14:02:58 [dubandbass_local_1:3] Connection setup was successful.
```

`/api/nowplaying` json:
```
"now_playing": {
      "elapsed": 1588445609,
      "remaining": 0,
      "sh_id": 0,
      "played_at": 0,
      "duration": 0,
      "playlist": null,
      "streamer": null,
      "is_request": false,
      "song": {
        "id": "7a1230502efebe8990578f71285bcf46",
        "text": "Stream Offline",
        "artist": "",
        "title": "",
        "album": "",
        "lyrics": "",
        "art": "https://xyz.fm/static/img/generic_song.jpg",
        "custom_fields": [
          
        ]
      }
    },
```

Icecast's `status-json.xsl` (notice there is no "title"):
```
{
   "icestats":{
      "admin":"icemaster@localhost",
      "banned_IPs":0,
      "build":"29-g487146b",
      "host":"xyz.fm",
      "location":"AzuraCast",
      "outgoing_kbitrate":875,
      "server_id":"Icecast 2.4.0-kh10-ac4",
      "server_start":"09/Apr/2020:12:15:38 -0400",
      "stream_kbytes_read":124735391,
      "stream_kbytes_sent":244267500,
      "source":[
         {
            "audio_info":"channels=2;samplerate=44100;bitrate=192",
            "bitrate":192,
            "connected":2175,
            "genre":140,
            "incoming_bitrate":195344,
            "listener_peak":2,
            "listeners":2,
            "listenurl":"http://xyz.fm:8000/dubandbass/hifi",
            "outgoing_kbitrate":376,
            "queue_size":90279,
            "server_name":"Dub & Bass",
            "server_type":"audio/mpeg",
            "server_url":"https://xyz.fm",
            "stream_start":"02/May/2020:14:02:58 -0400",
            "total_mbytes_sent":99,
            "dummy":null
         },
         {
            "audio_info":"channels=2;samplerate=44100;bitrate=64",
            "bitrate":64,
            "connected":2175,
            "genre":140,
            "incoming_bitrate":65152,
            "listener_peak":0,
            "listeners":0,
            "listenurl":"http://xyz.fm:8000/dubandbass/lofi",
            "outgoing_kbitrate":0,
            "queue_size":65201,
            "server_name":"Dub & Bass",
            "server_type":"audio/mpeg",
            "server_url":"https://xyz.fm",
            "stream_start":"02/May/2020:14:02:58 -0400",
            "total_mbytes_sent":0,
            "dummy":null
         },
         {
            "audio_info":"channels=2;samplerate=44100;bitrate=256",
            "bitrate":256,
            "connected":2175,
            "genre":140,
            "incoming_bitrate":260376,
            "listener_peak":2,
            "listeners":2,
            "listenurl":"http://xyz.fm:8000/dubandbass/uhifi",
            "outgoing_kbitrate":499,
            "queue_size":95295,
            "server_name":"Dub & Bass",
            "server_type":"audio/mpeg",
            "server_url":"https://xyz.fm",
            "stream_start":"02/May/2020:14:02:58 -0400",
            "total_mbytes_sent":131,
            "dummy":null
         }
      ]
   }
}
```

**Screenshots**
<img width="974" alt="Screen Shot 2020-05-02 at 12 31 06 PM" src="https://user-images.githubusercontent.com/135516/80890791-7a0d2c00-8c74-11ea-9083-ee11176f1cc4.png">
<img width="649" alt="Screen Shot 2020-05-02 at 12 31 35 PM" src="https://user-images.githubusercontent.com/135516/80890793-7b3e5900-8c74-11ea-915a-49c8f78055a4.png">

**Additional context**
As you can see in liquidsoap.log, the track that seems to have triggered this "the_dose_with_niko_10.25.2016.mp3" has no artist or title id3 information - the "title" was derived from the file name.
It's possible this is related to #2737 although I do have many tracks with empty title/artist where the "text" looks like ` - Title based off filename`. Note that once this track has finished, the problem is resolved, with all metadata for the new track appearing properly. Very interestingly, at this point, the song history now shows the correct metadata for the previous track that used to show as "Stream Offline":
```
"song_history": [
      {
        "sh_id": 59856,
        "played_at": 1588442580,
        "duration": 7286,
        "playlist": "default",
        "streamer": "",
        "is_request": false,
        "song": {
          "id": "1c0e9f21743016b24882fa51202d5702",
          "text": " - the dose with niko 10.25.2016",
          "artist": "",
          "title": "the dose with niko 10.25.2016",
          "album": "",
          "lyrics": "",
          "art": "https://xyz.fm/static/img/generic_song.jpg",
          "custom_fields": [
            
          ]
        }
      },
```

**I feel bad for adding another issue to the queue and I would like to say a huge THANK YOU to Buster and those who help! I am happy to jump into code to help with this issue - I have my local environment setup. It's not clear to me where to start on this one so I'm hoping that the info provided (and more if necessary) can help pin down the issue or at least provide some hints. Feel free to ping me on Slack.**

**Comment by Abqehebter** [comment] 2021-01-02 20:33
I kind of have the same problem right now. It only occurs with the local Icecast, the relay seems to work according to the log.

Using Docker installation method: Yes.
Host Operating System: Debian 9
Version: Rolling Release #7d927b8 (2020-12-14 22:39)

**Comment by themadcap1976** [comment] 2021-02-27 03:09
I show this when a streamer/dj account connects 

![Screen Shot 2021-02-26 at 10 07 43 PM](https://user-images.githubusercontent.com/32073620/109373813-1f863180-787f-11eb-8e2d-6740525156e8.png)

**Comment by patrickvdhoek** [comment] 2022-08-02 09:54
Same problem here, in 2022 :-)

**Comment by ivellios1988** [comment] 2023-03-26 14:14
Same problem here, in 2023 ;-)

**Comment by BusterNeece** [comment] 2023-03-26 14:40
> Same problem here, in 2023 ;-)

You honestly couldn't post a _worse_ reply in a GitHub issue. Not only does it provide _absolutely no_ information about what you're experiencing in particular, or logs to help us diagnose things, or literally any supporting information whatsoever, but it has that fun undertone of berating us for having not fixed something in a few years, when there is absolutely every possibility in the world that the issue you're experiencing is NOT caused by the same thing that was causing it in 2020's AzuraCast. We wouldn't know that, of course, as you've provided us nothing. The Now Playing components have been _heavily_ modified in that time.

Closing this issue. Feel free to fire up a new one if you're able to back it with logs, documentation and specific examples.

**Closed by BusterNeece** 2023-03-26 14:40 UTC
Labels: bug, in progress, stable

**Comment by Citizen3rased** [comment] 2023-07-21 06:03
Same problem here
