### ISSUE TITLE
Remote URL Playlists - This source may control its own latency and cannot be used with this operator.

### ISSUE THREAD

**Issue by simpsss** [AzuraCast/AzuraCast#4770] opened 2021-11-09 15:32 UTC
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #4cbb9dd (2021-11-08 10:29)

### What happened?

New installation.

### Relevant log output

```shell
Error 6: Cannot apply that parameter because the function at /var/azuracast/stations/groover_demo/config/liquidsoap.liq, line 28, char 26-37
has no argument labeled "max"!
At /var/azuracast/stations/groover_demo/config/liquidsoap.liq, line 28, char 41-44:
Error 6: Cannot apply that parameter because the function at /var/azuracast/stations/groover_demo/config/liquidsoap.liq, line 28, char 26-37
has no argument labeled "max"!
At /var/azuracast/stations/groover_demo/config/liquidsoap.liq, line 28, char 41-44:
Error 6: Cannot apply that parameter because the function at /var/azuracast/stations/groover_demo/config/liquidsoap.liq, line 28, char 26-37
has no argument labeled "max"!
At /var/azuracast/stations/groover_demo/config/liquidsoap.liq, line 28, char 41-44:
Error 6: Cannot apply that parameter because the function at /var/azuracast/stations/groover_demo/config/liquidsoap.liq, line 28, char 26-37
has no argument labeled "max"!
At /var/azuracast/stations/groover_demo/config/liquidsoap.liq, line 28, char 41-44:
Error 6: Cannot apply that parameter because the function at /var/azuracast/stations/groover_demo/config/liquidsoap.liq, line 28, char 26-37
has no argument labeled "max"!
```

**Comment by simpsss** [comment] 2021-11-09 15:32
line 28:

playlist_groover = mksafe(input.http(max=35., "http://185.33.21.112/crock_32a"))

**Comment by Abqehebter** [comment] 2021-11-09 15:33
Duplicate of: https://github.com/AzuraCast/AzuraCast/issues/4761
The bug should be fixed in the latest rolling release version. See commit: https://github.com/AzuraCast/AzuraCast/commit/550054916f03ecfc7a7b1bfe5655e433d52fe2aa

**Comment by simpsss** [comment] 2021-11-09 15:40
updated!

Error 7: Invalid value:
This source may control its own latency and cannot be used with this operator.
At /var/azuracast/.opam/4.12.0/lib/liquidsoap/share/liquidsoap/git/43aa734d/libs/source.liq, line 1 char 0 - line 28 char 85:
Error 7: Invalid value:
This source may control its own latency and cannot be used with this operator.
At /var/azuracast/.opam/4.12.0/lib/liquidsoap/share/liquidsoap/git/43aa734d/libs/source.liq, line 1 char 0 - line 28 char 85:
Error 7: Invalid value:
This source may control its own latency and cannot be used with this operator.
At /var/azuracast/.opam/4.12.0/lib/liquidsoap/share/liquidsoap/git/43aa734d/libs/source.liq, line 1 char 0 - line 28 char 85:
Error 7: Invalid value:
This source may control its own latency and cannot be used with this operator.

**Comment by Abqehebter** [comment] 2021-11-09 15:42
I'll check the whole thing out for myself. Thanks for the feedback.

**Comment by SC2Mitch** [comment] 2021-11-09 16:33
flagged up to be investigated by the team thx for reports.

**Comment by Vaalyn** [comment] 2021-11-09 17:10
Seems to be something on the LS side that's causing this and I'm not sure how to work around this yet.

I have created an[ issue on the LS GH repo](https://github.com/savonet/liquidsoap/issues/2051) and will get this figured out.

**Comment by nunotfc** [comment] 2021-11-09 20:31
how to deactivate this? all my radio is stoped, i think because this error. cant go live or auto dj. stream is offline and in log the same errors. when ig o to the stream url says that this link cannot be found.

**Comment by Vaalyn** [comment] 2021-11-13 11:46
Hey, could you check if the error is resolved for you with the latest update?

**Comment by nunotfc** [comment] 2021-11-13 12:28
for me no. with url playlists enabled same error
This source may control its own latency and cannot be used with this operator.
the error apears to be different the lines and etc.
At /var/azuracast/.opam/4.12.0/lib/liquidsoap/share/liquidsoap/git/43aa734d/libs/switches.liq, line 1 char 0 - line 141 char 82:
Error 7: Invalid value:

**Comment by Vaalyn** [comment] 2021-11-13 14:25
Could you check with this update again?
I have added a buffer in the LS config for remote streams that has fixed this in my test installation.

**Comment by nunotfc** [comment] 2021-11-13 14:27
now fixed. but remote urls doesnt play.

**Comment by nunotfc** [comment] 2021-11-13 14:47
sorry. im managed it. but still buggy. it doesnt play when stop oter songs is checked in advensed. and when you restart radio with scheduled stream playlist active. keeps stream offline. but if you uncheck otpin, letr play 1 or 2 songs auto dj, the radio works.

**Comment by simpsss** [comment] 2021-11-13 20:46
Hello!

YESSS, working now, thanks!!

**Comment by SC2Mitch** [comment] 2021-11-13 22:18
fixed as per OP, closed

**Closed by SC2Mitch** 2021-11-13 22:18 UTC
Labels: bug, in progress, upstream, rolling-release, Liquidsoap 2.0
