### ISSUE TITLE
Cannot start auto dj (urgent)

### ISSUE THREAD

**Issue by TechComputerServiceDunkerque** [AzuraCast/AzuraCast#2717] opened 2020-04-22 09:42 UTC
we reset our server because we had an error with the auto dj, and then after making the last updates, the problem came back and we can't broadcast anything anymore, it's quite urgent, we are a professional radio and we are annoyed by this problem: here are the error messages we get every time:

Liquidsoap a rencontré une erreur
Re-raised at file "lang/lang_errors.ml", line 155, characters 48-55
Called from file "lang/lang.ml", line 671, characters 8-163
Called from file "lang/lang.ml", line 678, characters 4-76
Called from file "main.ml", line 125, characters 34-40
Called from file "main.ml", line 668, characters 6-16
Called from file "runner.ml", line 30, characters 14-31

I did a Debug:
Error
NowPlaying adapter error: Request returned status 400: <b>mount does not exist</b>

We are running dockerized instance on a VPS with debian 9.

**Comment by SlvrEagle23** [comment] 2020-04-23 21:21
@TechComputerServiceDunkerque I believe this may be caused by savonet/liquidsoap#1108 which has been fixed by the Liquidsoap team and is pending a 1.4.2 version release so that we can update to it on our installations.

**Comment by SlvrEagle23** [comment] 2020-04-23 21:23
@TechComputerServiceDunkerque You may want to follow that thread for instructions on how to work around the issue. It appears it's caused partly by too many playlists being present. Disabling some playlists and restarting your station _may_ fix the issue in the meantime.

**Comment by SlvrEagle23** [comment] 2020-05-03 19:00
@TechComputerServiceDunkerque Today we updated our Docker images to include the latest version of Liquidsoap (1.4.2) which should completely fix this error.

Please update your installation and let us know if the issue persists.

**Closed by SlvrEagle23** 2020-05-03 19:00 UTC
Labels: error, in progress, upstream
