### ISSUE TITLE
Public Page Metadata not updating.

### ISSUE THREAD

**Issue by NotifiedGaming** [AzuraCast/AzuraCast#1820] opened 2019-08-05 19:49 UTC
Hey there. 
So in the public page, the player, when first loaded will show the current time the song is at and its correct meta. But when it gets to the end as seen here:
![image](https://user-images.githubusercontent.com/20782042/62490739-fc3df200-b7c1-11e9-8f50-9e4be50fab9a.png)
the song metadata doesn't update. This happens in my embeds too. 

Any advice on what's wrong/how to fix it? 

F12 console doesn't show any errors on chrome.

**Comment by SlvrEagle23** [comment] 2019-08-05 19:50
@NotifiedGaming Check the "Network" tab on Chrome. It should either be hitting a websocket or the standard API, but you should see an ongoing connection. If it's just showing the initial nowplaying information, then that connection failed for some reason.

**Comment by NotifiedGaming** [comment] 2019-08-05 19:52
I'm not sure what i'm looking for but here's the result.

![image](https://user-images.githubusercontent.com/20782042/62491092-ed0b7400-b7c2-11e9-8f14-3f845d5a724b.png)

**Comment by SlvrEagle23** [comment] 2019-08-05 19:58
@NotifiedGaming Click the one that says "websocket" in its type column, and look to see if there are any frames.

If not, make sure your Now Playing sync task is running properly. You can do so by visiting the system administration and clicking "Run Task" on the leftmost task at the bottom of the page.

**Comment by NotifiedGaming** [comment] 2019-08-05 20:00
How do I see if a frame has been made?

![image](https://user-images.githubusercontent.com/20782042/62491494-ffd27880-b7c3-11e9-842a-445a1c9fd690.png)

**Comment by NotifiedGaming** [comment] 2019-08-05 20:03
Further note- 
The task is running fine.

`Response for mount point
mount
"\/radio.mp3"
response
{
    "current_song": {
        "artist": "Bananarama",
        "title": "I Want You Back",
        "text": "Bananarama - I Want You Back"`
is the correct song playing right now.

**Comment by SlvrEagle23** [comment] 2019-08-05 20:05
@NotifiedGaming It's in the "messages" tab there. You should see a list of updates being received from the server; if not, there's likely some connection issue.

**Comment by SlvrEagle23** [comment] 2019-08-05 20:05
@NotifiedGaming Also, are you on the very latest AzuraCast as of the last few hours? I pushed out a minor fix that may have helped with that issue in some cases.

**Comment by NotifiedGaming** [comment] 2019-08-05 20:07
I acknowledged the update, but have not updated it considering the instance was installed yesterday. As for the messages, there is none. (Empty)

**Comment by SlvrEagle23** [comment] 2019-08-05 20:09
@NotifiedGaming You should update to the latest version of AzuraCast as of today. We are working every day to fix bugs like this and it may already be fixed by that update.

This also may be a duplicate of #1814 but we'll have to see.

**Comment by NotifiedGaming** [comment] 2019-08-05 20:11
Updating this second. I did read that before creating an issue, but don't really seem like a correlation. I don't believe their embed was working at all? Thanks for replying straight away though :D Unique support.

**Comment by NotifiedGaming** [comment] 2019-08-05 20:13
Ok, the update has completed and now the timing bar has disappeared? 
![image](https://user-images.githubusercontent.com/20782042/62492211-d0247000-b7c5-11e9-9a5c-ca67e96f666f.png)

..will have to see if the metadata updates.

**Comment by SlvrEagle23** [comment] 2019-08-05 20:13
@NotifiedGaming That can happen with the first song after the update. It's a known issue. Give it a minute.

**Comment by NotifiedGaming** [comment] 2019-08-05 20:14
That's interesting. Anyhow that did manage to fix everything. Thanks! Once again +1 for instant replies.

**Closed** 2019-08-05 20:15 UTC
