### ISSUE TITLE
Issue on importing mp3 files (moved to not proccessed)

### ISSUE THREAD

**Issue by derkalle4** [AzuraCast/AzuraCast#191] opened 2017-07-15 09:33 UTC
I've got a problem with importing mp3 files. Much files can't be proccessed. If I try to execute the cronjob manually the following errors appear:

![error1](https://user-images.githubusercontent.com/15657782/28238316-382e2c6a-6951-11e7-989b-7d286b34958b.PNG)
![error2](https://user-images.githubusercontent.com/15657782/28238317-3830257e-6951-11e7-8fc3-ad1449e000db.PNG)

After that the mp3 files are not imported but got moved to a new folder named "not-proccessed". The MP3 files seems to contain only valid ID3-Tag values. The insert error shows an sql error (16 columns but only 15 for insert).

It's a fresh installation on a VM (Ubuntu 16.04.2 LTS) with latest updates.

Hopefully someone can help me. Thanks!

**Comment by SlvrEagle23** [comment] 2017-07-15 18:16
@derkalle4 Have you tried running the update script on the new installation? I know there may not be any code changes, but the update script also flushes the cache, ensures the database migrations are at their latest state, and fixes other such problems. Often the "number of items in query doesn't match value list" types of issue are caused by Doctrine (the database layer) having an outdated model of the database in its cache. This definitely shouldn't happen for new installations, though.

**Comment by derkalle4** [comment] 2017-07-16 07:51
Hey @SlvrEagle23 thanks for the fast help. I used the update.sh and it updated some files (commits since  Jul 14, 2017). But nevermind the problem isn't gone. I've tried to upload some MP3s again and the error will occure until I delete the mp3 file from azuracast. The error message for the song above is whyever gone over the last night. The song is actually in the database and gets played by the autoDJ Oo. Nevermind I attached you the current ID3Tags of the song and I have no idea why it now passed. The other songs of the album do not work. And I've got some other albums that don't work either. Same error.
![id3tags](https://user-images.githubusercontent.com/15657782/28245660-43a16268-6a0c-11e7-9ad7-45800d56ca83.PNG)

**Comment by ckeurk** [comment] 2017-07-19 15:46
For my part, mp3 files are no longer treated at all

**Comment by derkalle4** [comment] 2017-07-22 06:59
@ckeurk I can't see that kind of problem on my site. Only specific (but much) MP3s will fall over with the error provided aboth.

**Comment by SlvrEagle23** [comment] 2017-07-22 07:03
@derkalle4 To be clear, this is only referring to files uploaded via SFTP to the folder, correct? Files uploaded via the web uploader should be processed one-by-one, thus alleviating any such issue that might occur.

**Comment by derkalle4** [comment] 2017-07-22 07:06
@SlvrEagle23 nope that's the normal web upload for me. The files do get uploaded and I'm firing the cronjob manually to actually see the error and to have no need to wait for at least 5 minutes. It makes no difference if I execute the cronjob manually or automatically. It always gives me the error up there and moves the mp3 file to a folder called "non-processed".

Can I debug sth for you?

**Comment by SlvrEagle23** [comment] 2017-07-22 07:10
@derkalle4 Can you e-mail me a sample of the affected MP3 files? That might help me take a closer look at the issue. buster@busterneece.com

**Comment by SlvrEagle23** [comment] 2017-07-22 08:50
@derkalle4 I'm not seeing the errors, even with the files you supplied.

Out of curiosity, what browser are you using to upload the MP3 files?

Also, when you upload the files using the web uploader, do you see the progress bar fill up completely and the page reload?

The cron job should instantly return with nothing to process, as long as the mp3 file was uploaded with the web uploader.

**Comment by derkalle4** [comment] 2017-07-22 08:55
Seems strange. I normally use Vivaldi (based on Chrome) but returned to the lastest 32Bit Firefox and have the same results. The MP3s get updated. On execution of the cronjob you'll see the error mentioned above.  Attached two screenshots. Directly after the web upload the file status is not processed. After the cronjob gets called file per file gets moved to the folder not processed.
![error1](https://user-images.githubusercontent.com/15657782/28489806-5178f01c-6ecc-11e7-80a5-cc185ae68a6f.PNG)
![error2](https://user-images.githubusercontent.com/15657782/28489808-51991dba-6ecc-11e7-9626-c864ed0c3e74.PNG)

**Comment by SlvrEagle23** [comment] 2017-07-22 09:00
@derkalle4 Diagnosing this issue will likely require running the web inspector tool for your browser. Keep the "Network" tab open and run the file upload process, and it will trigger multiple chunked requests, but you may see an HTTP 500 error response, and you can send the body of that response over to me for further diagnosis.

**Comment by derkalle4** [comment] 2017-07-23 13:28
Hey @SlvrEagle23 it's a very strange issue. I just thought it could be my NGINX reverse proxy but if I didn't use it (connecting directly to your webserver that got installed via install.sh) it still has the same error. Upload is cool. Uploaded the whole album again. I don't know why, but ifI do an upload of this files sometimes a file won't "disappear" into the not-processed folder. It will stay there (with the error from the cronjob) but after some time (maybe an hour or more) the file is definately processed.

Steps I did:
- Upload a bunch of album files via your web uploader
- execute the 5 Minute Cronjob manually to force an processing of the files.

Step1 (after Upload):
![upload1](https://user-images.githubusercontent.com/15657782/28499665-41f0e380-6fbb-11e7-92be-a2000eed0456.PNG)
![error1](https://user-images.githubusercontent.com/15657782/28499667-454a8b30-6fbb-11e7-8dac-3d29d086432f.PNG)

As you can see the files are not processed and there isn't any upload error.

If I now run this "every 5 minute cronjob" then the following error will happen:

```
 Doctrine \ DBAL \ Exception \ DriverException
An exception occurred while executing 'INSERT INTO station_media (station_id, song_id, title, artist, album, isrc, length, length_text, path, mtime, fade_overlap, fade_in, fade_out, cue_in, cue_out) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [1, "c81db3b2950660c3722ebce85804d3fb", "My Ghost (Short Edit)", "Alle Farben", "Live Circus", null, 186.14857142857144, "3:06", "13-my-ghost--28short-edit-29.mp3", 1500816127, null, null, null, null, null]: SQLSTATE[21S01]: Insert value list does not match column list: 1136 Column count doesn't match value count at row 1
```

This error will happen for every songe once. At least for one song it will sometimes not disappear, even if I execute the cronjob 10 times. But after an hour or so (I don't really know) the song will added to a database.

Hopefully this will help you a little bit.

**Comment by SlvrEagle23** [comment] 2017-07-23 15:58
@derkalle4 Honestly I'm a little baffled by this one. I've had sporadic reports of trouble processing certain MP3s from many various users of the system, but I've never been able to reproduce the issues myself, and in this case I still can't seem to put together the necessary conditions to reproduce the issue, even with the specific MP3 files that you sent me.

This will unfortunately take a little time until I can piece together what's happening here, or until I can get the situation to happen on a machine that I can fully debug.

**Comment by derkalle4** [comment] 2017-07-24 05:08
I will retry a complete new installation in case I did something wrong... If the error occurs after that I could still grant you access via teamviewer. But thanks for your help :)

**Comment by SlvrEagle23** [comment] 2017-07-30 01:38
Hello all!

I've made a number of changes to the media screening process that should ease these types of problems. Media that can't be processed won't be moved into "Not Processed"; it will instead use the filename to determine the artist and title if ID3 reading fails for whatever reason. You can still add "non-processed" files to playlists, and thus cue them up in your AutoDJ.

Since this should remove a whole class of issues relating to media being moved to "not processed", I'm going to close this issue. If there are any further issues with media processing, please feel free to start a new issue.

**Closed by SlvrEagle23** 2017-07-30 01:38 UTC
Labels: bug
