### ISSUE TITLE
Issues with AutoDJ After Updating AzuraCast from Version 0.20.2 to 0.20.3

### ISSUE THREAD

**Issue by dxer72** [AzuraCast/AzuraCast#7559] opened 2024-11-18 16:45 UTC
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.20.3

### What happened?

Hello, my AzuraCast is installed on a VPS, and I usually perform updates via an SSH client. My release channel is set to stable. Everything works fine until I update from version 0.20.2 to version 0.20.3. The AutoDJ service seems to go crazy: 1) it interrupts songs with fragments of other tracks or jingles; 2) the skip song button doesn't advance to the next song in the queue but loads a different one instead. 
Currently, I have rebuilt the server to revert to version 0.20.2. I am not an expert in Linux. Could you help me with any scripts or steps needed to resolve this issue? Thank you.
Luigi, from Italy

**Comment by dxer72** [comment] 2024-11-20 09:35
"It seems that the 'Upcoming Song Queue' list is not being considered by the 'Now Playing' service. The 'Playing Next' song on the dashboard never transitions to 'Now Playing'. In this section, songs that are not in the 'Upcoming Song Queue' list appear and play."
[Liquidsoap conf.txt](https://github.com/user-attachments/files/17828260/Liquidsoap.conf.txt)
[Liquidsoap log.txt](https://github.com/user-attachments/files/17828261/Liquidsoap.log.txt)

**Comment by denilsonorfaoaraujo** [comment] 2024-11-21 14:24
> "It seems that the 'Upcoming Song Queue' list is not being considered by the 'Now Playing' service. The 'Playing Next' song on the dashboard never transitions to 'Now Playing'. In this section, songs that are not in the 'Upcoming Song Queue' list appear and play." [Liquidsoap conf.txt](https://github.com/user-attachments/files/17828260/Liquidsoap.conf.txt) [Liquidsoap log.txt](https://github.com/user-attachments/files/17828261/Liquidsoap.log.txt)

The same problem is happening to me. I have 5 stations, and the "now playing" information gets stuck and doesn't update very often. Even after restarting the service, it happens again shortly after. I also use Azuracast on a VPS, and in version 0.20.2 this didn't happen. I had to restore the snapshot.

**Comment by dxer72** [comment] 2024-11-21 16:02
Let’s hope someone will help us with this big problem, which makes the new version unusable.

**Comment by dxer72** [comment] 2024-11-21 16:21
Within my means, I already make my monthly donation. And I am not rushing anyone, haste is not a good idea.

**Comment by BusterNeece** [comment] 2024-11-21 16:31
Currently I have no information on this. Due to the active hostility from the user base on this, I am not working on active development today or likely the rest of this week.

I don't know what's causing it. None of the logs thus far have explained the problem, and I can't reproduce it myself.

Pull requests are welcome from anyone who can help.

**Comment by BusterNeece** [comment] 2024-11-23 19:19
@dxer72 @denilsonorfaoaraujo I'd recommend updating to the latest stable (0.20.4) or the latest Rolling Release. Both have rolled back the scheduler code, and the Rolling Release also incorporates other fixes that bring us to a more stable state. Everything appears to be working quite normally in my local installation.

**Comment by dxer72** [comment] 2024-11-24 08:34
After updating to the stable version 0.20.4, everything works well. Thanks, @BusterNeece !

**Comment by BusterNeece** [comment] 2024-11-24 08:36
Good to hear! Closing this issue for now.

**Closed by BusterNeece** 2024-11-24 08:36 UTC
Labels: needs investigation
