### ISSUE TITLE
Can't Play On Public Page and local stream

### ISSUE THREAD

**Issue by istahilagi** [AzuraCast/AzuraCast#5686] opened 2022-08-20 09:32 UTC
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.17.3

### What happened?

I can't play the radio on the "public page".
I also can't access the "Local Streams" link which is structured like this:
https://hostname/listen/station_29/radio

but if the url is structured like this:
https://hostname/radio/8290/radio
radio can be played.

Please help

### Relevant log output

```shell
[2022-08-11  15:58:02] WARN slave/slave_startup process has 65536 max file descriptor limit
[2022-08-11  16:44:17] WARN slave/slave_startup process has 65536 max file descriptor limit
[2022-08-19  18:04:30] WARN slave/slave_startup process has 65536 max file descriptor limit
```

**Comment by renatopinto89** [comment] 2022-08-20 15:29
Following, because I have the same issue in a couple of stations (Error 401) both on the stream URL and Administration link on the Station Page.
However going to the direct "IP:Port" it works.

**Comment by Ferz0id** [comment] 2022-08-21 06:48
Almost the same thing https://github.com/AzuraCast/AzuraCast/issues/5511

Broken link:
https://edmdnb.com:448/listen/dnb_edm/radio.mp3

Working link:
https://edmdnb.com:8000/radio.mp3

**Comment by JRB-Prod** [comment] 2022-08-21 15:31
@istahilagi Is one of your station URLs like this?
[https://hostname/listen/station_**2**/radio](https://hostname/listen/station_2/radio)

If so, see my comment on this issue: https://github.com/AzuraCast/AzuraCast/issues/5511#issuecomment-1221567089

**Comment by BusterNeece** [comment] 2022-08-22 07:06
The cause of this has been identified and fixed as of the latest Rolling Release version that is currently deploying.

**Closed by BusterNeece** 2022-08-22 07:06 UTC
Labels: needs investigation

**Comment by istahilagi** [comment] 2022-08-22 10:36
I also have another solution while waiting for the new stable release..
create a radio remote without auto dj, fill it with hostname, mount and radio port itself, check "Show on Public Pages".
Then go to the mountpoint menu, edit and uncheck "Show on Public Pages"...
