### ISSUE TITLE
Equal signs in metadata cause incorrect metadata

### ISSUE THREAD

**Issue by pascalla** [AzuraCast/AzuraCast#3582] opened 2020-12-20 13:18 UTC
**Using Docker installation method**
Yes

**AzuraCast version**
 Rolling Release #16a77d5 (2020-12-13 23:31) 

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
Songs with equal signs in them cause the metadata to be incorrect

**To Reproduce**
1. Play a song with an equal sign. (I reccomend https://open.spotify.com/track/6V68ItawQkQlZhYIf1S86C?si=5oAPVMB9RqWs_SlXGlqsEg)
2. Check the "now playing" API.
3. Check blank artist, Title is anything after "="

**Expected behavior**
Metadata comes through correctly

**Relevant Logs**
![image](https://user-images.githubusercontent.com/22846433/102714341-c79edd80-42c5-11eb-858e-e8a00af4b660.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/22846433/102714332-b786fe00-42c5-11eb-8567-43dcb953278a.png)

**Comment by Vaalyn** [comment] 2020-12-21 03:22
Can confirm this issue is caused by Liquidsoap.

This has been reported on their repository and was fixed in the master branch but was not included in LS 1.4.3. I think it will probably included in LS 1.4.4 but this is speculation from my side, would need to check the pre-release.

See https://github.com/savonet/liquidsoap/issues/1340

**Comment by Vaalyn** [comment] 2021-04-20 16:15
Closing this issue als resolved.

Small test with the current AzuraCast version with LS 1.4.4 correctly plays a song with a `=` in the title.

**Closed by Vaalyn** 2021-04-20 16:15 UTC
Labels: bug, upstream
