### ISSUE TITLE
Random songs from folder

### ISSUE THREAD

**Issue by andrewyv** [AzuraCast/AzuraCast#2159] opened 2019-11-21 13:17 UTC
Hello.
I don't want to use the feature of playlist.
I just want to consider the folder where the songs are as a playlist.
So, i read documentation about advanced playlist and liquidsoap.

I added this code in Advanced Custom Configuration
`radio = playlist(mode='randomize',reload=1,reload_mode="rounds","/var/azuracast/stations/radio/media/")`
But when i hit play on AutoDJ Service - START , i get this this error

> Liquidsoap encountered an error
Line 99, char 0:
Warning 4: Unused variable radio
No output defined, nothing to do.
Line 99, char 0:
Warning 4: Unused variable radio
No output defined, nothing to do.

**Comment by CodeSteele** [comment] 2019-11-21 13:57
Possible duplicate of #2154?

**Comment by CodeSteele** [comment] 2019-11-21 13:59
@andrewyv if you could, get us the the Liquidsoap generated configuration (liquidsoap.liq) from the log viewer utility for us.

**Comment by andrewyv** [comment] 2019-11-21 20:39
@CodeSteele i just want to play all the songs from a folder random without creating aditional playlist.
So all songs from /var/azuracast/stations/radio/media/ - i want to play them directly from that directory.
Can i do it somehow? I don't understand the documentaton.

**Comment by SlvrEagle23** [comment] 2019-11-22 22:14
@andrewyv Playlists are how we tell the underlying AutoDJ software what to play and with what settings, so you have to add your media to playlists (even just the default one that we create for you) for the AutoDJ to know that it should play it.

You can go "up" a level from a folder in the media manager, select that folder, then add it to a playlist, and it will add all of the folder's contents to the selected playlist.

**Closed** 2019-11-22 22:15 UTC
Labels: question
